### ISSUE TITLE
isPedantic is conflict with fallback field in metadata

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#1002]
when `await api.query.staking.lastEraLengthChange.at(blockHash)` i have this error :
```
Unable to decode storage staking.lastEraLengthChange: Encoding for input doesn't match output, created 0x0000000000000000 from 0x
```
it's fine without `at()` which go through the subscription path.

the return of state query is null, but since in metadata there's a fallback for LastEraLengthChange.
```
{
              "name": "LastEraLengthChange",
              "modifier": "Default",
              "type": {
                "PlainType": "BlockNumber"
              },
              "fallback": "0x0000000000000000",
              "documentation": [
                " The session index at which the era length last changed."
              ]
            },
```
should not throw but use the fallback. Turn out in `packages/rpc-core/src/index.ts#241` isPedantic is passed as true.

I guess the solution would be to check `meta.fallback` and pass isPedantic false if fallback exists.

**Comment by ianhe8x** [comment]
i don't know the whole story behind `isPedantic`, my fix works though i realized that Type.Fallback is for Type not value.

**Comment by jacogr** [comment]
Seems like at has a bug. The fallback should apply even for at, and currently it would seem that it doesn't. (Just based on this report - if it did encoded would match)

So `isPedantic` actually makes us determine if the structures we have, actually match with the expected encoded length. A recent example - https://github.com/polkadot-js/api/pull/985 - only picked that up since we started failing and the realized the fields have changed.

**Comment by jacogr** [comment]
Both these tests should pass (added to api/test/e2e/promise-queries.ts as a test) - only the first does, the second doesn't apply the fallback (and fails with the above issue) -

```js
  it('allows retrieval of an fallback entry (once-off query)', async () => {
    const nonce = await api.query.system.accountNonce('5DSo5RVtfrtgHoz2c7jK7Tca7FgJgpCzFnxoRVDeYUQcKPng');

    expect(nonce.toHex()).toEqual('0x0000000000000000');
  });

  it('allows retrieval of fallback when at query is made', async () => {
    const header = await api.rpc.chain.getHeader() as Header;
    const nonce = await api.query.system.accountNonce.at(header.hash, '5DSo5RVtfrtgHoz2c7jK7Tca7FgJgpCzFnxoRVDeYUQcKPng');

    expect(nonce.toHex()).toEqual('0x0000000000000000');
  });
```
