### ISSUE TITLE
Add correct typings for api.rpc.*.*

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1009]
Same thing as in #987, for `api.rpc.*.*`

This is different from #714, since these can be inferred in-editor.

**Comment by jacogr** [comment]
Marked refactor, since I believe we should probably just get rid of the string way of specifying these and directly use types. (The parsing an generation doesn't add any benefit, being explicit here would just solve all the issues)

```js
function getHeader (hash?: Hash | string): Header {
... do whatever
}
```

**Comment by amaurymartiny** [comment]
+1 for functions.

> The value the strings does add however - it allow inspection down the tree, e.g. in apps where the actual args types are used to construct the calls dynamically. (Along the same lines as metadata queries). Not 100% sure how to inject those with the above approach.

Can't we use .toRawType() for that?

**Comment by jacogr** [comment]
We can, but not on a function. Or rather, need to know -

- the output type, create it and then perform toRaw on it
- the input types, create it, and then toRaw it

So worth case, which is a bit of duplication

```js
type RpcMethod = {
  args: Array<{ name: string, type: string, isOptional?: boolean }>,
  documentation: Array<string>,
  type: string
}

function getHeader (hash?: Hash | string): Header {
... do whatever
}

(getHeader as RpcMethod).documentation = ['do whatever'];
(getHeader as RpcMethod).args = [{ name: 'hash', type: 'Hash', isOptional: true }];
(getHeader as RpcMethod).type = 'Header';
```

This does mean we duplicate somewhat - one for the typing bits, once for the human-readable version. This metadata-like info is useful.
