### ISSUE TITLE
new Keyring error .

### ISSUE THREAD

**Issue by beykery** [polkadot-js/api#1033]
const keyring = new Keyring({type: 'sr25519'});
  let key = keyring.addFromMnemonic(mnemonic);
  console(key);

error occur bellow ：

ExtError: @polkadot/wasm-crypto has not been initialized

why?

**Comment by jacogr** [comment]
The keyring relies on sr25519, which is only available via WASM and this is initialized async. So either -

- if used alongside the API, call `Api.create` first before constructing the keyring - the API init is async anyway, so it also does the crypto init
- If used stand-alone, you need to explicitly init the crypto before the new, i.e

```js
import { cryptoWaitReady } from '@polkadot/util-crypto';

await cryptoWaitReady();
const keyring = new Keyring({type: 'sr25519'});
```

**Comment by beykery** [comment]
it work , thank you 。
