### ISSUE TITLE
Acomodate 2.x (alongside 1.x) Vote interfaces

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#1034]
Intially from https://github.com/polkadot-js/apps/issues/1315

The 2.x `democracy.vote` doe not take a `i8` anymore, but rather a `Vote` (alongside a conviction). https://github.com/paritytech/substrate/blob/master/srml/democracy/src/lib.rs#L145

This has a specific encoding and decoding override for a compact encoding.

**Comment by jacogr** [comment]
This one could be problematic, i.e. the Vote is encoded differently - unlike decoding, it is not clear how to handle different params on creation. Options -

- Just treat it as a byte, i.e. pass already encoding
- For the above, could expose encoding features on the class, but caller takes care
- Pass in additional version into constructor (which means this is not default anymore, however could be done optionally)

**Comment by amaurymartiny** [comment]
Closed in #1061
