### ISSUE TITLE
One-shot storage queries should use `getStorage` instead of `subscribeStorage`

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1039]
In decorateStorageEntry:

https://github.com/polkadot-js/api/blob/aed73e2bb3d395d4210e193f996b19bcfab0ee91/packages/api/src/Base.ts#L585

so right now:
```javascript
const api = new ApiPromise();
await api.query.system.accountNonce(addr1); // uses subscribeStorage, with immediate unsubscribe after resolve
```

Expected: uses `state_getStorage`.

Edit: same for multi

**Comment by jacogr** [comment]
Agreed with the `getStorage` for single-shot (we had it that way, I think with the Rx/Promise combination is was dropped for the sake of simplicity). However that doesn't cater for multiple keys, so in that case either -

- subscribe/unsubscribe (current)
- log a feature request with substrate
