### ISSUE TITLE
props for derive.staking.info not updated

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#1060]
An issue appeared in `apps` and is related to `derive.staking.info`. Updates are not pushed through the props, so that the info don't update unless the page is reloaded.

I've tracked down the issue and it happens since v0.82 https://github.com/polkadot-js/api/pull/987

How to reproduce:
- navigate to staking>actions
- change the reward destination
- once the tx succeeds, the reward destination isn't updated
- refresh the page or change tab and get back -> the destination is updated.

**Comment by Tbaut** [comment]
I noticed the same behaviour for `derive.democracy.referendums`

**Comment by jacogr** [comment]
Weird on referendums, it was working for me up till a couple of days ago. Something is weird.
