### ISSUE TITLE
Add storage test to promise-queries.spec.ts

### ISSUE THREAD

**Issue by axelchalon** [polkadot-js/api#1070]
I removed the following test from `@polkadot/api/test/e2e/promise-queries.spec.ts` in https://github.com/polkadot-js/api/pull/1066, because the test used `existentialDeposit` to test the storage with a well-known value. However, `existentialDeposit` has since been moved to `consts`. The test needs to be rewritten to use another storage.

```js
describe('with plain type', () => {
    const EXISTENTIAL_DEPOSIT = 500;
    it('queries correct value', async () => {
      const existentialDeposit = await api.query.balances.existentialDeposit() as Balance;

      expect(existentialDeposit.toNumber()).toEqual(EXISTENTIAL_DEPOSIT);
    });

    it('queries correct value at a specified block', async () => {
      const header = await api.rpc.chain.getHeader() as Header;
      const existentialDepositAt = await api.query.balances.existentialDeposit.at(header.hash) as Balance;

      expect(existentialDepositAt.toNumber()).toEqual(EXISTENTIAL_DEPOSIT);
    });

    it('subscribes to query and get correct result', (done) => {
      return api.query.balances.existentialDeposit((existentialDeposit: Balance) => {
        expect(existentialDeposit.toNumber()).toEqual(EXISTENTIAL_DEPOSIT);
        done();
      });
    });

    it('queries correct hash', async () => {
      const hash = await api.query.balances.existentialDeposit.hash();

      expect(hash).toBeDefined();
    });

    it('gets correct key', async () => {
      const key = api.query.balances.existentialDeposit.key();
      const existentialDepositData = await api.rpc.state.getStorage(key) as Option<any>;
      const existentialDepositRPC = new Balance(existentialDepositData.unwrapOr(undefined));

      expect(existentialDepositRPC.toNumber()).toEqual(EXISTENTIAL_DEPOSIT);
    });

    it('queries correct size', async () => {
      const size = await api.query.balances.existentialDeposit.size();

      expect(size.toNumber()).not.toEqual(0);
    });
  });
```

**Comment by amaurymartiny** [comment]
Putting P1, as these tests help a lot in whether the PRs we make are correct or not. I would love to see them back in master asap, it just doesn't feel right to remove tests

**Comment by axelchalon** [comment]
I added the test back in my branch as I think Stefie's backward-compatibility PR (previously https://github.com/polkadot-js/api/pull/1068) will make the test continue to work
cc @Stefie

**Comment by Stefie** [comment]
#1068  is mainly for the api.derive methods, but I fixed them in a separate branch. Since there are not many constants in the storage anymore, I just switched to `SessionIndex`. https://github.com/polkadot-js/api/pull/1072

I'll open a new branch for the derive methods, rolling back the merge of #1068 with #1066  was too much of a hassle...
