### ISSUE TITLE
Error when add custom @polkadot/types in Nuxt/Vue app

### ISSUE THREAD

**Issue by enfipy** [polkadot-js/api#1073]
I'm setting up a Nuxt.js app with @polkadot-js. When I do request to custom substrate runtime module with my @polkadot/types - I'm getting this error `Class constructor Struct cannot be invoked without 'new'`.

This is for a Nuxt.js app with official setup of typescript. In the past, I've tried to setup it with clean Nuxt.js and Vue but always the same error. Only if I setup clean NodeJS (with or without typescript) or with @polkadot react apps - it works well.

I've created a [repository](https://github.com/enfipy/substample) to try some other ways.

API call:

```javascript
class VecU32 extends Vector.with(u32) {}
class Kind extends Struct {
  constructor(value) {
    super({
        stuff: VecU32
    }, value);
  }
}

const Alice = "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY";

const provider = new WsProvider("ws://127.0.0.1:9944");
const typeRegistry = getTypeRegistry();
typeRegistry.register({ Kind });
const api = await ApiPromise.create(provider);
// With types provided in create function - works well
// types: {
//   Kind: {
//     stuff: "Vec<u32>"
//   }
// }
const res = await api.query.template.kinds(Alice);
console.log(res);
```

I expect empty (or some values, depending on what is in the blockchain) result output, but the actual output is the error, `Class constructor Struct cannot be invoked without 'new'`.

P.S: If I add types as objects (see comment in the code example) - everything okay, but 2 problems with it: 1) I need to create javascript classes again; 2) I didn't find any methods to add Enums in that way

**Comment by jacogr** [comment]
Sorry for the wait and no response here - will pull things down and take a look. (The repo helps a lot here, thank you very much for the effort)
