### ISSUE TITLE
.multi is returning a "Codec[]" in .then instead of unsub function

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#1086]
Pseudo code:
```js
let unsub: Function | undefined;

api.query.balances.balanceOf
  .multi(addresses)
  .then((_usub) => unsub = _unsub);
```

Here `_usub` is of type `Codec[]` and is not assignable to type `Function`.

In case it can be any usefull, an example implementation can be found [here](https://github.com/Tbaut/basic-substrate-ui-template/blob/one-account/src/Balances.tsx#L27).

**Comment by jacogr** [comment]
Ok, I typed up this - 

```js
  // check multi for unsub
  const multiUnsub = await api.queryMulti([
    [api.query.system.accountNonce, keyring.eve.address],
    [api.query.system.accountNonce, keyring.bob.address]
  ], (balances) => {
    console.log('balances', balances);

    multiUnsub();
  });
```

So it works the same way as a normal query with callback.
