### ISSUE TITLE
Transform AccountId -> SS58

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#109]
e.g. in the case of storage, we don't currently do the transform 100% - there really should be no need to call transform on the value (e.g. `encodeAddress` in this case), it should just be done for you in the API.

```js
// TODO We should unsubscribe from subscriptions
  subscribeProposals () {
    const { api } = this.props;
    const key = createStorageKey(method)();
    const transform = storageTransform(method);

    api.state
      .getStorage(key)
      .subscribe((value) => {
        this.setState({
          proposals: (transform(value, 0) as any[])
          .reduce((proposals, [propIdx, proposal, accountId]) => {
            const address = encodeAddress(accountId);

            if (!proposals[address]) {
              proposals[address] = [propIdx];
            } else {
              proposals[address].push(propIdx);
            }

            return proposals;
          }, {})
        });
      });
  }
```

(The above from the apps/example/tut-003)

It means we would need to pass the actual un-encoded key to the method and use that in the deconstruction. So the call could become `getStorage(storage.staking.public.freeBalanceOf, <params>).subscribe(...)`

Needs some thinking around the auto-generation, i.e. how do we specify these types to make it "just happen".

**Comment by jacogr** [comment]
The same happens with e.g. Balances, i.e.

https://github.com/polkadot-js/apps/pull/129/files#diff-f4e153119ebcf3e652c624e3d01f6a44R33

**Comment by ltfschoen** [comment]
WIP PR created in polkadot-js/common here https://github.com/polkadot-js/common/pull/170

**Comment by jacogr** [comment]
Closed, currently AccountIndexx encodes and decodes properly
