### ISSUE TITLE
api.queryMulti should cache values

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1092]
```javascript
api.queryMulti([
  [api.query.session.nextKeyFor, controllerId],
  [api.query.staking.ledger, controllerId],
], callback)
```

First result: [something1, something2],

**Expected:** 

second result: [something1, something3]

**Actual:**

second result: [null, something3]

**Comment by jacogr** [comment]
Marking a bug since it is actually existing stable functionality.
