### ISSUE TITLE
Add derives for SetIndex in Elections.

### ISSUE THREAD

**Issue by jnaviask** [polkadot-js/api#1118]
Elections now uses chunking for approvals and voters (see: https://github.com/paritytech/substrate/blob/master/srml/elections/src/lib.rs#L243). It would be useful to have a set of derives that let the caller "just get everything" without worrying about the chunking. There is already an internal function that does this (https://github.com/paritytech/substrate/blob/master/srml/elections/src/lib.rs#L1047) but no way to access it via RPC.

The derive would also be useful if it converted ApprovalFlag to booleans, as seen here: https://github.com/paritytech/substrate/blob/master/srml/elections/src/lib.rs#L1030

Thanks!

**Comment by jacogr** [comment]
Apps would also need this, need top get it in ASAP since it helps a lot with the substrate 2.x support.

cc @kwingram25

**Comment by jnaviask** [comment]
Been rewriting the client code and came up with some other derives that may be important:

- accessing the global voter slot via `voter_at()`: https://github.com/paritytech/substrate/blob/master/srml/elections/src/lib.rs#L943
- accessing the decayed/effective stake via `get_offset()`: https://github.com/paritytech/substrate/blob/master/srml/elections/src/lib.rs#L1083
