### ISSUE TITLE
Links to detail type class pages broken

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/api#1155]
The automatic link generation to the detail pages of the type classes is broken.
It was working at one point with that syntax, so something in the config or vuepress must have changed.

Every thing written like this `[[TYPE]]` should be a generated link to the detail page.

https://polkadot.js.org/api/types/

**Comment by jacogr** [comment]
This may be worse now. Since all "classes" as part of the runtime is now "interfaces". So with the links working, we may have other issues...
