### ISSUE TITLE
Convert all e2e tests to use describeE2E & fix broken/ outdated tests

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/api#1157]
Addresses "Fix broken / outdated tests" of https://github.com/polkadot-js/api/issues/908

Convert all e2e tests to use describeE2E as introduced in https://github.com/polkadot-js/api/pull/1117: 

These tests should pass without errors/ warnings:
`$ yarn run test:e2e-docker`
`$ yarn run test:e2e-remote`

Files that need fixing in `packages/api/test/e2e`:

`/api/`
- [ ] ( promise-alex-archive.spec.ts ??)
- [x] promise-alex.spec.ts
- [x] promise-consts.spec.ts
- [x] promise-contract.spec.ts
- [x] promise-queries-dev.spec.ts _(see known failing tests)_
- [x] promise-queries-doubleMap.spec.ts
- [x] promise-queries.spec.ts _(see known failing tests)_
- [ ] promise-tx-era.spec.ts
- [x] promise-tx-signer.spec.ts _(see known failing tests)_
- [x] promise-tx.spec.ts _(see known failing tests)_
- [x] rx-queries-dev.spec.ts
- [x] rx-queries.spec.ts
- [ ] rx-tx.spec.ts

`/api-derive/`
- [ ] promise-dev.spec.ts
- [ ] promise.spec.ts
- [ ] rx-dev.spec.ts
- [ ] rx.spec.ts

`/rpc-core/`
- [x] alexander.spec.ts
- [x] basics.spec.ts
- [x] chain.spec.ts
- [x] state.spec.ts
- [x] child-storage.spec.ts
- [x] subscribe.spec.ts

**Comment by jacogr** [comment]
Closing as stale. We will probably remove all the e2e tests soon since they are not being maintained and is currently just an area of code rot.
