### ISSUE TITLE
Substrate 2.0: api.tx.system.setCode() nor working with larger code examples

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/api#1172]
When trying to call `api.tx.system.setCode()` with a large code example (eb 262146 or 131072 bytes),  the transaction starts is return `Finalized`, but the extrinsic fails:
` {"ApplyExtrinsic":2} : system.ExtrinsicFailed []`

This happens both wrapped in an democracy proposal or called directly via sudo.
<img width="1391" alt="Screenshot 2019-07-24 at 11 10 05" src="https://user-images.githubusercontent.com/125398/61781915-773bfb80-ae05-11e9-96f5-a31089d13857.png">

The behaviour can be reproduced by uploading this file (262146 bytes) https://github.com/polkadot-js/api/blob/b1b4530bf13ab6ef2480e42ac0b71bde14a0e707/packages/api/test/mock-data/randomAsHexRaw in the PolkadotJS UI https://polkadot.js.org/apps/#/democracy/propose

or by running this test https://github.com/polkadot-js/api/blob/b1b4530bf13ab6ef2480e42ac0b71bde14a0e707/packages/api/test/e2e/api/promise-tx.spec.ts#L112

Both the UI and the e2e tests are working fine with smaller code examples.

**Comment by jacogr** [comment]
Closing. The issue was substrate-related. (There are some jest timeouts, but for these would just have to adjust around them when found)
