### ISSUE TITLE
Add e2e tests for DoubleMap

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#1174]
Can use this - https://github.com/polkadot-js/api/pull/1171/files#diff-a60854aee74a1ede6dc8edf6544d4240R1404

- set key
- query to see if it has changed in the map

**Comment by jacogr** [comment]
Actually need normal mock-tests for these as well, data can be pulled from the e2e as working

**Comment by Stefie** [comment]
There is https://github.com/polkadot-js/api/blob/master/packages/api/test/e2e/api/promise-queries-doubleMap.spec.ts

**Comment by jacogr** [comment]
Cool!

Ok, so the session NextKeys seem to fail and always return `null`, so clueless at this point. (Could be a construction issue)

**Comment by Stefie** [comment]
I primarily just moved them from here as a first step https://github.com/polkadot-js/api/blob/9b15a373d3003066610e09fddd013d7e8235e873/packages/api/test/e2e/promise-queries.spec.ts#L322

I think there are quite a few tests that could need some refinement, but I'm still focusing on making what's there work again as a first step.

**Comment by jacogr** [comment]
Yes, not blaming you - it is what it is atm :) 

Just pointing out that with those, we are not sure it actually works. (i.e. first time actually using DoubleMap in apps and well, there are "some" issues, which could be Problem-Between-Keyboard-and-Couch as well)
