### ISSUE TITLE
`ClassOf<T>('SomeType')` should not require the `<T>`

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1177]
**Expected:**

```typescript
const g = createType('Gas', 1234);
g.ad... // should autocomplete because it's a BN
```

**Actual:**

Doesn't autocomplete. We need to do the following:

```typescript
import { Gas } from '@polkadot/types/smrl/types';

const g = createType<Gas>('Gas', 1234);
g.ad... // autocompletes correctly
```

which is okay for 1 or 2 types, but gets really redundant for more, since we're really typing the same word twice

**Solution:**

The idea is to create an `InterfaceRegistry`, empty at first, and the script `srmlTs.ts` populates `InterfaceRegistry` with the types it finds, via module augmentation.

- Step 1. Create `InterfaceRegistry`. The keys are strings with represent the srml type (like 'Gas'), and the values are the actual interface (like `Gas` in `types/smrl/contracts/types`).

```typescript
// in `@polkadot/types/smrl/types.ts`

export interface InterfaceRegistry {
  // empty at first
}
```

- Step 2. Modify `srmlTs.ts` to populate `InterfaceRegistry` via module augmentation. For example, for gas, the script would output in `types/srml/contract/types.ts`:

```typescript
declare module '@polkadot/types/srml/types' {
  interface InterfaceRegistry {
    Gas: Gas // maps the key "Gas" to the interface `Gas`
  }
}
```

- Step 3. In `ClassOf`:
    - if we're calling `const a = createType<SomeOtherType>('Gas', 1234)`, then `a` should be of type `SomeOtherType` (overridden by user)
    - if we're calling `const a = createType('Gas', 1234)`, then `ClassOf` should check if `InterfaceRegistry['Gas']` is present, if yes, take it, if no, return `Codec`

I'm not 100% this will actually work, so needs some exploration first.

**Comment by jacogr** [comment]
This does work as well...

```js
const a: Gas = createType('Gas', 1234);
```

(Also if you assign a value into an interface)

**Comment by amaurymartiny** [comment]
But again, 1/ you need to import Gas and 2/ you type Gas twice.

**Comment by jacogr** [comment]
Yes, not disputing the fact that it still sucks :)
