### ISSUE TITLE
Expose definition to interface creation script

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#1223]
Should be runnable to any package user via cli, pointing to a definitions folder

**Comment by amaurymartiny** [comment]
I would suggest creating a `packages/interfaces-ts` package just for this cli. Right now everything's in `packages/types/scripts/interfacesTs.ts`, and it's getting messy. This script could be cleaned up a bit with a nice folder structure.

**Comment by jacogr** [comment]
Closing. Sure there are more specifics, they should be logged separately.
