### ISSUE TITLE
Unify type signatures for primitive types

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1224]
Codec types can be left as-is, but for all primitive types, i would propose this signature for the constructor:
```typescript
class MyType {
  constructor (value: AnyValue, options: Options) { ... }
}
```

This will allow `createType()` to be recursively called, without needing to worry about type signatures of nested types.

Options will for example hold: `metadata,networkId,typeRegistry,extrinsicVersion,runtimeVersion,createType (i.e. a ref to the function itself)`

**Comment by jacogr** [comment]
Closing.

- `createType` allows for nested, out of order and recursive structures (since around 0.92)
- `Registry` is now passed through as the execution context for all types
