### ISSUE TITLE
Disconnection from WebSockets

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/api#1236]
I'm testing out the master version of Polkadot and when I try to connect to the node with WebSockets (either using `@polkadot/api` directly or using `apps`) I get a disconnect:

```
<snip>
2019-07-30 16:05:30          API-WS: disconnected from wss://127.0.0.1:9944 code: '1006' reason: 'connection failed'
2019-07-30 16:05:31          API-WS: disconnected from wss://127.0.0.1:9944 code: '1006' reason: 'connection failed'
<snip>
```

The node prints out:

```
<snip>
Encountered an error: Unable to parse HTTP: Invalid byte where token is required.
Enable a logger to see more information.
Encountered an error: Unable to parse HTTP: Invalid byte where token is required.
Enable a logger to see more information.
<snip>
```

I assume its a discrepancy between the recent master version of `polkadot` and the latest version of the JS libraries. I was testing against a node with the same libraries and the same version of master before without an error. 

Any thoughts on the issue?

**Comment by jacogr** [comment]
There has been no changes on the WS layer with substrate 2.x. 

(However a lot of changes with metadata, types, etc. - for that need to use one of the beta versions, i.e. `0.90.0-beta.x`, the 0.81.1 stable release does not have any of this and will fail against master. But not due to the above issue)

**Comment by ianhe8x** [comment]
i think the local node use `ws` not `wss`

**Comment by jacogr** [comment]
Erm... yes, @ianhe8x is right - local is always WS. I completely missed that. (To run with wss you need to deploy a secure proxy in-front of the node)

**Comment by jacogr** [comment]
Verified against polkadot master, it is . def. a local issue. Make sure you are connecting to `ws://127.0.0.1:9944/` (not `wss`, unless you have a secure proxy in front of the node).
