### ISSUE TITLE
When i run example ,there has an error!!!

### ISSUE THREAD

**Issue by ruanqunfeng** [polkadot-js/api#1247]
![image](https://user-images.githubusercontent.com/15098545/62277309-76940c80-b478-11e9-8a11-895819d112e3.png)

**Comment by jacogr** [comment]
You are trying to connect to a substrate 2.x chain. If you are using master, you are advised to use the `@polkadot/api` `-beta` versions (master is still undergoing rapid changes daily, so there has been . no "stable" point release for 2.x support)

Install via `yarn @polkadot/api@beta` (`0.90.0-beta.12` as of this writing)
