### ISSUE TITLE
Allow customize ExtrinsicImpl in Extrinsic

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#1345]
`primitive/Extrinsic/Extrinsic.ts` is a nice structured `VersionedExtrinsic`, which is very handy if i can reuse and let my own Extrinsic Impl work with it. The problem I have is it doesn't get ExtrinsicImpl from typeRegistry.

**Comment by jacogr** [comment]
Why not override Extrinsic itself in a custom case? (Which is what is in the registry). The whole ExtrinsicV1 bundle is quite tied with payload and signature. 

Would obviously want to make extension easy, but these have very specific meaning/logic and is a currently almost an implementation detail of the registered “GenericExttinsic’

**Comment by ianhe8x** [comment]
You are right. I raise this only because this versioned abstraction is nice and i will copy most of it in my custom extrinsic. I will close the ticket.

**Comment by jacogr** [comment]
No, I'm not thinking it is a bad idea, I'm just trying to understand what is the best approach here.

So if I had to do my own right at this point, I would probably make it version 64 and get it to operate in the same structure, so there allowing the Generic to use registered versions, makes sense.

**Comment by ianhe8x** [comment]
The reason is because we also will have ExtrinsicV1, ExtrinsicV2, one for our network which derived from substrate v1, the other for network derived from substrate v2. (we are upgrading and trying to migrate seamlessly to v2 at the moment)
They shared version number 1/2 but all have extra logic. ( and we make the customization backward compatible, if the extra feature is not used, they encode/decode exactly same as Buildin Impl)

**Comment by ianhe8x** [comment]
Actually, the changes i made in my PR doesn't totally solve my problem. I will need to access version in ExtrinsicImpl
```
const BIT_UNSIGNED = 0;
const BIT_VERSION = 0b0000001;
const BIT_DOUGHNUT = 0b01000000;
const BIT_FEE_EXCHANGE = 0b00100000;
```
this is the mask we have for extrinsic version. we use it to indicate if certain feature is enabled.

**Comment by jacogr** [comment]
Closing this one based on #1348, #1349 & #1350
