### ISSUE TITLE
Lazy create Submittable

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#1368]
When using custom extrinsic, got an error `1010: Invalid Transaction (-20)`.

After some debugging, it is because of Submittable extends original Extrinsic not the customized impl, then in `Extrinsic.ts:55` where it should pass the if check it fails. (value is a Submittable)

**Comment by ianhe8x** [comment]
Before the Submittable refactor, it is constructed when decorating extrinsics, when all customized types are already injected.

**Comment by jacogr** [comment]
This is a weird one, since I actually tested that specific case with the apps ui and custom injected extrinsics (actually overwrite Extrinsic to ExtrinsicUnknown), i.e. comment here - https://github.com/polkadot-js/api/pull/1350

**Comment by jacogr** [comment]
Closed in #1370
