### ISSUE TITLE
Custom and non-standard extrinsic formats

### ISSUE THREAD

**Issue by fubuloubu** [polkadot-js/api#1427]
In extrinsics v3, the API adds the tip to to the transaction, however a chain that does not have the balances module doesn't expect the tip in the payload so it will barf on handling it with the following error:
```
ERROR: Error: "submitAndWatchExtrinsic (extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime! (Client(Exe)"
```

You would need to implement your own payload format for the chain in the PolkadotJS API that doesn't include the tip.

**Comment by jacogr** [comment]
Documentation update PR incoming that will explain . the SignedExtensions, what is it used for and how it actually changed both the extrinsic sent and the extrinsic payload being signed. Additional with an explanation of how to provide your own should you wish to have a non-standard implementation.

**Comment by jacogr** [comment]
Closes with https://polkadot.js.org/api/start/extrinsic.extend.html
