### ISSUE TITLE
Allow for a completely offline API

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1461]
It would be good to have a completely offline `api` object, for example to do offline extrinsics creation.

Requirements: 
- the metadata, genesisHash, blockNumber etc are retrieved by an external party, and can be inputs to the offline `api` object.
- no WsProvider at all, a.k.a completely offline

Output:
- be able to create an extrinsic, ready to be broadcasted to the network

---

### Possible hack today (it's a hack, not recommended)

Today, the solution to this is hacky: we use the `injectMethods` which will populate a global singleton object:

```typescript
import Call from '@polkadot/types/primitive/Generic/Call';
Call.injectMethods(extrinsics);
```

This is hacky, and we want to remove it: https://github.com/polkadot-js/api/issues/580. But with this hack we can

```typescript
createType('Extrinsic', someValue, { version: 3});
```

---

### Possible solutions:

- `new Api({ metadata })` will not create a WsProvider, and will decorate based on inputted metadata. 
    - `api.query.balances.freeBalance().then()` could just fail.
    - `api.query.balances.transfer(...).sign(...)` here we pass in blockNumber, genesisHash, specVersion here, will return a ready-to-be-broadcasted tx.
- `createType('Type', value, { metadata, extrinsicVersion, otherParams... })`
    - needs Type signature unification: https://github.com/polkadot-js/api/issues/1224
- instead of decorating `api`, we could decorate `Metadata`?
    - `metadata.query.balances.freebalance(...); // returns a StorageKey`
    -  `metadata` can be offline, and `api` is just a wrapper of promise/rx + provider around `metadata`

**Comment by jacogr** [comment]
Ok, so this still does not solve the actual problem - what are the actual full end-to-end requirements here that are not catered for with the signer interface and the hooks.

So effectively, I'm getting bits and pieces of information here and not body actually comes 100% clear on the actual requirements.

1. "genesisHash, blockNumber etc are retrieved by an external party" what does this mean? 
2. What does broadcast mean in this case? Does that use the API?
3. How are the signatures generated an injected (which is very heavily biased towards the signer, e.g. https://github.com/polkadot-js/api/issues/1421#issuecomment-540545590)

I don't believe #1463 solves the "API works offline" - it addresses one part, creating stuff via metadata. (So would swap that to "addresses part of")

**Comment by Wangmmx** [comment]
I have solved the offline signing problem today with the help of @jacogr 
thanks a lot!
and the following is my code:


`const Alice = keyring.getPair('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY');
const tx = api.tx.balances.transfer('5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY', 12345678);
const nonce = await api.query.system.accountNonce('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY');

// create the payload
const signer = api.createType('SignerPayload', {
  method: tx,
  nonce,
  genesisHash: api.genesisHash,
  blockHash: api.genesisHash,
  runtimeVersion: api.runtimeVersion,
  version: api.extrinsicVersion
});

const { signature } = api.createType('ExtrinsicPayload', signer.toPayload(), { version: api.extrinsicVersion }).sign(Alice);

tx.addSignature(Alice.address, signature, signer.toPayload());

try {
  console.log(await tx.send());
} catch (error) {
  console.error(error);
}`

I really appreciate it!

**Comment by jacogr** [comment]
We are mixing up stuff here - creating and extrinsic is not the same as signing and extrinsic. So for instance, allowing the combination of api-metadata & metadata caters for the creation. Signing has got nothing to do with the metadata, blockNumber, era & (!!!) keyring.

So from a user POV, I still don't get the flow at all.

- where does the metadata come from
- where does the blockHash, genesisHash come from
- where is this generated
- where is the tx generated
- where are these combined
- where are these transferred

We should not continue patching around this stuff until it makes 100% sense as to what people are trying . to do and what the API does not do with the signing capabilities. (Which allows you to move the signing completely out-of-process already)

**Comment by jacogr** [comment]
@Wangmmx That code should not have been written. So trying to unpack here where the API falls short and exactly the flow that people expect, but are not getting. So really would like a walk-through from people having these requirements to explicitly state -

- where do they expect to generate the transaction
- where do they expect to be able to generate the signature (and where this info comes from)
- where do they expect . to transmit the transaction

Need to look at this properly so (a) devs don't need to do low-level and complicated stuff (like above) & (b) can actually get to their aims.

**Comment by Wangmmx** [comment]
> @Wangmmx That code should not have been written. So trying to unpack here where the API falls short and exactly the flow that people expect, but are not getting. So really would like a walk-through from people having these requirements to explicitly state -
> 
> * where do they expect to generate the transaction
> * where do they expect to be able to generate the signature (and where this info comes from)
> * where do they expect . to transmit the transaction
> 
> Need to look at this properly so (a) devs don't need to do low-level and complicated stuff (like above) & (b) can actually get to their aims.

Ok, I tried to write it.

First of all, this is the step of sending an offline transaction.
```
1.create transaction
2.create SignerPayload
3.create ExtrinsicPayload
4.sign ExtrinsicPayload
5.inject data (address, sigHex, singerPayload)
6.send
```

For each step, I make the following explanation

1.create transaction
transaction is an object created  from api.tx.balances.transfer(toAddress, amount);
the type of transaction is a class named Submittable, you can see details in https://github.com/polkadot-js/api/blob/ad4a6e63ce890d875a29eebf93c6df373962849d/packages/api/src/submittable/Submittable.ts
code:
`  const transaction = api.tx.balances.transfer(to, amount);`

2.create SignerPayload
if you want to know the txBody to sign,  The body is a signerPayload,  it looks like this
https://github.com/polkadot-js/api/blob/630b8318c0251fe59ea2c34a2c9694524fa93c09/packages/types/src/primitive/Extrinsic/SignerPayload.ts
code:
```
 const signer = createType('SignerPayload', {
        address: address,
        blockHash: blockHash,
        blockNumber: blockNumber,
        era: era,
        genesisHash: genesisHash,
        method: transaction,
        nonce: nonce,
        runtimeVersion: runtimeVersion,
        tip: tip,
        version: version
        // method: tx,
        // nonce,
        // genesisHash: api.genesisHash,
        // blockHash: api.genesisHash,
        // runtimeVersion: api.runtimeVersion,
        // version: api.extrinsicVersion
    });
```
This has a similar application. You can see how each parameter comes from.
https://github.com/polkadot-js/api/blob/00d86011a75eb99119d8085b13d474760d134dda/packages/api/test/e2e/api/promise-tx-eras.spec.ts
I also listed some of them:
nonce: api.query.system.accountNonce(address);
genesisHash: api.genesisHash;
runtimeVersion: api.runtimeVersion;
version: api.extrinsicVersion;

3.create ExtrinsicPayload
ExtrinsicPayload is another payload type, it is similar to signerPayload, but has some different parameters.it looks like this
https://github.com/polkadot-js/api/blob/master/packages/types/src/primitive/Extrinsic/v3/ExtrinsicPayload.ts
code:
```
const ExtrinsicPayload = createType('ExtrinsicPayload', signerPayload.toPayload(), { version: api.extrinsicVersion })
```

4.sign ExtrinsicPayload
after creating ExtrinsicPayload, you need to sign it with pair to get the signature
code
`const {signature} = ExtrinsicPayload.sign(pair) `

5.inject data (address, sigHex, singerPayload)
`transaction.addSignature(fromAddress, signature, signer.toPayload());`

6.send
` const hash = await transcation.send();`

All the steps have been completed, maybe I didn't write it very well, but this is what I can understand.

**Comment by mzolkiewski** [comment]
> @Wangmmx That code should not have been written. So trying to unpack here where the API falls short and exactly the flow that people expect, but are not getting. So really would like a walk-through from people having these requirements to explicitly state -
> 
> * where do they expect to generate the transaction
> * where do they expect to be able to generate the signature (and where this info comes from)
> * where do they expect . to transmit the transaction
> 
> Need to look at this properly so (a) devs don't need to do low-level and complicated stuff (like above) & (b) can actually get to their aims.

I'm looking for that functionality as well. From my side, I would like something similar to https://www.myetherwallet.com/interface/send-offline
So ideally, there would be a way for regular users to easily generate and serialize signed transactions that could be shared or stored for later and published to the blockchain by anyone.

**Comment by jacogr** [comment]
And the API allows for exactly that, see for instance https://github.com/polkadot-js/tools/tree/master/packages/signer-cli which is an implementation of an offline signer.

(There is also a tool developed by @amaurymartiny https://github.com/amaurymartiny/txwrapper)

I am closing this, since the API implements all the required functionality to allow for generating txs.
