### ISSUE TITLE
Fail transfering DOTs

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/api#147]
I am using the following code to send DOTs from Alice to Bob:
https://gist.github.com/chevdor/aed62310878042c81f8e71f9e13e7511

It fails with the following error:
```
ExtError: submitExtrinsic (extrinsic: Bytes): Hash:: [1001]: Extrinsic has invalid format.
```

**Comment by jacogr** [comment]
Needs to have the length added to the front. Closing, issue sorted and submitted.

We need to clean up and simplify the boilerplate, it is too much looking at the sample provided.
