### ISSUE TITLE
WSProvider times out connecting to Edgeware, but only when using `yarn run chain:info`?

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/api#1496]
This may seem a dumb issue but when trying to fetch metadata from Edgeware via `yarn run chain:info --ws  wss://mainnet1.edgewa.re`, the connection is always rejected with error message: `API-WS: disconnected from wss://mainnet1.edgewa.re code: '1006' reason: 'connection failed'`. This is not the case with any of the other hosted nodes (Kusama, Flaming Fir, etc.) nor with a local node.

Weird part is that I'm able to connect to Edgeware on apps and get the metadata through the apps toolbox no problem.

**Comment by jacogr** [comment]
Closing. Known issue with the edgeware devops config.

**Comment by jacogr** [comment]
I believe ws://hostname:9944 used to work. (Bypassing the nginx proxy)
