### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/api#152]
The goal is to:
- Revert this change https://github.com/polkadot-js/api/pull/145/commits/16237c44cdf9828dc63fd651609f5d4910b65056
- Get the CI happy again (meaning writing the missing doc)

**Comment by jacogr** [comment]
Don't worry abut any of the docs outside api-*, i.e. the rveret is overkill for now -

1. The types will be mostly pulled via the new state_jsonmeta API, so type-storage & type-extrinsics will be gone
2. type-params is going to be replaced completely

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/145
