### ISSUE TITLE
Support `Option<T>` in Extrinsic signed payload

### ISSUE THREAD

**Issue by holygits** [polkadot-js/api#1542]
I'm using an `Option<MyType>` in a custom extrinsic signed payload.
The expected behavior is unclear for the `None` case. 
The rust side expects a `0` to be encoded for the signature to verify.
This implementation encodes nothing for `None` when `isBare = true`

`Option` is an implementation detail so it seems that polkadot-js/api is taking the correct approach here but the change will be much harder to implement on the substrate side.

https://github.com/polkadot-js/api/blob/56dc116d92ed3de5994e3dc7c767940617e088e9/packages/types/src/codec/Option.ts#L133-L149

**Comment by jacogr** [comment]
There is another approach we can take when we convert the payload for signing that will not strip all. As it stands it works for defaults but not all, like here. 

So yes - can be done and should be done for overall correctness by adjusting where we serialize the payload.

**Comment by jacogr** [comment]
I have not forgotten about this, I'm just not (yet) sure how to solve it. Have had 2 aborted attempts thus far. It is easy to solve if we never expect the structure to be de-serialized, however we actually do. 

So atm thinking about custom serliazation into payload, without having to duplicate code everywhere. Sorry about this very long delay here, apparently it is not an easy thing to solve (or well, at least not in the way we've done it here)

**Comment by holygits** [comment]
Thanks for the update. I've turned to monkey patching in the mean time.

```js
Option.prototype.toU8a = function toU8a(isBare?: boolean): Uint8Array {
  // Hack to always encode `0` for None (ignores `isBare`)
  if (this.isNone) return new Uint8Array([0]);
  if (this.isSome && isBare) {
    return this.unwrap().toU8a(isBare)
  } else {
    let buf = new Uint8Array([1]);
    buf.set(this.unwrap().toU8a(isBare), 1);
    return buf;
  }
}
```

**Comment by jacogr** [comment]
The `isBare` is actually "encode for storage", the only place where stuff like option really comes through with "no prefix".

Not 100% sure about the `isSome` path though in the hack, for `Option` it should be `<1/0><data>`. But happy that you are not completely stuck atm.
