### ISSUE TITLE
subscribeNewHeads only works with session module

### ISSUE THREAD

**Issue by geigerzaehler** [polkadot-js/api#1554]
`subscribeNewHeads` only works when the node runtime provides the session module. If this is not the case (when using Aura consensus for example) the method throws an error that `api.query.session` is undefined.

**Comment by jacogr** [comment]
You are speaking about the `api.query.derive.subscribeNewHeads` - it does work with Aura, i.e. Edgeware chains. 

The reason why the derive needs the `session` module is to be able to calculate the author. So a straight `api.rpc.chain.subscribeNewHeads` will work when there are no `session.validators`.

**Comment by jacogr** [comment]
Should be a "wontfix", but comes with no additional cost.
