### ISSUE TITLE
Contract call method data exception

### ISSUE THREAD

**Issue by jeremymj** [polkadot-js/api#1556]
I used the latest available [apps](https://github.com/polkadot-js/apps) `7048a65c3dc0bea2061a653a7f63baf8b192ddb4` and [substate node](https://github.com/paritytech/substrate) `7874be8668ba6ff43c107c5da26105f934654cc2` to `deploy` an [erc20 contract]()  and found that the value set in `on_deploy` is not the same as the value returned by the `total_supply` method. I recently found this bug with the new ABI, but I am not sure if it is caused by [api](https://github.com/polkadot-js/api) or `substrate node`.This is the [abi file ](https://github.com/polkadot-js/api/files/3823230/abi.txt) I am using.This problem exists with all method calls in the contract instance.

**Comment by jacogr** [comment]
This should be fixed now in . both the API and the apps UI.
