### ISSUE TITLE
 Cannot destructure property `strings` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by liupan163** [polkadot-js/api#1568]
when i use it in my vueJs project ,it occurs this error once i  compile code.

```
Cannot destructure property `strings` of 'undefined' or 'null'.
    at new MetadataRegistryLookup (MetaRegistry.js?1408:44)
    at new MetaRegistry (MetaRegistry.js?1408:117)
    at new ContractRegistry (ContractRegistry.js?25d1:56)
    at new ContractAbi (Abi.js?14ba:22)
```

package.json:

```
  "dependencies": {
    "@polkadot/api": "0.96.1",
    "@polkadot/keyring": "^1.6.1",
    "@polkadot/util": "^1.6.1",
    "@polkadot/util-crypto": "^1.6.1",
    "@polkadot/api-contract": "0.96.1",
    "@polkadot/types": "0.96.1",
    "@polkadot/app-contracts": "^0.36.1",
    "core-js": "^2.6.9",
    "vue": "^2.6.10",
    "vue-class-component": "^7.1.0",
    "vue-i18n": "^8.14.0",
    "vue-property-decorator": "^8.2.2",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@types/pdfjs-dist": "^2.1.0",
    "@types/qrcode": "^1.3.4",
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-typescript": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "ts-import-plugin": "^1.6.1",
    "typescript": "^3.6.2",
    "vue-template-compiler": "^2.6.10",
    "vuetable-2": "^1.7.5",
    "webpack": "^4.39.3"
  }
```

tsconfig.json:

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "allowJs": true,
    "resolveJsonModule": true,
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by jacogr** [comment]
Can you share the ABI please?

**Comment by liupan163** [comment]
> Can you share the ABI please?

import {Abi, PromiseContract as ApiContract} from '@polkadot/api-contract';



 const contractAbi = new Abi(json_obj);      // this place report error

**Comment by jacogr** [comment]
Perfect. Can you just share the `./abi.json` file as well? It seems the API has problems parsing that due to the format.

**Comment by liupan163** [comment]
> Perfect. Can you just share the `./abi.json` file as well? It seems the API has problems parsing that due to the format.

{
  "registry": {
    "strings": [
      "Erc20",
      "erc20",
      "normal",
      "total_supply",
      "Value",
      "ink_core",
      "storage",
      "value",
      "cell",
      "SyncCell",
      "sync_cell",
      "Key",
      "key",
      "balances",
      "HashMap",
      "collections",
      "hash_map",
      "impls",
      "AccountId",
      "env",
      "srml",
      "types",
      "len",
      "entries",
      "SyncChunk",
      "chunk",
      "sync_chunk",
      "Entry",
      "Occupied",
      "OccupiedEntry",
      "val",
      "Removed",
      "cells_key",
      "allowances",
      "on_deploy",
      "init_value",
      "Balance",
      "balance_of",
      "owner",
      "allowance",
      "spender",
      "transfer",
      "to",
      "bool",
      "approve",
      "transfer_from",
      "from",
      "Approval",
      "EnvTest",
      "balance",
      "Transfer",
      "Option",
      "None",
      "Some"
    ],
    "types": [
      {
        "id": {
          "custom.name": 1,
          "custom.namespace": [
            2,
            3
          ],
          "custom.params": []
        },
        "def": {
          "struct.fields": [
            {
              "name": 4,
              "type": 2
            },
            {
              "name": 14,
              "type": 8
            },
            {
              "name": 34,
              "type": 16
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 5,
          "custom.namespace": [
            6,
            7,
            8
          ],
          "custom.params": [
            3
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 9,
              "type": 4
            }
          ]
        }
      },
      {
        "id": "u128",
        "def": "builtin"
      },
      {
        "id": {
          "custom.name": 10,
          "custom.namespace": [
            6,
            7,
            9,
            11
          ],
          "custom.params": [
            3
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 9,
              "type": 5
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 12,
          "custom.namespace": [
            6,
            7,
            13
          ],
          "custom.params": []
        },
        "def": {
          "tuple_struct.types": [
            6
          ]
        }
      },
      {
        "id": {
          "array.len": 32,
          "array.type": 7
        },
        "def": "builtin"
      },
      {
        "id": "u8",
        "def": "builtin"
      },
      {
        "id": {
          "custom.name": 15,
          "custom.namespace": [
            6,
            7,
            16,
            17,
            18
          ],
          "custom.params": [
            9,
            3
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 23,
              "type": 10
            },
            {
              "name": 24,
              "type": 13
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 19,
          "custom.namespace": [
            6,
            20,
            21,
            22
          ],
          "custom.params": []
        },
        "def": {
          "tuple_struct.types": [
            6
          ]
        }
      },
      {
        "id": {
          "custom.name": 5,
          "custom.namespace": [
            6,
            7,
            8
          ],
          "custom.params": [
            11
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 9,
              "type": 12
            }
          ]
        }
      },
      {
        "id": "u32",
        "def": "builtin"
      },
      {
        "id": {
          "custom.name": 10,
          "custom.namespace": [
            6,
            7,
            9,
            11
          ],
          "custom.params": [
            11
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 9,
              "type": 5
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 25,
          "custom.namespace": [
            6,
            7,
            26,
            27,
            26
          ],
          "custom.params": [
            14
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 33,
              "type": 5
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 28,
          "custom.namespace": [
            6,
            7,
            16,
            17,
            18
          ],
          "custom.params": [
            9,
            3
          ]
        },
        "def": {
          "enum.variants": [
            {
              "tuple_struct_variant.name": 29,
              "tuple_struct_variant.types": [
                15
              ]
            },
            {
              "unit_variant.name": 32
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 30,
          "custom.namespace": [
            6,
            7,
            16,
            17,
            18
          ],
          "custom.params": [
            9,
            3
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 13,
              "type": 9
            },
            {
              "name": 31,
              "type": 3
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 15,
          "custom.namespace": [
            6,
            7,
            16,
            17,
            18
          ],
          "custom.params": [
            17,
            3
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 23,
              "type": 10
            },
            {
              "name": 24,
              "type": 18
            }
          ]
        }
      },
      {
        "id": [
          9,
          9
        ],
        "def": "builtin"
      },
      {
        "id": {
          "custom.name": 25,
          "custom.namespace": [
            6,
            7,
            26,
            27,
            26
          ],
          "custom.params": [
            19
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 33,
              "type": 5
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 28,
          "custom.namespace": [
            6,
            7,
            16,
            17,
            18
          ],
          "custom.params": [
            17,
            3
          ]
        },
        "def": {
          "enum.variants": [
            {
              "tuple_struct_variant.name": 29,
              "tuple_struct_variant.types": [
                20
              ]
            },
            {
              "unit_variant.name": 32
            }
          ]
        }
      },
      {
        "id": {
          "custom.name": 30,
          "custom.namespace": [
            6,
            7,
            16,
            17,
            18
          ],
          "custom.params": [
            17,
            3
          ]
        },
        "def": {
          "struct.fields": [
            {
              "name": 13,
              "type": 17
            },
            {
              "name": 31,
              "type": 3
            }
          ]
        }
      },
      {
        "id": "bool",
        "def": "builtin"
      },
      {
        "id": {
          "custom.name": 52,
          "custom.namespace": [],
          "custom.params": [
            9
          ]
        },
        "def": {
          "enum.variants": [
            {
              "unit_variant.name": 53
            },
            {
              "tuple_struct_variant.name": 54,
              "tuple_struct_variant.types": [
                9
              ]
            }
          ]
        }
      }
    ]
  },
  "storage": {
    "struct.type": 1,
    "struct.fields": [
      {
        "name": 4,
        "layout": {
          "struct.type": 2,
          "struct.fields": [
            {
              "name": 9,
              "layout": {
                "range.offset": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "range.len": 1,
                "range.elem_type": 3
              }
            }
          ]
        }
      },
      {
        "name": 14,
        "layout": {
          "struct.type": 8,
          "struct.fields": [
            {
              "name": 23,
              "layout": {
                "struct.type": 10,
                "struct.fields": [
                  {
                    "name": 9,
                    "layout": {
                      "range.offset": "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "range.len": 1,
                      "range.elem_type": 11
                    }
                  }
                ]
              }
            },
            {
              "name": 24,
              "layout": {
                "range.offset": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "range.len": 4294967295,
                "range.elem_type": 14
              }
            }
          ]
        }
      },
      {
        "name": 34,
        "layout": {
          "struct.type": 16,
          "struct.fields": [
            {
              "name": 23,
              "layout": {
                "struct.type": 10,
                "struct.fields": [
                  {
                    "name": 9,
                    "layout": {
                      "range.offset": "0x0000000000000000000000000000000000000000000000000000000100000001",
                      "range.len": 1,
                      "range.elem_type": 11
                    }
                  }
                ]
              }
            },
            {
              "name": 24,
              "layout": {
                "range.offset": "0x0000000000000000000000000000000000000000000000000000000100000002",
                "range.len": 4294967295,
                "range.elem_type": 19
              }
            }
          ]
        }
      }
    ]
  },
  "contract": {
    "name": 1,
    "constructors": [
      {
        "name": 35,
        "selector": "[\"0x00\",\"0x00\",\"0x00\",\"0x00\"]",
        "args": [
          {
            "name": 36,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            }
          }
        ],
        "docs": []
      }
    ],
    "messages": [
      {
        "name": 4,
        "selector": "[\"0x38\",\"0x93\",\"0x5D\",\"0x92\"]",
        "mutates": false,
        "args": [],
        "return_type": {
          "ty": 3,
          "display_name": [
            37
          ]
        },
        "docs": [
          "Returns the total number of tokens in existence."
        ]
      },
      {
        "name": 38,
        "selector": "[\"0xE4\",\"0x1D\",\"0xBB\",\"0x26\"]",
        "mutates": false,
        "args": [
          {
            "name": 39,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          }
        ],
        "return_type": {
          "ty": 3,
          "display_name": [
            37
          ]
        },
        "docs": [
          "Returns the balance of the given AccountId."
        ]
      },
      {
        "name": 40,
        "selector": "[\"0xB6\",\"0x39\",\"0x76\",\"0x70\"]",
        "mutates": false,
        "args": [
          {
            "name": 39,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          },
          {
            "name": 41,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          }
        ],
        "return_type": {
          "ty": 3,
          "display_name": [
            37
          ]
        },
        "docs": [
          "Returns the amount of tokens that an owner allowed to a spender."
        ]
      },
      {
        "name": 42,
        "selector": "[\"0xC9\",\"0x28\",\"0x03\",\"0x27\"]",
        "mutates": true,
        "args": [
          {
            "name": 43,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          },
          {
            "name": 8,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            }
          }
        ],
        "return_type": {
          "ty": 21,
          "display_name": [
            44
          ]
        },
        "docs": [
          "Transfers token from the sender to the `to` AccountId."
        ]
      },
      {
        "name": 45,
        "selector": "[\"0x19\",\"0xB3\",\"0x60\",\"0xCA\"]",
        "mutates": true,
        "args": [
          {
            "name": 41,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          },
          {
            "name": 8,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            }
          }
        ],
        "return_type": {
          "ty": 21,
          "display_name": [
            44
          ]
        },
        "docs": [
          "Approve the passed AccountId to spend the specified amount of tokens",
          "on the behalf of the message\\'s sender."
        ]
      },
      {
        "name": 46,
        "selector": "[\"0x0B\",\"0xC5\",\"0x58\",\"0x63\"]",
        "mutates": true,
        "args": [
          {
            "name": 47,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          },
          {
            "name": 43,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            }
          },
          {
            "name": 8,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            }
          }
        ],
        "return_type": {
          "ty": 21,
          "display_name": [
            44
          ]
        },
        "docs": [
          "Transfer tokens from one AccountId to another."
        ]
      }
    ],
    "events": [
      {
        "name": 48,
        "args": [
          {
            "name": 39,
            "indexed": false,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            },
            "docs": []
          },
          {
            "name": 41,
            "indexed": false,
            "type": {
              "ty": 9,
              "display_name": [
                19
              ]
            },
            "docs": []
          },
          {
            "name": 8,
            "indexed": false,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            },
            "docs": []
          }
        ],
        "docs": []
      },
      {
        "name": 49,
        "args": [
          {
            "name": 50,
            "indexed": false,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            },
            "docs": []
          }
        ],
        "docs": []
      },
      {
        "name": 51,
        "args": [
          {
            "name": 47,
            "indexed": false,
            "type": {
              "ty": 22,
              "display_name": [
                52
              ]
            },
            "docs": []
          },
          {
            "name": 43,
            "indexed": false,
            "type": {
              "ty": 22,
              "display_name": [
                52
              ]
            },
            "docs": []
          },
          {
            "name": 8,
            "indexed": false,
            "type": {
              "ty": 3,
              "display_name": [
                37
              ]
            },
            "docs": []
          }
        ],
        "docs": []
      }
    ],
    "docs": []
  }
}

**Comment by jacogr** [comment]
This one is weird - the ABI loads all-ok on the apps UI.

**Comment by jacogr** [comment]
Not sure why you are stringify-ing and parsing -

```js
import * as abi from './abi.json';

function getAbiObj(obj: any) {
 const contractAbi = new Abi(abi);
}
```

Could you try the above approach? (The imported object is passed as-is)

**Comment by liupan163** [comment]
> Not sure why you are stringify-ing and parsing -
> 
> ```js
> import * as obj from './abi.json';
> 
> const abi = getAbiObj(obj);
> 
> function getAbiObj(obj: any) {
>  const contractAbi = new Abi(obj);
> }
> ```
> 
> Could you try the above approach? (The imported object is passed as-is)

ok, i got the wrong place.  when format the json file to string , it appear more "deafult" layer
{"default":{"registry":{"strings":
...
}

thx        : )

**Comment by jacogr** [comment]
Perfect!
