### ISSUE TITLE
Change naming of transaction inclusion events

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/api#1571]
We had this conversation out of band and I wanted to document here so it doesn't get lost. 

In brief, the `Finalized` event for transaction inclusion is misleading because it _may_ lead the user to believe their transaction has been included in the finalized when actually it only means that the transactions were included (in potentially a fork). This is problematic when a fork does occur because it means the transactions will be included in a different block then the one that the client saw. The idea is then to change `Finalized` to `Included` and for the status of being included in a finalized chain possibly `Canonical` or whatever is better.

**Comment by jacogr** [comment]
The statusses map 100% through to Rust - https://github.com/paritytech/substrate/blob/master/core/transaction-pool/graph/src/watcher.rs#L28-L43

So here we won't change step, however whatever is included on the pool side will be mapped in the API.

**Comment by jacogr** [comment]
Closing here. We will see what happens on the node side and (as always), just align the naming with what . is there for full e2e consistency.
