### ISSUE TITLE
Extrinsic sign confused

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#1575]
Very confused, how are the two lines of signatures obtained, it should not be the result of the signature,
https://github.com/polkadot-js/api/blob/a4c5ca45b237b42bacce91e02e22b236876c19ee/packages/types/src/primitive/Extrinsic/v4/Extrinsic.spec.ts#L67-L68
Not sure what  ``genesisHash`` and ``blockHash ``  has to do

**Comment by jacogr** [comment]
The signature is created by signing a serialized payload, https://github.com/polkadot-js/api/blob/master/packages/types/src/primitive/Extrinsic/v3/ExtrinsicPayload.ts#L16-L32

So the genesisHash & blockHash are not part of the extrinsic, however they are signed and retrieved by the node, generating the same payload and then comparing signatures.

**Comment by freehere107** [comment]
OK, I get the same payload, but I sign with ed25519 get signature, but the signature top 64  length is correct , but 64 behind is the error. I sign the message with [https://ed25519.cr.yp.to/.](https://ed25519.cr.yp.to/.).

**Comment by freehere107** [comment]
I get with signature is 
``b8065808da3d11ddb4167afb156eafb51e8104ba792589bb443653a7fab82b90
cfa356ec925b3f04f0b68e08175067ec4e452916172476ce6dfa9849256d0a0a
``

**Comment by freehere107** [comment]
I get with signature is 
``b8065808da3d11ddb4167afb156eafb51e8104ba792589bb443653a7fab82b90
cfa356ec925b3f04f0b68e08175067ec4e452916172476ce6dfa9849256d0a0a
``

**Comment by freehere107** [comment]
Thanks you, solve it.

**Comment by freehere107** [comment]
Signed with blockHash, this ``blockHash`` is needed specific ``blockHash``？ I signal with ``polkadot.js`` sign always wrong

**Comment by jacogr** [comment]
`blockHash` relates to the ExtrinsicEra the extrinsic applies to. So if you era is valid from block 123,456, the `blockHash` is the for that block.

**Comment by freehere107** [comment]
Thank you, got it
