### ISSUE TITLE
Could not convert parameter `tx` between node and runtime

### ISSUE THREAD

**Issue by vol4tim** [polkadot-js/api#1576]
When I execute a extrinsic, I get an error.

`
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field CheckEra.0")): RuntimeApi("Execution(ApiError(\"
`

You can reproduce the error on the latest version of the substrate-node-robonomics project
airalab/substrate-node-robonomics#36

**Comment by jacogr** [comment]
Ensure that you have the correct types for the node injected. For instance, substrate by default used `u32` for `BlockNumber`, for Robonomics, this is `u64`, e.g. https://github.com/airalab/substrate-node-robonomics/blob/master/node/runtime/src/types.rs#L25

(Same with `Index`, `u32` on Substrate, `u64` here - unless you explicitly inject those types, the encoding across the wire will not match)

**Comment by vol4tim** [comment]
Fixed in signing scheme extrinsic. airalab/substrate-node-robonomics@c2ba3a52f36b104a99e564461a8e837fe7de09a4
Thanks!

**Comment by jacogr** [comment]
Ahhh, can see the issue.  The new MultiSignature vs the old AnySignature. (As for extrinsics v4). Since the signature is 65 bytes in length with the new variant, the encoding went wrong. 

The good news is that this is now stabilized.
