### ISSUE TITLE
Unable to create and validate type from BTreeMap

### ISSUE THREAD

**Issue by sunqiLoveSnow** [polkadot-js/api#1651]
when using btreemap in decl_storage:

```
decl_storage! {
    trait Store for Module<T: Trait> as Storage {
    ...
    Book get(get_book): map T::AssetId => BTreeMap<T::Balance, Vec<T::Hash>>;
    ...
    }
}

```

polkadot-js has an error like ### **"API/DECORATOR: Error: FATAL: Unable to initialize the API: Unhandled: Unable to create and validate type from BTreeMap<Balance,Vec<Hash>>"**
It seems that we need to add an case for btreemap in @polkadot/metadata/Metadata/util/validateTypes.js

**Comment by jacogr** [comment]
Yes, not sure how this would work otherwise.
