### ISSUE TITLE
Error 404 when opening links in polkadot.js.org/api/types/#polkadot-types in new tab

### ISSUE THREAD

**Issue by alexeiZamyatin** [polkadot-js/api#1655]
When opening the links to the types listed in [api/types/enums/_codec_create_types_.typedefinfo.html#compact](https://polkadot.js.org/api/types/#primitive-types) in a new browser tab (ctrl + click) error 404 is thrown. 

Links work fine when opening in same tab.

**Comment by axelchalon** [comment]
Thanks for reporting! links are working fine now
