### ISSUE TITLE
Support adjusted contracts ABI

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#1660]
https://github.com/paritytech/ink/pull/296

This opens the door to get rid of the custom parser and just define the objects and parse directly into them.

**Comment by yangwao** [comment]
Looks like that issue was merged. Is there another way to interact with ink3.0? I found I could use https://www.npmjs.com/package/@polkadot/api-contract but probably it will yield error as well as because ABI has different strcuture?

**Comment by jacogr** [comment]
Look at the linked PRs, there has been a lot of work since Dec already, but it is not done yet, so there is no way to support it atm.
