### ISSUE TITLE
Error Message for certain queries is incomplete

### ISSUE THREAD

**Issue by DanielMagro97** [polkadot-js/api#1663]
When running a '.at(blockHash)' query on a node which is not an archival node, with an old blockHash, the error which is returned is incomplete:

"Error: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occured: Client(UnknownBlock(\"State alread"

To clarify: the query should return an error, the issue is that the error message ends abruptly.

**Comment by jacogr** [comment]
It is known, and by design since these can get exceptionally long - https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/coder/index.ts#L60

So would accept PRs around this, but probably won't touch it otherwise.

**Comment by jacogr** [comment]
These have been adjusted recently with length and formatting (most info will now come back). We still have an issue where you have nested errors, so the 98-percentile is covered, but not all.
