### ISSUE TITLE
Encoding error for single item Enums

### ISSUE THREAD

**Issue by c410-f3r** [polkadot-js/api#1667]
Substrate encodes a single item Enum with an added leading zero while Polkadot encodes a single item Enum with an unnecessary (?) extra 255, breaking interchangeability between both ends.

```rust
hex::encode(some_single_item_enum.encode()); // Gives, for example, 001234
```

```ts
someSingleItemEnum.toHex(); // Gives 0x00ff1234
```

**Comment by jacogr** [comment]
Can you share how this is defined. The output above is certainly wrong, not sure where it comes from though. So the definition would help.

**Comment by jacogr** [comment]
Ok, has a single-entry test added here - https://github.com/polkadot-js/api/pull/1670 - all encoded exactly as expected.

**Comment by c410-f3r** [comment]
@jacogr It was a misunderstanding. I was indeed playing with address fields when the additional `ff` arrived. Nevertheless, Substrate was still expecting an encoding without `ff` and this behavior was fixed with `hexToU8a(someSingleItemEnum.toU8a(true))`.

Sorry for the noise, I will be more careful next time

**Comment by jacogr** [comment]
The Address encoding is very explicit and has a special serialization, enum-like - the first byte indicates if it is an AccountId or AccountIndex. AccountId will be without.

**Comment by c410-f3r** [comment]
@jacogr  Thank you very much!
