### ISSUE TITLE
Unable to generate documentation

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#168]
In Polkadot-JS API Docs https://github.com/polkadot-js/api/docs, what is the current procedure that is used (both in 'development' and in 'production') for generating the Markdown (.md) and HTML (.html) docs for our Gitbook at https://polkadot.js.org/api/?

Note that I reviewed comments between @jacogr and @amaurymartiny in https://github.com/polkadot-js/api/pull/159, and created this PR https://github.com/polkadot-js/api/pull/167 to address Issue #154, although I'm not sure if what I've done is correct. So I've come up with the following questions:

1) How are we generating the HTML .html files in docs/ directory?
	* If I delete a HTML doc file (i.e. docs/api-provider/classes/_http_index_.httpprovider.html) and then run `yarn; yarn run build:htmldoc;`, the Bash Terminal logs says `Documentation generated at /polkadot-js/api/docs/html`, but the file _http_index_.httpprovider.html does not exist (isn't regenerated).

2) How are we generating the Markdown .md files in docs/ directory?
	* Were the Markdown .md files that are currently there generated originally generated by running `yarn clean && typedoc --theme markdown --out docs/html` (i.e. using the `markdown` instead of the `default` theme)
		* Note: When I previously ran `yarn; yarn run build:htmldoc;`, the Bash Terminal logs also said `To generate markdown please set option --theme markdown`.
	* Are we currently just "manually" modifying the Markdown .md files (instead of generating them with a script)?

	* How are we updating the Markdown .md files in docs/ directory automatically after modifying the Typedoc comments in the code comments? (i.e.
		```
		/**
		 * @example
		 * ```javascript
		...
		```

3) Should we by using the `gitbook` command at all? https://toolchain.gitbook.com/

4) Should https://polkadot.js.org/ have a {.api} link to the Github repo and a link to the docs at https://polkadot.js.org/api/?

**Comment by jacogr** [comment]
The HTML/md docs are generally not needed to be checked in, it is generated on CI and pushed. However, obviously for dev it is useful to view any changes made.

`yarn gitbook serve`

should do the trick. (or `build` to generate) The you can access it in `:4000`.

**Comment by jacogr** [comment]
Ahhh... and since I didn't have my morning coffee yet. The above PR may not change much once generated. (Will see when the merge/CI is pushed, but it _may_ still break since it is generated from the TS code)

**Comment by jacogr** [comment]
Marking as an future addition to dev section in README.
