### ISSUE TITLE
Error when connecting to a runtime with nested types

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/api#1685]
We have a runtime method with the following signature:

```
fn validate_mint(origin, anchor_id: T::Hash, deposit_address: [u8; 20], pfs: Vec<proofs::Proof>, static_proofs: [[u8;32];3]) -> Result {
```

It works well in unit tests, but polkadot-js seems to not like the type of `static_proofs`. The error I'm seeing when instanciating the API is:

```
2019-12-19 20:08:22   API/DECORATOR: Error: FATAL: Unable to initialize the API: Expected '[' closing with ']'
    at EventEmitter.Init._onProviderConnect (/Users/philipstanislaus/go/src/github.com/centrifuge/centrifuge-chain-functional-test/node_modules/@polkadot/api/base/Init.js:55:23)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

A workaround is to use 

```
Inner: ‘[u8;32]’
Outer: ‘[Inner;3]’
```

**Comment by jacogr** [comment]
Dropping this down in priority -

- there is a work-around
- this is quite a it of work to make the parse compliant

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
