### ISSUE TITLE
Unable to create enum error

### ISSUE THREAD

**Issue by dillu24** [polkadot-js/api#1687]
Lately I was getting this error ... `Error: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Unable to create Enum via index 202, in ApplyExtrinsic, Finalization` .. when querying data from a validator ... Is this due to an API version?

**Comment by jacogr** [comment]
Yes, and types. For instance in the latest Substrate master (which the API beta branch tracks), the DispatchError struct was changed. 

So it would depend on how closely the node you are connecting to and which version of the API is used. (For Substrate current master, you would need the API beta)
