### ISSUE TITLE
How to use setKeys api

### ISSUE THREAD

**Issue by trietnguyen267** [polkadot-js/api#1701]
https://polkadot.js.org/api/substrate/extrinsics.html#setkeys-keys-keys-proof-bytes
There is no example that we can refer to this api and nowhere I can find anybody used it. Could you add an example to the document?

**Comment by jacogr** [comment]
It is just 2 parameters -

- the first is the hex output from the `author_rotateKeys` call
- the second is (for now) and empty Uint8Array (proof is not yet checked)

```js
const tx = api.tx.session.setKeys('0x123...980', new Uint8Array());
```

**Comment by trietnguyen267** [comment]
Thanks @jacogr, I was scratched my head what kind of proof data it needed.
