### ISSUE TITLE
SemVer suggestion

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/api#1703]
It's convenience suggestion but it would really help us at [api-explorer](https://apiexplorer.polkalert.com) if you dropped the -beta versions while on 0.x.x since it's already considered unstable by SemVer definition. 

Package managers don't update to -beta versions, thus we need to update our dependencies manually every time you update API which is quite often. 
It's also hassle in other projects, since we need to manually change all the dependencies that use the -beta naming instead of simple update. If we need stable version, which we probably won't, since it's pretty much useless if we don't have latest type definitions, then we could specify it in package.json easily.

**Comment by jacogr** [comment]
We will do a 1.0 as soon as Substrate 2.0 hits. (Weeks, not months)

**Comment by jacogr** [comment]
Closing, the next release will be 1.0 (undergoing audits and cleanups, the 1.0-beta will probably have some short-lived breakages along the way)
