### ISSUE TITLE
api.query.nicks.nameOf() method is broken

### ISSUE THREAD

**Issue by bhaskarSingh** [polkadot-js/api#1712]
```
const provider = new WsProvider('wss://kusama-rpc.polkadot.io/');
const api = await ApiPromise.create({ provider });

const value = await api.query.nicks.nameOf(
   'HeCK315sYXruJvZKB5uXtEBnpWwYHFaKfNNZ54G76Qr7Nkn' //Validator stash ID
);
```

on calling namesOf() method results in the below error
`Error: FATAL: Unable to initialize the API: createType(Percent):: Unable to find plain type for {"info":6,"type":"Percent"}`

**Comment by joshua-mir** [comment]
@bhaskarSingh nicks were removed on Kusama in favor of the identity module

**Comment by prastut** [comment]
@JoshOrndorff thank you for the prompt response! 

Would you have recommendations for where we can keep abreast of breaking changes? And recommendations on how we can help? 

At our end, we monitor the changelog as much as possible: https://github.com/polkadot-js/api/blob/master/CHANGELOG.md and though Identity support is mentioned, this change wasn't mentioned.

**Comment by jacogr** [comment]
The API supports anything on the metadata - so some chains, when they have the module included, will have nicks support. Kusama is not one of those. The API will never have chain-specific details.

If you want chain-specific details, follow the specific chain, for Kusama that is the https://github.com/paritytech/polkadot repo.

**Comment by prastut** [comment]
@jacogr ahh got it. Thanks for the mental model :)
