### ISSUE TITLE
Possibly missing endpoints in the documentation or completely missing?

### ISSUE THREAD

**Issue by jakobhans** [polkadot-js/api#1720]
I am looking at the documentation for the API and I am missing some endpoints that would be useful, I just don't know if these are missing from the documentation or not available at all.

- Query transactions by hash.
- Check what kind of extrinsic is each one of the listed in the getBlock method returned object.

**Comment by jacogr** [comment]
There is no ability to query a tx by hash. Hashes can be duplicated between blocks. (it is not unique per tx, rather is will be unique per block)

The extrinsics you can just decode with the metadats, the api getBlock actually transparently decodes all txs as received based on the metadata.

**Comment by jakobhans** [comment]
Thanks for replying! So, I do have the getBlock response, and there is an array for extrinsics, but I still can't figure out what to do with these strings to get tx information, like amount, fee, destination wallet, etc. I'm sure I'm not being able to wrap my head around the abstraction here, but any help is greatly appreciated.

**Comment by jacogr** [comment]
If you looks the the apps UI, you get the block details https://polkadot.js.org/apps/#/explorer/query - all it does is an getBlock query (the details are decoded into an `Vec<Extrinsic>` - may be that you log the JSON if you cannot see t)

**Comment by jakobhans** [comment]
Thank you for all the help, this clears things up a little. Closing the question now.
