### ISSUE TITLE
Multi-query seems to not update cache for boolean value.

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#1729]
I have a storage item:

```
map T:Account => bool
```

I use a `.multi` query to fetch the boolean value for all the members. This multi-query seems to update when the value goes from false -> true, but does not update when going from true -> false.

(It may be relevant to note that we never actually store `false`, we just remove the storage item, but it should return false on default).

You can see the behavior here with inline comments:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1860335/72680554-7554ab80-3abb-11ea-9e47-5633ee217395.png">

The image shows:
* Initially both users are suspended (`[true, true]`), (correct)
* We un-suspend one of them
* A new `.multi` query still returns `[true, true]`, (incorrect)
* If you query the value of the un-suspended member separately, you get `false` (correct)
* Then if you multi-query again, you get the correct result of `[false, true]`. (correct)

Not this issue does not appear when going from `false` -> `true`. Only `true` -> `false`.

**Comment by shawntabrizi** [comment]
Here is that better example, with inline comments about the different steps:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1860335/72680554-7554ab80-3abb-11ea-9e47-5633ee217395.png">

**Comment by jacogr** [comment]
Don't use multi for those.

So the issue is the following - the RPC make no distinction between "the value has not been updated"  and "the value has been deleted". So there is just way way to actually track deletions, the RPC returns `null` for the field. (Which also indicates it has not changes from previous)

There is a write-up here - https://github.com/polkadot-js/api/issues/1417

**Comment by shawntabrizi** [comment]
Thanks @jacogr. The problem makes sense, but it seems maybe an improvement in the Substrate RPC (at least the results) could fix this.

Is there any alternative other than querying every block?

I have a half solution here:

```javascript
  useEffect(() => {
    const addresses = keyring.getPairs().map(account => account.address);

    var promises = [];

    addresses.forEach(address =>
      promises.push(api.query.society.suspendedMembers(address))
    );

    Promise.all(promises).then(results => {
      var suspended = [];
      results.forEach((suspendedStatus, i) => {
        console.log('suspended status: ', suspendedStatus, i);
        if (suspendedStatus.isTrue) {
          suspended.push(addresses[i]);
        }
      });

      setSuspendedMembers(suspended);
    });
  }, [api.query.society, api.query.society.suspendedMembers, keyring, members]);
```

Basically I create an array of promises, call `Promise.all` on them, and then work through the results to get the data I need.

To get around the "subscription" problem, I have my `useEffect` hook update on `members`, which will of course be updated if the suspended member is approved. However, if they are rejected, we don't get any update.

Is this the ergonomic way to do this? Or do you have a better idea/something you have done before?

**Comment by jacogr** [comment]
In polkadot-js stuff, we generally stay about from the above hooks when dealing with anything UI. In cases where it is re-usable and especially when it is useful to others, we move them to derives where we use RxJs. 

For instance, the logic for the society member retrieval - https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/society/member.ts#L23 (Still early, but should give through the concept of the splits employed there)

Can also ve done with the promise-specific `api.combineLatest` (which basically does what `combineLatest` does, with subscriptions and unsubscribes so it updates and the status changes)

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/1732 - thanks to @shawntabrizi for the verification.
