### ISSUE TITLE
I get an error when I import @polkadot/rpc-provider/mock/index 

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#1735]
My code:
```javascript
import Mock from @polkadot/rpc-provider/mock/index 
console.log(Mock)
```
I noticed that @polkadot/types/json/SignedBlock.004.immortal.json will be imported into this package.https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/mock/index.ts#L17

Actually, this file has not been published

![image](https://user-images.githubusercontent.com/7029338/72813298-10a57680-3c9e-11ea-8e7f-ac19124567f5.png)

This may be the cause of the error.

**Comment by jacogr** [comment]
The mock was intended for usage in the polkadot-js tests, never really as a comprehensive external solution. (It should actually not be published in the current form, the json samples def. should not be published)

There is actually a much better solution (I have been meaning to rip this off, hopefully with @jnaviask 's permission) developed by Edgeware - however cannot find that published.

**Comment by jnaviask** [comment]
@jacogr: unfortunately I haven't had the time to update the mechanisms in my test mock to match the current state of the chain logic, so it's on-hold for now. But we can discuss its usage offline and I can send over what I have.
