### ISSUE TITLE
Ability to iterate all keys (and values?) for a map / double_map

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#1737]
Something similar to linked map but for standard map and double_map.

**Comment by jacogr** [comment]
There is .entries on maps that returns all key/values. (Keys encoded)

**Comment by xlc** [comment]
Oh thanks. Is there a similar method for double_map? I mean get all key values for a given first key.

**Comment by jacogr** [comment]
It is limited to Map atm, however if DoubleMap has the same prefixed keys now as maps, it is a simple check extension. 

Have not looked at it, so cannot definitively comment if it will work. (A simple test with RPC getKeys will confirm)
