### ISSUE TITLE
Rework api & rpc packages

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#176]
Rename the actual RPC wrappers -

- api -> rpc-core
- api-rx -> rpc-rx
- api-provider -> rpc-provider

Then for the actual high-level API -

- api-observable -> api

In this `api-codec` seems like the odd man out, I would make the published package `@polkadot/codec`

@amaurymartiny Thoughts?

**Comment by amaurymartiny** [comment]
How we name internally our folders doesn't actually matter to me, the important thing is the `@polkadot/*` npm packages name.

So I'm thinking
- `api`-> `@polkadot/rpc` or `@polkadot/api`
- `api-rx`->`@polkadot/rx` : This one shouldn't be used at all
- `api-provider`->`@polkadot/provider`
- `api-codec`->`@polkadot/codec` or `@polkadot/types` : users don't need to know we do codec, but need to know these are the the types they actually need to use.
- `api-observable` -> `@polkadot/observables`
- ??? -> `@polkadot/api`: We don't have this one yet (because the UI doesn't need it), but I would like to see a simple-to-use api library that is promised-based. Ideally it would just import `@polkadot/observables` and run `.toPromise()` everywhere, because Rx is just a programming pattern among others, while Promises are standard. And this one would be called `@polkadot/api`.

**Comment by jacogr** [comment]
- `@polkadot/rpc` - happy
- `@polkadot/rpc-rx` - maybe not externally used, but it does have some critical function
- `@polkadot/provider` - happy
- `@polkadot/types` - happy (full-circle, primitives was types, then became primitives + some coding, then replaced, now back)
- `@polkadot/api-rx` - feels simpler than typing `observables`
- `@polkadot/api` - wraps above, just with `.toPromise()`?

**Comment by jacogr** [comment]
Thought about the .toPromise() thing - it is actually an issue, since most of the use is actually queries and these are for anything non-trivial subscription-based. Ror that your options are -

- observables
- (current) api package

Just went through what use we actually have out there - 2 datapoints only, Polkabot & UI. So not convinced that the .toPromise() will add any value. Happy to re-visit when we have actual requests and rather focus on making what is there bullet-proof.

**Comment by jacogr** [comment]
@amaurymartiny So thinking about this (expanding the above). There is the promise & rx-based versions. 

Storage -

- rx-based queries via chain.storage, which is a subscription (updates are pushed as they come in)
- promise-base queries via chain.getStorage, which is just a single value

So effectively -

api.storage.balance.freeBalance(accountId) -> promise or (auto-updating value) subscription based on API

Extrinsics - (focussing on the rx-version here, promise-based is similar)

- api.extrinsics.balances.transfer returns an Extrinsic extension. Basically the Extrinsic class, that still allows .sign(), but also an extension, .submit()
- So you can sign (or not) and when ready .submit() will just call author.submitExtrinsic rpc in the background 

Actually for promise-based, author.submitExtrinsic (which just returns a hash), for the rx-version it calls author.submitAndWatchExtrinsic (which returns a subscription-based ExtrinsicStatus, e.g. see the work @yjkimjunior wants to do in #181)

For just normal calls, I expect them to be exposed on (probably) something like api.rpc.<section>.<method>, e.g. api.rpc.system.version() - once again promise or Observable, based on API.

(Overall for the rx-based version, can probably whack rpx-rx then as well, the api-auto-contruction can just do what it wants in this one)

**Comment by amaurymartiny** [comment]
Yes, this is great. Since `state.storage/getStorage` and `author.submit(andWatch)Extrinsic` are the rpcs that we use 90% of the time, it makes sense to create shortcuts for them.

One thing I want to understand correctly:
```javascript
import api from '@polkadot/api';

api.storage.balance.freeBalance(...); // Returns Observable
```
```javascript
import api from '@polkadot/api/promise'; // Naming tbd

api.storage.balance.freeBalance(...); // Returns Promise
```
So you want 2 Api objects. Is that correct?

**Comment by jacogr** [comment]
Yes, I would split into 2 packages -

```
import api from '@polkadot/api-rx'; // naming tbd

// internally this would subscribe to api.rpc.state.storage(<balanceKey>), delivering updates as the go through
api.storage.balance.freeBalance(...); // Returns Observable
```
```
import api from '@polkadot/api-promise'; // Naming tbd

// internally this would call `api.rpc.state.getStorage(<balanceKey>), only returning the current as-is value
api.storage.balance.freeBalance(...); // Returns Promise
```

**Comment by jacogr** [comment]
Closing, implemented.
