### ISSUE TITLE
Custom RPC docs

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#1775]
It is possible to add custom RPC on Substrate side and we have done that. Now the question is how to make it available in polkadot.js?

I think the API needs a way to allow user to register custom RPC just like register custom types.

**Comment by xlc** [comment]
Seems possible already. Closing.

**Comment by jacogr** [comment]
Sorry, not documented yet :(

**Comment by remon-nashid** [comment]
Could someone at least refer to unit test that covers custom RPC queries? That would be helpful until this feature is documented.

**Comment by jacogr** [comment]
There are none, and there are no plans to add them in the current state of the RPC decoration. (Once we have https://github.com/polkadot-js/api/issues/1884 in, then yes, they will be there and documented)

Use this as a starting point -

https://github.com/polkadot-js/api/blob/master/packages/api/src/types/index.ts#L51
https://github.com/polkadot-js/api/blob/master/packages/rpc-core/src/types.ts#L21

More than that, cannot provide until the other piece have started falling into place. It is a simple `rpc: { section: { method: {...} } }` definition. If the above is not enough for now, it is best wait a bit.
