### ISSUE TITLE
Allow unsubscription from wsprovider.on()

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/api#1779]
It's really hard to handle disconnects, reconnects or changing servers cleanly right now. We managed to be pretty close by using manual connect to ``wsProvider`` and doing some hacks with ``wsProvider.on('error', cb)``, ``wsProvider.on('connected', cb)`` and ``wsProvider.on('disconnected', cb)``

However returning unsubscribe function like when subscribing to API queries would be very helpful in this case. I've already tried to implement this and it solved most of our problems. I'll make it a PR. 

If that's not acceptable at least returning EventEmitter would be helpful but that might not be as user friendly.

https://github.com/polkadot-js/api/blob/de9f033d994bebe2145e5cd0155f77ef8471a3c0/packages/rpc-provider/src/ws/Provider.ts#L172

**Comment by jacogr** [comment]
Happy to take a look.

**Comment by jak-pan** [comment]
Thanks! That was quick. :) 

P.S. Should I start branch in this repo next time?

**Comment by jacogr** [comment]
Closed in #1780 

For that you need commit access - happy to give it out for consistent contributors. So lets ice that until we have a couple more PRs under the belt and I'll gladly expand the pool with you included. Love contributions for actual users more than anything else.
