### ISSUE TITLE
Broken Webpack compatibility

### ISSUE THREAD

**Issue by SCaptainCAP** [polkadot-js/api#1802]
PR https://github.com/polkadot-js/api/pull/1758

This PR broke ability to bundle the api package with wepback because of unsafe require.

I used to bundle this package with webpack, but updating to the new version (from v0.100.1 to v1.0.1) broke webpack bundle ability.

My webpack.config.js:
```javascript
        target: "node",
        mode: "development",
        output: {
            path: path.resolve(profilePath, 'dist'),
            filename: 'file.js',
            libraryTarget: 'umd',
            library: 'profile',
            umdNamedDefine: true
        },
        resolve: {
            extensions: ['.ts', '.js']
        },
        node: {
            fs: "empty"
        },
        module: {
            exprContextCritical: false,
            rules: [
                {
                    test: /\.ts$/,
                    loader: require.resolve('ts-loader'),
                    exclude: /node_modules/,
                    options: {
                        configFile: tsconfig,
                        context: profilePath,
                    }
                }
            ]
        }
```

Webpack error:
`
./node_modules/@polkadot/api/index.js
Module not found: Error: Can't resolve '../package.json' in '/myproject/node_modules/@polkadot/api'
resolve '../package.json' in '/myproject/node_modules/@polkadot/api'
  using description file: /myproject/node_modules/@polkadot/api/package.json (relative path: .)
    using description file: /myproject/package.json (relative path: ./node_modules/@polkadot/package.json)
      no extension
        /myproject/node_modules/@polkadot/package.json doesn't exist
      .ts
        /myproject/node_modules/@polkadot/package.json.ts doesn't exist
      .js
        /myproject/node_modules/@polkadot/package.json.js doesn't exist
      as directory
        /myproject/node_modules/@polkadot/package.json doesn't exist
[/myproject/node_modules/@polkadot/package.json]
[/myproject/node_modules/@polkadot/package.json.ts]
[/myproject/node_modules/@polkadot/package.json.js]
`

**Comment by jacogr** [comment]
It works in both the apps repo as well as the extension (both using webpack). So it is probably due to the fact that it doesn't have a loader for `.json` files.

**Comment by SCaptainCAP** [comment]
@jacogr could you give me a link to the valid working example of webpack configuration?

**Comment by jacogr** [comment]
This one does work - https://github.com/polkadot-js/apps/blob/master/packages/apps/webpack.config.js

(So would be interested to see what the diffs are - sorry, have not looked, so not 100% sure where the issue lies as of yet. Took a quick look, there is no special json handling, so atm a bit stumped either way)

**Comment by hanwencheng** [comment]
After update "@polkadot/types": "1.0.0-beta.7", to "1.0.1", I have the similart problem in the react native project with metro bundle:

```
bundling failed: Error: Unable to resolve module `../package.json` from `/Projects/parity-signer/node_modules/@polkadot/types/index.js`: The module `../package.json` could not be found from `/Projects/parity-signer/node_modules/@polkadot/types/index.js`. Indeed, none of these files exist:
  * `package.json`
  * `/Projects/parity-signer/node_modules/@polkadot/package.json/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Projects/parity-signer/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Projects/parity-signer/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Projects/parity-signer/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Projects/parity-signer/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at /Projects/parity-signer/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Projects/parity-signer/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Projects/parity-signer/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Projects/parity-signer/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

the other dependencies like husky also has the similar syntax like `const pkg = require('./package.json')`, so I am thinking the bundle should already have the `.json` file loader;

**Comment by vikiival** [comment]
@jacogr: Do you have any progress with this issue?

**Comment by jacogr** [comment]
To be honest, have not looked and it is not on my personal priority atm. Both places where webpack is used in these repos,

- https://github.com/polkadot-js/apps/blob/master/packages/react-api/webpack.config.js
- https://github.com/polkadot-js/extension/blob/master/packages/extension/webpack.config.js

It is working 100% as expected. All this stuff is being dog-fooded.

For react-native, we may need additional entries, as done here (although it does pick up the browser overrides normally) - https://github.com/polkadot-js/common/blob/master/packages/keyring/package.json#L29
