### ISSUE TITLE
Basic Enum `toJSON()` returns lower-case string for upper-case variants

### ISSUE THREAD

**Issue by shaopengw** [polkadot-js/api#1808]
There is an all upper-case variants Enum defined in our project and the type definition in JS lib is like 

```javascript
CurrencyId: {
  _enum: ['ACA', 'AUSD', 'DOT', 'XBTC']
},
```

But calling our custome RPC with this `CurrencyId` as parameter would return error:

```javascript
let v = await api.rpc.oracle.getValue("DOT");
```

> Error: getValue(key: OracleKey): Option<TimeStampedValue>:: -32602: Invalid params: unknown variant `dot`, expected one of `ACA`, `AUSD`, `DOT`, `XBTC`.

After some researching in @polkadot/api, it turns out to me that `toJSON()` was called on the `CurrencyId` param, but the return value is a lower-case string `dot`, instead of `DOT`.

https://github.com/polkadot-js/api/blob/deecf4853ec250745dcc2a770f073ad3b10ff452/packages/rpc-core/src/index.ts#L250

Which is caused by the `stringCamelCase` call in `toJSON`, if I was not wrong. The all upper-case variants looks like an edge case for the implementation. And I wonder why the json result needs to be camel case?

https://github.com/polkadot-js/api/blob/deecf4853ec250745dcc2a770f073ad3b10ff452/packages/types/src/codec/Enum.ts#L267-L271

**Comment by jacogr** [comment]
So that was actually recently changed - for basic enigma it used to just toJSON the number. Taking a step back - for value enum it generally has the camel case version in followed by the value. 

I think best here is probably to just adjust the basic enum to return the value as specified, no transforms.
