### ISSUE TITLE
JSON RPC: `UserRpc` and @polkadot/jsonrpc interfaces not consistent

### ISSUE THREAD

**Issue by shaopengw** [polkadot-js/api#1816]
### The inconsistency

`ApiOptions` requires `UserRpc` type (`Record<string, UserRpcMethod[]>`) for custom rpcs:

https://github.com/polkadot-js/api/blob/f6490217ec2b9354ed1a994700d9ae8501590a69/packages/api/src/types/index.ts#L52

https://github.com/polkadot-js/api/blob/f6490217ec2b9354ed1a994700d9ae8501590a69/packages/rpc-core/src/types.ts#L20

While `@polkadot/jsonrpc` default export uses `Record<string, RpcSection>` type

https://github.com/polkadot-js/api/blob/f6490217ec2b9354ed1a994700d9ae8501590a69/packages/type-jsonrpc/src/index.ts#L16-L27

There're gaps between user rpc method and `@polkadot/jsonrpc`, which makes it difficult to integrate custom JSON RPCs into polkadot apps.

### Difficulty for custom JSON RPC integration

Currently in polkdot apps, to integrate custom JSON RPCs, one needs to:

Firstly provide `rpc` api option while creating `ApiPromise`.

Secondly, in `@polkadot/react-components` `InputRpc`, combine `@polkadot/jsonrpc` interfaces with custom ones, to make custom rpc methods available in apps/toolbox/rpc selections. https://github.com/polkadot-js/apps/blob/4787ae852e049ae46ac94c355d9a7104f961e57e/packages/react-components/src/InputRpc/index.tsx

And this needs custom json rpc types to satisfy both `Record<string, RpcSection>`, and `Record<string, UserRpcMethod[]>`.

### Improvements?

I used the `any` type workaround to create a "mixed" type to fill the gaps [in our `@orml/jsonrpc` lib](https://github.com/laminar-protocol/orml.js/blob/master/packages/jsonrpc/src/oracle.ts), to avoid creating two different types.

To make custom json rpc integration easier, it might be better to unify `Record<string, RpcSection>` and `Record<string, UserRpcMethod[]>` types.

And further more, probably refactor `@polkadot/react-components` `InputRpc`, to use a single source of truth to get rpcs info, instead of using both `@polkadot/jsonrpc` and `api`.

**Comment by jacogr** [comment]
The UI has some way to go here - https://github.com/polkadot-js/apps/issues/2162

So have not actually looked at to where and what To make that possible. Thanks for the investigation.

**Comment by jacogr** [comment]
Reading through the descriptions, it actually needs to be combined with the linked issue. Most mentioned here is UI related, which is kinda out of scope for the API (that moves at it's own pace with own priorities).
