### ISSUE TITLE
This relative module was not found:  * ../package.json

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/api#1817]
Hey,
thanks for fixing #1802 by #1803 
also same issue occurs for [types](https://github.com/polkadot-js/api/blob/f6490217ec2b9354ed1a994700d9ae8501590a69/packages/types/src/index.ts#L22)

```bash
This relative module was not found:

* ../package.json in ./node_modules/@polkadot/metadata/node_modules/@polkadot/types/index.js, 
```

**Comment by jacogr** [comment]
That will be in 1.2I have a PR with some small cleanups that has not been pushed as of yet. 

As I mentioned elsewhere it certainly does not happen on any of the builds I have, so has not been a priority (cleaning up the bunch of checks/trys done there however was, hence the above merges)
