### ISSUE TITLE
Add support/types for offchain phragmen

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#1834]
Introduced in https://github.com/paritytech/substrate/pull/4517

**Comment by kianenigma** [comment]
I have seen this mistake quite often in naming and I am thinking of renaming my [**offline** phragmen](https://github.com/kianenigma/offline-phragmen) repo, which is actually not **offchain** phragmen, to something else to avoid confusion 😁

**Comment by jacogr** [comment]
Point taken :) Also done on the phone while in line waiting so it was a 

Ooops, yes, I forgot about that one, log it so "somebody" can take a look 

:)
