### ISSUE TITLE
signAndSend events in callback returning the same event across simultaneous calls

### ISSUE THREAD

**Issue by joshua-mir** [polkadot-js/api#1854]
rel/details: https://github.com/playproject-io/datdot-substrate/issues/18

When we make the same extrinsic call using multiple accounts (calling signAndSend on the same extrinsic using multiple pairs) practically simultaneously, the callback object appears to return the same events for every call - when each call should in reality return unique events.

Here is the exact code where this occurs:

https://github.com/joshua-mir/datdot-service/blob/e5ee50b3b5080c9cafaae71cae9deff2e6ec249b/index.js#L175-L228

I have confirmed that we see every expected event separately in the UI - so this appears to be an issue specific to events in callbacks.

**Comment by joshua-mir** [comment]
another anecdote - can reliably control which event is emitted by changing the order in which accounts call signAndSend :sweat_smile:

**Comment by jacogr** [comment]
So which event is emiitted? What is the output? 

So the issue is that to track the events, the extrinsic hash is used - since you are re-using the same extrinsic, that changes affect older & newer as more txs go through.

So would suggest not re-using the same tx.

**Comment by joshua-mir** [comment]
will make that change, thanks; as expected from what you've described here, it's always the last event (the event associated with the latest call) that is printed.

**Comment by jacogr** [comment]
Sadly the tx is not immutable :( (Otherwise it cannot reliable carry the signature)
