### ISSUE TITLE
Move jsonrpc definitions into interfaces (ala types/interfaces)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#1884]
The actual code around these are mostly repetition, type checking can be done by defining these as part of structures. (The tricky bits would be in updating the type definitions around these)

**Comment by jacogr** [comment]
Thanks for grabbing this one - you've done a couple in the last week and a bit, so you understand the boilerplate quite well. The definition injection should be fine, think the type generation bit just needs a bit of rework to make it hum along.

At least we've done something similar on the types, so we know it can work.

**Comment by axelchalon** [comment]
hey, not sure I understand the scope of this issue. what would the new jsonrpc definitions roughly look like? will the generation process essentially be about importing the return/param types directly instead of having them be a string reference? in which case the exports would be different before and after the refactor, is this correct?

**Comment by jacogr** [comment]
Think of `types/src/interfaces` - actually we can add the json definitions right in there, 

```
export default {
  types: {...},
  rpc: {...}
}
```

Since these are on a module basis. Where a pre-exiting module does not exist (e.g. `chain`), we can add it containing only rpc. So like we extract and generate types from interfaces, we can do exactly the same with RPC. (And get rid of `packages/jsonrpc` altogether)

So with the stuff there, it also means that we start having support (at least for decoration) on custom added RPCs as well.

**Comment by axelchalon** [comment]
Sorry for taking so long to tackle the issue, didn't mean to bog you down. :pray:
