### ISSUE TITLE
Vote's toHuman could be nicer

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#1887]
Vote's toHuman should show something like
```js
{
  aye: true,
  conviction: "Locked..."
}
```

2 ways:
- either keep Vote extends u8a, and craft a toHuman that does that
- or do Vote extends Struct, and craft a toHex/toU8a that encodes as per Substrate (closer to Rust code, Vote is struct)

edit: cc @axelchalon

**Comment by jacogr** [comment]
Since underlying it is a byte representation, the `extends Struct` def does not make any sense at all. I understand where you are coming from, but basically overriding everything in struct to cater for this is not sensible. 

There are a number `toHuman` which still need work.
