### ISSUE TITLE
Support for westend

### ISSUE THREAD

**Issue by bhaskarSingh** [polkadot-js/api#1895]
I am trying to connect to Westend via 
`const provider = new WsProvider('wss://westend-rpc.polkadot.io');
  const api = await ApiPromise.create({ provider});`

This is working fine on localhost but, when deployed on a custom domain, I am getting the below error
![Screenshot 2020-02-19 at 11 29 20 AM](https://user-images.githubusercontent.com/16613455/74813738-d15d5a80-531b-11ea-9956-f38bc3089eb1.png)

**Comment by jacogr** [comment]
Not sure why this is logged here, this is not API related, but rather specific infrastructure setup. 

The RPC setup specifically limits the domains that can connect to it, see `polkadot --help` for the CORS option.
