### ISSUE TITLE
Get block data through chain [getblock] and how to parse extrusics

### ISSUE THREAD

**Issue by gitcodeporter** [polkadot-js/api#1910]
{"jsonrpc":"2.0","result":{"block":{"extrinsics":["0x280402000b6015ad5c7001","0x1c040b0006840100","0x4d0284ffa032d6aef2f3a24a31c41cfdfb21f39ba3fdcfc9ed1f38b9167dacb2e43d747c01307e7c6e32da88dfba3c31ff48e2b58cf61416a941c1a4dab617a70267b808086b2a7de31392bffe8b17dad2427d7fa989a14277e059b4e26861f72faef3e98745003c000500ff366b0f9b0856591375550fc36267eb74db31fb35f5626228527efd394a2e1475130000e8890423c78a"],"header":{"digest":{"logs":["0x066175726120da7eb70f00000000","0x056175726101018c07fd2ec1b2fa66f01efbbcedfb8ff85e92b5527940056b9e4f7a7408e8704e5015dfcdb73c2693e91dc213042aed8063ca9be52f6831e79848372e77d6a007"]},"extrinsicsRoot":"0x0f4906e3acb1f5acf14bddcaf4176a4cfdc224f72087a1e277e7130cc86b5f9d","number":"0x6107","parentHash":"0x08b117b85aafc463fda120ea7dc975bc7bf95de35a6793cce07437e308b6074a","stateRoot":"0x7ebaf88439c12259a30ba60e41da4d94b8a211364b2dc2bf7e296dd016a4ac17"}},"justification":null},"id":1}

Get block data through chain [getblock] and how to parse extrusics

**Comment by jacogr** [comment]
The JS API - you can take a look at the get-started. https://polkadot.js.org/api/start/

The `api.rpc.chain.getBlock()` returns a fully parsed block as an [Extrinsic](https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/Extrinsic.ts)

All the RPC and queries parse via the JS API.

**Comment by gitcodeporter** [comment]
Is there an example of parsing extrusics? Want to get specific information about the transaction, such as from address and transaction amount

**Comment by jacogr** [comment]
On the block (which is returned parsed), the extrinsics is parsed as well. Depending on the extrinsic type, the args will contain the applicable information.

(When in doubt, just use the `.toHuman()` on any object returned (1.3.1+) to get a human-representation of what is in there.)
