### ISSUE TITLE
Custom generated types conflict with polkadotjs ones

### ISSUE THREAD

**Issue by shaopengw** [polkadot-js/api#1937]
I was using `generateInterfaceTypes` from `@polkadot/typegen@1.4.0-beta.36` to generate our custom interface types, which led to type conflicts. Our custom runtime module has an `Amount` type, while there is a deprecated `Amount` type in `@polkadotjs/types`:

https://github.com/polkadot-js/api/blob/775697f51e57ecb58e386f0869d4cb036c685dbc/packages/types/src/augment/registry.ts#L16

A quick workaround might be removing the deprecated types in polkadotjs side, since they're "deprecated". And is there any general solution for types conflicts?

**Comment by jacogr** [comment]
As a quick fix, we can remove the deprecated here. It is for old metadata versions which

- we want to drop anyway
- we don’t fail on construction anymore
- tests may need adjustments

For 1.5 onwards can look at a better way of merging modules (conflicts) and types - user-specified should override.

**Comment by jacogr** [comment]
One thing do add here as well is the aliasing, it should be at the point to see the light of day (and it will convert types between different modules). It is employed already for Polkadot/Kusama and should be exposed - https://github.com/polkadot-js/api/blob/master/packages/types/src/known/overrides.ts#L8-L34
