### ISSUE TITLE
User-defined struct properties clash with `Codec` and `Struct` properties

### ISSUE THREAD

**Issue by monitz87** [polkadot-js/api#1946]
# Problem

Let's say I have the following definition:

```
"Document": {
  "name": "DocumentName",
  "uri": "DocumentUri",
  "hash": "Text"
}
```

After generating types with `@polkadot/typegen`, the following error will appear where `Document` is defined:

```
Type 'Document' does not satisfy the constraint 'Codec'.
  Types of property 'hash' are incompatible.
    Type 'Text' is missing the following properties from type 'H256': bitLength, subarray, BYTES_PER_ELEMENT, buffer, and 21 more.
```

The reason, of course, is that my `Document`'s `hash` property is shadowing `Codec`'s `hash` property. This would also happen if I used `registry`, `isEmpty`, `encodedLength`, etc (all reasonable names for props).

# Suggestion

Since any change to `Codec` or `Struct` would break a lot of stuff, I suggest adding a note to the docs (probably in the section regarding user-defined types and maybe in the substrate docs as well) advising devs to either prefix their struct variables in some manner or listing the property names that would cause conflicts (`hash`, `registry`, `isEmpty`, etc)

**Comment by jacogr** [comment]
As discussed, this is not going to happen - we don't break userspace for existing users unless there is no other choice.

Over-the wire everything is binary encoded using SCALE, with no naming. So you can easily adjust the interface to name your specific field what you like. So in your case -

```
"Document": {
  "name": "DocumentName",
  "uri": "DocumentUri",
  "documentHash": "Text"
}
```

The above can be added to the FAQ. So marking as "wontfix" & "documentation".
