### ISSUE TITLE
How to judge whether a transaction is successful

### ISSUE THREAD

**Issue by gitcodeporter** [polkadot-js/api#1956]
How to judge whether a transaction is successful？

`const allEvents = await api.query.system.events.at(blockHash)
`
 RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occured: Client(UnknownBlock("State alread

**Comment by jacogr** [comment]
So by default Substrate runs in pruning mode with a block length of 256 blocks, as stated here - https://polkadot.js.org/api/start/api.query.other.html#state-at-a-specific-block

If you want to access much older blocks, you need to run your node with `--pruning archive` which will keep all the state.

**Comment by gitcodeporter** [comment]
block.extrinsics[0].method.callIndex

How is the callindex defined? What is the callindex corresponding to the transfer?

**Comment by jacogr** [comment]
callIndex is defined by the metadata. So there is no "standard" for transfer, it would depend on the index of the module in the metadata and the transfer method inside that.

Try `block.extrinsics[0].toHuman()` to get a feel on the actual available methods.
