### ISSUE TITLE
How to transfer transactions

### ISSUE THREAD

**Issue by gitcodeporter** [polkadot-js/api#1971]
`const from = 'nx2eQN5y2B4eZRKFHsjyTG7vSP8Cq3iub9JwAQojVpM2CZK';
const to = 'nGyyxvzLHvDmzQx5viuDNTp7ZkT12DtkCEFNERHsYRw64wT';

const keyring = new Keyring({ type: 'sr25519' });
const fromPair = keyring.getPair(from);
const { nonce } = await api.query.system.account(from);
api.tx.balances.transfer(to, value).signAndSend(fromPair, { nonce }, ({ events = [], status }) => {
      console.log('status: ', status)
      console.log('Transaction status:', status.type);
      if (status.isInBlock) {
            console.log('Included at block hash', status.asInBlock.toHex());
            console.log('Events:');
            events.forEach(({ phase, event: { data, method, section } }) => {
                  console.log('\t', phase.toString(), : ${section}.${method}, data.toString());
            });
       } else if (status.isFinalized) {
             console.log('Finalized block hash', status.asFinalized.toHex());
       }
});
`

Error: Unable to retrieve keypair 'nx2eQN5y2B4eZRKFHsjyTG7vSP8Cq3iub9JwAQojVpM2CZK'
2020-02-28 03:59:21 852: at assert (/user/node_modules/@polkadot/util/assert.js:34:11)
2020-02-28 03:59:21 852: at Pairs.get (/user/node_modules/@polkadot/keyring/pairs.js:33:22)
2020-02-28 03:59:21 852: at Keyring.getPair (/user/node_modules/@polkadot/keyring/keyring.js:225:24)
2020-02-28 03:59:21 852: at assetsTransfer (/user/assets:37:30)
2020-02-28 03:59:21 852: at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by gitcodeporter** [comment]
The official information is such a transfer, is it not necessary to sign the account private key?

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/keyring.html#adding-accounts
