### ISSUE TITLE
ApiPromise's .queryMulti is only subscription based

### ISSUE THREAD

**Issue by monitz87** [polkadot-js/api#1974]
Right now the only way of using queryMulti is providing a callback that gets called whenever the stored values change. It would be useful if there was also a callback-less version that simply returned the values wrapped in a promise (as with other query methods)

**Comment by jacogr** [comment]
Ok, so unlike what I said... the typings are actually wrong. It actually does work, here it is on the apps UI (with no pesky type checking) -

![image](https://user-images.githubusercontent.com/1424473/75563034-e9368c00-5a49-11ea-8975-1fcea87bfcdb.png)

So will get the typings updated.
