### ISSUE TITLE
When the storage parsing fails, the promise is not rejected.

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#1984]
I think the reason is that storage update did not handle the error.

https://github.com/polkadot-js/api/blob/master/packages/rpc-core/src/index.ts#L250-L257
The error thrown by the formatOutput was not handled properly.

If I change it to this it will work: 
```javascript
const update = (error?: Error | null, result?: any): void => {
  if (error) {
    l.error(createErrorMessage(method, error));
    observer.error(error)
  }
  try {
    observer.next(this.formatOutput(method, params, result));
  } catch(error) {
    observer.error(error)
  }
};
```

**Comment by jacogr** [comment]
Yes, good catch, that is unprotected. Your change will work.
