### ISSUE TITLE
How to get the confirmed block height

### ISSUE THREAD

**Issue by gitcodeporter** [polkadot-js/api#1988]
How to get the confirmed block height

**Comment by jacogr** [comment]
I would strongly suggest reading the documentation, all the RPC calls are there. 

Specifically https://polkadot.js.org/api/substrate/rpc.html#chain

**Comment by gitcodeporter** [comment]
How to get transaction records through transaction hash? Not a block hash

**Comment by jacogr** [comment]
It is not-unique, so it is not an identifier to use.
