### ISSUE TITLE
Broken links everywhere

### ISSUE THREAD

**Issue by bedeho** [polkadot-js/api#1996]
Just about every package has broken links to what seems to be the main documentation for the package, fixing this would significantly improve the onboarding experience of a new developer attempting to become familiar with all of these packages.

**Comment by jacogr** [comment]
PRs welcome where they are found. The entry point for all docs should be https://polkadot.js.org/api/

**Comment by jacogr** [comment]
I am closing this since I have no idea what to do with it - there are no pointers to what or suggestions that I can action.
