### ISSUE TITLE
Hardware wallet signer integration

### ISSUE THREAD

**Issue by akru** [polkadot-js/api#2002]
**Motivation**

For security reasons, hardware cryptocurrency wallets are very popular.
It could be wonderful to have the support of hardware wallets in Polkadot JS.

**Comment by jacogr** [comment]
The apps UI does support it. (Ledger, where an app is available). Additionally the ui-keyring has extensible support. The API itself only deals with transport, the signing can happen anywhere and it managed externally in the keyrings.

**Comment by akru** [comment]
Got it, thank you for explanation!
It’s a question to key ring extension. Do you known extensions with support of popular wallet like Trezor or Ledger?

**Comment by jacogr** [comment]
Ledger is in development and pre-approval, like I mentioned the ui-keyring has support for it, and the apps UI does support it. https://github.com/Zondax/ledger-kusama

**Comment by akru** [comment]
Thank you
