### ISSUE TITLE
"__dirname" broke react native applications

### ISSUE THREAD

**Issue by hanwencheng** [polkadot-js/api#2006]
The `__dirname` used in [@polkadot/type](https://github.com/polkadot-js/api/blob/master/packages/types/src/index.ts#L9) and [@polkadot/util](https://github.com/polkadot-js/api/blob/master/packages/api/src/index.ts#L9) break the browser side applications (react native case).

I am currently use babel plugin to rewrite `__dirname` to static values as a walkaround.

if an application is using `webpack`, then the following setting could solve as well
```
{
    node: {
        __dirname: false
    }
}
```

It would be nice for other browser-side applications to skip this step if polkadot.js could use `peerDependency` to specify related dependencies to prevent the missmatched packages under `@polkadot` scope instead of using [detectVersion](https://github.com/polkadot-js/common/blob/master/packages/util/src/detectPackage.ts) function. Then they do not need to do it manually, also there is a bonus to flatten the dependency graph and remove duplicated dependencies.

**Comment by jacogr** [comment]
There is a exceptionally good reason why it is done manually - especially when you start injecting extensions into the pages (i.e. web). After going through the peerDependencies route, this is the only solution that cut down significantly on the support overhead.

Thanks, though, good to have an RN work-around.

**Comment by puti94** [comment]
I have the same problem，Here's how I solved it：
`
module.exports = {
  transformer: {
    babelTransformerPath: "<customPath>",
    ...
  }
}
`
`
const upstreamTransformer = require('metro-react-native-babel-transformer');
const path = require('path');
module.exports.transform = file => {
  if (file.filename.includes('@polkadot') && file.src.includes('__dirname')) {
    let src =
      `var __dirname = "${path.dirname(
        path.resolve(__dirname, file.filename),
      )}"; \n` + file.src;
    return upstreamTransformer.transform({
      ...file,
      src: src,
    });
  }
  return upstreamTransformer.transform(file);
};
`
But I don't think it's a good idea. I hope there is a good solution
