### ISSUE TITLE
use limited semver for package dependencies

### ISSUE THREAD

**Issue by subtly** [polkadot-js/api#2010]
Recently our code broke with the update to 1.5.

We were using an explicit version of "1.2.1" for @polkadot/api so our expectation was that our code would continue to work, independent of future releases.

What actually happened is that, after 1.5.1 came out, and we updated dependencies (yarn install) version 1.5.1 of @polkadot/types was installed. But in 1.4 extrinsic types were moved, and this broke @polkadot/api v1.2.1.

In polkadot/api the package.json specifies types as "^1.2" instead of a more limited version range, and so when 1.4 and 1.5 came out, updating node modules caused mismatched versioning (/api was still at 1.2.1 but /types updated to 1.5). End result is code not working. Expected result is that we can include @polkadot/api as a dependency with a static version and not worry about future updates to its dependencies (like /types).

We notice this issue is fixed in 1.5 for @polkadot/types, however keyring, util, util-crypto and a few 3rd-party dependencies still allow updated versions. If one of these dependencies is upgraded in a way that isn't backwards compatible, it'll break dependent software.

We ask that limited version ranges are adopted in packages like @polkadot/api so the code that is deployed and published is less prone to surprise version updates. That said, we also recognize that the software is a work in progress; in this case we would ask that dependencies which are prone to be broken by upgrades are marked as such and documented in readme so there's some notice as to what might break if/when developers reinstall dependencies or deploy code to a fresh environment.

**Comment by jacogr** [comment]
The breakages are all documented in the CHANGELOG, or rather should be.  For instance in the 1.4.1 CHANGELOG -

- Move `types/primitive/{extrinsics, generic}` to `types/{extrinsics, generic}`

(If a mistake did happen there, or one missed, would need to retrospectively add it - really try to make sure it is always updated with the changes... mistakes may slip n)

For the types it is always recommended to import via `@polkado/types` to not have to worry about the internals. Where it does create issues (there are a couple of these in the CHANGELOG), is where things move from `primitive` to `interfaces` - won't be covered there.

**Comment by subtly** [comment]
Thanks for the update and we did see its explicit now. I'm not well versed on JS require syntax but when we tried manually importing polkadot/types it still imported types from within api.

The CHANGELOG notes that extrinsic types were moved, but it doesn't indicate that that breaks backwards compatibility and its not reflected in the semver change which was MINOR (from 1.2 -> 1.4). It would be ideal for upstream changes that are MINOR or PATCH not to break across versions. Great way to keep consensus across software deployments. https://semver.org

Presume this issue will be closed 👍

**Comment by jacogr** [comment]
Ok, the reason why it is not marked is because it is an internal change. Imports always should be done directly via `@polkadot/types`. There is obviously an issue when stuff moves to interfaces, those are marked breaking through. (There is a lot more here I want to do but am careful on those... really hate breaking userspace :()
