### ISSUE TITLE
`tx.sign` requires nonce but not enforced by types

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2013]
```
const tx = api.tx.balances.transfer
tx.sign(pair)
```

this signs the transaction with nonce `0`, which is kind of unexpected.

`signAsync` does fetch nonce, but docs doesn't really indicate the difference between `sign` and `signAsync`

**Comment by jacogr** [comment]
It is not unexpected, just unclear. Sign only operates on what you give it. Moving to docs.
