### ISSUE TITLE
Error while sending an extrinsic what takes a structure containing an enum

### ISSUE THREAD

**Issue by lovesh** [polkadot-js/api#2037]
I am using Substrate version pre-v2.0-3e65111 (latest stable) and polkadot-js version 1.6.2.
I am accepting public keys of several kinds as part of an extrinsic. Different public keys can be of different sizes like Sr25519 is 32 bytes, Secp256k1 is 33 bytes. On the Substrate Node side I have following enums and structure. 
```rust
#[derive(Encode, Decode, Debug, Clone, PartialEq, Eq)]
pub enum PublicKey {
	// XXX: Sr25519([u8;32]) does not work either
    /// Public key for Sr25519 is 32 bytes
    Sr25519(Bytes32),
    /// Public key for Ed25519 is 32 bytes
    Ed25519(Bytes32),
    /// Compressed public key for Secp256k1 is 33 bytes
    Secp256k1(Bytes33),
}

#[derive(Encode, Decode, Clone, PartialEq, Debug)]
pub struct Detail {
    public_key: PublicKey,
    ... some more fields
}
```

Inside `decl_module`, i have this extrinsic
```rust
fn new(origin, detail: Detail) -> DispatchResult {
```

The JSON types look like this and i pass them to `ApiPromise.create`
```
  "Bytes32": {
    "value": "[u8;32]"
  },
  "Bytes33": {
    "value": "[u8;33]"
  },
  "PublicKey": {
    "_enum": {
      "Sr25519": "Bytes32",
      "Ed25519": "Bytes32",
      "Secp256k1": "Bytes33"
    }
  },
  "KeyDetail": {
    "public_key": "PublicKey",
    .... more fields
  }
```

When I try to send the extrinsic using polkadot-js's `api.tx.module.new`, i create the enum as
```
const publicKey = {
	Sr25519: '0x9999999999999999999999999999999999999999999999999999999999999999',
};
```

But i get the following error
```
createType(MultiSignature):: Unable to create Enum via index 46, in Sr25519, Ed25519, Secp256k1
```
The `index 46` changes on different runs.

**EDIT:**
When using the [polkadot-js UI](https://polkadot.js.org/apps), after adding the above JSON types even transfer fails with the above error.
When I had the simpler Enum variants, i.e. the variants were not structures, like below the extrinsic used to work.
```rust
#[derive(Encode, Decode, Debug, Clone, PartialEq, Eq)]
pub enum PublicKey {
    /// Public key for Sr25519 is 32 bytes
    Sr25519,
    /// Public key for Ed25519 is 32 bytes
    Ed25519,
```

**Comment by jacogr** [comment]
Everything looks fine there. Did you base your node on Substrate node or node-template. Specifically looking at how Lookup and address is defined in your node and what spec_name is. 

(Thinking about this - https://polkadot.js.org/api/start/types.extend.html#node-and-chain-specific-types)

**Comment by lovesh** [comment]
I used node-template. Don't follow the other part of your comment

**Comment by jacogr** [comment]
So for node-template, you need to add additional types. As per the link I posted, the Address and Lookup types in node-template is customized from Substrate node. So you need to override those. 

https://polkadot.js.org/api/start/types.extend.html#node-and-chain-specific-types 

The above explains the differences in types between the two, what the impact is and how to override types to cater for this customization.

**Comment by lovesh** [comment]
@jacogr I don't which files of the Substrate nodeIi should be looking at. Going by the occurrence of `type Lookup` or `type Address =`, i looked at `frame/nicks/src/lib.rs` and the mock files of babe and grandpa but they don't seem useful matches. Also if these mismatch, basic transactions like balance transfer should fail, correct? Or are there other types i should look at?

**Comment by jacogr** [comment]
Yes. If the Address and lookups are wrong transactions will be affected. 

Like you added the types for your additions, add the “Address: AccountId” (formatted correctly) and the LookupSource override. (The link I posted has both)

**Comment by jacogr** [comment]
There was also this posted on SO today, maybe the explanation is clearer - https://stackoverflow.com/questions/60660590/how-to-use-polkadot-js-api-with-substrate-node-template

**Comment by lovesh** [comment]
I tried both variations:
```
"Address": "AccountId",
"LookupSource": "AccountId",
```
and
```
"Address": "GenericAddress",
"LookupSource": "Address"
```
But same error.
I have updated my original post with some extra info.

**Comment by jacogr** [comment]
Ahhh...

Ok, you defined the following -

```
"Bytes32": {
    "value": "[u8;32]"
  },
  "Bytes33": {
    "value": "[u8;33]"
  },
```

So it is a struct with a "value" entry.

Try -

```
"Bytes32": "[u8;32]",
"Bytes33": "[u8;33]"
```

(The construction, as you've done it, stays the same). Not 100% convinced this will solve it, since the SCALE encoding should be equivalent, but worth a try.

**Comment by lovesh** [comment]
Are you making `Bytes32` a tuple struct in or a type alias?

**Comment by jacogr** [comment]
Just an alias. But that should not solve anything.

**Comment by jacogr** [comment]
And those the only types you've added?

**Comment by lovesh** [comment]
Other types are similar like `Bytes64` and `Bytes65` and types similar to `Detail`. I have a macro to generate various `Bytes*` and implementations of some traits like Default, PartialEq, etc for them.

**Comment by jacogr** [comment]
Can you post the full list of overrides? The MultiSignature worries me a bit, so trying to see where that comes from. (It is early in the payload and tx, before we get to "detail")

**Comment by lovesh** [comment]
@jacogr Thanks for helping me private chat. As @jacogr pointed out, I had a type named `Signature` in my modules which was conflicting with the base `Signature` type. His proposed solution was to rename `Signature` to something else like  `ModSignature` in the types passed to `Api.create` and use the `typeAlias` option to specify the renaming.
```
Api.create({
  types: {
    ...
    // everything the same, expect the following, name change
   ModSignature: {
     _enum: { ... }
   }
  },
  typesAlias: {
    // module name
    sigmod: {
      // type rename
      Signature: 'ModSignature'
    }
  }
})
```
This worked for me.
