### ISSUE TITLE
Queries are very slow

### ISSUE THREAD

**Issue by faboweb** [polkadot-js/api#2039]
The query `api.query.staking.bonded` takes 38s. This is not really usable to be queried reactively for users. `api.query.balances.locks` takes 6s. So it is not just one query. `api.isReady` takes also 35s to finish, slowing down initial loading times.

We use a dedicated node. Is there something we are doing wrong? How can we improve these loading times? Can we query the node in some other more effective way?

**Comment by jacogr** [comment]
Check the node itself. The RPC class simply returns when the node gives a response. Doing a query against public hosted nodes (UI, chain state tab) for bonded comes back <1s. (Populated an unpopulated)
