### ISSUE TITLE
Coloured syntax highlighting missing in code snippets generated from TypeDocs in API docs

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#204]
Currently the examples that are generated from Markdown include coloured syntax highlighting as shown below
<img width="688" alt="screen shot 2018-10-04 at 18 53 32" src="https://user-images.githubusercontent.com/6226175/46492948-ead53380-c806-11e8-884d-f997be27b95c.png">

However the API Docs themselves that are generated from TypeDoc/TSDoc labels in code comments sometimes also contain an `@example` code snippet, however it does not contain any coloured syntax highlighting. 

<img width="863" alt="screen shot 2018-10-04 at 18 56 16" src="https://user-images.githubusercontent.com/6226175/46493074-4a334380-c807-11e8-86ca-2ff7996fe225.png">

The approach used to achieve generation of multi-line code snippets including spaces between lines of code was to wrap the code with `<PRE><CODE> ... </CODE></PRE>` and to add `<BR>` between lines of code where a newline was desired. However it does not colour the code based on the syntax used.

One possible solution could be to use [Google Code Prettify](https://github.com/google/code-prettify), which according to the usage instructions simply requires applying their CSS class to one of the elements i.e. `<PRE class="prettyprint">` or `<CODE class="prettyprint">`, and somehow loading their JS file in the root HTML document (or just injecting their CDN script) that's generated by building with Gitbooks  (i.e. `<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>`). However I tried following this approach, but it did not work, and may be because CSS classnames may not be added to HTML elements that are used in TypeDocs.

**Comment by jacogr** [comment]
Checkout the gitbook plugins, there may be one available to syntax highlighting.
