### ISSUE TITLE
submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof

### ISSUE THREAD

**Issue by testrain** [polkadot-js/api#2061]
On `https://polkadot.js.org/apps/#/staking/actions`, when I was trying to collect payout reward, it returns me with this error

**Comment by jacogr** [comment]
This is generated fro the chain. It is not the API.

In this specific case there was a council proposal to make a fix to a migration key that was missed. Refresh the UI.
