### ISSUE TITLE
api.query.staking.currentEraStartSessionIndex is not implemented

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#2067]
Hi,

We were using this code to calculate the era progress at a determined block height:

```
const currentEraStartSessionIndex = await api.query.staking.currentEraStartSessionIndex.at(blockHash);
```

But currently (api v1.8.0-beta.1) this query doesn't work. Is there an alternative to calculate the era progress at some block height?

Thank you!

**Comment by jacogr** [comment]
When it is not on the API, it means -

- it is not in the runtime
- it is not exposed as part of the metadata

https://polkadot.js.org/api/start/basics.html#metadata

This is not an API issue, it will only ever decorate what is on the metadata. There is no hardcoding. The API is dynamically decorated.

If you want to see what is on the specific chain -

- Connect to the chain via the apps UI, explore the storage
- This is generated based on the latest (Substrate master) metadata - https://polkadot.js.org/api/substrate/storage.html (it will vary based on the chain connected to)
