### ISSUE TITLE
Support `at` queries for derive queries

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#2081]
It'd be great to have support of `at` for derive queries:
e.g `api.derive.democracy.referendumInfo.at(BlockHash, RefIndex)`

The reason in this particular case is that each client needs to implement its own logic (e.g for backward compatibility or `referendumInfoOf` that recently changed), although the compatibility layer has already been implemented in derive.

**Comment by jacogr** [comment]
Closing this as a "wontfix". Derives are only realtime and will never have that level of complexity - same goes for the `.range` & `.historic` queries.
