### ISSUE TITLE
Is there some way to get balance and nonce without websocket?

### ISSUE THREAD

**Issue by XuNeal** [polkadot-js/api#2092]
Hey 
I'm building a mobile app to transfer polkadot by react-native. polkadot-js/api is great, as though the polkadot wallet is just a small part in my app, keeping a long connection of websocket seems too heavy. Is there some way to get balance and nonce without websocket? some like restful API?

I have made some research, and find the node provides a http jsonrpc, but it doesn't provide some simple api equals to `balance.account(AccountId)`. I'm wondering if the polkadotjs/api is based on the rpc.state?

**Comment by jacogr** [comment]
`HttpProvider` - does not support subscriptions.

And yes, everything in Polkadot/Substrate is based on the state, which means -

- the API needs the metadata
- the API needs to decorate based on metadata
- The API will encode the storage keys based on metadata
- encoded calls go over generic RPCs
- responses are decoded based on the SCALE codec

**Comment by XuNeal** [comment]
Ok, I get it now, thanks.
And I find a blog to show how to get balance through the http provider: https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/
