### ISSUE TITLE
api.tx.democracy.vote has wrong types

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#2095]
When using `@polkadot/api@1.9.4-beta`.
Contructing the following tx: 
```js
const voteTx = api.tx.democracy.vote(referendumId, { Standard: { balance: undefined, vote: { aye, conviction } } });
```

I get a TS errors:
> Object literal may only specify known properties, and 'Standard' does not exist in type 'Uint8Array | Vote | { aye: boolean; conviction?: number | "None" | "Locked1x" | "Locked2x" | "Locked3x" | "Locked4x" | "Locked5x" | "Locked6x" | undefined; }'

When forcing the type to any, the TX works:
```js
const params = { Standard: { balance: undefined, vote: { aye, conviction } } } as any;
const voteTx = api.tx.democracy.vote(referendumId, params );
```

And if I use the older 
```js
const voteTx = api.tx.democracy.vote(referendumId, { aye, conviction });`
```

TS is happy, but voting fails:
> Struct: failed on 'vote':: Cannot construct unknown type AccountVote createType.js:68:10

It looks like what TS has the old types.

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/typescript.user.html
