### ISSUE TITLE
Unable to decode Vec on index 1 createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 35, in Ed25519, Sr25519, Ecdsa

### ISSUE THREAD

**Issue by Bopsi** [polkadot-js/api#2110]
async getBlock(blockNumber: Number): Promise<string> {
        await this.init();
        try {
            let blockHash = await this.api.rpc.chain.getBlockHash(blockNumber);
            blockHash = this.toJson(blockHash);
            debug('Block Hash of block %d is %o ;', blockNumber, blockHash);
            let _block = await this.api.rpc.chain.getBlock(blockHash);
            _block = _block.toHuman({isExtended: true});
            debug('Block %d ===> %j', blockNumber, this.toJson(_block));
            let blockKey = `block:${blockNumber}`;
            //let timestamp = await this.api.query.timestamp.now.at(blockHash);

            let block = {
                ..._block.block,
                hash: blockHash,
                number: blockNumber,
                //timestamp: timestamp
            };

            try {
                await zadd('block.keys', blockNumber.toString(), blockKey);
                await set(blockKey, JSON.stringify(block));
                await publish('blockUpdated', JSON.stringify(block));
                debug('Block %d synced ;', blockNumber);
                return JSON.stringify(block);
            } catch (err) {
                debug('Block %d sync failed. Error: %O ;', blockNumber, err);
            }
        } catch (e) {
            debug('Block %d fetch failed. Error: %O ;', blockNumber, e);
            return null;
        }
    }

    toJson(type) {
        return JSON.parse(JSON.stringify(type));
    }

getBlock(2617) returns-

 

> watcher:BlockProcessor Block Hash of block 2617 is '0x16dab292ae96544764ef6b6ff14c69830c303c402ee07605fb787540e5154f33' ; +0ms
>   watcher:BlockProcessor Block 2617 ===> {"block":{"header":{"parentHash":"0x42729c09cabc0fafaba7bf59560499578693c34cfa2b056bdae119ff24641c9b","number":"2,617","stateRoot":"0x35d924060196f879529b1e5f94d9e6405eddf2705dc7e12329216d808586e6ce","extrinsicsRoot":"0xf9cceba20f8e44d9079b5c3af304bd2bc77864c0b903b22bc615b2bb6a6d568f","digest":{"logs":[{"PreRuntime":["aura","0x24b1bf0f00000000"]},{"Seal":["aura","0xd06283835e1129a940c683f2c13081d50d8fcdd0429ec68afccbdd8003185c09d4873eae4f5025205b9810cdee7708fc11105c13242b5aace2d159ca35724e8e"]}]}},"extrinsics":[{"method":{"callIndex":"0x0200","section":"timestamp","method":"set","args":["1,585,325,784,000"],"documentation":[" Set the current time.",""," This call should be invoked exactly once per block. It will panic at the finalization"," phase, if this call hasn't been invoked by that time.",""," The timestamp should be greater than the previous one by the amount specified by"," `MinimumPeriod`.",""," The dispatch origin for this call must be `Inherent`."]},"isSigned":false}]},"justification":"0x"} +84ms
>   watcher:BlockProcessor Block 2617 synced ; +4ms

getBlock(18) returns -

>  watcher:BlockProcessor Block Hash of block 18 is '0xe1bfd7a3f9e7f59caeda8e2e69acc35943485ce5efd61d0274e61abcd6e599dc' ; +51s
> Unable to decode Vec on index 1 createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 35, in Ed25519, Sr25519, Ecdsa
> 2020-03-28 14:05:49        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 35, in Ed25519, Sr25519, Ecdsa
>   watcher:BlockProcessor Block 18 fetch failed. Error: Error: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 35, in Ed25519, Sr25519, Ecdsa
>   watcher:BlockProcessor     at CatchSubscriber.pipe.error [as selector] (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/@polkadot/rpc-core/index.js:200:38)
>   watcher:BlockProcessor     at CatchSubscriber.error (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/operators/catchError.js:48:31)
>   watcher:BlockProcessor     at MapSubscriber._next (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/operators/map.js:52:30)
>   watcher:BlockProcessor     at MapSubscriber.Subscriber.next (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/Subscriber.js:66:18)
>   watcher:BlockProcessor     at SwitchMapSubscriber.notifyNext (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/operators/switchMap.js:89:26)
>   watcher:BlockProcessor     at InnerSubscriber._next (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
>   watcher:BlockProcessor     at InnerSubscriber.Subscriber.next (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/Subscriber.js:66:18)
>   watcher:BlockProcessor     at CombineLatestSubscriber.notifyNext (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/observable/combineLatest.js:97:34)
>   watcher:BlockProcessor     at InnerSubscriber._next (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
>   watcher:BlockProcessor     at InnerSubscriber.Subscriber.next (/home/bappaditya/DRIVE_E/projects/borlaug/Block Explorer/watcher/node_modules/rxjs/internal/Subscriber.js:66:18) ; +58ms

I am using polkadot version 1.4.1 (also tried with 1.8.1) with a substrate alfa 5 chain.

Block 18 contains an extrinsic that is custom made in the chain. This error always occurs when we try to fetch such blocks. 

What is the solution?

**Comment by jacogr** [comment]
Make sure you have the correct types for the chain. Specifically, on node-template the Address type has changed. So this would seem like the older blocks has the old type 

https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

**Comment by jacogr** [comment]
Related #845

**Comment by Bopsi** [comment]
We are using the node-template pattern, so adding following to types did the trick. Thanks @jacogr 

```
types: {
  Address:'AccountId',
  LookupSource:'AccountId'
}
```
