### ISSUE TITLE
Unable to decode Vec on index 3 createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args'

### ISSUE THREAD

**Issue by xianggy** [polkadot-js/api#2111]
the code: 
```
...
const hash = await api.rpc.chain.getBlockHash(number);
const block = await api.rpc.chain.getBlock(hash);
console.log(block.toString());
```

`number` is 1572210, return:
`{"block":{"header":{"parentHash":"0x242fa04db1861897dc94bb6c013d3da9c2ac64cce4769ac1daf4d729ad23aaa9","number":1572210,"stateRoot":"0x4fb3909ba1325cbf30e5d5fa64566c9efb13130dcc8307d50cc06c2db6177e61","extrinsicsRoot":"0xb6cf6d515f31a8375d3f308147d8375b2986b794fd7a91723a6547db14e29f56","digest":{"logs":["0x064241424534028b0000004ac4be0f00000000","0x054241424501011018d1f10f91c05a01843ed94cbeea75047ca7c7b831bb17c7fd73a61bbf331976d581c4bb54972df789288d7e9c40d6b7af9b0e77f3368cef6219ada21ad38f"]}},"extrinsics":["0x280402000b608618077101","0x1004140000"]},"justification":"0x"}
`
`number` is 1572211, return:
Unable to decode Vec on index 3 createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 128, in Standard, Split
2020-03-28 20:13:10        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 128, in Standard, Split
(node:13168) UnhandledPromiseRejectionWarning: Error: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 128, in Standard, Split
```

OS: macOS 10.14.6
version: polkadot-0.7.28, "@polkadot/api": "^1.8.1"

so how to solve this problem,  thank you.

**Comment by jacogr** [comment]
The API does not have historic functionality atm. It decoded everything using -

- the latest chain metadata (as retrieved)
- the types based on the current runtime version

So if you go beyond the last runtime upgrade, you would need to inject the correct metadata for that block along the types.

This will be solved (at some point), using `.historic` queries, but at this point you need to do all the heavy lifting yourself.

Related https://github.com/polkadot-js/api/issues/845
