### ISSUE TITLE
Parsing Issue with Custom Type in `Constants` view

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#2112]
There seems to be some parsing error when using a custom struct in the `constants` tab of the Polkadot JS Apps.

There might be a bug in Polkadot JS Apps, but in general here is the steps to get what I think you want.

We have a custom type:
```
#[derive(Encode, Decode)]
struct Rule {
    name: Vec<u8>,
    version: u32,
    ops: Vec<u32>,
}
```

We place a `const` in the `decl_module` so it exposes it in the metadata:
```
         /// Rules for the PoE
        const rule: Rule = Rule {
            name: b"rule 1".to_vec(),
            version: 1,
            ops: vec![2]
        };
```

Then we start our chain. In Polkadot JS Apps, I register a new custom type:
```
{
  "Rule": {
    "name": "Vec<u8>",
    "version": "u32",
    "ops": "Vec<u32>"
  }
}
```

Then I go look at the constants in the pallet:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1860335/77825708-6ae20e00-710b-11ea-893b-1c2da81d3b0e.png">

It seems it does not correctly detect the length prefix. When i parse the bytes on my own, it works:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1860335/77825726-8816dc80-710b-11ea-89d0-0c294b580dc7.png">

**Comment by shawntabrizi** [comment]
```
          constants: [
            {
              name: rule,
              type: Rule,
              value: 0x1872756c652031010000000402000000,
              documentation: [
                 Rules for the PoE
              ]
            },
 ```

Let me know if you need anything else.

**Comment by jacogr** [comment]
Should be in apps in around 20 mins - if that doesn't solve it, can re-open, but should be correct now. (Should have been fixed originally instead of hacked around for bytes-only)

**Comment by shawntabrizi** [comment]
can confirm it is fixed

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1860335/77833130-4736bc00-713b-11ea-9387-77c7925e6509.png">

thanks!
