### ISSUE TITLE
RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature"))

### ISSUE THREAD

**Issue by wuminzhe** [polkadot-js/api#2128]
When I do transfer, I get the error. My chain is based on substrate v2.0.0-alpha.4. api version is 1.9.1

**Comment by wuminzhe** [comment]
message from chain log:
`
Failed to submit extrinsic: Extrinsic verification error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature"))
`

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

**Comment by wuminzhe** [comment]
@jacogr Thanks, but why I can do transfer with polkadot.js.org?

**Comment by wuminzhe** [comment]
I do nothing to node template. how can I fix the problem?
Address and LookupSource maped.

**Comment by jacogr** [comment]
polkadot.js.org/apps/ injects types specifically based on spec - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/node-template.ts#L8

**Comment by wuminzhe** [comment]
@jacogr thank you very much
