### ISSUE TITLE
Error: Unable to retrieve keypair '0x1cc77cd4e914553a655fbc52923618d5be5eb9cb22271b2f4d001422d89ec225'

### ISSUE THREAD

**Issue by shareven** [polkadot-js/api#2133]
@polkadot/api: ^1.9.1

```js
try {
   let u8a=hexToU8a('0x1cc77cd4e914553a655fbc52923618d5be5eb9cb22271b2f4d001422d89ec225')
   console.log('u8a:',u8a);             
   let keyPair = keyring.getPair(u8a);
   if (!keyPair.isLocked) {
       keyPair.lock();
    }
} catch (err) {
  console.log(44444,err);
}
```
![1585905272755](https://user-images.githubusercontent.com/25793040/78344461-00c7de00-75cf-11ea-9d19-9a9129460e4d.jpg)

**Comment by jacogr** [comment]
This means the pair is not in your store, i.e. it has not been added. You cannot retrieve non-existent pairs. Add it via seed first before trying to retrieve.
