### ISSUE TITLE
Question: specVersion for chain and specs

### ISSUE THREAD

**Issue by hanwencheng** [polkadot-js/api#2137]
Westend has only one versioned types with specVersion 1000, but polkadot has 3 versioned types. When loading westend chain with specVersion number 1000, does it meant to use same version number 1000 for both chain and specs(i.e "westend" and "polkadot")? 

I am confused because when I loading Westend network, `apps` now use specVersion number 1000, but the latest versioned type of Polkadot is with specVersion `1005`  as [here](https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/polkadot.ts).  Is it a expected behaviour?  If not, is it needed to add `chainVersion` in addition to `specVersion`?

**Comment by jacogr** [comment]
The overrides go in order -

- first spec
- then chain

So the chain types for a specific version will take priority. The specVersion will be specific per chain instance. Since Westend is non-current Polkadot, it is effectively running on an older version.

**Comment by hanwencheng** [comment]
I see, thanks!
