### ISSUE TITLE
Search Functionality for Documentation

### ISSUE THREAD

**Issue by fkbenjamin** [polkadot-js/api#2182]
It would be really nice to have a search bar in the documentation! I always struggle to navigate to the right subpage.

Jaco mentioned on Riot that there is a search plugin available for vue-press. Sadly, I have no experience with vue.js, so I can't really create a PR myself.

**Comment by jacogr** [comment]
This is the one I mentioned - https://vuepress.vuejs.org/plugin/official/plugin-search.html (that seems official - also have no experience, so marked this as a "medium effort", not sure may be "extra small" with just config and it works... seems that way)

**Comment by developerfred** [comment]
done @jacogr and @fkbenjamin

**Comment by jacogr** [comment]
Closed in #2232
