### ISSUE TITLE
Is there any way to reduce the metadata size

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/api#2203]
The metadata size is too large, the state_getMetadata request takes almost 5s.

And decode metadata will cause freezing on RN.

![image](https://user-images.githubusercontent.com/4149827/80084922-215dd500-858a-11ea-8088-fd1e0a342237.png)

**Comment by jacogr** [comment]
That is what is received from the node, so yes, it is very large.(And as new modules are added, it becomes bigger). I would rather suggest moving this to the Substrate repo, here am just a consumer of the info as received via RPC, so really cannot comment on how to reduce it. (The SCALE encoding is quite optimal, so it really is a case of the number of methods, events, queries & errors being described)

**Comment by xlc** [comment]
I think we definitely want to improve this. But it won't be easy.

I can see few directions:

- Improve polkadot.js
  - Optimize polkadot.js to improve speed
    - This will be dirty and hard and potentially unreliable
  -  Implement some kind of lazy decoding
    - This may buy some limited improvements but unfortunately SCALE codec have variable length, so it is not easy to skip thing without decode most of the data upfront.
- Rework metadata format on Substrate side to make it support lazy / partial decoding
  - e.g. no need to wait for decoding dispatchables until js sdk needs to build a transaction
  - We are in alpha stage, last chance to do this?
  - Break up into multiple calls
    - something like
      - get events metadata
      - get dispatchable calls metadata
      - get storage metadata
      - get constants and errors metadata
  - Somehow make the format support partial / lazy decoding
    - Rearrange the struct, insert few length prefixes
  - Metadata currently including docs string, they are useful, but I don't think they are necessary
    - They are moved into another rpc

**Comment by jacogr** [comment]
I am going to close this one, does not belong in this repo.

**Comment by xwartz** [comment]
@jacogr 
Is it possible make Polkadot.js to support decode a part of metadata? So we don't need to get the whole payload.

**Comment by jacogr** [comment]
SCALE is variable-length, binary based on the content. so to decode byte 2048, you need to have decoded bytes 1 to 2047 correctly to understand what is that position. It is the raw values, there is for instance no key information as you would find in a struct, on the raw package values for the elements within.

**Comment by xwartz** [comment]
@jacogr  So if metadata is updated, we'll have to update the Polkadot.js, otherwise it can't decode?

**Comment by jacogr** [comment]
If the metadata "format" and version changes, yes. (Currently the format is on V11) for chain upgrades where different metadata is generated, no. (Unless it contains new types, which would need support in the API)
