### ISSUE TITLE
Support state_subscribeStorage for all keys

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2211]
https://github.com/polkadot-js/api/pull/2208 is not enough.

Getting error here

https://github.com/polkadot-js/api/blob/1c8bd896e1f0050703119d04854b33048c522fc9/packages/rpc-core/src/index.ts#L391

keys is undefined.

The type information is coming from `StorageKey`, polkadot.js won't be able to just decode all the change set without extra helps.

Not sure what's the best solution.

I am trying to access the raw output instead and it is also not easy. There should be a version that doesn't do all the magics and just give me hex string and I can do the parsing myself.

**Comment by jacogr** [comment]
Yes. All RPCs does have a .raw option that ignores all parsing and returns the RPC as-is.
