### ISSUE TITLE
Problem with getting receivedHeartbeats. Empty response.

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2216]
I have a problem with running `api.query.imOnline.receivedHeartbeats`. I set era to 660 and index to 0 and I get empty response. No matter what I pass in I always get empty response. I have a feeling that I am doing something wrong because I also get empty responses for all the system queries related to extrinsics ie. `api.query.system.extrinsicData`. I can't figure out what am I doing wrong. Can someone can point me out into right direction?
Thanks you very much!

**Comment by jacogr** [comment]
It is `SessionIndex`, not `EraIndex`. Additionally it does not store it for all the sessions from the start of time, only the recent to determine slashing at the end of an era.

**Comment by silentlight** [comment]
Thank you @jacogr. I have one more question about metadata.

I get block info and there is that array of extrinsics over there and when I do `extrinsic.method.callIndex.toString()` I get `2, 0`. Where can I look for information about what those numbers mean? I am sorry but I have a problem to figure out where I can find some descriptions about returned fields. Do I take them from metadata?

**Comment by jacogr** [comment]
The API always returns the decoded extrinsic, so the meta on the extrinsic would have the info as to the method, as will `xt.method` & `xt.section` (where `xt` is the extrinsic)

**Comment by silentlight** [comment]
@jacogr `toHuman` is exactly what I needed.

Going back to your answer about `receivedHeartbeats `, do you know if there is any method to query validators' uptime at any given height?

**Comment by jacogr** [comment]
at queries, https://polkadot.js.org/api/start/api.query.other.html#state-at-a-specific-block against an archive node, at a specific block hash.

**Comment by silentlight** [comment]
Perfect! It works for me now  using:
`const receivedHeartBeats = await api.query.imOnline.receivedHeartbeats.at(blockHash, SESSION, 0);`
You rock @jacogr.
I think I have one last question for this one: What is the best way to decode bytes that I receive from this call?

**Comment by jacogr** [comment]
https://github.com/paritytech/substrate/blob/master/frame/im-online/src/lib.rs#L285-L289

**Comment by silentlight** [comment]
I am sorry @jacogr for bothering you.

```
const receivedHeartBeats = await api.query.imOnline.receivedHeartbeats.at(blockHash, SESSION, 0);
  console.log('receivedHeartBeats: ', receivedHeartBeats.toHuman());
```
and I get 
```
0x8c881220811a5e4ba54c1603b9206a5feec6fe02efcc302f6edbdc69acb924f6145d197d1874702f6970342f3134372e37352e3139372e31372f7463702f3330333333605c2f6970342f31302e302e302e392f7463702f333033333364602f6970342f31302e32302e322e312f7463702f333033333368642f6970342f31302e302e312e3133342f7463702f33303333336c682f6970342f31302e3135362e312e33342f7463702f333033333364602f6970342f31302e34342e342e312f7463702f3330333333
```

I am really stuck here :/

**Comment by jacogr** [comment]
It is an encoded opaque structure, as per the linked source - it is not text. So yes, it will be "garbage" when viewed as text.

**Comment by silentlight** [comment]
So can I assume that when I get not null from this request:
```
const receivedHeartBeats = await api.query.imOnline.receivedHeartbeats.at(blockHash, SESSION, 0);
```
It means that validator at index 0 was online?

**Comment by jacogr** [comment]
It would mean he/she didn't send a heartbeat. It could be that it was not needed (blocks produced, no need to send the heartbeat) or it could be that he/she was offline.

**Comment by silentlight** [comment]
Ah ok this makes sense. Thanks @jacogr!
So I guess I cannot use this method to figure out validators uptime. Would you recommend any other call I could use to figure out validators' uptime?

**Comment by jacogr** [comment]
From a network perfective the imOnline storage is used (blocks & messages), so that would probably be most aligned.

**Comment by silentlight** [comment]
So I guess any combination of these? https://polkadot.js.org/api/substrate/storage.html#imonline. Can you let me know which method can I use from polkadot-js?
