### ISSUE TITLE
Error when using .at " Vec length 436207936 exceeds 32768"

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2236]
Recently I upgraded my node and polkadot-js version to v1.12.2.
Now when I try to run at height **1805384**: 
```
const eventsAt = await api.query.system.events.at(blockHash);
```
I get error:
```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Vec length 436207936 exceeds 32768
ERROR Error: createType(Vec<EventRecord>):: Vec length 436207936 exceeds 32768
```
Any idea what can be wrong?

**Comment by jacogr** [comment]
The old types for the node does not match the current types. For instance after the last update on Kusama (last Monday) the Weight type includes in each ExrinsicSuccess event changed from u32 to u64. 

Unless you explicitly inject the older types it will try to decode using current.

**Comment by silentlight** [comment]
Thanks @jacogr. 
What do I have to do to fix it? The node version that I have is ` 0.7.31-99681c1d-x86_64-linux-gnu`

**Comment by silentlight** [comment]
Where can I find any info what node version works with what api version?

**Comment by jacogr** [comment]
It is not the API version - on Monday Kusama had an upgrade. That means that current types are different from previous types. Compare this vs previous - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L66-L83

(Kusama is at runtime version 1058 on-chain)

**Comment by jacogr** [comment]
Related is this - https://github.com/polkadot-js/api/issues/845

To parse older blocks, states which are generated with an older runtime version, you will need -

- the metadata at that point in time
- the types at that point in time

So you would need to -

- query the on-chain version at that block
- retrieve the metadata at that block
- inject the different types for that version (as per the link above, these change between versions)

At some point (with the linked issue), all this will be done automatically (at a huge cost in performance to historical queries). The TL;DR at this point is that things change completely with the dat structures between upgrades, old data is in most cases nt compatible with the current live runtime state. (Which creates issues, as you saw)

**Comment by silentlight** [comment]
This makes sense @jacogr 

So I have this code:
```
const blockHash = await api.rpc.chain.getBlockHash(HEIGHT);
const runtimeVersionAt = await api.rpc.state.getRuntimeVersion(blockHash);
const metaDataAt = await api.rpc.state.getMetadata(blockHash);
```
Now how can I inject types so that all following call to the api will use correct types?
I am building an indexer and need this to work for every height.

**Comment by silentlight** [comment]
I did 

```
api.injectMetadata(metaDataAt);
const eventsAt = await api.query.system.events.at(blockHash);
```
Is this the right way to do it @jacogr ?

**Comment by jacogr** [comment]
You have a types issue there as well :( The new `Weight` (current) is `u64`, the previous version is `u32`. (That I know will occur in older blocks)

**Comment by silentlight** [comment]
Should I use `registerTypes`? Can you point me to some code snippets/documentation so I can see how this should be done?

**Comment by jacogr** [comment]
It is certainly do-able. `api.registerTypes({ Weight: 'u32' })` - so all these hoops is what the API would need to jump through to transparently cater for older stuff -

- get the version at a point
- inject the metadata at that point (if not the same as current)
- inject the types at that point (if not the same as current)
- get the data
- ... rinse and repeat for all older

**Comment by silentlight** [comment]
OK got it.
But is there a way to inject type dynamically based on metadata at given height without hardcoding it? I see that Init.ts you have
```
this.registerTypes(getMetadataTypes(this.registry, metadata.version));
```
Maybe my understanding here if flowed. I thought that you can derive types from metadata at given height and then inject those types using `registerTypes`. Isn't that the case?

**Comment by jacogr** [comment]
For Kusama we do keep a list - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts

So with the specVersion at a give height, you can get the actual applicable types via https://github.com/polkadot-js/api/blob/master/packages/types-known/src/index.ts#L51

**Comment by silentlight** [comment]
I think this works @jacogr! Thank you so much!

**Comment by jacogr** [comment]
So all that magic needs to make it's way into `.at/.historic` so we all can stop jumping though hoops.
