### ISSUE TITLE
typegen not work 

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#2237]
![image](https://user-images.githubusercontent.com/7029338/81122194-7fc08580-8f84-11ea-8980-b8c4f2ba72f4.png)
I think it's because `typegen/ src/templates` wasn't published.

**Comment by jacogr** [comment]
Dangit. Thanks fo this, will apply a fix. (This is after https://github.com/polkadot-js/api/pull/2228, we only copy/publish known types and `.hbs` was unknown)

**Comment by jacogr** [comment]
Just checked the CI output and it does get published now.
