### ISSUE TITLE
Error when decoding block 2074527 (Runtime 1058)

### ISSUE THREAD

**Issue by nobrick** [polkadot-js/api#2241]
I'm trying to get info on block [2074527](https://polkascan.io/pre/kusama/block/2074527) with polkadot/api 1.13.0-beta.12.

The runtime spec version of the block is 1058 (the latest), so this may be not a historic block decoding issue.

```js
await api.rpc.chain.getBlock("0x938542841ea11d49ea935cfff1870f8f567dbdc5bfe1529445a805fd6d792e32")
```

returns the following error:

```
RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Vec length 406809645981752381342736809236557020018769378140960137781029859556038752627072435177728 exceeds 32768
```

I also tried `api.registerTypes` and `api.injectMetadata` before `getBlock`, the error still occurred.

Any ideas?

**Comment by jacogr** [comment]
Phragmen solution decoding seems unhappy, fails on `0xc95204061785033b003f003e00ac00d300e000f0001600a0` which would mean we have an issue with the `CompactAssignments`, https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/staking/definitions.ts#L26

**Comment by Linux-Server** [comment]
Im stuck with same issue? Help will be appreciated!
