### ISSUE TITLE
.mulit and .queryMulti together with .at

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2249]
Is it possible to use `.multi` and `.queryMulit` together with `.at`. I am trying to minimize number of calls I make to the node.

**Comment by jacogr** [comment]
No. But for historic queries (if you want to optimize), you could look at `.range` when you are dealing with more than one historic block.

**Comment by silentlight** [comment]
Thank you @jacogr!

**Comment by jacogr** [comment]
Just one comment. Both multiAt approaches I believe is now possible as of a couple of weeks ago (there is an RPC that will allow for this on newer implementations of Substrate, queryStorageAt)

So will change this to an enhancement, although don’t expect a change in status immediately for an implementation.

**Comment by jacogr** [comment]
(It will have to be multiAt in both cases instead of re-using multi)

**Comment by xw332** [comment]
> No. But for historic queries (if you want to optimize), you could look at `.range` when you are dealing with more than one historic block.

why I use `.rang`, but get `Error: Account is a Map and requires one argument`?

**Comment by Linux-Server** [comment]
...
// Retrieve the current block header
const lastHdr = await api.rpc.chain.getHeader();
const startHdr = await api.rpc.chain.getBlockHash(lastHdr.number.unwrap().subn(500));

// retrieve the range of changes
const changes = await api.query.system.account.range([startHdr],[]);

changes.forEach(([hash, value]) => {
  console.log(hash.toHex(), value.toHuman());
});

**Comment by andrew-frank** [comment]
Is it possible to get events in one go like with `.range`, but knowing which block they belong to? 

When using `.range` like so:
```javascript
const lastHdr = await api.rpc.chain.getHeader();
const startHash = await api.rpc.chain.getBlockHash(lastHdr.number.unwrap().subn(500))
const endHash = lastHdr.hash
const events = await api.query.system.events.range([startHash, endHash])
```
I get a flat array of events. So I can't map these to their block numbers. Unless I'm missing something?

**Comment by jacogr** [comment]
The query/queryMulti is being extended to return the blockHash as well. No ETA yet, but it is an oft-requested feature so has a high priority for me atm. (The idea and WIP is to return it as an additional param in the callback on the subscription)

**Comment by jacogr** [comment]
Closing, replaced by #3585
