### ISSUE TITLE
When initialized, metadata is requested and injected twice.

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#2250]
![image](https://user-images.githubusercontent.com/7029338/81252517-3b171600-907a-11ea-9059-3454b7784cac.png)
https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L130-L145
Because of these lines of code, metadata is requested twice, causing unnecessary performance problems.
There's a simple fix:
![image](https://user-images.githubusercontent.com/7029338/81252742-ca242e00-907a-11ea-820b-b933e24b41bf.png)
Add `skip(1)`. Skip the first time and avoid repeated initialization.

**Comment by jacogr** [comment]
Thanks for this, not sure how that was missed. Will take a peek.
