### ISSUE TITLE
determine height of last block within era

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2256]
Give era number is it possible to determine first and last height within that era? What API endpoint should be use to get this info?

**Comment by jacogr** [comment]
Always remember that the state just has the information required to process the next block. (Or in some cases block+X, i.e. payouts). It is not a database, it has as little information as possible, jus enough to 

- show exactly what happened at a specific block (events)
- being able to process the current block (state)

So, the above info is all available - via events. So if you want to extract it, you need to check all blocks for the relevant start event and can then determine at which point it happened

**Comment by silentlight** [comment]
This is very interesting @jacogr. Where can I read more about this?

**Comment by jacogr** [comment]
The best is to refer to the wiki and the Rust code to see which events are emitted by the runtime.

NewSession - https://polkascan.io/pre/kusama/event?module=session&event=NewSession&page=1

Those should be checked alongside an activeEra change. (So blocks + state at that block)

**Comment by silentlight** [comment]
Yeah, I saw NewSession event. Thanks @jacogr. This one is clear. I have a problem with activeEra since this has to be ran as a subscription from what I see. 
I want to specify any era number from the beginning and get staking information for that era but in order for historical requests to work I have to get metadata and types and inject them. Otherwise I will most likely get wrong types errors :/

**Comment by jacogr** [comment]
`await api.query.staking.activeEra.at(<blockHashWithEvent>)`

If the same as the previous one, you know it is just a session change, otherwise it is a new era.

**Comment by silentlight** [comment]
Ha! You are a very clever man @jacogr :) Thanks! I will try that.

**Comment by silentlight** [comment]
It might be harder than I though since the only piece of information that I have is era number :/

**Comment by silentlight** [comment]
Hi @jacogr. Do you have any hints on how can I move this forward having only era number?

**Comment by jacogr** [comment]
You need to check all historic blocks for the event - when the event is present, pull the era at that block. If it matches/changes you know you have the start/end.

**Comment by silentlight** [comment]
I think this might be too expensive to loop through all blocks in order to find events on every call to the /staking/:era endpoint :/

**Comment by jacogr** [comment]
Yes, the state is not a database - if you want that type of info, there is no other way than to build up your own index.

Going to close this one.
