### ISSUE TITLE
Can't create 'MultiSignature' type in addSignature

### ISSUE THREAD

**Issue by hanwencheng** [polkadot-js/api#2258]
Use the following code to inject signature:

```typescript
	const signature = registry.createType('Sr25519Signature', signatureRaw);
        //signature is a length 64 u8 array
	unsignedTx.addSignature(signer, signature, u8aPayload);
```

ends with the error 
```shell
error is Error: createType(MultiSignature):: Unable to create Enum via index 82, in Ed25519, Sr25519, Ecdsa
```
which caused by the `createType` function [here](https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicSignature.ts#L120), I guess the Enum type 'MultiSignature' cannot be direct created.

**Comment by jacogr** [comment]
64-bytes is not a valid `MultiSignature`. That is 65 bytes in length -

- the first byte is the indicator, 0=ed25519, 1=sr25519, 2=edcsa
- the last 64 bytes is the actual signature

**Comment by hanwencheng** [comment]
I use Keyring for testing with a prefixed bytes, but it turns out to be a bad proof.

e,.g 
```typescript
//This function get the 65 bytes signature with first byte as indicator
function prefixSignature (signatureRaw: ArrayLike<number>): Uint8Array {
	const u8aSignature = Uint8Array.from(signatureRaw);
	const u8aHeader = new Uint8Array([1]);
	const signature = new Uint8Array(65);
	signature.set(u8aHeader);
	signature.set(u8aSignature, 1);
	return signature;
}

const suri = 'ability cave solid soccer gloom thought response hard around minor want welcome//kusama';
const keyring = new Keyring({ss58Format: 42, type: 'sr25519'});
const signer:KeyringPair = keyring.addFromUri(suri, undefined, 'sr25519');

const payload:SignerPayload = registry.createType('SignerPayload', payloadRaw, { version: payloadRaw.version });
const signatureRaw = sender.sign(hexToU8a(payload.toRaw().data));

//if prefix the u8a then it is a bad proof after sending
const isBadproof = sender.verify(hexToU8a(payload.toRaw().data, signatureRaw), prefixSignature(signatureRaw));

//if not prefixed then can't add signature
unsignedTx.addSignature(signer, prefixSignature(signatureRaw), payload.toPayload());

unsignedTx.send();
```

And the Signing with Keypair here is aligned with test code in [SingleAccountSigner](https://github.com/polkadot-js/api/blob/a833dccdafa87735be93192beb5cbbdb2edb0756/packages/api/test/util/SingleAccountSigner.ts#L50) as well as the add signature process in [signViaSigner](https://github.com/polkadot-js/api/blob/9deaff54e40392722f49a748d1a93aca381afce8/packages/api/src/submittable/createClass.ts#L246-L257). 

So I am not sure what is the correct way to add the prefix.

**Comment by jacogr** [comment]
If you sign via the keyring, pass the withType: true option and it generates a MultiSignature.

**Comment by jacogr** [comment]
Here is an example of that - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicPayload.ts#L87

**Comment by hanwencheng** [comment]
Using Keyring signing should be works well. I was trying to use `addSignature` to adding the external signed signature into Extrinsic. 

short version: schnorrVerify always get "BadProof" with an external signing. I have different result from Parity Signer test [here](https://github.com/paritytech/parity-signer/blob/hanwen-test-verify/rust/signer/src/lib.rs#L419-L426)(passed) and a Keyring test [here](https://github.com/hanwencheng/substrate_api_flutter/blob/test/js/src/main.ts#L29-L35)(not passed).

long version: I am trying to port Polkadot API to Flutter, because the Polkadot api signing is a continues process with Keyring, but on Flutter wasm is not possible to integrated. So the signing process has to be split out(`getRaw` and `submit` [here](https://github.com/hanwencheng/substrate_api_flutter/blob/test/js/src/tx.ts)). That's where I start this issue, but after fixing the MultiSignature error (origin question on this issue) and trying different payload types, now I still getting `BadProof` error. In the above mentioned test suites, I used the signature generated from [Rust code](https://github.com/hanwencheng/substrate_sign_flutter/blob/master/rust/src/lib.rs#L106-L124) but got different outputs. So I guess some tweak of singing result is needed for the Keyring `signer.verify` function, as well as `addSignature` function.

Could you please spot any hints on that ?
