### ISSUE TITLE
Duplicate types PropIndex and ProposalIndex

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#226]
These two files appear to be duplicate of each other:

https://github.com/polkadot-js/api/blob/master/packages/types/src/PropIndex.ts

https://github.com/polkadot-js/api/blob/master/packages/types/src/ProposalIndex.ts

**Comment by jacogr** [comment]
Yeap, the naming sucks - however they are meant to be different types. The issue originates in Rust actually, remember we just have a mapping 1-to-1 with the Rust types so we can interpret the metadata. 

Specially asked about this one, cannot just alias the 2 to 1 (although the current are both u32)

From the code -

- PropIndex - public proposal index
- ProposalIndex - council proposal index

**Comment by jacogr** [comment]
Update to above, here is where the possible alias is marked - https://github.com/polkadot-js/api/blob/master/packages/types/src/Type.ts#L64

(However, since these are distinct types, cannot quite execute on that - have to keep an eye on Rust and see if the situation improves)
