### ISSUE TITLE
Unable to deposit into EVM account

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/api#2278]
Depositing into the EVM account yields:
```
Try again
Error: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x0012/[0,18]
```

**Comment by jacogr** [comment]
There is a probably a type mismatch. Feel free to make a PR into https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/evm/definitions.ts if you know what is missing/wrong.

**Comment by drewstone** [comment]
A bit unsure truthfully, types look fine and there don't seem to be newly introduced types for the existing events. Do you need to include events and their args in this as well?

**Comment by jacogr** [comment]
No. Took a quick peek as well, and it seems fine. Does other txs work? Culprits for this is normally - https://polkadot.js.org/api/start/FAQ.html#when-querying-older-blocks-events-it-fails-on-parsing

**Comment by jacogr** [comment]
Closing. (Have not run into this recently)
