### ISSUE TITLE
.at queries off by one?

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2282]
When I go to Polkascan at https://polkascan.io/pre/kusama/block/2275840, it shows that session is `3977` but when I use 
```
const sessionAt = await api.query.session.currentIndex.at(blockHash);
```
I get `3978`
Any idea why is that?

**Comment by jacogr** [comment]
It is correct. But what happens is the following -

- the state gets updated by extrinsics/state changes in processing a block and committed at the end of the block
- this means that those states only takes effect at the start of the next

So that block is the last of the session, the next block starts session 3978

**Comment by silentlight** [comment]
Got it. Thanks for the explanation.

**Comment by silentlight** [comment]
Ok so let's say we want to get data for height 100. Then all the calls to:
```
const era = await api.query.staking.currentEra.at(blockHash);
const session = await api.query.session.currentIndex.at(blockHash);
const runtimeVersionAt = await api.rpc.state.getRuntimeVersion(blockHash);
const metaDataAt = await api.rpc.state.getMetadata(blockHash);
```
should use height `99`, and for instance calls to:
```
const rawEventsAt = await api.query.system.events.at(blockHash);
```
should use height `100`.
Is that correct?

**Comment by jacogr** [comment]
100%

So get the block hash for block 100, the metadata and version stuff using the parentHash and the actual state using the actual hash.

**Comment by silentlight** [comment]
Great.

Are there any other call that use previous block hash?

**Comment by jacogr** [comment]
Just those 2 (well, currentIndex would make sense as well).

**Comment by silentlight** [comment]
How about 
`api.query.staking.currentEra.at(blockHash);`
and
`await api.query.timestamp.now.at(blockHash);`

**Comment by jacogr** [comment]
currentEra is actually the next planned era. (So may be there, or may be empty depending of where we are in the activeEra)
