### ISSUE TITLE
magicNumber in metadata

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2283]
What is the meaning of `magicNumber` in metadata? When does this number change? Does it change when metadata and types change?
I would like to cache this information so that I don't have to do injection on every height and I am trying to figure out what cache key should I use. Should it be that magicNumber or maybe specVersion?

**Comment by jacogr** [comment]
specVersion - the metadata version is for the format of the metadata, not what is contained within. The specVersion gets updated when there are upgrades.

**Comment by silentlight** [comment]
Thank you @jacogr

**Comment by jacogr** [comment]
... just remember that specVersion changes means it takes effect at the start of the next :)

Also for inspiration and/or use - https://github.com/paritytech/substrate-api-sidecar
