### ISSUE TITLE
Get details about event

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2284]
When I query events I get something like
```
{
   index: '0x0300',
  data: [ 780, 353653307267834, 265837297931696 ] 
}
```
How can I get more details (module, event name, description) about event similar to what we have on polkascan https://polkascan.io/pre/kusama/event/2308381-3?

**Comment by jacogr** [comment]
Use `toHuman()` is you want to display. It will show all the getters available, including the descriptions, types, etc. 

This is in the docs - https://polkadot.js.org/api/start/api.tx.subs.html#transaction-events (and event is always an event)
