### ISSUE TITLE
Balance problem in token transfer

### ISSUE THREAD

**Issue by mustafasevinc** [polkadot-js/api#2298]
Hello, I want to transfer tokens. I was able to send a transaction with the code I wrote. Balance in transaction was 0 in transaction. Token was not transferred and GAS received.

```
const { ApiPromise, WsProvider } = require('@polkadot/api');
const { Keyring } = require("@polkadot/keyring");
const { cryptoWaitReady } = require("@polkadot/util-crypto");
const { Balance } = require("@polkadot/types/interfaces");

async function main () {
    const wsProvider = new WsProvider('ws://127.0.0.1:9944');
    const api = await ApiPromise.create({ provider: wsProvider, types: {
        Address: 'AccountId',
        LookupSource: 'AccountId',
    }});
    
    cryptoWaitReady();
    const keyring = new Keyring({ type: 'sr25519' });
    const pk = keyring.addFromMnemonic('smoke indicate blush ancient return unfold matter bind fiscal tired catch safe');
    const {Nonce} = await api.query.system.account(pk.address);
    
    const txn = await api.tx.balances.transfer('5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw', 700).signAndSend(pk, { nonce: Nonce });
    console.log(txn.toJSON());
}
main().catch(console.error).finally(() => process.exit());

**Comment by jacogr** [comment]
It is expected. 

The amount transferred needs to be more than the actual existential amount, otherwise it is treated as dust. So 700 should be greater than api.consts.balances.existentialDeposit

**Comment by mustafasevinc** [comment]
I tried what you said, I think the problem stems from something else. There is a sufficient amount of money in the account of those mnemonic words. I set the transfer amount to be more than you say but it did not.
`
const txn = await api.tx.balances.transfer('5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw', api.consts.balances.existentialDeposit+1).signAndSend(pk, { nonce: Nonce });`

**Comment by jacogr** [comment]
This stems from node processing, as long s the tx gets there (you can check in the node logs), all is good. Nothing wrong with the code above. (Would just remove the `cryptoWaitReady()` since the API init does that, and the nonce is retrieve in signAndSend, so no need to specify that)

(Moving, this is in no way UI related, not actually API related, but it fits better there as a question)

**Comment by mustafasevinc** [comment]
Again it didn't work :(

**Comment by jacogr** [comment]
I started a `substrate --dev` node. Connected the UI, added the seed you provided and funcded it.

Next I took your code and just adjusted naming (type overrides not required for Substrate dev, it uses indices) -

```js
const { ApiPromise } = require('@polkadot/api');
const { Keyring } = require("@polkadot/keyring");

async function main () {
    const api = await ApiPromise.create();

    const keyring = new Keyring({ type: 'sr25519' });
    const pair = keyring.addFromMnemonic('smoke indicate blush ancient return unfold matter bind fiscal tired catch safe');
    const value = api.consts.balances.existentialDeposit.muln(2);

    const txn = await api.tx.balances
      .transfer('5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw', value)
      .signAndSend(pair);

    console.log(txn.toJSON());
}

main().catch(console.error).finally(() => process.exit());
```

Then I executed it and it returned the hash.

Then I looked in the UI and this is the event -

![image](https://user-images.githubusercontent.com/1424473/82660183-2ade6980-9c2a-11ea-8569-13434563809d.png)

So whatever it is, is local to your setup.

**Comment by mustafasevinc** [comment]
Why did you close the issue? My problem is still not gone. This move made you upset me.  "https://www.substrate.io/tutorials/create-your-first-substrate-chain/v2.0.0-alpha.8", I started my own chain like this site. Then I sent money from "https://polkadot.js.org/apps/#/accounts" to the relevant account. After I had enough money in the account, I wanted to transfer tokens to another account via js-code. But it didn't happen. When I try to do it with the code you sent, it gives the error in the image below.

![image](https://user-images.githubusercontent.com/59833608/82704076-78d08d00-9c7d-11ea-9363-1610d2d95da1.png)

Then I ran and ran with Indices. He gave me the Transaction mix. But still the balance was 0.

![image](https://user-images.githubusercontent.com/59833608/82709105-88a19e80-9c88-11ea-9914-3017b5333ebe.png)

![image](https://user-images.githubusercontent.com/59833608/82709184-b0910200-9c88-11ea-8e35-96164750b4e4.png)

**Comment by mustafasevinc** [comment]
I installed the substrate you said. Then I started the chain by saying substrate --dev. I ran the code you sent. This time I got a different error.

![image](https://user-images.githubusercontent.com/59833608/82720278-b56ea980-9cba-11ea-99f5-193a5df2230e.png)

**Comment by jacogr** [comment]
The issue was closed since the intent of issues is to -

- log enhancements
- log bugs

This is neither, this is a local support issue for your specific setup. I suggest reading this -

- You are running a master branch - https://polkadot.js.org/api/start/FAQ.html#i-am-getting-a-unknown-types-found-no-types-for-error

- You were running node-template - https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

If you want specific support, I would suggest joining the support channels on Riot. If is not like I don't want to help, but support really should be directed to the correct channels. For both issues detailed here there are FAQ links.
