### ISSUE TITLE
Democracy voted result mistake

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/api#2299]
https://polkadot.js.org/apps/#/democracy

Test:
Vote refer # 53 aye.
The number of voted aye is increased.
**But the list of  aye address not have my address**

Polkawallet use the polkadot-js api, have the same issue.
It's the api issue.

**Comment by jacogr** [comment]
Without an actual reference to the tx and the type of vote, cannot comment. Sadly, there is no relevant information in here at all.

- which chain?
- which account?
- which tx? (reference)

**Comment by jiangfuyao** [comment]
Sorry, normal, my mistake.

Kusama.
E8Yd2tgy9BQi2dGPAMc9GgiGJy3wsibhL1EU4kCLf1g1A3V
