### ISSUE TITLE
Can't build payload (createtype error)

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/api#2318]
Hello, I don’t know if you have any impressions. I successfully constructed the transaction body offline 7 months ago and it was successfully posted. 
The previous issue is # 1421.

There are a lot of errors when I try again now. I updated the library and modified the related API interface methods. There was an error when constructing the transaction body. I don’t understand why, can you tell me about it? 
```
  const signerPayload = createType('SignerPayload', {
            address: from,
            blockHash: genesisHash,
            blockNumber: '',
            // era: era,
            genesisHash: genesisHash,
            method: tx,
            nonce: nonce,
            runtimeVersion: runtimeVersion,
            tip: '',
            version: version
        });
```
got error:Error: createType([object Object]):: value.replace is not a function

and, what other important changes are there?

In addition, I can’t get the test coins from the taps that ca n’t connect to the testnet. Can you give me a little test? Thank you very much!

**Comment by jacogr** [comment]
Actually, all my testing is done on dev chains, i.e. running `substrate --dev`. I don't use Kusama, Westend, Edgeware, etc. to test. (There are just way too many things to test and way to operate, that control over the chain and actual config thereof is critical)

`createType('SignerPayload', {` -> `registry.createType` or `createType(registry`, those changes went in with this release according to the CHANGELOG, `# 0.97.1 Nov 29, 2019`

**Comment by Wangmmx** [comment]
> Actually, all my testing is done on dev chains, i.e. running `substrate --dev`. I don't use Kusama, Westend, Edgeware, etc. to test. (There are just way too many things to test and way to operate, that control over the chain and actual config thereof is critical)
> 
> `createType('SignerPayload', {..})` needs to change to `registry.createType({...})` or `createType(registry, {...})`, those changes went in with this release according to the CHANGELOG, `# 0.97.1 Nov 29, 2019`

Thank you, I will try to change the payload method first. I am using westend. It feels more convenient, but it is really troublesome without WND. Let me think about other methods. Thank you for responding so quickly

**Comment by jacogr** [comment]
Have not tried it, but Westend does have a faucet via Riot.

**Comment by Wangmmx** [comment]
Yes,  but I can't register for riot, and I asked riot and matrix official to solve

**Comment by Wangmmx** [comment]
After changing the createType construction method, the parameters are wrong. I am not sure about the specific parameters and values. Is there a similar demo? 

This is my current parameter

```
  const signerPayload = registry.createType('SignerPayload', {
            address: from,
            blockHash: genesisHash,
            blockNumber: '',
            // era: era,
            genesisHash: genesisHash,
            method: tx.toHex(),
            nonce: nonce,
            runtimeVersion: runtimeVersion,
            tip: '',
            version: version
```

got error: 
Error: createType(SignerPayload):: Struct: failed on 'method':: findMetaCall: Unable to find Call with index 0x9004/[144,4]

The rest of the code is like this
```
        const api = await ApiPromise.create({provider: wsProvider});
        const nonce = await api.query.system.account('5DoAuBX5F83DEBA89vh9is6AebzUjspekuQPxa9QAvfhmwkR').nonce;
        const genesisHash = api._genesisHash.toString();
        const version = api._rpc.state.getRuntimeVersion()


        //1.create transaction
        let tx = api.tx.balances.transfer(to, 1);

        //2.create SignerPayload
        let signerPayload = api.registry.createType('SignerPayload', {
            address: from,
            blockHash: genesisHash,
            blockNumber: '',
            // era: era,
            genesisHash: genesisHash,
            method: tx.toHex(),
            nonce: nonce,
            runtimeVersion: api._rpc.state.getRuntimeVersion()['specVersion'],
            tip: '',
            version: api._rpc.state.getRuntimeVersion()['transactionVersion']
        });

        //3.create ExtrinsicPayload
        const extrinsicPayload = api.registry.createType('ExtrinsicPayload', signerPayload.toPayload(), {version: signerPayload.version});

        //4.sign ExtrinsicPayload
        const {signature} = extrinsicPayload.sign(pair);

        const verifyData = extrinsicPayload.toU8a(true);
        let verifyResult = pair.verify(verifyData, hex.hexToU8a(signature));
        console.log('verifyResult', verifyResult)

        //5.inject data (address, sigHex, singerPayload)
        tx.addSignature(from, signature, signerPayload.toPayload());
        console.log('tx', tx.toHex().size)
        console.log('tx', tx.toHex())

         //6.send
         const hash = await tx.send();
         console.log(hash.toHex())

```

**Comment by jacogr** [comment]
The version is wrong. The runtimeVersion.transactionVersion is something different (but confusingly named).  So the version is the same as retrieved from the metadata

**Comment by Wangmmx** [comment]
The version is changed but got the same error:
Error: createType(SignerPayload):: Struct: failed on 'method':: findMetaCall: Unable to find Call with index 0x9004/[144,4]
Should the data be like this?
```
        const api = await ApiPromise.create({provider: wsProvider});
        const nonce = await api.query.system.account('5DoAuBX5F83DEBA89vh9is6AebzUjspekuQPxa9QAvfhmwkR').nonce;
        const genesisHash = api._genesisHash.toString();

        //1.create transaction
        let tx = api.tx.balances.transfer(to, 1);

        let version = api.extrinsicVersion;
        let runtimeVersion = (await api._rpc.state.getRuntimeVersion())['specVersion'].toString()

        //2.create SignerPayload
        let signerPayload = api.registry.createType('SignerPayload', {
            address: '5DoAuBX5F83DEBA89vh9is6AebzUjspekuQPxa9QAvfhmwkR',
            blockHash: genesisHash,//'0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3',
            blockNumber: ''
            // era: era,
            genesisHash: genesisHash,//'0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
            method: tx.toHex(),//'0x90040500c5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a04'
            nonce: nonce, //0
            runtimeVersion: runtimeVeraion,//1
            tip: '',
            version: version,//4
        });
```

**Comment by jacogr** [comment]
Here is an example - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/SignerPayload.spec.ts#L17 (the version there is 3, it is older, in your case `version: 4` is indeed current)

So the tx is not quite correct, since you only want the method part, not the full. So `tx.method.toHex()`

runtimeVersion also does't look 100% since that is a struct containing spevcVersion, transactionVersion.

**Comment by Wangmmx** [comment]
thanks, I modified my parameters according to the example, and finally no error was reported, and then successfully constructed ExtrinsicPayload.
I successfully signed the signature, but the signature verification failed.
the seed is correct to sign because I signed with a simple message and isValid returned true.

Has the signature-related method changed?
```
....
        //1.create transaction
        let tx = api.tx.balances.transfer(to, 1);

        //2.create SignerPayload
        let signerPayload = api.registry.createType('SignerPayload', {
            address: from,
            blockHash: genesisHash,
            blockNumber: '',
            // era: era,
            genesisHash: genesisHash,
            method: tx.method.toHex(),//0x0500c5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a04
            nonce: nonce,
            runtimeVersion: await api._rpc.state.getRuntimeVersion(),
         //   tip: '',
            version: api.extrinsicVersion
        });

        //3.create ExtrinsicPayload
        const extrinsicPayload = api.registry.createType('ExtrinsicPayload', signerPayload.toPayload(), {version: signerPayload.version});
//0x8c0500c5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a04000000010000000000000091b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c391b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3

        //4.sign ExtrinsicPayload
        const {signature} = extrinsicPayload.sign(pair);//0x00073a53dcea3092b81552382e0bb3904bf55e1cd1b2a1a25a9328213eca088d8659fcc9126ab6b34184d7ecb88f0176146602cafba1760b84a9f7e93fae374506
        const verifyData = extrinsicPayload.toU8a(true);
        let verifyResult = pair.verify(verifyData, hex.hexToU8a(signature));
        console.log('verifyResult', verifyResult)//false

        //5.inject data (address, sigHex, singerPayload)
        tx.addSignature(from, signature, signerPayload.toPayload());
        console.log('tx', tx.toHex())

        //6.send
        const hash = await tx.send();
        console.log(hash.toHex())
        process.exit();
```

**Comment by jacogr** [comment]
So in the last 7 months, Substrate has moved from `AnySignature` to `MultiSignature`. Extrinsic Version4 is `MultiSignature` if on-chain. So the only thing I can suggest it to look at these options, I really don't know off-hand - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicPayload.ts#L94

`{ withType: true }` is passed through to create a 65-byte signature with the type information.

So the verify as-is won't work, since it is 65 bytes, not 64. (The first byte contains the identifier for Substrate, the last 64 the actual sig that can be verified)

**Comment by Wangmmx** [comment]
It looks like the changes are still a bit big, ok let me take a closer look at these changes first and try again, thank you very much

**Comment by Wangmmx** [comment]
Well, yes, I tried the v3 version signature verification to be correct. But later addSignature will also report an error, what is needed is the type of multiSignature.

 I understand, let me look at the way of V4 version signature first

**Comment by jacogr** [comment]
So when you verify, just use the last 64 bytes. So `signature.subarray(1)` - the first byte is an indicator for the type of crypto.

**Comment by Wangmmx** [comment]
Yes, I only verify that the 64 bytes signature is correct, but my signature is the same whether added with {withType: true}, I may added it wrong. And then added the signature of 65 bytes in `addSignature`, got the hex of tx , and then an error occurs when sending:
 RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1012: Transaction is temporarily banned


```
const extrinsicPayload = api.registry.createType('ExtrinsicPayload', signerPayload.toPayload(), {version: signerPayload.version});

const {signature} = extrinsicPayload.sign(pair, { withType: true });

let verifySignature = hex.hexToU8a(signature).subarray(1)
const verifyData = extrinsicPayload.toU8a(true);
let verifyResult = pair.verify(verifyData, verifySignature);
console.log('verifyResult', verifyResult) //ture

 //5.inject data (address, sigHex, singerPayload)
tx.addSignature(from, signature, signerPayload.toPayload());
console.log('tx', tx.toHex())
//0x21028488ccfe1c52268e4f5dfb6228e71b2cff7a24446fad25fcd2bc3481fad2c63ccf00ceeff14d750846f6b44cf321fdea29347645fc40cf8bdb7c7fa65da3e08dbbf8d8719fac047782ab506b9a0913b3a973b4c9f5a8c40f537b8fcddf3f14e43d0d0000000500c5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a04

 //6.send
const hash = await tx.send();
console.log(hash.toHex())
```

**Comment by jacogr** [comment]
That message comes from the tx pool. So would refer to that to see the actual causes.

Going to close this one.

**Comment by Wangmmx** [comment]
thank you very much!
