### ISSUE TITLE
How to get extrinsic details by extrinsic hash

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/api#2326]
Is there any way to get the transaction details through the transaction hash?

I used blockHash to find the whole block details, and query each of these transactions.
Is there a better way？
```
let block = await api.rpc.chain.getBlock('*****')
        block.block.extrinsics.forEach(ex=>{
            console.log(''ex");
        });
```

**Comment by jacogr** [comment]
Sadly not. there is no "by hash" RPC query. (hashes are not unique, however hash + block is)

**Comment by Wangmmx** [comment]
Is the interface on the browser to obtain transaction details based on the transaction hash written separately?

like 
https://polkascan.io/polkadot-cc1/transaction/0xca9bf68af6f808f0ed2580d679805a64ccff24e7dcee25a49e3db00bc511beb0
txHash is 0xca9bf68af6f808f0ed2580d679805a64ccff24e7dcee25a49e3db00bc511beb0.

I sent a transaction only returned hash, I do not know how to query

**Comment by jacogr** [comment]
Yes, Polkascan trawls the whole chain, extracts the info and writes to their own database. Since they are an explorer they turn blockchain data in query-able data in a database.

**Comment by Wangmmx** [comment]
Okay,  then I still use the polkascan to check the transaction.
By the way, can the polkascan westend's network be used? The current transaction is still a month ago. 

The question I mentioned before https://github.com/polkadot-js/apps/pull/2871

**Comment by jacogr** [comment]
I have no idea - you will need to ask Polkascan directly. I honestly don't track their updates.

**Comment by Wangmmx** [comment]
Oh right, sorry to ask you again, thank you for answering me

**Comment by crossle** [comment]
> Sadly not. there is no "by hash" RPC query. (hashes are not unique, however hash + block is)

@jacogr How to get the detail transaction info by block id?

**Comment by SleepingNext** [comment]
Hi, @crossle!

First, what do you mean by Block ID?

1. If you mean Block Height, then you can get the Block Hash first by using: `blockHash = await api.rpc.chain.getBlockHash(blockHeight)`, and then get the block by its hash with: `block = await api.rpc.chain.getBlock(blockHash)`. The transactions (extrinsics) will inside: `block.block.extrinsics`.

2. If you mean Block Hash, then start from the second code I wrote above.
