### ISSUE TITLE
Failed to make create-type call offline

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/api#2328]
`api.registry.createType('SignerPayload', {...})` is worked
But when called as a dependent package, an error occurs

here's code
```
let { TypeRegistry, createType} = require('@polkadot/types');
let registry = new TypeRegistry();
let signerPayload = registry.createType('SignerPayload', {
            address: from,
            blockHash: genesisHash,
            blockNumber: '',
            // era: era,
            genesisHash: genesisHash,
            method: tx.method.toHex(),
            nonce: nonce,
            runtimeVersion: runtimeVersion,
            signedExtensions:signedExtensions,
            // tip: '',
            version: version
        });
```

and I also tried `createType(registry, 'SignerPayload', {...}) `and failed

Which method should be written here?

**Comment by Wangmmx** [comment]
The result of signerPayload is printed, these two methods generate the same result, but the second method will report an error

`Error: Struct: failed on 'method':: findMetaCall: Unable to find Call with index 0x0400/[4,0]`

```
{ address: '5FA5GKjtaCYHRhLtJ8bWhA1zP137PzTMmiDw8nfb5wDXSyGD',
  blockHash:
   '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e',
  blockNumber: '',
  era: '',
  genesisHash:
   '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e',
  method:
   '0x040047c9440935f46211a67b04514420dec0bbc79d7751b3757fb0e0cc164b6d2b1e04',
  nonce: '3',
  signedExtensions:
   [ 'TransactionCallFilter',
     'CheckSpecVersion',
     'CheckTxVersion',
     'CheckGenesis',
     'CheckEra',
     'CheckNonce',
     'CheckWeight',
     'ChargeTransactionPayment',
     'LimitParathreadCommits',
     'ValidateDoubleVoteReports',
     'ValidateEquivocationReport' ],
  specVersion: '20',
  tip: '',
  transactionVersion: '1',
  version: 4 }
```

**Comment by jacogr** [comment]
`Error: Struct: failed on 'method':: findMetaCall: Unable to find Call with index 0x0400/[4,0]` - you have not added metadata to decode. (Or incorrect metadata for your chain)

**Comment by Wangmmx** [comment]
Which data is the problem? Can you tell me more about metadata, thank you very much

**Comment by Wangmmx** [comment]
It might be blockNumber, let me try first

**Comment by Wangmmx** [comment]
But using the `api.registry.createType('SignerPayload', {...})` method is possible without error, I am still not sure which data is wrong, please help me to take a look

**Comment by Wangmmx** [comment]
I know that there is something wrong with the method data, I use the result of `tx.method.toHex()` to report this  error
`Error: Struct: failed on 'method':: findMetaCall: Unable to find Call with index 0x0400/[4,0]`
 and the result of `tx.toHex()` report this
`Error: Struct: failed on 'method':: findMetaCall: Unable to find Call with index 0x9004/[144,4]`


Also, using the api.registry.createType('SignerPayload', {...}) method is possible without error, I don't know which is the problem

**Comment by Wangmmx** [comment]
This is my unit test, you can run this directly, the first signerPayload is correct, the second one is not printed, is the dependency I cited wrong?
```
let { TypeRegistry } = require('@polkadot/types/create');

it('createType test', async () => {
    const wsProvider = new WsProvider('wss://westend-rpc.polkadot.io')
    const from = '5FA5GKjtaCYHRhLtJ8bWhA1zP137PzTMmiDw8nfb5wDXSyGD';
    const to = '5Dgq3axpAPE7nUDKdhsxfvHKjBiRTwCQJesfxZ2z12b91TC3';
    const api = await ApiPromise.create({provider: wsProvider});

    const nonce = (await api.query.system.account(from)).nonce.toString();
    const genesisHash = api._genesisHash.toString();
    const version = api.extrinsicVersion;
    const runtimeVersion = (await api._rpc.state.getRuntimeVersion());
    const signedExtensions = api.registry.signedExtensions;

    let tx = api.tx.balances.transfer(to, 1);
    let registry = new TypeRegistry();

    let data = {
        address: from,
        blockHash: genesisHash,
        blockNumber: '',
        // era: '',
        genesisHash: genesisHash,
        method:  tx.method,
        nonce: nonce,
        runtimeVersion: runtimeVersion,
        signedExtensions:signedExtensions,
        // specVersion: runtimeVersion.specVersion.toString(),
        //tip: '',
        // transactionVersion: runtimeVersion.transactionVersion.toString(),
        version: version
    }

    let signerPayload1 = api.registry.createType('SignerPayload', data);
    console.log('signerPayload1', signerPayload1.toPayload());
    let signerPayload2 = registry.createType('SignerPayload', data);
    console.log('signerPayload2',signerPayload2.toPayload());

   // process.exit();
});

```

**Comment by Wangmmx** [comment]
I added the `metadata` 

`    new Metadata(registry, rpcMetadata); `

try again

**Comment by Wangmmx** [comment]
got error `Error: createType(SignerPayload):: Struct: failed on 'method':: Struct: failed on 'args':: Vec length 262073888867941627869161784301049115725686995764425 exceeds 32768`

Could you please help me see it? Thank you

**Comment by Wangmmx** [comment]
I'm sorry to disturb you all the time. I recently worked in the docking of polkadot. I need to assemble the transaction body offline and make a transfer. The task is quite large, so I am also very stressed. If I don't understand a lot, I will always ask you. We have a time difference. Sorry for affecting your rest

**Comment by Wangmmx** [comment]
It should be a question of parameters, I will look at each parameter against the demo

**Comment by Wangmmx** [comment]
I found the problem, the result obtained by my method is not correct. What I got is a 36 bytes result, and the result in the demo is 38 bytes.
But what I got from the previous assembly transaction is also the result of 36 bytes, and it was sent successfully, you can query from https://polkadot.js.org/apps/#/explorer/query/0x50d3425ddfdc32641b456a3d49fd85115d5e3a5c78c95330cc159dab9ef8f4a4, The method of this transaction is `0x040047c9440935f46211a67b04514420dec0bbc79d7751b3757fb0e0cc164b6d2b1e04`
 Why not use the `api.registry` method to report errors

**Comment by Wangmmx** [comment]
Sorry to disturb you, if you can take the time to look at it, thanks again

**Comment by Wangmmx** [comment]
Solved, closed
