### ISSUE TITLE
Conflicting augment types

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2338]
`generateTx/generateQuery` are not usable for us as it is due to two reasons:

- It will generate the definitions for substrate pallets again, and if the version we are using does not match to polkadot.js one, TypeScript check will fail.
  - This will be a problem when Polkadot & Kusama having two different interfaces.
- We have our own Vesting module (before the one in Substrate is implemented) and we cannot generate type defs for it because otherwise again the types will conflict with the one provided by Substrate.

I think the solution is the ability to exclude the definitions for default pallets.

The better way is somehow make things generic so it is possible to have correct type completion while working with multiple chains at same time (think about wallets / arbitrage bots etc).

We are currently filtering pallets before type generation but that means when polkadot.js upgraded and if we don't, we will have invalid typings for Substrate provided pallets.

https://github.com/laminar-protocol/laminar-chain.js/blob/d36a06a414210d9d5fb87ed8bee76758ccd0a944/packages/types/scripts/generate.ts#L19-L63

You can see the build errors:

When not filtering substrate pallets:
https://github.com/AcalaNetwork/acala.js/runs/748491394?check_suite_focus=true

When have our vesting pallet:
https://github.com/AcalaNetwork/acala.js/pull/42/checks?check_run_id=748580355

**Comment by jacogr** [comment]
The user supplied modules should take precedence when there are conflicts - that is the intent. So there seems to be a mismatch for cases where that doesn’t happen.

**Comment by xlc** [comment]
The problem is I don't think TS support type override?

`error TS2717: Subsequent property declarations must have the same type`

**Comment by gdethier** [comment]
Same problem here. To add to @xlc 's comment, TS enables interface merging (which may be considered as a kind of type overriding) but overlapping non-function members must have the same type, otherwise you get error TS2717 (see [here](https://thewebdev.info/2020/04/13/merging-declarations-in-typescript/)).

**Comment by gdethier** [comment]
For the record, as we are not yet packaging our code, we were able to use another (dirty) workaround: delete the conflicting type definition files from `./node_modules/@polkadot/api/augment` (i.e. execute `rm -f ./node_modules/@polkadot/api/augment/*.d.ts` before building the app).
