### ISSUE TITLE
Getters not recognised by TypeDoc

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#234]
If we use TypeDoc for TypeScript Getters i.e. `get`, as follows:
```
export default class Rpc implements RpcInterface {
  private _provider: ProviderInterface;

  constructor (provider: ProviderInterface) {
    this._provider = provider;
  }

  /**
   * @example
   * <BR>
   *
   * ```javascript
   * <insert_example_here>
   * ```
   */
  get provider (): ProviderInterface { return this._provider; }
...
``` 
When we render it in Gitbooks by running: `yarn; yarn run build; yarn gitbook serve` and then viewing the relevant page after opening http://localhost:4000, it renders as `getprovider()` instead of `get provider()` (i.e. there's no space between).
Note that this may also be an issue with Setters.

**Comment by amaurymartiny** [comment]
Should probably open an issue on gitbook

**Comment by amaurymartiny** [comment]
Yes correct, should be in typedoc not in gitbook

**Comment by jacogr** [comment]
Closing here, nothing that we can do until fixed upstream - as updated, will update dev packages.
