### ISSUE TITLE
Allow pass OverrideVersionedType[] to api constructor

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2341]
We have some breaking changes between our old and new testnet and we would like to have a single API that support both testnet.

But seems like the filterVersions is not been called on user provided types and we cannot know which types without knowing the spec version first.

https://github.com/polkadot-js/api/blob/e6beb6554dff7ac61fd2e9d16b2631978e6ec626/packages/types-known/src/index.ts#L59-L62

For now we can use the chain name to distinguish between versions, but won't work once we introduce breaking changes in our public testnet via runtime upgrade.

We would like to pass something like this to API contractor and have it detect and use correct types based on spec version

```
export const typeChain: Record<string, OverrideVersionedType[]> = {
  acala: [
    {
      minmax: [undefined, 403],
      types: {
        Weight: 'u32'
      }
    }
  ]
};
```

**Comment by jacogr** [comment]
Yes, don't have that atm. For types-that-are-in-Substrate can suggest adding here 

- https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/index.ts
- eg. https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/centrifuge-chain.ts

(But only applies to Substrate base types)

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/2422 via `typesBundle` that allows (a) multiple chains, (b) versioned
