### ISSUE TITLE
Decode extrinsics in python

### ISSUE THREAD

**Issue by i-xiaov** [polkadot-js/api#2349]
I'm building a polkadot explorer in python. I found some useful rpc calls but can not use them directly since there are no py-libs to decode the result. Anyone can tell me what exacly the extrinsics encoder did, then maybe I can write a corresponding decoder in python?

Below are my situations.

1. Block data from `chain_getBlock` method
`
{
    "justification": null, 
    "block": {
        "extrinsics": [
            "0x280402000b504b089d7201", 
            "0x10040d0000", 
            "0x25028488ccfe1c52268e4f5dfb6228e71b2cff7a24446fad25fcd2bc3481fad2c63ccf00da8cebad43b8e5e2a8041119981d64a78e19ebd6f1405ed4267b4b5a6b52774047ee765af2b5e3f833d574fca1d600d0ba5a2b8b1aba7f422fc07015af77fb0f45030800040047c9440935f46211a67b04514420dec0bbc79d7751b3757fb0e0cc164b6d2b1e04"
        ], 
        "header": {
            "extrinsicsRoot": "0x83a87bee742346c9e4c3545ea82ac9d7e1d3c490fad14faa0f733c0a15f8e1df", 
            "stateRoot": "0xdf9b99ecb820beea7d4ae2d315bbef371e8d6bacb0f91099be5694d82edd7fc2", 
            "parentHash": "0x9cf3f2a5f9922287d7ac600585dac3099fdf07fe3facbd7fdab73a121a1454da", 
            "number": "0xdbb38", 
            "digest": {
                "logs": [
                    "0x06424142453402010000003316d00f00000000", 
                    "0x05424142450101864800a5ccafaa53c6de56c5ee29584e2c0d0b8ba35d24c2537a2970fb1d706fdd27716bc32d37f4a7f9a578442516e08af501534f1e4a21b9e5dbb142ef3985"
                ]
            }
        }
    }
}
`
I guess `block.extrinsics` field represents the raw_txs, am I right? So how can I decode them just like `{from: **, to: **, value: **}`

2. How can I query balance of an account? I noticed the `state_getStorage` method. But I don't know how to make the param `key` and I can't decode the result like `0x04000000005d390a5a160000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

**Comment by jacogr** [comment]
There is a Python implementation - https://github.com/polkascan/py-scale-codec
