### ISSUE TITLE
Add type `Status` to API

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/api#2350]
https://github.com/paritytech/substrate/pull/6330 adds `Status` to encode/decode for events. Add this type to the API.

**Comment by jacogr** [comment]
Would appreciate a bit earlier heads-up, especially when these things hit live networks.

**Comment by joepetrowski** [comment]
Yeah this went in fast and I didn't realize it broke this API when I made it in Substrate, will give a better heads up next time.

**Comment by jacogr** [comment]
Yes... the last upgrade did go a bit quick :)
