### ISSUE TITLE
Getting disconnection errors on epoch change

### ISSUE THREAD

**Issue by dillu24** [polkadot-js/api#2352]
I am getting the following error from the API on epoch change:

`API-WS: disconnected from ws://IP:PORT`

**Comment by jacogr** [comment]
This is not related to the API. There is really no logic at all that actually checks for "certain state".

Have not seen this behaviour myself though, interesting and will keep and eye on the various networks.

**Comment by dillu24** [comment]
It seems that with the latest API update this issue was solved. What i am noticing however is that when executing the `system.chain` function call during an epoch change, some of my nodes are taking very long to respond

**Comment by jacogr** [comment]
Ahhh, I stoopidly assumed you were on latest - since you generally are. From which version did you update? (It could have been the change events that created some chaos, but you would have seen _something_ in the logs in that case)

**Comment by dillu24** [comment]
Actually we updated from 1.18, but we also updated the nodes in the process, could be because of that. Another thing I was told on Riot is that the problem could be because the node would be busy computing phragmen computations, so esentially it would take long to service my request.

**Comment by jacogr** [comment]
There will be a big difference between 0.8.7 and 0.8.8 - the latter version would run natively and will execute faster. 

For instance on Kusama runtime version 200x maps to 0.8.x, so 2008 uses the native from 0.8.8. Same thing on Westend (2x -> 0.8.x) and Polkadot (x -> 0.8.x), assuming all Polkadot-like chains here. Especially on RPC, the 0.8.8 update was critical, it fixed some tx pool issues on RPC and was the main reason behind the release.
