### ISSUE TITLE
TypeScript compiler errors for type declarations 

### ISSUE THREAD

**Issue by nud3l** [polkadot-js/api#2355]
I'm trying to use the api package to build a front-end in React and Typescript. However, on a plain repo I get compiler errors in TS and I can't compile the code as below.

I'm just following the getting started guide from the documentation. 

**Code**

```js
import { ApiPromise, WsProvider } from '@polkadot/api';

const wsProvider = new WsProvider('wss://127.0.0.1:9944');
const parachain = await ApiPromise.create({ provider: wsProvider });
```

**Versions**
react: 16.13.1
typescript: 3.7.2

**@polkadot/api version 1.18.1**

If I use the latest version I get an error in the BN import:

```
../node_modules/@polkadot/api-derive/democracy/types.d.tsTypeScript error in ../node_modules/@polkadot/api-derive/democracy/types.d.ts(1,13):
'=' expected.  TS1005
  > 1 | import type BN from 'bn.js';
      |             ^
    2 | import { AccountId, Balance, BlockNumber, Hash, Proposal, PropIndex, ReferendumInfoTo239, ReferendumStatus, Vote, ReferendumIndex, VoteThreshold } from '@polkadot/types/interfaces';
    3 | import { Vec } from '@polkadot/types';
    4 | export interface DeriveDemocracyLock {
```
I had a look at the changelog and saw this was changed on May 11. So, next I tried an older version to see if that would fix the issue.

**@polkadot/api version 1.13.1**
However, that gave me a different error so not sure how to get around that.

```
../node_modules/@polkadot/api-derive/type/HeaderExtended.d.ts
TypeScript error in ../node_modules/@polkadot/api-derive/type/HeaderExtended.d.ts(10,5):
Invalid character.  TS1127

     8 |  */
     9 | export default class HeaderExtended extends _Header {
  > 10 |     #private;
       |     ^
    11 |     constructor(registry: Registry, header?: Header, sessionValidators?: AccountId[]);
    12 |     private _extractAuthor;
    13 |     /**
```
Is there anything in particular I need to do to make it work with react and typescript? I already tried adding @polkadot/types and @polkadot/typegen as additionally dependencies. I also tried adding @types/bn.js, but none of those fixed the first error with version 1.18.1.

**Comment by jacogr** [comment]
You need at least TS 3.8 - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#ecmascript-private-fields

**Comment by nud3l** [comment]
Updating to 3.9.5 solved this issue. Thanks for the quick reply!
