### ISSUE TITLE
registry.setMetadata has no effect

### ISSUE THREAD

**Issue by athei** [polkadot-js/api#2364]
In the substrate-api-sidecar project we try use metadata of a historical block. In order to do so through the `api.consts` namespace we register the historical metadata:
https://github.com/paritytech/substrate-api-sidecar/blob/c087497fa37ad84520e9dc00b4b5d419bf3ff75b/src/ApiHandler.ts#L589-L590

However, when accessing some metadata later on we always get the value for the current block instead of the block whose metadata we set:
https://github.com/paritytech/substrate-api-sidecar/blob/c087497fa37ad84520e9dc00b4b5d419bf3ff75b/src/ApiHandler.ts#L184

**Comment by jacogr** [comment]
It has the correct effect, just not what you expected - the registry does not handle re-decoration.

`registry.setMetadata` is there to ensure that the registry operations for calls/events/errors work, so it is only used in that context.

There is actually no recommended way atm to do what you expect, although the API does (internally) uses `injectMetadata` (both on chain load and metadata upgrades) to re-decorate. https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L140-L141

That will most probably be removed in a future version (and replaced) to cater for `.historic` queries.

**Comment by athei** [comment]
Thanks. I will close it then in favor of this feature request: https://github.com/polkadot-js/api/issues/2365
