### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by faboweb** [polkadot-js/api#2368]
The api object has a memory leak. This is consistent across many versions.

Here you see the memory consumption. The consumption consistently drops when disconnecting and reconnecting.

![image](https://user-images.githubusercontent.com/5869273/85206318-cffe6780-b2e6-11ea-86c7-5bc5df1deccc.png)

Is there a clean up we are missing somewhere?

**Comment by jacogr** [comment]
Without actual usage information, this is a bit of a needle in a haystack. Having said that theye are 2 places that do not clean up -

- where staking derives are used, some of them have an in-memory cache (no TTL)
- subscriptions to multiple value do have a cache (to fill in unchanged), no TTL there

**Comment by faboweb** [comment]
We run all requests for our wallet through the API. So we get all data a user needs. We run the API on the server so we don't init the API on the client as it is too slow to query data and we use IP whitelisted nodes.

We only use one block subscription. So that is probably not the issue.

Should there be a TTL for all data to prevent the API to cause crashes?

**Comment by jacogr** [comment]
This would be my immediate thought as to a culprit - https://github.com/polkadot-js/api/blob/5c5db2709b93451bc695adaf8a88dbbe32813337/packages/rpc-core/src/index.ts#L438-L441

(That comment has been there since it was introduced - which is why it jumps to the front of the mind as a possible culprit)

And LRU cache there would make sense (not quite straight-forward to do since it needs to keep type + values in mind. However even just keeping it on a per-connection basis and clearing values on on unsub would already have a jump in usability.

**Comment by dillu24** [comment]
We are also experiencing memory leaks lately. If we connect our [API server](https://github.com/SimplyVC/polkadot_api_server/blob/master/src/server.js ) with a high number of nodes, we are noticing that the heap size is always increasing such that our server eventually crashes.

After comparing heap dumps I am noticing that there a lot of entries related to the `state_storage` and Types such as `Registry`.

**Comment by jacogr** [comment]
The above would point to the cache, yes. As an aside, are you unsubscribing when the sub is no longer needed?

**Comment by dillu24** [comment]
Currently what we do is the following:

1. When our API server starts, it connects with all the nodes the user has inputted in the config file.
2. Whenever the user calls an endpoint, for example the `/api/query/imOnline/authoredBlocks`, the corresponding function from the `polkadot-js/ap`i is called (in this case `api.query.imOnline.authoredBlocks`). 
3. The connection with the Nodes providers is left as open in case of further requests.

Is there something we are missing, that we should do with regards to clean up?

**Comment by jacogr** [comment]
@dillu24 I have not take a peek at your code in the past (I promise it is on my TODO list, really want to), however took a quick, literally 2-3 min look into https://github.com/SimplyVC/polkadot_api_server/blob/master/src/substrate_query_interface.js

So there you always do `await api.query.<module>.<>something>()` - which is correct and it should unsubscribe and not keep stuff open. (In the case of `api.query.<module>.<something>((result) => {...})` you would need to manually unsub.

If all you usages are only `await <endpoint>` and you are seeing a lot of open subs, there is an issue with that type of construct - cannot comment if it is related to the above issue, so it _could_ be the same or something that is clearly a bug.

**Comment by dillu24** [comment]
Thanks for your clarification @jacogr . I will investigate further and put some more heap snapshots here maybe they can help.

**Comment by dillu24** [comment]
So, I compared two snapshots together, and the leakage is pointing to this piece of code in registry.js

![image](https://user-images.githubusercontent.com/23262259/85365082-e560d500-b524-11ea-9159-020d7655350a.png)

**Comment by jacogr** [comment]
I really appreciate this, it helps allowing me to start zooming in and makes it not less difficult, but less of a needle in a haystack.

Neither of those point to my suspected. So will start with the `await` approach here, track through and see what does not get cleaned up along the way. There is def an unintended area in here somewhere.

**Comment by dillu24** [comment]
@jacogr feel free to use directly our API server as a use case for debugging. Also, let me know if you need more heap dumps and data.

**Comment by jacogr** [comment]
The TL;DR of it - the swap to string ids broke the subscriptions, unsubscribe was never done. It lead to all of this. With #2380 that hole has now been closed and it is back to operating normally. (The bonus is that we got some nice optimizations out of this)

**Comment by faboweb** [comment]
Awesome @jacogr !!!! You're my hero
