### ISSUE TITLE
api.rpc.chain.getBlock(hash) fails

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#2372]
used version: 1.20.0-beta.7

api.rpc.chain.getBlock(hash) fails for certain blocks: 
e.g. block 2818682 (kusama)
`Unable to decode Vec on index 3 createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: findMetaCall: Unable to find Call with index 0x9614/[150,20]`
or block 2818627 (kusama)
`Unable to decode Vec on index 3 createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: findMetaCall: Unable to find Call with index 0xc2b1/[194,177]`
Seems the code cannot handle unknown callIndexes

btw: 
I'm currently scanning the chain for extrinsics with a special type.
What is the correct way tho check the correct callIndex? 
For example: I search for events of type staking.reward. Can you please give me a short code example? Thx

**Comment by jacogr** [comment]
Yes, it only handles with the currently metadata. If the metadata for older blocks are incompatible, it needs to be explicitly set.

See https://github.com/polkadot-js/api/issues/845 for the tracking issue with steps and links to others

**Comment by jacogr** [comment]
Closing.
