### ISSUE TITLE
About transaction fee

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/api#2386]
Is the fee for sending transactions is a certain value now? The fee required by westend and kusama is different. I see that there is no fee specified in the transaction body, can it be specified?

**Comment by jacogr** [comment]
It is calculated by the transaction weight. so when blocks are empty, the weight multiplier is lower and txs are cheaper. It is defined on a per-chain basis and adjusts dynamically.

**Comment by Wangmmx** [comment]
So fee does not participate in the construction of the transaction body, only calculated according to the size of the transaction after the transaction serialization?

**Comment by jacogr** [comment]
It is calculated based on the impact it has on runtime and the trie. So more reads, higher weight, more writes, higher weight.Larger tx size, higher weight.

**Comment by Wangmmx** [comment]
Thanks a lot, I get it

**Comment by Wangmmx** [comment]
Can fee be calculated in advance? For example, know some current reads and writes, or know the size of the tx

**Comment by jacogr** [comment]
https://polkadot.js.org/api/cookbook/tx.html#how-do-i-estimate-the-transaction-fees

**Comment by jacogr** [comment]
Closing.
