### ISSUE TITLE
DRR: TypeError: this._rpcCore.state.queryStorageAt is not a function

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#2398]
i created a faucet similar to the [Westend](https://github.com/w3f/faucet-bot) one, but when I try to run this line of code to transfer some funds from the faucet account to a requestor https://github.com/DataHighway-DHX/faucet/blob/master/helpers/contractDhx.js#L85
```
const transactionHash = await transfer.signAndSend(DAppDhx.faucetAccount);
```
it gives error:
```
DRR: TypeError: this._rpcCore.state.queryStorageAt is not a function
```
i'm using the latest stable version of `"@polkadot/api": "^1.21.1",`

According to the changelog https://raw.githubusercontent.com/polkadot-js/api/master/CHANGELOG.md, it looks like `queryStorageAt` was introduced in 1.9.1. I can't find that variable in the codebase.

I changed to using `"@polkadot/api": "=1.8.1",`, and it sent the transaction successfully

**Comment by jacogr** [comment]
That is a RPC that was included quite some time ago on Substrate. https://github.com/paritytech/substrate/pull/5362
