### ISSUE TITLE
How does historyDepts is used?

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2412]
Hi,

I am trying to index data from the genesis and for certain calls to ie. `erasRewardPoints` or `erasStakers` I am getting all zeros.
I think that it has to do something with history depth. Right now when I run `historyDepth` method I get 84. Does it mean that I can only query last 84 eras? If so how can I change it so that I can query all the eras all the time?

**Comment by jacogr** [comment]
The state only stores the most recent historyDepth eras for all staking.eras* data - this is only to facilitate payouts. If you want history data you need to query at a specific known blockhash.

(The state is not a traditional database, it carries the state to allow the node to process transactions - anything else is dicarded. If you run an archive node, you can access historical state)

**Comment by silentlight** [comment]
Ah ok. So simply I have to use .at correct?

**Comment by jacogr** [comment]
Yes. It is obviously more tricky since you need to understand where you are in terms of eras on historic queries. (era => blockHash mapping). That can be done by monitoring the events for session changes, on session changes where the activeEra increments it is the start of a new era.

**Comment by silentlight** [comment]
can I just do `await api.query.staking.currentEra.at(blockHash)`?

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/api.query.other.html#state-at-a-specific-block

**Comment by silentlight** [comment]
I understand how to query at specific height using .at. My question was referring to your comment about understanding where you are in terms of eras on historic queries.

What I do is:
I first get the block hash by given last height in era. Then I do
```
const eraAtRaw = await api.query.staking.activeEra.at(blockHash);
const eraAt = eraAtRaw.toJSON()['index'];
```
and then I use this era to do:
```
const erasTotalStake = await api.query.staking.erasTotalStake.at(blockHash, eraAt.toString());
```
It seems to work.
There are some queries that return nothing like:
```
const erasRewardPoints = await api.query.staking.erasRewardPoints.at(blockHash, eraAt.toString());
```

**Comment by jacogr** [comment]
Looks fine, although with some hoops. Option would unwrap -

```js
const activeAtOpt = await api.query.staking.activeEra.at(blockHash);

if (eraAtOpt.isSome) {
  const era = activeAtOpt.unwrap().index;

  const erasTotalStake = await api.query.staking.erasTotalStake.at(blockHash, era);
  const reward = await api.query.staking.erasValidatorReward.at(blockHash, era);

  ...
}
```

**Comment by silentlight** [comment]
Thanks @jacogr 

Do you know why this one does not work for me for height 2278812?

```
const reward = await api.query.staking.erasValidatorReward.at(blockHash, eraAt);
```

It returns nothing :/

**Comment by jacogr** [comment]
No idea. this could be around the point where the migration from `{validator, nominator}Payouts` to `stakerPayouts` took place which had a impact on storage entries, locations and operation..

**Comment by jacogr** [comment]
Closing, answered.
