### ISSUE TITLE
Problem with activeEra.at

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2415]
I am trying to get activeEra at specific height (558037) but I keep getting nothing.

```
const activeEraAtOpt = await api.query.staking.activeEra.at(blockHash);
```

Any idea why this is happening?

**Comment by jacogr** [comment]
`558037` - you need to be specific on the chain you are connecting to. Which substrate-based chain are you connecting to?

**Comment by silentlight** [comment]
@jacogr I am connecting to Kusama. Thanks

**Comment by jacogr** [comment]
So as you go back in the state on Kusama, the eras* (incl. activeEra) are not available. Those were all added and migrated to this year.

**Comment by silentlight** [comment]
Hmm ok. Is there any other way for the eras* to always work from the genesis?

**Comment by jacogr** [comment]
No. The storage entries were not there since genesis.

**Comment by jacogr** [comment]
Closing, answered.
