### ISSUE TITLE
What is the best way to parse event data

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2416]
I am trying to figure out what is the best way to parse event data.

For instance https://polkascan.io/kusama/event/3089836-3 has 3 attributes. I have actually 2 questions around it:
- Is there easy way to do something like eventData.getSender()?
- Can attributes be different for height ie. 100 and 1000000 for the same event method/name

**Comment by jacogr** [comment]
You need to check the event data - it is a tuple with the data (as per event), in order. Example here - https://polkadot.js.org/api/examples/promise/08_system_events/

Yes. Event data can (and do) change with upgrades.

**Comment by silentlight** [comment]
So even in case of balance transfer event where we have 3 attributes (from, to, value), this can change to to be let's say (value, from, to)?

**Comment by jacogr** [comment]
That could happen, but would be unlikely in practice.  Generally it is additions. (Devs try not to break compact)

**Comment by jacogr** [comment]
Closing, answered.
