### ISSUE TITLE
Configurable Headers in Providers

### ISSUE THREAD

**Issue by jack-kearney** [polkadot-js/api#2417]
HI!

I'd love to be able to create a provider that includes custom headers. We'd use this to authenticate to a node that we don't want open to the Internet.

If you're open to this, I can open up a PR that includes it.

**Comment by jacogr** [comment]
Please do. Makes 100% sense.

**Comment by brad-larson** [comment]
I've opened a PR to implement here: https://github.com/polkadot-js/api/pull/2423

**Comment by jacogr** [comment]
Closed in #2423
