### ISSUE TITLE
Support FixedI64, FixedI128 and FixedU128

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2439]
FixedI64, FixedI128 and FixedU128 are Substrate build-in types. `@polkadot/types` should support them out of box.

**Comment by jacogr** [comment]
Since they are no used in Substrate master pallets (or Polkadot), these are not testable and verifiable via the base metadata. The types align with what the latest substrate master exposes.

PRs welcome to add support, alternatively when Substrate master does use it in pallets, they will be added.
