### ISSUE TITLE
Transaction fee

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2442]
What is the easiest way to get a transaction fee?

**Comment by jacogr** [comment]
https://polkadot.js.org/api/cookbook/tx.html#how-do-i-estimate-the-transaction-fees

**Comment by xw332** [comment]
> https://polkadot.js.org/api/cookbook/tx.html#how-do-i-estimate-the-transaction-fees

which api could I use to get the whole info by any transaction hash??

jest like: https://polkascan.io/kusama/transaction/0x73c4013c1205de21a2a60c86911e90b8f48f8bfec1a6727bd4d93d0857a4f61b

**Comment by jacogr** [comment]
(Comment deleted, since there is an issue logged additionally - let's keep the issues to the point)

**Comment by jacogr** [comment]
Closing.

**Comment by silentlight** [comment]
@jacogr can I use https://polkadot.js.org/api/substrate/rpc.html#queryinfo-extrinsic-bytes-at-blockhash-runtimedispatchinfo for getting tx fee?
