### ISSUE TITLE
I want know the api to get the transaction info by transaction-hash

### ISSUE THREAD

**Issue by xw332** [polkadot-js/api#2445]
code like:

someapi(transaction-hash), return blockInfo and nonce and otherInfo

on website like: https://polkascan.io/kusama/transaction/0x73c4013c1205de21a2a60c86911e90b8f48f8bfec1a6727bd4d93d0857a4f61b

**Comment by jacogr** [comment]
Polkascan is a block explorer. As such they built a crawler that monitors the chain (which is not a Database), extracts the information is puts it into their database for queries. There is no author RPC to track extrinsic by hash in Substrate at this point.

**Comment by xw332** [comment]
> Polkascan is a block explorer. As such they built a crawler that monitors the chain (which is not a Database), extracts the information is puts it into their database for queries. There is no author RPC to track extrinsic by hash in Substrate at this point.

thanks ^-^

**Comment by jacogr** [comment]
Logged a Substrate issue (linked), so it gets tracked.
