### ISSUE TITLE
Create signature (type Signature or Sr25519Signature)

### ISSUE THREAD

**Issue by thashimoto1998** [polkadot-js/api#2446]
Please tell me how to create signature (type Signature or Sr25519Signature).

```
let sig = api.registry.createType("Signature", alice.sign(message))
let sig = api.registry.createType("Sr25519Signature, alice.sign(message))
```
above two code does not work.

**Comment by jacogr** [comment]
How do you mean it doesn't work? What are you trying to achieve?

**Comment by thashimoto1998** [comment]
I want to create signature (type of Signature or Sr25519Signature) by sign message and verify this signature at on chain runtime.

Error message:
 2020-07-22 01:24:13        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: CelerPayModule.0")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: Error de
/Users/hashimototatsuki/celer-pay-client/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: CelerPayModule.0")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: Error de

Onchain code: line 237,  1445 
https://github.com/celer-network/cChannel-substrate/blob/master/pallets/celer-pay/src/lib.rs

**Comment by jacogr** [comment]
Ok, so depending on how your chain is configured -

- If AnySignature, the on-chain signatures are 64-bytes in length, with no indicator
- if MultiSignature the on-chain signatures are 65 bytes in length, with a type indicator as the first byte

(Signature & Sr25519Sig are just aliasses for H512, i.e. the first form)

To generate the second type - 

- you need to tell the keypair to sign with type information (Passing `withType: true` as an option)
- pass these 65-bytes `[u8; 65]` for on-chain MultiSignature verification

**Comment by thashimoto1998** [comment]
It worked. Thank you.
