### ISSUE TITLE
Deposit in api.query.identity.identityOf

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2447]
What is the meaning of deposit field in query `api.query.identity.identityOf`? Is it first deposit? Current deposit?

**Comment by jacogr** [comment]
Please refer to the Rust code for the any unclarity - https://github.com/paritytech/substrate/blob/master/frame/identity/src/lib.rs

All the API does is decorate what is exposed by the node on the metadata - there is no actual addition/subtraction of information. so the pallet is the source of truth.
