### ISSUE TITLE
'Assertion failed' error of formatBalance

### ISSUE THREAD

**Issue by carmencitaqiu** [polkadot-js/api#2463]
when value > 0x20000000000000 ( 2 ^ 53),it will throw an error('Assertion failed') in assert function of formatBalance.d.ts.So why 0x20000000000000 is a limit for assert function?

**Comment by jacogr** [comment]
JS numbers are limited to 2^53-1 for integers. (JavaScript limit)

Pass a hex string or BN if you want bigger formatted.

**Comment by jacogr** [comment]
EDIT:  MAX_SAFE_INTEGER - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by carmencitaqiu** [comment]
if BN like 
 {
      number:8ac77ee06f075000,
      base:'hex'
    };
