### ISSUE TITLE
RPC parameter u128 type serialization 

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2464]
We have custom RPC that have argument type `Balance` (`u128`), and when calling this rpc with large input, polkadot.js serialize it into hex format, which is not supported on the Substrate side.

Should default serialize to string or provide a way to set serialization method.

Reproduce:

https://console.acala.network/#/js

Run this `console.log(await api.rpc.dex.getSupplyAmount('ACA', 'AUSD', {amount: '1000000000000000000'}))`

Getting error

```
Error: -32602: Invalid params: invalid type: string "0x00000000000000000de0b6b3a7640000", expected u128.
    at t.default._checkError (https://console.acala.network/polkadotjs.libs.cb6ec734.js:1:187411)
    at t.default.decodeResponse (https://console.acala.network/polkadotjs.libs.cb6ec734.js:1:186995)
    at N.value (https://console.acala.network/polkadotjs.libs.cb6ec734.js:1:470120)
    at WebSocket.value (https://console.acala.network/polkadotjs.libs.cb6ec734.js:1:469915)
```

**Comment by jacogr** [comment]
I would suggesting adjusting the RPC. This is the same format as used for numbers and the same way as supplied by Substrate, hence the BE encoding here. I understand that u128 is an issue, but we need to get it fixed consistently once and for all with the same inputs/outputs everywhere.

**Comment by xlc** [comment]
I just checked and I think none of the Substrate RPC takes u128 as input.

The transaction payment API returns u128 and it is serialized as decimal instead of hex

https://github.com/paritytech/substrate/blob/270a992bf299cd41b2ed4e211814d2a958e3bfc8/frame/transaction-payment/rpc/runtime-api/src/lib.rs#L48

**Comment by jacogr** [comment]
Yes, the API can handle number, string and hex. The point is that numbers, when big are returned as BE hex via RPC. This is why the RPC outputs do exactly the same. o doing a blanket change without proper testing is problematic. As an example, result formatting with numbers -

`{"jsonrpc":"2.0","result":{"block":{"extrinsics":["0x280403000bb01ea9b87301","0x1004140000"],"header":{"digest":{"logs":["0x0642414245b50101340000002d30dc0f00000000b4400b0d3ee65c793aa3c2c599e67b8c091a44203f1a7a332607c7f52f43b0420ff6e43cdec15f76db4d77212a1dae133822a39d753aecbea47879dedca6bb01c5a16f21f487ce0ce477d5eac40e10589734d331adf88378c7950153b762ba08","0x0542414245010146376f52bd24e9c3c9bc478c05d4e1ee296c58147bbb9fee882ca30a8ff29e39e854d8f23448f6eb6b7f16f8af34a0680674b3045ae9f132740be7abf2dc9380"]},"extrinsicsRoot":"0x688af73e65f2ada33f23bf9de48a743680ed82eaf476b6230eea3d2d9d186e6f","number":"0xf43a5","parentHash":"0xd7a7ccbb36e4e8eec5f6c18e9ee461871e58c81e5903cf54dceb1dcf9b298339","stateRoot":"0x72275f082f7a37d12e7888d7722f48cda2787ce35bf0da42dafdb3918f903b79"}},"justification":null},"id":65}`

So the above indicates that hex outputs/inputs BE-formatted is valid.

I am suggesting consistency - not working around issues where serde cannot handle u128 correctly. I don't have a horse in the race of what consistency is, but as long is it is expected in all cases, all onboard.

**Comment by xlc** [comment]
Interesting... I will update the Rust side then.
