### ISSUE TITLE
About Ecosystem Project Redenomination Guide

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/api#2465]
Hey, I have some questions about [Ecosystem Project Redenomination Guide](https://docs.google.com/document/d/1yAzoDh99PgR_7dYAKTWLMVu2Fy5Ga-J6t9lof4f4JUw/edit#heading=h.nn6lodwu31m3).

1. Dividing each DOT into 100 DOTS will change the decimal from 12 to 10, will you update the metadata? If the metadata need to be updated, does polkadotjs also need to be updated?

2. Does metadata need to be updated to enable transfers? does polkadotjs also need to be updated?

**Comment by jacogr** [comment]
The tokenDecimals appear in the chain spec - so once the RPC node is updated, it will just be displayed as defined on the UI.

With an upgrade, there is always updated metadata - this gets pulled from the chain, on connect the chain supplies the metadata and the API uses it.

**Comment by xwartz** [comment]
If metadata is updated, then polkadot.js should be updated as well? Otherwise, it may not be able to parse metadata.

**Comment by jacogr** [comment]
It only gets updated when there are new types to handle.

**Comment by xwartz** [comment]
Thanks.

**Comment by xlc** [comment]
But is `tokenDecimals` is hardcoded in [polkadot genesis json file](https://raw.githubusercontent.com/paritytech/polkadot/master/service/res/polkadot.json). Which is not upgradable via runtime upgrade. It is also not secured by consensus and required upgrade node binary to change. This will be troublesome.
