### ISSUE TITLE
Ability to override tokenDecimals from chain properties

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2466]
So that developer can make sure the correct value is applied regards to the Polkadot redenomination.

**Comment by jacogr** [comment]
This probably won't happen at all - since it has a knock-on effect everywhere. The RPC is the source of truth.

**Comment by jacogr** [comment]
It is actually already available - you can set anything into the chain properties used by the registry (for any internal formatting such as `toHuman()`) and it will be available as set here on the `registry.chainDecimals` getter -

https://github.com/polkadot-js/api/blob/master/packages/types/src/create/registry.ts#L314
