### ISSUE TITLE
Get storage entries for a particular block

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2469]
I would like to query historical account balances for all accounts at a particular block, something like

```
const accounts = await api.query.system.account.at(blockHash).entries()
```

But looks like not possible with current polkadot.js.

One way is add `blockHash` to `.entries()` and pass it to `getKeysPaged`

**Comment by jacogr** [comment]
Same would apply to `.keys` (as well as manual paging). Since these both take optional params, the `.at` pattern probably works better (and it consistent)
