### ISSUE TITLE
Event emitter generated methods are not all useful/desired in API docs

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#247]
When you go to https://polkadot.js.org/api/, and navigate to the **ApiRx** page https://polkadot.js.org/api/api/classes/_rx_index_.apirx.html, 
it displays EventEmitter information such as:

```
Inherited from EventEmitter.prefixed
Defined in /home/travis/build/polkadot-js/api/node_modules/eventemitter3/index.d.ts:6
```

The only one deemed useful is `on`, which could probably be wrapped to override it and expose it, to show the actual event names.
```
Inherited from EventEmitter.on
Defined in /home/travis/build/polkadot-js/api/node_modules/eventemitter3/index.d.ts:32
```

However we do not want to see stuff like `addListener`, as it just clutters

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/258
