### ISSUE TITLE
When executing the erasStakers function, it takes too long for Centrifuge nodes

### ISSUE THREAD

**Issue by leopoldjoy** [polkadot-js/api#2487]
I am trying to connect the PANIC [Polkadot API Server](https://github.com/SimplyVC/polkadot_api_server) (which uses polkadot-js) with a Centrifuge validator. However, when trying to connect I observe the following error:

```
Aug 12 13:10:24 ip-10-0-0-100 bash[13610]: Connecting to ws://10.0.0.110:9944
Aug 12 13:10:24 ip-10-0-0-100 bash[13610]: 2020-08-12 13:10:24        API/INIT: RPC methods not decorated: anchor_getAnchorById
Aug 12 13:10:25 ip-10-0-0-100 bash[13610]: Unknown types found, no types for ProposalVotes
Aug 12 13:10:25 ip-10-0-0-100 bash[13610]: Successfully Connected to ws://10.0.0.110:9944
Aug 12 13:10:25 ip-10-0-0-100 bash[13610]: API running on port 3000
Aug 12 13:10:46 ip-10-0-0-100 bash[13610]: Received request for /api/query/staking/erasStakers?websocket=ws%3A%2F%2F10.0.0.110%3A9944&account_id=4cZinFirTStRByraTHS7zQvs3AQeg4YLS6ft8NUS3MMeywzF
Aug 12 13:10:46 ip-10-0-0-100 bash[13610]: staking/erasStakers
Aug 12 13:10:46 ip-10-0-0-100 bash[13610]: 4cZinFirTStRByraTHS7zQvs3AQeg4YLS6ft8NUS3MMeywzF
Aug 12 13:10:46 ip-10-0-0-100 bash[13610]: null
Aug 12 13:10:46 ip-10-0-0-100 bash[13610]: Function call to getActiveEraIndex failed.
```

Note that the 7-9 in the above log are logging due to print messages I added for the purposes of debugging the parameters passed to the API request.

From the message it seems that there are still some missing types, namely the `ProposalVotes` message. Although following discussion with the Centrifuge team they did recently add most of the missing types in [this PR](https://github.com/polkadot-js/api/pull/2475).

And although the log says `Successfully Connected...` it doesn't in fact create a usable connection to the node (the PANIC alerter cannot receive the relevant data from the API server).

It seems that the `erasStakers` function takes too long when executing on Centrifuge nodes. Any idea why this is and what's going on here? Does this `erasStakers` function issue likely result from the missing `ProposalVotes` type?

**Comment by jacogr** [comment]
Don't think the additional types for the modules should affect it. 

Looking at the extrinsics on the Centrifuge node (via apps UI), it does not yet have `staking_payoutStakers`, so it would seem to be on a previous version of Substrate where there is auto-payout. in that case th call is not expected to work since it is unneeded.

**Comment by leopoldjoy** [comment]
Thanks for your response @jacogr.

Following your response, I've confirmed with the Centrifuge team that they are currently using an older version of Substrate.

We looked into using a matching older version of PANIC, however older versions are incompatible with the current version of the API server, and the accompanying (older) API server version isn't able to connect with current nodes.

Centrifuge are planning to release their node upgrade in approximately 4 weeks and it should include the missing extrinsics and types. As it stands currently, we must simply wait for this new Centrifuge release.

**Comment by jacogr** [comment]
The good news is that -

- Substrate is nearing 2.x
- Both Edgeware & Centrifuge are close to upgrading
- For recent-ish Substrate versions (post rc-3) there has not been massive breaking changes all round

But yes, you have my understanding here - if I had $0.02 for each override I've had to put in place to support oldest, old, newer, new, newest types of nodes in e.g. the apps UI, I would have been very happy. It is tough with a moving target.
