### ISSUE TITLE
Feature request: Support fixed point types exposed by substrate-fixed crate

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/api#2488]
The SCS team developed [substrate-fixed](https://github.com/encointer/substrate-fixed/), a fixed-point arithmetic crate compatible with Substrate and the SCALE codec. It is used projects like encointer and demonstrated in the Substrate Recipes. It is hoped that this implementation will become a common tool in the Substrate ecosystem.

This issue is a feature request to add the types `FixedI8`, `FixedU8`, etc to the API so that Substrate-based chains using this crate can encode their values using Polkadot JS.

**Comment by JoshOrndorff** [comment]
@brenzi Can you please link details about how the types are encoded?

**Comment by jacogr** [comment]
It is really an uphill battle to support external to Substrate & Polkadot crates. Since it cannot be tested and cannot be tracked. 

So not against the types, of they were part of Substrate frame itself. (Eg. See the recent additions for the FixedI64-and-fiends types from the base Substate.)

**Comment by jacogr** [comment]
Closing. Happy to re-open if there are PRs that bring in the types.
