### ISSUE TITLE
Staking event/transactions

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2490]
Is there a way to query staking transactions/events for given account?

I know that we have `erasStakers` https://polkadot.js.org/api/substrate/storage.html#erasstakers-eraindex-accountid-exposure, but this only returns stakers for given account and era. I am wondering if there is a `stake` transaction or event we can track?

**Comment by jacogr** [comment]
You can tracks events as emitted https://polkadot.js.org/api/substrate/events.html#staking or tracks the blocks with transactions https://polkadot.js.org/api/substrate/extrinsics.html#staking

There are no RPCs for per-account queries, so you'll need to built it up yourself by subscribing to events/blocks.

**Comment by silentlight** [comment]
Thanks @jacogr. So I was looking a bond event and bond transaction but I thought that this only tells how much balance account is "locking"? It does not really tell that account x staked y DOTs on account z.

**Comment by jacogr** [comment]
I'm not sure I understand the question - if you want to tracks events/txs, the above is what Substrate emits. If that is not the info you are looking for, then you need to query the relevant state. (As adjusted after the tx has executed)

**Comment by silentlight** [comment]
For instance here: https://polkascan.io/kusama/transaction/0x242ffa021acbe665a9a98bea93f54f940d335b110b5436fa9a60762ce25fea3a
We have staking->bond transaction. I see that address and controller are the same. Does it mean that it is self-delegation?

**Comment by jacogr** [comment]
At this point if you want to understand the actual event conditions (the linked docs are just generated from metadata, which is turn is as-is from the Rust code), you would need to consult the Rust code itself as the source of truth. 

(The API really only decorates what Rust exposes and the docs is generated in the same way. Any specific interpretation needs to be done with how that code emits the events)

**Comment by jacogr** [comment]
Closing as answered.
