### ISSUE TITLE
Kusama vs Polkadot

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2494]
I was wondering if I have to change my code using polkadot-js when I switch from Kusama to Polkadot?

**Comment by jacogr** [comment]
The API transparently injects the types for the different chains. However in most cases Kusama will be newer, so there may be calls that are different (older) on Polkadot. (Tis applies to state & extrinsics). As of right now, they are equivalent. (Apart from Kusama having more functionality)

So the answer is - it depends.

**Comment by jacogr** [comment]
Closing as answered.

**Comment by silentlight** [comment]
I am having problems when switching the proxy that we wrote from Kusama (0.8.22-c6ee8675-x86_64-linux-gnu) to Polkadot ('0.8.23-d327000a-x86_64-linux-gnu).
I get this error: ` RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: createType(BlockHash):: Cannot read property 'subarray' of null`.
Can you assist me in finding the the best way to fix it?
