### ISSUE TITLE
Question: call data for events

### ISSUE THREAD

**Issue by metmirr** [polkadot-js/api#2498]
I am storing runtime events and sometimes events parameters do not provide the data I need. For example, in the treasury module, there is [`TipClosing`](https://github.com/paritytech/substrate/blob/3f1341a384559ec046710e2f46eb4a7d9fc52f50/frame/treasury/src/lib.rs#L297) event. So when this event is dispatched by the `treasury` module (an extrinsic by treasury module) then I can access the extrinsic call parameter but when this event is dispatched with the `multisig` module then the extrinsic is totally different. I need a generic solution so I can access the extrinsic parameter without a problem.

More details:

```ts
// extrinsic is instance of { Extrinsic } from '@polkadot/types/interfaces';

// treasury.TipClosing event

// if the extrinsic is by treasury module args are not empty otherwise they are undefined
let _args = extrinsic?.args

if (extrinsic?.method.methodName === 'asMulti') {
  _args = (extrinsic?.args[3] as any).args
}
```

**Comment by jacogr** [comment]
It is an `OpaqueCall` type, which means a `Call` encoded as `Bytes`, i.e. has length prefixes. It is opaque since the meaning can change between upgrades and the utility module treats it as bytes only. To convert to `Call` -

```js
// uses toHex to get rid of the hex prefix (`toU8a(true)` should yield the same result
// as a valid input to the type creation)
const c = api.createType('Call', value.toHex());
```

**Comment by metmirr** [comment]
Thank you so much for your help! I can access call args now!
