### ISSUE TITLE
Support for ethereum-compatible types

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#2499]
API version of https://github.com/polkadot-js/common/issues/656

This needs unpacking, but some things I can immediately think of -

- [x] `AccountId` needs to use 20-bytes, not 32
- [x] `AccountId` needs to encode to the Ethereum version (display)
- [x] `Address` needs to use the above
- [x] `Extrinsic`, probably need hashing support as per this https://github.com/polkadot-js/common/issues/656#issuecomment-677974552 (However this really is config dependent, i.e. is all hashes replaced, or just this singular, i.e. for large payloads)
- ...

There will be more, needs to be unpack actually looking at what Rust does

**Comment by crystalin** [comment]
It looks good. I can test it tomorrow to see if there is anything missing. 
My substrate implementation of the ethereum is at the moment very much a hack over current substrate ECDSA, I'll have to test it too.

For the signature of the payload, do you use the Ethereum signature (including the r,v,s) ?

**Comment by jacogr** [comment]
It does work with the current ecdsa implementation, have tested live txs with that on Kusama, so yes, exactly as output here - https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/secp256k1/sign.ts

(For Ethereum, I'm assuming is is "edcsa", so the first byte of the MultiSignature is 2 (just the normal enum position for the impl)

**Comment by crystalin** [comment]
Than you Jaco, great work !
I confirm it is working with a Ethereum compatible Substrate implementation.

As discussed, some further improvement (outside of this scope) could be to better support MultiSignature enums (or even single Signatures).

**Comment by jacogr** [comment]
Closing. (Splitting out signature replacement for Extrinsics in https://github.com/polkadot-js/api/issues/2536)
