### ISSUE TITLE
Update e2e tests to simulate the UI

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#250]
Based on discussion with @jacogr. Currently the UI is not working due to Metadata changes.
Once the UI is working again, and we've finished api/promise PR, and Amaury's changes are made, we need to pull actual data from the UI and have real tests running on those. We will need to pull in the real world tests with the PR to avoid having to debugging the UI.
To do so we need to grab the json responses from the rpc and then push those in, as done here, we need more of these: https://github.com/polkadot-js/api/blob/master/packages/types/src/SignedBlock.rpc.json

We need those for each of the methods to ensure that it actually decodes as it should.

We also need to watch this Substrate PR https://github.com/paritytech/substrate/issues/847, as everything will need to be updated after it goes in

Note that it is not sufficient just to update https://github.com/polkadot-js/api/blob/master/packages/type-storage/src/fromMetadata.spec.js, as this isn't simulating real tests from UI.

**Comment by jacogr** [comment]
Ongoing, we are adding json as we are adding methods and types. This is not a once-off event. (Can re-open if somebody wants to do it bing-bang for all calls)
