### ISSUE TITLE
phase.asApplyExtrinsic returns invalid extrinsic index

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#2507]
Accessing the events of the westend chain, sometimes invalid extrinsic indexes are returned. 
Depending on the previously called functions, the results may be different.
Possibly the reason is an uninitialized variable?
The bug is reproducible, I have attached a small test program.
[main.ts.txt](https://github.com/polkadot-js/api/files/5114664/main.ts.txt)
Output of the program:
``` bash
Chain:    "Westend"
Node:     "Parity Polkadot" version 0.8.14-d0e553fe-x86_64-linux-gnu
API:      "@polkadot/api v1.29.1"
Block: 212903, event: 1 ExtrinsicIdx: 0
Block: 212903, event: 2 ExtrinsicIdx: 655360000
Block: 212903, event: 3 ExtrinsicIdx: 0
Block: 212904, event: 1 ExtrinsicIdx: 0
Block: 212904, event: 2 ExtrinsicIdx: 655360000
Block: 212904, event: 3 ExtrinsicIdx: 0
Block: 212904, event: 4 ExtrinsicIdx: 0
Block: 212904, event: 5 ExtrinsicIdx: 0
Block: 212904, event: 6 ExtrinsicIdx: 0
Block: 212904, event: 7 ExtrinsicIdx: 0
Block: 212905, event: 1 ExtrinsicIdx: 0
Block: 212905, event: 2 ExtrinsicIdx: 1
Block: 212906, event: 1 ExtrinsicIdx: 0
Block: 212906, event: 2 ExtrinsicIdx: 1
Block: 212906, event: 3 ExtrinsicIdx: 2
```

The events 212903-2 and 212904-2 refer to invalid extrinsics

**Comment by jacogr** [comment]
Thos are historic blocks, it is expected. Current metadata does not reliably decode previous runtime versions. So at each upgrade block, the extrinsic indexes may change. (As do events)

For historic queries, you need to inject the metadata yourself so it can be used. (API only retrieved current runtime version metadata and uses that). Additionally types do change, on earlier Westend blocks, u32 was used as weight - I actually think that is what creates the issue here. 

History of Westend types as it has gone through versions is here - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/westend.ts#L16

**Comment by TheGoldenEye** [comment]
Ok, you're right. I forgot to inject the right metadata here. Im my real project I do so. 
However, using the correct metadata does not solve the problem.
I've changed the test program:
[main.ts.txt](https://github.com/polkadot-js/api/files/5114824/main.ts.txt)

The result is the following.

1 Iterating from block 212903 to 212905:
``` bash
Chain:    "Westend"
Node:     "Parity Polkadot" version 0.8.14-d0e553fe-x86_64-linux-gnu
API:      "@polkadot/api v1.29.1"
Block: 212903, event: 1 ExtrinsicIdx: 0
Block: 212903, event: 2 ExtrinsicIdx: 1
Block: 212903, event: 3 ExtrinsicIdx: 2
Block: 212904, event: 1 ExtrinsicIdx: 0
Block: 212904, event: 2 ExtrinsicIdx: 1
Block: 212904, event: 3 ExtrinsicIdx: 2
Block: 212904, event: 4 ExtrinsicIdx: 3
Block: 212904, event: 5 ExtrinsicIdx: 3
Block: 212904, event: 6 ExtrinsicIdx: 3
Block: 212904, event: 7 ExtrinsicIdx: 3
Block: 212905, event: 1 ExtrinsicIdx: 0
Block: 212905, event: 2 ExtrinsicIdx: 258
```

2 Now from block 212904 to 212905:
``` bash
Chain:    "Westend"
Node:     "Parity Polkadot" version 0.8.14-d0e553fe-x86_64-linux-gnu
API:      "@polkadot/api v1.29.1"
Block: 212904, event: 1 ExtrinsicIdx: 0
Block: 212904, event: 2 ExtrinsicIdx: 655360000
Block: 212904, event: 3 ExtrinsicIdx: 0
Block: 212904, event: 4 ExtrinsicIdx: 0
Block: 212904, event: 5 ExtrinsicIdx: 0
Block: 212904, event: 6 ExtrinsicIdx: 0
Block: 212904, event: 7 ExtrinsicIdx: 0
Block: 212905, event: 1 ExtrinsicIdx: 0
Block: 212905, event: 2 ExtrinsicIdx: 1
```
3 And last block 212905 only:
``` bash
Chain:    "Westend"
Node:     "Parity Polkadot" version 0.8.14-d0e553fe-x86_64-linux-gnu
API:      "@polkadot/api v1.29.1"
Block: 212905, event: 1 ExtrinsicIdx: 0
Block: 212905, event: 2 ExtrinsicIdx: 1
```

Depending on the blocks loaded before, the results are different.
That's why I suspected a uninitialized variable.

In the case of a changed type: How can i handle it?

**Comment by jacogr** [comment]
It is most probably the Weight type (that appears inside blocks where extrinsics were included). So for older runtime versions set it to `u32`. (Alternatively it can be any of the other older types if they appear in an extrinsic)

**Comment by jacogr** [comment]
Ok, you do seem to inject the correct types. However, do ensure you padd the metadata for the previous block, not the current - state is updated at the end of the block, however only applies to the next. (Refering to this `const meta = await api.rpc.state.getMetadata(hash);`)

So if an upgrade happens at the end of that block the state is updated with the new metadata, but the extrinsics inside the block uses the metadata at the start of block execution. (Same with runtimeVersion, it is set at the end of extrinsic execution, but applies from the next block onwards only)

**Comment by TheGoldenEye** [comment]
ok, things look better now
[main.ts.txt](https://github.com/polkadot-js/api/files/5115092/main.ts.txt)
with your proposed change I get the following:
``` bash
Chain:    "Westend"
Node:     "Parity Polkadot" version 0.8.14-d0e553fe-x86_64-linux-gnu
API:      "@polkadot/api v1.29.1"
set metadata westend v3
Block: 212905, event: 1 ExtrinsicIdx: 0
Block: 212905, event: 2 ExtrinsicIdx: 1
----
set metadata westend v1
Block: 212903, event: 1 ExtrinsicIdx: 0
Block: 212903, event: 2 ExtrinsicIdx: 1
Block: 212903, event: 3 ExtrinsicIdx: 2
Block: 212904, event: 1 ExtrinsicIdx: 0
Block: 212904, event: 2 ExtrinsicIdx: 1
Block: 212904, event: 3 ExtrinsicIdx: 2
Block: 212904, event: 4 ExtrinsicIdx: 3
Block: 212904, event: 5 ExtrinsicIdx: 3
Block: 212904, event: 6 ExtrinsicIdx: 3
Block: 212904, event: 7 ExtrinsicIdx: 3
set metadata westend v3
Block: 212905, event: 1 ExtrinsicIdx: 0
Block: 212905, event: 2 ExtrinsicIdx: 258
```
Why seems the ExtrinsicIdx of event 212905-2 ok, if no other metadata was applied before, but it is 258, if the metadata changed from v1 to v3?

**Comment by jacogr** [comment]
The issue is the decoding goes wrong - so 258 means somewhere in the bytestream prior to that byte, it decoded something incorrectly. So it is never right at the point, but rather the data before then that makes s go wrong. For instance, if the last field before the data where the extrinsic starts is decoded as 2 bytes (instead of the correct 4), it would use the 3rd byte in the extrinsic to try and extract the index, instead of the first.

**Comment by TheGoldenEye** [comment]
you can do something here?

**Comment by jacogr** [comment]
Yes, the idea it to look at metadata and re-decoration alongside `.historic` queries. It is not something that can be done in isolation, since any changes there is actually quite difficult to test/verify, so it only makes sense alongside proper support.

**Comment by TheGoldenEye** [comment]
sure, I can test it
regardless of that first of all thank you very much for your support!

**Comment by TheGoldenEye** [comment]
Your PR fixed the issue, great!

However, I found that the runtime of v1.31.0-beta.15 is more than 50% longer than v1.30.1.

Examples with the code above:
v1.31 beta: 222 ms per block
v1.30.1: 141 ms per block

**Comment by jacogr** [comment]
It now natively will get the version and the metadata (as required) and will have a registry cache as well. 

So simplify - no manual injection. Just .at or RPC with the hash. It will handle the detection. It does mean .at queries do take slightly longer.

**Comment by TheGoldenEye** [comment]
Great extension!! Thx
