### ISSUE TITLE
PerThing confusion

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/api#2512]
1. It seems like the apps UI will never set the commission to 0. When I start a dev node and validate and set commission to 0, the resulting value in storage is: `[4]`, which is `0b0100` which is indeed the [compact](https://substrate.dev/docs/en/knowledgebase/advanced/codec#compactgeneral-integers) encoded value of `1`. 

I was told by Jaco that this is for UI reasons and for being able to distinguish between default values, but nonetheless the current solution is also not idea. 1% is not much but overall it could aggregate to some significant amount, and basically I think validators are not aware that they cannot place a true 0 percent commission on chain as of now.

2. Querying the same value from the UI: 

```
console.log(commission.unwrap().toHex());
console.log(commission.unwrap().toHuman());
console.log(commission.unwrap().toU8a());
console.log(commission.unwrap().toJSON());
console.log(commission.unwrap().toNumber());
console.log(commission.unwrap().toBn());
console.log(commission.unwrap().toString());
```

Will return 

```
0x00000001
0.00%
Uint8Array [ 1, 0, 0, 0 ]
1
1
<BN: 1>
1
```

All of which are sensible except for UnitArray returned. From this, It seems like this number is a normal 4 byte u32, not a compact one. I think what is happening here is that the api is trying to re-encode the type and it does not know if the type is u32 or Compact<u32>.

For such cases, and to avoid confusion, I have a proposal that should be easy to implement and will allow everything to be checked better. All of the above `toXXX()` contain a good amount of magic that most people appreciate. But I think it is also helpful to expose a `toRawBytes()` that returns the original scale encoded bytes of any `.query`. 

cc @emostov

**Comment by jacogr** [comment]
If the UI sets 1/1,000,000,000 the API will report as-is. So not sure what the uestion is, The API reports it as set on-chain.

**Comment by kianenigma** [comment]
> If you want to see the compact SCALE representation, do toU8a() without an unwrap.

This was the main thing I was missing. 

All good @emostov hope everything is clear to you as well.

**Comment by emostov** [comment]
I guess it seems like I am still missing something. My original question I brought to Kian is why can't I find a validator with a  commission of 0 Perbill, but there are plenty with 1 Perbill when I use the api to query validator prefs (for a sidecar endpoint).

I was not sure if there is some limitation with Perbill's, some defaults with polkadot-js, or validators literally just never set commission to 1 Perbill.

> When I start a dev node and validate and set commission to 0, the resulting value in storage is: [4], which is 0b0100 which is indeed the compact encoded value of 1... I was told by Jaco that this is for UI reasons and for being able to distinguish between default values...  basically I think validators are not aware that they cannot place a true 0 percent commission on chain as of now.

Sorry if this is redundant, but to clarify for myself, is the limitation keeping validators from setting a commission to 0 Perbill coming from the polkadot/app layer, polkadot/api layer or the substrate layer? And why does this limitation exist?

**Comment by kianenigma** [comment]
> I guess it seems like I am still missing something. My original question I brought to Kian is why can't I find a validator with a commission of 0 Perbill, but there are plenty with 1 Perbill when I use the api to query validator prefs (for a sidecar endpoint).

There are none because they all use the UI and the UI set 1 instead of 0.

> @jacogr @kianenigma Sorry if this is redundant, but to clarify for myself, is the limitation keeping validators from setting a commission to 0 Perbill coming from the polkadot/app layer, polkadot/api layer or the substrate layer? And why does this limitation exist?

App layer, and it is because if you query the commission rate of a non-validator now, the chain will also return 0 (non-existant == default), so setting 1 allowed the UI to distinguish the two.
