### ISSUE TITLE
API/INIT: Error: FATAL: Unable to initialize the API 

### ISSUE THREAD

**Issue by czl1378** [polkadot-js/api#2513]
When I upgrade @polkadot/api to '1.30.1', it occurs:
 `API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageKey):: Derived TypedArray constructor created an array which was too small`

**Comment by jacogr** [comment]
Which chain/node?

**Comment by easydeal-io** [comment]
> Which chain/node?

Development. Substrate Node v2.0.0-rc5

**Comment by jacogr** [comment]
On Substrate master, it should just work. On node-template, follow https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain to ensure the AccountId/Address types are set correctly.
