### ISSUE TITLE
Calling .concat() on Vec results in an error

### ISSUE THREAD

**Issue by Lezek123** [polkadot-js/api#2522]
**Example:**
```
const vec = api.createType('Vec<u32>', [0, 1, 2])
const vec2 = api.createType('Vec<u32>', [3, 4, 5]);
const vec3 = vec.concat(vec2);
```
This results in an error like:
```
TypeError: registry.createClass is not a function
```
But because `Vec` extends an `Array` through `AbstractArray` - this is perfectly valid script according to TypeSciprt compiler, which makes the issue hard to detect.

Other methods like `.filter()` and `.map()` seem to be handled correctly (since `AbstractArray` provides the overrides for them)

**Comment by jacogr** [comment]
Instead of trying to do everything, it just added the methods that was used internaly. Adding `.concat()` would be sensible. (PRs very welcome, but will mark it as enhancement and make sure it is in the queue)
