### ISSUE TITLE
can some help to explain the Fail （AlreadyPaired） Eorror when SetController

### ISSUE THREAD

**Issue by carltraveler** [polkadot-js/api#2523]
I tried to set the controller some times. but some success and some failed.  all failed explained the alreadyPaired reason. why

**Comment by jacogr** [comment]
It is sent from here - https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L1511-L1513

The controller is already paired to a stash.

**Comment by jacogr** [comment]
Closing.
