### ISSUE TITLE
Supports parsing the additional metadata

### ISSUE THREAD

**Issue by IIlIlI** [polkadot-js/api#2524]
Hi, I am using the latest version of the Substrate and ink development contract. But I found that Polkadot JS doesn't seem to support the new version of the ABI. (https://github.com/paritytech/ink/issues/299) . I wonder if there are any development plans.

**Comment by jacogr** [comment]
Indeed, see issue https://github.com/polkadot-js/api/issues/1660 and PRs https://github.com/polkadot-js/api/pull/1662 & https://github.com/polkadot-js/api/pull/2356
