### ISSUE TITLE
getFinalizedHead and meta injection

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2526]
Does `getFinalizedHead` use the most recent types and metadata by default?
When I use `registerTypes` and `injectMeta` to querying historical data and then afterwards I want to use `getFinalizedHead`, do I have to use the same injection methods for finalized head or does it happen for me automatically?

**Comment by jacogr** [comment]
The API always uses the latest metadata.

**Comment by silentlight** [comment]
Ok thanks. So I have to use registerTypes and injectMeta after I query historical data.
