### ISSUE TITLE
Query historical metadata without contaminating registry

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#2527]
There're cases we want to query metadata of a past block for comparison and don't want to have any side effects for such query. But with current implementation, it actually call `registry.setMetadata()`.
I believe this is an unexpected behavior for most people.

https://github.com/polkadot-js/api/blob/9c1327ea22e1e8600fa8d216ce36f6618ffdb093/packages/metadata/src/Metadata/MetadataVersioned.ts#L44

**Comment by jacogr** [comment]
Should be done as part of #845. As it stands, it is actually expected behavior, since the registry contains all the info. Until the API had native historical-query support, it is non-optimal.
