### ISSUE TITLE
`api.derive.chain.getHeader()` fails with repeated calls to same block; api version >= 1.31.beta.17

### ISSUE THREAD

**Issue by emostov** [polkadot-js/api#2541]
When querying `api.derive.chain.getHeader()` with an historic block hash (block from an older spec version) consecutively, it fails with the error `Unable to decode Vec on index 0 Tuple: failed on 0:: Invalid character`. I assume this is related to the optimization introduced here: https://github.com/polkadot-js/api/commit/637069d723bf9a8afcd42af8b3162a20737ff501

Here is a link to some code that illustrates the issue: https://github.com/emostov/substrate-tx-seed/blob/1-31-beta-17/src/main.ts (example is just in main.ts, rest of repo irrelevant, except for package info)

And here is that same code for posterity: 
```
async function main(): Promise<void> {
	const wsProvider = new WsProvider('wss://rpc.polkadot.io');
	const api = await ApiPromise.create({
		provider: wsProvider,
	});

	const hash1378238 =
		'0xbc38431a6a4e0cdaadd3b34d1fd1d6692cb08ff07d58bb1726101d341f100892'; // polkadot block number 1378238
	const firstTry1378238 = await api.derive.chain.getHeader(hash1378238);
	console.log('This works: (firstTry1378238) ', firstTry1378238?.toHuman());

	const secondTry1378238 = await api.derive.chain.getHeader(hash1378238);
	console.log('This works: (secondTry1378238) ', secondTry1378238?.toHuman());

	const hash1 =
		'0xc0096358534ec8d21d01d34b836eed476a1c343f8724fa2153dc0725ad797a90'; // polkadot block number 1

	const firstTry1 = await api.derive.chain.getHeader(hash1);
	console.log('This works: (firstTry1)', firstTry1?.toHuman());

	const secondTry1 = await api.derive.chain.getHeader(hash1);
	// Logs to console: Unable to decode Vec on index 0 Tuple: failed on 0:: Invalid character
	console.log(
		'This will not log to console (secondTry1)',
		secondTry1?.toHuman()
	);
}
```

Worth noting I consistently get this error with polkadot block 1, but with other low number blocks, consecutive calls seem to work sometimes.

**Comment by TheGoldenEye** [comment]
I can confirm the error, it also occurs in my code
