### ISSUE TITLE
Allow to opt out metadata swap for `isHistoric` queries

### ISSUE THREAD

**Issue by emostov** [polkadot-js/api#2542]
From my understanding, recently, the `isHistoric` flag is introduced to some RPC calls, causing a metadata swap that includes some overhead RPC calls (getRuntimeVersion and getHeader). 

For the use case of `substrate-api-sidecar`, it would be very helpful if this metadata swap could be opted out of (i.e. appending a param `isHistoric=false`). So far we are seeing a significant performance regression, even with the optimization introduced here: https://github.com/polkadot-js/api/commit/637069d723bf9a8afcd42af8b3162a20737ff501 - even though I would have thought it would have fixed performance issues because the endpoint services make every call possible at the same block hash.

Currently Sidecar has its own method to swap out metadata and we are working on a way to handle edge cases like runtime upgrade blocks while only having a minimal performance penalty (see here: https://github.com/paritytech/substrate-api-sidecar/pull/232). We are trying to avoid the overhead of call to `getHeader`, which the new built in swap implicitly does with every query to a different block hash. This is especially important because the longer an endpoint takes to respond, the higher the memory footprint of Sidecar grows with concurrent requests, and just all around lower throughput/ higher latency - which is becoming a concern as the users of Sidecar experience quickly scaling traffic.

Here are the response times from using our own metadata swapping with v1.30.1 and querying the same block endpoint 5 times in a row. The first is quite long because we have to fetch the metadata since we don't have any default metadaRpc (branch master, commit 3dfe6dc353da4027cae8ee63cc0bf5244a6490ca) :

![image](https://user-images.githubusercontent.com/32168567/91669167-c869f480-eac7-11ea-9091-388a7084dfcd.png)

And here are the response times when I disable our own metadata swap and use v1.31.beta.x (branch: zeke-tst-polk-js commit: bb52ae971a51701b4cdbc7c3f773ce57b796d8a3)

![image](https://user-images.githubusercontent.com/32168567/91669197-09620900-eac8-11ea-8063-10dc19964192.png)

Also for reference in case you want to see exact calls for this endpoint:
- controller: https://github.com/paritytech/substrate-api-sidecar/blob/zeke-tst-polk-js/src/controllers/v0/v0blocks/BlocksController.ts#L90
- service: https://github.com/paritytech/substrate-api-sidecar/blob/zeke-tst-polk-js/src/services/v0/v0blocks/BlocksService.ts#L39
- metadata swapping: https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/AbstractService.ts#L16

Also let me know if there is anything related to this that I can help implement on the polkadot-js side. I am not that familiar with the RPC architecture but happy to help and learn more about it.

**Comment by jacogr** [comment]
Have you disabled you ensureMeta?

**Comment by emostov** [comment]
Yes, in this branch on this line: https://github.com/paritytech/substrate-api-sidecar/blob/zeke-tst-polk-js/src/services/v0/v0blocks/BlocksService.ts#L39 - this is where the second screen shot is from

**Comment by jacogr** [comment]
So this is not going to be an opt-out since everybody puts in their own hacks for the same thing. Quite happy to accept PRs for optimizations.

However, the code you linked seems wrong. The metadata/version/types is supposed to be for the parent block, not the requested block. (State is applied at the end of the block to be available for the next)

**Comment by joepetrowski** [comment]
> So it seems the extra delay your are seeing is because it is done correctly, there is an extra lookup to get the parentHash before information retrieval. (For most blocks this is not an issue, if an upgrade did go through in a specific block, it is an issue since the metadata/types used for that block needs to be prior, i.e. as it was at the start of execution)

Yeah, but the metadata is generated by the runtime, so this is only an issue on blocks with an upgrade, which we can identify historically due to the `CodeUpdated` event, and can generally identify in the future by block number as long as `scheduler` is used. So we can keep a registry of blocks for which we need to take the extra step, which is exactly what we currently do.

The extra time that this change adds to each call adds an additional 6 _days_ to sync just 500k blocks. That adds 2.5 weeks to sync Polkadot at its current height.

**Comment by jacogr** [comment]
Adjusted the script in the other closed issue to add -

```js
  let blockNumber = 0;

  while (true) {
    const start = Date.now();
    const hash = await api.rpc.chain.getBlockHash(blockNumber);
    const header =  await api.derive.chain.getHeader(hash);

    console.log(`${blockNumber}`.padStart(7), `${Date.now() - start}ms`, header?.author?.toString());

    blockNumber++;
  }
```

Yielding results -

```
    937 106ms 15zF7zvdUiy2eYCgN6KWbv2SJPdbSP6vdHs1YTZDGjRcSMHN
    938 155ms 15zF7zvdUiy2eYCgN6KWbv2SJPdbSP6vdHs1YTZDGjRcSMHN
    939 148ms 167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM
    940 122ms 12zSBXtK9evQRCG9Gsdr72RbqNzbNn2Suox2cTfugCLmWjqG
    941 152ms 12zSBXtK9evQRCG9Gsdr72RbqNzbNn2Suox2cTfugCLmWjqG
    942 150ms 146YJHyD5cjFN77HrfKhxUFbU8WjApwk9ncGD6NbxE66vhMS
    943 148ms 12zSBXtK9evQRCG9Gsdr72RbqNzbNn2Suox2cTfugCLmWjqG
    944 149ms 146YJHyD5cjFN77HrfKhxUFbU8WjApwk9ncGD6NbxE66vhMS
    945 124ms 12H7nsDUrJUSCQQJrTKAFfyCWSactiSdjoVUixqcd9CZHTGt
    946 109ms 12H7nsDUrJUSCQQJrTKAFfyCWSactiSdjoVUixqcd9CZHTGt
    947 115ms 13wY4rD88C3Xzd4brFMPkAMEMC3dSuAR2NC6PZ5BEsZ5t6rJ
    948 143ms 12H7nsDUrJUSCQQJrTKAFfyCWSactiSdjoVUixqcd9CZHTGt
    949 148ms 12H7nsDUrJUSCQQJrTKAFfyCWSactiSdjoVUixqcd9CZHTGt
    950 160ms 167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM
    951 188ms 167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM
    952 116ms 15zF7zvdUiy2eYCgN6KWbv2SJPdbSP6vdHs1YTZDGjRcSMHN
    953 107ms 13wY4rD88C3Xzd4brFMPkAMEMC3dSuAR2NC6PZ5BEsZ5t6rJ
    954 153ms 13wY4rD88C3Xzd4brFMPkAMEMC3dSuAR2NC6PZ5BEsZ5t6rJ
```

There is a jump at upgrade blocks where it gets the updated metadata.

**Comment by jacogr** [comment]
If you are asking for an enhancement around actual known versioned upgrade points (since we do have the header and can shortcut based on known-number ranges), this would certainly be useful for known chains. 

Obviously adds overall benefit since everybody doesn't need to apply the same hacks and gets a boost right out of the starting blocks.

**Comment by jacogr** [comment]
@emostov I would suggest taking 1.31.0-beta.24 for a drive

**Comment by emostov** [comment]
Using `ensureMeta` with 1.30.1:
<img width="438" alt="1-30-1 (6req)" src="https://user-images.githubusercontent.com/32168567/91748709-3b7d7480-eb75-11ea-80d9-a747f0045ebc.png">

No `ensureMeta` using 1.31.1:
<img width="424" alt="1-31-1 (6 req)" src="https://user-images.githubusercontent.com/32168567/91748739-4801cd00-eb75-11ea-8b32-023f4862bd27.png">

Not including the initial query, it still seems to be a little slower on the average. I presume this is because while 1.31.1 saves a call to runtime version, it still calls for the header, which sidecar's `ensureMeta` does not do. 

However, I think this seems like the best solution/optimization I can think of for now. If @joepetrowski is ok with it, I would say we can close the issue.

**Comment by jacogr** [comment]
So there is still work left. And by that I would suggest looking at sidecar as well, 1.1-1.3s is a lot, especially when I get this on Polkadot for derive headers (so all the stuff + api.derive.chain.getHeader) -

```
...
    59,397      82ms 15zF7zvdUiy2eYCgN6KWbv2SJPdbSP6vdHs1YTZDGjRcSMHN
    59,398     111ms 167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM
    59,399      88ms 146YJHyD5cjFN77HrfKhxUFbU8WjApwk9ncGD6NbxE66vhMS

     59,400 blocks, 98.49ms/block 
```

The last number is the average over all blocks up to that point, spits out every 100 blocks.

**Comment by jacogr** [comment]
Closing an "wontfix", sadly the native support is not going away since it has been the #1 support burden in the last 9 months. Additionally there are a couple  of issues waiting that needs this (e.g. `consts.<module>.<method>.at(blockHash)` and `keys.at(...)`/`entries.at(...)`

Fo specific suggestions on additional improvements regarding performance (here and elsewhere), all ears. The last suggestion here actually helped a lot.
