### ISSUE TITLE
ApiPromise stucks on 'Connection dropped by remote peer.' and 'connection failed' errors

### ISSUE THREAD

**Issue by dvneverov** [polkadot-js/api#2565]
Hi! I'm using ApiPromise with websocket provider as singleton like this:

```
let wsProvider;
let client;

function createClientInstance() {
  wsProvider = new WsProvider('wss://rpc.polkadot.io');

  client = new ApiPromise({ provider: wsProvider });
}

async function buildDotClient() {
  try {
    if (!wsProvider) {
      createClientInstance();
    }

    await client.isReady;

    return client;
  } catch (e) {
    throw new Error('service_unavailable');
  }
}
```

And then use client in some script inside interval. But from time to time I get such errors:
`API-WS: disconnected from wss://rpc.polkadot.io code: '1006' reason: 'Connection dropped by remote peer.'`
`API-WS: disconnected from wss://rpc.polkadot.io code: '1006' reason: 'connection failed'`

And after throwing such error from ApiPromise, script gets stuck. It's even impossible to catch for following restart.
I even tried to add event emitter listenings, but still the same:
```
    client.on('disconnected', () => {
      createClientInstance();
    });

    client.on('error', () => {
      createClientInstance();
    });
```

Maybe it is possible to restart connection manually?

Package version:
"@polkadot/api": "^1.30.1"

**Comment by jacogr** [comment]
The API reconnects on connection interruptions. If you want to manage the connection manually, pass `{ autoConnect = false }` to your provider. That way you can actually call `.connect()` on the provider manually.

**Comment by dvneverov** [comment]
When I tried first, I used 
`const api = await ApiPromise.create({ provider: wsProvider });`

Just like in example in docs: https://polkadot.js.org/api/start/create.html#create-an-instance

But at one moment it failed with errors I mentioned above and stopped working until restart of application/script

**Comment by jacogr** [comment]
So the initial issue is most probably related to the enhancement that went in today - https://github.com/polkadot-js/api/pull/2577

Basically the `isReady` can throw an error.

For the manual connect/disconnect, it seems the api exposes a `api.disconnect()` (just calling the `provider.disconnect()` but doesn't have a equivalent `api.connect()` (which would call `provider.connect()`, see https://github.com/polkadot-js/api/issues/2578)

So with the connect/disconnect on the provider you can manually break/resume the connection, even today.

**Comment by jacogr** [comment]
The actual event emission for connection errors is now handled in #2578

In the above, using the latest version of the API (beta only), it is not suggested to destroy instances. If you manually wish to connect, use `.connect()` or `.disconnect()`

**Comment by jacogr** [comment]
Closing on the back on #2577 , #2580 & #2585 - in all cases the API will continue to retry (if not manually done via connect/disconnect) as well as raise errors via the provider.
