### ISSUE TITLE
PaymentInfo call throws 'Error decoding field Call'

### ISSUE THREAD

**Issue by KanLei** [polkadot-js/api#2568]
I'm creating two `ApiPromise` instances, one use to connect Kusama network and the other use to connect Polkadot network. When I use the two instances to call `paymentInfo` for estimate tx fee at the same time, then get error below:

`RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 2: Unable to query dispatch info.: Error decoding field Call :: Authorship.0`

my code:

    const kusamaApi = new ApiPromise({ provider: kusamaProvider });
    await kusamaApi.isReady;
    const polkadotApi = new ApiPromise({ provider: polkadotProvider });
    await polkadotApi.isReady;

    const transfer = await kusamaApi.tx.balances.transfer("Efc2jfxwUVUrjCSs4t3o6QJU3R8xqtHpwDvhD2f1oKactFX", 1)
        .paymentInfo("Efc2jfxwUVUrjCSs4t3o6QJU3R8xqtHpwDvhD2f1oKactFX");

    const transfer2 = await polkadotApi.tx.balances.transfer("136HWkbAAtk2YcPX41813HsTB58YrUdFT47fTqk4668c4Fkv", 1)
        // this call will get error
        .paymentInfo("136HWkbAAtk2YcPX41813HsTB58YrUdFT47fTqk4668c4Fkv");

**Comment by jacogr** [comment]
Which version of the API and from which node?

**Comment by KanLei** [comment]
API version `"@polkadot/api": "^1.30.1"`
Kusama RPC `wss://kusama-rpc.polkadot.io/`
Polkadot RPC `wss://rpc.polkadot.io/`

error message:

`RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo::1: Unable to query dispatch info.: Execution(Wasmi(Trap(Trap { kind: Unreachable })))`

**Comment by jacogr** [comment]
Nothing jumps out on the above, i.e. no known reports/issues along the same lines. So happy to take a look. Before I do so, could you just also verify that it still occurs in the latest 1.31 release (latest as of Monday).

**Comment by KanLei** [comment]
Yes, I have upgrade to API 1.31.2, still get the same error.

**Comment by jacogr** [comment]
Ok, sadly I can confirm, this is really _exceptionally_ weird. When there is a fix, will link the PR through.

**Comment by jacogr** [comment]
Fixed in 1.32.0-beta.12 and later. (Tested against the same script provided here)
