### ISSUE TITLE
Problem on Polkadot 0.8.23

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2571]
I am having problems when switching the proxy that we wrote from Kusama (0.8.22-c6ee8675-x86_64-linux-gnu) to Polkadot ('0.8.23-d327000a-x86_64-linux-gnu).
When I use Kusama it all works fine. When I switch to Polkadot, I get this error: `RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: createType(BlockHash):: Cannot read property 'subarray' of null`.
Can you assist me in finding the the best way to fix it?
I am running the newest version of polkadot-js: 1.30.2.

**Comment by jacogr** [comment]
You need to show code.

**Comment by silentlight** [comment]
Here is the proxy we built for our indexer: https://github.com/figment-networks/polkadothub-proxy

**Comment by jacogr** [comment]
I honestly would struggle to download, run and look for errors. You really need to be specific here. (I am not being obnoxious, but you are putting a big as up there to debug your code- zoom in, let me help you)

**Comment by silentlight** [comment]
Sorry :) So I think it fails here: https://github.com/figment-networks/polkadothub-proxy/blob/master/utils/setup.js#L14
It seems that it fails on `api.rpc.chain.getBlockHash()` and the height I use is 2278822.
When I use height 1 it works just fine.

**Comment by jacogr** [comment]
Depends on what version of the API, that seems to hack the metadata, in 1.31 there is transparent support for historic queries, see - https://github.com/polkadot-js/api/releases/tag/v1.31.1

**Comment by silentlight** [comment]
@jacogr It is working now. I updated to v1.31.1 and everything seems to be working fine! 
You are the man!

**Comment by jacogr** [comment]
Closing as resolved.
