### ISSUE TITLE
How to get extrinsic status?

### ISSUE THREAD

**Issue by anhcao142** [polkadot-js/api#2591]
Hi, currently I need to monitor the network for Dot deposit and withdrawal, the only way I know now is using the method `getBlock` (api.rpc.chain.getBlock) then loop through the extrinsic in the block, but the object does not include information such as `feeUsed` and `status`. For `fee` I think I can get from this method: `api.rpc.payment.queryInfo()`, but I don't know to query the status information of the extrinsic. So how to get extrinsic status?

**Comment by jacogr** [comment]
Not sure what you mean by "status". Each extrinsic hs either a ExtrinsicSuccsess" or "ExtrinsicFailed" event attached from the system module. Likewise the fees paid are available for each extrinsic via the deposits. Attaching a screenshot from the apps UI where it shows all events for a specific transfer -

- treasury.Deposit - the fees that went to the treasury
- balances.Deposit - the fees that went to the validator
- system.ExtrinsicSuccess - the success event

![image](https://user-images.githubusercontent.com/1424473/92482377-da464880-f1e7-11ea-92dc-b6ebe6e92e4d.png)

**Comment by anhcao142** [comment]
Thanks for your support but how to extract such information? Below is my code, and what I get from `extrinsic.toHuman()` doesn't contain `events`:

```javascript
const wsProvider = new WsProvider('wss://westend-rpc.polkadot.io');
const api = await ApiPromise.create({ provider: wsProvider });
const block = await api.rpc.chain.getBlock('0xfc0c1c839a8d187d51e5c26cd7913ac15a89f61960a01de432addaec502d641d');
block.block.extrinsics.forEach(async (ex, i) => {
  console.log(i, ex.toHuman());
});

// Result
// {
//   "isSigned":true,
//   "method":{
//      "args":[
//         "5Cm3AMwNKyLMmXu1dxuveBh4Zna6YqrU841BM6CqessSpN2J",
//         "500.000m WND"
//      ],
//      "callIndex":"0x0400",
//      "method":"transfer",
//      "section":"balances"
//   },
//   "era":{
//      "MortalEra":{
//         "period":"64",
//         "phase":"55"
//      }
//   },
//   "nonce":"2,928",
//   "signature":"0xd0e3817b644edb2fc0d7d5a866e90b18f0a196536937a47a8bf1caae71cc1275c51d801fb3d1e4ae9170d90350b584ddbc218ab2eefcc63ed2931e6fe1f51389",
//   "signer":"5HpLdCTNBQDjFomqpG2XWadgB4zHTuqQqNHhUyYbett7k1RR",
//   "tip":"0"
// }
```

**Comment by anhcao142** [comment]
Nevermind @jacogr, I kinda managed how to query `events` by scanning through the code in [Substrate Api Sidecar](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/blocks/BlocksService.ts), it's `api.query.system.events.at(blockHash)`.

So to calculate the total fee, I just need to sum `treasury.Deposit` and `balances.Deposit` if any of them exist right?

**Comment by jacogr** [comment]
100%

**Comment by anhcao142** [comment]
Thank you @jacogr, awesome support.
