### ISSUE TITLE
Uncaught syntaxerror on OPPO android

### ISSUE THREAD

**Issue by KanLei** [polkadot-js/api#2600]
OPPO android 6.0.1 cannot run this library, webview cannot parse es6 syntax, got error: `Uncaught SyntaxError: Unexpected token ...`. But when I try to use `babel` to tranform to es5, still got error: `Uncaught TypeError: t(...) is not a function`.

I not very familiar with javascript and babel, this is my babel config:

webpack.common.js

    const path = require('path');
    module.exports = {
        entry: {
            main: './src/index.js',
        },
        output: {
            path: path.resolve(__dirname, "../", "dist"),
            filename: '[name].js',
        },
        resolve: {
            extensions: ['.js'],
        },
        module: {
            rules: [
                {
                    test: /\.(js|jsx)$/,
                    loader: 'babel-loader',
                    options: {
                        presets: ["env", "stage-0"],
                        plugins: ["transform-runtime"]
                    },
                    // exclude: /node_modules/
                },
            ]
        },
        plugins: []
    }

webpack.prod.js

    const merge = require('webpack-merge');
    const common = require('./webpack.common.js');

    module.exports = merge(common, {
        mode: 'production',
        devtool: "source-map",
        module: {
            rules: []
        },
        plugins: [
        ]
    });

`"release": "webpack --config build/webpack.prod.js"`

How to use this library on android with low version webview, or which library I could use for mobile phone app? Thanks.

**Comment by jacogr** [comment]
Which error is the first one? All libs does get compiled down to es5, however it does assume at least a reasonable up-to-date version.

Since you are compiling via babel, check your config there to ensure it uses the babel-preset with a sufficient version range. so you want your babel setup to have targets that assumes older versions, an example config for reasonably recent is here - https://github.com/polkadot-js/dev/blob/master/packages/dev/config/babel.js#L22 (Not applicable for you, but you can tweak those values to your liking in your project and Babel will comply)

**Comment by KanLei** [comment]
Thanks. At first, I just run with `webpack -p --mode production` without any babel config, on OPPO android will get the first error `Uncaught SyntaxError: Unexpected token ...`, looks like the  javascript spread syntax cannot be parse. 

Then I try to use babel, all my babel config in the code above `webpack.common.js` and `webpack.prod.js`, then get the second error `Uncaught TypeError: t(...) is not a function`, looks like the syntax transform worked. But I don't know if this config is correct and how to tweak the config to correct. I will try.

**Comment by jacogr** [comment]
Closing as-is since it really a a local build-target setup. (And yes, Babel configs are not always simple in support :()
