### ISSUE TITLE
Mapping blocks to timestamp

### ISSUE THREAD

**Issue by dillu24** [polkadot-js/api#2603]
Is there a way we can get the timestamp of a block using the API?

**Comment by jacogr** [comment]
Each block has a `timestamp.set` extrinsic containing the timestamp of the node creating the block - https://polkadot.js.org/api/substrate/extrinsics.html#set-now-compact-moment

**Comment by dillu24** [comment]
So if I get the block using `api.rpc.chain.getBlock`, which is the timestamp?

**Comment by jacogr** [comment]
The `timestamp.set` extrinsic. So under the block extrinsics, filter for that module with the method and use the compact value as the timestamp. Loop through in a similar fashion to here - https://polkadot.js.org/api/cookbook/blocks.html#how-do-i-view-block-extrinsic-information

**Comment by dillu24** [comment]
So for example this is returned if I Iterate through `ex.toHuman()`

![image](https://user-images.githubusercontent.com/23262259/93096036-2a1f8680-f6a4-11ea-96bd-4266697fa7d3.png)

Does arg represent the timestamp? And how can this be converted to an actual timestamp?

**Comment by jacogr** [comment]
```js
// no blockHash is specified, so we retrieve the latest
const signedBlock = await this.api.rpc.chain.getBlock();

// the information for each of the contained extrinsics
signedBlock.block.extrinsics.forEach(({ method: { args, method, section }) => {
  /// check for timestamp.set
  if (section === 'timestamp' && method === 'set') {
    // extract the Option<Moment>
   const moment = args[0].unwrap();

    // convert to date (unix ms since epoch in Moment - exactly as per the Rust code)
    const date = new Date(moment.toNumber());
  }
});
```

**Comment by dillu24** [comment]
Understood, thanks!

**Comment by jacogr** [comment]
Closing, believe it is esolved. (Also updated the cookbook entry this morning to be slightly more expansive) - https://polkadot.js.org/api/cookbook/blocks.html#how-do-i-view-block-extrinsic-information
