### ISSUE TITLE
 What should I do if I need to fork a piece of code as our dependency in polkadot/app? The reason for this is that we have made a lot of changes to the staking module, and the existing api can no longer be adapted

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/api#2607]

**Comment by jacogr** [comment]
The apps UI itself is very unlikely to support customizations to specific standard Substrate modules that are deployed to a subset of chains. It already carries a very heavy burden trying to support very old, old, previous-versions and current versions through all the standard modules. (It is really simple supporting a single chain, it is difficult supporting multiples as versions change through time)

So what is will always (try very hard to support) -

- various iterations of modules, as deployed on older chains, current chains and future chains (for instance in staking it has support for early-generation versions as well as the current generation, even with chains still using linked lists)
- detection of modules to make sure things don't break when the module is not available (e.g. some chains don't have Balances, the apps UI tries to assume that chains are no alike)
- where it makes incorrect assumptions on features and detection is missing, it should be adapted to "not do the wrong thing"

**Comment by yuhui1208** [comment]
Is it possible for me to fork out polkadot/api to modify some of these methods, then publish to npm, and then reference my own published library in apps? If I want to do this, how do I publish the api?

**Comment by jacogr** [comment]
So the API itself allows you to inject your own derives. (Not in the apps UI though, but a fork of that will allow you to inject them)

The simplest would always be to just modify the calls in a fork of the apps UI, less moving parts.
