### ISSUE TITLE
Querying balance with api.query.balances.account returns 0 but not with api.query.system.account

### ISSUE THREAD

**Issue by lovesh** [polkadot-js/api#2617]
I have a non-zero balance account and when i query with `api.query.balances.account(address)` I get result `{"free":0,"reserved":0,"miscFrozen":0,"feeFrozen":0}` but when querying with `api.query.system.account(address)` I do see the actual balance and the nonce and other things.
My node is based off node-template (rc-6) and I am using polkadot js version 1.32.1 and passing the following (apart from my chain specific) types to `ApiPromise.create`:

```
  "Address": "AccountId",
  "LookupSource": "AccountId",
  "AccountData": {
    "free": "Balance",
    "reserved": "Balance",
    "misc_frozen": "Balance",
    "fee_frozen": "Balance"
  },
  "Balance": "u64",    // 8 bytes are enough for holding total issuance on my chain.
```
I am able to reproduce the result in polkadot-js apps UI as well in chain state section as well as seen here https://prnt.sc/uij3oh and here https://prnt.sc/uij3u6

**Comment by jacogr** [comment]
It is completely expected. It depends on the chain config. A singular write (along with nonce) to system optimizes trie storage. 

Depending on the chain config (as set in the runtime) it may be in either position, however most newer Substrate based chains will optimize with system.

**Comment by jacogr** [comment]
If based on node-template, see lines 190 & 241 for the config that swaps the  storage to system - https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime/src/lib.rs

**Comment by lovesh** [comment]
Thanks @jacogr, understood. So with the chain config I have, `system` module should be used and not `balances`.
