### ISSUE TITLE
Can Not Get Block  When i call the method  ''api.rpc.chain.getBlock(blockHash) " 

### ISSUE THREAD

**Issue by yzbbanban** [polkadot-js/api#2623]
Unknown types found, no types for Announcement
block hash: 0x2c17980245d4be1e3617692eae9ce0facfca2f2143c14e9752972855f2b8f71b
Unable to decode Vec on index 3 createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 3, in Staked, Stash, Controller
2020-09-18 09:46:31        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call)::
Struct: failed on 'args':: Unable to create Enum via index 3, in Staked, Stash, Controller
block hash error: Error: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 3, in Staked, Stash, Controller

**Comment by jacogr** [comment]
Which network? Which version of the API?

**Comment by jacogr** [comment]
Assuming Kusama/Polkadot, update to the latest beta version (Will be in Monday's release)
