### ISSUE TITLE
How do we convert bytes from encoded number

### ISSUE THREAD

**Issue by thashimoto1998** [polkadot-js/api#2624]
In substrate(rust), type of encoded value is Vec<u8> and in polkadot-js, type of encoded value is Uint8Array. How to convert a value of type Uint8Array to value of type Vec<u8> or Bytes?

Error code 1
```
let u8_1 = api.registry.createType("u8", 1).toU8a();
let u32_25 = api.registry.createType("u32", 25).toU8a();
```

Error message is : 
mockNumericCondtion: error message is MustBeDecodable,

This error defined
```
let number: u8 = Decode::decode(&mut &_query[..]).map_err(|_| Error::<T>::MustBeDecodable)?;
```

Error code 2
```
let u8_1 = new Bytes(api.registry, api.registry.createType("u8", 1).toU8a());
let u32_25 = new Bytes(api.registry, api.registry.createType("u32", 25).toU8a());

```

Error message is:
UnhandledPromiseRejectionWarning: Error: Bytes: required length less than remainder, expected at least 2, found 1

**Comment by jacogr** [comment]
`api.registry.createType(<type>, <value>).toU8a()` encodes to SCALE, which the node expects. Generally you would never need to call it manually. Which actual call are you making to pass the data?

**Comment by thashimoto1998** [comment]
I want to call a function of args is encoded value of u8 and u32.
```
pub fn is_finalized(
        _app_id: &T::Hash, 
        query: Option<Vec<u8>>
    ) -> Result<bool, DispatchError> {
        let _query = query.unwrap();
        let number: u8 = Decode::decode(&mut &_query[..]).map_err(|_| Error::<T>::MustBeDecodable)?;
        if number == 0 {
            return Ok(false);
        } else {
            return Ok(true);
        }
    }
```
https://github.com/celer-network/cChannel-substrate/blob/master/pallets/mock-numeric-condition/src/lib.rs

This function is called by module of another pallet. In order to have a more loosely coupled architecture, It is necessary to all types values passed as arguments. So arg is encoded value.

**Comment by jacogr** [comment]
Ok, now I get it, you double-encode.

Ok, so the issue with passing a Uint8Array in anywhere is that it expects it fully encoded. This is why you have error condition 2, the value passed ins not a fully-encoded Vec. So the suggested approach is to pass  the hex value o the opaque" data and the Bytes will correctly add the length prefixes.

In code -

```js
// types as you have them
const u32 = api.registry.createType('u32', 123);

// hex values - ok, so you would normally jump to .toHex() here, but numbers have BE hex 
// representation as per JSON/RPC so we have to jump through hoops
const u32Hex = u8aToHex(u32.toU8a());

// Vec<u8>
const bytes = api.registry.createType('Bytes', u32Hex);

// an alternative would be to encode it correctly - more optimal, one less conversion
const bytes = api.registry.createType('Bytes', compactAddLength(u32.toU8a()));
```

**Comment by thashimoto1998** [comment]
It worked :) Thank you very much!
