### ISSUE TITLE
State already discarded for BlockId::Hash

### ISSUE THREAD

**Issue by z330789559** [polkadot-js/api#2629]
I run my project which called api ,i get some error, but not everytime ,sometime it is normal
The following error causes the program to crash
2020/9/21 下午2:36:0514:36:05 0|cube-job  | [2020-09-21 14:36:05.160] [ERROR]
2020/9/21 下午2:36:0514:36:05 0|cube-job  | 2020-09-21 14:36:05        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x34404caec5cf2f9e7a087a5fbef54975b7d
2020/9/21 下午2:36:0514:36:05 0|cube-job  | [2020-09-21 14:36:05.161] [ERROR]  2020-09-21 14:36:05        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x34404caec5cf2f9e7a087a5fbef54975b7d

**Comment by jacogr** [comment]
The node only keeps the last 256 blocks unless run in archive mode.

**Comment by z330789559** [comment]
i need redeploy fullnode and sync data?

**Comment by jacogr** [comment]
Yes, after changing you would need a re-sync, see the `--pruning` flag in the node help.
