### ISSUE TITLE
Cater for older chain for derive eraStakingExposure

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#2630]
As discussed https://github.com/polkadot-js/apps/pull/3714#discussion_r490943875

**Comment by jacogr** [comment]
I'm actually of the opinion to just leave it as-is. The problematic live chain until now was Edgeware and they have 2 days 18hrs as of writing being updating to rc3-era. (So in that case we can actually start removing some of all these old hacks in derives)

**Comment by Tbaut** [comment]
Nice, closing  then.

**Comment by jacogr** [comment]
Closing, Edgeware is also updated.
