### ISSUE TITLE
Query Transaction and Block

### ISSUE THREAD

**Issue by thanlok** [polkadot-js/api#2636]
Hi, I am trying to query transaction with the transaction id only (not inside the signAndSend callback) and query the block details(with transactions details inside if possible) through the lib? Can you give example on how to do so? Thank you.

**Comment by jacogr** [comment]
There are no RPCs for transactionHash - it is non-unique accros blocks.

**Comment by jacogr** [comment]
There is a WIP entry on transactions and why they are not unique (and not indexed on Substrate) - https://docs.google.com/document/u/1/d/e/2PACX-1vRoGXUHxpaF6xARB_BduDRa8ynZKgFSi0G5TtzHubUZNmnSnO2KSdNrsn7nWRcAgSSqTDyhpXT9F1XN/pub

**Comment by thanlok** [comment]
I see. Since it says block ID and transaction index are used to uniquely identity the transaction, will i be able to retrieve the block id and transaction index in the `signAndSend` callback? How can i get the transaction by the block id and transaction index? Can you provide an example? thank you

**Comment by jacogr** [comment]
`.signAndSend` returns the events for the block. 

`.tx.hash()` always has (after signing) the tx hash.

**Comment by thanlok** [comment]
So the event of the block will include the block id and transaction index? If I want to query the transaction by using the block id and transaction index outside of the `signAndSend` callback function, how can i do so?

**Comment by jacogr** [comment]
Never had a need for this. So the way to go about it is to monitor all blocks, check the extrinsics against what was sent.  (Which is what signAndSend die via the author_submitAndWatch RPC)

**Comment by thanlok** [comment]
@jacogr I just want to make sure:

1. So the only way to monitor my own transaction is inside the `signAndSend` callback function, listening to the events?

2. Is there any way I can listen to my transaction events again after i lost connection or restart my system?

3. How can i monitor all blocks in order to monitor new deposits to my account?

**Comment by jacogr** [comment]
This would be helpful - https://polkadot.js.org/api/cookbook/blocks.html#how-do-i-view-block-extrinsic-information

**Comment by thanlok** [comment]
@jacogr got it, i missed out this page. One last question, how can i produce an on chain fail transaction? Or will there be any fail transaction?

**Comment by jacogr** [comment]
To make the transaction fail, it depends on the Rust implementation of the specific call. For instance, in staking you need to call bondExtra from the stash. Calling it from the controller (or any other invalid origin) will make it fail. 

To make it fail on the transaction pool (before execution), send a transaction that cannot pay fees.
