### ISSUE TITLE
error

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2653]
i run the below code on my private substrate chain.
i got this error!
how can solve this ?

----------------------------code-----------------------------------
var { ApiPromise, WsProvider } = require('@polkadot/api');

async function main () {
  // Initialise the provider to connect to the local node

  const provider = new WsProvider('ws://127.0.0.1:9944');
 

  // Create the API and wait until ready
  const api = await ApiPromise.create({ provider });
//  console.log(api);

  // Retrieve the chain & node information information via rpc calls
  const [chain, nodeName, nodeVersion] = await Promise.all([
    api.rpc.system.chain(),
    api.rpc.system.name(),
    api.rpc.system.version()
  ]);

  console.log(`You are connected to chain ${chain} using ${nodeName} v${nodeVersion}`);
}

main().catch(console.error).finally(() => process.exit());

----------------------------error------------------------------------
Unable to resolve type StrVecBytes, it will fail on construction
Unknown types found, no types for StrVecBytes
Unable to decode Vec on index 1 createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Cannot construct unknown type StrVecBytes
2020-09-25 13:07:05        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Cannot construct unknown type StrVecBytes
2020-09-25 13:07:05        API/INIT: Error: FATAL: Unable to initialize the API: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Cannot construct unknown type StrVecBytes
    at EventEmitter.value (/home/test/node_modules/@polkadot/api/base/Init.js:85:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15310) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Cannot construct unknown type StrVecBytes
    at EventEmitter.value (/home/test/node_modules/@polkadot/api/base/Init.js:85:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by jacogr** [comment]
See https://polkadot.js.org/api/start/types.create.html

The metadata does not convey the information about what is contained in a type, only the nsma.e

**Comment by puffanddmx** [comment]
i got it, but to understand more clearly,
can you show the example code to fix above my error code ?

**Comment by jacogr** [comment]
Pass the type definitions to the API create.

**Comment by puffanddmx** [comment]
Probably, polkadot api is made with typescript, and like rust, if you do not write type type, you will get an error.

What I want to know is how to get meta data from my private chain and put it in type form here in above javascript code.

**Comment by jacogr** [comment]
It is not a TypeScript issue, what I linked describe the problem - the data, over RPC, is a byte-stream encoded with the SCALE codec. To decode this data the JS side need to understand the structure.

So in what I linked for you -

- The first section, describes the why https://polkadot.js.org/api/start/types.extend.html#extending-types
- The second section describes how to pass the types to the API, https://polkadot.js.org/api/start/types.extend.html#extension
- The remaining sections shows how to define other complex types, eg. enum, structs, ...

**Comment by puffanddmx** [comment]
thanks for the reply!

for the below polkadot mainnet socket case, do not need that type right ?
-> polkadot encoded stream is in that default module right ?
const provider = new WsProvider('wss://rpc.polkadot.io');

**Comment by jacogr** [comment]
No, the Polkadot/Kusama types are managed as known types, so the API comes with a full definition for those chains. (Including their specific overrides, per spec version - so that is tracked to make it known to the API, e.g. https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/polkadot.ts)

**Comment by puffanddmx** [comment]
thanks for your support.
I think I know roughly what the link post you sent me. I have to extract the type information from my private chain. I would like to know how to extract it from my chain and convert it to human readable way. -> then adapt it to the type. ( i am not type of professional for coding , so understand me)

**Comment by jacogr** [comment]
To extract -

- look at the Rust code for the affected types
- define those types in a format the JS API understands

**Comment by puffanddmx** [comment]
ok i try it!

**Comment by puffanddmx** [comment]
thanks!
