### ISSUE TITLE
How can I query extrinsic events by JSON-RPC?

### ISSUE THREAD

**Issue by anhcao142** [polkadot-js/api#2661]
Sorry if this is not the place to ask this, but is it possible for me to query extrinsic events using JSON-RPC?

**Comment by jacogr** [comment]
There is no RPC for info via transaction hash.

Via the JS API you can use subscription and it will extract the events from the block where it has been included.

**Comment by anhcao142** [comment]
Currently, I'd prefer getting data using RPC methods like this (because WebSocket seems a lot slower than Http):

```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' http://localhost:9933/
```

I noticed there is this method `api.query.system.events.at("blockHash")` in the package, so is there any way I can get the same result using Http request like above?

**Comment by jacogr** [comment]
Sure. Just query for the events at the block it was includes.
