### ISSUE TITLE
Changing to u32 for Substrate 2.0

### ISSUE THREAD

**Issue by Dudleyneedham** [polkadot-js/api#2664]
https://github.com/polkadot-js/api/blob/68856e9692c64d0ace603f146f4904309e1b89ad/packages/types/src/interfaces/system/types.ts#L258

Wondering if this should be updated to `u32` due to the changes from the `RefCount` in the Substrate update.

**Comment by Dudleyneedham** [comment]
Nevermind, I noticed changes in a new commit.

**Comment by jacogr** [comment]
See 

- definition https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/system/definitions.ts#L273
- generated type https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/system/types.ts#L252

**Comment by Dudleyneedham** [comment]
Thank you 👍
