### ISSUE TITLE
How can you get the referenced transaction of and event?

### ISSUE THREAD

**Issue by dillu24** [polkadot-js/api#2665]
Is there a way of getting the reference transaction of an event from an event itself? Or the only way is from the block?

**Comment by jacogr** [comment]
The indexes in the event refers to the transaction index in the block. More than that we don't have. So you need to know which blockHash it was applied for and then map the indexes between the two.

**Comment by dillu24** [comment]
ah ok, and how can you get the transactions of a block?

**Comment by jacogr** [comment]
https://polkadot.js.org/api/cookbook/blocks.html#how-do-i-view-block-extrinsic-information

**Comment by dillu24** [comment]
Ok, from what I am seeing (unless I am missing something) is that you can see the transaction information, but there is no Tx hash, how can you get that?

**Comment by dillu24** [comment]
> 
> 
> The indexes in the event refers to the transaction index in the block. More than that we don't have. So you need to know which blockHash it was applied for and then map the indexes between the two.

Sorry for opening again but I am confused with this. I want to traverse the events trigered by a particular transaction. Now for example let us consider this block: https://polkascan.io/kusama/block/14836#transactions 

If we click on the first transaction we see that the transaction index is 3, and for the other transaction the transaction index is 4. Now if I go through the list of events for block 14836 I see that the indices in the block are as follows:

![image](https://user-images.githubusercontent.com/23262259/94775369-f93b9300-03bf-11eb-9742-c53f02df0a48.png)

Converting to dec these are both 3333, am I doing something wrong?

**Comment by jacogr** [comment]
Each record of the `system.events` has a `phase` member. It is an enum, so when that enum is `isApplyExtrinsic` it means it links to an extrinsic. Expanding this has the index of the tx in the block.

Something like this -

```js
events.forEach(({ phase }) => {
  if (phase.isApplyExtrinsic) {
    console.log('tx index is', phase.asApplyExtrinsic.toNumber());
  }
});
```

**Comment by dillu24** [comment]
Got it, thanks jaco!
