### ISSUE TITLE
about the txid!

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2667]
After executing the substrate private chain, if i connect to the polkadotjs app explorer, the websocket connection is successful.

And when basic balance transfer is performed, it is possible to check that the balance is transferred to alice -> bob, but the txid is not actually displayed on the explorer. Also, txid-related information is not visible on the substrate private chain log. What is the problem?

**Comment by jacogr** [comment]
No idea. What do you mean txid is not displayed in the explorer? Which explorer?

**Comment by puffanddmx** [comment]
https://polkadot.js.org/apps/#/explorer
- txid : transaction hash
-> if i transfer balance alice to bob, there is transaction hash for it. but i cannot find it.

**Comment by jacogr** [comment]
The apps UI doesn't actually show any transaction hashes, only allows queries on block hashes and then expands the extrinsics in that block. (Transaction hashes are non-unique and therefore not indexed by Substrate at all)

**Comment by puffanddmx** [comment]
Then, it means that there is no way to see the transaction that I signed in here? What if we don't implement another method?

**Comment by jacogr** [comment]
There are no RPCs from Substrate to query by transaction hash. As mentioned, it is not indexed by Substrate since it is not unique.

**Comment by puffanddmx** [comment]
thank you!
