### ISSUE TITLE
error

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2669]
-question1 -
polkadot explorer url : https://polkadot.js.org/apps/#/explorer

If i click on block 2 in polkadot explorer, i can see the information, but it seems that the following error appears from the 3rd block. What is the solution to the error below?

error -> Unable to retrieve the specified block details. createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x5443/[84,67]

-question 2- 
url : https://polkadot.js.org/api/examples/promise/05_read_storage

When viewed from the url, it appears as if it supports api.query.system.account. But in reality there is no account function, is there a replacement function? What can I look at to see the balance information of the account? (use query balance?)

error -> api.query.system.account is not a function

**Comment by jacogr** [comment]
The issue in 1 happens when the decoding of the binary data goes wrong. Ensure that your types matches 100% with the Rust definitions and add them appropriately to the apps UI. some reading as to why the API needs them is found here https://polkadot.js.org/api/start/types.extend.html (In this case it is certainly due to a wrongly specified type that occurs in an event)

For 2 read this FAQ entry https://polkadot.js.org/api/start/FAQ.html#my-chain-does-not-support-system-account-queries

**Comment by puffanddmx** [comment]
Thanks @jacogr 
Q1. How to upgrade?
-> only upgrade the library which is related to the weight?

Q2. How can i query all accounts in my chain in a one shot? (Api)

**Comment by jacogr** [comment]
You need to add the specific types, for your chain.

See https://polkadot.js.org/api/start/api.query.other.html#map-keys-entries - I would suggest reading the guide linked, it has all these answers.

**Comment by puffanddmx** [comment]
thanks!

i got the below error on https://polkadot.js.org/apps/#/accounts.
all of accounts info are not shown. (alice, bob....)

- error-
One of more extensions has been detected in your browser, however no accounts has been injected.
Ensure that the extension has accounts, some accounts are visible globally and available for this chain and that you gave the application permission to access accounts from the extension to use them.

**Comment by jacogr** [comment]
Please do log the apps/extension specific issues on the relevant repos. 

JS o lay allows integers to Number.MAX_INTEGER, which is 2^53 - 1. to pass larger numbers-

- pass it as a String 
- pass it as a JS BigInt
- pass it as a BN

(Both the last 2 would need a string/hex anyway, so you can go for the first)

**Comment by puffanddmx** [comment]
@jacogr
Currently, i are testing a private chain using aura/granpa. 
However, the author information is not available. 
Am I doing the wrong setting?

const header = await api.rpc.chain.getHeader();
console.log(` ${header.author}`); -> undefined

<header info
Type [Map] {
  'parentHash' => Type [Uint8Array] [
    128,
    228,
    123,
    219,
    70,
    106,
    29,
    0,
    40,
    235,
    167,
    118,
    109,
    21,
    10,
    220,
    84,
    144,
    76,
    149,
    62,
    136,
    223,
    140,
    139,
    175,
    128,
    166,
    135,
    161,
    141,
    222,
    registry: TypeRegistry {} ],
  'number' => Compact { registry: TypeRegistry {} },
  'stateRoot' => Type [Uint8Array] [
    252,
    235,
    249,
    66,
    161,
    231,
    219,
    198,
    86,
    244,
    174,
    11,
    118,
    251,
    242,
    253,
    3,
    234,
    170,
    162,
    2,
    85,
    113,
    189,
    218,
    86,
    235,
    128,
    156,
    89,
    146,
    212,
    registry: TypeRegistry {} ],
  'extrinsicsRoot' => Type [Uint8Array] [
    20,
    128,
    247,
    14,
    141,
    76,
    167,
    214,
    48,
    63,
    232,
    107,
    240,
    210,
    86,
    67,
    73,
    119,
    52,
    42,
    20,
    81,
    89,
    173,
    42,
    161,
    121,
    212,
    114,
    50,
    130,
    220,
    registry: TypeRegistry {} ],
  'digest' => Type [Map] {
    'logs' => Vec [
      [Type],
      [Type],
      registry: TypeRegistry {},
      _Type: [Function: Type] ],
    registry: TypeRegistry {},
    logs: [Getter] },
  registry: TypeRegistry {},
  parentHash: [Getter],
  number: [Getter],
  stateRoot: [Getter],
  extrinsicsRoot: [Getter],
  digest: [Getter] }

**Comment by jacogr** [comment]
There is no `author` in `chain.getHeader()`

**Comment by puffanddmx** [comment]
In some testnets, blockauthor information appears as an icon in the explorer below. 
What did it add to the type? 
If you see the recent block tab on below explorer, you can see the author information in the picture.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer

**Comment by jacogr** [comment]
I really would suggest reading the documentation - it is not fully complete and needs a lot of work, however this information is in there with a derive helper.

**Comment by puffanddmx** [comment]
ok good!
