### ISSUE TITLE
How create an ExtrinsicPayload and sign it on another machine.

### ISSUE THREAD

**Issue by robin-crypto-com** [polkadot-js/api#2680]
Hello,

1. basically I just want to create the `ExtrinsicPayload` on `machine A` connected to my node
2. then send it over the network (http) to `machine B` which has access to my keys for signing
3. then pass again the signature to `machine A` for sending the transaction.

I tried to pass the `signerPayload.toPayload()` from A to B it works fine as it is JSON.
But I'm missing the api.registry to `createType(registry, "ExtrinsicPayload", payload, { version: payload.version }).sign(keys);`.
I tried to play with Codec to encode on A and decode on B, but same problem, I'm missing the api.registry .

Any suggestions ?

**Comment by jacogr** [comment]
Take a look at https://github.com/polkadot-js/tools/tree/master/packages/signer-cli

**Comment by robin-crypto-com** [comment]
Ok so to be clear using this cli my `machine B` doesn't need to be connected to my node ?
Also one last question, after signing I see it generates a mortal extrinsic. Any way to make it immortal ?

**Comment by jacogr** [comment]
Yes. So machine A has a connection, machine B just needs a way to get access to the hex payload, it never connects to sign.

Mortals are always recommended. However, if you wish to forgo protection it provides, you can (in the above tools) pass `--blocks 0` and it will create an immortal on construction.

**Comment by robin-crypto-com** [comment]
Great thank you so much ! 🙏
