### ISSUE TITLE
metadata.toJSON does not respect typesAlias

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/api#2687]
Hi, I'm using the latest version of the polkadotjs. I found a problem that  the typeAlias does not work when I use `metadata.toJSON()`. But the interesting thing is that if I use `metadata.aslate.toJSON()`, the type can be overwritten normally.  I want to know whether this is a bug or a feature.
The data I use is the https://github.com/polkadot-js/api/blob/master/packages/metadata/src/Metadata/v12/static.ts
It  works at 1.30.1 and V11

**Comment by jacogr** [comment]
Only on `asLatest` does it actually applies the type overrides. In 1.30.1 this was also the case, although v11 was the latest - 

- https://github.com/polkadot-js/api/blob/v1.30.1/packages/metadata/src/Metadata/v11/toLatest.ts

vs 

- https://github.com/polkadot-js/api/blob/v2.1.1/packages/metadata/src/Metadata/v12/toLatest.ts

So it was intended, but not sure why it appears to apply in the 1.30.1 version. This could be since in 1.30.1 we actually polluted the registry quite a bit, so while not intended it did work.

Atm not sure how to make it apply there, but it seems useful to have.

**Comment by aniiantt** [comment]
But this also seems to cause the following code to fail to generate the type files correctly.
```javascript
import generateConst from '@polkadot/typegen/generate/consts';
import generateQuery from '@polkadot/typegen/generate/query';
import generateTx from '@polkadot/typegen/generate/tx';

const registry = new TypeRegistry();

// override types
registry.setKnownTypes({
  typesAlias: {
    xxxx: {
      Foo: 'Bar'
    }
  },
});

const metadata = new Metadata(registry, '0x......');

const metadataStatic = metadata.toHex()

generateConst('......', metadataStatic, definations)
generateTx('......', metadataStatic, definations);
generateQuery('......', metadataStatic, definations);
```
Now I can't override the types like this. I wonder if there is any way to solve this problem.

**Comment by jacogr** [comment]
Bugs are always features. :) Will see what can be done based on your sample.

**Comment by aniiantt** [comment]
Sorry, my example missed a few lines of code. It should look something like this:
```javascript
import generateConst from '@polkadot/typegen/generate/consts';
import generateQuery from '@polkadot/typegen/generate/query';
import generateTx from '@polkadot/typegen/generate/tx';
const registry = new TypeRegistry();

// override types
registry.setKnownTypes({
  typesAlias: {
    xxxx: {
      Foo: 'Bar'
    }
  },
});

const metadata = new Metadata(registry, '0x......');

const newMetadata = new Metadata(registry, metadata.toJSON())

const metadataStatic = newMetadata.toHex()

generateConst('......', metadataStatic, definations)
generateTx('......', metadataStatic, definations);
generateQuery('......', metadataStatic, definations);
```

**Comment by jacogr** [comment]
In the above, as a work-around for now, this should do the trick while  solution is pending.

```js
const metadata = new Metadata(registry, '0x......');

// HACK to populate registry
metadata.asLatest.toJSON();

const newMetadata = new Metadata(registry, metadata.toJSON())
```

The additional asLatest (while the output is not used), will enhance the registry so subsequent uses will have the added types.
