### ISSUE TITLE
PalletsOrigin / OriginCaller & Scheduled type updated

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2691]
With https://github.com/paritytech/substrate/pull/6387, it is now possible to store and expose `PalletsOrigin` type. It is generated by `construct_runtime` macro similar to `Call` type so polkadot.js needs some customized code to generate it.

Also just found out `Scheduled` type definition is not updated (or did I missed something?).

This means polkadot.js won't be able to decode `Agenda` correctly.

https://github.com/paritytech/substrate/blob/81f3e7caf351c27aab518ee3b640c06b1a4392bf/frame/scheduler/src/lib.rs#L161-L162

https://github.com/paritytech/substrate/blob/81f3e7caf351c27aab518ee3b640c06b1a4392bf/frame/scheduler/src/lib.rs#L126-L136

https://github.com/polkadot-js/api/blob/2faf68c4d2ddb1fef710f5ebf5ef8ce2088b923c/packages/types/src/interfaces/scheduler/definitions.ts#L16-L21

**Comment by jacogr** [comment]
Sadly I do lose track of some PRs along the way in the cases where help is not requested, there are a lot that goes in. 

So what was missing above was a `cc @jacogr` in the PR, but it tracked now.
