### ISSUE TITLE
Determine tx fee in advance

### ISSUE THREAD

**Issue by roccomuso** [polkadot-js/api#2697]
Is there a way to determine extrinsic fees in advance? I found this link (but it's dead): https://polkadot.js.org/api/cookbook/tx.html#how-do-i-estimate-the-transaction-fees

Any rpc that could be helpful for this?

**Comment by jacogr** [comment]
Docs have moved, everything is now under the docs repo, https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-estimate-the-transaction-fees

**Comment by roccomuso** [comment]
what kind of rpc does it use under the hood? is there any computation done client-side?

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/substrate/rpc#queryinfoextrinsic-bytes-at-blockhash-runtimedispatchinfo

**Comment by jacogr** [comment]
Closing.
