### ISSUE TITLE
Branched out a branch based on polkadot/api to facilitate me to adjust the interface of our chain, how to deploy to npm?

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/api#2709]

**Comment by jacogr** [comment]
https://docs.npmjs.com/creating-and-publishing-scoped-public-packages

**Comment by yuhui1208** [comment]
Do I need to manually execute the build script and compile it into a js file and copy the corresponding package.json to the corresponding folder?

**Comment by jacogr** [comment]
A normal `yarn build` will compile the packages into the `package/<name>/build` folders. This contains everything that can de deployed.

**Comment by yuhui1208** [comment]
Okay, thank you very much for your patient help

**Comment by jacogr** [comment]
Closing.
