### ISSUE TITLE
Remove EnumType, use only Enum

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#271]
Make Enum class as close as possible to Rust enum.

**Example 1:**
If Rust = 
```rust
| Something(123)
| Empty
```
then JS =
```javascript
new Enum({ Something: UInt, Empty: Null}, { Some: 123 }); 
```

**Example 2:** a Rust Option in JS is simply a:
```javascript
class Option extends Enum {
  constructor(Type, value) {
    super({ None: Null, Some: Type }, value)
  }
}
```
and U8a codec will be magically resolved: `[0]` for `None` and `[1, ...]` for `Some(...)`

**Example 3:** A simple Enum (i.e. without values)
Unfortunately we won't use TS enums at all (anyway they don't allow values), but a SimpleEnum is just an Enum using Null everywhere
```javascript
class SimpleEnum extends Enum {
  constructor(Type, value) {
    super({ VALUEA: Null, VALUEB: Null }, value)
  }
}
```

**Example 4:** MisbehaviorKind
```javascript
class MisbehaviorKind extends Enum {
  constructor(Type, value) {
    super({ 0x11: BftDoublePrepare, 0x12: BftDoubleCommit }, value)
  }
}
```
Just have a convention that instead of key strings, we can pass key numbers, and in this case the encoding is `[0x11, ...]` for BftDoublePrepare, and `[0x12, ...]` for BftDoubleCommit (i.e. 1st byte is not index position, but index value).

**Comment by jacogr** [comment]
I suggest sticking to EnumType since it gets the most love. We can do -

- allow Array<string> as input
- as found, do { [name: string]: Null } (as suggested)
- delete Enum, rename EnumType -> Enum
