### ISSUE TITLE
not activation for erc.wasm[ink build)

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2721]
After building erc20 using ink, ink wasm was deployed on the network. After that, I try to deploy with initial information (name, symbol) using a constructor, so the deploy button cannot be activated. Changing any other value will not activate it.
if i do 1->2 below, deploy button for 2 is not activated.
 
1. https://polkadot.js.org/apps/#/contracts-
code hashes 

ERC721 | Constructors (1)
deploy new (name: str, symbol: str)  -> deploy  button click 

2. add an existing code hash
-> if i put below info, deploy button is not activated

deployment constructor
new (name: str, symbol: str)

name: str
0x

symbol: str
0x

endowment
0

maximum gas allowed
1000000
1.000s execution time
20% of block time

**Comment by jacogr** [comment]
Can you link to the code (preferably WASM & ABI, it has been tested with the erc20 version (compiled) found here - https://github.com/polkadot-js/api/tree/master/packages/api-contract/test/contracts

**Comment by puffanddmx** [comment]
thanks for the sharing.

i test the erc721 for executing mint function id 0.
then i got the below error, which is not callable function.

Oct 14 13:05:55.009 DEBUG apply_extrinsic: DispatchError    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: 11    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: 12    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: NotCallable    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: PostInfo:     {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: actual_weight=    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: 67500000    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: pays_fee=    {ext}
Oct 14 13:05:55.009 DEBUG apply_extrinsic: Yes    {ext}

**Comment by jacogr** [comment]
Let me preface this to say I'm not familiar with the ink! internals to know why that would happen.

However, ran a test now using the erc271 contracts against a canvas-node (which seems like the simple version to test these on a contract-only chain) and could mint without any issues. Will try against Substrate master as well (which is my general go-to testing tool)

**Comment by puffanddmx** [comment]
thanks! jacogr
