### ISSUE TITLE
The requested module '@polkadot/api' does not provide an export named 'ApiPromise'

### ISSUE THREAD

**Issue by SarahKay99** [polkadot-js/api#2727]
Hi everyone,

I ran this code on my PC, 

```
import { ApiPromise } from '@polkadot/api';

async function createApi() {
    const api = await ApiPromise.create();
    return api;
}

const api = createApi()

```
As instructed by your docs, and I got this error in the first line:

**_The requested module '@polkadot/api' does not provide an export named 'ApiPromise'_**

Am I doing something wrong, or is there a bug?

**Comment by jacogr** [comment]
It is exported, see here - https://github.com/polkadot-js/api/blob/master/packages/api/src/index.ts#L13

(And it def used that way in projects that i know of, see e.g. https://github.com/w3f/faucet-bot/blob/master/src/server/actions.js#L1

So not sure why it would fail in your case. (You can also do `import ApiPromise from '@polkadot/api/promise';` as a direct import, but while that may mask the above should just work)

**Comment by jacogr** [comment]
Is it in a node.js environment or a browser environment? (For the former would swap to require since only cjs modules are exported)

**Comment by SarahKay99** [comment]
I'm running it in a node.js environment. I switched to require and used the string `'@polkadot/api/promise';`. It worked... but I have a different issue now, which is also an issue with the code in your documentation.

```
const { ApiPromise } = require('@polkadot/api/promise');

async function createApi() {
    var api = await ApiPromise.create();
    return api;
}

const api = createApi();

api.rpc.chain.subscribeNewHeads((header) => {
    console.log(`Chain is at #${header.number}`);
});
```

**ERROR:** 
```
api.rpc.chain.subscribeNewHeads((header) => {
                ^
TypeError: Cannot read property 'chain' of undefined`
``

**Comment by SarahKay99** [comment]
It should be noted that when I run 

```
const { ApiPromise } = require('@polkadot/api/promise');

const api = await ApiPromise.create();

api.rpc.chain.subscribeNewHeads((header) => {
    console.log(`Chain is at #${header.number}`);
});
```

I get the error: 

```
await is only valid in async function
```

**Comment by jacogr** [comment]
Your issue is here `const api = createApi();` should be `const api = await createApi()`

As for the docs, it is mentioned at the start (or at least used to be) that is uses top-level await. It is sample code so takes a lot of shortcuts to only show the core functionality. (top-level await is not supported consistently in all environments yet)

**Comment by SarahKay99** [comment]
I tried `const api = await createApi()`, still gives me `SyntaxError: await is only valid in async function`

**Comment by SarahKay99** [comment]
Should I make a new issue for this?

**Comment by jacogr** [comment]
Sure if it is unclear in the docs, can clarify further there - https://github.com/polkadot-js/docs/issues (the code certainly won't be changed, but but if it is a hurdle and should be clarified even, can be done in a paragraph)

**Comment by SarahKay99** [comment]
Thank you for your help @jacogr . The new issue is here:https://github.com/polkadot-js/api/issues/2732. I will keep this issue open in case ApiPromise continues to be the problem for me.
