### ISSUE TITLE
Unable to Interact with contract

### ISSUE THREAD

**Issue by MayankVats** [polkadot-js/api#2731]
_The contract I deployed is the Flipper contract on Beresheet(Edgeware's testnet) below is the code and the output for interacting with the contract using polkadot-js API_
# CODE:
```
const { ApiPromise, WsProvider, Keyring } = require('@polkadot/api');
const { CodePromise, ContractPromise } = require('@polkadot/api-contract');
const { cryptoWaitReady } = require('@polkadot/util-crypto');
const abi = require('./metadata.json');

async function getApi() {
    const wsProvider = new WsProvider('wss://beresheet2.edgewa.re');
    const api = new ApiPromise({ provider: wsProvider });
    await api.isReady;
    return api;
}

async function Contract() {
    const api = await getApi()
    const contract = new ContractPromise(api, abi, '5FYgGr2PJHFAqLAFEkQRCRZdJcA5WoeXF7UrdcFEv1rtFycg');
    return contract;
}

async function readContract() {
    const value = 0;
    const gasLimit = '100000000000';

    const contract = await Contract();
    const result = contract
    .read('get', value, gasLimit)
    .send('kCGrwUPxoyK4XMRWeXhKd9QccR5wdAYbGpoC9suuTx3zJyG');
    
    return result;
}
readContract().then((value) => {
    console.log(value);
    console.log(value.result);
    console.log("isSuccess", value.result.isSuccess);
    console.log("isError", value.result.isError);
    console.log("asError", value.result.asError);
}).catch(err => console.error(err));

```
# OUTPUT:
```
Type {
    registry: TypeRegistry {},
    isSuccess: [Getter],
    asSuccess: [Getter],
    isError: [Getter],
    asError: [Getter]
}
isSuccess: false
isError: true
asError: Null { registry: TypeRegistry {} }
```

**Comment by jacogr** [comment]
Does it work via the UI? (I just want to rule out code issues)

Now tht you mentioned Edgeware, not sure if there are differences (should not be) between the version running there and Substrate 2.0 (which is recommended for ink! 3.0-rc1)

**Comment by MayankVats** [comment]
> Does it work via the UI? (I just want to rule out code issues)
> 
> Now tht you mentioned Edgeware, not sure if there are differences (should not be) between the version running there and Substrate 2.0 (which is recommended for ink! 3.0-rc1)

![image](https://user-images.githubusercontent.com/30179337/96116936-e5874500-0f06-11eb-8926-035bc6ff82f4.png)
yes It does work with the UI

**Comment by svrapidinnovation** [comment]
Yes, I am also facing same issue.

**Comment by jacogr** [comment]
The get in the screenshot above also fails. (And there it has as much gas as available in a block). The reason I know it fails is that it will show that actual value (for the reads without the params) when it can actually retrieve a value.

As to why those contracts fails on Beresheet (but works on Substrate master & canvas-node, I don't know), but it is not actually API related. So the results you get from the code above ties up with what we are seeing in the screenshot above.

(Will add an "expected" as soon as my node is built)

**Comment by jacogr** [comment]
This is generally expected when the calls do match, the values for the param-less getters always sho the current results automatically -

![image](https://user-images.githubusercontent.com/1424473/96118846-65ec7c80-0eec-11eb-87ba-0ba5e7939fdf.png)

**Comment by shubh151994** [comment]
@jacogr mine get function is showing values automatically but still when trying to connect using @polkadot/api getting issue
![image](https://user-images.githubusercontent.com/30794490/96121914-5847ee80-0f0e-11eb-8566-5592cbf91d83.png)

**Comment by jacogr** [comment]
So the UI uses the exact same calls as in the API and document. So if it does work UI-wise (so contract executes), just ensure you on a non-mutate call (like get)

- don't pass a value (should be 0, it will error when specified)
- ensure the gasLimit aligns with what works in the UI (I don't understand why there is a gasLimit on call, but that is the paletted interface - you can always check it by exec on inc, swap to get, make the call and ensure it succeeds)

**Comment by svrapidinnovation** [comment]
I deployed a flipper contract and interacted with polkadot ui , It's working fine.But when I am interacting contract with Polkadot api , It is giving error.

I have used below code : 

const { ApiPromise, WsProvider, Keyring } = require('@polkadot/api');
const { CodePromise, ContractPromise } = require('@polkadot/api-contract');
const { cryptoWaitReady } = require('@polkadot/util-crypto');
const abi = require('./metadata.json');

const keyring = new Keyring({ type: 'sr25519' });


// FUNCTION TO CONSTRUCT THE PROVIDER
async function getApi() {
    const wsProvider = new WsProvider('wss://beresheet2.edgewa.re');
    const api = new ApiPromise({ provider: wsProvider });
    await api.isReady;
    return api;
}

async function Contract() {
    const api = await getApi();
 
   const contract = new ContractPromise(api, abi, '5CgivzHf97og2wjuYbLecTFgEJxkF7WCNbmxboUGpCo5fCVL');
 return contract;
 
}

async function readContract() {
    const value = 0;
    const gasLimit = '1000000';
    await cryptoWaitReady();

    const mnemonic = "";
    const newPair = keyring.addFromUri(mnemonic);

    const contract = await Contract();
    const result = await contract
    .exec('flip',  gasLimit,value)
    .signAndSend(newPair,(result) => {
         if(result.status.isInBlock){          
              console.log('in a block');
           }else if (result.status.isFinalized) {
                   console.log(`Transaction included at blockHash ${result.status.asFinalized}`);
    
          // Loop through Vec<EventRecord> to display all events
           result.events.forEach(({ phase, event: { data, method, section } }) => {
            console.log( `${phase}: ${section}.${method}:: ${data}`);
          });
            }
          });
      
    
        
    return result;
}
readContract().then(value => console.log(value.output.toHuman())).catch(err => console.error(err));


I am getting this error: 

Transaction included at blockHash 0xea197705122110ffeb62b0697542a584a96a99414467c22083dcde4ead44e49f
{"ApplyExtrinsic":2}: treasury.Deposit:: ["0x0000000000000000002aa1efbf43e100"]
{"ApplyExtrinsic":2}: system.ExtrinsicFailed:: [{"Module":{"index":16,"error":6}},{"weight":0,"class":"Normal","paysFee":"Yes"}]

**Comment by jacogr** [comment]
@svrapidinnovation Refer to https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event

**Comment by svrapidinnovation** [comment]
Thanks @jacogr  I'll check it.

**Comment by MayankVats** [comment]
Thanks @jacogr the issue is resolved I interacted with the contract using API successfully. I guess Beresheet is not stable yet.

![image](https://user-images.githubusercontent.com/30179337/96212697-11e9a280-0f95-11eb-9a76-2fd36756abb0.png)

**Comment by yangwao** [comment]
Hello, @MayankVats @svrapidinnovation everything should work through UI on Beresheet. 
Visit our Edgeware Developers channel and we can chat more to get you positive experience! 

On Beresheet it works for me! 
![image](https://user-images.githubusercontent.com/5887929/96280450-4468bf00-0fd8-11eb-83b3-307fab621591.png)
