### ISSUE TITLE
WebSocket connection to 'ws://127.0.0.1:9944/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED Provider.js:380

### ISSUE THREAD

**Issue by SarahKay99** [polkadot-js/api#2733]
In the substrate-front-end-template folder, I cmd'd `yarn add @polkadot/api`

----

CHROME

The node runs in one tab of my browser, but a new tab with the same URL comes up which gives me the error: 

```
Error Connecting to Substrate
Error: FATAL: Unable to initialize the API: createType(StorageKey):: Derived TypedArray constructor created an array which was too small
```

In the console:

```
WebSocket connection to 'ws://127.0.0.1:9944/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Provider.js:380
```

----

FIREFOX

I got only one tab, with a different error written: 

```
Error Connecting to Substrate

Error: FATAL: Unable to initialize the API: createType(StorageKey):: expected TypedArray of at least length 4, but constructor returned TypedArray of length 0
```

Console:

```
API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageKey):: expected TypedArray of at least length 4, but constructor returned TypedArray of length 0
Init.js:85
```

----

I read your closed thread about this error, and I assume it's not an easy one to trace, so hopefully my excessive information can help you.

**Comment by SarahKay99** [comment]
I don't know how to check. It's a basic Substrate node (no edits to the Rust code) taken directly from this tutorial https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact#runtime-metadata

**Comment by jacogr** [comment]
And the node code? (The reason for asking since there is quite large differences pre-2.0 and 2.0)

**Comment by SarahKay99** [comment]
In the cargo.toml file for 'substrate-node-template/node' , it says version 2.0.0. Also 2.0.0 for the runtime.

**Comment by SarahKay99** [comment]
Should I fix this by manually changing the versions in package.json? If so, what versions should I change to.

**Comment by jacogr** [comment]
Yes, you can manually fix it - I would alway recommend the latest stable version in the case 2.2.1 - https://github.com/polkadot-js/api/releases

Just ensure you change both the `@polkadot/api` & `@polkadot/types` lines (they always go hand-in-hand). After that, do a `yarn` and it should be ok.

**Comment by SarahKay99** [comment]
yarn what?

**Comment by jacogr** [comment]
Just `yarn` which will install the changes in the package.json

**Comment by SarahKay99** [comment]
![hello world hackathon entry](https://user-images.githubusercontent.com/51705696/96159753-c1f0e880-0f60-11eb-90c6-884759ae845d.PNG)

**Comment by jacogr** [comment]
Closing.
