### ISSUE TITLE
Runtime upgrade won't register custom types

### ISSUE THREAD

**Issue by zikunfan** [polkadot-js/api#2737]
When runtime upgraded, `ApiPromise` will check the wasm code changed with log:
```shell
2020-10-16 14:31:30        API/INIT: Runtime version updated to spec=2, tx=1
2020-10-16 14:31:30     API/AUGMENT: api.tx: Found 1 added modules:
	  added: candy
2020-10-16 14:31:30     API/AUGMENT: api.query: Found 1 added modules:
	  added: candy
```
But the customer types won't registered, this might be a bug when reload `ApiPromise`?

**Comment by jacogr** [comment]
This is how all registries are populated - https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L74-L85

This is where the upgrade populates - https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L200-L221

There are no type registration logs, the logs being output is for the metadata changes.
