### ISSUE TITLE
Understanding Address and LookupSource

### ISSUE THREAD

**Issue by h4x3rotab** [polkadot-js/api#2745]
> 1002: Verification Error: Execution: Could not convert parameter tx between node and runtime: No such variant in enum MultiSignature: RuntimeApi, Execution: Could not convert parameter tx between node and runtime: No such variant in enum MultiSignature

Got the above error when sending transaction from Polkadot.js-apps if I specify `Address: AccountId` and `LookupSource: AccountId` in `Settings > Developer` tab. I read the doc [here](https://polkadot.js.org/docs/api/FAQ#the-node-returns-a-could-not-convert-error-on-send), but still found it hard to understand.

I have the following questsion:

1. What are the possible values of "Address" and "LookupSource"?
2. My types in the runtime are as below, what is the correct value of "Address" and "LookupSource" in the developer tab?

```rust
pub type AccountId = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;
pub type Address = <Indices as StaticLookup>::Source;
```

**Comment by jacogr** [comment]
In the above, don't add overrides. It matches with the Substrate defaults.

**Comment by h4x3rotab** [comment]
Thanks. It turned out we the latest client is incompatible with Rococo v0. When we switched back to v0.57.1 everything worked well. But anyway, it's good to know the default values (GenericAddress and GenericLookupSource).
