### ISSUE TITLE
Error at height `2017533 `

### ISSUE THREAD

**Issue by silentlight** [polkadot-js/api#2748]
Hi,
I am getting an error `Error: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 3, in Staked, Stash, Controller` when I try to get block at height 2017533. I get this error using polkadot-js 2.2.1 and also 2.3.1.
Any idea what is wrong?

**Comment by jacogr** [comment]
Which chain?

This sound like the RewardDestination type that has been applied too late, i.e. newer versions of the runtime has 4 entries, older 3.

**Comment by silentlight** [comment]
This is for Polkadot. Do you think there is something we do wrong in the code?

**Comment by jacogr** [comment]
Ok, so the apps UI displays it correctly. As long as you don't try to manage registries and types yourself, and have a recent API, you will be fine. The types are correct and it is in the current range as well. The only way it can go wrong is is some registry types are injected and clobber the defaults.

**Comment by silentlight** [comment]
Is it maybe because we inject metadata and type per height and we do the same for previous height to make sure that certain queries work?

**Comment by jacogr** [comment]
That would be problematic, yes. In doing so you clobber the current specVersion registry. (And the new type, since it is default, is not explicitly specified)

The API handles `.at` queries transparently since 1.34

**Comment by jacogr** [comment]
I'm closing this, I'm assuming it has been resolved.
