### ISSUE TITLE
Generate argument-api-consts failed from metadata

### ISSUE THREAD

**Issue by qwer951123** [polkadot-js/api#2750]
Hi, When I had used the **@polkadot/typegen/generate/const** to generate **argument-api-consts.ts** file.

Their is an error like this:

<img width="694" alt="截屏2020-10-20 下午2 09 24" src="https://user-images.githubusercontent.com/4833280/96546967-de34b280-12dd-11eb-8e97-2132edf22412.png">

The type in the chain is **(u32, u32)**, so maybe it should be **ITuple<[u32, u32]>**?

**Comment by jacogr** [comment]
Strange we have not had a Tuple constant yet. Needs a fix, at this point consts handles everything as primitives.
