### ISSUE TITLE
Error: Invalid JSON ABI structure supplied, expected a recent metadata version

### ISSUE THREAD

**Issue by oznfc** [polkadot-js/api#2751]
When I use  the  api.tx.contracts.call ,  ı'm using "abi".  I have this error . :  "Error: Invalid JSON ABI structure supplied, expected a recent metadata version".
I'm already using to new ink3.0!

**Comment by jacogr** [comment]
Can you please supply the ABI?

**Comment by jacogr** [comment]
Closing. Since the ABI is not provided for replication, there is nothing that can be done here it is a guess. Based on the tests from solang and ink!, the metadata aligns.
