### ISSUE TITLE
API-WS: disconnected from ws://rpc.polkadot.io: 1006:: connection failed

### ISSUE THREAD

**Issue by schadokar** [polkadot-js/api#2755]
I am trying to connect to the public node using the @polkadot/api npm module.  
```
Version: "@polkadot/api": "^2.3.1"
```
Node Version: v12.16.2

This is my code
```
// Import
const { ApiPromise, WsProvider } = require('@polkadot/api');

const wsProvider = new WsProvider('ws://rpc.polkadot.io');

const main = async () => {
    const api = await ApiPromise.create({ provider: wsProvider });
    await api.isReady;
    // Do something
    console.log(api.genesisHash.toHex());
};

main();
```

Due to this error I am unable to use the substrate-api-sidecar docker image.  

Thanks.

**EDIT**
The error is same for both urls `ws://rpc.polkadot.io` and `wss://rpc.polkadot.io`.

**Comment by jacogr** [comment]
Sadly the error 1006 doesn't provide any information. However, in this case your endpoint is wrong -

`ws://rpc.polkadot.io` should be `wss://rpc.polkadot.io`

**Comment by schadokar** [comment]
I tried both the urls and result is same. Previously it used to work but after this change `ws://` to `wss://` I am facing this issue. Can you please run the script on your machine and confirm if it is connecting? Then I can check in my network side.

**Comment by jacogr** [comment]
There are no issues with the endpoint, local scripts work for me. Not running your script, but my testing today included the following -

```js
const { ApiPromise, WsProvider } = require('@polkadot/api');

async function test1 () {
  const api = await ApiPromise.create({ provider: new WsProvider('wss://rpc.polkadot.io') });
  let blockNumber = 1;

  while (true) {
    const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
    const signed = await api.rpc.chain.getBlock(blockHash);
    const events = await api.query.system.events.at(blockHash);

    console.log('****', blockNumber);

    events.forEach((record) => {
      // Extract the phase, event and the event types
      const { event, phase } = record;

      // Show what we are busy with
      console.log(`\t${event.section}:${event.method}:: (phase=${phase.toString()})`);
    });

    blockNumber++;
  }
}

test1().catch(() => process.exit(1));
```

**Comment by schadokar** [comment]
Thank you. I think it was some network issue. Now, it is working.
