### ISSUE TITLE
Unable to resolve type , it will fail on construction

### ISSUE THREAD

**Issue by herryho** [polkadot-js/api#2756]
When I used "yarn generate:defs" command  to generate customized types, I encountered the following warnings.

<img width="916" alt="E9A7CCB0-583B-4C28-89C9-C44C1E6E1FA0" src="https://user-images.githubusercontent.com/45537372/96798068-a4c18b80-1432-11eb-90c5-ada6dc68801b.png">

The typegen version is 2.0.1. However, there was nothing shown when I usded typegen version of 1.35.0-beta.5 and downwards.

<img width="927" alt="2CEAC80A-696A-4B25-9D58-157F442FA721" src="https://user-images.githubusercontent.com/45537372/96798169-e0f4ec00-1432-11eb-8c0a-912d44bb37be.png">

What could be the problem? I originally thought it was our project's problem. But when I tried to use the edgeware example from https://github.com/hicommonwealth/edgeware-node-types.git. The same issue appeared. Actually the picture's shown above are from the edgeware example type generation process.

**Comment by jacogr** [comment]
In the case of Edgeware, the actual way it it exported has changed in the packages. The example needs an update as applied elsewhere, ie.g. apps UI. will run it through with the update and see what it does.

**Comment by jacogr** [comment]
Ok, can confirm. The message it displays is new, will see what needs to be done. (It is innocent since we are not constructing, only generating, but at the same time should not be there at all - it will drown out real need-to-action concerns).
