### ISSUE TITLE
Typegen does not support tuple type on transaction api

### ISSUE THREAD

**Issue by herryho** [polkadot-js/api#2757]
I saw the newest typegen version 2.3.2-2 alreday supports tuple constants, but tx api still do not support tuple. 
![735EF276-990D-48DF-8D98-BE5D027F78C0](https://user-images.githubusercontent.com/45537372/96825392-9475d480-1463-11eb-9ee5-bf31fdcd7892.png)

**Comment by jacogr** [comment]
The generation is not comprehensive, it only supports what is in Substrate master. (At some point should have a manually-generated metadata list with all combos, but until then it is really based on demand.)

Will take a look at the above, it seems sensible to add.

**Comment by herryho** [comment]
Thanks! So if I mannually revise the file, shall I embrace the tuple with quare brackets, like [TxOut, u64]?

**Comment by herryho** [comment]
![image](https://user-images.githubusercontent.com/45537372/97265581-d935ad00-1861-11eb-891e-cf3ce88532ae.png)

@jacogr Hi Jaco, I've already upgraded the @polkadto/api version to version 2.4.1, but it seems it still isn't compatible with tuple.

**Comment by jacogr** [comment]
They are all handled separately - 2.4 added support for consts and raw RPC calls. The above are Submittables they were not touched. (Adding on 1 does not add it on the others, the generation logic is very different)

**Comment by jacogr** [comment]
Ummm... seems I misread your request, you did as for txs.

**Comment by herryho** [comment]
As an alternative, is it right to wrap the tuple with the squre brackets just like [TxOut, u64]? I tried to do this manually, and it can pass the type check. But I'm not sure whether it will cause problems later on.

**Comment by jacogr** [comment]
Yes, that works. All `ITuple<[a, b]>` does is basically `[a, b] & Codec`

**Comment by herryho** [comment]
Ok, I see. Thanks for your answer and the reopen of the issue!

**Comment by jacogr** [comment]
Ok, so I have no idea why in your case some don't work, see for instance this - https://github.com/polkadot-js/api/blob/master/packages/api/src/augment/tx.ts#L1110 - Tuple input.

(The logic in the tx is actually what was adapted to make RPC work and tested there as well).

**Comment by jacogr** [comment]
Can you please copy (instead of a screenshot) the definition as (wrongly) generated?

**Comment by herryho** [comment]
![image](https://user-images.githubusercontent.com/45537372/97285222-e90eba80-187c-11eb-9428-1e3e1272ac7b.png)

Below is the rust definition:
changed_trxs: Vec::<((TxOutV1<T::AccountId>, u64), TrxStatus, (TxOutV1<T::AccountId>, u64), Option<Checksum256>)>)

********************************************************************************
![image](https://user-images.githubusercontent.com/45537372/97285872-bd400480-187d-11eb-8273-426e78063c1b.png)

Below is the generated augment-api-tx.ts presentation:
      updateBridgeTrxStatus: AugmentedSubmittable<(changedTrxs: Vec<ITuple<[ITuple<[TxOut, u64]>, TrxStatus, ITuple<[TxOut, u64]>, Option<Checksum256>]>> | ([(TxOut,u64) | [TxOut | { Initial: any } | { Generated: any } | { Signed: any } | { Processing: any } | { Success: any } | { Fail: any } | string | Uint8Array, u64 | AnyNumber | Uint8Array], TrxStatus | 'Initial' | 'Generated' | 'Signed' | 'Processing' | 'Success' | 'Fail' | number | Uint8Array, (TxOut,u64) | [TxOut | { Initial: any } | { Generated: any } | { Signed: any } | { Processing: any } | { Success: any } | { Fail: any } | string | Uint8Array, u64 | AnyNumber | Uint8Array], Option<Checksum256> | null | object | string | Uint8Array])[]) => SubmittableExtrinsic<ApiType>>;

**Comment by jacogr** [comment]
Ok, it is a nesting issue - it should be sorted in #2788 (well, the tests does the right thing, going from failing to passing). It would however be good if you could possibly just give it a run-through when merged, it will be `2.4.2-3` (So we don't have a still-not-working 2.5.1 next Monday)

**Comment by herryho** [comment]
Ok. Thank!
