### ISSUE TITLE
Unable to create proper abi.

### ISSUE THREAD

**Issue by sbhm2** [polkadot-js/api#2764]
`const abi = new Abi(api.registry, <...JSON ABI...>);`

This syntax given in the template is throwing error:-

> "_Argument of type 'Registry' is not assignable to parameter of type 'AnyJson'_ 

I checked the constructor definition and it is `constructor(abiJson: AnyJson, chainProperties?: ChainProperties);`. So the error is somewhat correct. As per my understanding, I should do
`const abi = new Abi(<...JSON ABI...> );
`
But after doing this, I am getting error 

> Property 'transfer' does not exist on type 'AbiMessage[]' 

in function calls like
`this.abi.messages.transfer(to, value)`
`this.abi.messages.approve(spender, value)`
`this.abi.messages.transferFrom(from, to, value)`
I am using 
**"@polkadot/api": "^2.3.1",
    "@polkadot/api-contract": "^2.3.1",**
and I am following this blog. [https://brightinventions.pl/blog/erc20-substrate-nest-example](url)

I am pretty much confused about where I am making the mistake. Please help.

**Comment by jacogr** [comment]
You won't call `this.abi.messages.transfer(to, value)` - the Abi actually just exposes the actuall messages as a holder to iterate through. For calling, you should use contract, i.e. https://polkadot.js.org/docs/api-contract/start/contract

**Comment by sbhm2** [comment]
I am trying to make a transaction on ERC20 contract given here [https://substrate.dev/substrate-contracts-workshop/#/2/creating-the-erc20-template](url).
I checked the metadata.json of the contract and it has 'transfer', 'approve' etc inside spec.messages
So, I think
`await this.api.tx.contracts.call(ERC20, 0, 1000000000000, this.abi.messages.transfer(to, value))
      .signAndSend(this.alice, (result: SubmittableResult) => { Logger.log(result) })`
should work as per your suggestion. But this kind of calls are throwing error at abi.messages

**Comment by jacogr** [comment]
You cannot use `this.abi.messages.transfer - it doesn't have an encoder.

As per my suggestion and the docs -

- Create a `Contract` object, passing the ABI & API
- that exposes (on the contract object) `.tx.methodName`

**Comment by sbhm2** [comment]
Thanks, @jacogr.
