### ISSUE TITLE
kusama and polkadot are greater than a certain number to send an error

### ISSUE THREAD

**Issue by toolsopen** [polkadot-js/api#2775]
Sending method: batch
kusama: greater than 10000
polkadot: greater than 1000000
An error occurred:
signError: createType(Call):: Struct: failed on'args':: Struct: failed on'value':: Assertion failed

**Comment by jacogr** [comment]
You will need to be slightly more specific here. What are you doing ( a code sample is always good).

**Comment by joepetrowski** [comment]
I believe they are trying to send batches of `balances.transfer` with an `amount > 10_000_000_000_000_000` (10 kKSM or 1 MDOT) and are getting an error. (Not sure if that's on transaction construction or on submission to node @toolsopen )

**Comment by jacogr** [comment]
As indicated, really need very explicit info, with samples (if possible) to even attempt to try and help.

**Comment by jacogr** [comment]
Closing. Please feel free to comment when info is available for either help or additional actions.
