### ISSUE TITLE
Polkadot.js.org does not include API section and links to Flow instead of TypeScript

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#278]
When I go to https://polkadot.js.org/, I can only see links to polkadot-js/apps, polkadot-js/client, and polkadot-js/dev, however I cannot see a link to polkadot-js/api.

Also, where it has the link to "full type definitions" the link goes to the Flow website https://flow.org/, however I think it should have a link to TypeScript http://typescriptlang.org instead.

Screenshot:
<img width="524" alt="screen shot 2018-10-13 at 01 49 41" src="https://user-images.githubusercontent.com/6226175/46898498-51eb8b80-ce8a-11e8-8121-2468e0c3e378.png">

**Comment by jacogr** [comment]
Should be logged/fixed here https://github.com/polkadot-js/polkadot-js.github.io
