### ISSUE TITLE
Proxy | Call | example

### ISSUE THREAD

**Issue by ironoa** [polkadot-js/api#2784]
Could you please help me to recreate this behavior via code ? 

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/25957738/97211071-ca49ee80-17be-11eb-8ae8-866d8a6ffab4.png">

I'm wondering what to use as `Call` parameter: 
```js 
api.tx.proxy.proxy(primaryAccount, null, 'Call Parameter')
```

My code, without the proxy involved, looks like:
```js
const extrinsic = api.tx.identity.provideJudgement(registrarIndex,target,judgement)
const txHash = await extrinsic.signAndSend(registrarAccount)
```

Maybe something like this ?
```js
const callIndex = api.tx.identity.provideJudgement.callIndex
const extrinsic = api.tx.proxy.proxy(primaryAccount, null, { callIndex, args:[registrarIndex,target,judgement] })
const txHash = await extrinsic.signAndSend(proxyAccount)
```

Thanks !

**Comment by jacogr** [comment]
You can just pass the actual generated (pre-sending) tx as generated by the API through. For instance, here is a cookbook example with `utility.batch` which takes in an array of `Call` - https://polkadot.js.org/docs/api/cookbook/tx#how-can-i-batch-transactions

**Comment by ironoa** [comment]
So `SubmittableExtrinsic` can be passed as `Call`, am I right ?
Thanks for the cookbook.

FYI: the example I previously posted above is working fine:
```js
const callIndex = api.tx.identity.provideJudgement.callIndex
const extrinsic = api.tx.proxy.proxy(primaryAccount, null, { callIndex, args:[registrarIndex,target,judgement] })
const txHash = await extrinsic.signAndSend(proxyAccount)
```

**Comment by jacogr** [comment]
Yes, SubmittableExrinsic can be passed - there are specific construction checks to allow them so it is easier to use, so you can pass a Call to a submittable or vice-versa. aka you don't need to manually construct like in your example above, this is simpler and cleaner -

```js
const reg = api.tx.identity.provideJudgement(registrarIndex, target, judgement)
const extrinsic = api.tx.proxy.proxy(primaryAccount, null, reg)
const txHash = await extrinsic.signAndSend(proxyAccount)
```

**Comment by jacogr** [comment]
Closing as resolved.
