### ISSUE TITLE
bug/help: error in connecting to provider via bundle

### ISSUE THREAD

**Issue by thelostone-mc** [polkadot-js/api#2794]
#### Description 

I'm using a bundled version of [polkadot-bundle](https://github.com/thelostone-mc/polkadot-bundle)

This was working until a few days ago where connecting the provider errors out!

https://github.com/thelostone-mc/polkadot-bundle/blob/master/src/utils.js#L20

![image](https://user-images.githubusercontent.com/5358146/97413559-f08b9d80-1928-11eb-9163-6cf041c5eab2.png)

Any idea why this happens / if something changed ?

The code snippet being used:

```
  polkadot_utils.connect('wss://rpc.polkadot.io');       
```

Here is gist of the error 
https://gist.github.com/thelostone-mc/b597ed153bc19bd438b1f4a67c4e052f

`raven.js:58 2020-10-28 17:59:20          API-WS: disconnected from wss://rpc.polkadot.io code: '1006' reason: ''`

Here it is in live
https://gitcoin.co/issue/PureStake/gitcoin-hello-world-by-moonbeam/3/100023962

**Comment by jacogr** [comment]
The connection errors are transient, in this case it actually did connect. 

the issue you have is that your bundle is way outdated and pre API V2, so it doesn't have support for metadata V12 that is live on all Substrate 2.0-based chains. Hence the error is that it cannot decode metadata V12. Even if it did connect, areas such as balances would be decoded incorrectly due to the changes in types that has been applied on later versions of Kusama/Polkadot.

**Comment by thelostone-mc** [comment]
Oh so which means recreating the bundle would fix it up with updated packages?

https://github.com/thelostone-mc/polkadot-bundle/blob/master/package.json#L12-L21
This is what I've got right now -> Is there a place where I can check which versions to use?

**Comment by jacogr** [comment]
I saw, 1.29 is very old. I would suggest going through he releases https://github.com/polkadot-js/api/releases - 1.34 introduced V12 metadata and on V2 support for substrate V2 was added (which is what Kusama/Polkadot is based on)

Generally when dealing with Kusama/Polkadot you probably want to upgrade the API each time the chain has an update. Chain upgrades generally mean new types that have been added, older types that have been adjusted, new modules and those need to at least types support from the API layer.

**Comment by thelostone-mc** [comment]
Gotcha ! This helps @jacogr

**Comment by thelostone-mc** [comment]
Just upgraded and regenerated the bundle and it worked
https://github.com/thelostone-mc/polkadot-bundle/blob/master/package.json

Will keep an eye out for releases and upgrading them 
Lemme know if you think this would be worth maintaining under the polkadot-js repo

**Comment by Swader** [comment]
@thelostone-mc we have [this](https://github.com/shawntabrizi/polkadot-js-bundle) already, not sure what @shawntabrizi's long term plans with it are but it seems reasonably up to date.
