### ISSUE TITLE
Prevent extrinsic submission from crashing

### ISSUE THREAD

**Issue by raykyri** [polkadot-js/api#280]
This should be `statusCb` for extrinsic submission to work, right?

https://github.com/polkadot-js/api/blob/67f625b096e8cc3f0a091105061a5f52e01bedef/packages/api/src/promise/SubmittableExtrinsic.ts#L21

**Comment by jacogr** [comment]
O, hell. Good catch, not sure how this slipped through with the end-to-end testing.
