### ISSUE TITLE
Error Querying All Proxies

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#2801]
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1860335/97470228-98b05f00-1947-11eb-8085-7a991009c1ef.png">

Missing type or maybe corrupt data?

This is on Polkadot, tying to query all entries in the storage item.

**Comment by kianenigma** [comment]
Same issue. I ran into it while querying accounts one by one, so I might be able to give you an account that actually triggers the issue.

**Comment by kianenigma** [comment]
Found one: 1KvKReVmUiTc2LW2a4qyHsaJJ9eE9LRsywZkMk5hyBeyHgw

**Comment by jacogr** [comment]
For that account -

```
{"jsonrpc":"2.0","method":"state_storage","params":{"result":{"block":"0xb4f38e95ce8a1e71a5cc319de1e74b558b835a97d5a93b6e8d64e7d8e3bb5340","changes":[["0x1809d78346727a0ef58c0fa03bafa3231d885dcfb277f185f2d8e62a5f290c854d2d16b4be62d0e00e6de68b13b82479fbe988ab9ecb16bad446b67b993cdd9198cd41c7c6259c49","0x0898c8a3d01da9877b7b30877c717ae8f2a7e726cefa176c5dfcdcebc9b6a122230098c8a3d01da9877b7b30877c717ae8f2a7e726cefa176c5dfcdcebc9b6a1222304005109bd2e0000000000000000000000"]]},"subscription":"wdwtnxoJRb6tSjUm"}}
```

Manual decoding should show what the issue is.

**Comment by kianenigma** [comment]
Turns out, this dude is the old sudo account, and the is expected, as per noted here: 

https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L811

**Comment by kianenigma** [comment]
Main incentive to fix is that currently `api.query.proxies.entries()` is broken and a combination of `.keys()` with `try` is the workaround.

**Comment by jacogr** [comment]
Ok, so actually the definitions should cater for it, i.e. that entry didn't go away in the types, but rather is still there (albeit unknown). So the fact that the enum entry is currently unused is not what breaks it, rather it is the actual data itself.

Unlike in Rust all the types are handled via the same generic parser (since they are injected), so it is not as easy as "ignore" one entry if it has X, Y or Z.
