### ISSUE TITLE
Error: Invalid JSON ABI structure supplied, expected a recent metadata version

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2818]
if i run the let code = new CodePromise(api, metaFile, wasmFile), i got the error like title.
maybe version problem, can you help this error?

<version>
 @polkadot/api": "^2.2.1",

 @polkadot/api-contract": "^2.5.1",

-meta abi version
"contract": {
    "name": "erc721",
    "version": "3.0.0-rc2",
    "authors": [
      "Parity Technologies <admin@parity.io>"
    ]

**Comment by jacogr** [comment]
Just ensure your API deps are all the same version. So both API and API-contract.

**Comment by puffanddmx** [comment]
i match the api and api-contract with version 2.2.1.
still same error.

"@polkadot/api": "^2.2.1",
"@polkadot/api-contract": "^2.2.1",
"@polkadot/keyring": "^3.7.1",
"@polkadot/rpc-provider": "^2.2.1",

**Comment by puffanddmx** [comment]
thanks!
