### ISSUE TITLE
getting the contract address

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2819]
I want to know the contract address(5xxxx.....) after executing the putcode function of wasm built with ink. Is there actually a way to get the address of the contract in putcode? In the code return value below, there is no way to know other than codehash.

<code>
let code = new CodePromise(api, metaFile, wasmFile);
            let unsub = await code
                .createBlueprint()
                .signAndSend(pair, (result) => {
                    if (result.status.isInBlock || result.status.isFinalized) {
                        blueprint = result.blueprint;
                        res.status(200).send(result);
                        unsub();
                    }
                });

**Comment by jacogr** [comment]
The blueprint has an `.address` getter.
