### ISSUE TITLE
ink contract query error

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2822]
When calling the ink contract below, the symbol value is properly obtained. However, it turns out that owner_of below is not a function. What was wrongly set up?

1. code : result = await contract.query.symbol(); -> works well

2. code: result = await contract.query.owner_of(id); -> TypeError: contract.query.owner_of is not a function

  #[ink(message)]
        pub fn symbol(&self) -> String {
            self.symbol.clone()
        }

#[ink(message)]
        pub fn owner_of(&self, id: TokenId) -> Option<AccountId> {
            self.token_owner.get(&id).cloned()
        }

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api-contract/FAQ#why-is-there-a-snake_case-vs-camelcase-difference
