### ISSUE TITLE
After I remove yarn.lock, an error occurs when I reinstall.

### ISSUE THREAD

**Issue by IIlIlI** [polkadot-js/api#2825]
➤ YN0000: Failed with errors in 30s 779ms

After I removed the yarn.lock, I tried for many times, but the `yarn install` failed.

But if I also remove the @polkadot/dev dependency. The installation will succeed.

So I think there's something wrong with @polkadot/dev and yarn V2.

The problem now is that I cannot install @polkadot/dev with yarn V2  if there is no yarn.lock file in the project.

Is this a known problem?

**Comment by jacogr** [comment]
This is a yarn2 problem. If you filter the logs you will see it cannot apply a patch to fsevents.

**Comment by IIlIlI** [comment]
Ok, thank you for your answer

**Comment by jacogr** [comment]
This is the link to the issue and the PR - and how to work around. (I have not swapped to the source version in any of the repos, hoping 2.3.4 or 2.4 will come soon) - https://github.com/yarnpkg/berry/issues/2089
