### ISSUE TITLE
How to access the return value using the API

### ISSUE THREAD

**Issue by JeremyConnor** [polkadot-js/api#2837]
When we make a function call to the Smart Contract using the @polkadot/api-contract, we are returned with a ```result``` object if the transaction was successful. I have a function which is supposed to return a variable string. Below is the mentioned value of the ```result``` object. But I cannot see any data regarding the returned string. Also, how should I access a triggered event from the API?
```
Result is :  {
  "dispatchInfo": {
    "weight": 150000000,
    "class": "Normal",
    "paysFee": "Yes"
  },
  "events": [
    {
      "phase": {
        "ApplyExtrinsic": 1
      },
      "event": {
        "index": "0x0000",
        "data": [
          {
            "weight": 150000000,
            "class": "Normal",
            "paysFee": "Yes"
          }
        ]
      },
      "topics": []
    }
  ],
  "status": {
    "Finalized": "0x3159371db6098be8c0c9552664aa7aa2c792e6c0c7d67ebbb08aef8a0a2eb193"
  }
}
```

**Comment by jacogr** [comment]
There is no result string, transactions don't return result strings on inclusion. So in that case all you have in the block where it was included (status.Finalized).

**Comment by jacogr** [comment]
Events as specified by the ABI will be decoded on current versions of the API, see https://polkadot.js.org/docs/api-contract/start/contract.tx#events

**Comment by JeremyConnor** [comment]
So how am I supposed to manage a function which is supposed to return a string?

**Comment by jacogr** [comment]
Transactions cannot return results at all. What you do it emit events and then look at those. (That is the same with normal Substrate transactions, no return value, but events are available)

**Comment by JeremyConnor** [comment]
So in order to work around this, I need to create events for every function in my Smart Contract which is supposed to return a variable?

**Comment by jacogr** [comment]
Transactions that are included in blocks don't return values. The only values that can be returned is via reads, that is a non-mutable operation, not executed via transactions.

**Comment by JeremyConnor** [comment]
> Events as specified by the ABI will be decoded on current versions of the API, see https://polkadot.js.org/docs/api-contract/start/contract.tx#events

So as this document states, "... however should events be emitted, the array will contain all the decoded values.", 
```result.contractEvents``` should contain all the values of ```emit``` from the smart contract

**Comment by jacogr** [comment]
Yes, events, not call results. Exactly the same as normal Substrate transactions, no magic. Transaction gets included, it emits events to indicate state changes if required.

**Comment by JeremyConnor** [comment]
Okay, got it. Thanks for clearing it out!

**Comment by JeremyConnor** [comment]
@jacogr 
I made sure that I had implemented events, but still could not retrieve it from the api. 
Below is my register function which in turn calls the ```register``` function in the Smart Contract.
```
export const register = async (contract, myAddress, myKey) => {
    const response = await contract
      .exec('register',  gasLimit, value, myAddress)
      .signAndSend(myKey,(result) => {
        if(result.status.isInBlock){          
          console.log('in a block');
        }else if (result.status.isFinalized) {
          console.log("\nResult is : ", JSON.stringify(result, null, 2));
          console.log("\nEvent is : ", result.contractEvents);
        }
      });
}
```
This is the terminal output which I received for the above used console.log()
```
Result is :  {
  "dispatchError": {
    "Module": {
      "index": 9,
      "error": 12
    }
  },
  "dispatchInfo": {
    "weight": 67500000,
    "class": "Normal",
    "paysFee": "Yes"
  },
  "events": [
    {
      "phase": {
        "ApplyExtrinsic": 1
      },
      "event": {
        "index": "0x0001",
        "data": [
          {
            "Module": {
              "index": 9,
              "error": 12
            }
          },
          {
            "weight": 67500000,
            "class": "Normal",
            "paysFee": "Yes"
          }
        ]
      },
      "topics": []
    }
  ],
  "status": {
    "Finalized": "0x5a584da69a08331b0400e0d52dcb1a85e53a26d4b38539dc1f819f52f623066b"
  }
}
    
Event is :  undefined

```
I have also mentioned the event that I have created in my Solidity Smart Contract
```
event successfulRegistration(address _newUser);
```

**Comment by jacogr** [comment]
There are no events in that call, it has a DispatchError.

**Comment by JeremyConnor** [comment]
What are DispatchErrors and how to solve them?

**Comment by jacogr** [comment]
The current contracts palette only allows you to deploy one contract with the same parameters, well, once. (That is due for changing)

DispatchError is from the chain, see https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event how to map it to the metadata.

**Comment by JeremyConnor** [comment]
@jacogr  I was able to solve the dispatch error. And I am getting the following result on the terminal : 
```
Result is :  {
  "dispatchInfo": {
    "weight": 151500000,
    "class": "Normal",
    "paysFee": "Yes"
  },
  "events": [
    {
      "phase": {
        "ApplyExtrinsic": 1
      },
      "event": {
        "index": "0x0000",
        "data": [
          {
            "weight": 151500000,
            "class": "Normal",
            "paysFee": "Yes"
          }
        ]
      },
      "topics": []
    }
  ],
  "status": {
    "Finalized": "0xf32a5420f72001fcdc8ce91ccf05a976d2317c167252ffdc1e446a4631a7e909"
  }
}
```
I have made sure that the function emits an event.

**Comment by JeremyConnor** [comment]
I also tried getting the value of a return variable, but didn't get the output I was expecting:
```
export const helperFunction = async (contract, myAddress, myKey) => {
    const {gasConsumed, result, outcome} = await contract.query.viewBalance(myAddress, value, gasLimit, myAddress);
    console.log("result : ", JSON.stringify(result, null ,2));
    console.log("gasConsumed : ", JSON.stringify(gasConsumed, null ,2));
    if(result.isOk){
      console.log('Success ', JSON.stringify(outcome, null ,2));
    } else{
      console.log('Error ', result.asErr);
    }
}
```
Where, the viewBalance function is : 
```
event viewingBalance(address sender, uint balance);

function viewBalance(address _user) public view returns(uint) {
    emit viewingBalance(_user, balance[_user]);
    return balance[_user];
}
```
The terminal output that I received was : 
```
result :  {
  "Ok": {
    "flags": 0,
    "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
  }
}
gasConsumed :  667000000
Success  undefined
```
