### ISSUE TITLE
Output log of jsonrpc

### ISSUE THREAD

**Issue by aniiantt** [polkadot-js/api#2855]
when NODE_EVM=test, the jsonrpc log is output.
But there is a problem. The metadata output is so long that you might not be able to find the log you want.
On my computer, there's another problem. When I run the command using the terminal in vscode, the metadata would cause the VSCode to freeze.

![image](https://user-images.githubusercontent.com/7029338/99250691-f4984480-2870-11eb-99b7-2abb90490e19.png)

![image](https://user-images.githubusercontent.com/7029338/99250487-98352500-2870-11eb-8a04-a9337da08b74.png)

**Comment by jacogr** [comment]
There is an issue logged to filter explicitly based on flags instead of env in the common repo (which does the logging). PRs welcome there.

**Comment by aniiantt** [comment]
@jacogr
But my problem is that the metadata log is too long. I still need other jsonrpc logs except for metadata. So I wonder if it is possible to set a maximum length for the log, beyond which it will show "...".

Or we can use the debug (https://github.com/visionmedia/debug) to control the metadata is displayed. We can use it like this:
`DEBUG=jsonrpc:metadata ....` or `DEBUG=jsonrpc:* ....` . However, this change only distinguishes metadata from other logs. If I upload contract wasm, or get contract wasm, If I upload contract wasm or get contract wasm, jsonrpc will also fill my screen and freeze my Vscode.

So maybe we just need to set the maximum display length of the log?

**Comment by jacogr** [comment]
`DEBUG=api,rpc,...` is already available (although `NODE_ENV=test` switches on all). However won't make  difference here, everything is logged on the RPC layer and it position won't move, it is a singular in/out point.

Feel free to add the request for size-limits to the issue in common, could be useful.
