### ISSUE TITLE
Unable to access item set via localStorageSet.

### ISSUE THREAD

**Issue by jnaviask** [polkadot-js/api#2856]
I have an offchain worker with the following code executed in the body of the worker function:

```rust
let s_info = StorageValueRef::persistent(b"worker::token");
let s_value = s_info.get::<Vec<u8>>();
```

I want to set this item via a typescript node file using the polkadot-js API, which I attempted to do as follows:

```typescript
let token = process.env.WORKER_TOKEN;
let encodedToken = api.createType('Bytes', token);
await api.rpc.offchain.localStorageSet('PERSISTENT', 'worker::token', encodedToken);
```

However, the offchain worker is never able to read the set token. Is there a different invocation I need to call in order to get this working? Thanks.

**Comment by jacogr** [comment]
I would suggest logging it on the node side and see what is done with the value retrieved. That should indicate if it is correct as expected. 

Never used this myself so cannot comment on how it is passed, assuming the env comes through as hex and the last 2 are Bytes, it would seem fine. (First item does look weird, not sure how that maps to the RPC)

**Comment by jnaviask** [comment]
I added some logs: the local storage result goes from `None` to `Some(None)` once I run the typescript call. I'll try wrapping in an Option type.

**Comment by jacogr** [comment]
So that would probably mean the first and second param is correct and between the RPC input and the set it doesn’t know how to handle it.  (Best guess)
