### ISSUE TITLE
Out of Memory Error in Polkadot JS

### ISSUE THREAD

**Issue by Gauthamastro** [polkadot-js/api#2864]
I am using the following code 
  
    api.derive.chain.subscribeNewHeads((header) => {
        api.query.polkadex.marketInfo(tradingPairID, header.number).then(market_data => {
            let market_data_obj = {
                "date": GenesisTime + (header.number) * blockPeriod,
                "low": market_data.low / factor,
                "high": market_data.high / factor,
                "volume": market_data.volume / factor,
                "open": market_data.open / factor,
                "close": market_data.close / factor
            };
            if (graph_data.length >= 3600) {
                graph_data.shift();
                graph_data.push(market_data_obj);
            } else {
                graph_data.push(market_data_obj);
            }
            // When new market data arrives from node
            io.emit("market-data-stream", market_data_obj)
        });

        api.query.system.events((events) => {
            // Loop through the Vec<EventRecord>
            events.forEach((record) => {
                // Extract the phase, event and the event types
                const {event, phase} = record;
                const types = event.typeDef;

                if ((event.section === "polkadex") && (event.method === "FulfilledLimitOrder" || event.method === "PartialFillLimitOrder")) {
                    // When new order got matched
                    io.emit("last-trade", {
                        "side": event.data[2].toString(),
                        "price": event.data[3] / factor,
                    });
                } else if ((event.section === "polkadex") && (event.method === "NewLimitOrder")) {
                    // When new order was inserted
                    io.emit("new-trade", {
                        "side": event.data[2].toString(),
                        "price": event.data[3] / factor,
                        "quantity": event.data[4] / factor,
                    });
                }
            });
        });

        let best_bid;
        let best_ask;
        api.query.polkadex.orderbooks(tradingPairID).then((orderbook) => {
            best_bid = (orderbook.best_bid_price / factor);
            best_ask = (orderbook.best_ask_price / factor);
        }).then(() => {
                api.query.polkadex.priceLevels.entries(tradingPairID).then((levels) => {
                    let orderbook = {};
                    orderbook.best_bid = best_bid;
                    orderbook.best_ask = best_ask;
                    // This is a trick to do parallel calculation of order quantity.
                    formatData(levels).then(price_levels => {
                        let temp = getfilteredPriceLevels(price_levels, orderbook.best_ask, orderbook.best_bid)
                        orderbook.bid_levels = temp.bids
                        orderbook.ask_levels = temp.asks
                        // console.log(orderbook.bid_levels);
                        // console.log(orderbook.ask_levels.reverse(), orderbook.bid_levels.reverse());
                        io.emit("orderbook-updates", orderbook);
                    });
                })
            }
        )

    });`

It is running fine for like 20 mins then it crashes with the following OOM error
`<--- Last few GCs --->

[9074:0x152d9a0]   559278 ms: Mark-sweep 1277.5 (1431.8) -> 1270.0 (1431.3) MB, 1100.4 / 0.0 ms  (average mu = 0.111, current mu = 0.034) allocation failure scavenge might not succeed
[9074:0x152d9a0]   560453 ms: Mark-sweep 1278.9 (1431.8) -> 1271.4 (1447.8) MB, 1092.9 / 0.0 ms  (average mu = 0.091, current mu = 0.070) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x36eac5d5452b]
Security context: 0x27bc0112ee11 <JSObject>
    1: broadcast [0x2d7d3015b691] [/home/ubuntu/polkadex-cloud/node_modules/socket.io-adapter/dist/index.js:~91] [pc=0x36eac62f50e6](this=0x2d7d301798f9 <EventEmitter map = 0x29b180f6fc29>,packet=0x321b97091de1 <Object map = 0x19866f8242d9>,opts=0x321b97091f11 <Object map = 0x115fda030569>)
    2: /* anonymous */ [0x321b97094771] [/home/ubuntu/polkadex-cloud...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fe32c11946c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7fe32c1194b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7fe32c345e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7fe32c3460e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7fe32c6e0c66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7fe32c6f2043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7fe32c6f2930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7fe32c6f491d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7fe32c6f4975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7fe32c6c0dda v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7fe32c94c31e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.64]
`

**Comment by jacogr** [comment]
The trace above is from within socket.io. To see what causes it, would suggest disabling/removing all io emits there. (Quite possible some objects just live on forever and never get marked for de-allocation, e.g. orderbook above)

**Comment by Gauthamastro** [comment]
@jacogr Okay I will check it
