### ISSUE TITLE
How to use txhash to query a transaction in Polkadot JS / API?

### ISSUE THREAD

**Issue by Yangxin-GG** [polkadot-js/api#2868]
How to use txhash to query a transaction in Polkadot JS / API?
I am a JS novice, did not find the corresponding API, please tell me, thank you！

**Comment by jacogr** [comment]
There is no such API. Substrate does not expose a "query-by-tx-hash" RPC, nor is it indexed on the Substrate node since the transaction hashes are non-unique across the chain. See https://wiki.polkadot.network/docs/en/build-protocol-info#unique-identifiers-for-extrinsics

**Comment by Yangxin-GG** [comment]
ok，thank you

**Comment by jacogr** [comment]
Closing. 

(Also added an FAQ entry in the API now, https://polkadot.js.org/docs/api/FAQ#which-api-can-i-use-to-query-by-transaction-hash - sadly I always have to search to the Polkadot wiki link, now it should be easier to get to)
