### ISSUE TITLE
approveAsMulti fails due to low balance only on mainnet.

### ISSUE THREAD

**Issue by LuisAcerv** [polkadot-js/api#2871]
Hello!

I am trying to signAndSend an approveAsMulti transaction in kusama network. If I run the code pointing to my dev nodes the code works, but in mainnet the code fails with 

```bash
balances.undefined:  Balance too low to send value
```
The Failed Extrinsic:
https://kusama.subscan.io/extrinsic/0xa2535715394ea98fdaacc8e0f6dd8008b818a85315a0213a8fa897a9f52ba80a

I am pretty sure that the accounts have enough balance, but I am not sure what is wrong with my code since it works on the testnet.

My snippet:
```js
// I just left the relevant parts:
  const txs = [
    api.tx.balances.transfer(sellerAddress, nativeAmount * multiplier), //paymentToSeller
    api.tx.balances.transfer(platformKey, platformFees * multiplier), //paymentToPlatform
  ];

  const transactions = api.tx.utility.batch(txs);

   const { weight, partialFee } = await api.tx.balances
    .transfer(sellerAddress, nativeAmount * multiplier)
    .paymentInfo(buyerPair);


   const tx = api.tx.multisig.approveAsMulti(
      threshold,
      otherSignatoriesSorted,
      null, // Null since this is the first call
      transactions.method.hash,
      weight.toNumber()
  );

  const promise = new Promise((resolve, reject) => {
    tx.signAndSend(buyerPair, ({ events = [], status }) => {
      console.debug(`Status: ${status.type}`);
      let index;
      let blockHash;
      if (status.isFinalized) {
        
        // If there is any error make it readable
        const filteredEvents = events.filter(
          ({ event: { section, method } }) =>
            section === "system" && method === "ExtrinsicFailed"
        );

        filteredEvents.forEach(
          ({
            event: {
              data: [error, info],
            },
          }) => {
            if (error.isModule) {
              // for module errors, we have the section indexed, lookup
              const decoded = api.registry.findMetaError(error.asModule);
              const { documentation, method, section } = decoded;
              console.log("RAW_ERROR=======>", decoded);

              console.log(`${section}.${method}: ${documentation.join(" ")}`);
            } else {
              // Other, CannotLookup, BadOrigin, no extra info
              console.log(error.toString());
            }
          }
        );
        // If there is any error make it readable END

        console.debug(`Hash: ${status.asFinalized}`);
        blockHash = `${status.asFinalized}`;
        events.forEach(({ state, event: { data, method, section } }) => {
          console.debug(`\t' ${state}: ${section}.${method}:: ${data}`);
          if (`${method}` === "NewMultisig") {
            console.log('STATE==========>',state);
            console.log('DATA==========>',data);
          }
          console.debug("Transaction index:", index);
        });
        resolve({ index, blockHash });
      }
    });
  });

```

The code above on local testnet returns: `system.ExtrinsicSuccess:: [{"weight":215137000,"class":"Normal","paysFee":"Yes"}]`

<img width="1440" alt="Captura de Pantalla 2020-11-23 a la(s) 16 22 22" src="https://user-images.githubusercontent.com/37945269/100023171-1ed68e80-2daa-11eb-9b32-70ac84b355c4.png">

Any help would be appreciated.

**Comment by jacogr** [comment]
The error is not coding related, as per the message, the sender does not have enough balance to enact this transaction.

The confg between local development and Kusama is not the same, for multisig you need a have a larger balance available for these transactions, as per the configuration of the chain. I'm not sure about the numbers, but with 1.5KSM, it is not enough for this type. (it uses the balance to reserve the storage of the call, once finalized, it gets returned)

**Comment by jacogr** [comment]
This is the config on Kusama - 

![image](https://user-images.githubusercontent.com/1424473/100061047-bfba5d80-2e2d-11eb-99a9-f92fdacccfcb.png)

(the depositFactor is a per-byte value in addition to the base deposit)

**Comment by LuisAcerv** [comment]
@jacogr Thanks for the response! So I will need have a larger balance to run tests on mainnet. Thank you! 😃
