### ISSUE TITLE
Where is root key from?

### ISSUE THREAD

**Issue by fwh1990** [polkadot-js/api#2873]
```typescript
const sudoKey = await api.query.sudo.key();
const sudoPair = keyring.getPair(sudoKey);
```

I am using sudo api to send balance to address, but I got this message
```
Error: Unable to retrieve keypair '0xxxxxxxxxxxxx...'
```
So how to generate root key by myself?

**Comment by jacogr** [comment]
It is from the chain itself. The storage entry from the sudo module under key.

**Comment by fwh1990** [comment]
Is there any document for this section? I am a new bee to blockchain.

**Comment by jacogr** [comment]
The config needs to be do on the sudo module in Substrate. Once you added a known key there, you can add it to the keyring. (Unless known to the keyring, you obviously cannot retrieve it since it is a secret, so add it to the Rust code for the Sudo module and then add the same seed to the keyring)

**Comment by jacogr** [comment]
Closing.
