### ISSUE TITLE
Q: Tx hash from system event?

### ISSUE THREAD

**Issue by dintores** [polkadot-js/api#2883]
Hey.

I subscribed to events, then I sent a transaction, then I saw it in the general descendant of all events.

tx:
https://polkascan.io/polkadot/transaction/0xb05cda3748cc05692099a8c21a02d0958527f61336b452d0421287d574f4004d

hash: 0xb05cda3748cc05692099a8c21a02d0958527f61336b452d0421287d574f4004d

``` javascript
await api.query.system.events((events) => {
    events.forEach((record) => {
       console.log(record) // how get tx hash?
    })
});
```

How can I get the transaction hash in the general flow of events?
I only managed to make a hash for event

@polkadot/api 2.8.2
env: node 14

**Comment by jacogr** [comment]
Take a look at this to map events to extrinsics. https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

Once you have the relevant extrinsic from the block, you can just call `.hash` on it to get the specific hash for it.

**Comment by dintores** [comment]
I figured it out something like this, but it doesn't work. The hash does't match.

```
  await api.query.system.events((events) => {
    events.forEach((record) => {
      console.log(record.event.hash) // ?
    })
  })
```

Your example uses block. Why is he? Can you send me a more detailed example?

**Comment by dintores** [comment]
My task is to see the balance transfer event - and display the hash of this transaction.

**Comment by dintores** [comment]
My task is to see the balance transfer event - and display the hash of this transaction.

**Comment by jacogr** [comment]
Then map between the two.  Events and transactions for the block, as described above.

**Comment by dintores** [comment]
You can write an example in which when an event is received, its hash will be displayed?

**Comment by jacogr** [comment]
Just adapt the example above, as linked -

1. while looping over the events, filter it for the event you want (we do loop through it and we do print the module & name)
2. when non-empty, print `ex.hash`

Feel free to make a PR to the above docs when not 100% clear.

**Comment by jacogr** [comment]
Closing, answered.
