### ISSUE TITLE
Batch Call Encoded as All Zeroes When Passed as Arg to Multisig.asMulti

### ISSUE THREAD

**Issue by danforbes** [polkadot-js/api#2889]
In [this script](https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/df/workshop/explore/scripts/init.js) I am trying to execute some batch calls from a multisig address. It seems like there is something that happens when the batch `Call` is encoded as an arg into the `api.tx.multisig.asMulti` call - it's encoded as an array of `0`s. It seems like this happens somewhere in between `_decorateExtrinsicEntry` and `createSubmittable`.

![image](https://user-images.githubusercontent.com/2193247/100554436-7e6ce800-3249-11eb-8b2f-0922e98350c8.png)

![image](https://user-images.githubusercontent.com/2193247/100554451-93e21200-3249-11eb-9336-8946ac1b86b7.png)

**Comment by jacogr** [comment]
How are you passing in the call? It is an `OpaqueCall`, so `Vec<u8>`, it you try to pass a Uint8Array, it won't work. (Unless properly encoded with length-prefix added)

**Comment by jacogr** [comment]
This line - https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/df/workshop/explore/scripts/init.js#L247

Use `call.method.toHex()` when passing it in, since it is an `OpaqueCall` you need to be explicit on what you need.

**Comment by danforbes** [comment]
Ah would explain the confusion here https://github.com/polkadot-js/api/issues/2878#issuecomment-735462621 :sweat_smile:
