### ISSUE TITLE
Transaction updated in the block before even getting finalised

### ISSUE THREAD

**Issue by JeremyConnor** [polkadot-js/api#2890]
![Screenshot from 2020-11-30 12-47-19](https://user-images.githubusercontent.com/73089748/100579576-745eee00-330a-11eb-9374-689abbebb174.png)
As you can see in the screen towards the left, it says in a block. The transaction should take few seconds to get finalised, but as soon as the transaction is initiated, I am able to see the transaction in the respective block (as can be seen in the UI). Due to this, my transaction does not get completed.

**Comment by jacogr** [comment]
The API only reports the status, as received from the pool. That actually means you can have "redacted" and "InBlock" before Finalization, see https://github.com/paritytech/substrate/blob/master/primitives/transaction-pool/src/pool.rs#L104-L127

Finalization generally is around 3 blocks behind the head, at least with Substrate defaults (and if grandpa is not stalled).

I most cases you would see InBlock followed by Finalization (3 blocks lag as above), however in some cases (depending on the network conditions and when the RPC node gets the status), you may only end up with Finalized. (Rare, but does happen on some node that are not well connected to the actual validator that includes the tx)

**Comment by JeremyConnor** [comment]
So, can this be a reason for the transaction not getting successful? If so, how can I solve it?

**Comment by jacogr** [comment]
How do you mean "not succesfull"? You have one of two options -

- listen for `InBlock`, this means that tx has been included (it could be redacted if the block is forked off and included elsewhere, so the blockHash may not be the final in the canonical chain)

- listen for `Finalized`, around 3 blocks behind, at this point it is on the final chain and cannot be reverted, included elsewhere

In both cases you would received the events and the hash of the block where included.

**Comment by JeremyConnor** [comment]
By ''not successful'' I meant that I checked the hash of the block where the transaction took place, but did not receive any such event. 
By 3 blocks behind, do you mean that, if the inBlock states Block 28, then I should check somewhere around block 25

**Comment by jacogr** [comment]
No, if the `InBlock` gets received at block 28, it means finalization would only happen around block 31. (So the new head would be at 31, however the finalized chain would be up to block 28). As a real example, here is Polkadot while writing this - 

![image](https://user-images.githubusercontent.com/1424473/100595893-cea48280-32fb-11eb-88d7-183e4b6a84ab.png)

The finalized chain lags by 3 blocks.

So if you listed for `Finalized` only, you can ensure it has been added and cannot disappear and re-appear in another block, although it would be slower since it would lag by 3 blocks.

**Comment by JeremyConnor** [comment]
> No, if the `InBlock` gets received at block 28, it means finalization would only happen around block 31. (So the new head would be at 31, however the finalized chain would be up to block 28). As a real example, here is Polkadot while writing this -
> 
> ![image](https://user-images.githubusercontent.com/1424473/100595893-cea48280-32fb-11eb-88d7-183e4b6a84ab.png)
> 
> The finalized chain lags by 3 blocks.
> 
> So if you listed for `Finalized` only, you can ensure it has been added and cannot disappear and re-appear in another block, although it would be slower since it would lag by 3 blocks.

Okay, I will then check in the finalized block and let you know.

**Comment by JeremyConnor** [comment]
I tried to initiate another transaction (at Block 64). This time, after the transaction was finalized, I checked all the blocks from 64 to 67, but none of them contained any information. For your reference, I am adding screenshot for block 64 and 67.
![Screenshot from 2020-12-01 16-58-59](https://user-images.githubusercontent.com/73089748/100735412-2b389800-33f7-11eb-8d89-68506cb88f8a.png)
![Screenshot from 2020-12-01 17-02-23](https://user-images.githubusercontent.com/73089748/100735350-165c0480-33f7-11eb-98ae-9d8c5fe0b66a.png)
![Screenshot from 2020-12-01 17-02-32](https://user-images.githubusercontent.com/73089748/100735355-178d3180-33f7-11eb-91bf-71424a1f91fe.png)

**Comment by jacogr** [comment]
The first block you listed has the contract call event success, so it was included there.

**Comment by JeremyConnor** [comment]
Yes, I know that. But, what can be the reason for no additional event getting emitted? Whenever I am trying to make a transaction, I am only getting ```ExtrinsicSuccess``` but no other event.

**Comment by jacogr** [comment]
All events for a specific transaction would be in the same block. The API will only decode what is in the event state, i.e. has been emitted. 

As to why a specific transaction doesn't emit anything is up to the runtime itself.

**Comment by jacogr** [comment]
For events, here is a working sample with a contract that emits events - https://github.com/jacogr/ink-sample-dns/

All-in-one.

**Comment by jacogr** [comment]
Closing.
