### ISSUE TITLE
Q:how to use the events api

### ISSUE THREAD

**Issue by Lawrencehh** [polkadot-js/api#2892]
For exmaple ,coult you give a concret example of call the "staking->EraPayout(EraIndex, Balance, Balance) events"?

**Comment by jacogr** [comment]
Here is an example traversing the eventrecord for a specific blockHash. https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

Obviously you could subscribe to the actual events, as per the storage API and retrieve that way.

**Comment by jacogr** [comment]
Closing, answered.
