### ISSUE TITLE
Q: Can the metadata abi of the contract code be verified?

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#2894]

**Comment by jacogr** [comment]
There is not verification function. However the `api-contract` ABI calss does do some sanity checks upon receiving it, which is basically this -

`assert(isObject(json) && !Array.isArray(json) && json.metadataVersion && isObject(json.spec) && !Array.isArray(json.spec) && Array.isArray(json.spec.constructors) && Array.isArray(json.spec.messages), 'Invalid JSON ABI structure supplied, expected a recent metadata version');`

But that is only a very high-level structure check.

**Comment by freehere107** [comment]
@jacogr Thank you for your reply
