### ISSUE TITLE
Question: How to pass additional parameters to blueprint.tx.new

### ISSUE THREAD

**Issue by remon-nashid** [polkadot-js/api#2898]
According to [Blueprint documentation](https://polkadot.js.org/docs/api-contract/start/blueprint), a contract can be instantiated as follows:

```
const unsub = await blueprint.tx
  .new(endowment, gasLimit, initValue)
```

Which brings me to a question: how can one pass additional parameters to the constructor? In our case, we need to pass `maxFee` besides endowment, gasLimit and initValue. Here's how `instantiate` extrinsic look. The goal is to pass `max_fee`. Note that `data` below is made of constructor's selector + the initial value (`02`).

I'm attaching the contract ABI for reference.

[metadata.txt](https://github.com/polkadot-js/api/files/5630155/metadata.txt)

<img width="1023" alt="Screen Shot 2020-12-02 at 6 56 54 AM" src="https://user-images.githubusercontent.com/1994818/100889367-e569e700-346b-11eb-9251-01dd49d3cfae.png">

**Comment by jacogr** [comment]
Where does maxFee come from? Don't see it as part of the constructor params?

**Comment by jacogr** [comment]
Ahhh, you have a changes `instantiate`. There is no way to currently cater for modified palette contracts interfaces in `api-contract`, it assumes and works with the default as per Substrate.

**Comment by remon-nashid** [comment]
Fair enough. I'll stick with `api.tx.contracts.instantiate()` then. Thanks @jacogr.
