### ISSUE TITLE
@polkadot/metadata package has undeclared dependency to @polkadot/api

### ISSUE THREAD

**Issue by APshenkin** [polkadot-js/api#2904]
https://github.com/polkadot-js/api/blob/master/packages/metadata/src/decorate/types.ts#L4

This dependency is missing in @polkadot/metadata package.json.

Also if you take a look on export from @polkadot/api 
https://github.com/polkadot-js/api/blob/master/packages/api/src/types/consts.ts

You can see that there is no `QueryableConsts` dependency.

This dependency can be found here https://github.com/polkadot-js/api/blob/master/packages/api/src/augment/consts.ts#L429 that redeclare `@polkadot/api/types/consts` module (what??? is that legal?? :))

And all works only if you `import @polkadot/api` in your application.

**Comment by jacogr** [comment]
Yes, it is legal - it is used for augmenting the API with user-defined types. So basically when you do that it stacks them on-top of each other. Quite  weird TS thing, but actually comes in quite helpful.

As for this specific circular dep, yes it is known, have not yet found a way to consistently (without mess/fuss) remove metadata <-> api. (There are a handful of those left at this point)
