### ISSUE TITLE
When node start with "manual_seal" feature, the api would cause "bad signature" when sand 7th extrinsic.

### ISSUE THREAD

**Issue by atenjin** [polkadot-js/api#2909]
## When node start with "manual_seal" feature, the api would cause "bad signature" when sand 7th extrinsic.

Like in substrate official tutorial, build and run a node from the repo [recipes](https://github.com/substrate-developer-hub/recipes.git)

and do like following thing:
1. modify "recipes/nodes/kitchen-node/Cargo.toml" file, using "weight-fee-runtime" instead of "super-runtime" (in line 60 and 63)
2. build and run with command `./target/debug/kitchen-node --dev --tmp`
3. then, use the following script to test:
```javascript
const { Keyring } = require('@polkadot/keyring');
const { ApiPromise, WsProvider } = require('@polkadot/api');

const BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';

async function main () {
    const provider = new WsProvider('ws://127.0.0.1:9944');
    const api = await ApiPromise.create({ provider, types: {
        "Address": "AccountId",
        "LookupSource": "AccountId"
      } });
    
    const keyring = new Keyring({ type: 'sr25519' });
    const alice = keyring.addFromUri('//Alice');

    // loop 6 times
    for (i = 0; i < 6; i++) {
        const transfer = api.tx.balances.transfer(BOB, 12345);
        const hash = await transfer.signAndSend(alice);
        console.log('Transfer sent with hash', hash.toHex());
        await new Promise(r => setTimeout(r, 1000));
    }    
    // this request would return bad signture
    const transfer = api.tx.balances.transfer(BOB, 12345);
    const hash = await transfer.signAndSend(alice);
    console.log('Transfer sent with hash', hash.toHex());
  };

main().catch(console.error).finally(() => process.exit());
```

In this script, we send **6 times normal extrinics before**, and then, send another extrinic would meet this error **`Transaction has a bad signature`**:
```bash
2020-12-03 16:07:08        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
Error: 1010: Invalid Transaction: Transaction has a bad signature
    at RpcCoder._checkError (/home/king/workspace/projects/ts/polkadotapi/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/home/king/workspace/projects/ts/polkadotapi/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at WsProvider.value (/home/king/workspace/projects/ts/polkadotapi/node_modules/@polkadot/rpc-provider/ws/index.js:212:90)
 # ...
```

We look in details, think this error is related to `era` when construct an extrinic. However, in substrate extrinics check, the "bad signature" error is later then `era` check

`primitives/runtime/src/generic/unchecked_extrinsic.rs:L130`
```rust
				let signed = lookup.lookup(signed)?;
				let raw_payload = SignedPayload::new(self.function, extra)?;  // check nonce, era and etc...
				if !raw_payload.using_encoded(|payload| signature.verify(payload, &signed)) {
					return Err(InvalidTransaction::BadProof.into()) // "bad signature" is from here
				}
```
Thus, the `era` is valid, but the signature is not valid. So we think the signature process maybe sign a thing which not the source. (Just I guess)

And another thing may be related to this case is in "manual_seal" node, the `MinimumPeriod` set to 1 milliseconds:
```rust
parameter_types! {
	pub const MinimumPeriod: u64 = 1;
}
impl timestamp::Trait for Runtime {
	/// A timestamp: milliseconds since the unix epoch.
	type Moment = u64;
	type OnTimestampSet = ();
	type MinimumPeriod = MinimumPeriod;
	type WeightInfo = ();
}
```
But I'm not sure this thing.

**Comment by atenjin** [comment]
This error can pass to UI, like Substrate Portal or  substrate-front-end-template or something else.
Thus this issue related to https://github.com/polkadot-js/apps/issues/4145

**Comment by jacogr** [comment]
You are spot-on that is is the MinimumPeriod. So by default (unless an override is provided i terms of number of locks), the API will attempt to make the mortal period 5 minutes. However with a 1ms period, this ends up with > 250 blocks (which is the max allowed for an era).

**Comment by atenjin** [comment]
But for "manual_seal" node, there no need for `MinimumPeriod`, for "manual_seal" just produce a block when receive extrinsic. And `MinimumPeriod` may effect the bock interval( like if I set 6s as `MinimumPeriod`, the last block could not  precede next block the within 6 seconds ( I'm not sure, I would check this later, It seems that there is a check in `pallet-timestamp`). )
The purpose for "manual_seal" is used in un-limited producing block, like package a block in a very sort time and accelerate tests or other cases. Thus I think `MinimumPeriod` set to 1 milliseconds should be allowed.

Thanks @jacogr
