### ISSUE TITLE
Calling addSignature errors out

### ISSUE THREAD

**Issue by geastwood** [polkadot-js/api#2911]
## Error message
```
REGISTRY: [Error: Cannot map Enum JSON, unable to find '010ae36681df50970a22ce55defe0775b3772bf05b08e6106954b42b5717ef082200a5445357ec345f7ec50151c4c41fb6fc432bef0461a19f5bc0efb1dc1c0f8c' in ed25519, sr25519, ecdsa]
```

## Context
Currently packing the tx signing payload into a QR code and using parity signer to sign the transaction. Parity signer is able to recognize the QR payload and deliver back a signature which looks like the following. And I'm using the `data` field.

However getting constantly the error msg. It would be helpful that anyone could provide me any direction to dig further.

```
{
   "bounds":{
      "origin":{
         "x":"25.452043",
         "y":"37.084819"
      },
      "size":{
         "height":"133.498951",
         "width":"135.724164"
      }
   },
   "data":"017acb926608839c110332f59c3761ce6caa01785b4ccca2691a3677555229066ad8f7d501995b3e1ea3b40978b0f163a08cdb13326e8a64f08d32a88fc9c5a989",
   "rawData":"482303137616362393236363038383339633131303333326635396333373631636536636161303137383562346363636132363931613336373735353532323930363661643866376435303139393562336531656133623430393738623066313633613038636462313333323665386136346630386433326138386663396335613938390ec11ec11ec11ec11ec11ec11ec11ec11ec11ec11ec11",
   "target":3929,
   "type":"org.iso.QRCode"
}
```

**Comment by jacogr** [comment]
All hex should have a 0x prefix. The signer returns it without. Add it before trying to addSignature.

**Comment by geastwood** [comment]
Thank for the quick reply.

However got a different error when trying to submit the tx :)

```
RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
```

Does this mean the original tx payload I give to signer to sign to badly constructed?

**Comment by jacogr** [comment]
It does mean the signature is invalid. Generally that would happen when the data passed to the signer was missing something. 

I do recall there was some magic that is applied specifically to create the data for the Parity Signer in the apps UI, let me find the link to that as a comparison here.

**Comment by jacogr** [comment]
Here is where the apps UI constructs the actual data (it is a hook into the API signer, hence implementing the signing interface) - https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/signers/QrSigner.ts#L18-L34

The `.toU8a()` for the data does look innocent enough. 

(The hashing is for large payloads,i.e. for something like  chain upgrade, opted to not display all the frames - so very large txs would only sign the hash, which is non-optimal user-wise, no details are shown on the signer)

**Comment by geastwood** [comment]
Actually I have already port some of the relevant code over, seems somewhere is a bit off.
```
export function createFrames(input: Uint8Array): Uint8Array[] {
  const frames = [];
  let idx = 0;

  while (idx < input.length) {
    frames.push(input.subarray(idx, idx + FRAME_SIZE));

    idx += FRAME_SIZE;
  }

  return frames.map(
    (frame, index: number): Uint8Array =>
      u8aConcat(
        MULTIPART,
        encodeNumber(frames.length),
        encodeNumber(index),
        frame,
      ),
  );
}

export function createSignPayload(
  address: string,
  cmd: number,
  payload: string | Uint8Array,
  genesisHash: string | Uint8Array,
): Uint8Array {
  return u8aConcat(
    SUBSTRATE_ID,
    CRYPTO_SR25519,
    new Uint8Array([cmd]),
    decodeAddress(address),
    u8aToU8a(payload),
    u8aToU8a(genesisHash),
  );
}

export const toSignPayload = (payload: SignerPayloadJSON) => {
  // limit size of the transaction
  const isQrHashed = payload.method.length > 5000;
  const wrapper: ExtrinsicPayload = registry.createType(
    'ExtrinsicPayload',
    payload,
    {
      version: payload.version,
    },
  );

  const qrPayload = isQrHashed
    ? blake2AsU8a(wrapper.toU8a(true))
    : wrapper.toU8a(true);

  return {
    isQrHashed,
    qrAddress: payload.address,
    qrPayload,
  };
};
```

And here is how I prepare the tx

```
    const [section, method] = this.#tx.split('.');

    if (!get(this.api.tx, [section, method])) {
      throw new Error(`Unable to find method ${section}.${method}`);
    }

    if (!this.#blocks && this.#blocks !== 0) {
      this.#blocks = 50;
    }

    if (!this.#nonce && this.#nonce !== 0) {
      this.#nonce = (
        await this.api.derive.balances.account(this.address)
      ).accountNonce;
    }

    let options: SignerOptions;
    let blockNumber: Compact<BlockNumber> | number | null = null;

    if (this.#blocks === 0) {
      options = {
        blockHash: this.api.genesisHash,
        era: 0,
        nonce: this.#nonce,
      };
      blockNumber = 0;
    } else {
      // Get current block if we want to modify the number of blocks we have to sign
      const signedBlock = await this.api.rpc.chain.getBlock();

      options = {
        blockHash: signedBlock.block.header.hash,
        era: this.api.createType('ExtrinsicEra', {
          current: signedBlock.block.header.number,
          period: this.#blocks,
        }),
        nonce: this.#nonce,
      };
      blockNumber = signedBlock.block.header.number;
    }

    const transaction: SubmittableExtrinsic<'promise'> = this.api.tx[section][
      method
    ](...this.#params);

    const payload: SignerPayload = this.api.createType('SignerPayload', {
      genesisHash: this.api.genesisHash,
      runtimeVersion: this.api.runtimeVersion,
      version: this.api.extrinsicVersion,
      ...options,
      address: this.address,
      blockNumber,
      method: transaction.method,
    });

    // const signature = await getSignature(payload.toRaw().data);

    // transaction.addSignature(address, signature, payload.toPayload());
    return {payload, transaction};
```

**Comment by geastwood** [comment]
The tx Api promise is correctly constructed, I guess the issue lays really in the Qr payload generation.

**Comment by jacogr** [comment]
Since you are construction manually, you are missing the transactionVersion field in the payload.

**Comment by geastwood** [comment]
Here is how I create the QR payload

```
  const {isQrHashed, qrPayload, qrAddress} = toSignPayload(payload);
  // ----

  console.log(
    'createSignPayload',
    qrAddress,
    isQrHashed ? CMD_HASH : CMD_MORTAL,
    qrPayload,
    genesisHash,
  );
  // createSignPayload
  // 5FFZDYwMTMn5Lz8YX5wPacVuHYnSyU3etxZwL5k1FfDs8mwG
  // 2
  // [60, 28, 1, 0, 5, 116, 101, 115, 116, 0, 0, 0, 0, 0, 0, 0, 229, 2, 40, 0, 26, 0, 0, 0, 170, 248, 252, 234, 143, 59, 94, 2, 89, 45, 75, 48, 84, 181, 161, 53, 144, 252, 215, 137, 102, 238, 112, 84, 128, 88, 13, 20, 30, 58, 15, 27, 98, 192, 226, 151, 110, 160, 116, 229, 67, 71, 3, 95, 155, 214, 236, 47, 17, 84, 151, 229, 255, 181, 106, 200, 24, 132, 131, 191, 203, 61, 22, 169]
  // "0xaaf8fcea8f3b5e02592d4b3054b5a13590fcd78966ee705480580d141e3a0f1b"

  // this to create frames
  const signPayload = createSignPayload(
    qrAddress,
    isQrHashed ? CMD_HASH : CMD_MORTAL,
    qrPayload,
    genesisHash,
  );

  useEffect(() => {
    const frames = createFrames(signPayload);

    const qr = QrCode(0, 'M');

    qr.addData(frames[0] as any, 'Byte');
    qr.make();

    setImageUri(qr.createDataURL(16, 0));
  }, [signPayload]);
```

**Comment by jacogr** [comment]
So to not worry about the actual `SignerPayload` itself, the simplest is actually to hook in a signer (like the class I linked above) and then just call -

`transaction.signAsync(<from>, { era, nonce, signer: new Signer() })` and it will call into that which can then call `getSignature`. The only difference is that hooking in the signer like this ensures that the payload received is always 100%.

(Instead of duplicating what the API does)

**Comment by geastwood** [comment]
Sounds good, thanks man for the help.

**Comment by geastwood** [comment]
Removed the manual construction of the payload. Using the `SignerPayloadJson` from `Signer` interface to construct the qr payload, However still get the bad signature error

```
RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
```

How can I learn more about this error message, like we can I debug this.

**Comment by geastwood** [comment]
I have done some further investigation and find something rather interesting.

I copied the raw qrCodePayload (Uint8Array) generated from polkadot.js web app and manage to generate the exact same QR code. And interact both on web and in app, the web ends up being successful, however the app keep telling me `bad signature`.

Both cases I use the same account to test, potential difference could be when I initiate the client, it's possible I didn't configure client setting correctly, e.g. get chain properties etc. 

Would this be possible? @jacogr

**Comment by geastwood** [comment]
Another direction is whether it has something todo with `keyring.loadAll`. I'm working under RN environment.

**Comment by jacogr** [comment]
After your updates, can you show me the "generation" part and the "QR construction" part (I assume this hasn't changed) again?

It is not keyring related, it is like some of the data doesn't get signed, so the node cannot reconstruct the signature. These are never easy to locate (as you've noticed since the payload is variable), but will get where it goes wrong. The code as-is would help to play.

**Comment by jacogr** [comment]
The reason for wanting  look above, is the following -

```js
const qrPayload = isQrHashed
    ? blake2AsU8a(wrapper.toU8a(true))
    // for the Parity Signer, this is cincorrect - it expects the length prefix on the payload (to be able to decode)
    // (the flag should be removed, with it passed, it will see the first 2 bytes are the non-existent length prefix)
    : wrapper.toU8a(true);
```

**Comment by geastwood** [comment]
> After your updates, can you show me the "generation" part and the "QR construction" part (I assume this hasn't changed) again. The code as-is would help to play.
> 
> Additionally, on the Parity Signer, does it actually display the details correctly? (compared to apps) Are you signing via the Parity signer or via your own app, i.e. RN app that reads the QR and generates a signature?
> 
> It is not keyring related, it is like some of the data doesn't get signed, so the node cannot reconstruct the signature. These are never easy to locate (as you've noticed since the payload is variable), but will get where it goes wrong.

I got rid of the manual construction of the payload, and it looks like this now:

```
      const transaction: SubmittableExtrinsic<'promise'> = api.tx[section][
        method
      ](...params);
      const f = await transaction.signAsync(address, {
        nonce: -1,
        tip: BN_ZERO,
        signer: new QrSigner((payload) => {
          setSignerPayload(payload);
          setStep('payload');
          return new Promise((resolve, reject) => {
            signatureRef.current = resolve;
          });
        }),
      });
      console.log('sending', transaction.toHex());
      await f.send();
```

And after I get the `SignerPayloadJson`,  I created `ExtrinsicPayload` and go though the `createPayload` and `createFrames` step.

The app I'm currently doing currently only support getting the signature from Parity Signer. I scan the signature from it and call `signAndSend` basically.

**Comment by geastwood** [comment]
The raw transaction after I called `api.tx.identity.setIdentity` is like

```
{
    "isSigned": false,
    "method": {
        "args": [
            {
                "additional": [],
                "display": {
                    "Raw": "test"
                },
                "legal": {
                    "None": null
                },
                "web": {
                    "None": null
                },
                "riot": {
                    "None": null
                },
                "email": {
                    "None": null
                },
                "pgpFingerprint": null,
                "image": {
                    "None": null
                },
                "twitter": {
                    "None": null
                }
            }
        ],
        "method": "setIdentity",
        "section": "identity"
    }
}
```

This is apparently different than on the polkadot.js app, also only after the QR code is generated

```
{
    "isSigned": true,
    "method": {
        "args": [
            {
                "additional": [],
                "display": {
                    "Raw": "test"
                },
                "legal": {
                    "None": null
                },
                "web": {
                    "None": null
                },
                "riot": {
                    "None": null
                },
                "email": {
                    "None": null
                },
                "pgpFingerprint": null,
                "image": {
                    "None": null
                },
                "twitter": {
                    "None": null
                }
            }
        ],
        "method": "setIdentity",
        "section": "identity"
    },
    "era": {
        "MortalEra": {
            "period": "64",
            "phase": "29"
        }
    },
    "nonce": "20",
    "signature": "0x42424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242",
    "signer": "5FFZDYwMTMn5Lz8YX5wPacVuHYnSyU3etxZwL5k1FfDs8mwG",
    "tip": "0"
}
```
It seems some steps I have been missing.

**Comment by jacogr** [comment]
Have you made the adjustment above removing the „true“ from the generation of the data before passing to the QR?

**Comment by geastwood** [comment]
> Have you made the adjustment above removing the „true“ from the generation of the data before passing to the QR?

Yeh, I did. Didn't help.

**Comment by geastwood** [comment]
```
{
    "isSigned": true,
    "method": {
        "args": [
            {
                "additional": [],
                "display": {
                    "Raw": "test"
                },
                "legal": {
                    "None": null
                },
                "web": {
                    "None": null
                },
                "riot": {
                    "None": null
                },
                "email": {
                    "None": null
                },
                "pgpFingerprint": null,
                "image": {
                    "None": null
                },
                "twitter": {
                    "None": null
                }
            }
        ],
        "method": "setIdentity",
        "section": "identity"
    },
    "era": {
        "MortalEra": {
            "period": "64",
            "phase": "29"
        }
    },
    "nonce": "20",
    "signature": "0x42424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242",
    "signer": "5FFZDYwMTMn5Lz8YX5wPacVuHYnSyU3etxZwL5k1FfDs8mwG",
    "tip": "0"
}
```
This is the `tx.toHuman()` output from the polkadot.js webapp only at the step on showing QR (Before signing), I think I miss a step to make my `tx` to be like this above.

**Comment by jacogr** [comment]
What does the signer do with - `setSignerPayload(payload);` - does it convert it into an ExtrinsicPayload? (and then with the raw bytes display the QR - these are quite tricky since the QR needs the raw bytes)

So when the transaction is incorrectly encoded, the error is slightly different. In this case it seems to be the signer that signs the incorrect data - so the transaction is constructed the right way, however the attached signature doesn't match on that content. 

(The signer used to decode the transaction, now at least for me it doesn't, aka the metadata is outdated, which is quite frustrating to try and debug these)

**Comment by geastwood** [comment]
After `setSignerPayload` it will go through the following code

```
  const isQrHashed = payload.method.length > 5000;
  const wrapper: ExtrinsicPayload = registry.createType(
    'ExtrinsicPayload',
    payload,
    {
      version: payload.version,
    },
  );

  // isQrHashed is `false`
  const qrPayload = isQrHashed
    ? blake2AsU8a(wrapper.toU8a(true))
    : wrapper.toU8a();

  const signPayload = createSignPayload(
    payload.address,
    isQrHashed ? CMD_HASH : CMD_MORTAL,
    qrPayload,
    payload.genesisHash,
  );

  useEffect(() => {
    const frames = createFrames(signPayload);
    const qr = QrCode(0, 'M');

    qr.addData(frames[0] as any, 'Byte');
    qr.make();

    setImageUri(qr.createDataURL(16, 0));
  }, [signPayload]);
```

**Comment by geastwood** [comment]
> (The signer used to decode the transaction, now at least for me it doesn't, aka the metadata is outdated, which is quite frustrating to try and debug these)

What do you mean here? I know the Parity signer seems to lack the capability to update metadata. However Parity Signer works with the polkadot.js app well (i.e. it can sign tx and generated QR code can make the tx go through)

**Comment by jacogr** [comment]
It used to display the actual transaction broken down into the parts, i.e. you could see what you are signing. Now it signs perfectly, but it is basically an unknown blob.

**Comment by geastwood** [comment]
Well, guess I have to dig into the signer and debug what is actually got signed.

**Comment by jacogr** [comment]
Since you are on RN, this thread may be of use - https://github.com/polkadot-js/apps/issues/2906 (discrepancies between what the signer expects and what is easy to generate and read in that environment)

**Comment by geastwood** [comment]
I dig in to Parity signer and everything seems to be already. 
This is the output right before it outputs a QR code:
```
{
   "action":"signTransaction",
   "data":{
      "account":"14tXVfMUCVv1Uj8kUWUK6VyC8Mw8nRcjA67WCsBHJGoogu8",
      "crypto":"sr25519",
      "data":[
         140,
         ...omitting,
         63
      ],
      "genesisHash":"0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
   },
   "isHash":false,
   "oversized":false
}

----
This is the signing payload

```
{
    "method": "0x050046cf11d7dd705e146b0fa89d0d75561ceac5b29fc9900a57762671645784850a04",
    "era": {
        "MortalEra": {
            "period": "64",
            "phase": "1"
        }
    },
    "nonce": "1",
    "tip": "0",
    "specVersion": "26",
    "genesisHash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
    "blockHash": "0x5b756173175580346a50d9f2963cee733d29940efa2f81b719d5ddb9289e203f"
}
```


And the `rawPayload` is `[140, ...omitting, 63]` which matches the one I got from Parity signer.

**Comment by jacogr** [comment]
The payload there seems sane, i.e. the 140 is an indicator for 35 bytes total for the actual call.

Do you have the most recent version of the signer? (Assuming so since it does seem to work with apps).

Atm, I have no idea.

**Comment by jacogr** [comment]
To see what is to blame, this may help (typing without having tested) -

1. Inside the signer, do the following -

```js
signPayload (payload) {
  const ep = registry.createType('ExtrinsicPayload', payload.toPayload());
  const sig = await getSignature(payload);

  console.log('p', u8aToHex(ep.toU8a(true), 's', u8aToHex(sig));

  return { id: 0, signature: signature );
}
```

So basically here we have the payload as to be signed along with the signature generated - with this and the account can verify it in apps under the developer tools (verify).

(Additionally can actually, since I'm assuming you do have the seed, actually sign it in there as well  (as a shortcut, i.e. signing with the pair, no QR should also work) - although, unless ed25519 (which the Signer is not), you cannot just compare the sig, but you can see if they are verifyable. (sr25519 yields non-deterministic sigs)

**Comment by jacogr** [comment]
Here is a minimal woking sample - https://github.com/jacogr/sample-signer-qr

**Comment by geastwood** [comment]
Thanks a bunch @jacogr for the effort spent to identify the root cause. 

After quite some try and error and have identified the problem, It's actually lies in the creation of `ExtrinsicPayload`.


```
registry.createType('ExtrinsicPayload', payload.toPayload())

api.registry.createType('ExtrinsicPayload', payload.toPayload())
^^^
```

Basically replace registry with api.registry made it work. 

Would you explain me a bit what's the difference between this two?

**Comment by jacogr** [comment]
The API registry is the one actually decorated with the signedExtensions and all recent types. So the way to access a registry -

- on the api itself (these actually get swapped depending on specVersion)
- on any type (hence using tx.registry in my sample) - this is the latest registry used to create the type

You should really never create these standalone - the apps UI does, but that is just due to historic reasons, there are still a couple of low-impact areas left where it was not done properly. (It comes from the age before isolated types, so it used to have everything global - so it still have some warts and holes)
