### ISSUE TITLE
how to subscribe pending tx

### ISSUE THREAD

**Issue by heipacker** [polkadot-js/api#2921]

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/substrate/rpc#pendingextrinsics-vecextrinsic

**Comment by heipacker** [comment]
i know this is an RPC request. and i need to poll by myself. Is there any subscription mode

**Comment by jacogr** [comment]
There is no pending subscription RPC exposed on Substrate.

**Comment by jacogr** [comment]
Closing.
