### ISSUE TITLE
query node info?

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2924]
hi

is there any api that query node infos which are not deprecated?

**Comment by jacogr** [comment]
What query are your referring to?

**Comment by puffanddmx** [comment]
i wanna query all node infos which act as a validator

**Comment by jacogr** [comment]
So which call are you referring to? Please be explicit so I can help.

**Comment by puffanddmx** [comment]
api.rpc.system.peers

**Comment by jacogr** [comment]
You need to explicitly expose that on the RPC node you are running - it is deemed as an unsafe RPC by substrate. So on your RPC node, you can use the `--unsafe-rpc` flags if you want to expose it.

**Comment by puffanddmx** [comment]
thanks!

Let's ask one more question.
I am trying to test erc721 using ink, but if there is no money in the contract address, the function cannot be executed. If you don't want to charge consumers that money is consumed every time, if you set the ink pallet wherever, can the function run infinitely without depositing money into the contract? For example, to enable the mint function indefinitely....

**Comment by jacogr** [comment]
I would suggest to refer that question into one of the ink! and/or substrate-tech channels - I honestly don't configure runtimes, only interact with what hey expose.

**Comment by puffanddmx** [comment]
After executing node in the --unsafe-rpc-external state, the function is executed, but the result cannot be received.
api.rpc.system.peers
