### ISSUE TITLE
Support derive injection via typesBundle (as RPC)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#2930]
- In the same vein as https://github.com/polkadot-js/api/pull/2927
- See background at https://github.com/polkadot-js/apps/pull/4171#issuecomment-740948438

**Comment by pr0fedt** [comment]
Would this suffice or should I also expose function like _getSpecDerives_ in _packages/types-known_ package?

**Comment by jacogr** [comment]
Don't believe we need to expose the `getSpecDerives` at all - I think what you have there fits the bill.

**Comment by jacogr** [comment]
Closed in #2932 - thank you very much!
