### ISSUE TITLE
Polkadot App js UI - "waiting to make a connection to the remote endpoint and finishing API initialization"

### ISSUE THREAD

**Issue by Tassz44** [polkadot-js/api#2935]
I am following the tutorial _Use the Sudo Pallet_ 
Built & run the upgraded runtime - **cargo +nightly-2020-10-06 run --release -- --dev --tmp**. 
Connected to Polkadot JS Apps - **https://polkadot.js.org/apps/#/extrinsics?rpc=ws://127.0.0.1:9944**. 

I am now receive an errors (_initializing connection - waiting to make a connection_) - and page does not load correctly.

![Untitled](https://user-images.githubusercontent.com/72080913/101621278-76f9cb80-3a0d-11eb-8102-82338eb44aaf.jpg)

Would like to know why this is happen?

**Comment by jacogr** [comment]
It means it cannot connect. The browser cannot make  a connection to the node. What does your dev console say? (Any error outputs?)

**Comment by Tassz44** [comment]
This is the error I receive: 

![Untitled](https://user-images.githubusercontent.com/72080913/101623447-5e3ee500-3a10-11eb-825f-5fc3c4c5ee82.jpg)

**Comment by Tassz44** [comment]
![Untitled](https://user-images.githubusercontent.com/72080913/101624092-56337500-3a11-11eb-9fcc-9b136b598f27.jpg)

**Comment by Tassz44** [comment]
I am receive the same issue when I open Canvas-UII 
{e.g. if I select _local node_ receive error _You are not connected to a node.
Ensure that your node is running and that your Websocket endpoint is reachable_.}
I have recently upgraded FRAME runtime (sudo pallet - RuntimeVersion struct from  spec_version: 1 to spec_version: 2..

Could this be a cause?

**Comment by jacogr** [comment]
There is sadly no additional info in those messages, as per RFC the WS connection failures don't return any useful info, apart from "I can't do it". Honestly don't have a workaround for this, but have heard some reports of FF sporadically doing this lately.

**Comment by Tassz44** [comment]
Thanks...

It was working Ok,, until I 'upgrade my chain'. I will continue to research this issue..

**Comment by jacogr** [comment]
So the reports I've heard (one only, Mac OS, latest FF), was that in some cases it starts happening where it cannot connect. (Only happens when running the polkadot binary locally with a `--dev` chain, and sometimes just works, other times doesn't)

Is there only one process running on your machine? (no zombies from an unclean shutdown?)

**Comment by Tassz44** [comment]
Yes I am only running one process on Windows OS...
