### ISSUE TITLE
Having issues querying a storage state with Option

### ISSUE THREAD

**Issue by a1zyx** [polkadot-js/api#2939]
How do I use the `api.query.<module>.<method>` pattern to query a storage item without sending in any arguments if the arguments are `Option<Type>`? Sending in nothing will throw an error like `<module>.<method>(<arg>) is a map, requiring 1 argument, 0 found`. 

I've checked that it works on https://polkadot.js.org/apps/#/chainstate and that there's a toggle to disable the sending of Optional arguments. How would that look directly against the `ApiPromise`?

**Comment by jacogr** [comment]
For `None`, just pass `null`

**Comment by a1zyx** [comment]
Thanks for the reply @jacogr. `null` doesn't work. It's from a custom pallet so maybe I need to register it? From the api docs, I've read that you can register custom types and rpcs, is it possible to do the same for storage methods?

**Comment by jacogr** [comment]
Ok, you will need to show me the query. If you want to do queries for entries, the format is different, see - https://polkadot.js.org/docs/api/start/api.query.other#map-keys--entries

**Comment by a1zyx** [comment]
Ah spot on. Just tried it and that was exactly what I needed. So basically a way to get the entire collection is to get the keys first `api.query.<module>.<method>.keys()` or `.entries()` and then with the keys I can get my storage items.

Thanks a lot, really appreciate it.
