### ISSUE TITLE
system.ExtrinsicFailed

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#2941]
If you search the block information api below, you can see extrinsics information. However, it seems that through extrinsics information, it is not possible to see whether the corresponding extrinsics succeed/fail. Regardless of success/failure, it looks like success, so ask if there is a way to check this part with api call. (system.ExtrinsicFailed check)

api.rpc.chain.getBlockHash
api.derive.chain.getHeader

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events
