### ISSUE TITLE
No subscribeStorage when provider doesn't support subscription

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#2949]
Currently when httpProvider is used, 
1. `api.query.<module>.<storage>` don't have `.multi()`
2. `api.queryMulti()` will fail
3. all derive queries that depend on multi() or queryMulti will fail.

The reason mentioned in the code comment says `rpc.getStorage` doesn't support multi keys while `rpc.subscribeStorage` supports. But it was out of date because `rpc.queryStorageAt` can be used as the equvalence of `rpc.subscribeStorage`  for httpProvider.

**Comment by jacogr** [comment]
It should be disabled completely. It is not supported.
