### ISSUE TITLE
@polkador/metadata build error: no exported member 'QueryableConsts'

### ISSUE THREAD

**Issue by dzhelezov** [polkadot-js/api#2970]
Trying to build a project with `@polkadot/api` and `@polkadot/metadata` dependencies.
Get a build error:
```
node_modules/@polkadot/metadata/decorate/types.d.ts:1:31 - error TS2305: Module '"../../api/types/consts"' has no exported member 'QueryableConsts'.

1 import type { AugmentedConst, QueryableConsts, QueryableModuleConsts } from '@polkadot/api/types/consts';
```

Here's `package.json` deps:
```
"dependencies": {
    "@oclif/command": "^1.8.0",
    "@polkadot/api": "~2.10.1",
    "@polkadot/typegen": "~2.10.1",
    "handlebars": "^4.7.6"
  }
```

Seems like indeed `@polkadot/metadata` [tries to import](https://github.com/polkadot-js/api/blob/9ee563e3f6abc63bf815a8c8cb13be1f07a533f1/packages/metadata/src/decorate/types.ts#L4) a missing `QueryableConsts`

**Comment by jacogr** [comment]
This is the generated output from the API as build right now for `decorate/types.d.ts` -

```js
import type { AugmentedConst, QueryableConsts, QueryableModuleConsts } from '@polkadot/api/types/consts';
import type { StorageEntry } from '@polkadot/types/primitive/types';
import type { Codec, ModulesWithCalls } from '@polkadot/types/types';
export interface ModuleStorage {
    [key: string]: StorageEntry;
}
export declare type Constants = QueryableConsts<'rxjs'>;
export declare type ConstantCodec = Codec & AugmentedConst<'rxjs'>;
export declare type ModuleConstants = QueryableModuleConsts;
export interface Storage {
    [key: string]: ModuleStorage;
    substrate: ModuleStorage;
}
export interface DecoratedMeta {
    consts: Constants;
    query: Storage;
    tx: ModulesWithCalls;
}
```

There is no `../../api/types/consts` import.

**Comment by dzhelezov** [comment]
Probably this build error is specific to tsc. Here's my `tsconfig.json`
```
{
    "compilerOptions": {
        "declaration": true,
        "importHelpers": true,
        "module": "commonjs",
        "outDir": "lib",
        "rootDirs": [
            "./src"
        ],
        "strict": true,
        "target": "es2017",
        "noImplicitAny": false,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "types": [ "node", "mocha" ]
    },
    "include": ["./src/**/*"]
  }
```
Build script:
```
rm -rf lib && tsc --build tsconfig.json
```
To reproduce, just create `src/index.ts` and import 'Metadata':
```
import { Metadata } from '@polkadot/metadata'
```

**Comment by dzhelezov** [comment]
> import type { AugmentedConst, QueryableConsts, QueryableModuleConsts } from '@polkadot/api/types/consts';
> 
> There is no `../../api/types/consts` import.

I think the problem is in the import itself. There's no exported `QueryableConsts` in '@polkadot/api/types/consts' at least in the current [master](https://github.com/polkadot-js/api/blob/9ee563e3f6abc63bf815a8c8cb13be1f07a533f1/packages/metadata/src/decorate/types.ts#L4)

**Comment by jacogr** [comment]
It is augmented.

https://github.com/jacogr/sample-metadata

Created via -

1. `mkdir -p sample-metadata`
2. `cd sample-metadata`
3. `yarn init`
4. `yarn add @polkadot/api`
5. `yarn tsc --init`
6. Added `index.ts` file
7. build via (index.js file in the repo as well) `yarn tsc --build`

**Comment by dzhelezov** [comment]
OK thanks! I think this issue is a dupe of this one https://github.com/polkadot-js/api/issues/2904

**Comment by jacogr** [comment]
Ahhh, the "use metadata on it's own" - actually do have a branch that fixed the remaining refs, didn't make it into 3.1 (still needs some testing),
