### ISSUE TITLE
Storage function erasValidatorReward doesn't support observable

### ISSUE THREAD

**Issue by x88** [polkadot-js/api#2979]
The function `erasValidatorReward` always returns empty value, when I using queries with`.at` iteration (for any eras, from older to earliest).  Our polkadot node woking in archive mode.  
```javascript
 const totalReward = polkadotConnector.query.staking.erasValidatorReward.at(blockHash, blockEra)
 ```
 There is [full code listing](https://github.com/p2p-org/polkadot-profit-transformer/blob/feat/milestone-staging/streamer/src/services/validators.js#L209).
 
 This execution working correctly, but we need to extract data, older than history_depth limit.
 ```javascript
 const totalReward = polkadotConnector.query.staking.erasValidatorReward(blockEra)
 ```

**Comment by jacogr** [comment]
See for instance -

```js
const value = await api.query.staking. erasValidatorReward.at('0x0c3c7de0cfeb6f0f45b9f6356fdb173a408415d2ec9c446569a4bdc9cf641e0a', 129);

console.log(value.toHuman())
```

(that is at block 1950117, e.g. where a payout was known to be made https://polkascan.io/polkadot/event/1950117-1)
