### ISSUE TITLE
transaction state

### ISSUE THREAD

**Issue by lijianl** [polkadot-js/api#2982]
is there any API to query the transaction state?  success or failure.

**Comment by jacogr** [comment]
Each transaction will have either `system.ExtrinsicSuccess` or `system.ExtrinsicFailure` events.

Via `signAndSend` - https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event (that shows the mapping from the dispatchError that is available)

Via block + event mapping - https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by lijianl** [comment]
thank you, I am trying.

**Comment by jacogr** [comment]
Closing.
