### ISSUE TITLE
Fix EthTransaction error

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#2995]
<img width="542" alt="Screenshot 2020-12-28 at 11 17 37" src="https://user-images.githubusercontent.com/16758383/103213693-baf63700-490e-11eb-97ca-34e635d8102b.png">

how do I test the api? is there a script to use local api package in the app in the same fashion as extension?

**Comment by jacogr** [comment]
Yes, you can copy the api to the local apps instance via `yarn polkadot-dev-copy-to apps`

**Comment by joelamouche** [comment]
thanks ! It looks like condition was removed from the Transaction type in Frontier

**Comment by jacogr** [comment]
Ok, so if it is removed, it obviously needs adjustment.

The only question is if it is on live chains - if not, just replace. If so, move the old to a versioned name and then replace. Generally with the "still up in the air" palettes, don't worry too much about keeping old, but in this case if needed for e.g. Moonbeam (2 versions out in the wild), can certainly version it.

An example of versioning - https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/system/definitions.ts#L188-L201

(The `To<XYZ>` indicated the Substrate specVersion where it took effect)

**Comment by joelamouche** [comment]
ok good to know. I opened a question in the frontier repo because I want a bit more context on this change https://github.com/paritytech/frontier/issues/259

I don't think this is related to this issue because now I can't reproduce it so Im thinking it was solved by one of your fixes from this morning (unless someone can reproduce it)

**Comment by jacogr** [comment]
So I saw something like the above on one of the Moonbeam networks. That disappeared when I pulled in the types. 

Anyway, will checke what is here against frontier again. The issue with wrong decoding is that it may decode crap in some cases and then fail in others if the types are wrong. (It all depends on the alignment of the bytes)
