### ISSUE TITLE
Partial duplication between "Usage" section examples and examples in the "Examples" section

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#300]
Some of the examples listed in the below "Usage" section:

<img width="737" alt="screen shot 2018-10-15 at 18 03 25" src="https://user-images.githubusercontent.com/6226175/46962960-c568e500-d0a4-11e8-844f-f5457c16ad4d.png">

Are duplicated to an extent in the examples in the "Examples" section at links shown below. Note however that often the version in the "Usage" section (such as "Submitting a transaction") is often more concise and makes more use of chaining:

<img width="227" alt="screen shot 2018-10-15 at 18 03 37" src="https://user-images.githubusercontent.com/6226175/46963018-e8939480-d0a4-11e8-9cc1-aa4739e2fbdd.png">

**Comment by jacogr** [comment]
@ltfschoen I think we fixed this?

**Comment by ltfschoen** [comment]
@jacogr Not yet, the examples in the "Usage" section use more chaining, whereas the ones in the "Examples" split each call without as much chaining. Perhaps I should add a separate example that shows how to achieve the same thing with chaining?

**Comment by ltfschoen** [comment]
@jacogr I've removed the Usage sections now (replacing them with links to the Examples i.e. `@example See [Polkadot-JS Api Rx Examples](https://polkadot.js.org/api/examples/rx/)`) since they duplicate the Examples and will push into PR #292  where I'm fixing up the examples along with addressing your review comments

**Comment by jacogr** [comment]
Closing until we have a docs drive, re-open as needed.
