### ISSUE TITLE
Initializing connection - Slow - 7 Seconds+

### ISSUE THREAD

**Issue by qalqi** [polkadot-js/api#3008]
Connecting to any network with polkadot.js is slow and usually takes 7/8 seconds or more regardless of the network speed.

* Polkadot, hosted by parity - 7.64s stalled
* Polkadot, hosted by web3 - 6.64s stalled
* Kusama, hosted by parity - 5.49s stalled
![image](https://user-images.githubusercontent.com/1781048/103393879-1d3b7b80-4b4b-11eb-9100-77a613f551bb.png)

This behavior is consistent across networks and can be noticed also in https://polkadot.js.org/apps/

![image](https://user-images.githubusercontent.com/1781048/103393274-db5d0600-4b47-11eb-91c3-208554a9534c.png)

This issue pertains even in subsequent connections
Is there any way we can bring it to 1/2 secs? client-side caching, preload registry etc?

Can be tested locally with following

``` js
import { ApiRx, WsProvider } from '@polkadot/api';
const provider = new WsProvider('wss://kusama-rpc.polkadot.io/')
const api$ = new ApiRx({ provider }).isReady; 
```

**Comment by jacogr** [comment]
You can pass the metadata through so it won't be retrieves - https://github.com/polkadot-js/api/blob/master/packages/api/src/types/index.ts#L45

(There is something in testing that will retrieves the metadata alongside the runtimeVersion, i.e. to parallelize the metadata retrieval in https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L237)

**Comment by jacogr** [comment]
Where are you located btw?

The reason for asking is that your timings is way off mine (not that I can say it is _great_, far from it). So it would be interesting to compare against other nodes, for instance Patract's instances are in Singapore. (The rest are all EU-based, which doesn't bode well for users in the Americas, since they have no closer options)

**Comment by qalqi** [comment]
I am in India. GMT + 5.30 Hours

**Comment by qalqi** [comment]
Are these files you are referring to for metadata?

static-polkadot.json? static.polkadot.ts?

at https://github.com/polkadot-js/api/tree/e77050b9f59a0b772d1d0b8c5c1da488a7c36810/packages/metadata/src/Metadata/v11



How did you generate metadata here?

**Comment by jacogr** [comment]
It is the actual hex metadata as retrieved from the chain.

**Comment by qalqi** [comment]
How often metadata change for a chain? only on upgrades?

**Comment by jacogr** [comment]
It is updated on upgrades. (Hence being keyed by genesisHash and specVersion)

**Comment by qalqi** [comment]
can we have an option to cache it from @polkadot.js/api?  burst cache when genesisHash and specVersion changes?


This way, at least subsequent requests payload will be smaller

**Comment by jacogr** [comment]
It is only retrieved once (and then on upgrades).

**Comment by qalqi** [comment]
Every new WebSocket connection is taking the same amount of initializing time say 7 secs.  

If metadata is already cached, then what else is required to improve the first load?

**Comment by jacogr** [comment]
The API only created one WebSocket instance.

**Comment by qalqi** [comment]
if we disconnect or refresh page after creating WebSocket once with metadata retrieved from the server, is metadata retrieved again?

**Comment by jacogr** [comment]
Disconnections, as handled by the API doesn't retrieve metadata again. A refresh certainly does, the API doesn't have insight into websites, React Native, Node.js, Electron or any other environment. It only acts on create.

**Comment by jacogr** [comment]
So these are my timings, doing the following -

```js

**Comment by qalqi** [comment]
This helps.

I can improvise loading time by caching metadata after the first retrieval for Websites and Electron using persistent data indexdb or AsyncStorage forReact Native,. 

Tx

**Comment by qalqi** [comment]
```js

const axios = require('axios');
import { ApiRx, WsProvider, ApiPromise } from '@polkadot/api';


const testKusama = (async () => {
    var genesisHashQuery = JSON.stringify({ "id": "1", "jsonrpc": "2.0", "method": "chain_getBlockHash", "params": [0] });
    var runtimeQuery = JSON.stringify({ "id": "1", "jsonrpc": "2.0", "method": "state_getRuntimeVersion", "params": [] });
    var metadataQuery = JSON.stringify({ "id": "1", "jsonrpc": "2.0", "method": "state_getMetadata", "params": [] });
    var config = {
        method: 'post',
        url: 'https://kusama-rpc.polkadot.io',
        headers: {
            'Content-Type': 'application/json',
        }
    };

    const genesisHashdata = await axios({ ...config, ...{ data: genesisHashQuery } });
    const runtimedata = await axios({ ...config, ...{ data: runtimeQuery } });
    const metadatadata = await axios({ ...config, ...{ data: metadataQuery } });

    const metadataKey = `${genesisHashdata.data.result}-${runtimedata.data.result.specVersion}`;
    const metaValue = metadatadata.data.result;
    let metadata = {};
    metadata[metadataKey] = metaValue;
    const ENDPOINT = 'wss://kusama-rpc.polkadot.io';

    console.time('kusamaWithMetaReady');
    await ApiPromise.create({ provider: new WsProvider(ENDPOINT), metadata })
    console.timeEnd('kusamaWithMetaReady');
    console.time('kusamaWithoutMetaReady');
    await ApiPromise.create({ provider: new WsProvider(ENDPOINT) });
    console.timeEnd('kusamaWithoutMetaReady')

})(); 
```

Result
`kusamaWithMetaReady: 3675.406982421875 ms`
`kusamaWithoutMetaReady: 5543.93603515625 ms`

Definite improvement 👍
