### ISSUE TITLE
getBlock error : Unable to create Enum via index 134, in Ed25519, Sr25519, Ecdsa

### ISSUE THREAD

**Issue by Yangxin-GG** [polkadot-js/api#3009]
Block in KLP (334250 334252 334253 334254....)."GetBlock " : Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\" header\",\" Extrinsics \":\"Vec&lt;Extrinsic&gt;\"}:: Struct: failed on extrinsics: Vec&lt;Extrinsic&gt;:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 170, in Ed25519, Sr25519, Ecdsa

**Comment by Yangxin-GG** [comment]
version:3.2.1 and 2.10.1

**Comment by Yangxin-GG** [comment]
![image](https://user-images.githubusercontent.com/30194654/103394596-706df800-4b64-11eb-86d7-81347c89742b.png)

**Comment by Yangxin-GG** [comment]
Block in 334250 334252 334253 334254....

**Comment by jacogr** [comment]
Have you added the new MultiAdress type for the version 13 runtime? (It o key applies to blocks front the upgrade, older is without)

**Comment by Yangxin-GG** [comment]
sorry，I'm not sure，I don't know what version KLP uses

**Comment by jacogr** [comment]
They use `MultiAddress` for all blocks >= 334080 for those prior `AccountId`. So you need to supply the correct types for Kulupu.

See https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-address-decoding-failures

And the types that the apps UI uses - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/specVersioned/kulupu.ts (It was updated by the team on Monday, see for instance the decoding for the first block you mentioned at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.kulupu.corepaper.org%2Fws#/explorer/query/334250)

**Comment by Yangxin-GG** [comment]
Thank you
