### ISSUE TITLE
for getblock api call

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#3018]
I have a question.

If the following call is executed, the transaction (Extrinsic)  will be included in the block regardless of whether the transaction (Extrinsic) failed/successful. In other words, it is possible to know what is included in the block, but it is difficult to check whether the transaction(Extrinsic) failed/successful with the api below.

I am trying to check in the api below whether it is fail or not, is there any other way?
cuz my system is watching block's data -> get the Extrinsic info from block's data with every 5 sec.

-Api call-
await api.rpc.chain.getBlock(blockHash);

**Comment by jacogr** [comment]
The `getBlock` does not include the transaction events, only the transaction data.

To map extrinsics to events, see https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by puffanddmx** [comment]
thanks!
