### ISSUE TITLE
Transfer events not working 

### ISSUE THREAD

**Issue by arijitban6** [polkadot-js/api#3029]
Code- 
`// Import the API & Provider and some utility functions
const { ApiPromise } = require('@polkadot/api');

// Import the test keyring (already has dev keys for Alice, Bob, Charlie, Eve & Ferdie)
const testKeyring = require('@polkadot/keyring/testing');

// Utility function for random values
const { randomAsU8a } = require('@polkadot/util-crypto');

// Some constants we are using in this sample
const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';
const AMOUNT = 10000;

async function main () {
  // Create the API and wait until ready
  const api = await ApiPromise.create();

  // Create an instance of our testing keyring
  // If you're using ES6 module imports instead of require, just change this line to:
  // const keyring = testKeyring();
  const keyring = testKeyring.default();

  // Get the nonce for the admin key
  const { nonce } = await api.query.system.account(ALICE);

  // Find the actual keypair in the keyring
  const alicePair = keyring.getPair(ALICE);

  // Create a new random recipient
  const recipient = keyring.addFromSeed(randomAsU8a(32)).address;

  console.log('Sending', AMOUNT, 'from', alicePair.address, 'to', recipient, 'with nonce', nonce.toString());

  // Do the transfer and track the actual status
  api.tx.balances
    .transfer(recipient, AMOUNT)
    .signAndSend(alicePair, { nonce }, ({ events = [], status }) => {
      console.log('Transaction status:', status.type);

      if (status.isInBlock) {
        console.log('Included at block hash', status.asInBlock.toHex());
        console.log('Events:');

        events.forEach(({ event: { data, method, section }, phase }) => {
          console.log('\t', phase.toString(), `: ${section}.${method}`, data.toString());
        });
      } else if (status.isFinalized) {
        console.log('Finalized block hash', status.asFinalized.toHex());

        process.exit(0);
      }
    });
}

main().catch(console.error);`

Output-
`TypeError: testKeyring.default is not a function`

polkadot version - ^3.3.2

**Comment by jacogr** [comment]
Check your imports, as per the error - `const testKeyring = require('@polkadot/keyring/testing');`

See the code - https://github.com/polkadot-js/common/blob/master/packages/keyring/src/testing.ts#L72

So the import is `const { createTestKeyring } = require('@polkadot/keyring/testing');`

**Comment by arijitban6** [comment]
Thanks @jacogr for your response, correct import fixed the issue. And you was correct I was referring to the doc. I am trying to deploy the flipper contract to my local network but not able to do so it will be much appreciated if can help me on this.
```
const { ApiPromise, WsProvider}  = require('@polkadot/api');
const { CodePromise }  = require('@polkadot/api-contract');
const testKeyring = require('@polkadot/keyring/testing');
var fs = require('fs');
const  abi = require('./contractBuild/metadata.json');
const { createTestKeyring } = require('@polkadot/keyring/testing');

const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';
async function main () {
  const keyring =  new createTestKeyring();
  const provider = new WsProvider('ws://127.0.0.1:9946');
  // Construct the API as per the API sections
  // (as in all examples, this connects to a local chain)
  const alicePair = keyring.getPair(ALICE);
  const api = await ApiPromise.create({ provider });
  const  wasm = fs.readFileSync('./contractBuild/flipper.wasm');
  // Construct our Code helper. The abi is an Abi object, an unparsed JSON string
  // or the raw JSON data (after doing a JSON.parse). The wasm is either a hex
  // string (0x prefixed), an Uint8Array or a Node.js Buffer object
  const code = new CodePromise(api, abi, wasm);

  // Deploy the WASM, retrieve a Blueprint
  let blueprint;

  // createBlueprint is a normal submittable, so use signAndSend
  // with an known Alice keypair (as per the API samples)
  const unsub = await code
    .createBlueprint()
    .signAndSend(alicePair, (result) => {
      if (result.status.isInBlock || result.status.isFinalized) {
        // here we have an additional field in the result, containing the blueprint
        blueprint = result.blueprint;
        unsub();
      }
    })
}

main().catch(console.error);
```
`Error: You need to connect to a node with the contracts module, the metadata does not enable api.tx.contracts on this instance`

**Comment by jacogr** [comment]
The above says exactly what is means - your node does not expose the contracts RPC, so it cannot attach.

**Comment by arijitban6** [comment]
Now I get it. Thanks for the response.
