### ISSUE TITLE
how to get an extrinsic hash with a block hash  or blocknumber or another way?

### ISSUE THREAD

**Issue by sollover** [polkadot-js/api#3036]
Hi,
I use getblock method and I'm getting an extrinsic details with this expect for extrinsic hash. How can I get this info?

```
` const signedBlock = await api.derive.chain.getBlock("0x76a8261425141d07579b5817dd7a06adf39954ef9b2822a62a102f013e21019f")
  signedBlock.extrinsics.forEach(({ 
    events,
    extrinsic}, index) => {

    console.log('>>', index, `${extrinsic.method.section}.${extrinsic.method.method}(${JSON.stringify(extrinsic.args)})`);
    console.log('events', JSON.stringify(events));

  })

`
```

Result is here:

`>> 1 balances.transfer(["12xtAYsRUrmbniiWQqJtECiBQrMn8AypQcXhnQAc6RB6XkLW",2499835000000])
events [{"index":"0x0501","data":["13GVmaG3qMk2Sq5rLyt4q3F1SRHK56MbSBFvLanSF99h1QXN",10000000]},{"index":"0x0004","data":["13GVmaG3qMk2Sq5rLyt4q3F1SRHK56MbSBFvLanSF99h1QXN"]},{"index":"0x0502","data":["13GVmaG3qMk2Sq5rLyt4q3F1SRHK56MbSBFvLanSF99h1QXN","12xtAYsRUrmbniiWQqJtECiBQrMn8AypQcXhnQAc6RB6XkLW",2499835000000]},{"index":"0x1306","data":[124000000]},{"index":"0x0504","data":["1gpCRov55rqmNaoEVRNAUCCYVzSGghitLNabng8UHVGwv1g",31000000]},{"index":"0x0000","data":[{"weight":215334000,"class":"Normal","paysFee":"Yes"}]}]`

thank you

**Comment by jacogr** [comment]
Every object (e.g. extrinsic, block, ...) has a `hash` methods, see https://polkadot.js.org/docs/api/start/types.basics#everything-is-a-type

To retrieve per-block extrinsic hashes, see https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-retrieve-the-headerextrinsic-hash-from-blocks (can be applied on the `extrinsic` above as mapped by you)

**Comment by sollover** [comment]
hi @jacogr  thank you!
