### ISSUE TITLE
how to set ws-max-connections parameter as unlimited for node over websocket connection 

### ISSUE THREAD

**Issue by sollover** [polkadot-js/api#3038]
hi everyone,

How can I set the` ws-max-connections ` parameter as unlimited?? (or another way) when I send a lot request (approximately ~50 request) to my local node over websocket connection, I'm getting an error like this:

`  API-WS: disconnected from ws://159.69.177.165:9944: 1006:: connection failed`

But I restart the my service, it fixes... 

How can I fix this error? 

thank you

**Comment by Tbaut** [comment]
The api WS connection should be unique for each client application. The number of WS connection accepter by the node can't be defined in the api.

If you show some code we may be able to help you troubleshoot. A WS connection is a long lasting connection that should supported an unlimited amount of request. The amount of connection and the amount of requests is very different.

**Comment by jacogr** [comment]
For the node as per `--help` -

```
        --ws-max-connections <COUNT>                             
            Maximum number of WS RPC server connections
```

**Comment by sollover** [comment]
@jacogr  If I set a count, I will get this error again, when I reach the this count ? Is it true? Therefore -I think-  I have to do without limits... but how ?

**Comment by jacogr** [comment]
The node does not have unlimited, the only option is the one above, as per the node help. When a client connects (doesn't matter how many messages it does over that connection), one is used. When it disconnects, the node frees up a slot.

**Comment by sollover** [comment]
I see @jacogr, thank you

**Comment by sollover** [comment]
hi again, @jacogr,  is there --ws-max-connections COUNT parameter maximum value? I assigned the parameter value as `999999`, I guess this didn't happen... what is the max. amount for this parameter?

also I assigned this value parameter in docker exec 

`polkadot --ws-max-connections 999999` but I got this error: 

```
`Error:
   0: Backend error: IO error: While lock file: /polkadot/.local/share/polkadot/chains/polkadot/db/LOCK: Resource temporarily unavailable

Location:
   src/main.rs:57

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main
      at <unknown source file>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.`


```

what is this error? how do I fix it?

thank you

**Comment by jacogr** [comment]
No idea - would need to look at the Rust code (https://github.com/paritytech/substrate) and where it handles it for max.
