### ISSUE TITLE
Runtime upgrades on detected on parachains

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/api#3039]
When a runtime happens on a standalone chain like Kusama or the Substrate node template, Apps detects the upgrade and tells users to reload the page. This notice to reload does not happen with runtime upgrades on cumulus-based parachains.

EDIT: I meant to open this against Apps, but I'm not really sure which is right, so I'll leave it here for now.

**Comment by jacogr** [comment]
It is apps UI :)

So it actually doesn't prompt anymore since the API does re-decorate with the updated meta. (Well, it interleves old/new and applies all latest types based on the typesBundle)

So what does not work after the upgrade? It is quite possible there is an expectation gap.

**Comment by JoshOrndorff** [comment]
Okay. Good to know. Let me explore more and report something more precise when I pin it down.

**Comment by jacogr** [comment]
When indexes do move around (this really should be checked _before_ upgrade and with the index on the macro is is perfectly easy to fix them), there _may_ be issues on some. (Since it interleaves metadata)
