### ISSUE TITLE
about websocket

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#3048]
if we use code below, ws://127.0.0.1:9944 (websocket) is automatically connected.
are there any function to stop websocket connection to make some logics (sometimes connection start , sometime connection stop)? 

<code>
const { ApiPromise, Keyring } = require('@polkadot/api')
api = await ApiPromise.create({});
await Promise.all([ ]);

**Comment by jacogr** [comment]
You can pass the autoConnect option set to false to the provider constructor, i.e.

```js
// create provider with autoConnect flag = false (or 0 has the same bahavior)
const provider = new WsProvider('ws://127.0.0.1:9944', false);

...

// connect manually
provider.connect();
```

**Comment by puffanddmx** [comment]
how to disconnect ?
provider.disconnect();??

**Comment by jacogr** [comment]
Yes, `provider.disconnect()` (or `api.disconnect()` (does the same, just calls down)

**Comment by puffanddmx** [comment]
thanks!
