### ISSUE TITLE
is there any methods for convert to dot from others (like: kDOT, mDOT etc.)

### ISSUE THREAD

**Issue by sollover** [polkadot-js/api#3052]
hi everyone, 

I got an transaction info with polkadot api and it turned -for some transactions- as mDOT, kDOT etc. Is there any methods  for convert this amounts to DOT?

thank you

**Comment by jacogr** [comment]
The API returns an actual Balance object in all cases. I'm assuming you called `toHuman()` on it if it is formatted that way? As the name suggests, that method is for human consumption, not computer consumption. It should not be used for anything else than display of values where you don't want to perform formatting yourself.
