### ISSUE TITLE
about sign and transfer

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#3056]
Is there a way to separate the signAndSend function without running sign and send at the same time?
Can the sign function and send function exist separately?

-code
api.tx.balances
    .transfer(recipient, AMOUNT)
    .signAndSend

-link-
https://polkadot.js.org/docs/api/examples/promise/transfer-events

**Comment by jacogr** [comment]
They do. `.signAsync` & .send`

**Comment by puffanddmx** [comment]
api.tx.balances.signAsync 
-> is this right ?

**Comment by jacogr** [comment]
No, it is on the submittable. So instead of `api.tx.balances.transfer(recipient, AMOUNT).signAndSend(...)` you can do -

```js
// construct tx
const tx = api.tx.balances.transfer(recipient, AMOUNT);

// sign it (same options as signAndSend)
await tx.signAsync(...);

// send it (await yields hash, o pass callback for status)
await tx.send(...)
```

**Comment by puffanddmx** [comment]
how to make the same code below with above await code ?
(fail/pass/inblock/isfinalized)

.......................................<code>.................................
api.tx.balances
    .transfer(recipient, AMOUNT)
    .signAndSend(alicePair, { nonce }, ({ events = [], status }) => {
      console.log('Transaction status:', status.type);

      if (status.isInBlock) {
        console.log('Included at block hash', status.asInBlock.toHex());
        console.log('Events:');

        events.forEach(({ event: { data, method, section }, phase }) => {
          console.log('\t', phase.toString(), `: ${section}.${method}`, data.toString());
        });
      } else if (status.isFinalized) {
        console.log('Finalized block hash', status.asFinalized.toHex());

        process.exit(0);
      }
    });
}

**Comment by jacogr** [comment]
I honestly cannot read what you posted above, it really would help me help you if the code in question is actually is a readable formatted fashion.

I'm guessing the question is "does send have a status callback" - yes, indeed it does. 

See https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/types.ts#L58 which is part of the interface linked in my previous comment (same callback definition as on `signAndSend`)

**Comment by puffanddmx** [comment]
ok thanks!
