### ISSUE TITLE
[BUG] Get error when query rococo blockNum 411786

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#3065]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer/query/411786

```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding inclusionInherent.inclusion:: Struct: failed on args: {"signed_bitfields":"SignedAvailabilityBitfields","backed_candidates":"Vec<BackedCandidate>","parent_header":"Header"}:: BitVec: required length less than remainder, expected at least 10404550, found 2643

```

**Comment by jacogr** [comment]
Thanks for reporting.

There has been a lot of changes lately to the types, quite possible something in mis-aligned. I get a slightly different error to the be above, but it does fail so would need to look at the block itself.

**Comment by jacogr** [comment]
Where do you get the type for this `{"signed_bitfields":"SignedAvailabilityBitfields","backed_candidates":"Vec<BackedCandidate>","parent_header":"Header"}`

There is no such type in the API itself. (Everything is `camelCase`). This is why my error on this doesn't match yours, you seem to have injected non-API types.

**Comment by jacogr** [comment]
2 issues actually -

The ValidatorIndex for inclusion needed adjustment. And then the linked block contains offences as well - that also failed decoding (So Rococo-known had to adjust the Validator identification).
