### ISSUE TITLE
how to catch " 1006: api-ws connection failed" error 

### ISSUE THREAD

**Issue by sollover** [polkadot-js/api#3070]
hi everyone,

I try to read dot transactions over my local node with web socket provider, and I send a lot request to node and I got like this error from node: ` API-WS: disconnected from ws://x.x.x.x:9944: 1006:: connection failed`

I guess, I'm getting this error after ~50 request. Then I start the my service manually it's fixed. How can I catch this error on codes? I couldn't on catch block or another ways this error... 

what should I do?
thank you

**Comment by jacogr** [comment]
`provider.on('error'), (error) => { ... })` is emitter on all provider-related errors.

**Comment by sollover** [comment]
thank you solved!
