### ISSUE TITLE
Add non-frontier rpc method decorators

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3083]
I know that all frontier method decorators are now injected by the api. But does it still also support non-standard decorator injection?
https://github.com/PureStake/moonbeam/pull/171 introduced new non-standard methods for moonbeam (txpool_content, txpool_inspect, txpool_status)
How do I declare these decorators for the api?
Furthermore, how do I make them available for the app?

Thanks in advance

**Comment by jacogr** [comment]
You add them o your types, like you have `types: [ { minmax: ... } ]` in your definitions, you can add `rpc: { ... }`

**Comment by joelamouche** [comment]
You mean

``` 
types:[...,{
      minmax: [6, undefined],
      types: {
        AccountId: "EthereumAccountId",
        Address: "AccountId",
        Balance: "u128",
        LookupSource: "AccountId",
        Account: {
          nonce: "U256",
          balance: "u128",
        },
        ExtrinsicSignature: "EthereumSignature",
        RoundIndex: "u32",
        Candidate: {
          validator: "AccountId",
          fee: "Perbill",
          nominators: "OrderedSet<Bond<AccountId, Balance>>",
          total: "Balance",
          state: "ValidatorStatus<RoundIndex>",
        },
        OrderedSet: "Vec",
      },
      rpc: rpcDefinitions,
      }]
      ```
      
      right?

**Comment by jacogr** [comment]
```js
const defs = {
  rpc: rpcDefinitions,
  types: [
    {
      minmax: [6, undefined],
      types: {
        AccountId: "EthereumAccountId",
        ...
 ```

**Comment by joelamouche** [comment]
Ha ok sorry I didn't realize there was two levels of string keys in `Record<string, Record<string, DefinitionRpc | DefinitionRpcSub>>`

What is the top level key supposed to be?
This?
```
// Moonbeam specific rpc methods
const rpcDefinitions: Record<string, Record<string, DefinitionRpc | DefinitionRpcSub>> = {
  txpool: {
    content: {
      aliasSection: "txpool",
      description:
        "The detailed information regarding Ethereum transactions that are currently in the Substrate transaction pool.",
      params: [],
      type: "TxPoolResult<TransactionMap<Transaction>>",
    },
    inspect: {
      aliasSection: "txpool",
      description:
        "Summarized information of the Ethereum transactions that are currently in the Substrate transaction pool.",
      params: [],
      type: "TxPoolResult<TransactionMap<Summary>>",
    },
    status: {
      aliasSection: "txpool",
      description:
        "The number of Ethereum transaction that are currently in the Substrate transaction pool.",
      params: [],
      type: "TxPoolResult<U256>",
    },
  },
};
```

(doesn't work btw)

**Comment by jacogr** [comment]
Just add the rpc key at the same level as the first types key that contains the min/max stuff. 

It does indeed inject. For instance, while Acala does not add the RPCs to their types bundle, they do expose it in their package. Which means that applying this to their definitions gets rids of all the RPC warnings and makes it available on the UI in the correct location -

```js
import { rpc, typesBundleForPolkadot } from '@acala-network/type-definitions';

const extended = { rpc, ...typesBundleForPolkadot.spec.acala };

export default extended as unknown as OverrideBundleDefinition;
```

**Comment by joelamouche** [comment]
Would you mind pointing me to where that code is?
After pulling master I have:
```
// Copyright 2017-2021 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

import type { OverrideBundleDefinition } from '@polkadot/types/types';

import { typesBundleForPolkadot } from '@acala-network/type-definitions';

export default typesBundleForPolkadot.spec.acala as unknown as OverrideBundleDefinition;
```

**Comment by jacogr** [comment]
I didn't add to master, only locally to provide the above (rather I logged an issue with them to add, since they expose it is a line they need to move down)

**Comment by joelamouche** [comment]
I'm sorry but exposing the rpc this way doesn't work for me.
Would you mind taking a look at https://github.com/PureStake/moonbeam/pull/208 ?
in the test folder, running `npm run test` should not log `API/INIT: RPC methods not decorated: txpool_content, txpool_inspect, txpool_status`

**Comment by joelamouche** [comment]
it's using the types declared here (moonbeam-types-bundle/index.ts) directly

**Comment by jacogr** [comment]
Sadly, I cannot see how the API is constructed, so I just duplicated -

![image](https://user-images.githubusercontent.com/1424473/105870940-16dcda00-5ff9-11eb-9c46-bef37f701131.png)

Which this in the Moonbeam types in apps -

```js
// Copyright 2017-2021 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

import type { OverrideBundleDefinition } from '@polkadot/types/types';

import { moonbeamDefinitions } from 'moonbeam-types-bundle';

const rpc = {
  txpool: {
    content: {
      aliasSection: 'txpool',
      description:
        'The detailed information regarding Ethereum transactions that are currently in the Substrate transaction pool.',
      params: [],
      type: 'TxPoolResult<TransactionMap<Transaction>>'
    },
    inspect: {
      aliasSection: 'txpool',
      description:
        'Summarized information of the Ethereum transactions that are currently in the Substrate transaction pool.',
      params: [],
      type: 'TxPoolResult<TransactionMap<Summary>>'
    },
    status: {
      aliasSection: 'txpool',
      description:
        'The number of Ethereum transaction that are currently in the Substrate transaction pool.',
      params: [],
      type: 'TxPoolResult<U256>'
    }
  }
};

const extended = { rpc, ...moonbeamDefinitions } as unknown;

export default extended as OverrideBundleDefinition;
```

**Comment by jacogr** [comment]
And without, it warns and appears in the list -

![image](https://user-images.githubusercontent.com/1424473/105871211-5dcacf80-5ff9-11eb-9d5c-1c79020b21ed.png)

**Comment by joelamouche** [comment]
Thank you that was helpful :) 
Also allowed me to better understand how to test it on the app

**Comment by jacogr** [comment]
Closing. Moonbase Alpha seems to inject the RPCs now.

![image](https://user-images.githubusercontent.com/1424473/106468071-c43e6a80-649d-11eb-8a9d-c997d7de6081.png)
