### ISSUE TITLE
Invalid Transaction Error

### ISSUE THREAD

**Issue by sollover** [polkadot-js/api#3086]
Hi everyone,

I'm trying send DOT from account to an account. The from account has sufficient balance but I get this error.

`Error: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low.`

Why I'm getting this error?

Sending Amount: 69984000000
From Address Account Balance: 85384000000

my code snippets is here: 

`const keyring = new Keyring({ type: 'sr25519' })
  const hexPair = keyring.addFromUri(fromAddressHex)`

what's my fault? 

thank you

**Comment by jacogr** [comment]
What does system.account say for the sending account? (A copy From the Apps UI or a query with a toGun is fine)

but basically it means you don’t have enough o pay for the fees and then the transfer from the transferable portion. (Free - all locks)

**Comment by sollover** [comment]
hi, all balances of the account is free. I'm making this transaction on my node with polkadot js. 

The address is: 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX

I couldn't understand your says :( @jacogr

**Comment by jacogr** [comment]
Can you log the `hexPair.address` to ensure it is the same? (You probably want to pass `{ type: 'sr25519', ss58Format: 0 }` as keyring options to ensure the ss58 encoding is correct)

**Comment by sollover** [comment]
Hi yes, I used sr25519. and my code snippets for transfer is here and ss58Format: 0  for the address

`const create_polkadot_transaction = async (obj, isFromMain, resolve, reject) => {
  const keyring = new Keyring({ type: 'sr25519' })
  const hexPair = keyring.addFromUri(0x343...) // generated with:  u8aToHex(SeedPhrase of Address)
  connectOverWs(true).then(async (api) => {
    const txHash = await api.tx.balances
    .transfer(obj.to_address, sendingAmount )
    .signAndSend(hexPair)  //hexPair
    // Show the hash and tx fee
    console.log(`Submitted with hash ${txHash}`)
    resolve({
      currency: obj.currency,
      userid: obj.ref_id,
      txID: `${txHash}`,
      txFee: getNetworkFee,
      amount: sendingAmount
    })
  }).catch(err => { reject(err) })

}`

**Comment by jacogr** [comment]
Ok, if the pair address does match the address linked, aka

```js
// should print 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX & true
console.log(hexpair.address, hexpair.address === '16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX')
```

I no idea why the tx pool would reject it. It is either that the application of frees drop below existential (which is not the case here, there is enough) or that there is not enough available funds (not the case here, no reserved).

So really at this point don't understand why.

**Comment by sollover** [comment]
hi, hexpair.address  starts with '5vc...' it's not polkadot address. what can I do?

```
`const test = async () => {
  await cryptoWaitReady()
  const keyring = new Keyring({ type: 'sr25519' })
  const hexPair = keyring.addFromUri("0x3x....") //seed to HEX Result

  console.log(hexPair.address, hexPair.address === '16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX')
}`
```

I mean returns false.. 
Result : `5ChU2uiiPQRnFtS3Z1XZs6soVM1Gcs5G2CTpg17H5Z8xspPH false` @jacogr

**Comment by sollover** [comment]
also I generated the address (16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX) this way as you said this issue: 

as you said: https://github.com/polkadot-js/common/issues/819#issuecomment-751204151


I used for Dot address: `console.log('Polkadot', encodeAddress(PUBLIC, 0)) ` (like there)

**Comment by jacogr** [comment]
That is why I suggested above to add the `{ type: 'sr25519', ss58Format: 0 }` to the keyring init - that tells the keyring to print addresses in the Polkadot format. See the comment above - https://github.com/polkadot-js/api/issues/3086#issuecomment-764945214

**Comment by sollover** [comment]
this address has already been generated by that method @jacogr

**Comment by jacogr** [comment]
With the address fine and the numbers fine, the node fully synced, I have no idea why the transaction pool kicks it out - it generally is a funding fee payment issue only.

**Comment by sollover** [comment]
hey, like that:
```
const mnemonic = mnemonicGenerate()
const createdSeed = mnemonicToMiniSecret(mnemonic)
const { publicKey, secretKey } = naclKeypairFromSeed(createdSeed)
const pair = { polPublicKey: publicKey, polSecretKey: secretKey }
const generatedAdddress = encodeAddress(getKeypair.polPublicKey, 0)
const privKey = u8aToHex(getSeed)
```
....

generatedAdddress = 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX
privKey = 0x....
@jacogr  is this way correct?

**Comment by jacogr** [comment]
Ahh, the pair above is an ed25519 pair - you are using an sr25519 keyring.

**Comment by sollover** [comment]
both are returns false.. (ed25519 -sr25519)... I couldn't understand really :( 
what should I do? @jacogr

**Comment by sollover** [comment]
also this address is mine (and I generated same way with the address 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX) too, and its made some transfers ..

https://polkadot.subscan.io/account/14b6vKpSqbcjens9r2Cp6YASXaCVSzN4wi8YFD6KZjkjdEBG

but 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX doesn't transfer to an account own balance...

**Comment by jacogr** [comment]
See https://github.com/jacogr/sample-pair for an equivalent generator.

**Comment by sollover** [comment]
well, how do i get it the address (16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX) DOTS ?

**Comment by jacogr** [comment]
Look at the above example - it shows you how the two are equivalent. (In general you always want to work with the keyring since it does the heavy lifting for you). Compare the above working code to what you did and you should get to the underlying cause - my knee-jerk reaction is that you probably didn't use the seed you put into the `nacl*` into the keyring.

(mnemonic -> seed - that seed it used to create the pair in both cases)

**Comment by sollover** [comment]
I ran your sample and it's returns equal results with the address mnemonic keys (16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX) @jacogr 

Result:
`via nacl 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX
via pair 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX`

**Comment by sollover** [comment]
Hi again @jacogr  I couldn't withdraw DOT's of the 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX still.

I imports the this account to Polkadot-js web application, but it dosen't see the account balance. but the account has DOT's... Also I couldn't withdraw over my node too... What can I do? 
Thank you

**Comment by jacogr** [comment]
Did it import with the same address? I am asking since in the JS apps you had the seed specified wrong on the keyring import.

**Comment by sollover** [comment]
Yes, I generate this address (16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX) with nacl keyring(and the keyring type is sr25519 for this address). I import this address mnemonic keys on polkadot-js application but address not equal to 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX and the address balance is 0.

where is this 16b1m5X4hUXz3tVdpg24o6x7JPZUe4wiKxQoFMwhCP49vKoX address balance? How can I access the DOT's of this address? @jacogr

**Comment by jacogr** [comment]
In your example above, unlike the sample code I provided, you did this - `const hexPair = keyring.addFromUri( privKey)`

So I'm assuming that you pass that same to the UI. See the example as to what to pass, also to the apps UI -

- the minisecret gets generated here - https://github.com/jacogr/sample-pair/blob/main/index.mjs#L9
- it gets passed here to the keyring - https://github.com/jacogr/sample-pair/blob/main/index.mjs#L16

So you are most probably, like in your example above (and unlike running your address through the sample which created the correct outputs), passing the private key instead of the seed.
