### ISSUE TITLE
Transaction not found on network

### ISSUE THREAD

**Issue by TurgutKanceltik** [polkadot-js/api#3091]
Hello,

Recently, I have been getting a transaction not found error on broadcasts I made to the network. When I broadcast, the transaction hash is returned to me successfully, but when I look at the network, it cannot find this transaction.
To show the sample transaction;
> Tx1: 0x23f8e1a1ac90a886250a461f99ee567d7ccb6b8f2c7a085d7a64801b42605b95
> Tx2: 0xed52773949c9beb427a74eff89b344564b75213295b2b2b0f2b81a7d4f4a9afa

My questions are;

1. What could this be caused by? 
2. Is there any way I can understand if these transactions will not go later? Or can we say that it definitely won't happen later?

**Comment by jacogr** [comment]
If using the API and you do `await tx.signAndSend(...)` it returns the hash. However it still means the Node transaction pool can actually discard it. Transactions will be valid for the mortality era (as set), once it gets past that it is removed from the pool.

**Comment by TurgutKanceltik** [comment]
@jacogr 
For mortality, we are not setting any value, I think it is 5 min default.
does it mean that, after we got the transaction hash, if it pass 5 minutes and I still can not find this transaction, can I assume it is removed and it will not appear later?
and what could be the cause of dropping, how can I check the reason, so we can prevent further drops

**Comment by jacogr** [comment]
You would need to check the Rust code - the Substrate transaction pool specifically. (This is why the `.signAndSend` with the callback is preferrable, since you get all the status updates from the pool itself as they become available)

**Comment by jacogr** [comment]
Closing.
