### ISSUE TITLE
Extracting and verifying extrinsic payloads

### ISSUE THREAD

**Issue by igorgogo** [polkadot-js/api#3106]
Hi, when creating a transaction with `api.tx.<module>.<method>`, how can i extract the payload and verify the signature on a signed payload?

**Comment by jacogr** [comment]
The issue with the payload is that not all the information required for the payload is in the extrinsic. For instance, the payload would contain both the genesisHash and the blockHash (where submitted), these are signed as part of the payload - however that never is part of the extrinsic. (Same with specVersion, transactionVersion, ...) If these would all be submitted as part of the transaction, the size would balloon, so the payload has 2 parts - the transaction data and then additional data that the node itself can extract.

So when signing a payload gets created from the data in the extrinsic + additional data from the chain (as above) and only the resulting signature is added to the extrinsic.

I guess there is a possibility to add the payload to the extrinsic as well (obviously won't be available for anything retrieved from that chain), but that will only allow verification if created locally.

**Comment by igorgogo** [comment]
Sorry for the delayed reply. I think in general I understand but let me clarify my use case to see if there's any solutions that you might be able to help me with.

I'm trying to see if there's a way to construct the tx with polkadot.js api and have it signed by a signing server then sent back to the webapp where it will send the signed tx to the node.

An alternative solution I've found and tested was to use `@substrate/txwrapper`, construct the payload and tx myself but I would like to avoid this if possible.

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/tools/tree/master/packages/signer-cli - it generates the tx is one process, signs in another. (The code is very simple for both sides)

**Comment by igorgogo** [comment]
Thanks! After looking into signer-cli, we've decided to follow the same idea to create a signing server. We're gonna send the tx info to the signing server and generate the tx from there instead of the webapp. Appreciate the guidance!
