### ISSUE TITLE
Query Kusama's erasTotalStake and totalIssuance since genesis block until today 

### ISSUE THREAD

**Issue by Chralt98** [polkadot-js/api#3115]
Hey there,

my aim is to query the full historic data of _api.query.balances.totalIssuance_ and _api.query.staking.erasTotalStake_ at every day in time for the **Kusama network**. So the end result should be to have the daily total staking rate since the genesis block.

At the moment I am running an archive node. The problem at the moment is, that I can not query the era of the genesis block.
Code Example which should be something like that. Could you help me out? 

```javascript

const { ApiPromise } = require('@polkadot/api');

async function main () {
  const api = await ApiPromise.create();

  let blockNumber = 0;
  while (true) {
    const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
    const activeEra = await api.query.staking.activeEra.at(blockHash);  
    if (activeEra.isSome) {
      const era = activeEra.unwrap().index;

      const totalCoins = await api.query.balances.totalIssuance.at(blockHash);
      const stakedCoins = await api.query.staking.erasTotalStake.at(blockHash, era);
      console.log('%s block number, %s staked coins and %s total coins for block hash %s', blockNumber, stakedCoins.toHuman(), totalCoins.toHuman(), blockHash);
    }
    blockNumber++;
  }
}

main().catch(console.error).finally(() => process.exit());
    
```

**Comment by Chralt98** [comment]
I just found the issue #2415 , but what is the first blockhash and therefore first era to query in Kusama to extract the most historic erasTotalStake and totalIssuance?

**Comment by jacogr** [comment]
The genesisHash is available via `api.genesisHash` (which is really just `api.rpc.chain. getBlockHash(0)` as retrieved by the API on init)

**Comment by Chralt98** [comment]
I am running this script at the moment, but it logs no output, it will take a while to get the genesis block for sure? Is there a way to extract the date of a specific block hash?

**Comment by jacogr** [comment]
So for Kusama, activeEra is a new concept. (It has been there since the start of Polkadot though). What I mean by "new concept" is that the initial staking queries were vastly different. For instance there was no historic payouts, no historic eras, no active era, only currentEra. (So the logic is not the same for Kusama historic until the staking upgrades went in)

**Comment by Chralt98** [comment]
So there is no way to extract the staking rate since genesis block for the Kusama network?

**Comment by Chralt98** [comment]
By the way: I found the exact block number where the first _api.query.balances.totalIssuance_ appears on the Kusama network and the block number is **1377831**.

**Comment by jacogr** [comment]
No, entirely possible, you just need to adapt for old/vs new. So activeEra is not available, but currentEra would be. (Bit tricky since it will match the activeEra until he last session of the era, then it points to the next)

For the APR your need totalIssuance and the exposure for all staked validators. So on older, none of the `eras*` queries would have entries at all. So you just need to get the exposure elsewhere. (On recent, you can use the `eras*` queries)

For older staking module the validators, nominators, ledger is all available - so you can query those at the start of an era and combine for totals.

There has been a couple of variants of staking on Kusama, Substrate evolves continously.

**Comment by Chralt98** [comment]
By the way: the exact block number for the first _api.query.staking.erasTotalStake_ is **1491598**.

**Comment by Chralt98** [comment]
@jacogr Thanks for your response. I understand to extract the exposure of nominators, validators and add them together for each era manually, but which API calls should I use to get the bonded stakes?

**Comment by jacogr** [comment]
`staking.bonded(stashId)` to get the controller. Then `staking.ledger(controllerId)`. Just grabbed this on Polkadot for a random validator (Polkadot was the network I had open) -

![Uploading image.png…]()

**Comment by Chralt98** [comment]
Ok I see, thank you! Assume we are in one era and assume I got each totalStake for every validator. Then I need the total staked nominators value, how do I get there addresses (with api.query.staking.snapshotNominators, but this is only at the beginning of the current election window)? Unfortunately then I need the api.query.balances.totalIssuance, but it's zero until the block number 1377831.

**Comment by jacogr** [comment]
`validators`. Not sure why the totalIssuance it zero, quite possible it could have moved as well. (Really cannot recall another location, but daily there are adjustments for new additions to Substrate, so don't take my word on it since I cannot remember every single query movement and type change)

**Comment by Chralt98** [comment]
So the _api.query.session.validators_ got every nominator included? Where do I can find out how the _api.query.balances.totalIssuance_ moved?

**Comment by jacogr** [comment]
`.validators` are only the validators. To get nominators you would need to query the `staking.nominators` entry (probably with `.entriesAt(blockHash)`

For the second part, the source of truth is the Substrate codebase, if it was "introduced after launch" there will be some PR that mentions it

**Comment by jacogr** [comment]
However, just queries the metadata at block 1, there is `balances.totalIssuance` -

![image](https://user-images.githubusercontent.com/1424473/106145672-1ddd2700-6176-11eb-9f23-c1bc9d708cef.png)

And it def has a value at block 1 -

![image](https://user-images.githubusercontent.com/1424473/106145815-4533f400-6176-11eb-93cb-644b378fae01.png)

**Comment by Chralt98** [comment]
I will find my mistake later and post hopefully the solution to query the totalStake since the genesis block in this chat here. :-)

**Comment by Chralt98** [comment]
```javascript

const { ApiPromise } = require('@polkadot/api');

async function main () {
  const api = await ApiPromise.create();
  // get the genesis block
  let blockNumber = 0;
  // 1491598 is the first occurance of _api.query.staking.erasTotalStake_
  while (blockNumber < 1491598) {
    const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
    const currentEra = await api.query.staking.currentEra.at(blockHash);  
    if (currentEra.isSome) {
      const era = currentEra.unwrap();

      const totalCoins = await api.query.balances.totalIssuance.at(blockHash);
      
      const validators = await api.query.session.validators.at(blockHash);
      let totalValidatorStaked = 0;
      let totalNominatorStaked = 0;
      let totalStaked = 0;
      for(var i = 0; i < validators.length; i++) {
          const validatorController = await api.query.staking.bonded(validators[i]).at(blockHash);
          totalValidatorStaked += await api.query.staking.ledger(validatorController).at(blockHash);
          totalStaked += totalValidatorStaked;
          // get map from validator stashes to nominator stashes
          const allNominatorEntries = await api.query.staking.nominators(validators[i]).entriesAt(blockHash);
          allNominatorEntries.forEach(([{ args: [validatorId] }, nominationsOpt]) => {
            if (nominationsOpt.isSome) {
              const nominatorController = await api.query.staking.bonded(nominationsOpt).at(blockHash);
              totalNominatorStaked += await api.query.staking.ledger(nominatorController).at(blockHash);
              totalStaked += totalNominatorStaked;
            }
          });
      }
      
      console.log('%s block number, %s staked coins and %s total coins for block hash %s', blockNumber, totalStaked.toHuman(), totalCoins.toHuman(), blockHash);
    }
    blockNumber++;
  }
}

main().catch(console.error).finally(() => process.exit());
    
```

**Comment by Chralt98** [comment]
The required data would be _api.query.staking.erasStakers_ to get the total staked coins with nominators of one validator.
