### ISSUE TITLE
Batch transfer transaction

### ISSUE THREAD

**Issue by shangpit** [polkadot-js/api#3121]
Please support me to create a batch transaction to reduce network fee using polkadot js api

- From one account to many account
- From many account to one account.

**Comment by jacogr** [comment]
You won't reduce fees, rather it will be more expensive since you need to pay for the weight of the batch call as well (in addition to the transfer weights).

Only the first is possible since a batch operates on a single sender account -

```js
const await api.tx.utility.batch([
  api.tx.balances.transfer(TO_1, VALUE_1),
  api.tx.balances.transfer(TO_2 VALUE_2),
  ...
]).signAndSend(FROM);

**Comment by shangpit** [comment]
It's not like UTXO from Bitcoin-base chain :(
When send multiple UTXO (different address) to one address, network fee is same with one to one

**Comment by jacogr** [comment]
Yes, Substrate is not UTXO-based. It is not like Bitcoin in implementation and while it has an address model like Ethereum, it is not like Ethereum in implementation either - it is it's own animal

**Comment by shangpit** [comment]
```js
https://polkadot.subscan.io/extrinsic/0x4fc1008a0e53f2d8b825d5bdc8b7a4f4b148da008a32ea1ede0d685408fa15ea
```
i saw that utility batch from 1 to 3 txs ~0.025 DOT while 1 to 1 is 0.015 DOT. Thank you very much

**Comment by jacogr** [comment]
Yes, I'm actually wrong when I say "you won't reduce it" - there is a base tx fee that applies in addition to the weight, so you only pay for that once. (And then just the weight fee on the embedded txs)

**Comment by shangpit** [comment]
Thanks for suported!
