### ISSUE TITLE
Discrepancy between the latest release version on GitHub and the one published on npm

### ISSUE THREAD

**Issue by dillu24** [polkadot-js/api#3122]
On npm the latest release is marked as 3.6.4, but on GitHub it is marked as 3.6.1 . Why is this different?

**Comment by jacogr** [comment]
The patches don't get a CHANGELOG. (Well they do, but rolled up in the next minor). All small little changes. 

Probably should re-evaluate that if it creates confusion. (Generally there are few and far in-between, sadly there were 3 quick-fire issues reported by users straight after which was worth fixing)

**Comment by dillu24** [comment]
Got it. Most probably so it is best to use 3.6.4 for our API server yes?

**Comment by jacogr** [comment]
Yes, please do.

**Comment by jacogr** [comment]
PS: The 3.7.1 on Monday will include support for Kusama/Polkadot 2028/28 (i.e. the upgrade after the next one... that will be worth upgrading to since the address types will change in those upgrades - it is only in rc in Parity, so not even submitted on-chain, just a heads-up)

**Comment by dillu24** [comment]
Thanks for your help and for informing us about this.
