### ISSUE TITLE
mjs files causing errors with create-react-app template

### ISSUE THREAD

**Issue by Lev-Stambler** [polkadot-js/api#3124]
Using a Create-React-App template with the @polkadot/api package causes the following error.

```
./node_modules/@polkadot/api/base/Init.mjs
Can't import the named export 'BN_ZERO' from non EcmaScript module (only default export is available)
```

I was able to provide a temporary fix by deleting all .mjs files from my `node_modules` by adding
```"postinstall": "yarn rm-mjs",
    "rm-mjs": "find . -type f | grep -e 'mjs$' | xargs rm"
```
To my `package.json` scripts. But as this is only a temporary fix, I thought to raise this as an issue.

**Comment by jacogr** [comment]
Here is a previous discussion with a fix - https://github.com/polkadot-js/common/issues/812

I would also suggest just trying `3.6.4` of the API (latest patch) first - the `module` field in all the `package.json` files has been removed, so old versions should not see it. However have not tested it yet with `create-react-app` myself o see if it removes the need to the above as linked.
