### ISSUE TITLE
Contract field is undefined after Blueprint is deployed

### ISSUE THREAD

**Issue by gregzaitsev** [polkadot-js/api#3125]
This code from [this tutorial](https://polkadot.js.org/docs/api-contract/start/blueprint) used to work, but now `result.contract` is undefined:

```
    const unsub = await blueprint.tx
    .new(endowment, gasLimit, initValue)
    .signAndSend(alice, (result) => {
      if (result.status.isInBlock || result.status.isFinalized) {

        console.log("Contract deployed: ", result.contract); // <--- Prints undefined

        unsub();
        resolve(result);
      }
    });    
```

**Comment by jacogr** [comment]
Ummmm.... there has been no changes, so indeed should still be the same. 

The only place it should not be included s if it doesn't pickup the event. Will test against a recent Substrate master.

**Comment by gregzaitsev** [comment]
I am using the API 3.6.4, but noticed that UI has newer API (3.6.5-6), and the UI contracts work.

**Comment by jacogr** [comment]
There really has been no changes in that layer :) All the stuff in the current betas have mostly revolved around parachains.

Ys, the UI uses the same api-contracts interface, so it doesn't use anything else or take shortcuts. Will try both though.

**Comment by gregzaitsev** [comment]
Turned out it was my fault, the deploying account did not have enough balance to pay for endowment. 

But the documentation still refers to `createContract`, which is marked as deprecated. Would you like to leave this issue open to track this update?

**Comment by jacogr** [comment]
Ok, have not been able to reproduce. 

Yes, the docs need an update. Additionally to support this https://github.com/polkadot-js/api/issues/3112 - the put code & deploy would become one (the API will detect old vs new) and handle appropriately. That will go into the betas this week.

**Comment by jacogr** [comment]
Closing, replaced by https://github.com/polkadot-js/docs/issues/172
