### ISSUE TITLE
[support] RPC type generation

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/api#3132]
There is a discrepancy between the documentation and implementation when it comes to generating RPC types. The documentation describes a nesting of type `rpc: { modules: { methods: ... } } }`, yet the implementation only parses `rpc: { methods: ... }`, skipping the module.

More concretely, the `modules` variable here (https://github.com/polkadot-js/api/blob/master/packages/typegen/src/generate/rpc.ts#L48) stores an array of file definitions (each of which contains modules), instead of an array of modules.

**Steps to reproduce**

- Try building this polkabtc-js commit after updating polkadot/api and polkadot/typegen to 3.7.1 here: https://github.com/interlay/polkabtc-js/blob/2185eb8c3b68e0f8171c8273e21384878309a80d/package.json#L49
- That polkabtc-js commit uses these rpc definitions: https://github.com/interlay/polkabtc-types/blob/40cde2cb1e8b0fcd93847803840bd05355a9da8d/definitions.json#L221
- As a workaround, I noticed that you also check the `aliasSection` property, which I used to avoid the bug for now. However, it makes our RPC type definitions really verbose, as we have to define them twice (once with `aliasSection` for the api/typegen and once in the regular format when calling `ApiPromise.create()`). See `rpc` and `providerRpc`: https://github.com/interlay/polkabtc-types/blob/master/definitions.json

**Comment by jacogr** [comment]
The typegen is correct. It actually gets used for all the RPCs as exposed. So the input to that is indeed an array since it gets pulled from different places.

Typegen operates on these definitions - https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/babe/definitions.ts (which is combined from the different modules, i.e. the linked plus for instance this https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/system/definitions.ts)

There is a difference as to how the `typesBundle` is specified, that does not have the array mappings.

**Comment by savudani8** [comment]
I just followed the steps here: https://polkadot.js.org/docs/api/start/rpc.custom, and defined the custom RPCs like this: https://github.com/interlay/polkabtc-types/blob/00d9a7c783deeb22d1fdaae62c09712c31d51cb6/definitions.json. This resulted in the error described above. I'm not sure if I'm missing something or if the docs should be updated

**Comment by jacogr** [comment]
So the types above is not actually a valid input - it is a bundle definition. The typegen specifically operates only on `*.ts` files, i.e. it tries to load `definitions.ts` to figure out the structure.

So the structure is generally,

```js
/// <ROOT>/definitions.ts
export export { default as assets } from './assets/definitions';
...
```

```js
/// <ROOT>/assets/definitions.ts
export default {
  // as you have it defined
  rpc: { ... },
  types: {
    AssetId: 'u32'
  }
};
```

So from the definitions.ts in the root, it constructs the typegen array for the RPC. So it explicitly loads the `definitions.ts` file, see here - https://github.com/polkadot-js/api/blob/master/packages/typegen/src/fromChain.ts#L18

(the JSON should work), however in that case since you don't have a root, you need to create another top-level key to simulate it. Which is what the root definitions looks like, it is effectively -

```js
{
  assets: { rpc: { ... }, types: { ... },
  ...
  system: { rpc: {... }, type: { ... }
}
```

Since you only have 1 level with the json file, you need to add the explicit keys for the modules yourself.

**Comment by savudani8** [comment]
That bundle definition is being pulled here: https://github.com/interlay/polkabtc-js/blob/2185eb8c3b68e0f8171c8273e21384878309a80d/src/interfaces/definitions.ts

**Comment by savudani8** [comment]
All other typegens work:
```
$ yarn build
yarn run v1.22.5
$ run-s generate:* build:*
$ ts-node --skip-project node_modules/.bin/polkadot-types-from-defs --package @interlay/polkabtc/interfaces --input ./src/interfaces
/home/dan/interlay/dev/polkabtc-js/src/interfaces/types.ts
        Generating
        Extracting interfaces for default
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'LookupSource' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Tally' @polkadot/types/interfaces/democracy -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Votes' @polkadot/types/interfaces/collective -> @interlay/polkabtc/interfaces/default
        Writing

/home/dan/interlay/dev/polkabtc-js/src/interfaces/augment-types.ts
        Generating
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'LookupSource' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Tally' @polkadot/types/interfaces/democracy -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Votes' @polkadot/types/interfaces/collective -> @interlay/polkabtc/interfaces/default
        Writing

$ ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --package @interlay/polkabtc/interfaces --endpoint ./src/json/parachain.json --output ./src/interfaces
Generating from metadata, 62,264 bytes
/home/dan/interlay/dev/polkabtc-js/src/interfaces/augment-api-consts.ts
        Generating
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'LookupSource' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Tally' @polkadot/types/interfaces/democracy -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Votes' @polkadot/types/interfaces/collective -> @interlay/polkabtc/interfaces/default
        Writing

/home/dan/interlay/dev/polkabtc-js/src/interfaces/augment-api-errors.ts
        Generating
        Writing

/home/dan/interlay/dev/polkabtc-js/src/interfaces/augment-api-events.ts
        Generating
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'LookupSource' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Tally' @polkadot/types/interfaces/democracy -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Votes' @polkadot/types/interfaces/collective -> @interlay/polkabtc/interfaces/default
        Writing

/home/dan/interlay/dev/polkabtc-js/src/interfaces/augment-api-query.ts
        Generating
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'LookupSource' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Tally' @polkadot/types/interfaces/democracy -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Votes' @polkadot/types/interfaces/collective -> @interlay/polkabtc/interfaces/default
        Writing

/home/dan/interlay/dev/polkabtc-js/src/interfaces/augment-api-rpc.ts
        Generating
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'LookupSource' @polkadot/types/interfaces/runtime -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Tally' @polkadot/types/interfaces/democracy -> @interlay/polkabtc/interfaces/default
                WARN: Overwriting duplicated type 'Votes' @polkadot/types/interfaces/collective -> @interlay/polkabtc/interfaces/default

/home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/util/imports.js:40
  types.forEach(type => {
        ^
TypeError: Cannot read property 'includes' of undefined
    at /home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/util/imports.js:54:21
    at Array.forEach (<anonymous>)
    at setImports (/home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/util/imports.js:40:9)
    at /home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/generate/rpc.js:79:32
    at Array.map (<anonymous>)
    at /home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/generate/rpc.js:50:50
    at Array.map (<anonymous>)
    at /home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/generate/rpc.js:47:29
    at writeFile (/home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/util/file.js:19:19)
    at generateRpcTypes (/home/dan/interlay/dev/polkabtc-js/node_modules/@polkadot/typegen/generate/rpc.js:33:23)
error Command failed with exit code 1
```

**Comment by jacogr** [comment]
Like I said, the RPC does expect an array input. It operates on the `<ROOT>/definitions.ts` keys to extract the RPCs for each of the modules - https://github.com/polkadot-js/api/blob/master/packages/typegen/src/generate/rpc.ts#L42-L45

So, root, as done above is -

```
{
  module1: { rpc: { ... } },
  module2: { rpc: { ... } }
 }
 ```
 
 So what the linked keys does is extract the keys `[module1, module2]` (only those with RPCs) and then generates on those.

**Comment by savudani8** [comment]
So, combining your suggestions, is this the structure that `definitions.ts` should export?
```
/// <ROOT>/assets/definitions.ts
export default {
   rpc: {
     /// rpcs here become `assets_<method>`
     assets: { rpc: { ... }, types: { ... } },
     ...
     /// rpc here become `system_<method>`
     system: { rpc: {... }, type: { ... } }
   },
   types: {
    // no min/max here, it is not a bundle definition
    AssetId: 'u32'
  }

};
```

**Comment by jacogr** [comment]
Depends it is is top-level or not. As part of a module that is included from the root, it is fine. If you want to use it as a top-level definition -

```js
export default {
   assets: { 
     rpc: {
       method: {
         description: "...",
         params: [],
         type: 'Bytes
       }
     },
     types:  {
      AssetId: 'u32'
    }
  },
  system: { 
    rpc: {... },
    types: { 
      Something: 'Bytes'
    }
  }
};
```

**Comment by savudani8** [comment]
Got it, thanks! I realised that everything you've explained was already in here https://polkadot.js.org/docs/api/start/typescript.user. It might be useful to link the `TypeScript user generated` page at the end of `Extending types` and `Custom RPC`

**Comment by savudani8** [comment]
As a takeaway, it is confusing that the rpc definitions structure used in `ApiPromise.create()` cannot be reused when generating the types. Thanks for your detailed explanations!
