### ISSUE TITLE
Error creating a type for batch calls in v3.7.1

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/api#3133]
I have seen the error in the API v3.7.1 when sending for instance a `system.remak` as_multi or a batch of `system.remark` as_multi. This seems to be a regression as it works in 3.6.1.

The following code:
```
const call = api.createType('Call', opaqueCall.toHex())
```

fails with:
```
     Error: createType(Call):: Call: failed decoding utility.batchAll:: Struct: failed on args: {"calls":"Vec<Call>"}:: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Unable to create Enum via index 38, in Id, Index, Raw, Address32, Address20
      at createTypeUnsafe (node_modules/@polkadot/types/create/createType.js:72:11)
      at createType (node_modules/@polkadot/types/create/createType.js:84:10)
      at TypeRegistry.createType (node_modules/@polkadot/types/create/registry.js:297:39)
      at ApiPromise.createType (node_modules/@polkadot/api/base/Decorate.js:168:82)
...
```

Visible in https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-rpc.polkadot.io#/explorer/query/0xd33b6afd92883d17ae7f9d04d77da98d769c9dc23b22809a119a619cbee99e48

**Comment by chevdor** [comment]
This issue probably explains: https://github.com/polkadot-js/apps/issues/4568

**Comment by chevdor** [comment]
If you are at it, you may want to double check that the following works as it fails/failed in 3.6.1:

## first one
- blockHash: `0xf36de4582f35cb7b2f057b803ad7ca4af3c7cccd5cafd00e4389adee526611e9`
- identity.requestJudgement
- successful call

## second 
- blockHash: `0x5ded06d4afb82e47108bfe0307f89e139179c167595a99779f8d62fe8ca30834`
- identity.requestJudgement
- UNsuccessful call (fee too low)

In 3.6.1, both fail with:
```
 Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 18, in Ed25519, Sr25519, Ecdsa
```

**Comment by jacogr** [comment]
3.6.1 will fail - it doesn't have the 48 runtime types.
