### ISSUE TITLE
Error when creating type Vec<Call>

### ISSUE THREAD

**Issue by raynaudoe** [polkadot-js/api#3140]
I'm trying to create a `Vec<Call> `type in the following way:
```
    "Vec<Call>":
      [
        [
          createType(api.registry, "Call", {
            args: [], // AccountId, CompactBalance
            callIndex: [4, 0], // Balance.Transfer
          }),
        ]
      ],
```
On console I'm getting the following:
```
[ERR  ] Utility Batch -----> Error: Assertion failed
[CALL ] {"callIndex":"0x0400","args":{"dest":{"Id":"2CSv6uVqcVVishrZsPZHXpC6kpiXfCZFGHeaPCicZG8rNwtK"},"value":0}}
[ARGS ] calls : Vec<Call>
```

But, creating a `Call` type like this works just fine:
```
    "Call":
      [
        createType(api.registry, 'Call', {
          args: [], // AccountId, CompactBalance
          callIndex: [4, 0],
        }),
      ],
```

(Method `Balance.Transfer` is actually from Polymesh network)

What could be source of the error ?
Thanks!

**Comment by jacogr** [comment]
It does a quite possibly the non-existent compact. 

Generally you don’t want to create Call directly. 

[
api.tx.balances.transfer(toA, valueA),
api.tx.balances.transfer(toB, valueB),
...
]

Is the suggested approach. (Call will instantiate from that)

**Comment by raynaudoe** [comment]
I'm not sure if I understood correctly, if I do:
```
    "Vec<Call>":
      [
        [
          api.tx.balances.transfer("2EV9YPYCTCS1osFsoXVbSZu6cRiR5Z8hUdGt4DViiTLdHmoz", "10"),
        ],
      ],
```
I'm getting the error:

```
[ERR  ] Utility Batch -----> TypeError: Cannot read property 'args' of undefined
[CALL ] {"signature":{"signer":{"Index":"7Fg3MxX3"},"signature":{"Ed25519":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},"era":{"ImmortalEra":"0x00"},"nonce":0,"tip":0},"method":{"callIndex":"0x0400","args":{"dest":{"Id":"2EV9YPYCTCS1osFsoXVbSZu6cRiR5Z8hUdGt4DViiTLdHmoz"},"value":10}}}
[ARGS ] calls : Vec<Call>
```

**Comment by jacogr** [comment]
Not not 100% what your structure look like, but seem like you have a double [

So a Vec is equivalent to [api.tx,...,api.tx], ie. the api.to is the Call data.

**Comment by raynaudoe** [comment]
Great, thanks! 
will try that

**Comment by raynaudoe** [comment]
Hi @jacogr , tried your solution and it works on my code, nice.
I'm still getting an assertion error when trying to use `balances.transfer`, I've tried using other modules and methods and they work just fine. Do you have an idea why `transfer` could be failing ?

**Comment by jacogr** [comment]
Call really should not instantiated tis way - 

```js
createType(api.registry, 'Call', {
          args: [], // AccountId, CompactBalance
          callIndex: [4, 0],
        }),
```

It cannot speak to what it is looking or there, but the only supported ways of doing a call is via `api.tx.*`, via hex or via Uint8Array, objects are generally expected to be either Call or Extrinsic, not user-constructed. There is quite a bit of info it tries to pull in terms of metadata that is most-probably missing in this specific case. 

TL:DR Have no idea, would look at PRs that addresses this specific usecase and makes it work, but it is not something I'll investigate myself since Call is not _quite_ a "normal" type or actually setup to cater for a user-defined object type in the construction.
