### ISSUE TITLE
API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights)

### ISSUE THREAD

**Issue by spaceforce-dev** [polkadot-js/api#3141]
The api is suddenly not initializing the same way it did a week ago. I get these errors.

Any ideas?

API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (Init.js:87)

 REGISTRY: Error: Cannot construct unknown type BlockWeights
    at new DoNotConstruct (DoNotConstruct.js:21)

**Comment by xianggy** [comment]
Hi, @spaceforce-dev , I got the  same issue.  What is this problem?

**Comment by xianggy** [comment]
Solved, just upgrade @polkadot/api to the latest version.

**Comment by spaceforce-dev** [comment]
Yes, that was our fix too.
