### ISSUE TITLE
txVersion from metadata

### ISSUE THREAD

**Issue by emmanuelm41** [polkadot-js/api#3144]
I need to get the transaction version from a specific metadata version I requested to the rpc api.

The current transactionVersion is available on 
`await api.runtimeVersion.transactionVersion.toString();`

I am not sure where I can find that value in, for example, the version 2011 metadata.

Network: Kusama
SpecsVersion: 2011
BlockNumber: 2832534

`const blockHash = await api.rpc.chain.getBlockHash(blockNumber)`
`metadata = await api.rpc.state.getMetadata(blockHash);`

**Comment by jacogr** [comment]
This should do the trick -

```js
const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
const rt = api.rpc.state.getRuntimeVersion(blockHash);

console.log(rt.transactionVersion.toString());
```

**Comment by emmanuelm41** [comment]
I worked perfectly! Thank you so much.
