### ISSUE TITLE
ERROR: Maximum call stack size exceeded error for a block

### ISSUE THREAD

**Issue by sollover** [polkadot-js/api#3145]
hi,

When I ran this

` const signedBlock = await api.derive.chain.getBlock(block_hash) // **for Block: 3610901  and Blockhash: 0x5b2f957044d16b356034ab5251a5681d8734d8fcfe297980c5e22ef9377d5648**`

I got this error:

` REGISTRY: Error: Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded`

I didn't get transactions info for this blockhash...  what is this? How can I fix??

thank you

**Comment by jacogr** [comment]
Which chain?
Which version of the API?

**Comment by jacogr** [comment]
The reson for asking is that Polkadot had an issue on some blocks, this was fixed as part of this https://github.com/polkadot-js/api/issues/3055 in the 3.5.1 version

**Comment by sollover** [comment]
hi  @jacogr, the version polkadot/api 3.3.2

**Comment by jacogr** [comment]
Yes, that is before the 3.5.1 release mentioned above. (The above block, on Polkadot, indeed decodes correctly with current API version, i.e. the apps UI displays it)
