### ISSUE TITLE
Could not convert parameter `tx` between node and runtime: Error decoding field CheckMortality.0

### ISSUE THREAD

**Issue by milseg** [polkadot-js/api#3153]
I tried to use polkadot-js libray to run a simple app for transferring tokens between Dusty accounts on plasm. Source code and package.json for running the snippet is found on [this git repo](https://github.com/milseg/plasm-simple-transfer.git)

**Node version:** v12.8.2
**Yarn version:** 1.22.5

`require('dotenv').config();

const { ApiPromise, WsProvider } = require('@polkadot/api')
const { Keyring } = require('@polkadot/keyring')
const plasmDefinitions = require('@plasm/types/interfaces/definitions');
const jsonDefinitions = require('./types.js')
const fs = require('fs')
const BN = require('bn.js')

startChain()

async function startChain() {
  console.log("trying connection to ", process.env.RPC_URL)
  const targetAddress = process.env.TARGET_ADDRESS
  const provider = new WsProvider(process.env.RPC_URL)
  const types = Object.values(plasmDefinitions).reduce(
      (res, { types }) => ({ ...res, ...types }),
      {},
  );

  const api = new ApiPromise({
      provider,
      types
  });

  api.on('connected', () => console.log(`Connected to ${process.env.RPC_URL}`));
  api.on('disconnected', () => console.log(`Disconnected from ${process.env.RPC_URL}`));
  await api.isReady;
  const [chain, nodeName, nodeVersion] = await Promise.all([
    api.rpc.system.chain(),
    api.rpc.system.name(),
    api.rpc.system.version()
  ])

  console.log(`You are connected to chain ${chain} using ${nodeName} v${nodeVersion} - ${process.env.RPC_URL}`)

  const keyring = new Keyring({ type: 'sr25519' })
  const fromPair = keyring.addFromUri(process.env.PLASM_MNEMONIC)
  const fromAmountUnits = new BN('1000000000000000')
  const transfer = api.tx.balances.transfer(targetAddress, fromAmountUnits)      
  // send value
  //const nonce = await api.query.system.accountNonce(process.env.FROM_ADDRESS)
  const nonce = await api.rpc.system.accountNextIndex(process.env.FROM_ADDRESS)
  console.log("got nonce", nonce)
  const txHash = await transfer.signAndSend(fromPair, {nonce})

}`

Stack trace: 

`trying connection to  wss://rpc.dusty.plasmnet.io/
Connected to wss://rpc.dusty.plasmnet.io/
You are connected to chain Dusty using Plasm Node v1.6.1-cf15b11-x86_64-linux-gnu - wss://rpc.dusty.plasmnet.io/
got nonce Type {
  negative: 0,
  words: [ 0 ],
  length: 1,
  red: null,
  registry: TypeRegistry {}
}
2021-02-05 21:00:27        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: Error decoding field CheckMortality.0: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: Error decoding field CheckMortality.0
(node:13572) UnhandledPromiseRejectionWarning: Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: Error decoding field CheckMortality.0: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: Error decoding field CheckMortality.0
    at RpcCoder._checkError (<mydir>\examples\plasm-simple-transfer\node_modules\@polkadot\api\node_modules\@polkadot\rpc-provider\coder\index.js:84:13)
    at RpcCoder.decodeResponse (<mydir>\examples\plasm-simple-transfer\node_modules\@polkadot\api\node_modules\@polkadot\rpc-provider\coder\index.js:47:10)
    at WsProvider.value (<mydir>\examples\plasm-simple-transfer\node_modules\@polkadot\api\node_modules\@polkadot\rpc-provider\ws\index.js:214:90)
    at W3CWebSocket.value [as onmessage] (<mydir>\examples\plasm-simple-transfer\node_modules\@polkadot\api\node_modules\@polkadot\rpc-provider\ws\index.js:194:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (<mydir>\examples\plasm-simple-transfer\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onMessage (<mydir>\examples\plasm-simple-transfer\node_modules\websocket\lib\W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (<mydir>\examples\plasm-simple-transfer\node_modules\websocket\lib\W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (<mydir>\examples\plasm-simple-transfer\node_modules\websocket\lib\WebSocketConnection.js:554:26)
    at <mydir>\examples\plasm-simple-transfer\node_modules\websocket\lib\WebSocketConnection.js:323:40
(node:13572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Additionally when i try to do a clear run (delete node_modules and reinstall) i get the same message but with field CheckMortality replaced by CheckNonce. Fields returned by plasm-types library can be found in [this file](https://github.com/milseg/plasm-simple-transfer/blob/main/types.js) in json format

**Comment by jacogr** [comment]
Assuming you are using a current API, see the release notes - https://github.com/polkadot-js/api/releases/tag/v3.7.1

The `types.js` above does not specify an `Address` type. 

See https://polkadot.js.org/docs/api/FAQ/#i-cannot-send-transactions-sending-yields-decoding-failures for the options available, matching to the chain.

**Comment by milseg** [comment]
I got it solved [here](https://github.com/milseg/plasm-simple-transfer/commit/6346138e6d7ced5ccd5cf3a2bd0a11b01d628787). I changed Address type from `{ "Address": "AccountId", "LookupSource": "AccountId" }` to `{ "Address": "IndicesLookupSource", "LookupSource": "IndicesLookupSource" }`

**Comment by jacogr** [comment]
It is an issue - however Substrate is pushing really hard for MultiAddress as the type that solves all issues. 

So really hoping chains will follow the lead of Kusama/Polkadot and adapt it. It will make things much easier in the ecosystem. (A number of chains have already adopted the ne format)

saldly from and API perspective there is no way to detect it. So it is a hurdle atm.
