### ISSUE TITLE
majority support calculation incorrect

### ISSUE THREAD

**Issue by moonrocket16** [polkadot-js/api#3156]
Hi,
I have been looking at the latest Kulupu vote and it appears that the majority support calculation is incorrect compared to the polkadot wiki calculation.
On top of this the vote is going from approve to reject (green to red) without any votes changing.
please see attached my calculations vs the polka wiki and the video of the vote decision changing with no votes changing.

![IMG_0297](https://user-images.githubusercontent.com/78681761/107142793-68844d80-6985-11eb-8ec3-0f9fd0bd5143.jpg)
![IMG_0299](https://user-images.githubusercontent.com/78681761/107142802-6e7a2e80-6985-11eb-914f-30dc49a66d31.jpg)

**Comment by moonrocket16** [comment]
video

https://user-images.githubusercontent.com/78681761/107142952-4f2fd100-6986-11eb-83e5-5c6a48b4ac5c.MOV

**Comment by jacogr** [comment]
The green to red is correct- since the totalIssuance is part of the calculation, when that changes the outcome can change without any votes changing. 

All of votes, convictions and issuance are inputs.

**Comment by moonrocket16** [comment]
please see my calculations jaco, they are very big difference to being close. it shouldnt be changing from green to red

**Comment by moonrocket16** [comment]
I also have consensus with Hacklick on Kulupu discord.

**Comment by jacogr** [comment]
This is the actual implementation on the Rust side, i.e. it is the source of truth as to how it is handled on the node - https://github.com/paritytech/substrate/blob/master/frame/democracy/src/vote_threshold.rs#L78-L88

Which is - 

```rust
	fn approved(&self, tally: Tally<Balance>, electorate: Balance) -> bool {
		let sqrt_voters = tally.turnout.integer_sqrt();
		let sqrt_electorate = electorate.integer_sqrt();
		if sqrt_voters.is_zero() { return false; }
		match *self {
			VoteThreshold::SuperMajorityApprove =>
				compare_rationals(tally.nays, sqrt_voters, tally.ayes, sqrt_electorate),
			VoteThreshold::SuperMajorityAgainst =>
				compare_rationals(tally.nays, sqrt_electorate, tally.ayes, sqrt_voters),
			VoteThreshold::SimpleMajority => tally.ayes > tally.nays,
		}
	}
```

So for super-majority (which most community referendums are), it is

`compare_rationals(tally.nays, sqrt_voters, tally.ayes, sqrt_electorate)`

The tally comes from the actual referendum state itself. The JS side for this is at https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/democracy/util.ts#L68

Which is the following 

`compareRationals(votedNay, sqrtVoters, votedAye, sqrtElectorate)`

The compare-rationals function is the same between both sides, see

https://github.com/paritytech/substrate/blob/master/frame/democracy/src/vote_threshold.rs#L46-L71
vs
https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/democracy/util.ts#L35-L60

**Comment by moonrocket16** [comment]
> This is the actual implementation on the Rust side, i.e. it is the source of truth as to how it is handled on the node - https://github.com/paritytech/substrate/blob/master/frame/democracy/src/vote_threshold.rs#L78-L88
> 
> Which is -
> 
> ```rust
> 	fn approved(&self, tally: Tally<Balance>, electorate: Balance) -> bool {
> 		let sqrt_voters = tally.turnout.integer_sqrt();
> 		let sqrt_electorate = electorate.integer_sqrt();
> 		if sqrt_voters.is_zero() { return false; }
> 		match *self {
> 			VoteThreshold::SuperMajorityApprove =>
> 				compare_rationals(tally.nays, sqrt_voters, tally.ayes, sqrt_electorate),
> 			VoteThreshold::SuperMajorityAgainst =>
> 				compare_rationals(tally.nays, sqrt_electorate, tally.ayes, sqrt_voters),
> 			VoteThreshold::SimpleMajority => tally.ayes > tally.nays,
> 		}
> 	}
> ```
> 
> So for super-majority (which most community referendums are), it is
> 
> `compare_rationals(tally.nays, sqrt_voters, tally.ayes, sqrt_electorate)`
> 
> The tally comes from the actual referendum state itself. The JS side for this is at https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/democracy/util.ts#L68
> 
> Which is the following
> 
> `compareRationals(votedNay, sqrtVoters, votedAye, sqrtElectorate)`
> 
> The compare-rationals function is the same between both sides, see
> 
> https://github.com/paritytech/substrate/blob/master/frame/democracy/src/vote_threshold.rs#L46-L71
> vs
> https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/democracy/util.ts#L35-L60
> 
> On both the JS & Node side the calculations are only done on integer numbers, hence the rational compare. Same with the sqrt of the numbers, these don't actually have the decimals attached. (This does have an impact when compared to non-integer calculations. There are no floating-point numbers used in the runtime.)

Hi Jaco,
Either the Polka Wiki is wrong with its calculation or the code is.
The example and my figures matched with calculation on the Polka Wiki, the error seems to be with how the formulae is written into the code or the Polka Wiki calculation is wrong and needs to be fixed.

**Comment by moonrocket16** [comment]
Either way the Kulupu vote needs to be passing right now which it is not.

**Comment by jacogr** [comment]
The implementation does match the wiki - the differences are that it is only working with integers. So for instance assume that the turnout is `15360`, the sqrt would be `123` when working with integers, but `123.935` when working with non-integers.

e.g. in the Rust node code, this is the following `let sqrt_voters = tally.turnout.integer_sqrt();` (non-floating point, hence the integer-sqrt)

**Comment by moonrocket16** [comment]
right now
against / SQRT turnout < approve / SQRT electorate
2.0911m / SQRT 9.663 < 7.5719 ? SQRT 36.1287

= 672.69595 < 1259.734

should be passing but is not.

**Comment by jacogr** [comment]
So atm, with the exact numbers from the state -

- aye: 7571933624600000000
- nay: 2091171000000000000
- turnout: 2645891112300000000
- issuance: 36129274096508281926

For the roots

- sqrt(turnout): 1626619535
- sqrt(issuance): 6010763187

For the various sides -

- left (nay / sqrt(turnout)): 2091171000000000000 / 1626619535 = 1285593191.9
- right (aye / sqrt(issuance)): 7571933624600000000 / 6010763187 = 1259729154.02

the difference -

- left-right: (1285593191.9 - 1259729154.02) = 25864037.88

Your turnout numbers are wrong, see the actual state, the turnout is part of the referendum info -

![image](https://user-images.githubusercontent.com/1424473/107146282-600d2200-6947-11eb-84ef-13c689af62d4.png)

**Comment by jacogr** [comment]
With inexact numbers, the same outcome is derived -

- nay / sqrt(turnout): 2.0911 / sqrt(2.6458) - 1.2855716777
- aye / sqrt(issuance): 7.5719 / sqrt(36.1287): 1.25973356851

Outcome with inexact: 1.2855716777 > 1.25973356851

**Comment by moonrocket16** [comment]
Ok thanks I see my error
