### ISSUE TITLE
ERROR:createType(ExtrinsicSignatureV4):: Unable to create Enum via index 76, in Id, Index, Raw, Address32, Address20

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/api#3161]
Hi, after I upgraded polkadot/api to the latest version 3.8.1, I found that the transfer operation reported an error.
`createType(Extrinsic):: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 76, in Id, Index, Raw, Address32, Address20'` 

At this time, the node I was connected to was an external node of Kusama, and the runtimeVersion was 2028. it seems that the Address type is different,  how can I solve it? Looking forward to your reply

**Comment by jacogr** [comment]
3.8.1 does have the latest runtime types for Kusama 2028, so this is quite weird.

**Comment by Wangmmx** [comment]
> 3.8.1 does have the latest runtime types for Kusama 2028, so this is quite weird.
> 
> Are you injecting any specific types into the API itself?

Solved this problem by changing the registry to 

{
   Address: 'MultiAddress',
   LookupSource: 'MultiAddress'
}

Problem solved and close the issue

**Comment by jacogr** [comment]
For Kusama, Polkadot, Westend you don't need to inject any types.

**Comment by Wangmmx** [comment]
> For Kusama, Polkadot, Westend you don't need to inject any types.

I build the transaction offline, if you remember https://github.com/polkadot-js/api/issues/1421

**Comment by jacogr** [comment]
Ahhh, ok. Sorry, after some time I know the names (like yours), but really cannot remember the specifics of the projects :)
