### ISSUE TITLE
Why are there always so many breaking change？

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/api#3162]
Every time the blockchain upgrade the polkadotjs always have to be updated, otherwise the App won't work. 
For users, this chain gives them the impression of being unstable and prone to unexpected situations.

Is there a way to do compatibility protection?

**Comment by jacogr** [comment]
There is a long-term plan in Substrate to expose the actual type definitions via the metadata. Until such time, the API needs to be kept updated - each upgrade on Substrate changes types, for instance in the latest round on Kusama, there has been -

- AccountInfo updates (these the API can detect and injects automatically)
- ValidatorPrefs updates (as above, this the API can and does detect)
- Adrress updates (AccountId -> MultiAddress, these cannot be detected)
- Keys updates (5 -> 6 entries, cannot be detected)
...

**Comment by xwartz** [comment]
However, we can't update it in time, especially for non-web apps, and we always know when there is feedback from users that it's not working.

**Comment by jacogr** [comment]
The 3.7.1 API release, 9 days ago, had all the changes required for Kusama 2028, Polkadot 28 - as indicated in the CHANGELOG for that version, so it is not a day's notice from the JS API perspective. I do agree that in this case the voting period for the upgrade on Kusama was quite short.

**Comment by xwartz** [comment]
As you can imagine, if you're developing an iOS App and you have breaking change updates, you have to release a new version of the App and there's simply not enough time. Not all apps are web-based.

**Comment by jacogr** [comment]
I understand that very well. Also dealing with app stores on multiple fronts and random delays in approvals on all of them. 

Kusama will always move very fast. The API always gives indication (like 9 days ago) when it knows a breaking change will go in to ensure dev has a much time as possible from me knowing to them knowing to enable updates. 

So apart from that there is nothing I can do so you don’t need to care about updates. Well, not yet anyway, there may be a solution with a central downloadable registry in a week or two can address most of the type-only updates.
