### ISSUE TITLE
Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/api#3164]
Suddenly this error was reported when I transferred Kusama today. It may have something to do with the chain upgrade, but I'm not sure.

The metadata spec version is 2028.

```
"@polkadot/api": "^3.8.1"
```

**Comment by jacogr** [comment]
I've done a couple of transfers (& payouts, etc) since the upgrade went through. (Same on Westend which runs the same code).

- Do you have any specific types injected? like` Address`?
- Which RPC node are you connected to (wondering f it is still on .27, although that should still match)

**Comment by xwartz** [comment]
> * Do you have any specific types injected? like` Address`?
> * Which RPC node are you connected to (wondering f it is still on .27, although that should still match)

1. No, there is no injection
2. We use the self-built node, the specVersion is 2028, node url is `https://kusama-mainnet.token.im`

**Comment by joelamouche** [comment]
I have the same error when trying to register the current version of moonbeam to its compatible polkadot version (71a528e822af63b96bdb03efac9b4927fb11a25e)
`RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable })): RuntimeApi, Execution failed: Wasmi, Trap, Trap { kind: Unreachable }`

**Comment by crossle** [comment]
I have the same error, I use offline sign transaction, use RPC author_submitExtrinsic  broadcast, it's ok when on polkadot runtime 27.
```
{"jsonrpc":"2.0","error":{"code":1002,"message":"Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))","data":"RuntimeApi(\"Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))\")"},"id":1614159077243671000}
```

**Comment by joelamouche** [comment]
Turns out I was loading the wrong specs
