### ISSUE TITLE
Could not decode `MultiAddress`, variant doesn\'t exist

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3166]
<img width="1747" alt="Screenshot 2021-02-10 at 17 38 03" src="https://user-images.githubusercontent.com/16758383/107540854-ceabe300-6bc6-11eb-864c-ec60c5343449.png">

When using polkadot-launch with polkadot at commit `71a528e8` and making a call on the api to register the chain:

```
const unsub = await api.tx.sudo
      .sudo(api.tx.parasSudoWrapper.sudoScheduleParaInitialize(id, genesis))
      .signAndSend(alice, { nonce: nonce, era: 0 }, (result) => {
        console.log(`Current registration status is ${result.status}`);
        if (result.status.isInBlock) {
          console.log(
            `Transaction included at blockHash ${result.status.asInBlock}`
          );
        } else if (result.status.isFinalized) {
          console.log(
            `Transaction finalized at blockHash ${result.status.asFinalized}`
          );
          unsub();
          console.log("one REGISTRATION DONE");
          resolvePromise();
        }
      });
```

**Comment by jacogr** [comment]
You need to ensure you use the Rococo v1 branch. Sadly between master and deployed there is a conflict -

- Rococo (from the v1 branch) had version 200 with `Address = AccountId`, at runtime 202 it jumped to `MultiAddress`
- Polkadot master never updated the spec version, so the master branch went from AccountId -> MultiAddress without bumping

TL:DR Unless using the rococo-v1 branch, Polkadot master is out-of-sync. (And there is nothing the types can do to fix it, it is set for the v1 branch, here https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/rococo.ts#L43-L57)

If all else fails, add the MultiAddress manually of bump the spec version to at least 202

**Comment by joelamouche** [comment]
Ha I see good to know. And `rococo-v1` will always be synced with the latest version?

**Comment by joelamouche** [comment]
>bump the spec version to at least 202

If I bump the spec version of the master-spawned relaychain to 202 I will have the same version as the running rococo?

How do I do that?

**Comment by joelamouche** [comment]
And sorry if Im not understanding correctly, but how do I add MultiAddress? 
I tried:
```
MultiAddress":{
 "_enum": {"Id":"AccountId", "Index":"AccountIndex", "Raw":"Vec<u8>","Address32":"[u8; 32]"," Address20":"[u8; 20]"}
}
```
and it didnt work

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

**Comment by joelamouche** [comment]
Either using `rococo-v1` or the master branch with injected types resolves the problem.

However, now I have this error: 
```
2021-02-10 19:14:54  [Relaychain] failed to handle new activations err=Runtime(RuntimeApiError("Execution(Wasmi(Function(\"Module doesn\\\'t have export ParachainHost_full_validation_data\")))"))
```

How do I apply the 202 runtime updgrade to my relaychain node?

**Comment by jacogr** [comment]
No idea, best is really the Rococo channel. (I don't operate, only use). The v1 branch doesn't need types. All I know from the Rococo chat is that the v1 branch is the recommended version. There could be some changes, since I know the devs said there is upgrades planned shortly.

**Comment by joelamouche** [comment]
Ok thanks :)
