### ISSUE TITLE
Result<T,E> type not compatible with json-serialized value from Rust

### ISSUE THREAD

**Issue by modbrin** [polkadot-js/api#3170]
With typegen it's possible to define type as e.g. `ResultType: 'Result<Balance, DispatchError>'` which is converted to 
```
export interface ResultType extends Result<Balance, DispatchError> {
  readonly isError: boolean;
  readonly asError: DispatchError;
  readonly isOk: boolean;
  readonly asOk: Balance;
}
```
It means that the definition is incompatible with default Rust's json-serialized value for `sp_std::result::Result`, which uses 'Err' instead of 'Error', therefore when used in custom RPCs:
```
Error: createType(Result<BalanceInfo, DispatchError>):: Cannot map Enum JSON, unable to find 'Err' in ok, error
```
Quick workaround to make separate enums works, however the question - is this Result<T,E> corresponds to different type?
```
ResultBalance: {
    _enum: {
        Ok: 'Balance',
        Err: 'DispatchError'
    }
}
```

**Comment by jacogr** [comment]
They should be consistent. Not sure where the mismatch comes from, it really could have been for an older version (Result is ancient), however certainly an issue. It should really be as simple as `s/Error/Err/` here - https://github.com/polkadot-js/api/blob/master/packages/types/src/codec/Result.ts#L19 (and then in the getter)

It would be good to have an actual JSON that fails serialization as well to add a test - the only test there is from actual bytes serialization. Do you have a failing JSON that can be added?

**Comment by modbrin** [comment]
I can think of simple case like this:
```
ResultBool: 'Result<bool, DispatchError>'
...
api.createType('ResultBool', { "Ok": "true" }); // passes
api.createType('ResultBool', { "Err": { "Module": { "error": 1, "index": 1, "message": "SomeMessage" } } }); // fails
```

**Comment by jacogr** [comment]
Yes, always just prefer a specific example from actual RPC.
