### ISSUE TITLE
Mysterious Balance Changes

### ISSUE THREAD

**Issue by migueldingli1997** [polkadot-js/api#3178]
Related to #2497

I've been trying to get the full list of balance changes for particular addresses but it seems that in the earlier days of Kusama (approx before block 1,600,000) there were balance changes that do not appear in explorers. I'll present an example below:

For address: `DNDBcYD8zzqAoZEtgNzouVp2sVxsvqzD4UdB5WrAUwjqpL8`

Balance at block 1001763:
- free: `5203350055228163`
- reserved: `10010000000000`

Balance at block 1001764:
- free: `5204526678206167` [+`1176622978004`]
- reserved: `10010000000000` [unchanged]

I expect to see some event at [block 1001764](https://polkascan.io/kusama/block/1001764) with the balance change (`1176622978004`) visible somewhere. Are there other places that I should be looking at for such balance changes?

**Comment by jacogr** [comment]
1002764 was the start of a new staking era - at that point of the chain the rewards were automatically paid, i.e. nobody needed to claim. So you will see staking rewards.

**Comment by migueldingli1997** [comment]
Thank you, that's very useful information. I assume the specific value that was given to each validator is not available via the API unless we get the balance before and balance after like I did in the original description. By any chance is there a way to get the era points (especially at a specific block like 1002764 for example) using the API?

**Comment by jacogr** [comment]
The block heights are only query-able via events. As for the points, I really cannot recall where they were stored in the state at that point. 

Possibly in the same imOnline location as now. It has been ages, really don’t have a recollection - changes come in hard and fast.

**Comment by migueldingli1997** [comment]
Ok, no problem. One last thing then... Is there a way to query block heights by events? Or would one need to iterate over all blocks and check the events of each block to find out if the block marks the era start/end?

**Comment by jacogr** [comment]
Since you can only get historic events with `api.query.system.events.at(<bockHash>)` it is an iteration process. (If you run a local archive node, you can use the `.range` query, assuming you run with unsafe flags)

**Comment by migueldingli1997** [comment]
Ok, thank you! Closing the issue.
