### ISSUE TITLE
Examples of interaction with the crowdload module 

### ISSUE THREAD

**Issue by ppoliani** [polkadot-js/api#3183]
Is it possible to interact with the crowdloan module?

**Comment by jacogr** [comment]
Sure, the API will decorate all the modules and endpoints as it receives from the metadata. So if you connect to a chain with that module active, the endpoints (queries, constants, extrinsics) is available. 

The intro here details the API decoration from what the chain provides.

**Comment by ppoliani** [comment]
Thank you @jacogr for the prompt response.

>  The intro here details the API decoration from what the chain provides.

Was this supposed to have a link to some into guide?

**Comment by jacogr** [comment]
Sorry, was mean to be this intro here - https://polkadot.js.org/docs/api/start/basics

**Comment by ppoliani** [comment]
> Sorry, was mean to be this intro here - https://polkadot.js.org/docs/api/start/basics

No worries mate :)

Thanks for that clear. I still though believe that a somewhat step by step guide for the crowdloan module would super helpful and will avoid any misconceptions from the developers' side.

**Comment by jacogr** [comment]
The is out of the scope for the API, it only provides the interfaces - for specific use of the Modules, you need to refer to the team creating those modules. The source of truth is always the Rust modules if you are unsure of any calls and their interactions.
