### ISSUE TITLE
API/INIT: Error: You need to pass a valid Metadata instance to Decorate

### ISSUE THREAD

**Issue by Deekor** [polkadot-js/api#3185]
Ive converted my js to ts and am now getting this error when creating an `ApiPromise`. Im unable to find any docs around a MetaData instance.

my initializer lines:

```
const provider = new WsProvider('wss://rpc.polkadot.io');
api = await ApiPromise.create({provider});
```

**Comment by jacogr** [comment]
This could happen when the `@polkadot/metadata` and `@polkadot/api` versions are mismatched. Which version of the API are you using. (The latest versions I believe do check for mismatches, but not sure it is between packages)

So basically when it initializes it checks that the instance is valid. So would suggest -

- list the versions of `@polkadot/{api, metadata, types}`
- ensure they are all pointing to the same version

**Comment by Deekor** [comment]
```
    "@polkadot/api": "^3.9.3",
    "@polkadot/metadata": "^3.9.3",
    "@polkadot/types": "^3.9.3"
```

**Comment by jacogr** [comment]
If they are all aligned, it will work. So check you package-lock or yarn.lock for duplicates. (`npm list @polkadot/metadata` will show if there are duplicates and why as well, `yarn dedupe` will cleanup duplicates, not sure about the npm command)

**Comment by Deekor** [comment]
All the versions were the same in the lock file. Running `npm dedupe` seems to have fixed it. Thanks!

**Comment by jacogr** [comment]
Really weird. But glad you are operational.
