### ISSUE TITLE
Transaction encoding

### ISSUE THREAD

**Issue by shaunxw** [polkadot-js/api#3186]
I tried to use polkadot-js api to encode a transaction, in order to send a [`Xcm::Transact` message](https://github.com/paritytech/xcm-format#transact), by this:

```javascript
const init = api.tx.hrmp.hrmpInitOpenChannel(5000, 8, 1024);
console.log(init.toHex());
```

The result is `0x3c041600881300000800000000040000`, but it is different with by doing it in rococo runtime `0x1600881300000800000000040000`. The later is the correct one which is accepted by rococo relay chain.

Is there a way in polkadot-js to get the correct encoded transaction? In the above case, the only difference is the leading bytes `3c04`, not sure where is this part from.

**Comment by jacogr** [comment]
The `toHex` does not add the length prefixes. So if you want the data with prefix, `u8aToHex(init.toU8a())`.

**Comment by shaunxw** [comment]
[Here](https://github.com/shaunxw/polkadot/blob/6f2ecd49fb74edc4446ccd6dbfde86552981d68f/runtime/rococo/src/lib.rs#L883-L893) is the rust code I used to get correct encoded call. The bytes are shorter than hex generated by `init.toHex()`.

**Comment by jacogr** [comment]
Yes, it won't match. The hex in the Rust includes the compact length. So on the JS side, when you pass the call through, you need to pass the hex value through and it will add the length encoding (assuming the param s `Vec<u8>`)

**Comment by shaunxw** [comment]
Based on the context I think the encoded bytes is for a `Call`, the value is passed to XCM executor [here](https://github.com/paritytech/polkadot/blob/7971054317f06bbbb4347e4c744cc2b2a8c7dd9d/xcm/xcm-executor/src/lib.rs#L90):

```
(origin, Xcm::Transact { origin_type, call }) => {
    // -- snip --
    let message_call = Config::Call::decode(&mut &call[..]).map_err(|_| XcmError::FailedToDecode)?;
}
```

As mentioned, the value was put in `Xcm::Transact` message as `call` field. The message was send from a parachain to relay chain, and finally got executed in XCM executor as above.

**Comment by jacogr** [comment]
"One kind of such a message is `Xcm::Transact`. This upward message can be seen as a way for a parachain to execute arbitrary entrypoints on the relay-chain. `Xcm::Transact` messages resemble regular extrinsics with the exception that they originate from a parachain."

An extrinsic is length-prefixed. So the that would mean it is an encoded call with a length prefix. In that case, `compactAddLength(call.toU8a())` would create the correct format.

So one of the two would work, either with or without. Really cannot see the explicit argument type in the above.

**Comment by jacogr** [comment]
Lemme circle back to the start - 

`0x3c041600881300000800000000040000`
 vs
 `0x1600881300000800000000040000`

So actually it is the method-only part. So ignore my comment just above.

Do the following to get the call-only without the version info -

`inner.method.toHex()` 

That will align, no version only the encoded method.

(the `3c` above is the length, the `04` is the version of the transaction, so it is full tx-encoding - here you only want the actual call part)

**Comment by shaunxw** [comment]
`init.method.toHex()` works perfectly well. Thanks!
