### ISSUE TITLE
Incorrect Weight type.

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/api#3187]
The type returned by `api.query.system.blockWeight` seems to have been confused `api.consts.system.blockWeights`.

The correct types to be decoded are: 

- `api.query.system.blockWeight`: Should be `frame_system::ConsumedWeight` which is just an alias for `frame_support::weights::PerDispatchClass<Weight>`, which is a struct with 3 values of `u64`.
- `api.consts.system.blockWeights` Should be `frame_system::limits::BlockWeights`, which is a more detailed struct with `max_block` and whatnut. 

In the current api, the former is seemingly using `PerDispatchClass<BlockWeights>`, instead of `PerDispatchClass<Weight>`. 

Example from the current UI on Kusama: 

<img width="1561" alt="Screenshot 2021-02-19 at 09 43 38" src="https://user-images.githubusercontent.com/5588131/108487239-f3731b00-7296-11eb-9690-302e149af7ab.png">

**Comment by jacogr** [comment]
It does return ConsumedWeight. It is decorated from metadata.

The `ConsumedWeight` is probably wrong with `BlockWeights`. There is no such thing as generics in this world, so with all the `Per*` quite possible that something is not right, untangling all these Rust definitions is not for the faint-of-heart.

**Comment by kianenigma** [comment]
Indeed: 

> The ConsumedWeight is probably wrong with BlockWeights

A temp fix that I did for now is to pass

```
types: {
	ConsumedWeight: { normal: 'u64', operational: 'u64', mandatory: 'u64' },
}
```

to the `api` initializer.
