### ISSUE TITLE
Issue with signAndSend method.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/api#3188]
Hi ! on the following [chain](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.rialto.brucke.link&types=eNp9VdtOGzEQ%2FRW0TyDtQ7kEUYqQuFVEBYISRB8qtDLrya7Lxt76QptG%2FHtn1t5rkr55Zs4ZH3tm7FV0wbkGY6LT6CJNlZN2zKM4ulPqzZUz5XQKg9C9KArmLguVvt0yk2P0drR%2F0A88uMUraAy54yOMTAUrrOpRDkbH%2FUBLOWyT3QLj5FxFJdMgbRLoQw1xJGv6lVqULLVna2rOEWUss5BopezGJPDHaiGNSM12DBcZmDZ07c2PWnGwUXGhMrrVZ0iDFh8aW1icD%2FHkJE4CeA5aTGxenYbY7oSkXzibKy2sAHOVM5lRWSha%2B5djTjAfM09awHTbEWbAiudPGAoLZClpQBpHgtu1RwYcWo8aptgFYkF7d4wPPE23uMNyh2hT4fWqI0ILngHvplkX3gU12dbbrgHW7dPvpjgaL0qlbRtfRXmN7DPjSMMvJ3BAkp%2FOWDEXKbNCSQS%2BKkV3IkwyF5IV4i%2Fw1mtEhr4k9weZlMQ5Gx6x6oKmfDOouoa1Zaa5q6N3ApsK84JNBO2DaBxG5E%2BhYEvQaPSntHL8cCdfdo5eyJTY%2BjKFyu0nnMmOdY9PAMvgQSGmGdvgrFC7Yx7voHuv9X%2BDZdXnmMiLCilxGCnNKd17Ny2qHctXVMiD6KFkH6Qs18wyyq09sJ6j3W6%2BeKdvNTexR3NQMGOTVMm50AvgSaVog6CJs2ubFvhGIDkDCRqXW8i0RYXTkIJ43w5TBSeYk6V28j9Sgl2rKNmyUIyuNQQegyOO5kD8S4Y336PWiO6zUR8wQL5WVF%2FeOtTQVlHKCpr3lo7Nlwlq9yuMTLyBbVhCmrxjXfwo%2BBf7N4gspwfnu1%2Bgrg6p%2B7j5byU8T7vUUU9MZ2BDM5CTOvfw8AVr7AorZjhOoONmzazTQDyfqeUFWvUidZi93W%2F4wWi0%2F7n9hGZ64LhJucEabM5W7b0tof8IOwm9o5vweEQJP%2F4BnQyCTg%3D%3D) any extrinsic performed retrieved the following error:

`RPC-CORE: accountNextIndex(accountId: AccountId): Index:: -32602: Invalid params: UnknownVersion.`
`VM93 react_devtools_backend.js:2430 signAndSend: error: Error: -32602: Invalid params: UnknownVersion.`

Also i have executed the following code in order to verify the sign:

`
		const keyring = new Keyring({ type: 'sr25519' });
		const alice = keyring.addFromUri('//ALICE');
		const message = stringToU8a('this is our message');

		const signature = alice.sign(message);
		const isValid = alice.verify(message, signature);
		console.log(`The signature ${u8aToHex(signature)}, is ${isValid ? '' : 'in'}valid`);

		const call = targetApi.tx.system.remark('bytes');

		const bridgeMessage = sourceApi.tx
			.bridgeMillauMessageLane
			.sendMessage('0x1234', {
				call,
				origin: {
					SourceRoot: 'SourceRoot'
				},
				spec_version: 5,
				weight: 1000

			}, '122345');

		bridgeMessage.signAndSend(alice);
`

Even if the payload of the message might be wrong the important piece of information here is that with a valid signature, the call fails with the issue:

`RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature`

This is the  [repo](https://github.com/paritytech/parity-bridges-common) for the bridges project in case  the types need to be checked.

**Comment by jacogr** [comment]
Have you adjusted to the correct `Address` types for your chain?

**Comment by hbulgarini** [comment]
Do you mean adding the following two objects in additional types field?

`  "Address": "AccountId",
  "LookupSource": "AccountId",`

If that is the question , yes i did that already.

**Comment by hbulgarini** [comment]
Actually we got that from this another issue: https://github.com/polkadot-js/apps/issues/4655

**Comment by jacogr** [comment]
The signature is the wrong place to look - the error comes from `accountNextIndex` RPC, where it cannot decode the `AccountId` to retrieve the index.

**Comment by hbulgarini** [comment]
it's the same as Kusama/Polkadot (sr25519). Here you have the reference about typedefs: Signature, AccountSigner and AccountId

https://github.com/paritytech/parity-bridges-common/blob/master/primitives/rialto/src/lib.rs#L110

**Comment by jacogr** [comment]
Then see no reason why the accountNonce would fail. Do you use a specific ss58 prefix in the chain. (Ie. Non default 42 set in chain spec)

**Comment by hbulgarini** [comment]
Yes, actually you can quickly refer to the last PR regarding ss58:
https://github.com/paritytech/parity-bridges-common/pull/739

Also i'm including @tomusdrw  in the loop.

**Comment by jacogr** [comment]
Ahhh. How old is your API and Substrate?

Support for higher indexes went in very recently on both.

**Comment by hbulgarini** [comment]
The current API version i'm using is "@polkadot/api": "^3.6.4" , should i downgrade the api ?  To be honest i think substrate needs to be upgraded on the project ( i'm not really involved with that part so i might be wrong )

**Comment by jacogr** [comment]
No, that is really prior the ss58 format change. So it sounds like Substrate has been bumped.

It may be worth a check just to bump the API to latest.

**Comment by hbulgarini** [comment]
Hi ! i upgraded api version to `"@polkadot/api": "^3.9.3"` and the issue is the same ... taking also a look at substrate side

**Comment by jacogr** [comment]
The ss58 encoding on the JS side is correct - actually added some more test-cases over the weekend for 65 & 66, generated from subkey. So not sure where it goes wrong.

**Comment by tomusdrw** [comment]
Turns out there is a peculiar call you need to make in CLI of your node in case the chain is using non-standard SS58 prefix.
This fixes JSON-RPCs decoding of addresses.

```rust
sp_core::crypto::set_default_ss58_version(
  sp_core::crypto::Ss58AddressFormat::Custom(your_runtime::SS58Prefix::get() as u16)
);
```

**Comment by jacogr** [comment]
TIL...
