### ISSUE TITLE
chainx transfer error

### ISSUE THREAD

**Issue by luckyhua** [polkadot-js/api#3190]
![image](https://user-images.githubusercontent.com/9531587/108582929-2093fc00-7371-11eb-842a-1f084b2bf5c3.png)
![image](https://user-images.githubusercontent.com/9531587/108582947-32759f00-7371-11eb-80c5-5f7b551fcd97.png)
excute chainx transfer rpc-core，help me，thanks

**Comment by xwartz** [comment]
Because they have a lot of breaking changes again, you need to do the following things：
1. update the node runtime to 28
2. update polkadot.js to the latest version
3. set the address type to `MultiAddress`

It's a chain that doesn't care about developers.

**Comment by luckyhua** [comment]
> 3\. set the address type to `MultiAddress`

I have need example or docs，help，thanks

**Comment by luckyhua** [comment]
> Because they have a lot of breaking changes again, you need to do the following things：
> 
> 1. update the node runtime to 28
-- 
chain =  [String (Text): 'ChainX'] { registry: TypeRegistry {} }
node name =  [String (Text): 'ChainX'] { registry: TypeRegistry {} }
node version =  [String (Text): '2.0.8-1-80b10212-x86_64-linux-gnu'] {
  registry: TypeRegistry {}
}
> 2. update polkadot.js to the latest version
-- "@polkadot/api": "^3.9.3"
> 3. set the address type to `MultiAddress`
-- help me
> 
> It's a chain that doesn't care about developers.

**Comment by jacogr** [comment]
The ChainX team has specific overrides for their `Address` types - you can see an example here of what they have provided - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/chainx.ts#L15-L16

So in your API initialization, you would need to add -

```js
const api = await Api.create({ provider, types: { Address: 'AccountId', LookupSource: 'AccountId } });
```

This information is different on a per-chain basics, however all chains are now moving to `MultiAddress` to smooth out the 3 different types that can be found on deployed chains - https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

**Comment by luckyhua** [comment]
> The ChainX team has specific overrides for their `Address` types - you can see an example here of what they have provided in their configuration - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/chainx.ts#L15-L16
> 
> So in your API initialization, you would need to add -
> 
> ```js
> const api = await ApiPromise.create({ 
>   provider, 
>   types: { Address: 'AccountId', LookupSource: 'AccountId' }
> });
> ```
> 
> This information is different on a per-chain basics, however all chains are now moving to `MultiAddress` to smooth out the 3 different types that can be found on deployed chains - https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

![image](https://user-images.githubusercontent.com/9531587/108592028-ba29d080-73a6-11eb-8269-1f3490bfb559.png)

![image](https://user-images.githubusercontent.com/9531587/108592026-b5651c80-73a6-11eb-9714-227ccc28ee3c.png)

**Comment by jacogr** [comment]
So what does the chainX imports do here? Sorry, not familiar with their setups at all? Is the override really needed if they have an "options" creator?

What error do you get when executing?

(Sorry for the dumb questions, not sure about their specific recommended setup, hence the question around the specific imports from their SDK you use here)
