### ISSUE TITLE
api.derive.elections.info return type error

### ISSUE THREAD

**Issue by zzcwoshizz** [polkadot-js/api#3200]
@polkadot/api version: 3.10.1

`api.derive.elections.info` returns `candidates` type is `AccountId[]`, but in latest substrate, the candidates type is `[AccountId, Balance][]`

it will cause apps page(/council) catch error. 
`Uncaught error. Something went wrong with the query and rendering of this component. Decoding ["5E7cWPZBaD5u23Vvctq3dcQeuuCi7MKSAukGkoymfD2kSiDM",1000000000000]: Invalid base58 character "[" (0x5b) at index 0 `

You can visit this page to check the error [https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnew.staging.jupiter.patract.cn#/council](url)

**Comment by atenjin** [comment]
replay:
substrate version:fd88fbf7e05b3bea3e8324e2661c586353b48a43

```bash
cargo build
./target/debug/substrate --tmp --dev
```

Using apps to connect this node:

1. send some money to an Address
2. click Council overview, current candidates is empty
![image](https://user-images.githubusercontent.com/5023721/108710772-745c3c00-754f-11eb-898b-41214ffaa63c.png)
3. use the account to submmit candidacy, than the website panic:
![image](https://user-images.githubusercontent.com/5023721/108711070-cbfaa780-754f-11eb-924b-12254beef7d3.png)

**Comment by jacogr** [comment]
It was partially adjusted, but it seems only for the election side, not for the council side.
