### ISSUE TITLE
1002: balances.transferKeepAlive

### ISSUE THREAD

**Issue by ZentaChainAdmin** [polkadot-js/api#3201]
As soon as I update the node

1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature

I also add some dev configs:
 **{
  "Address": "MultiAddress",
  "LookupSource": "MultiAddress"
}**

It doesn't help.

**Comment by jacogr** [comment]
Update which node? The types is only needed if the chain explicitly requires it - MultiAddress is the API default, so when nothing is specified, it would apply that by default. 

Here is some info on the 3 Address formats that can be configured on the node - https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

**Comment by ZentaChainAdmin** [comment]
Understand thank you so much!
{ 
**"Address": "AccountId", 
"LookupSource": "AccountId"**
 }
