### ISSUE TITLE
How to resolve errors

### ISSUE THREAD

**Issue by noahsalvadordenjo** [polkadot-js/api#3210]
Dear Polkadot-js,
I have the following substrate code that should throw an error 
```
#[weight = 10_000 + T::DbWeight::get().writes(1)]
		pub fn generate_qr_code(origin, peer_id: Vec<u8>) -> dispatch::DispatchResult {
			let who = ensure_signed(origin);
			ensure!(pallet_node_authorization::Module::<T>::well_known_nodes().contains(&OpaquePeerId::new(peer_id)), Error::<T>::UnknownNode);
			Ok(())
		}
```
Im trying to resolve this error with 
```
const result = await api.tx.sesches.generateQrCode('12D3KooWDZyM56RRChPVTBCTxdRkstEwajsdfhajshd').signAndSend(alice,  status => {
        console.log(status);
    });
```
But it only displays a Submittable result and the dispatchError is ```undefined```
How do i resolve errors with polkadotjs?

**Comment by jacogr** [comment]
`dispatchError` is extracted from the `ExtrinsicFailed` event. So it is only available when that event occurs.
