### ISSUE TITLE
How can we get the history balance correctly?

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#3211]
I query the treasury balance with following function, but it can't give me the right treasury balance at height 43200 of Kusama. I know there is a data migration between balance and system module, but I expect the right balance with query balance module.

```javascript
async function queryBalance(api) {
  const TreasuryAccount = "F3opxRbN5ZbjJNU511Kj2TLuzFcDq9BGduA9TgiECafpg29";
  const blockHash = await api.rpc.chain.getBlockHash(432000);

  const a1 = await api.query.system.account.at(blockHash, TreasuryAccount);
  const a2 = await api.query.balances.account.at(blockHash, TreasuryAccount);

  console.log('a1', a1.toJSON());
  console.log('a2', a2.toJSON());
}
```

Output:

```
a1 {
  nonce: 0,
  refcount: 0,
  data: { free: 0, reserved: 0, miscFrozen: 0, feeFrozen: 0 }
}
a2 { free: 0, reserved: 0, miscFrozen: 0, feeFrozen: 0 }
```

I think the `a2` is a wrong result, and I guess the storage key calculated in this query process is wrong. So how can we get the history account balance?

**Comment by jacogr** [comment]
The balances were never stored in `balances.account` - prior to moving to `system.account` it was in `balances.freeBalance`.

**Comment by wliyongfeng** [comment]
> The balances were never stored in `balances.account` - prior to moving to `system.account` it was in `balances.freeBalance`.

Thanks. I got `undefined` with `api.query.balances.freeBalance`, so we need to load the corresponding block metadata and construct the query, right?

Any convenient way for us to query it?

**Comment by jacogr** [comment]
Something like this, untested -

```js
const blockHash = await api.rpc.chain.getBlockHash(432000);
const metadata = await api.rpc.state.getMetadata(blockHash);
const decorated = expandMetadata(metadata.registry, metadata);
const key = u8aToHex(decorated.query.balances.freeBalance(address));
const value = await api.rpc.state.getStorage(key, blockHash);

// not sure, could be Balance, cannot recall
console.log(metadata.registry.createType('Compact<Balance>', value).toHuman());
```

**Comment by wliyongfeng** [comment]
> Something like this, untested -
> 
> ```js
> const blockHash = await api.rpc.chain.getBlockHash(432000);
> const metadata = await api.rpc.state.getMetadata(blockHash);
> const decorated = expandMetadata(metadata.registry, metadata);
> const key = u8aToHex(decorated.query.balances.freeBalance(address));
> const value = await api.rpc.state.getStorage(key, blockHash);
> 
> // not sure, could be Balance, cannot recall
> console.log(metadata.registry.createType('Compact<Balance>', value).toHuman());
> ```

Thanks, I'll try it.

**Comment by wliyongfeng** [comment]
I can run it, but unfortunately the finale value is empty. I also tried the `totalIssuance` with following code, the `totalIssuanceValue` is also empty, so there maybe some problems with the way we construct the key?
```javascript
  const totalIssuanceKey = u8aToHex(decorated.query.balances.totalIssuance());
  const totalIssuanceValue = await api.rpc.state.getStorage(key, blockHash);
```

**Comment by jacogr** [comment]
Yes, I was just looking and the API code. Try this (which is more-or less what the API is using) -

```js
const key = [decorated.query.balances.freeBalance, address];
const value = await api.rpc.state.getStorage(key, blockHash);
```

There is some tricky bits with the storage keys since they are Bytes, i.e. have a prefix. When passed as a tuple of `[function, param]` it should properly handle it.... hopefully. So in the case of totalIssuance, pass it as `api.rpc.state.getStorage([decorated.query.balances.totalIssuance], hash)` 

(Good test to ensure it does work first)

Worst-case, `key = com[actStripLength(decorated.query.balances.totalIssuance())`

**Comment by wliyongfeng** [comment]
Great, tested and it works!

**Comment by wliyongfeng** [comment]
> (Code wise the migration went balances.freeBalance -> balances.account -> system.account - however as I recall the intermediate step was never deployed - or if it was, very shortly lived)

Hi, @jacogr it works well until [1375086](https://polkascan.io/kusama/block/1375086#events). The runtime updated, and the `balances.freeBalance` was removed. I queried `balances.account` and `system.account`, bu in either way the treasury address free is 0. Do you remember what happened for this update and could you help figure this out?

**Comment by wliyongfeng** [comment]
The account migration happened in [1492896](https://polkascan.io/kusama/block/1492896#events). Can we assume that we have no interfaces to query the balance from the from `1375086` to `1492896`?

**Comment by jacogr** [comment]
If you do a raw query at those blocks, ie. Just the value via Verstöße with a passed-in key, does it have something?

the reason for asking is that it could be a type conversion mismatch, hence asking whet the state itself contains.

**Comment by wliyongfeng** [comment]
I haven't tried it. Just not familiar with the raw storage key calculation, while `compactStripLength(decorated.query.balances.freeBalance(address))` may not produce the direct storage key. 

I guess query with the pre-calculated key will work. Will try it maybe in browser.

**Comment by jacogr** [comment]
Yeap, the storage locations are there, but they are empty. Really cannot recall where they would be then, there is only freeBalance, account(balance) & account(system) as possibilities.

However, it does seem I see some stuff in that location. So I'm thinking it is a type mismatch (possibly the refCount type, which changed at some point) for that location.

**Comment by jacogr** [comment]
Ok, so this is the what I believe - the first iteration of the system.count didn't actually return the details as we know it. It was actually a Tuple of `[AccountIndex, AccountData]`.

So in the same way you use the createType to get to that data, you need to `createType('(AccountIndex, AccountData)', rawDataFromStorage)` to decode.

**Comment by wliyongfeng** [comment]
Sure, I can make it work with following code. I need some debug to find how to get the raw storage hex, but now I think it's enough for this issue.  Thanks, @jacogr .

```javascript
const TreasuryAccount = "F3opxRbN5ZbjJNU511Kj2TLuzFcDq9BGduA9TgiECafpg29";

async function getOldKey(api) {
  const blockHash = await api.rpc.chain.getBlockHash(1375085);

  const metadata = await api.rpc.state.getMetadata(blockHash);
  const decorated = expandMetadata(metadata.registry, metadata);

  return [decorated.query.balances.freeBalance, TreasuryAccount]
}

async function queryBalance(api) {
  const blockHash = await api.rpc.chain.getBlockHash(1375086);
  const metadata = await api.rpc.state.getMetadata(blockHash);

  const key = await getOldKey(api);
  const value = await api.rpc.state.getStorage(key, blockHash);
  console.log(metadata.registry.createType('Compact<Balance>', value).toJSON());
}
```
