### ISSUE TITLE
Error: Unknown type passed to AccountId constructor

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3213]
I found a error "Error: Unknown type passed to AccountId constructor" after sending transaction using @polkadot-js: v3.10.2

Pieces of source code are here.
txParams.transfer = api.tx.balances.transfer(txParams.to, this.convertUnit("to", txParams.amount))
nonce = await this.getNonce(txParams.from)
await txParams.transfer.sign(this.wallet[txParams.from], { nonce })
await signedTx.send()

Please let me know how to solve it. Thanks.

**Comment by jacogr** [comment]
Ensure you pass a publicKey or ss58 address to the to param in the transfer.

**Comment by boohyung** [comment]
Thanks for helping me @jacogr

There are arguments of transfer function.

txParams.to -> '5F3nmjeRb3PDRQ7EagnsDPFhnsbEQwmqLjz5cT1X9Rb9RR8y'
this.convertUnit("to", txParams.amount) -> '10000000000'

and I changed to @polkadot-js: v3.10.2 -> @polkadot-js: v3.10.3-5 so I encountered another error log "createType(Address):: Unable to create Enum via index 206, in Id, Index, Raw, Address32, Address20"

**Comment by jacogr** [comment]
The chain you are using is not on `MultiAddress` which is the API default. Pass the correct Address types for that chain - https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-sending-yields-decoding-failures

**Comment by boohyung** [comment]
_ApiPromise.create
api.registerTypes({ "Address": "AccountId", "LookupSource": "AccountId" })_

I append this line and get another error.
-> 1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress"): RuntimeApi, Execution failed: ApiError, \"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress

**Comment by jacogr** [comment]
The good news is that I can reproduce your issue, it was introduced in `v3.10.2`. The bad news is that it needs a fix.

**Comment by WannaM** [comment]
> The good news is that I can reproduce your issue, it was introduced in `v3.10.2`. The bad news is that it needs a fix.

Hi, I have checked the releases of `v3.10.2`which is the version we use. So it's fixed `v3.11.1` ? Need I upgrade `api-contract` too?
