### ISSUE TITLE
Where do i find the old documentation of polkadotjs?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [polkadot-js/api#3222]
Hi there i have my substrate node running on version ```2.0.1``` but the contracts pallet still requires the ```putCode``` functionality
So where do i find the old documentation of polkadotjs?

**Comment by jacogr** [comment]
The https://polkadot.js.org/docs/ always tracks the latest substrate master (it gets updated around once a week). I don't have a older version around, but this PR may be of help - 

https://github.com/polkadot-js/docs/pull/131/files

(That is the one where it was updated to current substrate 3 functionality)
