### ISSUE TITLE
Need "transfer_with_memo" feature on the chain. Its a critical feature for many use-cases.

### ISSUE THREAD

**Issue by outlier89** [polkadot-js/api#3250]
`transfer` is the most important call for a chain. However Substrate/Polkadot balances module just provide transfer but currently there is no way to attach other information.

In Ethereum/ EOS or some other blockchain, transactor could add input_data(Ethereum) or add Memo(EOS) to attach some information which could be used in exchange for deposit, in-game transactions or in many other ways.

I would suggest to either just add a parameter "Memo" in balances OR add a new call in balances module named transfer_with_memo with just one more parameter "Memo"

**Comment by jacogr** [comment]
Please redirect this to Substrate - this is not an API feature. the API only exposes what the chain metadata exposes.

However, as it stands, there is nothing that stops you for sending a remark with a transfer - a batch transaction with the transfer and the system.remark fills the same purpose.
