### ISSUE TITLE
Cannot execute getMetaData() & injectMetadata() on block #3899547

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3258]
I'm using polkadot-js API function `getMetaData()` and `injectMetadata()` for querying transaction event in the specific block. but I cannot receive any response in block #3899547. What should I do?

**Comment by jacogr** [comment]
Which chain?

**Comment by boohyung** [comment]
The Polkadot network and The point is runtime v28 update block.

polkadot-js version is  "@polkadot/api": "^3.11.1", and api-derive, metadata, rpc-core, rpc-provider, types are same version.

**Comment by jacogr** [comment]
It work directly with the API itself, i.e. the apps UI for instance has no issues retrieving that block alongside with the state at that point. So it has something to do with your usage.

**Comment by boohyung** [comment]
My API usage is here. and the RPC method "state_getMetadata" took about 3 minutes (correctly 03:07) until I got response.

source code>
```javascript
const metaDataAt = await this.api.rpc.state.getMetadata(hash);
this.api.injectMetadata(metaDataAt);
```

curl>
`curl -H "Content-Type: application/json" -d '{  "id": 1,  "jsonrpc": "2.0",  "method": "state_getMetadata",  "params": ["0x95488d035a54f89a451f32ebcd8b90dbc792713a835dcaf719cb8d3b0f578aca"]}' http://localhost:9933 | python -m json.tool
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   145    0     0  100   145      0      1  0:02:25  0:02:09  0:00:16     0

**Comment by jacogr** [comment]
If you inject, you need to make sure you have all the correct types setup for the new version.

**Comment by boohyung** [comment]
How can I types setup for the new version?

**Comment by jacogr** [comment]
So my question here is - why are you injecting the metadata into the API? the API takes care of all of that - swapping type registries, adding the correct types, retrieving/injecting metadata.

**Comment by boohyung** [comment]
I want to querying transaction event of specific block. So I set up the metadata using blockhash.

This is my approach that I get the transaction event.

```javascript
const { block } = await PolkadotSigner.getBlock(hash)
await PolkadotSigner.setMetaData(hash) // getMatadata() + injectMetadata() in polkadot-js
let txEvent = await PolkadotSigner.getEvents(hash) as EventRecord[] 

```

**Comment by jacogr** [comment]
`api.query.system.events.at(hash)` - injects the types, metadata, swaps registries, decodes the result at that point.

https://polkadot.js.org/docs/api/start/api.query.other#state-at-a-specific-block

**Comment by boohyung** [comment]
Thanks @jacogr . Using `api.query.system.events.at(hash)` is more simple than `getMetaData() `+ `injectMetaData()`

In addition, Where do I find the polkadot-js API documentation? function/argument/return value.etc.
"https://polkadot.js.org/docs/" Is that right?

**Comment by jacogr** [comment]
All available docs are in the docs portal.

If you refer to Substrate interfaces, these are here - https://polkadot.js.org/docs/substrate
