### ISSUE TITLE
Type request for the new election provider pallet

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/api#3265]
The new election provider pallet is already on westend, and will go to Kusama soon. The types are not in the apps ui yet. This was partly my oversight as well, I should have pinged someone beforehand. 

![Screenshot 2021-03-05 at 10 01 10](https://user-images.githubusercontent.com/5588131/110092408-7d3fdf80-7d91-11eb-9486-4c3f9e079467.png)

**Comment by kianenigma** [comment]
Seems like only phase is missing.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/3280
