### ISSUE TITLE
Failed to decode events of Westend block 1

### ISSUE THREAD

**Issue by tomaka** [polkadot-js/api#3274]
Reproduction: https://gist.github.com/tomaka/cc849b6ee4ff8a12680c01f57309e0b3

This leads to:

```
REGISTRY: Error: findMetaEvent: Unable to find Event with index 0x0f00/[15,0]
    at assert (assert.js:34)
    at assertReturn (assert.js:44)
    at TypeRegistry.findMetaEvent (registry.js:314)
    at Function.decodeEvent (Event.js:133)
    at new GenericEvent (Event.js:114)
    at new Type (registry.js:340)
    at decodeU8a (decodeU8a.js:24)
    at decodeStruct (Struct.js:98)
    at new Struct (Struct.js:132)
    at new <anonymous> (Struct.js:150)
```

And

```
Error: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x0f00/[15,0]
    at createTypeUnsafe (createType.js:72)
    at createType (createType.js:84)
    at TypeRegistry.createType (registry.js:297)
```

I took the metadata of the Westend runtime found in its genesis, and the events stored at block number 1.

I'm very confident that the constants are correct.
Here's for example what the Westend JSON-RPC server returns when looking at block 1 in the PolkadotJS UI:

![image](https://user-images.githubusercontent.com/1412254/110216166-dbfa7b80-7ead-11eb-8a25-1784e1d6c9a0.png)

Are the errors "normal"? Am doing something wrong? Is there some caveat here?

**Comment by tomaka** [comment]
I'm passing `true` because I copy-pasted [this example](https://github.com/polkadot-js/api/blob/a9c9fb5769dec7ada8612d6068cf69de04aa15ed/packages/types/src/interfaces/system/EventRecord.spec.ts#L25), but I guess this `true` doesn't make sense. Removing it doesn't change anything however.

**Comment by jacogr** [comment]
Yes, the above is not going to work. 

The metadata is just one piece of the puzzle. In addition to the metadata the types for the correct specVersion as at that point needs to be applied.

So what the API itself does for any historic queries -

- gets metadata
- gets runtime version
- set metadata on registry 
- inject types as of that point in the chain
- ... decode

**Comment by tomaka** [comment]
> inject types as of that point in the chain

Do you have any code to point to that I could read to figure how to do that?
I have all the information necessary, just trying to somehow plug them into PolkadotJS to decode events.

**Comment by tomaka** [comment]
Found what I was looking for: https://github.com/polkadot-js/api/blob/ec76b11666aea72135f899267abf784fc6309156/packages/api/src/base/Init.ts#L83-L97
