### ISSUE TITLE
Balance stays zero

### ISSUE THREAD

**Issue by noahsalvadordenjo** [polkadot-js/api#3275]
```await api.query.system.account('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')``` returns ```{
  nonce: '0',
  consumers: '0',
  providers: '0',
  data: { free: '0', reserved: '0', miscFrozen: '0', feeFrozen: '0' }
}```  and  ```await api.query.system.account('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')```
returns ```{ free: '0', reserved: '0', miscFrozen: '0', feeFrozen: '0' }``` with the following genesis.json 
```
    "palletBalances": {
      "balances": [
        [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
          1152921504606846976
        ],
```
using the substrate node template ```3.0.0```

**Comment by jacogr** [comment]
Honestly not sure how the genesis config flow through. 

I would suggest looking at the Substrate codebase, i.e. Substrate node with `--dev` populates the accounts correctly.
