### ISSUE TITLE
Custom RPC typegens breaking with RpcCore

### ISSUE THREAD

**Issue by igorgogo** [polkadot-js/api#3279]
Hi, 

From version `3.6.4` of typgen, I was able to successfully add custom rpc to typegen `definitions.ts`:
```javascript
/* eslint-disable @typescript-eslint/camelcase */
export default {
  types: {
   ...
  },
  rpc: {
   ...
  },
}
```
```
Class 'RpcCore' incorrectly implements interface 'RpcInterface'.
  Property 'customModule' is missing in type 'RpcCore' but required in type 'RpcInterface'
```

but is now breaking `RpcCore`, maybe due to some changes in `@polkadot/rpc-core`. 

Has anyone experienced this or any ideas on how to fix this?

**Comment by jacogr** [comment]
This is certainly now new. The rpc-core has an explicit available definition, see https://github.com/polkadot-js/api/blob/master/packages/rpc-core/src/index.ts#L97-L131

(However that should only apply to all api-internal definitions, none injected via typegen for chain-specific types)

**Comment by natpopov** [comment]
hi i'm getting the same error as well. I've tried 3.8.1 and 4.0.2 for typegen/api and I'm using 4.0.5 for typescript. Following is the error message that I encounter:

```bash
yarn run v1.22.5
$ rimraf dist
$ nest build
node_modules/@polkadot/rpc-core/index.d.ts:29:22 - error TS2420: Class 'RpcCore' incorrectly implements interface 'RpcInterface'.
  Property 'customMod' is missing in type 'RpcCore' but required in type 'RpcInterface'.

29 export declare class RpcCore implements RpcInterface {
                        ~~~~~~~

  packages/interfaces/augment-api-rpc.ts:67:5
    67     customMod: {
           ~~~~~~~~~~~
    'customMod' is declared here.

Found 1 error(s).

error Command failed with exit code 1.
```

**Comment by jacogr** [comment]
What does `nest build` do? 

(Sorry for all the questions, a bit weird since this is the first complaint here... and it has been in apparently since 3.8.1. Which means a number of teams don't have this issue - and that interface has not changed at all as linked above, so a bit confused. Have some ideas to work around it is a widespread issue, just trying to get to the bottom of it first)

**Comment by natpopov** [comment]
I've only been seeing this issue after upgrading to substrate 3.0.0 recently, I'm using polkadotjs in my nestjs (https://docs.nestjs.com/) web application. The error disappears if I don't include rpc in my customMod definitions.ts.

**Comment by jacogr** [comment]
Ok. Will figure out something to address this. 

A stop-gap solution for now would be to add skipLibCheck to your tsconfig - this means it won’t check node_modules.

**Comment by natpopov** [comment]
works, thanks!

**Comment by igorgogo** [comment]
```
    "@polkadot/api": "^3.6.5-9",
    "@polkadot/typegen": "^3.6.4",
    "@polkadot/types": "^3.6.5-9",
 ```
 
 to
 
 ```
     "@polkadot/api": "^3.8.1",
