### ISSUE TITLE
The transfer balance is 0 every time I use polkadot.js.org/apps, the transfer is correct, what am I doing wrong

### ISSUE THREAD

**Issue by andrewang** [polkadot-js/api#3281]
```
transfer(data:TransferData)
    {
        const keyring = new Keyring({type:'sr25519'});
        const from = keyring.addFromAddress(data.from);
        web3FromAddress(data.from).then((injector)=>{
            this.api.tx.balances.transferKeepAlive(data.to,100).signAndSend(from.address, { signer: injector.signer }, ({ status }) => {
                            if (status.isInBlock) {
                                console.log(`Completed at block hash #${status.asInBlock.toString()}`);
                            } else {
                                console.log(`Current status: ${status.type}`);
                            }
                        }).catch((error: any) => {
                            console.log(':( transaction failed', error);
                            if (error && error == 'Cancelled') {
                               
                            }
                        });
        })

```

The transfer balance is 0 every time I use polkadot.js.org/apps, the transfer is correct, what am I doing wrong

<img width="700" alt="{F480E134-72D3-CB6C-2A1C-014DE1E650FA}" src="https://user-images.githubusercontent.com/5197349/110320401-31b85a80-804b-11eb-9bd7-0f4dabc1198b.png">

**Comment by jacogr** [comment]
The 100 you are sending is less than the existential deposit. (You need to take the number of decimals into account. If an account does not exists. You need to transfer more to it than existential. Also bear in mind that the UI only displays the First 4 decimals.)

**Comment by jacogr** [comment]
On a local network, the existential is 100 - the dev/local chains have 12 decimals. This means that any value below 100 + 12 decimals = `100000000000000` won't reflect. (When dealing with transfer directly, it is an integer, when 1 reflects the smallest decimal)

**Comment by andrewang** [comment]
I did not understand what you said, can give a code snippet. I use polkadot.js/apps/ web developer javascript make transfer and listener to events and the result is also 0

**Comment by jacogr** [comment]
Substrate has the concept of an existential deposit - any account with a value below this is reaped. This means if you send a value < existential to an account, it won't reflect. So to ensure you send more than existential to create an account -

```js
const ed = api.consts.balances. existentialDeposit;

// send ed + 1
const tx = api.tx.balances.transfer(<to>, ed.addn(1));
```

**Comment by andrewang** [comment]
After I added a node js library, there was an error like this when I used signAndSend

2021-04-07 16:58:57 REGISTRY: Error: Invalid character
    at assert (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:17:21)
    at parseBase (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:280:7)
    at Type._parseBase (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:316:14)
    at Type.init [as _init] (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:110:12)
    at new BN (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:50:12)
    at new AbstractInt (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:95:5)
    at new UInt (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:34:1)
    at new eval (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:38:9)
    at new u32 (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:29:1)
    at new GenericAccountIndex (eval at <anonymous> (__quick_compile__.js:230), <anonymous>:62:5)
