### ISSUE TITLE
PaymentInfo for remarks 

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/api#3285]
Hi ! is it possible to get the `weight` value from a remark transaction? 

i'm trying to get this value with the following code:

`
    const remarkInfo = await api.tx.system.remark('0x1234').paymentInfo;
    console.log('remarkInfo', remarkInfo.weight);
`

From this code i face two issues:

Execution issue:
`
Unhandled Rejection (TypeError): api.rpc.payment.queryInfo is not a function
`

TypeScript issue: 
`
Property 'weight' does not exist on type '(account: AddressOrPair, options?: Partial<SignerOptions> | undefined) => Promise<RuntimeDispatchInfo>'.ts(2339)
`

**Comment by jacogr** [comment]
You need to ensure your Substrate node exposes the payment RPCs, this is what leads to this error `api.rpc.payment.queryInfo`

See 

- addition to node: https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L1087
- actual RPC definition: https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/rpc/src/lib.rs#L36

**Comment by hbulgarini** [comment]
understood! the RPC exposure is the issue ... what about the typescript issue?

i'm typing my api connections using:
`import { ApiPromise } from '@polkadot/api';`

**Comment by jacogr** [comment]
`RuntimeDispatchInfo` has the weight, 

- definition here: https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/payment/definitions.ts#L46-L50
- generated TS interface: https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/payment/types.ts#L21-L25

In your case however, you seem to be missing a `then` or `await`, you are trying to get it on a `Promise<RuntimeDispatchInfo>` (i.e. didn't call the function and await the result.

**Comment by hbulgarini** [comment]
thank you Jaco , you replied all my questions.
