### ISSUE TITLE
Undefined author for latest block in a session

### ISSUE THREAD

**Issue by Nivelium** [polkadot-js/api#3294]
Hello!
I have a problem receiving author for the latest block in a session. Whenever i request header and author of the latest block of a session i receive undefined value.
The package versions in package.json:

```
    "@polkadot/api": "^3.9.3",
    "@polkadot/api-derive": "^3.9.3",
    "@polkadot/rpc-core": "^3.9.3",
    "@polkadot/types": "^3.9.3",
    "@polkadot/types-known": "^3.9.3",
    "@polkadot/util": "^5.6.3",
```

the ws url of node: wss://rpc.polkadot.io

I use method ```derive.chain.getHeader(blockHash)```, could you please tell what's wrong? Is that correct behavior and i should do  it another way? Or this is a bug?

https://github.com/p2p-org/polkadot-profit-transformer/blob/master/streamer/src/services/blocks.js#L115

Here when i request author of ```extHeader``` i always receive undefined for the latest block in a session

**Comment by jacogr** [comment]
It is a current known issue. Not exactly sure why yet, but looking.
