### ISSUE TITLE
Dividing transaction into parts

### ISSUE THREAD

**Issue by Rakhymzhan** [polkadot-js/api#3296]
Hey, I'd like to ask how can I divide tx into parts?
* I create the Tx without signing, and have to pass this Tx through api in API serialized json format(or smth else).

* Then by requesting Client-part get this Tx and sign and return it back, also as API serialized json format. 
(signing is NOT offline)
* Finally I get this Tx and have send() this Tx;

Can you show how the converting goes from API serialized json to Tx(I mean Submittable) and back?

Thank you in advance!

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/tools/tree/master/packages/signer-cli/src for examples for offline signing.

The `signAsync` and `send` is the two parts. Once signed, you can also do `tx.toHex()` to have the signed tx as hex and `api.tx(txHex).send()` to re-create and send.

**Comment by Rakhymzhan** [comment]
@jacogr Thank you so much, appreciate your answer which was helpful!)
