### ISSUE TITLE
Change ECDSA Signature type

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3298]
In `packages/types/src/interfaces/extrinsics/types.ts`, EcdsaSignature is declared:

```
/** @name EcdsaSignature */
export interface EcdsaSignature extends U8aFixed {}
```

But according to my esteemed colleague @girazoki it should be 65 bytes https://docs.rs/sp-core/2.0.0-rc4/src/sp_core/ecdsa.rs.html#231

**Comment by jacogr** [comment]
It is 65 bytes in the same way as the other are 64 - https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/extrinsics/definitions.ts#L37-L39

Don't confuse the extension of a class with what it contains. U8aFixed gets the bitLength as part of the constructor.

**Comment by jacogr** [comment]
TL;DR Closing, invalid understanding of the actual types.
