### ISSUE TITLE
Chain Interface "contracts" section of API Docs does not render correctly. "substrate" section missing

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#330]
When I go to the API Docs > Chain state (runtime), it has a "contract" section https://polkadot.js.org/api/METHODS_STORAGE.html#contract in the menu but no methods associated when I click the link, and there isn't a "substrate" section at all (differs from Substrate UI at https://polkadot.js.org/apps/next/#/chainstate which does have that section)

**Comment by jacogr** [comment]
Bug in actual substrate metdata. Fixed in substrate.
