### ISSUE TITLE
ApiOptions type for default hasher?

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/api#3301]
I'm trying to implement the default hasher parameter for constructing the Api connection and i'm not able to find the corresponding type. Is there any ts type defined for this parameter included recently in latest releases?

i'm mainly trying to implement this code snippet in TS:
https://github.com/polkadot-js/api/pull/3206#issue-578398817

**Comment by jacogr** [comment]
The default would be -

```js
ApiPromise.create({ hasher: (data) => blake2AsU8a(data) })
```

The above does nothing since it is blake2 by default anyway. 

The definition is here - https://github.com/polkadot-js/api/blob/master/packages/types/src/types/registry.ts#L71

(Bit of an indirection from the root APIOptions)

**Comment by hbulgarini** [comment]
So basically for defining the `hasher` type on my own interface i would have to do something like:
`hasher?: ApiOptions['hasher'];` right?

if that is the case i'm receiving the following TS error: `Property 'hasher' does not exist on type 'ApiOptions'.ts(2339)`

thanks for the quick response btw

**Comment by jacogr** [comment]
`RegisteredTypes['hasher']` should work (but weirdly, also would have expected `ApiOptions['hasher']` to work... it extends...)

But yes, it is just a simple function taking in a Uint8array and outputting the same.

**Comment by hbulgarini** [comment]
For some reason it is not working as expected...

I have defined `hasher?: ApiOptions['hasher'];` ( which should work since it extends RegisteredTypes as you mentioned), but i got:

```
Type '{ hasher: (data: Uint8Array) => Uint8Array; provider: ProviderInterface; types: RegistryTypes | undefined; }' is not assignable to type '{ provider: ProviderInterface; types: RegistryTypes | undefined; }'.
  Object literal may only specify known properties, and 'hasher' does not exist in type '{ provider: ProviderInterface; types: RegistryTypes | undefined; }'.ts(2322)
```

is there any refresh step that i missing? i have upgraded api version to `"@polkadot/api": "^v4.0.3"`

**Comment by jacogr** [comment]
Can you show the code-line where it complains?

**Comment by hbulgarini** [comment]
sorry my bad, the issue is not related to the api types , it was because a conditional assignment .... `hasher?: ApiOptions['hasher'];` did the job. Thanks
