### ISSUE TITLE
Balance information 

### ISSUE THREAD

**Issue by Rakhymzhan** [polkadot-js/api#3304]
Hello, I'd like to get all balances, such as

- mainBalance
- nominatedBalance
- adding
- stake
- frozenBalance
- unstake
- rewards

Thank you in advance!)

**Comment by sahilnanda1995** [comment]
`api.derive.balances.all(accountId)`
the above query might help, but it doesn't include rewards

**Comment by Rakhymzhan** [comment]
@sahilnanda1995 
accountId? what do you mean?)

**Comment by sahilnanda1995** [comment]
accountId: The public address/key of the account for which you want to gather balances information
more info here: https://wiki.polkadot.network/docs/en/build-protocol-info#addresses

**Comment by Rakhymzhan** [comment]
Than you, 
I am getting such HEX values
"freeBalance": "0x00000000000000000000000b6e8748c0",
    "frozenFee": "0x000000000000000000000009502f9000",
    "frozenMisc": "0x000000000000000000000009502f9000",
    "reservedBalance": "0x00000000000000000000000000000000",

**Comment by sahilnanda1995** [comment]
you can use `toNumber()` to convert them

Example:
```
api.derive.balances.all(accountId, (info) => {
  console.log('freeBalance: ', info.freeBalance.toNumber());
  console.log('availableBalance: ', info.availableBalance.toNumber());
});
```
for more information:
https://polkadot.js.org/docs/

**Comment by Rakhymzhan** [comment]
Thank you so much, appreciate your help!
