### ISSUE TITLE
An error is reported during the operation of connecting to the KLP node

### ISSUE THREAD

**Issue by Yangxin-GG** [polkadot-js/api#3307]
error ：
![image](https://user-images.githubusercontent.com/30194654/110905247-26b04380-8345-11eb-9dc2-b0dd94b31a27.png)

An error says Unable to resolve type，But I don’t know how to add this type,

My current connection information:
![image](https://user-images.githubusercontent.com/30194654/110905464-7989fb00-8345-11eb-9ba5-3ee33d90cdc9.png)

I hope to get your help

**Comment by Yangxin-GG** [comment]
It was normal in the first two days, and an error occurred suddenly. The JS code and node version have not been changed.

**Comment by xianggy** [comment]
Hi, same issue here. How to resolve it? thank you.

**Comment by Yangxin-GG** [comment]
> 嗨，这里是同样的问题。怎么解决呢？谢谢你。

Find the corresponding currency at https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api/spec, which has the latest configuration
