### ISSUE TITLE
Requesting Claim and Nominated balances

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3308]
Hey, can you help with requesting the claim and nominated balances, please?

api.derive.balances.all(address) <- here I can find many balances but there are no these two balances.
api.derive.staking.account(address) <- here I can find redeemable and locked balances, but again there are no these two balances.

Thank you in advance!)

**Comment by jacogr** [comment]
You need to look at the staking ledger.

**Comment by Rakhymzhan** [comment]
is locked balance == delegated balance on polkadot? 
is vestedClaimable == reward balance?

**Comment by jacogr** [comment]
No. The locked balance is the total for all locks - democracy, council, treasury, staking - locks overlap.

Claimable vesting is the balance claimable as received via a vested transfer. (Or from-genesis vesting)

**Comment by jacogr** [comment]
The only delegation in Substrate is available in governance, i.e. democracy where you can delegate you voting balance to somebody else (with the correct locks). That is available via democracy.votingOf (and the applicable locks based on voting in democracy.locks).

**Comment by MrRakhim** [comment]
ok, got it, thanks!
