### ISSUE TITLE
How to get transaction hash (extrinsic hash) using a transaction subscription method instead of simple transfer?

### ISSUE THREAD

**Issue by outlier89** [polkadot-js/api#3311]
The simple signAndSend function returns the transaction hash (extrinsic hash) but how to retrieve the transaction hash using a transaction subscription method (await api.tx.balances
  .transfer(BOB, 12345)
  .signAndSend(alice, (result) => {...})

**Comment by jacogr** [comment]
```js
const tx = api.tx.balances.transfer(...);

tx.signAndSend(alice, (result) => {
  // needs to be inner, outer it will still be unsigned, so the hash  
  // only reflects the data without the signature
  console.log(tx.hash.toHex());
));

**Comment by outlier89** [comment]
Perfect. INNER "tx.hash.toHex()" does the work. 

Also, in order to verify the extrinsic hash on the server side, currently we are trying to use the block hash together with the extrinsic hash using the below code: 

```
var block = await api.rpc.chain.getBlock('<block_hash>');
  block.block.extrinsics.forEach(ex=>{
      console.log("Extrinsic Hash: ",ex);
  });
```
However, the extrinsic hash (ex) in the block.block.extrinsics array in the getBlock function doesn't match the inner tx.hash that we retrieved correctly using the transaction subscription function above. 

Could you please tell how to retreive our transaction hash (inner tx.hash) in the getBlock function OR how to arrive at the extrinsics (from tx.hash) which block.block.extrinsics array exposes?

**Comment by outlier89** [comment]
Perfect. INNER "tx.hash.toHex()" does the work.
