### ISSUE TITLE
version 4.0.4-13 api.derive.chain.getBlock(), PreRuntime,Consensus,Seal type error: 0000，should be the string ”BABE“

### ISSUE THREAD

**Issue by easyang** [polkadot-js/api#3319]
const signedBlockExtended = await api.derive.chain.getBlock("0xc0096358534ec8d21d01d34b836eed476a1c343f8724fa2153dc0725ad797a90");
signedBlockExtended.block.header.toHuman();

PreRuntime,Consensus,Seal type error: 0000, should be the string ”BABE“

**Comment by jacogr** [comment]
Which chain is that?

**Comment by easyang** [comment]
@jacogr chain  polkadot

**Comment by easyang** [comment]
> Which chain is that?

@jacogr chain polkadot
