### ISSUE TITLE
Recognizing a change from pending to finalized block on a known block

### ISSUE THREAD

**Issue by Swader** [polkadot-js/api#3325]
I am subscribed to blocks. When I notice a specific extrinsic, my UI reacts in a certain way. 

If the block in which the extrinsic was noticed ends up not being finalized, the UI reacts in a certain way, and if it does get finalized, it reacts in another way.

What is the easiest way to figure out if a given block X I've noticed as non-finalized has been finalized, other than checking if `lastFinalizedHead is > {blocknum}` and then checking if block at X has the hash equal to its original hash from when it was noticed? 

Is there an event of some kind built into the API perhaps which would let me react to this in a cleaner way?

**Comment by jacogr** [comment]
You can subscribe to finalized headers. 

But there is no trigger when blocks go into finalized otherwise - also bear in mind that multiple blocks may be finalized at once. (In normal operations this doesn't seem like an issues, but when finality lags, it will catch up and do chunks)

**Comment by Swader** [comment]
The problem with being subscribed to only finalized headers is that I can't notice a non-finalized block in time and react to stuff inside it to modify the UI etc. So we would have to sub to both non-finalized and finalized and then remove the non-finalized from consideration after comparing the sets. Ok, thanks.

Somewhat related to https://github.com/polkadot-js/extension/issues/672
