### ISSUE TITLE
How to register a custom pallet in the ApiPromise so that we can call it with polkadotjs?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [polkadot-js/api#3327]
I'm trying to do the following 
```await api.tx.custom.function()```but it throws the following error ```TypeError: Cannot read property 'function' of undefined``` How do we register the custom pallet in our ApiPromise?
substrate version ```3.0.0```

**Comment by jacogr** [comment]
There is no registration, see https://polkadot.js.org/docs/api/start/basics#metadata

If properly configured on the node, the Node adds all the details to the metadata.
