### ISSUE TITLE
Unnominate specific validator

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3328]
Hey @jacogr
I can nominate many validators, so 
### How can I unnominate the _specific validator_ by request?

I saw `api.tx.staking.chill()`, but it seems to unnominates all validators.
I saw `api.tx.staking.kick(who)`, but it seems to kicks nominators, and the validator must sign this transaction.

So, as a nominator, how can I unnominate the validator specifying the **address** of this validator?

**Comment by jacogr** [comment]
You re-nominate with the validator excluded. The whole list gets replaced.

**Comment by MrRakhim** [comment]
ok, got it, thanks!
