### ISSUE TITLE
meet  `LE` or `BE` problem when use Codec toJSON to decode number

### ISSUE THREAD

**Issue by yjhmelody** [polkadot-js/api#3331]
I meet the problem when decode `EventCount`.
The bytes are reversed.

**Comment by jacogr** [comment]
You will need to be quite specific here as to what you are doing.

**Comment by yjhmelody** [comment]
When I decode key: '0x26aa394eea5630e07c48ae0c9558cef70a98fdbe9ce6c55837576c60c7af3850', val: '0x07000000'

The `val.toJSON()` return 117440512, but in the `LE` it's 7 which is what we want.

**Comment by jacogr** [comment]
The issue is that you are passing in `0x70...` - the hex format is always BE (mapping with Substrate where the RPCS are using hex values, which are always BE).

**Comment by yjhmelody** [comment]
I know that, but how to solve it ? We don't know the scale encoded value type before decoding it.

**Comment by yjhmelody** [comment]
Oh, I have known how to solve it. Thanks.

**Comment by yjhmelody** [comment]
Oh, You reversed the LE/BE.  `0x07000000` is 7 of LE.

**Comment by jacogr** [comment]
It is, as mentioned by design. Hex is always treated BE as an input. 

(If not done that way, any number result retrieved via RPC won’t be able to be decoded)

**Comment by yjhmelody** [comment]
But rpc returns LE data.

**Comment by jacogr** [comment]
Not for numbers. The encoding for RPC is BE.

**Comment by jacogr** [comment]
Example, local dev node -

```
$ curl -H "Content-Type: application/json" -d '{"id":"1", "jsonrpc":"2.0", "method": "chain_getHeader", "params":[]}' http://localhost:9933

{"jsonrpc":"2.0","result":{"digest":{"logs":["0x0642414245340200000000b97f1a2000000000","0x044241424529010104d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d0100000000000000c2e33ea793bd9c79f0f6c1355dec3ddf2f509a9d1bb28558e22d7b25d06010c3","0x05424142450101a88cab5950763225ede7488fefd522cc45668638adf11a5289eaa38293a1b3321ee0f3a1b0b42f0d181c010bb63a79b6b578ff18bd2ef8f7510a300745c85186"]},"extrinsicsRoot":"0x9ecd73a3b9e96e6c2ae847dc583ac878773db958177e9650b88b82460ea192bd","number":"0x2188","parentHash":"0xe5579c26e25ce0f6c955d060f203e1baba3a205ec4a0c40ea62a3e4585ff8d6d","stateRoot":"0xdef2e9e3bc56affc8314da4706868fb0eaf17a0aa07d18d0fdbe5911b9079ded"},"id":"1"}
```

`0x2188` for the blockNumber, which is `8584` in BE, which is -

![image](https://user-images.githubusercontent.com/1424473/111617465-6c588a80-87e3-11eb-9079-6bc84dbd7fe1.png)

**Comment by yjhmelody** [comment]
Well, I thought it was referring to methods like `state_getStorage`. 

`chain_getHeader`'s block number is indeed a BE.
