### ISSUE TITLE
an account free balance returned as wrong value!!!!

### ISSUE THREAD

**Issue by gitloverr** [polkadot-js/api#3332]
hi everyone,

I checked an account balance over **my node** and **rpc.polkadot.io url**, but the account free balance returned as total balance value. My code snippets here and I checked this address: **[14g72vf47zeY3Fr4E22Cf1bkvFHsMmTAyFTug3BgjJHvepzb](https://polkadot.subscan.io/account/14g72vf47zeY3Fr4E22Cf1bkvFHsMmTAyFTug3BgjJHvepzb)**

```
  const lastHdr = await api.rpc.chain.getHeader()
  const [{ data: balanceNow }] = await Promise.all([api.query.system.account.at(lastHdr.hash, address)])
  console.log("free balance",`${balanceNow.free}`)

 >>>> **free balance : 1619489858194711** but the address transferable balance is **6,948.985819471098 DOT**

```

what's wrong? why the result returns as a wrong value? 

thank you

**Comment by jacogr** [comment]
Ensure that you are on a recent version of the API - the AccountData structure have changed recently (and will change again in Polkadot runtime 30)

**Comment by gitloverr** [comment]
hi, @jacogr  I updated all packages and then  `console.log("balance",`${balanceNow}`) ` is returned this:

` balance {"free":1619489858194711,"reserved":0,"miscFrozen":1550000000000000,"feeFrozen":1550000000000000}`

now, which is the transferrable balance from this snippet?

also what is misc frozen and fee frozen?

thank you

**Comment by jacogr** [comment]
The amount you can transfer, its free amount - locked amount. The locked amount comes from api.query.balances.locks.

**Comment by gitloverr** [comment]
hi @jacogr 
 it's ok! 

thank you
