### ISSUE TITLE
Implement output for ContractSubmittableResult the same way it is in ContractExecResult

### ISSUE THREAD

**Issue by vminkov** [polkadot-js/api#3349]
Currently calls with contract.**query**.method() return the output, but calls with contract.**tx**.method() do not and in pieces like this one:

```
    #[ink(storage)]
    pub struct MyContract {
        counter: u32,
    }

    pub enum Error {
        CustomError,
    }

    pub type Result<T> = core::result::Result<T, Error>;

    #[ink(message)]
    pub fn callMethod(&mut self, value: u32) -> Result<()> {
         *self.counter += value;
         if value % 2  {
            Err(Error::CustomError)
         } else {
            Ok(())
        }
    }
```

it is not possible to extract the output from ContractSubmittableResult - its fields are 
```
[
  "dispatchError",
  "dispatchInfo",
  "events",
  "status",
  "contractEvents"
]
```

whereas ContractExecResult has:

```
[
  "debugMessage",
  "gasConsumed",
  "output",
  "result"
]
```

**Comment by jacogr** [comment]
There is a difference between exec and read - exec sends a transaction, transactions do not return values like a read call does. (The only communication a transaction does have is with events)

**Comment by vminkov** [comment]
Well, this basically means that we have emit events to know the reason why a transaction failed? Is there a better way to do that in ink?

**Comment by jacogr** [comment]
The general and only way a transaction can communicate with the outside world (providing info on success) is via events. For Substrate itself, error conditions are indicated with an Error enum that is returned via the ExtrinsicFailed event itself.

If a failure is meant to emit an event, it would mean the transaction needs to succeed - event are not emitted on ExtrinsicFailed statuses.

I'm no ink! expert (only understand how transactions actually do work), so it may be worth-while asking the team, they would be happy to help.

**Comment by RoyTimes** [comment]
I think I came across the same issue at https://github.com/patractlabs/redspot/issues/78 . @vminkov would you mind keeping me posted if you are able to resolve this?

**Comment by hychen** [comment]
@RoyTimes  The error forwarding of ink! is not implemented and still under discussion.
https://github.com/paritytech/ink/issues/641
