### ISSUE TITLE
Type '[xx, xx, xx]' does not satisfy the constraint 'AnyTuple'

### ISSUE THREAD

**Issue by herryho** [polkadot-js/api#3350]
Hi,

When I use "polkadot-dev-build-ts" for type generation, I got a bunch of "Type '[xx, xx, xx]' does not satisfy the constraint 'AnyTuple'" messages. It didn't show up before. Seems there's some issue with the tuple type. Could you please have a look at it?

![image](https://user-images.githubusercontent.com/45537372/112140765-66154480-8c0f-11eb-8d08-135d23ed84e4.png)

**Comment by jacogr** [comment]
The API itself uses the same type generator. It does not show up any errors, see e.g. https://github.com/polkadot-js/api/blob/master/packages/api/src/augment/events.ts#L35

**Comment by herryho** [comment]
We recently have been working on parachain, so we are using the rococo branch code base. That's the biggest difference compared to our previous code which didn't have the type generation issue. Is there any chance that the problem is caused by this?

**Comment by herryho** [comment]
It turned out to be the version matching issue of polkadot.js and substrate.  Api 4.0.1 is working fine while 4.2.1 is not.  Thanks anyway!
