### ISSUE TITLE
Unable to set validator preferences.

### ISSUE THREAD

**Issue by karthikeyan-cere** [polkadot-js/api#3353]
I am trying to set the validator preference using the below code. 
 ```javascript
   const commission = +process.env.REWARD_COMMISSION;
    const transaction = this.api.tx.staking.validate({
      commission,
    });

    return new Promise((res, rej) => {
      transaction.signAndSend(controllerAccount, this.sendStatusCb.bind(this, res, rej))
        .catch((err) => rej(err));
    });
  }
```

But I couldn't able to successfully apply it. By default every time the commission is passed a 0 for whatever value I pass.

Version: 
"@polkadot/api": "^3.11.1"

**Comment by jacogr** [comment]
It depends on which chain - the Validator preferences has been changed in Substrate and it has been deployed on chains such as Kusama and Polkadot. so in those cases, I would suggest a bump of the API which has all the newer types.
