### ISSUE TITLE
Initializing ApiPromise blocking browser thread

### ISSUE THREAD

**Issue by kdembler** [polkadot-js/api#3356]
Hey!

I run into an issue when integrating dapp with our Substrate-based blockchain with `polkadot.js`. Everything seems to be working fine, except that the initialization of the API seem to block the browser thread for ~3s.

I'm calling:

```ts
await ApiPromise.create({ provider, types });
```

and that seems to cause the browser to engage in some heavy operations.

This is a screenshot of the Chrome performance capture:
<img width="1307" alt="Screenshot 2021-03-25 at 15 35 33" src="https://user-images.githubusercontent.com/12646744/112524991-b7a10900-8da0-11eb-801c-b51590245b23.png">

Any ideas on what might be causing it? Would greatly appreciate any help, I'd really wouldn't want to have to stick it in a web worker 😅 

I'm running `@polkadot/api@1.26.1` since this is what our types package currently rely on. Is it possible this has been improved in some more recent version?

cc @nukemandan

**Comment by jacogr** [comment]
Please upgrade, really cannot support versions 3+ versions old.

**Comment by kdembler** [comment]
Hey @jacogr, haven't replied here before, but I think this is worth keeping open? We updated to the latest version available and the problem persists pretty much the same.

I understand that the operations may take some time, but maybe it would be worth considering how this waiting could be shortened or maybe there's some more general change possible to not have to parse all of this.

You have to use this library if you want to create a polkadot/substrate-facing dApp and if you want it to thrive, be sleek and user-friendly you cannot really accept blocking a thread for a couple of seconds.

I'm sure this is something non-trivial to do but I think worth considering, as a future improvement

**Comment by jacogr** [comment]
JS has one thread - this thread is used for -

- the UI
- any network connections
- any timers, etc.

There is nothing that can be done, library wise in this environment. If you want more responsive UIs, then move the API itself to a worker.
