### ISSUE TITLE
Keyring persistence functionality (save/load/import/export)

### ISSUE THREAD

**Issue by TrustVeriCor** [polkadot-js/api#3357]
Requesting api documentation on basic keyring persistence functionality. Also document any integration with subkey that can be leveraged for these purposes.

**Comment by jacogr** [comment]
The keyring itself does not have persistence. However it is implemented as part of the ui-keyring - https://github.com/polkadot-js/ui/tree/master/packages/ui-keyring

There is no explicit documentation on use thereof.
