### ISSUE TITLE
Stuck problem to get block #6137913

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3360]
I'm trying to get block #6137913 using `api.rpc.chain.getBlcok(blockhash)` method. But It took about 12 minutes to execute. 
I tried `getBlock()` on other blocks, but the results were much faster.

Any other way? or How can I solve it?

The information is here. Thanks.

[Sample Code]
```javascript
const { ApiPromise } = require('@polkadot/api');
const util = require('util')

async function main() {

    const api = await ApiPromise.create();

    let start = new Date()
    let blockHash = '0xe079dd31cee9874b392ddd4e496ffe2f562ce9ed7ebcd9a7a4e29b328c6db8e5'
    const block = await api.rpc.chain.getBlock(blockHash) // 11.934583333333334s
    let end = new Date()
    console.log((end - start) / 1000 / 60)

    console.log("get Block\n", util.inspect(block.toHuman(), false, null, true))

}

main().catch(console.error);
```

[Used SDK version]
@polkadot/api: 4.2.1 (4.2.2-4 have same problem..)

**Comment by jacogr** [comment]
Which chain?

**Comment by boohyung** [comment]
Oh, Sorry. This is Kusama @jacogr

**Comment by jacogr** [comment]
The block before is an upgrade block, so if the API does not have the metadata for that version yet, it needs to retrieve and parse it as well. (Which is why the first block after an upgrade will always take longer, the block after will be faster again since the API can use the metadata already retrieves).

Having said that, it should not be 12s, more along the lines of the first init of the API where it also needs to get the metadata.

**Comment by boohyung** [comment]
Thanks @jacogr. I understood the cause. But does that mean you can't help it? 
And the first block on 2028 runtime is #6137912.(https://kusama.subscan.io/block/6137912) but block that caused problem is #6137913. I'm so sorry I'm confused your mention.

**Comment by jacogr** [comment]
The new runtime metadata takes effect the block after the upgrade. (Since the upgraded code is only effective the block after)

**Comment by boohyung** [comment]
Thanks for supporting me :D

**Comment by jacogr** [comment]
I would also suggest trying the new 4.9.2 release (same as 4.9.1, just had publishing issues, hence the follow-up patch). 

There has been a change to the metadata retrieval for historic blocks, which does speed things up by a small amount. (Sadly we still need to get and parse the blob of data, so it will never be as fast as a known metadata-without-upgrade block)
