### ISSUE TITLE
Including tip and memo into transaction

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3363]
### Hey, @jacogr

How can I include tip on api transaction `await api.tx.balances.transfer(BOB, 12345)`? 

Also, is there way to include some memo/comment/note to transfer?

**Comment by jacogr** [comment]
Send a utility.batch transaction including both the transfer and a system.remark . Substrate does not have an additional memo field on transfer.

**Comment by jacogr** [comment]
Pass the tip field as part of the signAndSend options.

**Comment by MrRakhim** [comment]
I could, so what about comment?

**Comment by jacogr** [comment]
Send a utility.batch containing both the transfer and system.remark. Substrate does not have a memo field with transfers.
