### ISSUE TITLE
tx.utility undefined

### ISSUE THREAD

**Issue by bakasura980** [polkadot-js/api#3364]
What is the correct way of processing several transactions in a batch. In the documentation, there is an out-dated example 
```
// construct a list of transactions we want to batch
const txs = [
  api.tx.balances.transfer(addrBob, 12345),
  api.tx.balances.transfer(addrEve, 12345),
  api.tx.staking.unbond(12345)
];

// construct the batch and send the transactions
api.tx.utility
  .batch(txs)
  .signAndSend(sender, ({ status }) => {
    if (status.isInBlock) {
      console.log(`included in ${status.asInBlock}`);
    }
  });
```

When I try to run it, I receive tx.utility undefined

**Comment by jacogr** [comment]
The example is correct. 

The chain you are connecting to does no include the utility pallet. Add it in the runtime/lib.rs 

batch transactions are only exposed by the utility pallet.
