### ISSUE TITLE
Multisig address validation

### ISSUE THREAD

**Issue by Swader** [polkadot-js/api#3366]
The docs say the easiest way to validate an address is to decode/encode it and catch an error. However, a valid multisig like DXqEcdGwGGtxLGEob55qMbZgHfkdBpEKPL2pph4w6UktS3 will always fail this test - and even produces an error page in the various blockchain explorers. What can we do to validate a multisig address?

**Comment by jacogr** [comment]
A multisig address is just an AccounId encoded. So it should pass the test.

The only difference between he 32 bytes in a normal AccountId and multisig is how it is created. See https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/encodeMulti.ts
