### ISSUE TITLE
custom rpc enum parameter first letter capitalization

### ISSUE THREAD

**Issue by herryho** [polkadot-js/api#3367]
Hi,

We have defined some custome rpcs. However, when using the format of "await api.rpc.<Module>.<method>" to invoke the rpc function, I've got the following error:
![image](https://user-images.githubusercontent.com/45537372/113396454-264c1b00-93ce-11eb-9dd8-633473151c7e.png)

But the parameters I passed in are right. Is this problem related to the [#3023](https://github.com/polkadot-js/api/issues/3023) ?

**Comment by jacogr** [comment]
Ummm, ok. This is an issue, yes. 

Generally the serde flag for camelCase is added to all enums in Substrate. This is why the behavior was changed, since previously it didn’t and was not matching with camelCase as expected.

**Comment by herryho** [comment]
So when will it be fixed? Or I need to lowercase the first letter of my enum names?

**Comment by jacogr** [comment]
There will be no fix on the API layer.

As I mentioned, by default Substrate does all enums with lowercase when using serde. As an example picking the first Enum in Substrate based on a file I had open - https://github.com/paritytech/substrate/blob/master/frame/support/src/weights.rs#L218-L238

**Comment by herryho** [comment]
Thanks, Jaco. Finally, I added the macro `#[cfg_attr(feature = "std", serde(rename_all = "camelCase"))]` right before the definition of my Enum, which solved my problem.
