### ISSUE TITLE
TypeError: api.query.session.validators.keys is not a function

### ISSUE THREAD

**Issue by guillaumegaluz** [polkadot-js/api#3373]
Going through this tutorial https://polkadot.js.org/docs/api/start/api.query.multi

and executing:

```
const validatorKeys = await api.query.session.validators.keys();
```

I'm on `"@polkadot/api": "^4.4.1"`

**Comment by jacogr** [comment]
Which chain?

**Comment by guillaumegaluz** [comment]
sorry for the late reply @jacogr. sounds good.

Should the docs reflect that by changing

```
// Retrieve a snapshot of the validators
const validatorKeys = await api.query.session.validators.keys();
```

to 

```
// Retrieve a snapshot of the validators
const validatorKeys = await api.query.session.validators;
```

?

**Comment by jacogr** [comment]
Yes, that will be the right version -

```js
const validatorIds = await api.query.session.validators();
```

(Just added the missing `()` above to make the call)

**Comment by guillaumegaluz** [comment]
Yes yes sorry, wrote too fast! Thanks
