### ISSUE TITLE
failed to getBlockHash() on Rococo

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#3377]
Hi, I'm trying to use api.rpc.chain.getBlockHash(190453) to get blockhash on Rococo,  it will print following errors. 

```
h = await api.rpc.chain.getBlockHash(9000)
2021-04-08 16:59:56        REGISTRY: TypeError: Cannot read property 'subarray' of null
```
However , it works fine when try to get block hash from #8000 and smaller.

Im on @polkadot/api: 4.4.2-0.

**Comment by jacogr** [comment]
Rococo was reset and the types updated. So highest block atm is 9,958 (as of right now)

If you have a problematic hash, can check it against the apps UI (which has the latest API), there still could be a type update I missed (there was a number that went in along the reset).
