### ISSUE TITLE
Generating a large nested type ie: Vec<Option<ITuple[AccountId, BlanaceOf]>>

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#3381]
## My Issue

Method: `api.query.slots.leases.at`

Return Type: `Vec<Option<ITuple<[AccountId, BalanceOf]>>>` or `Option<ITuple<[AccountId, BalanceOf]>>[]`

Reference: ['polkadot/apps'](https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/useFunds.ts#L149)

Our implementation: [Sidecar](https://github.com/paritytech/substrate-api-sidecar/blob/feat-experiment-plo-endpoints/src/services/paras/ParasService.ts#L135)

Now our implementation works, as far as manually testing can take us, but the current issue I am having is being able to generate that exact return type for our test suites. Specifically with `Vec` and `Option` I am using a similar implementation as [this](https://github.com/polkadot-js/api/blob/master/packages/api-derive/test/bountyFactory.ts#L30), but I am having trouble understanding how to generate an `ITuple` type. The current registry I am using as well is a rococoRegistry. 

I am curious how you would go about generating a type like this, or if you could point me to the right files, where there is a similar implementation. 

Thanks again for everything!

**Comment by jacogr** [comment]
A tuple is just a Limited Array with know types. So [AccountId, BalanceOf]

Don’t really have the inclination to read cod outside of polkadot-JS and trying to follow a thought pattern, but happy to help with pin-point specifics.

**Comment by TarikGul** [comment]
Awesome I was able to figure it out. I was wildly over-thinking a very simple concept! 

> A tuple is just a Limited Array with know types. So [AccountId, BalanceOf]

That just gave me the kick in the head I needed, thank you! 

Then for types such `StorageKey`, `Option` and `Vec`, I am using a very similar kind of Type Factory you have for Bounties, so thank you so much for that as well.  

Closing this issue!
