### ISSUE TITLE
Possible wrong type on extrinsicCount.at(block_hash)

### ISSUE THREAD

**Issue by manylov** [polkadot-js/api#3383]
const eventCount = await polkadotConnector.query.system.eventCount.at(block_hash) 
has type EventIndex with .toNumber() method

const extrinsicCount = await polkadotConnector.query.system.extrinsicCount.at(block_hash) 
has type Option<u32> and has no methods to return extrinsics count

**Comment by jacogr** [comment]
Which blockHash and which chain?

**Comment by manylov** [comment]
@jacogr 
Thank you for reply. but I asked about extrinsicCount.at():

Here is block with 4 extrinsics: https://polkadot.subscan.io/block/0xc9f63d52944cec7f3c3f682168a89132ba3abc4883c4cc2e7c0de2f5d088006c?tab=extrinsic

`const e1 = await api.query.system.extrinsicCount.at('0xc9f63d52944cec7f3c3f682168a89132ba3abc4883c4cc2e7c0de2f5d088006c')
  const e2 = await api.query.system.allExtrinsicsLen.at('0xc9f63d52944cec7f3c3f682168a89132ba3abc4883c4cc2e7c0de2f5d088006c')

e1.toHex() // 0x
e1.toHex() // 0x
`

How can I get extrinsics count for block?

**Comment by jacogr** [comment]
ExtrinsicsCount and length are option - https://polkadot.js.org/docs/substrate/storage#extrinsiccount-optionu32

you generally don’t want to use the system storage for these, they are used as scratchpad for block construction.
