### ISSUE TITLE
Websocket 1006: Abnormal closure

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#3387]
We are constantly see websocket errors for our users as well as on our local machines if browser tab is open for a long time (over night for example)

`RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://node.rmrk.app: 1006:: Abnormal Closure`

And another one:

```
API-WS: disconnected from wss://kusama-rpc.polkadot.io: 1001:: Going Away
logger: console
arguments: ["2021-04-10 20:07:07","         API-WS:","disconnected from wss://kusama-rpc.polkadot.io: 1001:: Going Away"]
```

![photo_2021-04-10 12 05 16](https://user-images.githubusercontent.com/666169/114267710-2d3de380-99f5-11eb-8dcd-a0c8a17cc378.jpeg)

Any clues as to why this might be happening?

**Comment by jacogr** [comment]
In the background the browser will de-prioritize the tab, which means heartbeats are not being sent https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L342-L344, which means the connection is dropped by the node. Same when the computer is running in power-saving mode.

**Comment by Yuripetusko** [comment]
Thanks Jaco for clearing this up
