### ISSUE TITLE
How to catch errors for not found types.

### ISSUE THREAD

**Issue by hbulgarini** [polkadot-js/api#3396]
Hey ! i'm having difficulties to catch the errors in my app for the issue types:

```
REGISTRY: Error: createType(Call):: Call: failed decoding bridgeMillauGrandpa.submitFinalityProof:: Struct: failed on args: :: Cannot construct unknown type GrandpaJustification
```

```
VEC: Unable to decode on index 3 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding bridgeMillauGrandpa.submitFinalityProof:: Struct: failed on args: :: Cannot construct unknown type GrandpaJustification
```

I'm basically trying to catch them using the `api.on('error`...` event listener but it is not triggering it.

FYI I took as reference these issues : #3070 & #3394

@tomusdrw

**Comment by tomusdrw** [comment]
@hbulgarini do you have stack trace? If there is no stacktrace it's most likely not an exception, but a logger printing these. Also it would be good to know what concrete code triggers this and make it a minimal example.

**Comment by hbulgarini** [comment]
> @hbulgarini do you have stack trace? If there is no stacktrace it's most likely not an exception, but a logger printing these. Also it would be good to know what concrete code triggers this and make it a minimal example.

```
index.js:1 2021-04-13 08:43:30        REGISTRY: Error: createType(Call):: Call: failed decoding bridgeMillauGrandpa.submitFinalityProof:: Struct: failed on args: :: Cannot construct unknown type GrandpaJustification
    at createTypeUnsafe (createType.js:56)
    at createType (createType.js:67)
    at TypeRegistry.createType (registry.js:284)
    at Function.decodeExtrinsic (Extrinsic.js:37)
    at new GenericExtrinsicV4 (Extrinsic.js:16)
    at new Type (registry.js:327)
    at initType (createType.js:34)
    at createTypeUnsafe (createType.js:53)
    at createType (createType.js:67)
    at TypeRegistry.createType (registry.js:284)
    at Function._newFromValue (Extrinsic.js:185)
    at Function._decodeU8a (Extrinsic.js:216)
    at Function._decodeExtrinsic (Extrinsic.js:195)
    at new GenericExtrinsic (Extrinsic.js:171)
    at new Type (registry.js:327)
    at Vec.js:31
    at Array.map (<anonymous>)
    at Function.decodeVec (Vec.js:29)
    at new Vec (Vec.js:19)
    at new <anonymous> (Vec.js:48)
    at Struct.js:45
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (Struct.js:11)
    at decodeStruct (Struct.js:98)
    at new Struct (Struct.js:119)
    at new GenericBlock (Block.js:12)
    at new Type (registry.js:327)
    at Struct.js:45
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (Struct.js:11)
    at decodeStruct (Struct.js:98)
    at new Struct (Struct.js:119)
    at new <anonymous> (Struct.js:138)
    at new Type (registry.js:327)
    at new Type (registry.js:327)
    at initType (createType.js:34)
    at createTypeUnsafe (createType.js:53)
    at RpcCore._formatOutput (index.js:363)
    at callWithRegistry (index.js:229)

```

**Comment by jacogr** [comment]
It is not catch-able, if this happens the API is in a dead state. It could probably be exposed with a lot of hoops, since the process itself gets triggerred as part of an event.

It does emit an error - https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L332

**Comment by jacogr** [comment]
Ahhh... this is on a result. These should reject the promise when you do a single await api.query.something()

**Comment by tomusdrw** [comment]
It seems to be comming from an error in `onSocketMessage`
https://github.com/polkadot-js/api/blob/e0e075b350414c1cf9bd881c629892587be18d9b/packages/rpc-provider/src/ws/index.ts#L378-L380

Perhaps these errors should be try-catched nad propagated to `onSocketError`?

**Comment by hbulgarini** [comment]
@jacogr i have created a simple repo with the isolated case for your review:

https://github.com/hbulgarini/reproduce-non-catched-polkadotjs-error

Please take into account that code contains hardcoded values which i think it does not make the difference for this code example.

Here is when tomek says that the error should be catched and it is not:
https://github.com/hbulgarini/reproduce-non-catched-polkadotjs-error/blob/master/src/App.tsx#L77

Please let me know for any questions.

**Comment by jacogr** [comment]
Ok. So it is in the getBlock RPC call not storage. Those should indeed reject the promise.

**Comment by jacogr** [comment]
Strangely enough, trying to mess around with the types does reject for me -

```js
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main () {
  const api = await ApiPromise.create({ provider: new WsProvider('wss://kusama-rpc.polkadot.io') });

  api.registerTypes({ 'Header': { _enum: { Something: 'Null' } } });

  api.rpc.chain
    .getBlock()
    .then((b) => console.log('block', b))
    .catch((e) => console.error('error', e))
    .then(() => process.exit(0));
}

main().catch(() => process.exit(-1));
```

**Comment by hbulgarini** [comment]
I think the error is generated on our chain when it tries to read the events inside the singAndSend method ( which i think you don't have those kind in kusama )

https://github.com/hbulgarini/reproduce-non-catched-polkadotjs-error/blob/master/src/App.tsx#L68

Does that make sense?

**Comment by jacogr** [comment]
Ok, for those, this is probably a "won't fix", as irritating as it is.

The API does warn on unknown types right up-front. This warning used to be an outright fail, however pressure suggestions turned it to only be a warning - the reason for the outright failure initially was specifically since unknown types just creates chaos. If they are missing, all bets are off.

Having said that, unlike queries/RPC the tx.* does not bubble the error into a promise once-off rejection like the code I linked. That is an enhancement worts having, that will catch "some" of them.
