### ISSUE TITLE
Validators of active era

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3402]
Hey, @jacogr 
By following flow 
```
const era = await api.query.staking.activeEra();
return (await api.query.staking.erasValidatorPrefs.entries(era.index));
```
(extra question: Let me know if there is way to set limit and offset to the request)
I'd like to fetch all validators of active era.

Format I'd like to get:
```
[
    [
      317,
      1zugcag7cJVBtVRnFxv5Qftn7xKAnR6YJ9x4x3XLgGgmNnS
    ],
    {
      commission: 0.70%,
      blocked: false
    }
],
```
Format I am getting:
```
[
        "0x5f3e4907f716ac89b6347d15ececedca682db92dde20a10d96d00ff0e9e221c009817eca757b54f8ee00000077ffb7a9541c00bed682e2bffca19e9276a79ab0bf0d76fbb5ac62cc7938b4c3ec7463543539c870",
        {
            "commission": 70000000,
            "blocked": false
        }
],
```
Can you show some tricks please?)

**Comment by jacogr** [comment]
Not all the keys will be decodable, as above. For older versions of the runtime the keys were generated via an opaque hashing, that was changed at a later point which made the keys decodable into the parts.

There is a `entriesPaged` query point as well, it takes the key of the last one retrieve as a param in the options - https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Decorate.ts#L406

(Have not used it myself, it was contributed, so no documentation)

**Comment by MrRakhim** [comment]
But I've tried on polkadot.js/app 
got this 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/24478899/114710447-89836900-9d4f-11eb-8dd9-d99dd1763821.png">

**Comment by jacogr** [comment]
Yes, the apps UI uses the `args` params on the key to extract the params.

**Comment by MrRakhim** [comment]
How nicknames of addresses can be retrieved ?
<img width="386" alt="image" src="https://user-images.githubusercontent.com/24478899/114866951-04af5280-9e16-11eb-9fa1-5773cc7f6d1f.png">

**Comment by jacogr** [comment]
I appreciate you re-opening, but this has got nothing to do with the issue as reported. Mix/matching issues makes it incredibly difficult for me to keep track and also makes future search impossible.
