### ISSUE TITLE
Allow passing types for different specVersion

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#3406]
Official chains have fallback mechanism, but It is not supported for custom chain. (as far as I know)
So unless the types provided are backward compatible, there will be problem to query historical blocks.

I think we can extend `RegisteredTypes` to accept a map of type where key is specVersion. 

Happy to contribute, but want to discuss first about the preferred approach and type interface.

**Comment by ianhe8x** [comment]
`types?: OverrideVersionedType[];` in `OverrideBundleDefinition` seems can support that.

**Comment by jacogr** [comment]
Indeed the bundled types do support versioning - that is how the Polkadot-family gets managed (Polkadot, Kusama, Westend, Rococo)

The apps UI now also defaults to the bundle by default to accept types across multiple versions and upgrades.
