### ISSUE TITLE
how to pass FixedU128 to substrate(FixedU128:: Assertion failed)

### ISSUE THREAD

**Issue by ziwenxie** [polkadot-js/api#3419]
I want to pass `0.05 * 10e18`(FixedU128) to substrate, but `0.05 * 10e18` exceeds the maximum value that Javascript can represent. 

Numeric literals with absolute values equal to 2^53 or greater are too large to be represented accurately as integers.ts(80008)

error info: `Struct: failed on price_limit_fixedu128: FixedU128:: Assertion failed`

Is there any way to solve it?

**Comment by jacogr** [comment]
Pass it as -

- a BN
- a JS BigInt
- a base-10 string
- a hex string

All those are handled and the API will always convert to BN internally before use.

**Comment by ziwenxie** [comment]
thx:) @jacogr
