### ISSUE TITLE
how to catch substrate error in polkadot.js

### ISSUE THREAD

**Issue by ziwenxie** [polkadot-js/api#3421]
Substrate returns `DepositNotEnough`, but `await txExecute.signAndSend(...).catch(txErrHandler)` does not catch and `status.isFinalized` == `true`.

```js
  const txResHandler = ({ status }) =>
    status.isFinalized ? setStatus("😉 Finalized") : setStatus(status.type);
  const txErrHandler = (err) => {"debug", console.log(err)};
  const signedTx = async () => {
    const fromAcct = await getFromAcct();

    const txExecute = inputParams
      ? api.tx[palletRpc][callable](...inputParams)
      : api.tx[palletRpc][callable]();

    const unsub = await txExecute
      .signAndSend(fromAcct, txResHandler)
      .catch(txErrHandler);
```

how to catch substrate `DepositNotEnough` error like below:

![image](https://user-images.githubusercontent.com/24546717/115548346-f3fd5180-a2d9-11eb-9800-1de6364a8cfb.png)

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event

**Comment by ziwenxie** [comment]
thx @jacogr
