### ISSUE TITLE
Secure passing data from client to server

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3422]
Hey, @jacogr 

We got such situation that client part (VueJs) cannot initialize api to sign the Tx, because of WsProvider can not be connected;

Question: Is that secure to pass Keyring which stores seed or mnemonic phrase from front-end to back-end, so back-end could signAndSend the transactions. If it is, in which format can we pass keyring from front-end, in order to back-end could **re-create the keyring** to sign the Tx?

For example, we can pass the tx in hex and re-create submittable by `api.tx(hexedTx)`

**Comment by jacogr** [comment]
If you have a backend, I would suggest not exposing the keyring on the front end. An example of this is the polkadot-JS extension - the UI it Wald has no access to any pairs, all keyring related operations are doing in the backend (with message passing between the two)

**Comment by MrRakhim** [comment]
but we made the emphasis that the front has to sign the tx, so the private key is not passed to the backend

**Comment by jacogr** [comment]
Keep the signing and key together. So in that case sign on front-end, send on back end. If you want to pass the seed across, you would need to use some (not in scope for the keyring), encryption or secure transport.
