### ISSUE TITLE
Sign the extrinsic Tx without api

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3427]
Hey, @jacogr 

on backend I create Tx by `api.tx.balances.transfer(toAddress, amount).toHex()` and send it to frontend.

How frontend can re-create Submittable without using **provider and api**, and sign it offline, in the end response me signedTx in hex value?

Front can create Keyring through mnemonic, but can not create ApiPromise

**Comment by jacogr** [comment]
https://github.com/polkadot-js/tools/tree/master/packages/signer-cli

**Comment by MrRakhim** [comment]
Any example repos?)

**Comment by MrRakhim** [comment]
> https://github.com/polkadot-js/tools/tree/master/packages/signer-cli - split creation/submission from signing

Hey, @jacogr you did not understand what I meant. I'd like to re-create Submittable on frontend without using ApiPromise and without connecting to Provide, but still use @polkadot/api package.

**Comment by jacogr** [comment]
That is exactly what the above does -

1. the creation part has access to the network and ApiPromise
2. the signer has only access to the keyring and the bytes to sign - https://github.com/polkadot-js/tools/blob/master/packages/signer-cli/src/cmdSign.ts#L41

**Comment by MrRakhim** [comment]
Thank you, I got it, but I am getting an error:  `Hash:: 1010: Invalid Transaction: Transaction has a bad signature`
<img width="703" alt="image" src="https://user-images.githubusercontent.com/24478899/115902044-ca802980-a483-11eb-8612-fdc562795131.png">

**Comment by jacogr** [comment]
Look at the linked example and the RawSigner as linked above. The tx doesn’t get signed, the tax payload does (which has information not in the tx itself)

**Comment by MrRakhim** [comment]
Ok, got it. Can tx be converted to tx payload? I am asking because whole system Txs created as tx not tx payload((

**Comment by MrRakhim** [comment]
Hey, @jacogr. 
I have researched that repo.

I tried to create a payload for `const tx = api.tx.balances.transfer('14M7FSfuyQ8HDCx3dh2MK43ENcu59JMLSqGcVRkAMRL5ywAM', 1 *dot_decimal_places)`

And signed it on frontend, but still catching the error: `Hash:: 1010: Invalid Transaction: Transaction has a bad signature`;

Can you show, how to create a payload for Tx, please? 
I have tried 'SignerPayload' and 'Extrinsic', they're not working!

**Comment by MrRakhim** [comment]
Hey, @jacogr. 
I have researched that repo.

Created an ExtrinsicPayload on backend by `api.createType()...` and sent .toHex() to frontend.

How can I re-create this payload on frontend without api? I tried `new TypeRegistry().createType()...`, and got signature by pair.
but getting an error “invalid transaction”
