### ISSUE TITLE
"Cannot use import statement outside a module" on detectPackage.js

### ISSUE THREAD

**Issue by rjarasson-ledger** [polkadot-js/api#3430]
Hi !

Since upgrade to `@polkadot/api @ 4.6.2`, i have an issue when running.
I encountered the issue with webpack and jest, but also on `substrate-api-sidecar` @ 4.0.8.

Node version: 12.14.1
This issue seems to be solved when switching to Node 14, but i was not expecting to have to upgrade my Node version.

```
import "./detectPackage.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rjarasson/Ledger/3rdparty/polkadot/substrate-api-sidecar/build/src/main.js:19:15)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
 ```

**Comment by jacogr** [comment]
It is supposed to work on Node 12. However, this is not the first report of it not “working out of the box”. 

Have not had a gap to look at why Node 12 is problematic.

**Comment by gre** [comment]
relates https://github.com/polkadot-js/api/issues/3446

**Comment by Milszym** [comment]
Hey, I have the same issue when running `jest`. Everything works fine on `3.11.1`, but `4.6.2` throws the same error mentioned above.
I encounter the same behavior on all of the following node versions:
* 12.14.1
* 13.14.0
* 14.16.1

@jacogr do you have any updates here?

**Comment by jacogr** [comment]
Check the jest config in the repo. We also use jest here. 

Sadly jest is lagging behind in esm support, so nothing that I can do here.

**Comment by woss** [comment]
for now using the slightly modified `dev` scripts from the https://github.com/polkadot-js/dev/tree/master/packages/dev and adding the jest next version seems to work. let's see for how long :)

**Comment by jacogr** [comment]
For jest, the API and common repos use this - https://github.com/polkadot-js/api/blob/master/jest.config.cjs#L30

**Comment by woss** [comment]
that's under the assumption we are using yarn 2 :) 
I'm using pnpm. the paths are different in pnpm.  Upgrade to the jest@next worked. let's see when it breaks

**Comment by jacogr** [comment]
It is good news that jest@next works - I was hoping it would catch up sooner rather than later.

**Comment by woss** [comment]
for the reference on the new packages based on [polkadot dev setup ](https://github.com/polkadot-js/dev/tree/master/packages/dev) here is the list of upgrades
```
    "babel-jest": "^27.0.0-next.9",
    "jest": "^27.0.0-next.9",
    "jest-cli": "^27.0.0-next.9",
    "jest-config": "^27.0.0-next.9",
    "jest-haste-map": "^27.0.0-next.9",
    "jest-resolve": "^27.0.0-next.9",
```

**Comment by woss** [comment]
i was wrong :( it doesn't work. 
due to the sheer amount of fixes for the tests the API was still on the version `3.11.1` where the `api/package.json` does not contain `type: module` where as the latest `4.11.1` does and that breaks the jest for pnpm users not sure about yarn. 

the trick is to make the `transformIgnorePatterns` to exclude all `@polkadot` from transforming but ni'm not sure how to do it yet. anyone has the solution to this? maybe core team can test it in a simple env their integration in other projects?
