### ISSUE TITLE
Initiating api instance took too long. Passing in cached metadata doesn't help.

### ISSUE THREAD

**Issue by will-yijinin** [polkadot-js/api#3440]
When I cache the metadata and initiate api instance like this: 
`api = await ApiPromise.create({ provider: httpProvider, metadata });`

It took as much time as fetching metadata from the chain:
`api = await ApiPromise.create({ provider: httpProvider })`; 

How do I reduce the time it took to initiate an api instance then?

**Comment by jacogr** [comment]
Assuming your metadata is keyed correctly (genesis + spec), you will still need parsing of the info and decoration of the API. The only savings you get is from the network roundtrip for retrieval.

There are no speedups, the API has the init calls as parallelized as possible. (If keying the metadata wrong or if the cuerect genesis + spec is not available, this means it would actually be a slower init cycle)

**Comment by will-yijinin** [comment]
@jacogr I request the runtimeVersion first, compare the requested specVersion with the cached specVersion, and if they are the same, then input the cached metadata. However, either way it costs the same amount of time. It seems passing in metadata info doesn't save any time.

What is curious to me is that changing rpc provider from remote to local node saves a lot of time. It seems odd that it is faster with a local node but not downloading metadata doesn't make a difference. I wonder if I am passing in metadata the correct way.

So is it enough to just pass in metadata to avoid API downloading it again?

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L265-L270 for the key layout creation.

(`metadata` is a `Record<string, string>` , key + hex-encoded as per https://github.com/polkadot-js/api/blob/master/packages/api/src/types/index.ts#L46)
