### ISSUE TITLE
@polkadot/api@4.7.1 requires node >= 14.0.0

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#3446]
I just wanted to bring this issue up as I noticed the `.nvmrc` file is still on node 12. I am using node 14.x locally which is why no errors were found, but our CI pipeline is using node 12 which brought up the build error. 

The quickest way I found to reproduce this error was. 

First, see what version's of node you have available:
```
$ nvm list
``` 

I have 12.19 from the past available so I just use that, but anything less than 14 should reproduce the issue.
```
$ nvm use 12.19.0
$ mkdir test-folder
$ cd test-folder
$ npm init -y
$ yarn add @polkadot/api
... (Yarn doing its thing)
error @polkadot/api@4.7.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.19.0"
```

**Comment by TarikGul** [comment]
Also as a note, I did notice that the `package.json` files all have the engines fields pointing to node >= 14. In this case would the `.nvmrc` file also have to reflect that? (Asking for myself because I am not sure).

**Comment by gre** [comment]
Hello,

Unfortunately we are stuck by this same problem, we can't easily upgrade @polkadot/* libraries – on our side, switching to Node 14 is not trivial (specifically we have to make it work on many environments, web, node, react-native, electron,.. which we will plan, but it's a lot of QA to do to retest these once we upgrade to Node 14).

So, in context of necessary upgrade to v30 we are looking for a quick solution that would be as less impacting as possible.

@gre from Ledger Live team

**Comment by jacogr** [comment]
Will update the .nvmrc - sorry about that.

**Comment by jacogr** [comment]
@gre For Polkadot/Kusama runtime v30, no need to bump to latest. The API actually supports the next upgrade at least a week before it even gets proposed on-chain. (API tracks the latest Substrate master changes, which Polkadot itself lags)

**Comment by TarikGul** [comment]
Closing this issue due to `.nvmrc` correction. Thanks again!
