### ISSUE TITLE
hexToString doesn't work

### ISSUE THREAD

**Issue by will-yijinin** [polkadot-js/api#3450]
When I retrieve the storageVersion using the `api` instance, `storageVersion.toHex()` returns `0x01`, `storageVersion.toHuman()` return `V2`.
When I retrieve the storageVersion using json-rpc requests, the result is still `0x01`. However, `hexToString` return an empty string.

```
import { hexToString, } from '@polkadot/util';
import rp from 'request-promise';

const storageVersion = await api.query.balances.storageVersion();
console.log(storageVersion.toHex())              // 0x01
console.log(storageVersion.toHuman())         // V2

const moduleName = xxhashAsHex("Balances", 128);
const storageName = xxhashAsHex("StorageVersion", 128);
const combined = moduleName + storageName.slice(2);

const resultStr = await rp({
    url: `${config.DOT.HTTP_RPC_ENDPOINT}`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({
        jsonrpc: '2.0',
        method: 'state_getStorage',
        params: [combined],
        id: 1
    }),
});

const result = JSON.parse(resultStr).result; 
console.log(result);            // 0x01
const str = hexToString(result);
console.log(str);                 // '' empty string
```

**Comment by jacogr** [comment]
It is an enum, the hex value is correct - enums are 0-indexed.

**Comment by will-yijinin** [comment]
@jacogr How do I retrieve the value `V2` from the json-rpc request then?

**Comment by will-yijinin** [comment]
@jacogr 
Same question but from another angle. I want to retrieve an account's balance info.
```
    const moduleName = xxhashAsHex("System", 128);
    const storageName = xxhashAsHex("Account", 128).slice(2);

    const decodedAccount = decodeAddress(address);
    const abx = u8aToHex(decodedAccount).slice(2)
    const blake2 = blake2AsHex(decodedAccount, 128).slice(2)
    const storageItemKey = blake2 + abx;

    const combined = moduleName + storageName + storageItemKey;

    const resultStr = await rp({
        url: `${config.DOT.HTTP_RPC_ENDPOINT}`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({
            jsonrpc: '2.0',
            method: 'state_getStorage',
            params: [combined],
            id: 1
        }),
    });

    const result = JSON.parse(resultStr)?.result;
    log.cyan(result)
    log.cyan(hexToString(result));
```
The result is `0x440000000200000001000000000000008679201349000000000000000000000000000000000000000000000000000000a28b5458460000000000000000000000a28b5458460000000000000000000000`. And `hexToString` returns some unrecognizable characters. How do I get a human readable or json data?

**Comment by jacogr** [comment]
As above, hexToString will return garbage since it is not a string being passed in. GIGO :)

If you want the data you need to SCALE decode it, `api.createType('AccountInfo', <hex goes here>)`

**Comment by will-yijinin** [comment]
@jacogr 

```
    const api = await createApiInstance();
    const obj = api.createType('AccountInfo', result);
    log.cyan(obj.data.free.toHuman());
```

It prints 51.5396 BWND. It seems to be a wrong number. Do you think the json-rpc process is wrong or the decoding process wrong?

**Comment by jacogr** [comment]
The UI displays the balances correctly for Westend, which means it is a local issue. Ensure you are on the current API version where the AccountInfo type is detected via on-chain queries.
