### ISSUE TITLE
erasStartSessionIndex is different than block session

### ISSUE THREAD

**Issue by manylov** [polkadot-js/api#3460]
```js
const blockHash = '0xebaa2476fcba89b97e9fbdf531f6c17a2633a432915d5d446d2549b545ade109'
const session = await polkadotConnector.query.session.currentIndex.at(blockHash) // 2027
const currentEra = await polkadotConnector.query.staking.currentEra.at(blockHash) // 332
const sessionStart = await polkadotConnector.query.staking.erasStartSessionIndex(332) // 2028 - why not 2027?
```

**Comment by jacogr** [comment]
State is applied at the end of the block after all executions complete. This means it takes effect at the start of the next for the extrinsics executing in the next block.

**Comment by manylov** [comment]
But this is not a block from era or session edge.
More on this,
```js
await polkadotConnector.query.staking.activeEra.at(blockHash) //  is { index: '331', start: '1,619,624,178,000' }
```

**Comment by jacogr** [comment]
So I don't know what the question is not sure where activeEra comes into the picture above. On the API layer, we simply decode what the RPCs provide, it doesn't guess. For detailed "why and when", I would suggest referring to the Rust code, it is generally well documented to as what the different entries indicate and when they get set, e.g for erasStartSessionIndex, see https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L884-L889
