### ISSUE TITLE
need sign and send two-step implement equivalent to api 'signAndSend'

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#3461]
I have a runnable code as bellow:

```
// construct a list of transactions we want to batch
    const txs = [
        api.tx.balances.transfer("5HXU4tiv5zmGyJkmV1gykoYNVC4X7dFK455J2vAcr9Rfkju9", 11),  
        api.tx.system.remark("0xffeeddccbbaa0001020304"),
    ];

// construct the batch and send the transactions
    const payload = await api.tx.utility.batch(txs);
    const txHash = await payload.signAndSend(pair);
```

But my business requirement is to split `signAndSend` into two steps: 
1) sign and save signed result
2) do some other staff, then send signed result created at step-1.

For methods.balances.transfer(), I have made it worked,  but unable to figure out the answer for batch mode transactions

I did some research with no luck.   Can anyone share some example codes or references docs?

**Comment by jacogr** [comment]
There is signAsync and send.

**Comment by code-brewer** [comment]
> There is signAsync and send.

Big thanks, brother~  You save my days.
