### ISSUE TITLE
 api.query.staking.eraElectionStatus is not a function

### ISSUE THREAD

**Issue by Deekor** [polkadot-js/api#3467]
Recently started getting this today. Assuming it had something to do with the new runtime upgrade?

Was api.query.staking.eraElectionStatus removed?

**Comment by jacogr** [comment]
Elections were reworked. The mention method does not seem to be available in the latest Substrate - https://polkadot.js.org/docs/substrate/storage#staking

**Comment by armorsun** [comment]
I am using polkadot:v0.8.29, the query cannot work, too.
Does it have an alternative call can get the election era period?

**Comment by jacogr** [comment]
Look at the Rust code for the source of truth - the elections were reworked recently.
