### ISSUE TITLE
transfer.signAndSend() method doesn't return transaction hash!!!

### ISSUE THREAD

**Issue by gitloverr** [polkadot-js/api#3477]
hi everyone,

I'm trying to send a DOT from account to another like this:

```

        const keyring = new Keyring({ type: 'sr25519' })
        const fromAddr = keyring.addFromUri(privKey)
        const transfer = api.tx.balances.transfer(toAddress, dotAmount)
        const hash = await transfer.signAndSend(fromAddr)

```
 the process is waiting **at the hash object** assignment step ( transfer.signAndSend) , and does not move on to the next step and dosent return any tx result to me. it's just waiting. it was working like this until today, but not anymore... I'm checking the connection to the server, I'm connected. 

My polkadot api-js package version is :

@polkadot/api: ^4.7.2,
@polkadot/keyring: ^6.3.1
Node version: 14.16.1

why is this happening? what should I do?

thank you

**Comment by jacogr** [comment]
Change RPC nodes. Some have been having issues actually processing the pool today (on Polkadot).

As always, best approach is to run your own node for RPCs.

**Comment by gitloverr** [comment]
hi @jacogr , already I'm running my self node. I think this issue associated with health  of network. there is no problem, now. thank you
