### ISSUE TITLE
chain.getBlock justification display byte ordering issue

### ISSUE THREAD

**Issue by adoerr** [polkadot-js/api#3481]
The `justifications` section of the `chain.getBlock` RPC result seems to have a byte ordering issue with the consensus engine id part. Please see the output below (sry for the formatting). It should be `BEEF` instead of `FEEB`.

`
{
  block: {
    header: {
      parentHash: 0xd0b4aa643dfa7669e73d36286b43bae84a800977f5be94fa56adc55e54516929,
      number: 21,
      stateRoot: 0x94d2c21d261048df94c3fa06c573ebc446c80e7e96dc2e9428513ca572774993,
      extrinsicsRoot: 0x94761e114f87978f73f5918fa7de84cd328266e901f4c171f4f3cc1982dce316,
      digest: {
        logs: [
          {
            PreRuntime: [
              aura,
              0xef4b302000000000
            ]
          },
          {
            Consensus: [
              BEEF,
              0x03d7347bbff90c5318e78ac064f87c0cb720114c0a4ca64286d0ae4c7da9eccb99
            ]
          },
          {
            Seal: [
              aura,
              0xf647762789818447451586104ef25564420afcd637860a0d414ff2208e0d9939dbd5ce7a4fb913a2a43812b73fea9d32082c4a75a6e1dc1b73960783e45b7180
            ]
          }
        ]
      }
    },
    extrinsics: [
      {
        isSigned: false,
        method: {
          args: [
            1,620,108,237,000
          ],
          method: set,
          section: timestamp
        }
      }
    ]
  },
  justifications: [
    [
      FEEB,
      0xd7347bbff90c5318e78ac064f87c0cb720114c0a4ca64286d0ae4c7da9eccb991500000000000000000000000401ca632c4208d05886d63aba32d15c37af179b2a41a5840f5c3cbaa0162fe0401e2157b6054bf13c6f3c7b17ec88a576170932cff8138dce4dbabe2190c581a53c00
    ]
  ]
}
`

Please note that for the `Consensus` section the value is shown correctly as `BEEF`.

**Comment by adoerr** [comment]
Not yet. This was a local test node for the related BEEFY PR [Append SignedCommitment to block justifications](https://github.com/paritytech/grandpa-bridge-gadget/pull/177)

**Comment by jacogr** [comment]
Have a PR that maps closer to the Rust side in https://github.com/polkadot-js/api/pull/3482 (it may do the trick - will pull it into the UI when merged)
