### ISSUE TITLE
Historic `chain_getHeader` call returns latest `Registry`

### ISSUE THREAD

**Issue by emostov** [polkadot-js/api#3487]
From what I can tell `api.rpc.chain.getBlock` returns a type with a `Registry` that has type defs dated to the runtime that the block belongs to. However `api.rpc.chain.getHeader` returns a type with a `Registry` that seems to be dated to the the latest runtime.

```javascript
import { ApiPromise, WsProvider } from '@polkadot/api';

// Encoded AccountInfo (taken from tracing data at Kusama block #4403377)
const accountInfoRead = '0x010500000000000000c03c2b68430c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'

async function main() {
	const provider = new WsProvider('wss://polkadot.api.onfinality.io/public-ws');
	const api = await ApiPromise.create({ provider });

	const blockHash4403377 = await api.rpc.chain.getBlockHash(4403377);

	const block4403377 = await api.rpc.chain.getBlock(blockHash4403377);
	const blockRegistryAccountInfo = block4403377.registry.createType('AccountInfo', accountInfoRead);

	const header403377 = await api.rpc.chain.getHeader(blockHash4403377);
	const headerRegistryAccountInfo = header403377.registry.createType('AccountInfo', accountInfoRead);

	// Below I try to demonstrate that the Registries of the returned objects are not equivalent.
	// I think the type registry on the block is the correctly dated, but it looks like the header
	// just uses the latest registry.

	console.log(
		// The same account info created with the different registries are not equal (at least when converted to a string).
		'Both registries create the same struct: ',
		headerRegistryAccountInfo.toString() === blockRegistryAccountInfo.toString()
	);

	console.log('AccountInfo created with state_getBlock registry', blockRegistryAccountInfo.toString())

	// The type created with Header includes the new `sufficients` field and assigns the `free`
	// `balance` to that field
	console.log('AccountInfo created with the state_getHeader registry', headerRegistryAccountInfo.toString());
}

main().catch(console.error).finally(() => process.exit());

**Comment by jacogr** [comment]
Indeed. It is a catch-22. To know which registry to use you first need the parentHash/blockNumber to do the lookup of existing registry and decoration of the new registry with types.

**Comment by emostov** [comment]
Gotchya, thanks for the explanation!

**Comment by dvdplm** [comment]
@jacogr Are you saying this is a gotcha that can't be fixed?

**Comment by jacogr** [comment]
Nothing is ever unfixable, I'm detailing the reality here of the implementation.

As it is implemented it will end up in an infinite loop since it will try and detect the metadata for that hash, which means getting the header to determine where it is, then seeing it needs metadata for that point, retrieving the header, then seeing it needs metadata, ... etc. So header is the 1 call where metadata is not decorated since the call itself is a critical part of the "determine which process".

PRs always welcome if there are ideas as to how to improve it.

**Comment by dvdplm** [comment]
> As it is implemented it will end up in an infinite loop since it will try and detect the metadata for that hash

Got it now, ty for explaining. A tricky one for sure.
