### ISSUE TITLE
api.rpc.chain.getBlock raise exception: Cannot construct unknown type ParachainsInherentData

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#3500]
I want to scan the chain, so try a simple function to get block data, but got error:

> Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding parasInherent.enter:: Struct: failed on args: :: Cannot construct unknown type ParachainsInherentData

The test code here: 

```
const { Keyring, ApiPromise, WsProvider } = require('@polkadot/api');

async function main(BLK_HASH) {
    const wsProvider = new WsProvider('wss://westend-rpc.polkadot.io');
    const api = await ApiPromise.create({ provider: wsProvider });

    try {
        const block = await api.rpc.chain.getBlock(BLK_HASH);
    }catch (e) {
        console.log("catch error : ", e);
    }
}

const BLK_HASH = "0x9708a71f83de53df2c1ecd180f733a1b235de3a9dccc43e6e35bfdf2dc953396";

main(BLK_HASH).then(() => {
    console.log('over');
    // process.exit();
})
```

Block on scan is at:
https://westend.subscan.io/block/0x9708a71f83de53df2c1ecd180f733a1b235de3a9dccc43e6e35bfdf2dc953396

I believe this error has relation to 5496195-1  extrinsic inside this block. 
https://westend.subscan.io/extrinsic/5496195-1

How to solve this error?  
Or, is it possible to get block data but exclude Parasinherent type extrinsics?

**Comment by jacogr** [comment]
Which version of the API?  Upgrade to latest which has support for all the parachain types.

**Comment by code-brewer** [comment]
> Which version of the API? Upgrade to latest which has support for all the parachain types.

Thanks, I will try.

It is the 4.4.1 version. 

Part of node_modules/@polkadot/api/package.json is: 

>   "name": "@polkadot/api",
  "version": "4.4.1",
  "type": "module",
  "description": "Promise and RxJS wrappers around the Polkadot JS RPC",
  "main": "index.js",
     ...

**Comment by code-brewer** [comment]
> > Which version of the API? Upgrade to latest which has support for all the parachain types.
> 
> Thanks, I will try.
> 
> It is the 4.4.1 version.
> 
> Part of node_modules/@polkadot/api/package.json is:
> 
> > "name": "@polkadot/api",
> > "version": "4.4.1",
> > "type": "module",
> > "description": "Promise and RxJS wrappers around the Polkadot JS RPC",
> > "main": "index.js",
> > ...

**Comment by code-brewer** [comment]
> Which version of the API? Upgrade to latest which has support for all the parachain types.

After upgrade to version 4.9.2.  It works! 

Thanks again.
