### ISSUE TITLE
Wrong return type of contract.query Result for ContractRx

### ISSUE THREAD

**Issue by achimcc** [polkadot-js/api#3501]
Hi,

I'm doing contract calls using `ContractRx` within a redux observable middleware:

https://github.com/achimcc/polka-rxjs/blob/main/src/epics/callRpc.ts

Here, when I define `call` as:

``` const call = contract.query[method](adds, { gasLimit: gas }); ```

with 

``` const contract = new ContractRx(api, abi, address); ```

Then `call` is of type `Observable<Observable<ContractCallOutcome>>` but I think it should be of type `Observable<ContractCallOutcome>`. I have to do an explicit type conversion with: 

```(response as unknown) as ContractCallOutcome``` 

to get something meaningful from the emitted responses.

**Comment by jacogr** [comment]
Closed in #3506
