### ISSUE TITLE
Extrinsic query

### ISSUE THREAD

**Issue by sondotpin** [polkadot-js/api#3505]
Hi, @jacogr , is there a way to determine all events of an extrinsic?

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by sondotpin** [comment]
0x22724f40c8a2586131cc9c518ac847c6c7fb4539d92933cbdaaa72f5681fbbdb
Example: how to detech all events of extrinsic hash above
I mean with a specific extrinsic, not at last signedBlock.

**Comment by jacogr** [comment]
There is no RPC to retrieve extrinsic by hash - extrinsic hashes are not unique in Substrate. (The Polkadot wiki has a full description around the "why")

**Comment by sondotpin** [comment]
https://polkadot.subscan.io/extrinsic/0x22724f40c8a2586131cc9c518ac847c6c7fb4539d92933cbdaaa72f5681fbbdb

I see that subscan they can find by extrinsic hash...

**Comment by jacogr** [comment]
Yes, their harvester indexes the blocks as they come in and then they write this out to their own database which then is queries.
