### ISSUE TITLE
ExtrinsicV4 signature Error

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3518]
Hey, @jacogr 

I am catching the following error, when trying to re-create the Submittable from hexedTx (created by Wallet Core).
the error: `createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 51, in Id, Index, Raw, Address32, Address20`

I tried to set `{ Address: 'AccountId', LookupSource: 'AccountId' }` as types to ApiPromise, but due to I am initializing api not in async function, it returns me the error above. 

How can I set these types? 
Initializing looks like:  `const api = new ApiPromise({ provider });` (not in async function)

**Comment by jacogr** [comment]
You need to pass the types to your constructor. They are registered in the construction phase, not async-only.

**Comment by MrRakhim** [comment]
`const api = new ApiPromise({provider, types: { Address: 'AccountId', LookupSource: 'AccountId' } })`
tried like that and got same error when provider was WebSocket

With Http provider everything is ok)

**Comment by MrRakhim** [comment]
can I inject these types after initializing the api? 

Because catching the following error when working with simple substrate methods

**Comment by MrRakhim** [comment]
Everything I want is to decode transaction hash created and signed by WalletCore(for mobile), also create transactions (for web). How shall I initialize the api?

**Comment by MrRakhim** [comment]
Solution: it is not recommended to decode the Tx, which generated on WalletCore. Eventually it’s sent by jsonrpc author_submitExtrinsic on backend
