### ISSUE TITLE
Question: api won't fail on bad transaction

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/api#3524]
[Observe the following gist](https://gist.github.com/vikiival/4a656122b51480569dd5fe1a1682f5bd)

My question is: since when has `@polkadot/api` this behaviour ?

**Comment by jacogr** [comment]
Transactions from the chain has never thrown - errors are always raised as part of the DispatchError event. Since day 1.

**Comment by vikiival** [comment]
06.02.2021

![photo_2021-05-13 15 36 20](https://user-images.githubusercontent.com/22471030/118133460-28f45400-b401-11eb-8145-50cb98912cab.jpeg)

**Comment by jacogr** [comment]
The above is from the txpool, as I mentioned. The transaction is not executed.

**Comment by vikiival** [comment]
Closing as invalid then.
