### ISSUE TITLE
You need to pass a valid Metadata instance to Decorated

### ISSUE THREAD

**Issue by smupyknight** [polkadot-js/api#3534]
I have this issue while running jest.
Everything worked fine when I've used version ^3.3.2 but not working after I've upgraded to the latest version ^4.9.2

There are similar issues reported already.

https://github.com/polkadot-js/api/issues/3053
https://github.com/polkadot-js/api/issues/2885

But looks like it's not my case. I have exactly version 4.9.2 for @polkadot/api, @polkadot/metadata, @polkadot/types.

This error is actually happening in @polkadot/metadata/decorate/index.js file
`assert(metadata instanceof Metadata, 'You need to pass a valid Metadata instance to Decorated');`
`metadata instance of Metadata` is returning false.

But when I log `metadata` and `Metadata`, 

`metadata` is 

```
Metadata(2) [Map] {
  'magicNumber' => MagicNumber {
    negative: 0,
    words: [ 24405357, 24 ],
    length: 2,
    red: null,
    registry: TypeRegistry { createdAtHash: undefined },
    createdAtHash: undefined
  },
  'metadata' => Type {
    registry: TypeRegistry { createdAtHash: undefined },
    createdAtHash: undefined,
    isV0: [Getter],
    asV0: [Getter],
    isV1: [Getter],
    asV1: [Getter],
    isV2: [Getter],
    asV2: [Getter],
    isV3: [Getter],
    asV3: [Getter],
    isV4: [Getter],
    asV4: [Getter],
    isV5: [Getter],
    asV5: [Getter],
    isV6: [Getter],
    asV6: [Getter],
    isV7: [Getter],
    asV7: [Getter],
    isV8: [Getter],
    asV8: [Getter],
    isV9: [Getter],
    asV9: [Getter],
    isV10: [Getter],
    asV10: [Getter],
    isV11: [Getter],
    asV11: [Getter],
    isV12: [Getter],
    asV12: [Getter],
    isV13: [Getter],
    asV13: [Getter]
  },
  registry: TypeRegistry { createdAtHash: undefined },
  createdAtHash: undefined
}
```

and `Metadata` is 
```
[class Metadata extends MetadataVersioned]
```

So I am sure that metadata is instance of Metadata.
I guess something became wrong while transpiling the code.
Jest does not support es6 so I could not run unit tests without transpiling.

When I've confirmed on a fresh project with following code it worked fine without any issue.

```
const { ApiPromise, WsProvider } = require('@polkadot/api');
const wsProvider = new WsProvider('ws://127.0.0.1:9944', false);

wsProvider.on('connected', ...);
wsProvider.connect();
```

Anyone has ideas?

**Comment by jacogr** [comment]
Ensure you only have one instance of `@polkadot/metadata`. Generally this would happen if -

- there are multiple versions around (instanceof 4.1 !== instanceof 4.9)
- cjs and esm gets mised (once again instanceof cjs != instanceof esm)

**Comment by smupyknight** [comment]
@jacogr I get this when I run `npm list @polkadot/metadata`

![image](https://user-images.githubusercontent.com/21160912/118361060-f5910100-b589-11eb-85e5-ad4b4b2b679c.png)

So I guess I only have one instance?

**Comment by smupyknight** [comment]
This issue was due to duplicate instances as @jacogr mentioned.
One was cjs and one was transpiled esm.
