### ISSUE TITLE
[ BUG ] resubscribe when ws is connected & onSocketOpen is accessible but onSocketMessage is broken

### ISSUE THREAD

**Issue by xsteadybcgo** [polkadot-js/api#3538]
Application structure
```
// Accessible
polkadotjs/api client  -----ws----> my service 1 ----ws----> my endpoint proxy 2 ----ws----> polkadot endpoint

// Exception
polkadotjs/api client  -----ws----> my service 1 ----ws----> my endpoint proxy 2 ----❌ （broken）----> polkadot endpoint
```
When **my endpoint proxy 2** is broken, it will notify **my service 1** to close the client ws connection and **my service 1** is still accessible.

Thus, the **polkadotjs/api** client will trigger the `#onSocketClose`, right ?
The calling pipeline is `onSocketClose` -> `connectWithRetry` -> `connect` -> `onSocketOpen` -> `resubscribe`,  look at [this line](https://github.com/polkadot-js/api/blob/526a3fd1391df165b5f7cc7fdd30792c6362a860/packages/rpc-provider/src/ws/index.ts#L467), setting `this.#subscriptions = {}`. let's go on, `subscribe` -> `send` messeges to  **my service 1**

Now  **my service 1**  receive messeges again and  pass to **my endpoint proxy 2** still being broken. Then **my service 1** will be notified to close ws connection with **polkadotjs/api client** again . 

Again, The third time `connectWithRetry` start,  but this time `resubscribe` will subscribe nothing because of  `this.#subscriptions` has been set as `{}`, after a long time **my endpoint proxy 2** is accessible, but polkadot/api client will get nothing about `subscribeNewHead` , etc unless I refresh my polkadotjs/api client (polkadotjs/app client)

**Comment by atenjin** [comment]
Hi jacob, we think it should be a bug, maybe need to fix it.

**Comment by jacogr** [comment]
The API cannot cater for specific proxy connections. It expects that the destination is actually acting correctly. In this case you have an issue with your proxy -> destination setup.

**Comment by xsteadybcgo** [comment]
> The API cannot cater for specific proxy connections. It expects that the destination is actually acting correctly. In this case you have an issue with your proxy -> destination setup, the proxy should not maintain connections that is not there.

There doesn't seem to be a connection maintained here.  Maybe it's a problem with my current service design, we use microservice architecture, `service 1` is used for traffic control of different accounts, `service 2` forwards requests from `service 1` to different chains to invoke rpc requests, whichever service is disconnected, the clients connected to it will eventually be notified of the disconnection. For some reason when `Service 2` has problems disconnecting for a while (but during this time `Service 1` is normal, so the client does not receive subscription data and is notified of the disconnected ws connection and keeps trying to reconnect) and restarts normally again, there will be a situation where @polkadot/apps can't subscribe to data after reconnecting Service 1 successfully, unless the user refreshes the browser. I think the reason is that `this.#subscriptions` above has been permanently set to empty object, do you have any suggestions to solve this situation? @jacogr

**Comment by xsteadybcgo** [comment]
In the above exception case, the connection is normal for the API (service 1 is always normal), but the subscription is not normal (service 2 is abnormal)
