### ISSUE TITLE
Unable to decode storage system.account: entry 0:: createType(AccountInfo)

### ISSUE THREAD

**Issue by JosephDenman** [polkadot-js/api#3553]
I'm attempting to connect to the SORA blockchain. I have passed their custom types to `ApiPromise`. After adding my key to the keyring via JSON, unlocking the key, and running either of the following

```
const transfer = api.tx.balances.transfer(ALICE.address, 1);
await transfer.signAndSend(BOB);
```

```
const account = await api.query.system.account(BOB.address);
```

I get back

```
Uncaught Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x63000000000000002a0000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (76 bytes), created 0x63000000000000002a0000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
```

It looks like there's a mismatch in the expected form of the `AccountInfo` type, possibly due to versioning.

**Comment by jacogr** [comment]
It is for your specific chain -

- either update to the latest Substrate (recommended) with the most recent AccountInfo structures
- apply the correct API overrides to suoport the older versions

**Comment by mckrava** [comment]
I have the same issue but with `AccountData`. And it's started after latest API updates :(

**Comment by tash-2s** [comment]
I had the same issue for the `AcountInfo` but solved it. If your chain is substrate v3.0.0, `AccountInfo: "AccountInfoWithDualRefCount"` is the correct setting.
