### ISSUE TITLE
Maximum message size exceeded on recent staking query

### ISSUE THREAD

**Issue by jhonalino** [polkadot-js/api#3561]
`Maximum message size exceeded on recent staking query`

I got the issue specifically for the 356th era which is today. did something happen on polkadot? cause its fine on kusama

`   const exposures = await api.query.staking.erasStakers.entries(356)`

**Comment by jacogr** [comment]
Comes from here - https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketConnection.js#L579

The default is 8MB according to https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md#client-config-options, so it means that message is over that.

There was something weird today, a large number of nodes started falling behind (after the staking election) for around 30 minutes.

Will bump it to 16MB with an explicit option... feels like something that will occur again

**Comment by jhonalino** [comment]
thank you for the fix @jacogr ! I see that you've bump it client side I would have thought this would be a substrate fix. so the memory is entirely client side? and they don't need to change anything on the server side?

**Comment by jacogr** [comment]
The API controls the amount of data it wants to retrieve. 

So for entries it asks for 256 (was 384, see the second linked PR) keys at a time. Depending on what those are, the messages can get, well, large like in this case. A massive amount of nominations on a specific staker would bloat that entry.
