### ISSUE TITLE
tx transaction 0.0000000001

### ISSUE THREAD

**Issue by rudolfp1979** [polkadot-js/api#3567]
when i push a transaction with the api and set value to 1.0 there is only 0.0000000001 dot transferred is there a way to transfer full dots beside multiplying with 10^10

**Comment by jacogr** [comment]
The API interfaces, like the runtime, only deal with `u128` values. In reality a Balance type is always denoted in the smallest unit, on-chain and in the API.

The fact that there is decimals is purely a UI and interface display issue to make it human-friendly, based on the properties as set in the chainspec. (As retrieved via the `api.rpc.system.properties` RPC.)

**Comment by rudolfp1979** [comment]
so is there a way to tell the api that it should convert it to u128.

`const transfer = api.tx.balances.transfer(BOB, 1.0);`

this should send one full dot not one of the smallest unit. Atm it am solving it by multiplying.

**Comment by jacogr** [comment]
The API converts. So when you pass in `1 * 1e9` is creates a `Balance` type from that. And yes, any human-like display adjustments are to be done by you.

**Comment by rudolfp1979** [comment]
my problem is that I have to pass in 1*1e9 to the api to get exactly 1Dot transferred not what it displays. I tested it and it transferred 1nanoDot without 1*1e9. So if I have to tell the api that it should multiply it, it is no problem. Just wanted to know. As I have seen [on](https://polkadot.js.org/apps/#/extrinsics)  there was an option to choose Dot, milliDot, PicoDot ... So I think there is than the value to send multiplied also by the option choosen.

**Comment by MrRakhim** [comment]
It is called multiplier, it is necessary to multiply the value to 1e9. For arithmetic operations with such big numbers you can use libraries like BigNumber and etc
