### ISSUE TITLE
Priority is too low Pt. II

### ISSUE THREAD

**Issue by JosephDenman** [polkadot-js/api#3569]
I'm attempting to submit a sequence of transactions as fast as possible. Without writing a function to sleep for the target block time (approximately 8 seconds), I run into this error:

```
submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (13904595768251726000 vs 13904595768251726000)
```

I tried to manually increment the nonce and send transactions, but the error persists. I know this is a duplicate of https://github.com/paritytech/substrate/issues/2312, but it suggests that the only solution is sleeping. Is that correct? What is the best way to allow for more than one transaction to make it into a block?

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce

Incrementing it in the loop is generally what people seem to use, aka that I know was the approach used for stress-testing up to 4k+ txs/s

**Comment by JosephDenman** [comment]
Awesome! Thanks.
