### ISSUE TITLE
How to reproduce empty call in api

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3570]
So I have a pallet state method that takes an optional parameter (Option in rust), so when I use the apps interface, I can untoggle the option and obtain the desired result.
How do I do the same thing with the api directly? I tried passing no parameter or passing null parameter and both return errors.
Thanks in advance for your help

**Comment by jacogr** [comment]
Do you have the call signature for this map?

**Comment by jacogr** [comment]
After https://github.com/polkadot-js/api/pull/3578 which cleans up the checks for better messaging in the case of maps, you should be able to just pass `null` through for `Option`. (Obviously the `api.createType('Option<MyType>')` as an arg would pass the default/node value as well, irrespective of version)

**Comment by jacogr** [comment]
Closing. Current api version can pass `null` through after some storage check relaxation.
