### ISSUE TITLE
How to write additional field values to identity

### ISSUE THREAD

**Issue by abzen** [polkadot-js/api#3572]
I'm trying to update identity with a few additional fields that store ipfs cids but can't seem to do it? I get runtime error whenever I try to write a long enough string in there.
![Screenshot 2021-05-26 at 21 26 14](https://user-images.githubusercontent.com/7943522/119726428-0171a280-be69-11eb-81fb-f1aaa5a11d38.png)

Checked Polkadot wiki and developer extrinsic ui that say that you need to encode it to hex (0x....) and used stringToHex util but still can't get it to work.

i'm trying something like this

```
  polkadotApi.tx.identity
        .setIdentity({
          display: { Raw: data.userName },
          legal: { Raw: data.legal },
          email: { Raw: data.email },
          twitter: { Raw: data.twitter },
          riot: { Raw: data.riot },
          web: { Raw: data.web },
          additional: [
            [
              { Raw: 'custom' },
              {
                Raw: stringToHex('bafkreidpmfk6uqalrjbf73jjptbvj47wkxv3l6mq25m5ijtfabj2hf7a2e'),
              },
            ],
          ],
        })
```

**Comment by jacogr** [comment]
`stringToHex` is not be needed. Passing hex or string in there has the same path for the API to convert (i.e. it will detect hex and convert to bytes or convert the raw string to bytes)

The parameter passed looks correct. In this case however, I believe you are running into this -

```rust
impl Encode for Data {
	fn encode(&self) -> Vec<u8> {
		match self {
			Data::None => vec![0u8; 1],
			Data::Raw(ref x) => {
				let l = x.len().min(32);
				let mut r = vec![l as u8 + 1; l + 1];
				&mut r[1..].copy_from_slice(&x[..l as usize]);
				r
			}
			Data::BlakeTwo256(ref h) => once(34u8).chain(h.iter().cloned()).collect(),
			Data::Sha256(ref h) => once(35u8).chain(h.iter().cloned()).collect(),
			Data::Keccak256(ref h) => once(36u8).chain(h.iter().cloned()).collect(),
			Data::ShaThree256(ref h) => once(37u8).chain(h.iter().cloned()).collect(),
		}
	}
}
```

It expects a max of 32 bytes on the Rust side. 

This seems to be a misalignment on the JS API types side, it should not try and encode anything > 32 bytes for this field, i.e. needs to bail on construction.

**Comment by jacogr** [comment]
For pushing hashes to identity - use one of the hash types with the raw 32 bytes of the hash (non-encoded).

**Comment by abzen** [comment]
ah, 32 byte limit is a bit of a bummer. 
Thanks for the explanation 👍
