### ISSUE TITLE
Getting error: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received

### ISSUE THREAD

**Issue by sbnair** [polkadot-js/api#3583]
I am getting this error when using polkadot api and these are the versions that i am using : 
"@polkadot/api": "^4.4.1",
    "@polkadot/api-contract": "^3.10.3-8",
    "@polkadot/extension-dapp": "^0.37.1",
    "@polkadot/hw-ledger": "^5.7.2-6",
    "@polkadot/keyring": "^5.7.2-6",
    "@polkadot/networks": "^5.7.2-6",
    "@polkadot/phishing": "^0.5.38",
    "@polkadot/types": "^4.4.1",
    "@polkadot/util": "^6.0.1-9",
    "@polkadot/util-crypto": "^6.0.4",

RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received

If there is a problem in versions please let me know also i am using substrate v3.0 .

**Comment by sbnair** [comment]
I Think i solved it, it was a metadata issue, i updated it in the code and it is not throwing any error now.

**Comment by prasad-kumkar** [comment]
@sbnair im having the same issue, could you please elaborate on exactly how you solved the issue?
