### ISSUE TITLE
When i compile mjs file with polkadot/api i get this error related to wasm-crypto-wasm/bytes.js

### ISSUE THREAD

**Issue by sbnair** [polkadot-js/api#3586]
Here is the api version i am using : "@polkadot/api": "^4.4.1",
                "@polkadot/util": "^6.0.1-9",
                "@polkadot/util-crypto": "^6.0.4",

Please let me know what to do ?

node_modules/@polkadot/wasm-crypto-wasm/bytes.js:3
 import { bytes as _bytes, sizeCompressed as _sizeCompressed, sizeUncompressed as _sizeUncompressed } from "./cjs/bytes.js";
          ^^^^^
SyntaxError: The requested module './cjs/bytes.js' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from './cjs/bytes.js';
const { bytes as _bytes, sizeCompressed as _sizeCompressed, sizeUncompressed as _sizeUncompressed } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)

Thanks,
Shailesh Nair.

**Comment by jacogr** [comment]
You don't want to mix versions of util & util-crypto. I would suggest sticking to the same version as your older version of the API requires.
