### ISSUE TITLE
Unable to decode storage tokens.accounts: entry 0:: createType(AccountData)

### ISSUE THREAD

**Issue by exeamos** [polkadot-js/api#3587]
![image](https://user-images.githubusercontent.com/24546717/120089762-dec4df80-c12f-11eb-960c-06c3d3a4aca5.png)

how to solve this problem?

**Comment by jacogr** [comment]
Add the correct AccountInfo type for the chain. The API defaults to what is on Substrate master (incl. Kusama/Polkadot). If you are using an older chain, adjust the type.

Here are the various iterations - https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/system/definitions.ts#L142-L162

That looks like a `AcountInfo: 'AccountInfoWithDualRefCount'` type needs to be injected into the API, obviously it depends on the chain runtime configuration

**Comment by prasad-kumkar** [comment]
I'm having same issue. I tried this, 
`const { AccountInfo } = require('@polkadot/types/interfaces/system')
const provider = new WsProvider('ws://127.0.0.1:9944')
    const api = await ApiPromise.create({ provider, types: {
      AccountInfo: AccountInfo
    }});

    const unsub = await api.tx.templateModule
    .createIdentity(did)
    .signAndSend(state.selectedAccount
`
and got
`DRR: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: Cannot construct unknown type AccountInfo`

**Comment by exeamos** [comment]
solved
