### ISSUE TITLE
(0 , _xRandomvalues.default) is not a function

### ISSUE THREAD

**Issue by elegant651** [polkadot-js/api#3591]
when I try to deploying with `flipper` contract,
```
const code = new CodePromise(api?.value, abiData, wasm.value);
code.tx['new'](
          {
            gasLimit: formData.weight,
            value: formData.endowment,
          },
          false
        );
```

I got error as
`(0 , _xRandomvalues.default) is not a function` .

maybe it related with createBlueprintTx function. any idea?

**Comment by jacogr** [comment]
Which version of the API do you have? Also what is your NodeJs version?

**Comment by elegant651** [comment]
@jacogr 
"@polkadot/api": "^4.12.1", "@polkadot/api-contract": "^4.12.1",

regarding nodeJs version, `v14.8.0`

fyi, here's my code for deploying contract. https://github.com/PlasmNetwork/plasm-apps-vue/blob/feature/dapps-page/src/components/dapps/ModalCreateDapps.vue#L518

**Comment by jacogr** [comment]
Do you have `@polkadot/util-crypto` specified locally? (The reason asking is that the current versions don't try and do a default import for randomValues at all)

**Comment by elegant651** [comment]
oh I didn't import that file, but after import it, it works as a charm. Thanks :)
