### ISSUE TITLE
How can I watch events after send signed transaction?

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#3596]
**What I expect is to get events and status like bellowing for a signed transaction:**

Expect a 'SendAPI' API that can provide  callback function  with 'status' and 'events' parameters: 

` SendAPI(signedTx,  {status, events) => { } `

//  That is what signAndSend API  callback do:   
` api.tx.balances.transfer(BOB, 12345).signAndSend(signer, ({status, events}) => { ... } )  `

Please help~   

` `

Currently, I have bellowing runnable approach, but wonder if there is a more  informational callback

**My first runnable approach:** 

Having signed transaction, for the first approach, I can submit use bellowing method:

```
async function submitTx(signedTx) {
    const actualTxHash = await rpcToNode('author_submitExtrinsic', [signedTx]);
    console.log(`Actual Tx Hash: ${actualTxHash}`);
}

 
function rpcToNode(method, params) {
    return fetch('https://westend-rpc.polkadot.io', {
        body: JSON.stringify({
            id: 1,
            jsonrpc: '2.0',
            method,
            params,
        }),
        headers: {
            'Content-Type': 'application/json',
        },
        method: 'POST',
    })
        .then((response) => response.json())
        .then(({ error, result }) => {
            if (error) {
                throw new Error(
                    `${error.code} ${error.message}: ${JSON.stringify(error.data)}`
                );
            }
            return result;
        });
}
```

**My second runnable approach:**

```
async function submitAndWatch(api, signedTx) {

    const extrinsic = api.createType('Extrinsic', signedTx);

    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    api.rpc.author.submitAndWatchExtrinsic(extrinsic, (result) => {
        console.log("====submitAndWatchExtrinsic result toHuman ==== : ");
        console.log(JSON.stringify(result.toHuman(), null, 2));
        console.log("====submitAndWatchExtrinsic result raw ==== : ");
        console.log(result);

        if (result.isInBlock || result.isFinalized) {
            process.exit(0);
        }
    });
}
```

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event

The signAndSend exposes the `events` as well as `dispatchError`/`dispatchSuccess`

**Comment by code-brewer** [comment]
> https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event

Thanks for reply.

But from the link resource, there is no such method `api.tx(...hex data or call...)` that accept  hex string type signed data.


Now the signed transaction data is hex string type data that read from DB, so can not call signAndSend() on it. 
From my understanding, to call signAndSend(),  we need to re-construct a submittable object from hex string type signed data, which is what I look for.

**Comment by jacogr** [comment]
api.tx(...data)` does exactly that, it re-constructs.

**Comment by code-brewer** [comment]
> `api.tx(...data or call)` does exactly that, it re-constructs.

I have tried  bellowing reConstructTxAndSend() but got error. 

I can make sure it run well if alternatively call the submitTx()/submitAndWatch() function mention in previous post.

```
async function reConstructTxAndSend(api, signedTx) {    
    console.log('signedTx: ' + signedTx);

    const submittable = await api.tx(...signedTx)   // ***** ERROR HERE *****

    await submittable.send(({status,events}) => {

        if (status.isInBlock) {
            console.log(`included in ${status.asInBlock}`);    
        }else if (status.isFinalized) {
            console.log('Finalized block hash', status.asFinalized.toHex());
        }

    })
}
```


> signedTx: 0x5902840071039d744e73612693cc21812a6c03513d0014faba057aaa0cac7a775d0461150250aff0f04333098ba280ae6a69432a383b4cca679b0f7d412267895d39ac40ad0b8d4198fe3691c27c88c7b7fdf709353755d6a0a6ee3d58d03a48235e7f3da800b5038d02001000080400008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a481800010c307861
Error: createType(ExtrinsicV4):: Struct: failed on signature: {"signer":"Address","signature":"ExtrinsicSignature","era":"ExtrinsicEra","nonce":"Compact<Index>","tip":"Compact<Balance>"}:: Cannot decode value "0" (typeof string), expected an input object with known keys
    at createTypeUnsafe (/tmp/polka_test/node_modules/@polkadot/types/create/createType.cjs:58:11)
    at createType (/tmp/polka_test/node_modules/@polkadot/types/create/createType.cjs:70:10)
    at TypeRegistry.createType (/tmp/polka_test/node_modules/@polkadot/types/create/registry.cjs:308:39)
    at Function._newFromValue (/tmp/polka_test/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:202:21)
    at Function._decodeExtrinsic (/tmp/polka_test/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:219:29)
    at new GenericExtrinsic (/tmp/polka_test/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:188:38)
    at new Type (/tmp/polka_test/node_modules/@polkadot/types/create/registry.cjs:351:16)
    at new Submittable (/tmp/polka_test/node_modules/@polkadot/api/submittable/createClass.cjs:66:7)
    at ApiPromise._extrinsics (/tmp/polka_test/node_modules/@polkadot/api/submittable/createSubmittable.cjs:18:23)
    at submitAndWatch (/tmp/polka_test/utils/polka/test/txUtils.batchTx.author_txFromSigned_send.js:59:35)
Process finished with exit code 0



My polkadot api version is:

>   "name": "@polkadot/api",
  "version": "4.9.2",

**Comment by jacogr** [comment]
`const submittable = await api.tx(...signedTx)`

Don't expand -

- if hex, pass the hex ()generated from `signedTx.toHex()`)
- if extrinsic or Call object, pass as-is

**Comment by code-brewer** [comment]
> `const submittable = await api.tx(...signedTx)`
> 
> Don't expand -
> 
> * if hex, pass the hex (generated from `signedTx.toHex()`)
> * if extrinsic or Call object, pass as-is (no `...`)

Yes, signedTx var is a hex string.
Now it work without expanding:  const submittable = await api.tx(signedTx)

Amazing~  Hard to found this usage from the document.

So kind of you, thanks.
