### ISSUE TITLE
Cannot broadcast transaction in KSM network

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3598]
Hi. When broadcasting transactions on the Kusama network(9030), it **sometimes** stops though node is running well. 

short code:
```typescript
async signRawTransaction(txParams: any): Promise<any> {
  this.logger.debug("Raw Transaction:", txParams.transfer.toString());

  const signedTx = await txParams.transfer.signAsync(this.wallet[txParams.from])

  await txParams.transfer.send();
  this.logger.debug('Signed Transaction:', signedTx.toString())

  return signedTx

}
```

In the short code, when it stops broadcasting transaction, the debug log message is not printed from "Signed Transaction: ~~". 
I found the release v4.12.1 (https://github.com/polkadot-js/api/releases) it is included changes "Added 9030 upgrade blocks for Kusama & Westend" 

Will this error disappear if I upgrade polkadot-js to v4.12.1? Please let me know if you find the reason other than using the latest polkadot-js SDK.

**Comment by jacogr** [comment]
If it is today, check the tx pool. A number of nodes, based on the number of txs flowing, have been loaded and got to points where they stopped accepting txs.

**Comment by boohyung** [comment]
Thanks. There are several questions.

1. When the tx stop transfer? 
2. How do I check the tx pool status? 
3. Will this error disappear if I query the nonce using `rpc.system.accountNextIndex`? (https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce)

**Comment by boohyung** [comment]
+ When broadcasting tx, we found that an RPC(curl) error occurred while connecting SDK and KSM nodes.
`errno: 52, data: Empty reply from server`

**Comment by jacogr** [comment]
No, there has been multiple reports where RPC servers just stopped accepting any new transactions. You can always monitor the queues on telemetry. As of this morning, it actually seems like the spam has stopped.

**Comment by Swader** [comment]
This was due to the RMRK.app NFT emote contest. It is over now and shouldn't happen again any time soon, plus this should fix it: https://github.com/paritytech/substrate/pull/8963

**Comment by boohyung** [comment]
Thanks. I can check best block, finalized block, avg time, block time, and status of validators on the telemetry in real time (https://telemetry.polkadot.io/#list/Kusama)
@jacogr 
1. Is there any way to monitor tx pool status?

@Swader 
1. When did RMRK.app NFT emote contest start and when did it finish?
2. paritytech/substrate#8963 will be merged next polkadot-js release. it it right?

**Comment by Swader** [comment]
> When did RMRK.app NFT emote contest start and when did it finish?

@boohyung it lasted throughout April and May, but it ramped up in the last few days of May due to people discovering scripting. It's calm now.

![image](https://user-images.githubusercontent.com/1430603/120297067-04d1b780-c2c9-11eb-82d5-3bacad6aab6e.png)

**Comment by boohyung** [comment]
Thanks. @jacogr @Swader I look forward to applying it to the next release(polkadot v0.9.4) to improve the stability of txpool.
