### ISSUE TITLE
types error in the same runtime version

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/api#3599]
The problem here almost the same as the  https://github.com/polkadot-js/api/issues/3434 descript. 

This time, my polkadot dependencies is 4.10.1, and the error message as below:

> subquery-node_1   | 2021-05-31T10:09:38.296Z <indexer> ERROR failed to fetch block Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: decodeU8a: failed at 0x250b0c0c10101414… on solution: {"compact":"CompactAssignmentsWith24","score":"ElectionScore","round":"u32"}:: decodeU8a: failed at 0x250b0c0c10101414… on compact: {"votes1":"Vec<(NominatorIndexCompact,ValidatorIndexCompact)>","votes2":"Vec<(NominatorIndexCompact,CompactScoreCompact,ValidatorIndexCompact)>","votes3":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);2],ValidatorIndexCompact)>","votes4":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);3],ValidatorIndexCompact)>","votes5":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);4],ValidatorIndexCompact)>","votes6":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);5],ValidatorIndexCompact)>","votes7":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);6],ValidatorIndexCompact)>","votes8":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);7],ValidatorIndexCompact)>","votes9":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);8],ValidatorIndexCompact)>","votes10":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);9],ValidatorIndexCompact)>","votes11":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);10],ValidatorIndexCompact)>","votes12":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);11],ValidatorIndexCompact)>","votes13":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);12],ValidatorIndexCompact)>","votes14":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);13],ValidatorIndexCompact)>","votes15":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);14],ValidatorIndexCompact)>","votes16":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);15],ValidatorIndexCompact)>","votes17":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);16],ValidatorIndexCompact)>","votes18":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);17],ValidatorIndexCompact)>","votes19":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);18],ValidatorIndexCompact)>","votes20":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);19],ValidatorIndexCompact)>","votes21":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);20],ValidatorIndexCompact)>","votes22":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);21],ValidatorIndexCompact)>","votes23":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);22],ValidatorIndexCompact)>","votes24":"Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);23],ValidatorIndexCompact)>"}:: decodeU8a: failed at 0x86d1700000000000… on votes17: Vec<(NominatorIndexCompact,[(ValidatorIndexCompact,OffchainAccuracyCompact);16],ValidatorIndexCompact)>:: Vec length 1848417 exceeds 65536

![image](https://user-images.githubusercontent.com/20088392/120265747-364f8080-c2d3-11eb-9dfb-abf5ce5aba1e.png)

The runtime version of the blocks that start from 3400000 are all 24, the error occurs during scan and parse the blocks between 3408900 and 3408999.

As @jacogr mentioned in  https://github.com/polkadot-js/api/issues/3434, it is most likely due to the Address type.

Does that mean I need to specify a different Address Type for some blocks between 34089000 and 3408999?

My current types 

```yaml
          - minmax:
              - 23
              - 24
            types:
              Address: MultiAddress
              LookupSource: MultiAddress
              MultiAddress: GenericMultiAddress
              AccountInfo: AccountInfoWithTripleRefCount
              AccountInfoWithTripleRefCount:
                nonce: Index
                consumers: RefCount
                providers: RefCount
                data: AccountData
```

**Comment by jacogr** [comment]
The above is due to Elections - there are 2 types, one with 16 nominators and one with 24. 

https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/staking/definitions.ts#L18-L62

So in this case adding `CompactAssignments: 'CompactAssignmentsWith16'` should solve the issue.

**Comment by sxlwar** [comment]
Thx @jacogr , success fixed by adding config
```yaml
    RawSolution: RawSolutionWith16
    CompactAssignments: CompactAssignmentsWith16
```
