### ISSUE TITLE
Cannot broadcast transaction in DOT network

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3604]
I found the error `“errno: 52, data: Empty from server”` in DOT v0.9.3 node when broadcasting transactions on the DOT network. The network and txpool status is good. Why is the error occured? Please let me know to resolve the problem.

DOT node command to start: 
`./target/release/polkadot --chain=polkadot --pruning=archive --rpc-external --ws-external --rpc-cors=all -l info -d ~/.dot
`

The time found the error: 2021-06-01 13:06 UTC

SDK version we used is:
  ```
"@polkadot/api": "^4.10.1",
  "@polkadot/keyring": "^6.4.1",
  "@polkadot/metadata": "^4.10.1",
  "@polkadot/types": "^4.10.1",
  "@polkadot/util-crypto": "^6.4.1"
```

**Comment by boohyung** [comment]
Any comments or solutions?

**Comment by jacogr** [comment]
That is from the node itself, so would refer to the logs on it. The API can only report what the node reports.
