### ISSUE TITLE
Improve `Option.toHuman`

### ISSUE THREAD

**Issue by awolokita** [polkadot-js/api#3605]
`Option.toHuman` returns `raw.toHuman` which will be either be of the generic type or `null`. This is different to how `Result` works, which uses `Enum.toHuman` which yeilds something like `{Ok: 123}` or `{Err: "Error!"}`.

There may be some reason to this difference that I'm not aware of.

**Comment by jacogr** [comment]
Unlike in the case of Results, an Option is either `null` or has value. The user is just interested (since this is only a `toHuman()` pretty output) in whether there is a value or not. So the suggestion would make it worse - it was explicitly done this way to get rid of unneeded wrapping.

**Comment by awolokita** [comment]
Fair enough. Cavas-UI does some explicit re-wrapping of Option so I thought that it might be an improvement. Thanks for reviewing.
