### ISSUE TITLE
missing types for new election pallet

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/api#3611]
Similar to https://github.com/polkadot-js/api/issues/3265

An example of failing block: 

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/explorer/query/5329310
which is https://polkadot.subscan.io/block/5329310

Looking into what types are missing myself, might be able to help more.

**Comment by kianenigma** [comment]
I was also doing some testing on this branch: https://github.com/paritytech/substrate/pull/8912

This one will add a new variant to `Phase` enum that need to be represented.

**Comment by jacogr** [comment]
Cannot replicate on that block (do you have types injected?) -

![image](https://user-images.githubusercontent.com/1424473/120487629-6d4a9280-c3b6-11eb-9b86-8c3b4871f824.png)

**Comment by kianenigma** [comment]
ahh bugger me, I had some types injected ages ago and they have been faffing with my UI all along. False alarm, closing.
