### ISSUE TITLE
RPC-CORE: submitAndWatch Extrinsic(extrinsic: Extrinsic): Extrinsic Status:: 1011: 

### ISSUE THREAD

**Issue by sbnair** [polkadot-js/api#3614]
Hi

   Getting this error when submitting signed transaction in Polkadot js but when i submit the same using sudo it is working :

RPC-CORE: submitAndWatch Extrinsic(extrinsic: Extrinsic): Extrinsic Status:: 1011: Unknown Transaction Validity: NoUnsigned Validator

**Comment by jacogr** [comment]
Refer to Substrate for the logic. Unsigned transaction each have a specific validator.

https://github.com/paritytech/substrate/blob/25388397aab20a24e2be55103dda95011aa04d7c/primitives/runtime/src/transaction_validity.rs#L120-L121

https://github.com/paritytech/substrate/blob/25388397aab20a24e2be55103dda95011aa04d7c/primitives/runtime/src/transaction_validity.rs#L131-L132

**Comment by sbnair** [comment]
Ok, but i am doing signed transaction not unsigned, so any changes i need to do in runtime logics ?

**Comment by sbnair** [comment]
It is solved by adding changes in the command that runs the node.
