### ISSUE TITLE
I get this error signAndSend: status :: {"dispatchError":{"badOrigin":null},

### ISSUE THREAD

**Issue by sbnair** [polkadot-js/api#3615]
When i try to add using Extrinsics i get this error but when i use sudo it is working fine but accountID is generated differently when added using sudo, can you please let me know what is this error ?

signAndSend: status :: {"dispatchError":{"badOrigin":null},

**Comment by jacogr** [comment]
It is exactly what it says, it is a Bad Origin. Some extrinsics are only applicable for root origins. (sudo, democracy, ...)
