### ISSUE TITLE
Got TypeError when try to use standard derives from @polkadot/api-derive

### ISSUE THREAD

**Issue by Lebed-kun** [polkadot-js/api#3619]
Version of @polkadot/api : 4.10.1

1. I created api with ApiPromise.create using these arguments:

```
ApiPromise.create({
          provider: new WsProvider("wss://rococo-rpc.polkadot.io"),
          types: {
            "FullIdentification": "()",
            "Keys": "SessionKeys7B",
            "BridgedBlockHash": "H256"
          }
});
```

2. My IDE shows that I have api.derive.staking.electedInfo method ;
3. When I try to call this method, I get error:
```
TypeError: api.derive.staking is undefined
```

**Comment by jacogr** [comment]
There is no staking on Rococo. The derives are decorated based on what the node provides.
