### ISSUE TITLE
How to generate right code for the Signer app to sign

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3627]
### What Im trying to do
I want to create a react app that would allow users with mobile wallets to sign transactions for the crowdloan. I need to display the extrinsic as a QR code for the Parity Signer app to sign.

### Code
Here is my code to create the payload (as per https://github.com/polkadot-js/api/issues/1421) : 

```
const remarkExtrinsic = api.tx.system.remark(token);
const payload={
        method: remarkExtrinsic.method.toHex(),
        nonce:u8aToHex(nonce),
        genesisHash: u8aToHex(api.genesisHash),
        blockHash: u8aToHex(api.genesisHash),
        runtimeVersion: api.runtimeVersion,
        version: api.extrinsicVersion,
    }
const wrapper = api.createType(
      "ExtrinsicPayload",
      payload,
      { version: api.extrinsicVersion }
    );
```

### Problem 
And then I inject `wrapper.toHex()` into a QR code component (`import QRCode from "react-qr-code";`) but it displays a hex that is way too big (length 748) and not recogized by the mobile app.

I tried using your `QrDisplayPayload` component but it doesn't work either. Frthermore, I can't see the content of @polkadot/react-qr so that's not helpful either.

Helpen! :)

**Comment by jacogr** [comment]
You need to pass the u8a, see https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/signers/QrSigner.ts#L24-L26 (the exact flags are important here, i.e. the QR needs the extra information that the flag applies) - for large QRs, it is a multipart message (`QrDisplayPayload` handles that)

**Comment by joelamouche** [comment]
I tried both u8a in the QRCode from "react-qr-code" and in QrDisplayPayload and neither work

**Comment by joelamouche** [comment]
BTW how do I use QrDisplayPayload? 
I get this when installing @polkadot/react-components:
```
Failed to compile
./node_modules/@polkadot/react-components/util/getContractAbi.js
Module not found: Can't resolve '@polkadot/api-contract' in '/Users/antoineestienne/GitHubRepo/moonriver-crowdloan-attestation/web/node_modules/@polkadot/react-components/util'
```

And when I install all the missing dependencies I get 

![Uploading Screenshot 2021-06-09 at 11.25.38.png…]()

**Comment by jacogr** [comment]
`@polkadot/react-components` is not published (it used to be hence the ancient version hanging about).

This is for the QR reading/writing - https://github.com/polkadot-js/ui/tree/master/packages/react-qr

**Comment by joelamouche** [comment]
Ok great thanks it display correctly but the app doesn't recognize the tx:
"Unable to parse QR data we cannot handle the paylaod: 0,0,1,0,0,3,etc"

Am I bulding the tx the right way?
```
const remarkExtrinsic = api.tx.system.remark(token);
const payload={
        method: remarkExtrinsic.method.toHex(),
        nonce:u8aToHex(nonce),
        genesisHash: u8aToHex(api.genesisHash),
        blockHash: u8aToHex(api.genesisHash),
        runtimeVersion: api.runtimeVersion,
        version: api.extrinsicVersion,
    }
const wrapper = api.createType(
      "ExtrinsicPayload",
      payload,
      { version: api.extrinsicVersion }
    );
```

Should it rather be as instructed here (https://wiki.polkadot.network/docs/en/build-transaction-construction) ?
`const signingPayload = createSigningPayload(unsigned, { registry });`

**Comment by joelamouche** [comment]
Should I pass `remarkExtrinsic.method.toHex()` as payload to the component instead? Would be grat if you could point me to where in the app the paylaod is created, because I couldn't find any call to signPayload

**Comment by jacogr** [comment]
The signer linked above e.g. https://github.com/polkadot-js/apps/blob/master/packages/react-signer/src/signers/QrSigner.ts#L24-L26 is created as an instance and passed to the tx as part of the transaction options. So all it does it take what the API gives it and then resolves (so the API can continue) once resolved.

So the API works fully with the Signer and the signer manages the U part to get the right data from the user.

**Comment by joelamouche** [comment]
Nice thanks
