### ISSUE TITLE
Does it a right approach to get extrinsic Index inside the block after sent?

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#3628]
I want to get extrinsic/transaction 'Index' inside a block with bellow sending api.

Does it correct to use the `applyExtrinsic` property of phase variable as my extrinsic 'Index'  ?

```
async function submitTxAndWatch(api, signedTx) {

    const submittable = await api.tx(signedTx)

    let result = await submittable.send(({status, events}) => {

        if (status.isInBlock) {
            console.log(`included in ${status.asInBlock}`);  
        }else if (status.isFinalized) {
            console.log('Finalized block hash', status.asFinalized.toHex());

            events.forEach(({ event: { data, method, section, meta, typeDef }, phase }) => {
                try {
                    console.log("begin event loop ... : ");
                    console.log('\t phase: ', phase.toString(), `: ${section}.${method}`, data.toString());

                    // Show what we are busy with
                    console.log(`\t section:method >  ${section}:${method}:: (phase=${phase.toString()})`);
                    console.log(`\t\t meta.documentation >  ${meta.documentation.toString()}`);
                    });
                }catch (e) {
                    console.log("events catch error : ", e);
                }
            });
            console.log('TxHash', submittable.hash.toHex());
        }
    })

    console.log("submitTxAndWatch end. Send result: ", result);
    return result;
}
```

After called,  I can get log like these:

> Finalized block hash 0xf2e509933f01226feeb88b08de9b06fee50f59d9d17b032f956addb583690b4d
begin event loop ... : 
	 phase:  {"applyExtrinsic":2} : balances.Transfer ["5EctLnqQoDfcTs1ghwkDwi31k8xdtdSsR8TjSfY5QGj9anrX","5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",6]
	 section:method >  balances:Transfer:: (phase={"applyExtrinsic":2})
		 meta.documentation >  [ Transfer succeeded. \[from, to, value\]]
begin event loop ... : 
	 phase:  {"applyExtrinsic":2} : utility.BatchCompleted []
	 section:method >  utility:BatchCompleted:: (phase={"applyExtrinsic":2})
		 meta.documentation >  [ Batch of dispatches completed fully with no error.]
begin event loop ... : 
	 phase:  {"applyExtrinsic":2} : balances.Deposit ["5FbpwTP4usJ7dCFvtwzpew6NfXhtkvZH1jY4h6UfLztyD3Ng",16200001717]
	 section:method >  balances:Deposit:: (phase={"applyExtrinsic":2})
		 meta.documentation >  [ Some amount was deposited (e.g. for transaction fees). \[who, deposit\]]
begin event loop ... : 
	 phase:  {"applyExtrinsic":2} : system.ExtrinsicSuccess [{"weight":214650000,"class":"Normal","paysFee":"Yes"}]
	 section:method >  system:ExtrinsicSuccess:: (phase={"applyExtrinsic":2})
		 meta.documentation >  [ An extrinsic completed successfully. \[info\]]
TxHash 0xb1412aa3088b292ac8b799285aa384a1b6bcdbd28779375ca04145b6a9378a49

**Comment by jacogr** [comment]
100% - yes, the apply refers to the index of the extrinsic inside the block.

**Comment by code-brewer** [comment]
> 100% - yes, the apply refers to the index of the extrinsic inside the block.

Thanks very much.
