### ISSUE TITLE
How to Decode Events based on the ABI file

### ISSUE THREAD

**Issue by SaberDoTcodeR** [polkadot-js/api#3629]
Hi, I have a contract and I want to check the events but when I try to check them I can see the Transfer event right but my custom events are not decoded.

```
events.forEach((record) => {
    // Extract the phase, event and the event types
    const { event, phase } = record;
    const types = event.typeDef;

    // Show what we are busy with
    console.log(`\t${event.section}:${event.method}:: (phase=${phase.toString()})`);
    console.log(`\t\t${event.meta.documentation.toString()}`);

    // Loop through each of the parameters, displaying the type and data
    event.data.forEach((data, index) => {
      console.log(`\t\t\t${types[index].type}: ${data.toString()}`);
    });
  });
```

the output is like this:

```
 balances:Transfer:: (phase={"applyExtrinsic":1})
                [ Transfer succeeded. \[from, to, value\]]
                        AccountId: 5FHneW46xGXgs5m**********C92UhjJM694ty
                        AccountId: 5HU3ay8NUP4fUte3**********tMtVxAd2T
                        Balance: 100
contracts:ContractEmitted:: (phase={"applyExtrinsic":1})
                [ A custom event emitted by the contract.,  \[contract, data\], ,  # Params, ,  - `contract`: The contract that emitted the event.,  - `data`: Data supplied by the contract. Metadata generated during contract,            compilation is needed to decode it.]
                        AccountId: 5HU3ay8NUP4fUte3CvSGdQYNDqH2xLCZXB5KUdRtMtVxAd2T
                        Bytes: 0x018eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48e80300000000000010270000000000000000000000000000
```

so basically all I need is to decode this data `0x018eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48e80300000000000010270000000000000000000000000000
` , I couldn't find any docs about this. 

Thanks for helping.

**Comment by jacogr** [comment]
- construct an `Abi` instance using the abi JSON
- use the `decodeEvent` method, e.g. https://github.com/polkadot-js/api/blob/master/packages/api-contract/src/Abi.ts#L78

**Comment by SaberDoTcodeR** [comment]
Thanks a lot; it worked. I think it would be great to add documentation and sample code about this in [here](https://polkadot.js.org/docs/api/examples/promise/system-events).
And also, is there a way to get the panic message of smart contract in the js?

**Comment by jacogr** [comment]
So if you use the `contract.tx.method(...)` signature, the events come in decoded already without you having to do anything. That should be in the docs.
