### ISSUE TITLE
How to use CodePromise tx.new() api

### ISSUE THREAD

**Issue by seanyoung** [polkadot-js/api#3631]
If I try to use the CodePromise interface, I get an error whatever value I provide.

I'm running against substrate v3.0.0, standard flipper contract and polkadot/api  and polkadot/api-contract v3.11. If deploy the same contract using polkadot app it works fine.

```
import fs from 'fs';
import { ApiPromise, Keyring } from '@polkadot/api';
import { CodePromise, ContractPromise } from '@polkadot/api-contract';

async function main() {
  // create the api, default to 127.0.0.1:9944 (assuming dev)
  const api = await ApiPromise.create();

  // create the keyring and add Alice
  const keyring = new Keyring({ type: 'sr25519' });
  const alice = keyring.addFromUri('//Alice');

  // create the contract
  const contractJson = fs.readFileSync('flipper.contract', { encoding: 'utf-8' });
  const code = new CodePromise(api, contractJson, null);

  const tx = code.tx.new({ gasLimit: 200000n * 1000000n, value: 1n }, 1);

  const res = await tx.signAndSend(alice, (result) => {
    console.log("result: " + JSON.stringify(result));
    const { status, contractEvents, dispatchError, dispatchInfo, events } = result;
    if (dispatchError) {
    console.log("decoded: " + JSON.stringify(dispatchError));
    const decoded = tx.registry.findMetaError(dispatchError.asModule);
    console.log("decoded: " + JSON.stringify(decoded));
	     }
  });

  console.log("res: " + JSON.stringify(res));
}

main();
```

**Comment by seanyoung** [comment]
This is the error:

decoded: {"documentation":[" Performing the requested transfer failed for a reason originating in the"," chosen currency implementation of the runtime. Most probably the balance is"," too low or locks are placed on it."],"index":10,"method":"TransferFailed","name":"TransferFailed","section":"contracts"}

**Comment by jacogr** [comment]
The apps UI is tracking the latest API - I would suggest upgrading, there is not much I can do with or help with old errors.

**Comment by seanyoung** [comment]
Turns out that upgrading gave me the correct error, and now I've solved the issue. Thank you!

**Comment by jacogr** [comment]
Phew, cool!
