### ISSUE TITLE
Decode the hash from api.rpc.childstate.getStorage

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/api#3632]
how do I decode api.rpc.childstate.getStorage to get the value corresponding to this key, I try to get the amount donated by contributors in crowdloan?
```
 const key = createChildKey(api.createType('TrieIndex', 3))
api.rpc.childstate.getKeys(key, '0x')
.then(res => {
    const contributors = res.map((k) => keyring.encodeAddress(k, 2))
    console.log('contributors', JSON.stringify(contributors))
})

api.rpc.childstate.getStorage('0x3a6368696c645f73746f726167653a64656661756c743a6993b2b365f09a434610d6337d5e802876f8145eeec42a5b9cf1d7e6001e148d', 
'0x1ce2d87554def067a1bf48aa6174ab7652f19db95196e57da9bff49649d3550a').then(res => {

    const result = api.createType('(BalanceOf, Vec<u8>)', res)
    console.log(result.toJSON())
})
```
The console output is
```
[ 0, '0x' ]
```

**Comment by yuhui1208** [comment]
change api.createType('(BalanceOf, Vec<u8>)', res) to api.createType('(BalanceOf, Vec<u8>)', res.unwrap) solved 😄

**Comment by jacogr** [comment]
Indeed, the `getStorage` returns an `Option`, see https://polkadot.js.org/docs/substrate/rpc#getstoragechildkey-prefixedstoragekey-key-storagekey-at-hash-optionstoragedata
