### ISSUE TITLE
Question: ApiPromise with HttpProvider currently not possible?

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#3634]
Can `HttpProvider` be used in any way right now? It doesn't look like ApiPromise can accept it as a provider

**Comment by jacogr** [comment]
It should still work, even though it is not actively tested. What issues are you getting?

**Comment by Yuripetusko** [comment]
@jacogr well it starts with types

![image](https://user-images.githubusercontent.com/666169/121564293-33f7cf80-ca13-11eb-8c7e-2b5efad07887.png)


But even if I supress it with ts-ignore then I get

![image](https://user-images.githubusercontent.com/666169/121564618-8fc25880-ca13-11eb-8db0-0668bfc64f8d.png)

**Comment by jacogr** [comment]
```js
import { HttpProvider } from '@polkadot/rpc-provider';`
```

There is no default export in `@polkadot/rpc-provider/http` it also only exports the named `HttpProvider`

**Comment by Yuripetusko** [comment]
@jacogr not according to Webstorm atleast

![image](https://user-images.githubusercontent.com/666169/121567199-3576c700-ca16-11eb-9779-76c328112733.png)

**Comment by Yuripetusko** [comment]
Oh I see now `@polkadot/api-provider` will try

**Comment by Yuripetusko** [comment]
It's the same TS errors

![image](https://user-images.githubusercontent.com/666169/121567964-0f9df200-ca17-11eb-82ce-8915c8202b7c.png)

And also docs in HttpProvider show a different example how to use it (looks like outdated?)

![image](https://user-images.githubusercontent.com/666169/121568027-22b0c200-ca17-11eb-8749-21fb74c1f556.png)

**Comment by jacogr** [comment]
`@polkadot/rpc-provider` is the package, not `api-provider`

**Comment by Yuripetusko** [comment]
Yay it works! Thanks Jaco and sorry for distractions
