### ISSUE TITLE
BTreeSet and BTreeMap encoding

### ISSUE THREAD

**Issue by Lezek123** [polkadot-js/api#3636]
There seems to be a long-running issue with the encoding of `BTreeSet` / `BTreeMap`.
Currently tested with `@polkadot/api` version: `4.2.1`

**The issue**
If one of the runtime extrinsics takes either `BTreeSet` or `BTreeMap` as argument, it can be provided as JavaScript `array` / `Set` (`BTreeSet`) or `Map` (`BTreeMap`), but we need to make sure that:
- the values are sorted in ascending order (in case of `BTreeSet`)
- the keys are sorted in ascending order (in case of `BTreeMap`)

Otherwise the call will fail with `ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature`.

So for example, if we assume the extrinsic argument is a `BTreeSet`, then:
```
await api.tx.module.method([1, 2, 3]).signAndSend(ALICE) // This will work
await api.tx.module.method([3, 2, 1]).signAndSend(ALICE) // This will throw an error
```

Those errors can be hard to spot and parse and require additional workarounds in `@polkadot/api` consumer applications.

**How to reproduce**

Unfortunately I don't have a minimum repository example, but this can be observed with [Joystream](https://github.com/Joystream/joystream) node:

1.
```
docker pull joystream/node
docker run -p 127.0.0.1:9944:9944 -p 127.0.0.1:9933:9933 joystream/node --dev --alice --validator --log runtime --rpc-port 9933 --unsafe-rpc-external --unsafe-ws-external --rpc-methods Unsafe
```
2. Go to https://testnet.joystream.org/#/settings
3. Set endpoint to `Local node`
4. Set interface operation mode to `Fully featured`
5. Hit `Save`
6. Go to `Developer`
7. Paste the json types from https://raw.githubusercontent.com/Joystream/joystream/master/types/augment/all/defs.json (this will prevent the current workaround for this issue from taking effect)
8. Go to https://testnet.joystream.org/#/js
9. Paste the following script:
```
const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';

const fillOpeningTx = api.tx.contentDirectoryWorkingGroup.fillOpening(
  1, // openingId,
  [1, 2, 3], // applicants
  null
)

await fillOpeningTx.signAndSend(ALICE)
console.log('Sent')

const fillOpeningTx2 = api.tx.contentDirectoryWorkingGroup.fillOpening(
  1, // openingId,
  [3, 2, 1], // applicants
  null
)

try {
  await fillOpeningTx2.signAndSend(ALICE)
} catch (e) {
  console.log(e)
}
```

Notice that `fillOpeningTx` will be send and `fillOpeningTx2` will fail with `ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature`, while the only difference between those calls is the order of elements in the array (`BTreeSet` extrinsic arg): `[1, 2, 3]` vs `[3, 2, 1]`

**The fix**

Make sure the keys / values are correctly sorted before beeing encoded or (perhaps even better) at `BTreeSet` / `BTreeMap` construction time.

**Comment by jacogr** [comment]
Seems sensible. PRs welcome, it will be quite  a while before I get to this.

(even more difficult since it is not used in the Substrate master base, which adds a lot of overhead with building yet another node, so personally need to have a lot of time available to get a gap to take a look - since it needs to be correct)
