### ISSUE TITLE
What is the result type?

### ISSUE THREAD

**Issue by VadneyK** [polkadot-js/api#3650]
Hello I am trying to use this api in TypeScript but I can't figure out the type of the `result` object here:

![Screen Shot 2021-06-14 at 4 40 57 PM](https://user-images.githubusercontent.com/57117207/121972184-4c2b5f80-cd2f-11eb-9067-7289d87b5236.png)

The quick fix doesn't seem to work and [`result: ISubmittableResult` seems to be used here](https://github.com/polkadot-js/api/blob/09831fe325df3b186baaed0aa1845c74b8a7e23d/packages/types/src/types/extrinsic.ts#L11) so I tried that but it doesn't have the [result interfaces built in as with the docs.](https://polkadot.js.org/docs/api-contract/FAQ#after-upgrading-to-25-im-missing-issuccessiserror) Where can I look into the functions and attributes available on the result object?

![Screen Shot 2021-06-14 at 4 43 28 PM](https://user-images.githubusercontent.com/57117207/121972333-a7f5e880-cd2f-11eb-8f9d-6cc2fff2a437.png)

Or I guess the docs are just outdated since this alternative function access works?

![Screen Shot 2021-06-14 at 4 50 41 PM](https://user-images.githubusercontent.com/57117207/121972735-aaa50d80-cd30-11eb-871d-ba3d903eb160.png)

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/api/blob/master/packages/types/src/types/extrinsic.ts#L11-L21

**Comment by VadneyK** [comment]
thanks! I guess the docs are just outdated
