### ISSUE TITLE
need to use a V3 contracts module?

### ISSUE THREAD

**Issue by VadneyK** [polkadot-js/api#3651]
I am trying to execute a function on my [smart contract ](https://github.com/PlasmNetwork/dusty-faucet/tree/main/contract)at `ZcJALe2RPN9p2RYosas2zwsjhQaNCb87ZtmJkhHh26wiX8U` with code hash `0xa1184ef1ec2bdf246b8c223535ae64db3ff7e39649b1b0bc35a38a5e678cc3d9` via [this code](https://github.com/PlasmNetwork/dusty-faucet/blob/main/app/src/helpers/sendTokens.ts) But am repeatedly prompted to connect to a V3 node as shown here: https://github.com/PlasmNetwork/dusty-faucet/issues/8

Thus it seems I may be using the polkadot.js api wrong, and I'm just stuck on this for a while and can't figure out where the issue is coming from! anyone know what causes this issue?

Executing .drip() via [the Ui here seems to work](https://polkadot.js.org/apps/#/contracts) so it must be that I am using this api wrong:

<img width="1292" alt="Screen Shot 2021-06-14 at 9 26 29 PM" src="https://user-images.githubusercontent.com/57117207/121992796-3336a480-cd57-11eb-8828-8fd3510422b1.png">

**Comment by jacogr** [comment]
You contracts module needs to have this extrinsic - https://polkadot.js.org/docs/substrate/extrinsics#instantiatewithcodeendowment-compactbalanceof-gas_limit-compactweight-code-bytes-data-bytes-salt-bytes

**Comment by jacogr** [comment]
In the above case, your API has not connected to the chain so the metadata has not been retrieved. Use `await ApiPromise.create({...})` to instantiate it correctly with a connected instance.

**Comment by VadneyK** [comment]
Thanks! Now I don't see any error on the server side, but I get an error for this call hash when calling the same smart contract above: `0xc4f968ba765ef50c1605462fa7e8b1844b2532aaeb3a6c48a18c0c7a67968f93` saying 

![Screen Shot 2021-06-15 at 9 09 48 AM](https://user-images.githubusercontent.com/57117207/122087367-7b86ae80-cdb9-11eb-841f-18888b7f9791.png)


![Screen Shot 2021-06-15 at 9 10 18 AM](https://user-images.githubusercontent.com/57117207/122087402-84778000-cdb9-11eb-936e-69965042a0b8.png)

Where can I go to understand the meaning of the error messages? I can't seem to google search to find a verbose explanation of the error. Is there some good comments on the original repo that implemented the error types?

Here is my api interaction code for reference, also available here
<img width="523" alt="Screen Shot 2021-06-15 at 9 12 20 AM" src="https://user-images.githubusercontent.com/57117207/122087657-cf919300-cdb9-11eb-8ef3-c9666eda71e6.png">

**Comment by jacogr** [comment]
The `type` and `details` in the UI is the decoded message, i.e. the contract trapped. (It is the dispatchError decoded)

**Comment by VadneyK** [comment]
What do you mean by the contract is trapped? as in it panic!'d somewhere? How can I get the smart contract to print out the panic message to the polkadot.js api so I can parse and console.log that? I am especially confused why the discord server side is not console loggint the error. I also have 5 replies from the discord bot for some reason:


![Screen Shot 2021-06-15 at 9 34 19 AM](https://user-images.githubusercontent.com/57117207/122090660-dcfc4c80-cdbc-11eb-87ea-e7b9048a5efe.png)

**Comment by VadneyK** [comment]
Also I'm trying to learn what the errors are here but am I confused or is the example out dated? https://github.com/w3f/polkadot-wiki/issues/2164

**Comment by VadneyK** [comment]
Also I'm getting a contract.ContractTrapped but this doesn't seem to show up on the table here https://wiki.polkadot.network/docs/en/maintain-errors so that means its a non-general polkadot error specific to the dusty network I'm using right?

**Comment by VadneyK** [comment]
index 8 corresponds to the `pallet_balances` [here from the dusty network runtime](https://github.com/PlasmNetwork/Plasm/blob/f4b669f2b9c4f5680ee7ccbdde0011462c8c702d/bin/node/runtime/src/lib.rs#L719)

but Balances doesn't have a 17th index error enum? Is this pointing to the index in the polkadot runtime?

**Comment by VadneyK** [comment]
It seems that everything besides `drip()` and `wasItAmt()` from here seems to work. The 2 have the same error.[ Here is my contract code.](https://github.com/PlasmNetwork/dusty-faucet/blob/main/contract/lib.rs)

![Screen Shot 2021-06-15 at 10 25 04 AM](https://user-images.githubusercontent.com/57117207/122096945-f3f26d00-cdc3-11eb-8aa8-8c83f8a873fa.png)

**Comment by VadneyK** [comment]
the deployer account calling drip(to = deployer account) seems to work, but when I try to have the deployer account call drip(to = other account) it gives me this error.

**Comment by VadneyK** [comment]
Huh, I didn't do anything and just tried to execute the smart contract later and it just worked for all cases? Did the contract just take time to get situated in the network for some reason?

1. Deployer call - to: deployer = [success](https://polkadot.js.org/apps/#/explorer/query/0x37c5da80a4fb9060d7327bed47a4a747f8fac16bfb2b837f33a6cc60a5cfb12b)
2. Deployer call - to: non-deployer = [success](https://polkadot.js.org/apps/#/explorer/query/0x3e0810f577c2198b64e25fa656b97fd20ec425406c8e108df24d825277c690d1)
3. Non-deployer call - to:deployer = [success](https://polkadot.js.org/apps/#/explorer/query/0x69dc6610079a42eed1bb32178a983c1501d99c6c7582313b6888c878a4622411)
4. Non-deployer call - to: Non-deployer = [success](https://polkadot.js.org/apps/#/explorer/query/0xd109d2079a748b46b5f6abf536ceed08ae87a79240691568cb209d960f38b47f)

**Comment by VadneyK** [comment]
It seems that calling `wasItAmt()` or `drip(to)` where the address at to has 0 PLD causes the [trapped error here.](https://polkadot.js.org/apps/#/explorer/query/0xbb1c0c531b6c98bbcefda2c2cd7f662955dff55992a8bf6edb80abc4fb51e7a8)

**Comment by VadneyK** [comment]
After sending 10 PLD to a test account what I set `to` equal to, and calling `drip()` with the same function,[ it worked.](https://polkadot.js.org/apps/#/explorer/query/0xb1c4da654233d6b9cfa4f79d10fe8e25318821cd36aeb736811324df8754b200) Here is the settings when I sign:
![Screen Shot 2021-06-15 at 9 09 48 AM](https://user-images.githubusercontent.com/57117207/122102702-8f86dc00-cdca-11eb-83e1-bccc378be8d5.png)

But then neither has the contract's balance gone down nor the receiver's address gone up by 10 PLD. I thought this may have to do with the recent re-denomination of PLM but that shouldn't have to do with PLD...

**Comment by HCastano** [comment]
@VadneyK Your transactions are not succeeding, that's what the `ContractTrapped` messages are indicating.

I don't think this is @jacogr's problem, so let's move this over to the issue you opened on Ink.

**Comment by VadneyK** [comment]
it was working, the units were in femto PLD instead of 1 PLD... ;(
