### ISSUE TITLE
How to pass Vector of String to contract

### ISSUE THREAD

**Issue by SaberDoTcodeR** [polkadot-js/api#3655]
Hi, I need to pass an array of strings as an input of a contract function.
The Signature of function is like this:
```
pub fn edit_plan(texts: Vec<String>)
```
but when I call the function with `['text1', 'text2']` it will fail. 
I think I need to do some encoding before calling the function.

PS:
The canvas UI is working well when I call this function with a generic length.

**Comment by jacogr** [comment]
`['text1, 'text2']` is the correct form. What fails?

**Comment by SaberDoTcodeR** [comment]
That's odd, I use the exact same parameters in my UI and the Canvas UI but, mine is not working. The contract trapped because of our logic with this error 	 
```
{"applyExtrinsic":1} : system.ExtrinsicFailed [{"module":{"index":8,"error":17}},{"weight":19258562233,"class":"Normal","paysFee":"Yes"}]
```

**Comment by jacogr** [comment]
There are a lot of moving parts - I would suggest getting a mimimal reproducible sample, including how the call is made.

**Comment by SaberDoTcodeR** [comment]
@jacogr Thanks for your help, There was a problem in the way that I built the transaction. The Endowment amount was like this `9,000,000` and when I changed it to `9000000` it worked.
