### ISSUE TITLE
Unable to retrieve the connected peers of the network

### ISSUE THREAD

**Issue by prasannayasan** [polkadot-js/api#3656]
I am trying to fetch all the connected peers of a network with [rpc](https://polkadot.js.org/docs/substrate/rpc/#peers-vecpeerinfo) endpoint. 
It returns Vec<PeerInfo>, but I unable to access the objects in that vector, so I tried to print the length of vector and it returned 0 as connected peers.

```
const {API} = ApiPromise.create({ provider: wsProvider });

const status = async function(input) {
  const api = await API
  const peers = await api.rpc.system.peers;
  console.log("peers count " + peers.length);
}
```

My project is connected to 'wss://rpc.polkadot.io' network. 
When I checked the console output for connected peers its connected with more than 40 peers, but the api provided by polkadot is returning as zero.

Also tried similar endpoints provided in the [rpc](https://polkadot.js.org/docs/substrate/rpc/) site, 
api.rpc.net.peerCount - this endpoint return peers count in string format, but I receives undefined. am unable to access

**Comment by jacogr** [comment]
This is incorrect - `const {API} = ApiPromise.create({ provider: wsProvider });` - should be `const API = ApiPromise.create({...})`

You cannot retrieve `system_peers` from the rpc.polkadot.network site. It is an unsafe RPC that is not exposed on RPC nodes. (Unless run with the `--unsafe` flag)

**Comment by prasannayasan** [comment]
@jacogr I tried running the polkadot node using --unsafe flag but it threw an error. It said the only recognised flag available is --unsafe-pruning. 
I ran the node with  --unsafe-pruning , but using this also did not help.

So, can you tell how to get the peers information from a node? 
And also you mentioned rpc.polkadot.network is unsafe, why is it considered unsafe?

**Comment by jacogr** [comment]
Check the node flags via `--help`, I'm not an expert with the flags. Could be `--unsafe-external` or something else.

It leaks information that is not needed for anybody but the node operator. Hence it is not meant to be public.
