### ISSUE TITLE
Support Accounts without AccountData

### ISSUE THREAD

**Issue by apopiak** [polkadot-js/api#3657]
This code assumes `AccountData` to be present in `AccountInfo` if there is a nonce.

https://github.com/polkadot-js/api/blob/f97a6d041827e64c96e6274bc1e2c3ea275fcd5f/packages/api-derive/src/balances/account.ts#L87-L89

This assumption does not hold for chains that set `type AccountData = ();` (e.g. Compound Gateway [here](https://github.com/compound-finance/gateway/blob/0d8b3f4e6bea7fda6c458e9cdce9c0f79e382cc7/runtime/src/lib.rs#L214)).

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/3658
