### ISSUE TITLE
Passing api object in function makes it undefined?

### ISSUE THREAD

**Issue by VadneyK** [polkadot-js/api#3660]
I am passing the api object in function and it is totally fine before but them becomes undefined after being passed in the function. Why is this?

https://github.com/PlasmNetwork/dusty-faucet/issues/10

**Comment by jacogr** [comment]
As commented elsewhere - "That is an issue in your code, not the API itself. The object references are not mishandled in the API."

**Comment by VadneyK** [comment]
https://github.com/PlasmNetwork/dusty-faucet/issues/10
