### ISSUE TITLE
Unhandled Rejection (Error): Cannot sign with a locked key pair

### ISSUE THREAD

**Issue by 2075** [polkadot-js/api#3664]
When running our test Dapp based on frontend template, in local as well as remote deployment, somehow i am incapable of properly triggering the polkadotjs extension to sign a message. the context provider is identical to the template, we just want to manually trigger and sign tx. somehow all we get is `Unhandled Rejection (Error): Cannot sign with a locked key pair` and in some cases a low priority message on a local dev node.

My assumption was, that signandsend with accountPair as the sender, when using an injected account together with extension, would trigger signing through the plugin?

e.g.:
```
	        const sender = accountPair
			const recipient = 'xyz'
			const amount = 10

			for (let i = 0; i < 10; i++) {
				console.log(i)
				const txhash = await api.tx.balances
					.transfer(recipient, amount)
					.signAndSend(sender, { nonce: -1 });
			}
```

What do i miss? Thanks for a pointer!

**Comment by jacogr** [comment]
The API is obvious where the pair comes from. It doesn't even know something like an extension exists. (Or QR codes, ledgers, etc...)

In the case of injected accounts you need to pass a a signer through that know how to communicate with the extension.

See https://polkadot.js.org/docs/extension/usage
