### ISSUE TITLE
Type generation issue: Only support for [Type; <length>], where length <= 256

### ISSUE THREAD

**Issue by herryho** [polkadot-js/api#3666]
Hi,
I'm generating types sdk by typegen. It pops out the following error message while generating augment-api-query.ts file. 
![WX20210617-172754](https://user-images.githubusercontent.com/45537372/122370332-90b63580-cf91-11eb-8555-0fd19c65b3c9.png)

I have a storage structure similar to what is described by the error message, where I guess the error might come from.
![image](https://user-images.githubusercontent.com/45537372/122362810-05d23c80-cf8b-11eb-9634-ec195d27e1ec.png)

AssetId type is defined as follows:
    AssetId: {
      chain_id: "u32",
      asset_type: "u8",
      asset_index: "u32",
    }

The storage structure is ((AssetId, AssetId), T::AccountId).  Since
AssetId= 4+1+4 =>  12 bytes
AccountId => 32 bytes
And the total length of it should be 12+12+32 = 56 bytes < 256
It seems length should not be the problem!

Please help to find out the real problem. Thanks!

**Comment by jacogr** [comment]
It is not the total length of the structure, rather it limits the following constructs -

- `[u32; 255]` - all ok
- `[u32; 512]` - not ok

So I would look for those. It is not a "unchangeable limit", so can be adjusted if indeed an issue in your definitions. (It just tries to add some protections around, i.e. when parsing goes "very wrong" it can yield memory issues which it tracked earlier by the above)

**Comment by herryho** [comment]
Is this limit newly added to polkadot.js? Because it was able to compile with the chain version Polkadot of v0.9.3 and Polkadot.js of v4.14.1. Now our chain upgrades to Polkadot of v0.9.4 and  Polkadot.js of v4.14.1, the issue appears.

**Comment by jacogr** [comment]
No, the check is ancient. It is due to type definitions, nothing to do with the chain.

**Comment by herryho** [comment]
Hello~ Is there any progress on the above typing issue? Since the storage structure is from a 3rd party module, we are not able to directly change it. So I'm hoping that there might be some kind of solution from your side 😃

**Comment by jacogr** [comment]
There is no solution that I can provide - it is somewhere in the type definitions for the specific generation.

**Comment by herryho** [comment]
Hi Jacor,
After a bunch of trials，I found a stupid but useful way to work around the problem.

Here is the type that causes parsing error.
![image](https://user-images.githubusercontent.com/45537372/122548562-1b676500-d064-11eb-99fc-1923f51f682a.png)

According to the type parsing rules shown below:
`[['[', ']', _types.TypeDefInfo.VecFixed, _decodeFixedVec], 
['(', ')', _types.TypeDefInfo.Tuple, _decodeTuple],
['BTreeMap<', '>', _types.TypeDefInfo.BTreeMap, _decodeTuple], 
['HashMap<', '>', _types.TypeDefInfo.HashMap, _decodeTuple], 
['Result<', '>', _types.TypeDefInfo.Result, _decodeTuple],`

As long as the content is wrapped by [ ], the type generator will consider it to be an array, and then send it to decodeFixedVec, which is wrong. In fact, this should be a tuple instead of an array, which should be sent to the decodeTuple function.

I replace the squre brackets by the parenthesis and add the following snippet to the getTypeDef.cjs file. It worked. 

`if (type == "[ITuple|[AssetId|{chain_id?:any;asset_type?:any;asset_index?:any}|string|Uint8Array,AssetId|{chain_id?:any;asset_type?:any;asset_index?:any}|string|Uint8Array],AccountId|string|Uint8Array]") {
type = "(ITuple|(AssetId|{chain_id?:any;asset_type?:any;asset_index?:any}|string|Uint8Array,AssetId|{chain_id?:any;asset_type?:any;asset_index?:any}|string|Uint8Array),AccountId|string|Uint8Array)";
}`
![image](https://user-images.githubusercontent.com/45537372/122549230-d7c12b00-d064-11eb-80fe-3b06be8ead36.png)

Do you have any insight on why the parsing fails?

**Comment by herryho** [comment]
There's another issue that I observed during the process of buiding types using typegen. But it seems not quite related to this post 😂 
We have a custom type which has a name conflicting to the polkadot.js type name of "AssetBalance". In our SDK, I rename it using typesAlias, like so:
  typesAlias: {
    ZenProtocol: {
      AssetBalance: "ZenAssetBalance",
    },
types: {
ZenAssetBalance: "u128",
}

The augment-api-query.ts and augment-aip-rpc files are generated fine. However, the type "AssetBalance" type in agument-api-tx.ts file was not replace by the new type name of "ZenAssetBalance", which indicates errors. I have to mannually do the replacement by myself.

Is there anything I can do to avoid the manual operation?

**Comment by jacogr** [comment]
Honestly, no idea on the first - without a specific type string to check, nothing I can say as to "what is wrong".

The second one could be that the RPC doesn't not apply aliasses, PRs welcome if not, otherwise it would need to be an new issue (since it is not related to this at all and honestly cannot keep track if things are not pin-point exact as to requirements/issues).
