### ISSUE TITLE
Unknown types found, no types for ValidationCodeHash

### ISSUE THREAD

**Issue by terryyyyyy** [polkadot-js/api#3691]
There days I got this issue:
API-WS: disconnected from wss://kusama-rpc.polkadot.io: 1006:: Connection dropped by remote peer.
METADATA: Unknown types found, no types for ValidationCodeHash
API/INIT: Error: FATAL: Unable to initialize the API: createType(ValidationCodeHash):: Cannot construct unknown type ValidationCodeHash

Is there any way to handle this?

**Comment by jacogr** [comment]
Update your API - https://github.com/polkadot-js/api/releases/tag/v4.14.1

**Comment by terryyyyyy** [comment]
Yes ,I have update polkadot/api to 4.15.1, but the issue still exist

**Comment by jacogr** [comment]
Very unlikely unless you don't have the `@polkadot/types` aligned with the API version (they always need to be in-lock-step). The type is there, so you are not running the correct versions.

**Comment by terryyyyyy** [comment]
There are my packages What can I do?
![image](https://user-images.githubusercontent.com/15071907/123412812-9a204d00-d5e4-11eb-9228-5b205094758f.png)

**Comment by terryyyyyy** [comment]
@jacogr Hi, I start node on my local PC ,It's all ok.But run it on server with pm2, It shows the error.I have update yarn.lock and update pm2 .It still happened.

**Comment by terryyyyyy** [comment]
> @jacogr Hi, I start node on my local PC ,It's all ok.But run it on server with pm2, It shows the error.I have update yarn.lock and update pm2 .It still happened.

Sorry, It's my fault, pm2 combine the logs of other project.This error came from another project.The error shut down when I update the packages.
