### ISSUE TITLE
Can't use sudo set balance due to misunderstandings with types

### ISSUE THREAD

**Issue by serezhaolshan** [polkadot-js/api#3692]
![image](https://user-images.githubusercontent.com/50380528/123283346-fd8e7a00-d513-11eb-902e-3f1e61fa377b.png)
I am doing functionality for testing the blockchain, namely for creating wallets and establishing a balance on them through sudo. However, the usual transfer (not through the Sudo) goes well. What could be the reason for this error?
![image](https://user-images.githubusercontent.com/50380528/123283461-172fc180-d514-11eb-8b02-110a00b02838.png)

**Comment by jacogr** [comment]
It would be better not posting screenshots, in this case it is actually really difficult to see the actual messages and the code since my eyes and the scheme above doesn't align :)

As far as I can see with the error (difficult to make out) It is from the BN lib, eg. "assertion failed" which could be due to missing libs not being packaged or it finding an invalid value it cannot convert. Since the actual `amount` assignment is not shown above, I don't know what is passed through, but it does point to that value.

**Comment by serezhaolshan** [comment]
@jacogr 
```
const amount = 10000000000000000;
const keyring = new Keyring({ type: 'sr25519', ss58Format: 42 });
const mnemonic = '*Our sudo mnemonic*';
const sudoGetPair = keyring.createFromUri(mnemonic);

for (let i = 0; i < 1000; i++) {
      const mnemonicFor = mnemonicGenerate();
      const pair = keyring.createFromUri(mnemonicFor);
      const nonce = await api.rpc.system.accountNextIndex(pair.address);
      const unsub = api.tx.sudo
      .sudoAs(sudoGetPair.address,
        api.tx.balances.setBalance(pair.address.toString(), amount, 1)
        )
        .signAndSend(sudoGetPair.address, { nonce });

      // console.log(`Balance set from ${sudoGetPair.address} to ${pair.address}`);
    }
```

**Comment by jacogr** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

The maximum integer value in JS is `9007199254740991` you are passing `10000000000000000` which cannot be represented by a JS integer number.

So -

- pass a BigInt, i.e. `10000000000000000n`
- pass it as a string, i.e. `'10000000000000000'`

**Comment by serezhaolshan** [comment]
@jacogr , thanks a lot, will try with a BigNumber lib)
So stupid mistake xD

**Comment by serezhaolshan** [comment]
@jacogr 
The same program throw a new Error due to the lack of types, although this is a standard types of Sustrate
```
const amount = new BigNumber(10000000000000000);
const keyring = new Keyring({ type: 'sr25519', ss58Format: 42 });
const mnemonic = '*Our sudo mnemonic*';




    for (let i = 0; i < 1000; i++) {
      const mnemonicFor = mnemonicGenerate();
      const pair = keyring.createFromUri(mnemonicFor);
      const nonce = await api.rpc.system.accountNextIndex(pair.address);
      const unsub = await api.tx.sudo.sudo(
        api.tx.balances.setBalance(pair.address, amount.toString(), 10000)
        ).signAndSend(sudoGetPair, { nonce })
    }
  }
```
Error Text:
 ```
  [ExceptionsHandler] createType(Address):: Unable to create Enum via index 16, in Id, Index, Raw, Address32, Address20 +11488ms
Error: createType(Address):: Unable to create Enum via index 16, in Id, Index, Raw, Address32, Address20
 ```
