### ISSUE TITLE
Uniques InstanceDetails is missing InstanceMetadatas

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#3693]
If I am understanding this correctly then there's a mistake here where Class is using `instanceMetadatas` instead of `classMetadatas`, same with destroy it's using `instanceMetadatas`, and lastly `instanceDetails` missing `instanceMetadatas` alltogether

https://github.com/polkadot-js/api/blob/dfc546955fdbfb657246ae0b88be1bb06c0a383c/packages/types/src/interfaces/uniques/types.ts#L44

if my assumption is correct then let me know and I can create a PR

-----------------

On a similar note, I am having trouble quering class metadata, the only way I found is this

```
const nft = await polkadotApi.query.uniques.class('test');
const s = polkadotApi.registry.createType(
  'ClassMetadata',
  nft.unwrap().instanceMetadatas.toHex(),
);
console.log(s.toJSON());
```

Surely there's a better way?

And also even tho I did setClassMetadata, this still returns 0x

![image](https://user-images.githubusercontent.com/666169/123342469-bcb05880-d547-11eb-8e94-90986821553d.png)

**Comment by jacogr** [comment]
PRs welcome if the types are mismatched. Don’t know off hand would really need to check the structs against the Rust code again. 

If they are wrong, it would explain why the deciding doesn’t quite go as expected.

**Comment by Yuripetusko** [comment]
Ok I looked at Rust code this morning and not much is different, this is the only part that needs to be fixed

![image](https://user-images.githubusercontent.com/666169/123393459-0a53b200-d596-11eb-99c5-d08896f53bbd.png)


But really this is not the main problem, main problem that even on Rust level there is no way to get `class_metadata` or `instance_metadata` it simply is never returned. The only thing that is returned is `instance_metadatas` (plural) which simply returns total of metadatas on all instances of this class.

So while there's a way to set metadata, there's no way to read it, unless I am missing something. Should I post this issue in substrate repo?

**Comment by jacogr** [comment]
Yes, the types above seem wrong. This is now the second time, so I guess between me adding them and merging there were changes that I didn't pick up.

I really have not had a gap yet to look at and using uniques, so not quite familiar (yet) as to what may be missing for optimal use.

**Comment by Yuripetusko** [comment]
Ok I will submit these correct types, although it won't solve the underlying issue that comes from Rust of metadata not being returned. Meanwhile we will try to look into rust code and perhaps submit a PR there

**Comment by Yuripetusko** [comment]
Thanks. For information to other people looking for answers, this is how you can get metadata once set:

```
const uniqueClass = await polkadotApi.query.uniques.classMetadataOf('test');
const classMetadata = polkadotApi.registry.createType('ClassMetadata', r.toHex());
console.log(hexToString(t.data.toString()));
```
