### ISSUE TITLE
Cannot construct unknown type ShardIdentifier

### ISSUE THREAD

**Issue by mohsinriaz17** [polkadot-js/api#3696]
Hi
i get the error 

`API/INIT: Error: FATAL: Unable to initialize the API: createType(ShardIdentifier):: Cannot construct unknown type ShardIdentifier
    at EventEmitter.value (/usr/local/Cellar/node/15.0.1/lib/node_modules/@subql/node/node_modules/@polkadot/api/base/Init.cjs:88:25)`

when I try to initialize the project ( it is a graphql indexer using Postgres for events on our chain)

following are the Dependencies
"devDependencies": {
    "@polkadot/api": "4.15.2-6",
    "@subql/cli": "^0.9.3",
    "@subql/types": "^0.7.1",
    "typescript": "^4.1.3"
  }
  
any and all suggestions are welcome, where do I start to debug?
Thanks

**Comment by jacogr** [comment]
There is no `ShardIdentifier` type in either Substrate nor Polkadot, which is the built-in types polkadot-js has. 

See https://polkadot.js.org/docs/api/start/types.extend to add your custom types for your chain to the API.
