### ISSUE TITLE
Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12

### ISSUE THREAD

**Issue by outlier89** [polkadot-js/api#3706]
Version of @polkadot/api: 3.11.1
Cannot use latest 4.x version as our front-end framework Nuxtjs still isn't using Webpack 5.0 which is crucial for 4.x versions

Issue: Not able to initialize api. 
Code: 
`const provider = new WsProvider('wss://rpc.polkadot.io');`
`api = await ApiPromise.create({ provider });`

@jacogr  Please suggest a workaround this issue.

**Comment by jacogr** [comment]
Bump the API. 3.x is ancient and metadata v13 was introduced in the last 6 weeks in Substrate.

**Comment by outlier89** [comment]
Thanks for the quick response jaco. But when I bumped the api version to 4.16.2, below error occurs:
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: S:\test\node_modules\@polkadot\api\index.js`

@jacogr Please help bud
