### ISSUE TITLE
api.query.system.account.at throws error for old block hashes

### ISSUE THREAD

**Issue by fkbenjamin** [polkadot-js/api#3708]
Following the example at https://polkadot.js.org/docs/api/examples/promise/read-storage-at/, trying to query for the balance at an old block hash (e.g. Block 1: [0xcd9b8e2fc2f57c4570a86319b005832080e0c478ab41ae5d44e23705872f5ad3 ](https://kusama.subscan.io/block/1 )or Block 1000000: [0xb267ffd706bbb93779eab04f47c7038031657b0a863794dbdd73170e3976c3e7](https://kusama.subscan.io/block/1000000))) results in the following error:

```
2021-06-28 13:35:55        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","refcount":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)
Error: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","refcount":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)
    at RpcCore._newType (/Users/user/kusama-genesis-balance/node_modules/@polkadot/rpc-core/index.cjs:457:13)
    at RpcCore._formatStorageData (/Users/user/kusama-genesis-balance/node_modules/@polkadot/rpc-core/index.cjs:391:17)
    at RpcCore._formatOutput (/Users/user/kusama-genesis-balance/node_modules/@polkadot/rpc-core/index.cjs:368:19)
    at callWithRegistry (/Users/user/kusama-genesis-balance/node_modules/@polkadot/rpc-core/index.cjs:247:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I am using wss://kusama-rpc.polkadot.io/ for these queries, which is a confirmed archive node (https://guide.kusama.network/docs/kusama-endpoints/)

Polkadot API is at version 4.16.2

**Comment by jacogr** [comment]
Ok... now that I think through it.

So the issue is that at block 1, there was no `api.query.system.account.at` entry. So it will indeed return the current defaults. For really old just-post-genesis blocks the balances used to be stored in `baalances.freeBalance`

**Comment by haikoschol** [comment]
I'm running into the same issue on Polkadot.

Example inputs:
* block number: `3134647`
* block hash: `0xb842f533b3110bab3854343e088378af23110b560edf26111ba728b4560d6c76`
* account ID: `12vCVEpCz81rvS23PEJQ6KBDbPWgvyVX5Q1PrgQbVvLc4i2Z`

Should it be possible to query balances from all three locations with the current version of `polkadot-js/api`? Or do I need to find a matching version?

In 4.16.2, both `api.query.balances.freeBalance` and `api.query.balances.reservedBalance` are `undefined`.

**Comment by jacogr** [comment]
Yes, so they will be undefined - since those storage locations don't exist anymore in the metadata. And the API endpoints are decorated based on the current metadata. (This is the only way to solve that via #3585 - which is some way away, i.e. decorate API with historic stuff)

**Comment by fkbenjamin** [comment]
Hey @jacogr, thanks for clarifying. Does that mean it's currently not possible to get these historic balances from the chain?

**Comment by jacogr** [comment]
It is in the trie, so you can. 

Query the storage with the correctly constructed key and decode. (As mentioned above) Since it is not decorated and not in the current metadata the API cannot provide help here. So you basically need to do it via getStorage RPC.

**Comment by haikoschol** [comment]
@fkbenjamin Here's a great explanation on how to use the getStorage RPC and it even happens to use `Balances.FreeBalance` as an example: https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/

**Comment by fkbenjamin** [comment]
Thanks @haikoschol , I'll check that link out! :)

**Comment by jacogr** [comment]
As of `4.17.1` the form such as `api.at(<blockHash>).balances.freeBalance(<address>)` will return the values

**Comment by haikoschol** [comment]
Thanks @jacogr!

One correction regarding [my comment above](https://github.com/polkadot-js/api/issues/3708#issuecomment-869690879): The changes to how balances are stored were made before Polkadot went live. That means, this issue only exists on Kusama and I was mistaken about the error I saw. The real issue was that some of the accounts I was querying simply didn't exist that far back. However, I'll have to do the same for Kusama and this will come in very handy!
