### ISSUE TITLE
@polkadot/metadata decorate/index.cjs - assert fails in expandMetadata()

### ISSUE THREAD

**Issue by matjazonline** [polkadot-js/api#3709]
Debugging in WebDev React runs index.js without issue but assert in expandMetadata() fails when Angular runs index.cjs. The provider connects to same server instance in both apps so same metadata value is returned.

Angular v12
"@polkadot/api": "^4.14.1",
"@polkadot/extension-dapp": "^0.38.5",
"@polkadot/extension-inject": "^0.38.5"
"@polkadot/ui-keyring": "^0.80.1"

**Comment by jacogr** [comment]
So you answered the question - it has something to do with the way you package and use it. Most probably the BN libs are not packaged correctly by your bundler and setup.

**Comment by matjazonline** [comment]
<img width="1282" alt="fixFile" src="https://user-images.githubusercontent.com/1091110/124079189-1f728a00-da49-11eb-9aa3-92c483cadcc3.png">
It's an instanceof type comparison of metadata object that fails. For dirty fix I commented out until I have a solution. This metadata is returned inside Init._loadMeta() from Init._metaFromChain() through this._rpcCore.state.getMetadata(). The metadata object is instance of type Metadata.js but the type used for comparison is from Metadata.cjs. Probably this is Angular's Webpack issue.
