### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by Fmeicheng** [polkadot-js/api#3711]
![image](https://user-images.githubusercontent.com/55660348/123927044-0e7d3680-d9bf-11eb-9866-e7ad25bd56c8.png)
![image](https://user-images.githubusercontent.com/55660348/123927172-294fab00-d9bf-11eb-8be0-c9f2fe6cc5d6.png)
There was a problem with the import

**Comment by jacogr** [comment]
There is no HTML server, this is your local config and the way you use it.
