### ISSUE TITLE
React-native supported?

### ISSUE THREAD

**Issue by Systerr** [polkadot-js/api#3719]
Hi. Does this library supports a react-native? 
I tried both react-native cli and expo and both of them generates me an error 

```javascript
error: Error: Unable to resolve module crypto from PROJECT/node_modules/scryptsy/lib/scryptSync.js: crypto could not be found within the project or in these directories:
```

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/ui/blob/master/packages/exampleReactNative/metro.config.js#L17
