### ISSUE TITLE
OriginCaller isn't registered for historical registry

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#3720]
https://github.com/polkadot-js/api/blob/9d5ab4a2d66eddbc8c435c9a7f57e78e0f5d949a/packages/api/src/base/Init.ts#L168-L171

This creates a new registry, but metadata is still using the old one.

https://github.com/polkadot-js/api/blob/9d5ab4a2d66eddbc8c435c9a7f57e78e0f5d949a/packages/types/src/create/registry.ts#L391-L392

This should set the metadata for registry but

https://github.com/polkadot-js/api/blob/9d5ab4a2d66eddbc8c435c9a7f57e78e0f5d949a/packages/metadata/src/MetadataVersioned.ts#L56

This is passing the registry for the metadata, i.e. the old one, instead of the newly created one

https://github.com/polkadot-js/api/blob/9d5ab4a2d66eddbc8c435c9a7f57e78e0f5d949a/packages/metadata/src/v13/toLatest.ts#L160

So this is registered on the old registry, not the new one

**Comment by jacogr** [comment]
The “old” registry always gets updated when used - toLatest Is called.
