### ISSUE TITLE
Can't call custom blockchain method

### ISSUE THREAD

**Issue by serezhaolshan** [polkadot-js/api#3727]
Hi, we are faced with such a problem, we have our own methods, but when we call them we get an error, although we do everything like you did it in documentation.

```
    const wsProvider = new WsProvider('wss://rpc.realis.network')
    const api = await ApiPromise.create({provider: wsProvider,
        types: {...types},
        rpc: {
            RealisGameApi: {
                transfer_from_pallet: {
                    description:'Test method',
                    params: [
                        {
                            name: 'origin',
                            type: 'mnemonic'
                        },
                        {
                            name: 'dest',
                            type: 'AccountId',
                            isOptional: true
                        },
                        {
                            name: 'value',
                            type: 'Compact<Balance>'
                        },

                    ],
                    type:'DispatchResult',
                }
            }
        }});
    let count = 0;

    const mnemonic = '***our memonic phrase***';
    const targetAccount = '***our account***';


    api.rpc.RealisGameApi.transfer_from_pallet(mnemonic, targetAccount, '10000');
}
```

Error: 
```
2021-07-05 18:04:31        METADATA: Unknown types found, no types for SubmissionIndicesOf
TypeError: api.rpc.RealisGameApi.transfer_from_pallet is not a function


```

**Comment by jacogr** [comment]
Check the `rpc_methods` output either via curl or calling `await api.rpc.rpc.methods()`. 

It should match, i.e. `api.rpc.RealisGameApi.transfer_from_pallet` should be exposed there as `RealisGameApi_transfer_from_pallet` - if it doesn't appear in there, it can't be decorated by the API and is removed.

**Comment by serezhaolshan** [comment]
> Check the `rpc_methods` output either via curl or calling `await api.rpc.rpc.methods()`.
> 
> It should match, i.e. `api.rpc.RealisGameApi.transfer_from_pallet` should be exposed there as `RealisGameApi_transfer_from_pallet` in the list - if it doesn't appear in there, it can't be decorated by the API and is removed.

So, can you tell me how can I add this method if it doesn't work like I did it?
I checked await api.rpc.rpc.methods( ), our method didn't show there

**Comment by jacogr** [comment]
I have no idea thb, the API only uses the runtimes and exposes what is on them, so between the hours in the day I have available I don't get time to play with the runtime changes myself.

**Comment by serezhaolshan** [comment]
@jacogr ping

**Comment by jacogr** [comment]
No sure why the ping here - I honestly have no idea how to configure Substrate - I don't do any Substrate development. You would need to look at how other RPC methods are exposed.

Closing, as mentioned, the API can only expose what the node exposes.
