### ISSUE TITLE
Creating Tuples via `createType`

### ISSUE THREAD

**Issue by mustermeiszer** [polkadot-js/api#3746]
Hi there, sorry for the inconvenience, as this is not really an issue of the code, but more a result of my bad understanding of it. 

I want to create the following tuple:

`(Vec<(T::AccountId, T::ProxyType)>, BalanceOf<T>)` - The frame v2 version of proxies storage.
 And transform it into:
`(BoundedVec<ProxyDefinition<T::AccountId, T::ProxyType, T::BlockNumber>,T::MaxProxies,>,BalanceOf<T>),` - the frame v3 version of proxies

I have two apis (one for v2, one for v3), so that the v2-api should be able to decode the type from a scale-encoded-byte-array.

My problem is: I am unable to give the `api.createType('INSERT_TYPE_HERE',  byte_array)` the correct type definition.

Thanks for your help!

**Comment by jacogr** [comment]
createType(‘(Vec<(AccountId, ProxyType)>, Balance)’, …)

Vec and BoundedVec is treated the same on the JD side, ie. No checking is done. (It is fine, the serialization is the same for bounded and non bounded types)

**Comment by mustermeiszer** [comment]
Ah okay, thank you for the quick reply! Typescript in Webstorm was complaining for some reason, when I tried this. But I will make it ignore then.

**Comment by jacogr** [comment]
Ok. The issue is that I probably need to remove that checking. It is meant well, but can only do what it knows of, which as simple Vec, Option, … and primitives. 

So it does add value at points when the type is simple auto-decorating the return as well, but on nested types (like here) my TS is not good enough to make it work in 100% of the cases.

**Comment by mustermeiszer** [comment]
I am closing this as all worked as described by @jacogr. Thanks again for the great lib you are providing!
