### ISSUE TITLE
TransferAll & Error of Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### ISSUE THREAD

**Issue by khelle** [polkadot-js/api#3747]
Hello, I am wondering why following snippet of code:

```
await api.tx.balances
    .transferAll(target, false)
    .signAndSend(sender, { nonce: -1 });
```

Returns me:

```
Invalid Transaction: Inability to pay some fees , e.g. account balance too low
```

I set the keep_alive flag to false, as shown before, so I would expect this call to fully drain the sender account and deduct the fee automatically from the amount being sent - basically perform a sweep of all funds from one account to another.

Instead it returns me shown error which is totally illogical to me. Why does method that supposed to transfer "ALL" funds complain about the fees? It should deal with it instead on its own.

What I am doing wrong? How to properly sweep ALL funds from one account to another, with keep_alive=fase and no dust left?

My environment:
Node 14.17.3
@polkadot/api 4.17.1

**Comment by jacogr** [comment]
The above method is correct to transfer all.

So in Substrate the fees are checked in the tx pool, before it gets to the node. So basically, the fees for the tx are deduced first as a check, then if the balance is < existential, the above error is shown.

**Comment by khelle** [comment]
@jacogr 

```
 then if the balance is < existential, the above error is shown.
 ```

Why is this checked then if I set the keep_alive to false as shown before? I am not interested in keeping accoutnt alive after the transfer that's why I set it to false. I want to send everything form one account to another and kill the sender. It should work with the snippet I shown but it complains about the fees - there is definietely some bug here.

**Comment by khelle** [comment]
Ok, after testing it thoroughly I understand where the problem lies.

If anyone is reading this in the future:
- Node checks existential balance before applying transaction, so transaction keep_alive setting does not matter at that stage
- After checks pass the transaction is applied that allow transfering all

That means in practice, (let's assume fees are 0.02DOT) transfering funds with ALWAYS fail if sender account has between 1.00 and 1.02 DOT regardless of transaction settings. This is expected behavior, but at the same time it shows how bad are fees designed in Substrate-based networks.
