### ISSUE TITLE
Getting insufficient balance error during the upgrade in blockchain.

### ISSUE THREAD

**Issue by PankajMUI** [polkadot-js/api#3750]
I have a code which is on substrate v2 which is working fine. Now i have upgraded it to v3, After that the code is working fine on local but when i am upgrading it existing blockchain then balances pallet is giving insufficient balance error during the balance transfer.

Environment:
Node: v14.17.3
@polkadot/api: 14.17.1

**Comment by jacogr** [comment]
Not sure how this relates to the API at all? This is quite possible a migration issue, i.e. the system.account structures have changes between v2 and v3 and requires migration.
