### ISSUE TITLE
METADATA: Unknown types found, no types for SignedSubmissionOf, SubmissionIndicesOf

### ISSUE THREAD

**Issue by rajqumar** [polkadot-js/api#3751]
Running latest polkadot node on westend network
I have created few APIs using polkadot.js
Keep getting this error message

**Comment by jacogr** [comment]
New types are added all the time, these were added 7 days ago in https://github.com/polkadot-js/api/pull/3717 which means it was in Monday's release.

**Comment by husonghua** [comment]
Just run `npm update` and the warning goes away.
