### ISSUE TITLE
api.at() is not support .multi 

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#3763]
I tested apiAt with different block height, found at earlier block height the `.multi` method is not supported, and somehow recent block can use this method but result alway same as query at latest block height.

test: 

```ts
//kusama network

 // block 6721189
const apiAt1 =  await api.at(`0x70070f6c1ad5b9ce3d0a09e94086e22b8d4f08a18491183de96614706bf59600`); 
//method not found
const patchedResult1 = await apiAt1.query.staking.erasStakers.multi([[2038,`DMkKL7AZw9TkNw2NaBdocmFRGUG8r8T4kdGGcB13fv2LARy`],[2038, `HAGcVQikZmEEgBBaChwjTVdwdA53Qopg2AYUtqw738C5kUq`]]);


const account = 'Faf2J6B81QwuoN7fMkvEjnpeJZLzzHLKQ2WiX2UfX2R4Z3e';
// block 8263342
const apiAt2 =  await api.at(`0x983b4c1909aa249922b6b5d7cf0362215e0e9532d31f85c4626021bbcfb6ba6c`); 
// apiAt2Result.data.free result is equal to query at latest block
const apiAt2Result = await apiAt2.query.system.account.multi([account]);
const expectedBalanceAt = await api.query.system.account.at('0x983b4c1909aa249922b6b5d7cf0362215e0e9532d31f85c4626021bbcfb6ba6c', account);
```

**Comment by jacogr** [comment]
At this point multi should always throw an error. If in the second case it does work, it is a bug. 

Emulation for it probably should be done, but underlying the RPC for at only has single queries available.

**Comment by ianhe8x** [comment]
Just point out an error that for chains support rpc.state_queryStorageAt it can be done.
We've done similar at https://github.com/subquery/subql/blob/3745b376aba6eb7916dd2841b6e3d11ca4cdf6fb/packages/node/src/indexer/api.service.ts#L375
