### ISSUE TITLE
Polkadot/node-api error with third part library (encointer-js)

### ISSUE THREAD

**Issue by KosmosKey** [polkadot-js/api#3766]
If you take a look at the encointer-js that is connected with polkadot in Readme: https://github.com/encointer/encointer-js

By the way i am using ApiPromsie.create({}) which comes from polkadot and then i connect it with a third party library. I got a message where the mean that there is something wrong with the polkadot that gives error to the thrid-part library (encointer-js).

This is the code:

`
import { options } from "@encointer/node-api";
import { EncointerWorker } from "@encointer/worker-api";

import { ApiPromise } from "@polkadot/api";
import { WsProvider } from "@polkadot/rpc-provider";

const communityId = "3LjCHdiNbNLKEtwGtBf6qHGZnfKFyjLu9v3uxVgDL35C";

const api = ApiPromise.create({
  ...options(),
  provider: new WsProvider("ws://"),
});

const worker = new EncointerWorker(communityId, { api });

console.log("Total issuance:", worker);
`

This is the polkadot error i get:
`./node_modules/@encointer/node-api/node_modules/@polkadot/api/types/index.js
Attempted import error: 'Signer' is not exported from '@polkadot/types/types'.`

Can you comment on if this is package error or if there is a solution to that ? 

What i think is that `ApiPromise` gives and `...option` which comes from the library which then gives the error to the thid part library. Let me know if you have any suggesions.

**Comment by KosmosKey** [comment]
If you want to move this issue to new repo can you send me the link of the repo ?

**Comment by jacogr** [comment]
The error comes from here - https://github.com/polkadot-js/api/blob/master/packages/api/src/types/index.ts#L25

And it is indeed exported by `@polkadot/types/types`, see here - https://github.com/polkadot-js/api/blob/master/packages/types/src/types/extrinsic.ts#L131 

If not none of the build would succeed, i.e. the type checking/linting on CI would kick it out.

My guess would be the types/api versions are mismatched. It is not a packaging error on the api/types.

**Comment by KosmosKey** [comment]
Oh ok so it's not the error that comes from `@polkadot/types/types` it's the error from the `encointer-js` package that tries to export the types, but it does not get through ?
