### ISSUE TITLE
EthereumSignature/EthTransactionSignature disparity

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3769]
On moonbeam (eth compatible) we had this error (https://github.com/polkadot-js/apps/issues/5818) whenever sending an extrinsic.

This type change solves it: https://github.com/PureStake/moonbeam/pull/598

Question: why is the type in the api
```
export interface EthTransactionSignature extends Struct {
  readonly v: u64;
  readonly r: H256;
  readonly s: H256;
}
```

but what works with Moonbeam: 

```
"EthereumSignature": {
    "r": "H256",
    "s": "H256",
    "v": "U8"
  }
```

**Comment by jacogr** [comment]
The order is important.m for serialization into SCALE. Weird though. It should match with Frontier.
