### ISSUE TITLE
How to pick out failed extrinsic from block get by `api.rpc.chain.getBlock()`

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#3781]
For example, https://westend.subscan.io/extrinsic/0x93f99888dcfd4222acf7816dbbc07573ed42c7c3bd91377edaed09165b6d9f6e
, which has a failed extrinsic. But how can I identify it? 

Currently, I try the following code but am unable to find the property which can identify the extrinsic status/result.

```
        const blockData = await api.rpc.chain.getBlock(xxxBlockHash);

        // the information for each of the contained extrinsics
        blockData.block.extrinsics.forEach((ex, index) => {

            const { isSigned, signer, meta, method: { args, method, section } } = ex; //

            let simplified_Args = JSON.parse(JSON.stringify(args))

            simplified_Args.forEach( arg => {

                arg.forEach( subTx => {
                    if(subTx.args && subTx.args.dest){
                        console.log("dest: ", subTx.args.dest.id);
                    }
                    if(subTx.args && subTx.args._remark) {
                        console.log("_remark: ", subTx.args._remark);
                    }
                })
            })
        });
```

Any hints?

Big thanks in advance!

**Comment by jacogr** [comment]
You need to match it alongside the event for the block - https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by code-brewer** [comment]
Really appreciate your help. 

I figured it out after some tries.

But be careful when choosing the event. Here, for the example: https://westend.subscan.io/extrinsic/0x93f99888dcfd4222acf7816dbbc07573ed42c7c3bd91377edaed09165b6d9f6e , should check event again utility::BatchCompleted/BatchInterrupted ,not system::ExtrinsicSuccess/ExtrinsicFailed !

**Comment by code-brewer** [comment]
As regards getting the detailed info of failure, I also did some tries.

I found the demo code of official document `https://polkadot.js.org/docs/api/cookbook/blocks/#how-do-i-determine-if-an-extrinsic-succeededfailed` section may be wrong.  I get my expected result using `dispatchInfo.isModule` and `dispatchInfo.asModule` , but failed if use `dispatchError.isModule` and `dispatchError.asModule`


```
                     const [dispatchError, dispatchInfo] = event.data;

                     let errorInfo;

                     // decode the error
                     if (dispatchInfo.isModule) {  // In document, it is dispatchError.isModule, which not work!
                         const decoded = api.registry.findMetaError(dispatchInfo.asModule);
                         errorInfo = `${decoded.section}.${decoded.name}`;
                     } else {
                         // Other, CannotLookup, BadOrigin, no extra info
                         errorInfo = dispatchError.toString();
                     }
```

**Comment by jacogr** [comment]
The batch is a funny one - it is not atomic. That means that some transactions will succeed, it basically runs until all completes or one fails. At that point the changes for preceding transactions are applied. 

In the above examples, DispatchError is only pulled from the ExteinsicFailed event. In batches (note that batchAll has a indeed atomic, batch is not), the interrupted even occurs at the point of the first extrinsic not applied. 

For the system events, since the state is changed, it is ExteinsicSuccess, however that may mean the full batch is not applied.
