### ISSUE TITLE
api.rpc.chain.subscribeNewHeads is not compiling under TypeScript

### ISSUE THREAD

**Issue by Janislav** [polkadot-js/api#3784]
## Problem

Hello everyone, 

when I try to subscribe to new blocks via. the api.rpc.chain.subscribeNewHeads function (like described in this tutorial https://polkadot.js.org/docs/api/examples/promise/listen-to-block), I get the following TS-Error during compile time:
```
TSError: ⨯ Unable to compile TypeScript:
src/services/statechainCrawler.ts:170:45 - error TS2575: No overload expects 1 arguments, but overloads do exist that expect either 0 or 2 arguments.

170     const unsubscribe = await api.rpc.chain.subscribeNewHeads((header) => {
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
171         console.log(`Chain is at block: #${header.number}`);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
176         }
    ~~~~~~~~~
177     });
```
Do you have any idea why this is not compiling? I also tried to set the type for the header argument to any and the explicit Header type defined in: @polkadot/types/interfaces/runtime/types but this also doesn't help :/.

**Comment by jacogr** [comment]
Never seen that. The API itself actually even has type-check tests for all incarnations, including the above - https://github.com/polkadot-js/api/blob/master/packages/api/src/checkTypes.manual.ts#L159-L161

**Comment by Janislav** [comment]
Interesting, when I try to copy your example I get the same error:
```
TSError: ⨯ Unable to compile TypeScript:
src/services/statechainCrawler.ts:155:25 - error TS2575: No overload expects 1 arguments, but overloads do exist that expect either 0 or 2 arguments.

155     await api.rpc.chain.subscribeNewHeads((header): void => {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
156         console.log('current header #', header.number.toNumber());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
157     });
    ~~~~~~
src/services/statechainCrawler.ts:155:44 - error TS7006: Parameter 'header' implicitly has an 'any' type.

155     await api.rpc.chain.subscribeNewHeads((header): void => {
                                               ~~~~~~

```

**Comment by jacogr** [comment]
Assuming you use ApiPromise (obviously ApiRx has very different syntax), maybe check your TS version. Not that these signatures have changed much since TS 3.x, but it is the only difference I can think of. (We generally keep TS updated to recent versions here)

**Comment by Janislav** [comment]
Upgrading TS did the trick - thank's a lot!

**Comment by jacogr** [comment]
Weird. Which version did you come from?

**Comment by Janislav** [comment]
3.9.6

**Comment by jacogr** [comment]
Ok, that would make sense - 4.x had a number of additions to make tuple definitions easier and more intuitive.
