### ISSUE TITLE
API: createType(Metadata):: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12

### ISSUE THREAD

**Issue by MilGard91** [polkadot-js/api#3787]
Hi everyone, 
I know there is already same issue https://github.com/polkadot-js/api/issues/3706 but the problem is I'm currently using version 4.17.1
and I still can't connect to a network, I get this message. Is there something I'm missing?

**Comment by jacogr** [comment]
Unlikely. The `@polkadot/types` (that `@polkadot/api` requires), has had metadata v13 support since https://github.com/polkadot-js/api/releases/tag/v4.9.1

The only way is happens is if you have an old non-match `@polkadot/types` version alongside.
