### ISSUE TITLE
Westmint events at 565/577 can not be decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#3801]
Hi, @jacogr . As the title  mentioned, please check westmint block 565/577:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestmint-rpc.polkadot.io#/explorer/query/565
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestmint-rpc.polkadot.io#/explorer/query/577

```
Unable to retrieve the specified block details. Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x00000000000302af… on : {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x0302af1bece884b2… on event: {"index":"EventId","data":"Null"}:: findMetaEvent: Unable to find Event with index 0x0302/[3,2]
```

should we fix it?

FYI, check following links for the event details which we scan days ago with the old version @polkadot/api:
https://www.statescan.io/westmint/block/565
https://www.statescan.io/westmint/block/577

**Comment by wliyongfeng** [comment]
And another thing, when I call `GenericBlock#toHex`, api#5.1.1 will produce different result with the one by the previous 5.0.1. So I guess there's no standard for the hex, and we just follow the latest one?

**Comment by jacogr** [comment]
Will check. There has been some old types than needed an update for Westend, there may have been a wrong change - this was related to heartbeats. 

The toHex should be the same if the blocks are the same.

**Comment by jacogr** [comment]
Ahhh... Westmint... interesting. (Not Westend, sorry, pre-coffee...) 

Ok, atm the API does not track the changes in types on Westmint/Statemint, so will need an addition.

**Comment by wliyongfeng** [comment]
> Ahhh... Westmint... interesting. (Not Westend, sorry, pre-coffee...)
> 
> Ok, atm the API does not track the changes in types across upgrades on Westmint/Statemint, so will need an addition to track historic types for these chains, e.g. https://github.com/polkadot-js/api/tree/master/packages/types-known/src/spec.

Sorry, not quite understand, do you mean we should add the the types manually while current `@polkadot/api` will not support them?

**Comment by jacogr** [comment]
So between versions the types change, see for instance Kusama (which is the chain tracked the longest) - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L37

So while the API has all the types, in this case it doesn't know that for an older version of the runtime to use older types, rather it only uses the latest.

**Comment by wliyongfeng** [comment]
I see. It's a little tricky for explorers development which has dependency on `@polkadot/api`. So we should init the api instance with the corresponding historical types when scan historical blocks, am I right?

**Comment by jacogr** [comment]
100%, it is quite tricky it can be adjusted simply by adding the missing overrides to the known-types and it will "just work" - the difficulty is finding which ones it actually is that creates issues...

Will scratch around a bit to see if I can figure out what historic type causes the issue.
