### ISSUE TITLE
 Hash:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### ISSUE THREAD

**Issue by lijianl** [polkadot-js/api#3803]
async function sendKSM(toAddr, amount) {
    await api.isReady
    let fromKey = key
    let keyring = new Keyring();
    let suri = fromKey;
    let pair = keyring.addFromUri(suri);
    let val = walletUtil.ksm2planck(amount);
    let transfer = await api.tx.balances.transfer(toAddr, val);
    let txhash = await transfer.signAndSend(pair, {nonce: -1}).catch(console.error);
    console.log('sendKSM->>', toAddr, amount, val, txhash.toHex());
    return txhash.toHex();
}

 RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

error when sending ksm??

**Comment by jacogr** [comment]
As the runtime error explicitly indicates with "Inability to pay some fees , e.g. account balance too low" - you cannot pay fees.

**Comment by lijianl** [comment]
how much is the existential deposit ?

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/substrate/constants#existentialdeposit-balance

**Comment by lijianl** [comment]
the balance of from key is 0.5 KSM, is this not enough to make a tx

**Comment by lijianl** [comment]
how could I get all KSM out from a KSM address if the 0.5 KSM can not be transfered
