### ISSUE TITLE
A lot of issues with return types since version 5.1.1

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#3809]
A lot of typescript issues since upgrading to 5.1.1

For example `const blockHash = await polkadotApi.rpc.chain.getBlockHash(change.block);` previously would retunr `BlockHash` type and now it's always `unknown` and a lot of similar issues where  correct types are not returned. Same with everywhere where toJSON() is called on Option<...> the return type is now AnyJson instead of whatever it suppose to be.

had to roll back to `4.17.1` Ubnless I am missing something?

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/126911664-12bd09f6-76a2-48dc-9556-0a2d990d49f1.png)

`toJSON()` is meant for JSONRPC, the AnyJSON type is correct, it can be, well, anything JSON-like.

**Comment by Yuripetusko** [comment]
@jacogr this is what I am getting too on 4.17.1 But with 5.1.1 I consistently get this

![image](https://user-images.githubusercontent.com/666169/126911770-c3106f6c-c1f2-443e-a86d-836cf6043016.png)

**Comment by Yuripetusko** [comment]
```
"@polkadot/api": "^5.1.1",
    "@polkadot/extension-dapp": "^0.39.1",
    "@polkadot/keyring": "^7.0.2",
    "@polkadot/react-identicon": "^0.84.1",
    "@polkadot/util-crypto": "^7.0.2",
    "@polkadot/x-randomvalues": "^7.0.2",
```

**Comment by Yuripetusko** [comment]
And then if I downgrade I get BlockHash as expected again 

![image](https://user-images.githubusercontent.com/666169/126911831-359f4719-3079-407e-a703-9bc3426a10a9.png)

**Comment by Yuripetusko** [comment]
```
    "@polkadot/api": "^4.17.1",
    "@polkadot/extension-dapp": "^0.38.8",
    "@polkadot/keyring": "^6.11.1",
    "@polkadot/react-identicon": "^0.83.1",
    "@polkadot/util-crypto": "^6.11.1",
    "@polkadot/x-randomvalues": "^6.11.1",
    
    ```

**Comment by jacogr** [comment]
The above screenshot is with 5.1.1. Could have something to do with an outdated TS version on your side (API always tracks latest, so the def files may be different on older), but as it stands, the types come through as expected, both inside the api repo and others such as apps.

**Comment by Yuripetusko** [comment]
Ok thanks I will keep looking to see if it's something on my side and wil lreport back

**Comment by Yuripetusko** [comment]
I am happy to report that indeed updating typescript from 4.0.5 to 4.3.5 solved all the issues
