### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED error

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3813]
Hi. I found the error when I ran the application imported polkadot-js. I used node v14.16.1 and npm 6.14.12. Is there a build dependency I need to check when I use polkadot-js v5.2.1?

```
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './packageInfo' is not defined by "exports" in /home/polkadot/node_modules/@polkadot/types-known/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/polkadot/generic-signer/node_modules/@polkadot/types/detectPackage.cjs:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/polkadot/generic-signer/node_modules/@polkadot/types/index.cjs:7:1) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by jacogr** [comment]
In the `package.json` from `@polkadot/types-known` (as installed) it is certainly there -

```
  "exports": {
    ".": {
      "require": "./index.cjs",
      "default": "./index.js"
    },
    "./bundle": {
      "require": "./bundle.cjs",
      "default": "./bundle.js"
    },
    "./bundle.d.ts": "./bundle.d.ts",
    "./chain": {
      "require": "./chain/index.cjs",
      "default": "./chain/index.js"
    },
    "./chain/index.d.ts": "./chain/index.d.ts",
    "./detectPackage": {
      "require": "./detectPackage.cjs",
      "default": "./detectPackage.js"
    },
    ...
```

So not sure what Node is saying there.

**Comment by boohyung** [comment]
my @polkadot/types-known v5.2.1 is here.

`  "exports": {
    ".": {
      "import": "./index.mjs",
      "default": "./index.js"
    },
    "./chain": {
      "import": "./chain/index.mjs",
      "default": "./chain/index.js"
    },
    "./chain/index.d.ts": "./chain/index.d.ts",
    "./index.d.ts": "./index.d.ts",
    "./modules": {
      "import": "./modules.mjs",
      "default": "./modules.js"
    },
    "./modules.d.ts": "./modules.d.ts",
    "./package-info.json": "./package-info.json",
    "./package.json": "./package.json",
    "./README.md": "./README.md",
    "./spec": {
      "import": "./spec/index.mjs",
      "default": "./spec/index.js"
    },
    "./spec/centrifuge-chain": {
      "import": "./spec/centrifuge-chain.mjs",
      "default": "./spec/centrifuge-chain.js"
    },
    "./spec/centrifuge-chain.d.ts": "./spec/centrifuge-chain.d.ts",
    "./spec/index.d.ts": "./spec/index.d.ts",
    "./spec/kusama": {
      "import": "./spec/kusama.mjs",
      "default": "./spec/kusama.js"
    },
    "./spec/kusama.d.ts": "./spec/kusama.d.ts",
    "./spec/node": {
      "import": "./spec/node.mjs",
      "default": "./spec/node.js"
    },
    "./spec/node-template": {
      "import": "./spec/node-template.mjs",
      "default": "./spec/node-template.js"
    },
    "./spec/node-template.d.ts": "./spec/node-template.d.ts",
    "./spec/node.d.ts": "./spec/node.d.ts",
    "./spec/polkadot": {
      "import": "./spec/polkadot.mjs",
      "default": "./spec/polkadot.js"
    },
    "./spec/polkadot.d.ts": "./spec/polkadot.d.ts",
    "./spec/rococo": {
      "import": "./spec/rococo.mjs",
      "default": "./spec/rococo.js"
    },
    "./spec/rococo.d.ts": "./spec/rococo.d.ts",
    "./spec/westend": {
      "import": "./spec/westend.mjs",
      "default": "./spec/westend.js"
    },
    "./spec/westend.d.ts": "./spec/westend.d.ts",
    "./upgrades": {
      "import": "./upgrades/index.mjs",
      "default": "./upgrades/index.js"
    },
    "./upgrades/index.d.ts": "./upgrades/index.d.ts",
    "./upgrades/kusama": {
      "import": "./upgrades/kusama.mjs",
      "default": "./upgrades/kusama.js"
    },
    "./upgrades/kusama.d.ts": "./upgrades/kusama.d.ts",
    "./upgrades/polkadot": {
      "import": "./upgrades/polkadot.mjs",
      "default": "./upgrades/polkadot.js"
    },
    "./upgrades/polkadot.d.ts": "./upgrades/polkadot.d.ts",
    "./upgrades/types": {
      "import": "./upgrades/types.mjs",
      "default": "./upgrades/types.js"
    },
    "./upgrades/types.d.ts": "./upgrades/types.d.ts",
    "./upgrades/westend": {
      "import": "./upgrades/westend.mjs",
      "default": "./upgrades/westend.js"
    },
    "./upgrades/westend.d.ts": "./upgrades/westend.d.ts"
  },`

**Comment by jacogr** [comment]
That is not 5.2.1... that is an older version.

**Comment by boohyung** [comment]
Is it older version? the result of npm show command is here.

```
npm show @polkadot/types-known

@polkadot/types-known@5.2.1 | Apache-2.0 | deps: 4 | versions: 1006
A JavaScript wrapper for the Polkadot JsonRPC interface
https://github.com/polkadot-js/api/tree/master/packages/types-known#readme

dist
.tarball: https://registry.npmjs.org/@polkadot/types-known/-/types-known-5.2.1.tgz
.shasum: d2b8ffad83b19255d0fa76222c518b0816f90673
.integrity: sha512-pFeEiVGs6J+E2tHXmYB/NRIzrP56kH/ymx+jw5JAfOkc0tPo5RXZwnlO31XK0bHm4iUXoIQ/Eb8j2OW4SAhz3Q==
.unpackedSize: 94.9 kB

dependencies:
@babel/runtime: ^7.14.8    @polkadot/networks: ^7.0.3 @polkadot/types: 5.2.1     @polkadot/util: ^7.0.3     

maintainers:
- jacogr <jacogr@gmail.com>
- polkadotjs <polkadotjavascript@gmail.com>

dist-tags:
beta: 5.1.2-13  **latest: 5.2.1** 
```

**Comment by boohyung** [comment]
Oh sorry to my mistake. I resolved the issue. Thanks. @jacogr
