### ISSUE TITLE
How to get txHash if `statusCb` passed in `signAndSend` function

### ISSUE THREAD

**Issue by Hayden0323** [polkadot-js/api#3814]
- `signAndSend(account: AddressOrPair, options?: Partial<SignerOptions>): SubmittableResultResult<ApiType, R>;`
- `signAndSend(account: AddressOrPair, options: Partial<SignerOptions>, statusCb?: Callback<R>): SubmittableResultSubscription<ApiType, R>;`

I can get txHash from type `SubmittableResultResult`
but I can't find txHash from statusCb

**Comment by jacogr** [comment]
```js
const tx = api.tx.balances.trasfer(...);

tx.signAndSend((result) => {
  console.log('signed hash', tx.hash);
});
```

**Comment by Hayden0323** [comment]
@jacogr Thank you!
