### ISSUE TITLE
[Feature request] Query subscriptions to finalized blocks

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/api#3824]
Looking at the docs (https://polkadot.js.org/docs/api/start/api.query.subs/#subscriptions) it's unclear whether the returned values are from finalized or new blocks. Assuming it's data from non-finalized blocks, would it be possible to also add a query subscription to finalized state?

**Comment by jacogr** [comment]
No. Subscriptions are to new heads - you have subs to finalized, see https://polkadot.js.org/docs/substrate/rpc#subscribefinalizedheads-header

**Comment by savudani8** [comment]
How would a derive help in this case? It seems like it just adds the author to the fetched block (https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-extract-the-block-author). There doesn't seem to be a `subcribeToFinalizedHeads` derive here: https://github.com/polkadot-js/api/tree/master/packages/api-derive/src/chain

**Comment by jacogr** [comment]
Yes, you are right - I though there was an extended subscribe to finalized heads/blocks.
