### ISSUE TITLE
What @polkadot/type do i need to use to encode (toU8a) a MarketID

### ISSUE THREAD

**Issue by KosmosKey** [polkadot-js/api#3828]
If you see in this code:
`const market = api.createType("MarketId", "BTC");` 

For some reason i will not be able to make my own types inside `ApiPromise.create({types: {
      MarketId: "string",
}})`

So just wondering if there is a way i can encode a market value when using `api.createType()`. 

If you have any question just give me a sound.

**Comment by jacogr** [comment]
`MarketId: "Text"`

**Comment by KosmosKey** [comment]
Hey @jacogr is there a way to create your own custom types for example ?` api.createType("customType", "BTC`. As i have seen in the documentation for polkadot type creation there is not a way to define your own custom types.

Another question. If i want to have a type creation + decode `(toU8a) with params for example `params: {Object1:1, Object:2}` is there a way to do that ? 

Because in rust side we are taking a spesific params and encoding them.

If any questions give me a sound.

**Comment by jacogr** [comment]
```
api.createType('{"param1":"u32", "param2":"u32"}', { param1: 1, param2: 2 })
```

Or enum -

```
api.createType('(Balance, Text)', [1234, 'hello world'])
```

**Comment by jacogr** [comment]
So the issue is that createType only type checks the primitives (and some wrappers thereof). TS cannot quite interpret the string you are passing and magically construct the type for static checking from it. I'm sure it is possible for somebody that inside out understands the TS system.

There are 2 solutions -

1. ignore it (or case it to something simple like `as 'u32'`
2. use api.registry.createTypeUnsafe(<string>, ...) (Note: params here are always passed an an array, i.e. `[{ p1: 1, p2: 2 }]`) - this form has no TS type interpolation

**Comment by KosmosKey** [comment]
Yeah right. I have a last question. Is there any way to define like own custom type / interface inside the `ApiPromise()` ?

Like this:
` const api = await ApiPromise.create({
    provider: wsProvider,

    ...types,
  });`

types: 
`
export default {
  types: {
    AssetId: {
      _enum: {
        BTC: null,
        USD: null,
      },
    },
    MarketId: {
      base: "AssetId",
      quote: "AssetId",
    },
  },
};

`

**Comment by jacogr** [comment]
The above will work, yes, as typed.

```js
const api = await ApiPromise.create({ types: { MarketId: { ... } } });

api.createType('MarketId', ...)
```

**Comment by KosmosKey** [comment]
Alright i see, but one problem is that i get errors, but i should just ignore them ? 

Or do i need to run ts-node scripts to not get errors ? 

Like in this link: https://polkadot.js.org/docs/api/examples/promise/typegen/

**Comment by jacogr** [comment]
If you want TS definitions for your types, you will need to generate them, as per the above.

**Comment by KosmosKey** [comment]
Hey @jacogr i tried to run this script on my local to generate types `"generate:defs": "ts-node --skip-project node_modules/.bin/polkadot-types-from-defs --package polkadexjs/interfaces --input ./src/interfaces",`


But got this error:
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)       
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at main (C:\Users\KosmosKey\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:330:12)
    at Object.<anonymous> (C:\Users\KosmosKey\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:477:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
```

**Comment by jacogr** [comment]
In this case, nothing that I can do - it is not thrown by these libs. 

I did see a similar issue on the Jest repo, unrelated to this, same error though that is due to the fact that a shell script is executed on Windows. The above would match, wherever `${dirname "${echo ...` comes from, it is not Windows syntax.

**Comment by KosmosKey** [comment]
Alright i see. Can i try this on MacOS?

**Comment by KosmosKey** [comment]
Decode does not work when i run this script:

`api.createType("Option<AccountId>", publicKey)`

Here is the public key: 
```
const keyring = new Keyring({ type: "sr25519", ss58Format: 2 });
const publicKey = keyring.addFromUri("//Alice").publicKey;
  ```
