### ISSUE TITLE
still got the probelm that  SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by chenxing-luckysky** [polkadot-js/api#3832]
env:
Node: 14.15.4
"jest": "^27.0.6",
"@polkadot/api": "^5.3.1",
with javaScript

 when I use 
         const { Keyring } = require('@polkadot/api');
it gives

 SyntaxError: Cannot use import statement outside a module

       9 | const bs58check = require('bs58check');
      10 | const p2pkh_modified= require('../constants/p2pkh_modified.js');
    > 11 | const { Keyring } = require('@polkadot/api');
         |                     ^
 and in my packae.json:    "type": "commonjs",
I read other issue, I didn't find a good solution for it, can you help me figure it out! thank you!

**Comment by Yuripetusko** [comment]
node 14+ supports esm, why don't you use `import` instead? And even better if you use simple tsconfig as a transpiler to use es6 features

**Comment by jacogr** [comment]
If you are using Jest (which has WIP esm support), you probably need the following - https://github.com/polkadot-js/api/blob/master/jest.config.cjs#L31

**Comment by Yuripetusko** [comment]
You can also check how we use both polkadot.js api and jest and esm here: https://github.com/rmrk-team/rmrk-tools/blob/master/jest.config.js
