### ISSUE TITLE
calling RPC with enum parameter failed

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#3833]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura.kusama.elara.patract.io#/js

```
let a = await api.rpc.oracle.getValue('Acala', {Token: 'KSM'})
console.log(a)
```

Getting error
```
2021-08-03 11:10:10        RPC-CORE: getValue(providerId: RpcDataProviderId, key: OracleKey, at?: BlockHash): Option<TimestampedValue>:: -32602: Invalid params: unknown variant `token`, expected one of `Token`, `DexShare`, `Erc20`, `ChainSafe`. polkadot.02.3b42db6e.js:1:205117
    m https://polkadot.js.org/apps/polkadot.02.3b42db6e.js:1
    error https://polkadot.js.org/apps/polkadot.02.3b42db6e.js:1
    Gi https://polkadot.js.org/apps/polkadot.01.a45f09ae.js:1
    a https://polkadot.js.org/apps/polkadot.01.a45f09ae.js:1
```

The default JSON serialization format is not matching on the Rust side.

Change to `Token` fixes the issue

```
curl -H 'Content-Type: application/json' --data '{"id":3,"jsonrpc":"2.0","method":"oracle_getValue","params":["Acala",{"Token":"KSM"}]}' https://karura.kusama.elara.patract.io/
```

**Comment by jacogr** [comment]
Depends on whether serde is setup with camelCase or not - in substrate the default is indeed camelCase, see for instance https://github.com/paritytech/substrate/blob/master/frame/support/src/weights.rs#L222-L243

Another example of the enum that is passed through to `author_removeExtrinsic` - https://github.com/paritytech/substrate/blob/master/client/rpc-api/src/author/hash.rs#L26-L34

In this case the api cannot detect how the node is supposed to do it, so it just follows the standards set by substrate.

**Comment by xlc** [comment]
That makes sense. Will update Rust side instead.
