### ISSUE TITLE
typegen prioritizes polkadot types over extended types

### ISSUE THREAD

**Issue by amphineko** [polkadot-js/api#3839]
I'm attempting to use `@polkadot/typegen` to generate TypeScript typings.

Recently Polkadot introduces a new type called `ChainId` which is also present on our extended types.

I have tried to use `typesAlias` to override in specific modules:

```typescript
{
    types: khalaTypes,
    typesAlias: {
        bridgeTransfer: {
            ChainId: 'u8',
        },
        chainBridge: {
            ChainId: 'u8',
        },
    },
}
```

However, `typegen` still want to use Polkadot's `u32` instead and results in the following error:

```
Error: Command failed with exit code 1: npx tsc --build
src/interfaces/augment-types.ts(83,33): error TS2344: Type 'ChainId' does not satisfy the constraint 'CompactEncodable'.
  Type 'U8aFixed' is missing the following properties from type 'CompactEncodable': toBigInt, toBn, toNumber
    at makeError (C:\Users\amphineko\Devcat\***\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\amphineko\Devcat\***\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Dive into the generated `augment-types.ts`, `ChainId` is still imported from `@polkadot` only.

**Comment by jacogr** [comment]
I am splitting the default augmented types out in the next release, ie. They will become optional, unless the package is installed.

**Comment by amphineko** [comment]
The error was thrown in `augment-types.ts`.

```typescript
declare module '@polkadot/types/types/registry' {
  export interface InterfaceTypes {
    /* ... */

    'Compact<ChainId>': Compact<ChainId>; 
    // Type 'ChainId' does not satisfy the constraint 'CompactEncodable'.
    //   Type 'U8aFixed' is missing the following properties from type 'CompactEncodable': toBigInt, toBn, toNumber ts(2344)

    /* ... */
  }
}
```

I think it's probably a type overlap that caused this error. Our own `ChainId` is an alias of `u8` which should extend BN. But `typegen` resolves it to the `ChainId` from Polkadot.

How about TypeScript namespaces or generating type names with module prefixes?

**Comment by jacogr** [comment]
Since you did add the alias definitions, the issue here is that you still have the `ChainId: 'u8'` in your definition.

As for namespacing/prefix, with the v14 metadata (where the types are generated from the metadata itself), it indeed does that, see eg. https://github.com/polkadot-js/api/blob/422337a3f01790f725eb9b2c3de5e48e65d5e930/packages/types/src/augment/lookup/polkadot.ts
