### ISSUE TITLE
Using caret (^) for dependencies causes unexpected issues

### ISSUE THREAD

**Issue by monitz87** [polkadot-js/api#3852]
Example:

My team is writing a library `A` that depends on `@polkadot/api`, and in turn, we're writing an application `B` that depends on that `A` library. We recently upgraded `A` to use `@polkadot/api` version 5.1.1 (which depends on `@polkadot/keyring` ^7.0.2, which depends on `@polkadot/util` 7.0.2). Before `B` updated its `A` dependency, `@polkadot/keyring` 7.1.1 was released (which depends on `@polkadot/util` 7.1.1). When `B` installed the latest version of `A`, the keyring dependency got resolved to 7.1.1, which results in yarn installing both `@polkadot/util` 7.0.2 AND 7.1.1, resulting in this warning

```
@polkadot/util has multiple versions, ensure that there is only one installed.
      Either remove and explicitly install matching versions or dedupe using your package manager.
```

The only ways I can think of fixing this on my end are:
- Upgrading all the polkadot dependencies in `A`, publishing a new version, and installing it in `B`. This will only last until the next keyring minor version, and then any future packages that install `A` it are going to run into the same issue
- Manipulating `B`'s lockfile, which is never pretty. Also, any future packages that install `A` will have to do the same
- Hacking some sort of postinstall script in `A` that deletes some installed versions of polkadot packages so that only the one that matches the api version remains (very ugly as well)

I've personally never been a fan of using version ranges for dependencies. It's always bound to lead to unpredictable and uncontrollable behavior.

**Comment by jacogr** [comment]
The api/util always depends on the latest released.

**Comment by monitz87** [comment]
What I'm saying is that dependencies within the api and other packages should be fixed version. Or at least, if you're going to use carets, use them all around. Otherwise you get this:

```
"@polkadot/api@5.1.1":
  version "5.1.1"
  dependencies:    
    "@polkadot/keyring" "^7.0.2"
    "@polkadot/util" "^7.0.2"
    "@polkadot/util-crypto" "^7.0.2"

"@polkadot/keyring@^7.0.2":
  version "7.1.1"
  dependencies:
    "@polkadot/util" "7.1.1"
    "@polkadot/util-crypto" "7.1.1"

"@polkadot/util-crypto@^7.0.2":
  version "7.0.2"
  dependencies:
    "@polkadot/util" "7.0.2"

"@polkadot/util-crypto@7.1.1":
  version "7.1.1"
  dependencies:
    "@polkadot/util" "7.1.1"

"@polkadot/util@7.0.2", "@polkadot/util@^7.0.2":
  version "7.0.2"  

"@polkadot/util@7.1.1":
  version "7.1.1"
```
I trimmed the fat away from the lockfile so it would be more evident.

As you can see, you get multiple versions of the same package, and that results in the aforementioned warning. I think the fact that the order in which dependencies are resolved has an effect on which versions get installed is a very good reason to avoid using ^ (or use it everywhere)

**Comment by jacogr** [comment]
They are used all around -

- util will reference the latest with ^
- api will always reference the latest with ^

In this case you had a version of the API that is outdated and a version of the common utils that is new.

**Comment by monitz87** [comment]
`A` is using api 5.1.1 and utils 7.0.2, not 7.1.1

I created a repo that reproduces the issue minimally
https://github.com/monitz87/carets-suck

It depends on api 5.1.1, utils 7.0.2 and has a script that creates an api instance, which will throw the mismatching version warnings.

To reproduce:
- clone the repo
- `yarn reproduce` (this will clear all dependencies and lockfile, install everything and then run the script)

You will see the warnings in the console and can check the lockfille to see the dependency resolutions

**Comment by jacogr** [comment]
yarn installs the latest, as per lockfile. Don’t know what resolution you expect here, there are no breaking changes between 7.x - only new standalone packages. 

If you want to fix dependencies to not upgrade, then use yarn resolutions.

**Comment by monitz87** [comment]
I didn't know about resolutions. That might work. I still stand by my original thought. Carets in package.json do more harm than good IMO

**Comment by jacogr** [comment]
You have 2 choices -

- accept the version that yarn provides (the API ensure there are no breaking change since the projects are under the same umbrella- and actually the common repo is very stable)
- don’t install your own alongside, use what yarn pulls in via the api
- use resolutions

internal, same repo deps are without a ^ since exact versions are required. Outside of that, some elbow grease required. For each person installing their own, there are a person not doing it. Dammed if you do, damned if you don’t.
