### ISSUE TITLE
Failed to submit transactions after runtime upgrade

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#3853]
A few of our servers can no longer able to submit transaction after an upgrade of Karura. I think the cause is some old metadata was used to construct the transaction. Restart the server fixes the issue.

The same issue happens on polkadot apps as well. It no longer automatically refetch metadata after upgrade. It still displays the old spec version. We need to manually refresh the page.

Also got a few error reports from exchanges with similar issue.

**Comment by jacogr** [comment]
Are we 100% sure that subscribe_runtimeVersion works on parachains? In both cases that is what gets used and in neither case has the logic for that changed. 

As I recall the subscription monitors :code and when that updates sends the updated version. Not convinced that is valid in this case.

**Comment by xlc** [comment]
Let me do some test locally first.

**Comment by jacogr** [comment]
Closed by https://github.com/paritytech/substrate/pull/9617
