### ISSUE TITLE
Reporting erroneous value for ValidatorCount

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/api#386]
I am using a local `substrate --dev`.
Issuing the following request:
`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "state_getStorage", "params": ["0x2dce29f1a768624dc5343063cb77f77d"]}' $HOST | jq`

gives me the correct value:
```
{
  "jsonrpc": "2.0",
  "result": "0x02000000",
  "id": 1
}
```

`0x020000` = 2

Using the API however, I get 0. The UI (https://polkadot.js.org/apps/next/#/staking) also shows 0:
![image](https://user-images.githubusercontent.com/738724/48204326-ce7a6880-e369-11e8-8f0c-c958348417df.png)

**Comment by jacogr** [comment]
Strangely enough on BBQ, `0x07000000` does show correctly as 7, however `0x02000000` is broken in both the UI and storage tabs.
