### ISSUE TITLE
ExhaustsResources issue

### ISSUE THREAD

**Issue by MrRakhim** [polkadot-js/api#3862]
Getting an error " Transaction would exhaust the block limits ".

I am building a transaction and it's signer payload as follows

"`transaction` variable is batch tx which contains 5 payoutStakers tx, so it might request a bit more resources than as usual"
"`nonce` is account's nonce"

`const signer = api.createType('SignerPayload', {`
`      method: transaction,`
`	nonce,`
`	genesisHash: api.genesisHash,`
`	blockHash: api.genesisHash,`
`	runtimeVersion: api.runtimeVersion,`
`	version: api.extrinsicVersion,`
`	tip: BigNumber(tip).times(DOT_DECIMAL_PLACES).toNumber()`
`});`

How do you think, how can I avoid that error

---------
If I change the blockHash field to last block's hash, I get an error "Invalid tx" (I sign the txs offline on client-part).

**Comment by citadeldao** [comment]
@jacogr the same problem

**Comment by OndasAlikhan** [comment]
@jacogr also have this problem

**Comment by victor-dm-black** [comment]
@jacogr I have the same problem.

**Comment by jacogr** [comment]
Use less transactions in the batch.

**Comment by jacogr** [comment]
And please don’t cc me on issue that are not API related. Spam issues will be closed going forward.
