### ISSUE TITLE
RPC-CORE: accountNextIndex(accountId: AccountId): Index:: -32602: Invalid params: UnknownVersion.

### ISSUE THREAD

**Issue by GopherJ** [polkadot-js/api#3864]
recently we start to get this issue using @polkadot/api 5.2.1

**Comment by jacogr** [comment]
That is from the node. Please check in the Rust code what results in that error. My guess is an outdated native vs on-chain client version.

**Comment by GopherJ** [comment]
> That is from the node. Please check in the Rust code what results in that error. My guess is an outdated native vs on-chain client version.

the client is the latest build from my fork https://github.com/GopherJ/parallel/commit/6507587b74ce3346c53409bb77d3fb3672d66533

**Comment by jacogr** [comment]
See https://github.com/paritytech/substrate/blob/e0d13b58e1281514866e93a04a7232c05f79da45/primitives/core/src/crypto.rs#L208-L209

Probably means you are using an ss58 prefix that is not in the registry, https://github.com/paritytech/substrate/blob/master/ss58-registry.json

**Comment by GopherJ** [comment]
@jacogr great thanks on your help, we have registered our prefixes here: https://github.com/paritytech/substrate/blob/master/ss58-registry.json#L545-L551 and https://github.com/paritytech/substrate/blob/master/ss58-registry.json#L562-L570

but they are not in https://github.com/paritytech/substrate/blob/polkadot-v0.9.8/ss58-registry.json yet, I'll try to upgrade to see if it helps

**Comment by GopherJ** [comment]
thanks it's fixed now
