### ISSUE TITLE
@polkadot/types-known: getSpecTypes should have Moonbeam types

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3867]
## Context
So one of our partner was trying to use `txwrapper-substrate` to make transaction with Moonbeam and got a typing error that I was able to reproduce in a test: https://github.com/PureStake/moonbeam/pull/676

![](https://files.slack.com/files-pri/TE2C53UGN-F02BFUEEPNU/screenshot_2021-08-10_at_18.22.45.png)

This is strange, because the `getSpecTypes` function used in https://github.com/paritytech/txwrapper-core/blob/d325b0b99de99699b5ad926c13f1e59fc0fd2cd0/packages/txwrapper-polkadot/src/index.ts#L97 should be able to fetch types correctly.

When looking closer at the `types-known` code, I realized the types were not imported neither form `apps-config` nor `moonbeam-types-bundle`

## Solution
I see that centrifuge has added their own types to `types-unkown`. Should Moonbeam do the same and import `moonbeam-types-bundle` ?
Or should txwrapper-polkadot be modified to use apps-config types in its getRegistry function ?

**Comment by jacogr** [comment]
No. The centrifuge types are in the wrong place, sadly pre apps-config. Like sidecar, txwrapper should use apps-config.

**Comment by joelamouche** [comment]
Makes sens...
But when I use getRistry from txwrapper-registry, I get this typing error:
```
Type 'import("/Users/antoineestienne/GitHubRepo/moonbeam/tests/node_modules/@polkadot/types/create/registry").TypeRegistry' is not assignable to type 'import("/Users/antoineestienne/GitHubRepo/moonbeam/tests/node_modules/@substrate/txwrapper-core/node_modules/@polkadot/types/create/registry").TypeRegistry'.
  Property '#private' in type 'TypeRegistry' refers to a different member that cannot be accessed from within type 'TypeRegistry'.ts(2322)

**Comment by jacogr** [comment]
No idea, have no insight into that repo. I would suggest asking there.
