### ISSUE TITLE
Error decoding justifications: Could not decode `Justifications.0`

### ISSUE THREAD

**Issue by migueldingli1997** [polkadot-js/api#3881]
I am trying to query block height `4420096` using version `5.5.1` of both `@polkadot/api` and `@polkadot/api-derive`. Unfortunately I'm getting this error:

```
RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: -32603: Unknown error occurred: Client, Backend, Error decoding justifications: Could not decode `Justifications.0`:\n\tNot enough data to decode vector\n
```
when running: `api.rpc.chain.getBlock(blockHash)`

The error does not show up for all of the next blocks but shows up again for some future block heights including:
- `4420608`
- `4421120`
- `4421632`
- `4422144`
- ...and so on

Should I perhaps be running a different version of the API?

**Comment by jacogr** [comment]
This is from the node itself - `-32603: Unknown error occurred: ...` - not on the API

**Comment by migueldingli1997** [comment]
Thanks for the reply @jacogr. Do you have a clue what the problem with the node might be? In any case I intend to close the issue since it is not from the API side.

**Comment by jacogr** [comment]
It could be that the node is running with native execution an on this specific block there is a mismatch, i.e. the native doesn't match with the runtime.

The above is a guess :) It tries to decode the data received from the chain but fails to do so. Not sure as to the "why".

**Comment by migueldingli1997** [comment]
Thank you @jacogr
