### ISSUE TITLE
Support enum with string and Record

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#3893]
In the RegistryType definition, enum are defined like that:

```
_enum: string[] | Record<string, number> | Record<string, string | null>;
```

So how would we type something like that:

```
pub enum NominatorStatus {
		/// Active with no scheduled exit
		Active,
		/// Schedule exit to revoke all ongoing nominations
		Leaving(RoundIndex),
	}
```
?

I assume something like that:
```
_enum: { Active: null, Leaving: "RoundIndex" }
```

But then it means getting `status: { Active: null }` when it is active, which is a little bit ugly

**Comment by jacogr** [comment]
Active: ‘Null’

But yes, the reast is all ok. 

This won’t change.

**Comment by joelamouche** [comment]
Looks cool! So will this PR turn `status: { Active: null }` into a different result?

**Comment by jacogr** [comment]
Will be status: Active in that case.

**Comment by joelamouche** [comment]
Awesome!
