### ISSUE TITLE
Seeing error instead of wallet signature dialog

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/api#3906]
I have a `rococo-local` relay chain to which I connected the `interbtc-parachain` (the setup is [here](https://github.com/interlay/interbtc/blob/master/docs/rococo.md#rococo---local-automated-setup) for reference. 

![Screenshot from 2021-08-26 17-55-04](https://user-images.githubusercontent.com/23065004/131004143-af1ec206-b15d-4578-b41a-fd8ef5f43e9d.png)

In `polkadot-apps`, I can submit signed extrinsics to the relay chain, but not to the parachain. After clicking the `Sign and Submit` button, instead of being shown the wallet signature dialog, I get this error:
![Screenshot from 2021-08-26 17-57-53](https://user-images.githubusercontent.com/23065004/131004499-9e68148d-d9a6-4d55-a254-a3a08780be5e.png)

In the console, the error is logged multiple times:
```
TypeError: e.query[r] is undefined
...
DRR: e.query[r] is undefined
```

**Comment by jacogr** [comment]
For interbtc, the `instances` option to the API define where balances live. So it would seem in this case it is not applied?

https://github.com/interlay/interbtc-types/blob/master/definitions.json#L499-L504

**Comment by gregdhill** [comment]
@jacogr I think that has solved the first issue but we now see the following error:
```
Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000010000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000010000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (100 bytes)
```

**Comment by jacogr** [comment]
The AccountInfo type is incorrect. If I had to guess, it may be an older structure without sufficients.

**Comment by gregdhill** [comment]
We use the overridden type specified in `orml`, could that be the issue? https://github.com/open-web3-stack/open-runtime-module-library/blob/5babe0b71cf60538ca23d41231f9558816c52ae9/tokens/src/lib.rs#L126

**Comment by jacogr** [comment]
Since `AccountData` is in the `AccountInfo` struct, yes, if changed, it needs to be specified.

**Comment by jacogr** [comment]
Closing, answered.
