### ISSUE TITLE
another SyntaxError: Cannot use import statement outside a module jest + polkadot

### ISSUE THREAD

**Issue by woss** [polkadot-js/api#3923]
i'm raising this again since other issues found [here](https://github.com/polkadot-js/api/issues?q=SyntaxError%3A+Cannot+use+import+statement+outside+a+module) are locked and you cannot comment. 

i want to link this https://github.com/polkadot-js/api/issues/3313 too which I really don't get, why not ship commonjs and save ALL of the trouble reporting you the errors, and being forced to rewrite out solutions just to suit changes you make? 

I've been complaining about this since April 22nd and tried to provide you all the proof that this approach at this stage was a bad move. 

Here is something you can look into [here](https://github.com/woss/rushstack-jest-polkadot). Many people use the [rushstack ](https://github.com/microsoft/rushstack) but `polkadot/*` are completely broken when testing.

**Comment by woss** [comment]
and yes, i agree ESM is the future, but ATM is the `experimental future` :)

**Comment by jacogr** [comment]
Used in all polkadot-js projects - https://github.com/polkadot-js/dev/blob/master/packages/dev/config/eslint.cjs#L7

Yes, I agree that Jest no supporting ESM _properly_, aka without workarounds, is disappointing, but that doesn't mean anything here will change. Don't complain here, this is not changing - put pressure on the relevant tooling.

And no, it is not experimental. It is the JS standard. Various implementation may be experimental, but ESM is not.

**Comment by woss** [comment]
right. The only part of rushstack you are using is eslint, which is well, not related to the jest and inclusion of this lib. 

I'll keep the repo i shared, in case I find a way to properly include this lib so others can benefit. thanks for the answers and understanding.
