### ISSUE TITLE
Why do errors have the cut block/transaction hash?

### ISSUE THREAD

**Issue by bgodlin** [polkadot-js/api#3924]
The example of an error:

`failed to fetch block Error: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x00030000000a033b… on :`

With the cut id it makes it harder to debug. Are there any specific reasons for such logging approach?

**Comment by jacogr** [comment]
It shows exactly at which point of the decoding  it fails, not the full data.

**Comment by bgodlin** [comment]
Is there any way to identify based on the current logs the block  where the error occurred?
