### ISSUE TITLE
Block details page with xcm related events is broken with `createType` error

### ISSUE THREAD

**Issue by shaunxw** [polkadot-js/api#3941]
The latest polkadotjs seems not be compatible with v0.9.9-1 runtimes, which are using XCM v0. The error is as below:

> Unable to retrieve the specified block details. Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x0001000000160209… on : {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x160209ba14a885f5… on event: {"index":"EventId","data":"Null"}:: Struct: failed on data: (MessageId,Outcome):: decodeU8a: failed at 0x01801a0600000000… on : {"_enum":{"Complete":"Weight","Incomplete":"(Weight,XcmErrorV0)","Error":"XcmErrorV0"}}:: decodeU8a: failed at 0x1a00000100000000… on : {"_enum":{"Undefined":"Null","Overflow":"Null","Unimplemented":"Null","UnhandledXcmVersion":"Null","UnhandledXcmMessage":"Null","UnhandledEffect":"Null","EscalationOfPrivilege":"Null","UntrustedReserveLocation":"Null","UntrustedTeleportLocation":"Null","DestinationBufferOverflow":"Null","SendFailed":"Null","CannotReachDestination":"(MultiLocation,Xcm)","MultiLocationFull":"Null","FailedToDecode":"Null","BadOrigin":"Null","ExceedsMaxMessageSize":"Null","FailedToTransactAsset":"Null","WeightLimitReached":"Weight","Wildcard":"Null","TooMuchWeightRequired":"Null","NotHoldingFees":"Null","WeightNotComputable":"Null","Barrier":"Null","NotWithdrawable":"Null","LocationCannotHold":"Null","TooExpensive":"Null"}}:: Unable to create Enum via index 26, in Undefined, Overflow, Unimplemented, UnhandledXcmVersion, UnhandledXcmMessage, UnhandledEffect, EscalationOfPrivilege, UntrustedReserveLocation, UntrustedTeleportLocation, DestinationBufferOverflow, SendFailed, CannotReachDestination, MultiLocationFull, FailedToDecode, BadOrigin, ExceedsMaxMessageSize, FailedToTransactAsset, WeightLimitReached, Wildcard, TooMuchWeightRequired, NotHoldingFees, WeightNotComputable, Barrier, NotWithdrawable, LocationCannotHold, TooExpensive

**Comment by jacogr** [comment]
It defaults to 1, most probably will be adjusted to 2. 

For older apply overrides, eg. Kusama does the following, https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L196

**Comment by shaunxw** [comment]
This issue is on rococo local, build from `v0.9.9-1`.
