### ISSUE TITLE
ApiPromise.create fails on seemingly identical typesBundles

### ISSUE THREAD

**Issue by brettkolodny** [polkadot-js/api#3942]
When trying to create an API instance with a `typesBundle` the API fails to initialize, but creating an API instance with a seemingly identical `typesBundle` succeeds.

Example: https://gist.github.com/brettkolodny/11d8a326dd2530cf134469040c8c11af

**Comment by jacogr** [comment]
It defaults to 1, most probably will be adjusted to 2. 

For older apply overrides, eg. Kusama does the following, https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L196

**Comment by brettkolodny** [comment]
I've figured out the issue. `JSON.stringify` changes:
```
"minmax": [
  720,
  undefined
],
```
to 
```
"minmax": [
  720,
  null
],
```
Which then doesn't work.

**Comment by jacogr** [comment]
It is not actual "JSON" https://github.com/polkadot-js/api/blob/master/packages/types-known/src/bundle.ts#L25-L26

If you want a JSON-like then I would suggest specifying a very large max.
