### ISSUE TITLE
Data Retrieval Questions

### ISSUE THREAD

**Issue by dillu24** [polkadot-js/api#3945]
I have some questions on how some data can be retrieved by the api or api-derive:

1. I am trying to find an easy way how to query the number of blocks authored in a past session. The `imOnline.authoredBlocks` function retrieves 0 for past sessions, so I thought to retrieve blocks and use `derive.getBlock` to get the block author at every block. But, I need a way of mapping the block to the session it was created in. Is there a way of retrieving the session ID a block has been authored in? 

2. I am trying to check whether it is possible to get the amount bonded to a waiting validator. From `api.derive.staking.waitingInfo` I can get info about the waiting validators, though I cannot get the amount bonded for each. Is there any way to get this piece of information?

3. Is there a constant in the polkadot js API which keeps track of the max number of eras a payout can be unclaimed for?

4. Is there a constant in the polkadot js API which keeps track of the HISTORY_DEPTH eras?

5. `api.rpc.system.syncState` returns `{startingBlock: 6480353, currentBlock: 6823825, highestBlock: 6823825}`, are `highestBlock` and `currentBlock` the `sync_target height` and `best block` height respectively? I am looking to get the `sync_target`, `best_block` and `finalized_height` using the API.

6. What will `api.query.grandpa.stalled` return if the grandpa algorithm stalls? In the docs there is written that it will return True, but the return type is defined as `Option<(blockNumber, blockNumber)>`

**Comment by jacogr** [comment]
The API only exposes what is on-chain - it doesn’t really decide information (apart from derives, not covered here)

for Substrate specific usage, I would suggest to refer to the Substrate docs and Code.
