### ISSUE TITLE
Balance doesn't show tokens locked in a crowdloan, is this a design decision?

### ISSUE THREAD

**Issue by frmz** [polkadot-js/api#3958]
Right now i need to parse all the extrinsics to get a list of contributions for a given address to CLs, this is quite annoying because then i need to match the destination address to the active CL.

Why is the balance endpoint not returning crowdloans partecipations as locked balance?

**Comment by jacogr** [comment]
It is not a locked balance, it does not appear under locks. 

To get the values you would need to get the entries or the crowdloan storage and map them to your accounts. (Since it means retrieving the full map, this is not a quick operation)

**Comment by frmz** [comment]
> It is not a locked balance, it does not appear under locks.

I would disagree with this statement, how is it not locked? the balance is not usable for X weeks depending on the CL, so its actually locked but still part of the wallet, logically how is this different from a nomination bond?

> To get the values you would need to get the entries or the crowdloan storage and map them to your accounts. (Since it means retrieving the full map, this is not a quick operation)

Yeah that's what i am doing, which is awful, from a developer and user experience i think it would be nice to see exactly how many KSM/DOT he has regardless of where, Kraken for example does this well and shows your funds including those assets

**Comment by jacogr** [comment]
There is a huge difference - a locked balance is a Substrate concept which means that a locks is placed on the amount and it shows up in the account system storage. This is not the case for crowdloans. The API (as this issue was logged), only places a thin wrapper around the on-chain storage, nothing more.

There is no centralized database - like Kraken has. All contributions has to be loaded from the chain. See https://github.com/polkadot-js/apps/issues/6041#issuecomment-909181258 for details.

**Comment by frmz** [comment]
> There is a huge difference - a locked balance is a Substrate concept which means that a locks is placed on the amount and it shows up in the account system storage. This is not the case for crowdloans - it is a seperate module with child trie storage, independent of balances. The API (where this issue was logged), only places a thin wrapper around the on-chain storage, nothing more, it doesn't re-write chain logic.

I get it its different but from a developer point of view this is massively complex, is an on-chain solution being considered? I see the issue on the apps side but i guess solving it there would not give much benefit to the devs

**Comment by jacogr** [comment]
The data is on-chain, just query the child trie with the paraId (which is what the `api.derive.cowdloan.contributions(paraId)` does as well - on a per parachain basis)

**Comment by frmz** [comment]
Will check the onwContributions derive then, the other methods require me to have a list of active auctions and i wasnt able to get that information either.

**Comment by jacogr** [comment]
Closing. Not API related with locking.
