### ISSUE TITLE
FATAL: Unable to initialize the API: disconnected from wss://pub.elara.patract.io/kusama: 1006:: Abnormal Closure

### ISSUE THREAD

**Issue by Edu260594** [polkadot-js/api#3960]
FATAL: Unable to initialize the API: disconnected from wss://pub.elara.patract.io/kusama: 1006:: Abnormal Closure

Anybody could help me with this message when i try to connect POLKADOT JS apps wallet (hosted) ???

I try change to mobile wifi and reinstall polkadot extension on google chrome, but it doesn´t work.

Thanks.

**Comment by jacogr** [comment]
Switch endpoints. The specific centralized RPC provider is dropping connections.

**Comment by jacogr** [comment]
cc @yuelipeng

**Comment by Edu260594** [comment]
> Switch endpoints. The specific centralized RPC provider is dropping connections.

Thanks jacogr, but i don´t know how to switch endpoints. Could you tell me somothing about this ? How can i switch endpoints?

Thanks again.

**Comment by jacogr** [comment]
Click on the top left where it says "Polkadot" with the logo. It allows you to select the endpoint or chain.

**Comment by Edu260594** [comment]
> Click on the top left where it says "Kusama" with the logo. It allows you to select the endpoint or chain. Endpoints are Parity/OnFinality/Elara/Dwellir for Kusama.

Thanks Jaco, but I try with all options in KUSAMA and all of them give me an error:

**PARITY:** FATAL: Unable to initialize the API: disconnected from wss://kusama-rpc.polkadot.io: 1006:: Abnormal Closure
**ONFINALITY:** FATAL: Unable to initialize the API: disconnected from wss://kusama.api.onfinality.io/public-ws: 1006:: Abnormal Closure
**PATRAC ELARA:** FATAL: Unable to initialize the API: disconnected from wss://pub.elara.patract.io/kusama: 1006:: Abnormal Closure
**DWELLIR:** FATAL: Unable to initialize the API: disconnected from wss://kusama-rpc.dwellir.com: 1006:: Abnormal Closure

This solution only works with POLKADOT and PATRAC ELARA :) ... but in KUSAMA all endpoints give me an error. Do you know another solution?

Very thankful.

**Comment by jacogr** [comment]
The only time I've ever seen this from the browser (and this is specific to `.network` domains) is where uBlock blocks the connection.
