### ISSUE TITLE
Wron values in Staking.Rebond Extrinsic

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#3962]
I do not know if this is an issue of the Polkadot API, maybe you can check it.
I noticed that certain values in the Staking.Rebond Extrinsic and the associated Staking.Bonded event are obviously wrong.
Example:
https://kusama.subscan.io/extrinsic/9008712-3
The rebonded value is 27,684,776 KSM, (a really huge amount)
The account balance at this time was 2805 KSM, so bonding this amount was not possible. Possibly there is an error factor.
If I query the bonded value in this block, the amount in 9008712-3 should actually be 2768.4776 KSM. Where is the error?

Other obviously wrong values I found in:
https://kusama.subscan.io/extrinsic/8789956-2
https://kusama.subscan.io/extrinsic/8803512-6

btw, I'm using @polkadot/api v5.9.1

**Comment by jacogr** [comment]
See the values via the API - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/9008712 - It is 27.6857 milli DOT

Here it is 10m - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/8789956

The above display you linked on Subscan (they have their own API) is without decimals, non-formatted, so treat it as 12 digits.

**Comment by TheGoldenEye** [comment]
> See the values via the API - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/9008712 - It is 27.6857 milli DOT

like i said, 27 **million** (which cannot be, since the balance is only 2805 KSM)

In the 2nd case is it 10 million, here is the stash balance only 1001 KSM:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/8789956

if i query the difference of the bonded values before and after the transaction, i get 2768.4776 KSM in the first and 1000.0999 KSM in the second case.

Where do the wrong values come from?

**Comment by jacogr** [comment]
It is mili Not Million

**Comment by TheGoldenEye** [comment]
No, it is Mill, not mili
![mill](https://user-images.githubusercontent.com/17945384/133754538-80cc3c1b-07bb-46ac-b5a0-65c27b99bda6.png)

Extrinsic#9008712-3:
![9008712-3](https://user-images.githubusercontent.com/17945384/133753618-57f38bb3-2eaa-49d5-93a8-f9ee1ac0fe62.png)

Extrinsic#8789956-2:
![8789956-2](https://user-images.githubusercontent.com/17945384/133753665-0873e54c-12ba-41ce-a01b-c28455d1305b.png)

with 12 decimals: 
27 million KSM  resp. 10 million KSM

The values above I got from your API too

**Comment by jacogr** [comment]
Indeed, misread between everything else. It is indeed 27M on-chain, https://polkascan.io/kusama/transaction/0x5033a1fe77292df95a055e05921df585aeb05e8851fa3a319e4c6eba6d6e7d5d

It is not incorrect, there is no available checking done on-chain. (However, when done the user will still only be rewarded up the the actual available bonded amount)

**Comment by TheGoldenEye** [comment]
Hm, but the Staking.Bonded event should reflect the amount actually bonded. You cannot lock more coins than available.

Moreover, if I check the bonded balances for the 2 accounts:

stash DcAgRyM7BCEToY43W3WesEtPKWDBJ5RDDc5FEE38pbP25AD
at block 9008711: 0 KSM bonded
at block 9008712: 2768.4776967981 KSM bonded
-> difference is 2768.4776967981 KSM

stash FSBmjB62yVo7T4pd4WjvRz5eWPp75GrbA77zoh1Mez7UuDj:
at block 8789955: 0.000072383276 KSM bonded
at block 8789956: 1000.099972383276 KSM bonded
-> difference is 1000,0999 KSM

It is noticeable that this is exactly the 10000th part of the amount in the Staking.Bonded event.
This can not be a coincidence.

**Comment by jacogr** [comment]
The API can only reflect what is on-chain, nothing more. It takes the values and decodes it. The values on-chain is the values being displayed.

**Comment by TheGoldenEye** [comment]
Ok, then it is obviously an issue of the polkadot node?

**Comment by jacogr** [comment]
This is not an API issue, no. It decides what the chain provides. It doesn’t “make up” info.

**Comment by jacogr** [comment]
Closing. Not API related.
