### ISSUE TITLE
FATAL: Unable to initialize the API: Cannot convert metadata from version 14 to 13

### ISSUE THREAD

**Issue by rphmeier** [polkadot-js/api#3967]

**Comment by rphmeier** [comment]
It seems like #3966 releases the parsing changes?

**Comment by jacogr** [comment]
Indeed. API release are always on Sunday/Monday. 6.0.1 should have it.  

(It is already part of the beta releases, each master merge triggers a beta release, so it is “out there for use”, just not “stable”)

**Comment by jacogr** [comment]
https://github.com/polkadot-js/api/releases/tag/v6.0.1

**Comment by jacogr** [comment]
Please use 6.0.x versions for “stable” (or betas prior where it has been released)
