### ISSUE TITLE
Links in README of polkadot/api are outdated leading to a 404 

### ISSUE THREAD

**Issue by nblogist** [polkadot-js/api#3984]
As of the commit https://github.com/polkadot-js/api/commit/3f69b3fc73fe16de9a5336a3a89e3acc405571f0 the links present in readme  [here](https://github.com/polkadot-js/api/blob/master/packages/api/README.md) are leading towards a 404 simply cause there is a `.HTML` present in front of each of them, I have fixed that ~~and will be submitting a PR next!~~ and submitted a PR [here](https://github.com/polkadot-js/api/pull/3985)

**Comment by jacogr** [comment]
Fixed in #3985
