### ISSUE TITLE
[Help] Get network staking returns and/or network inflation

### ISSUE THREAD

**Issue by iicc1** [polkadot-js/api#3993]
Hello,

I would like to get the "staking returns" value that is displayed on the Polkadot.js Web App. This screenshot shows an example with Polkadot:
![image](https://user-images.githubusercontent.com/13121233/134815744-252d6280-8078-455d-8726-f75f09b99c21.png)

I have not found any query or method that is able to get this value from the chain.
I could calculate the staking returns with the network inflation and the proportion of staked tokens/total tokens, but I have not been able to get the network inflation either.

![image](https://user-images.githubusercontent.com/13121233/134816003-b769403b-ad5f-463c-af30-fa1897d39893.png)

I would appreciate any help regarding this question.
Many thanks in advance.

**Comment by jacogr** [comment]
It is different on a per network basis. For instance, for Kusama, see the calculation at -

https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L426-L463

For Polkadot just a normal curve is used (no gilts, no parachains... yet) -

https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L442-L453

**Comment by iicc1** [comment]
Many thanks for your reply. Extracting the APR seems more complicated than I thought.

I discovered a possible way to get an estimated APR in a simpler way. Not sure if it correct but it matches the APR displayed on the web apps:

Get the reward of the last era: `api.query.staking.erasValidatorReward(lastEra)`
Get the total staked coins in the last era: `api.query.staking.erasTotalStake(lastEra)`

Then, the APR is the reward of the last era divided by the total staked coins, extrapolated to one year. Taking into account the era duration of the network.
