### ISSUE TITLE
[Help] needed about scanning the chain

### ISSUE THREAD

**Issue by i5possible** [polkadot-js/api#3998]
I want to scan the chain to find out the extrinsic has given event. And the scan should be able to start at given block height and continue where it leaves.

I used `api.query.system.events.at(hash)` and `api.rpc.chain.getBlock(hash)` to get the data, and  `api.query.timestamp.now.at(hash)` to get the timestamp. And I am going to use `api.rpc.chain.getFinalizedHead()` and `api.rpc.chain.getHeader(finalizedHash)` to check if it's a finalized block. 

It could work I think. But these rpc calls are really time consuming so I can't scan the block faster. Any suggestion about how should I simplify this work?

Thank you for your help!

**Comment by jiqiang90** [comment]
@i5possible SubQuery is exactly what you need (https://www.subquery.network/), you can also follow the guide here (https://doc.subquery.network/) to build your own project

**Comment by i5possible** [comment]
@jiqiang90 Thanks for you sugesstions!

I had a look at the subquery a little bit. It seems to be one station toolbox for scanning the chain and has done too much for us. 

We have done similar work to get the block and save it. I just wondering if I could make it much faster call the rpc call takes some time. We may not take this solution cause it means we need to learn it first and it becomes a black box for us.
