### ISSUE TITLE
query.system.account and old metadata

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#4004]
I would like to query the balance of an account for block 1310797 in the Kusama chain
The query returns with the following error: 
```
const sysAccount = await this._api.query.system.account.at(hash, address);

Error: query.system.account is not available in this version of the metadata
    at assert (/share/data/ge/src/coins/polkadot/my/polka-store/node_modules/@polkadot/util/assert.cjs:34:11)
    at /share/data/ge/src/coins/polkadot/my/polka-store/node_modules/@polkadot/api/base/Decorate.cjs:443:24
    at /share/data/ge/src/coins/polkadot/my/polka-store/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:30
    at OperatorSubscriber._this._next (/share/data/ge/src/coins/polkadot/my/polka-store/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/share/data/ge/src/coins/polkadot/my/polka-store/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at /share/data/ge/src/coins/polkadot/my/polka-store/node_modules/rxjs/dist/cjs/internal/observable/from.js:124:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
If i go deeper, i learn that system.account() exists only from runtime 1050 (block 1310797 was runtime 1045).

How can I check (beforehand) if a certain function is available? 
How to query metadata versions and determine their properties?
In Runtime 1045 there was a function 'system.accountNonce', is it possible to call it?

**Comment by jacogr** [comment]
(Sorry for the non-formatted content, on the phone the laptop decided to stop starting up…)

const a = await api.at(blockhash);
const n = await a.query.system.accountNonce(accountId);

console.log(n.toNumber());

it is generally advisable to use api.at(blockhash) since it returns a decorated instance with the metadata at that point of the chain.

**Comment by TheGoldenEye** [comment]
Great, this helps.
Another question: How to get Balance info before runtime 1050? (without 'query.system.account')?

**Comment by jacogr** [comment]
balances.freeBalance

**Comment by TheGoldenEye** [comment]
thank you, you have helped me a lot

Finally, an admittedly somewhat stupid question:
How can I initialize a variable of type "Balance" with a value of 0 (KSM)?
The following is obviously wrong:
`const fee : Balance  = 0 as unknown as Balance;`

**Comment by jacogr** [comment]
api.createType(“Balance”, 0)

You can also leave out the 0, it will yield the same result (since 0 is the default value). The value above is just more maintainable 6 months from now since it is explicit.

**Comment by TheGoldenEye** [comment]
thanks again!
