### ISSUE TITLE
Call to `new Metadata(registry, rawMetadata)` with large metadata is slow, particularly on mobile

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#4005]
With Karura metadata obtained with `console.log(api.runtimeMetadata.asCallsOnly.toHex());` from the apps JS console, they are almost 300Kb :exploding_head: 

In Stylo, just like it's done in the extension, I'm using  `new Metadata(registry, rawMetadata)` when signing an extrinsic, and this call actually takes about 1 minute on an older device, and something like 40s on a newer one. Even on the extension it takes several seconds:

https://user-images.githubusercontent.com/33178835/135359328-06bd6107-0ac5-4b77-b936-b1f93e8f4f18.mp4

I wonder if there's anything we can do, beside asking the Karura team why :)
To be precise, my `rawMetadata` from above is a string, where the extension is [actually feeding it with metaCalls as a Uint8Array](https://github.com/polkadot-js/extension/blob/9d0a6c96f5e99232b8710bf8f688b391431ba75c/packages/extension-chains/src/index.ts#L45), `new Metadata(registry, base64Decode(metaCalls));` I'm not sure if this changes something.

**Comment by jacogr** [comment]
The meta calls is stripped down. No storage, no events. Only extrinsics.

**Comment by Tbaut** [comment]
Not sure if you missed it, I do have the `asCallOnly`, it's still huge, 298Kb right now compared to 398Kb with the events.

**Comment by jacogr** [comment]
Ahhh... yes, misread.

**Comment by jacogr** [comment]
So, a couple of things here -

- metadata v14 is worse than metadata v13 (larger, has types included)
- the API natively supports v14, so all older versions are converted
- for v13 (as here) it means it gets parsed and then converted to v14

... the last step will be skipped once the chain is native v14, which _will_ be faster

**Comment by Tbaut** [comment]
Ah this is encouraging. I was about to ask about the v14, which I honestly know very little about. I saw you did all the heavy lifting in the api, so that there's seemingly nothing to do on the extension/offline side, thank you so much for that.

iiuc, this means we'll be able to skip importing network specific types, we won't need to add the types overrides, and we'll be able to directly import the metadata v14, which will contain the right types. Do I get this correctly?

**Comment by jacogr** [comment]
100% types have gone the way of the Dodo.

**Comment by Tbaut** [comment]
Thanks a lot, I'll close this for now since there's not much we can do. I'll complain to the Acala ppl if this keeps growing too much. I bet they won't be the only ones having this issue as time goes.

**Comment by jacogr** [comment]
It is a bit ineffective at this point - however from an API user perspective it means there is o lay one way of doing things. 

Acala will no doubt (in my mind), be one of the first to swap to v14 - the team really tracks latest.

**Comment by Tbaut** [comment]
I did ask in their discord today, didn't get an answer yet, but since they've been driving this originally, I also think they'll be quick :)
