### ISSUE TITLE
Multiple `state_getMetadata` calls between v5.9.1, and v6.1.2

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#4019]
I put together a short example of some api calls I make in one of the services and the ran the `api-ws` logger against it to see what differences might be present. 

```javascript
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://westend-rpc.polkadot.io'),
    });

    const hash = await api.rpc.chain.getBlockHash(28831)

    // Should be a Promise.all but for examples sake I am splitting them up.
    const block = await api.derive.chain.getBlock(hash)
    
    const runtime = await api.rpc.state.getRuntimeVersion(hash)
    
    const header = await api.rpc.chain.getHeader(hash)

    console.log(runtime, header, block)
};
```

When running this example with v5.9.1, `state_getMetadata` is called twice, but when I run the same example against v6.1.2, `state_getMetadata` is called 4 times. 

Wondering is this expected behavior?

**Comment by jacogr** [comment]
For the same hash, only one registry _should_ be retrieved - https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L125-L131

Quite possible that there are some weird effects with v14 (where the right/recent registry is critical), but nothing that springs to mind.

**Comment by TarikGul** [comment]
Thanks for the insight. I'll do some more digging and see what I can find. When I initially updated `@polkadot/api` in Sidecar from v5.9.1 -> v6.0.5 there was a pretty large regression in our response times (Could 100% be an implementation issue on my end that is just surfacing now).

Thats where this digging initially started from. I am currently working my way through [commit #3759](https://github.com/polkadot-js/api/pull/3759) to have a deeper understanding of whats exactly happening with the v14 overhaul.  

The one thing I was able to narrow down so far is the extra `state_getMetadata` calls start happening via `v6.0.4-0` or commit hash [870bb8d3cb2339aa9d3cb7513f8dc30c695f270c](https://github.com/polkadot-js/api/commit/870bb8d3cb2339aa9d3cb7513f8dc30c695f270c).

At the same time though I am not even sure our regression completely stems from the extra `state_getMetadata` calls, since I have a similar performance issue with 6.0.3 (the extra `state_getMetadata` calls seems to be something I found residually). Ill do some more thorough investigating between v5.9.2-0 -> v6.0.1 and some benchmarking too, and see what I can find.

**Comment by jacogr** [comment]
With `.at` it will certainly now perform an extra call if the hash changes - specifically due to the commit you highlighted. However, for that one there is probably an inefficiency in that at, it needs to get the version, if that changed then get a new registry & metadata, otherwise use the registry as at that version.

(The above example in the first post however, should really not have any extra calls)

**Comment by jacogr** [comment]
Ok, it is the derive that end up with multiples, not the subsequent calls - for the derives cases it doesn't have the registry for the details it gets it in parallel, ending up with multiple state calls.

**Comment by TarikGul** [comment]
Thanks for the PR that solves that!
