### ISSUE TITLE
[QUESTION] Connect to dApp from mobile

### ISSUE THREAD

**Issue by barmanabarmana** [polkadot-js/api#4038]
Hi there
I am working on a dApp bridge,and having some problems with mobile users.
[FOR EXAMPLE] - metamask has it own app,that has built in browser,and its easy to connect to the dApp through the metamask browser.

[PROBLEM] - I wanna fIgure out how can i do the same with the polkadot wallet,i didnt found any apps that has the same functionality
What would you recommend me to do?

**Comment by joelamouche** [comment]
@barmanabarmana there is https://www.parity.io/technologies/signer/ but it is more or less wip

**Comment by joelamouche** [comment]
@barmanabarmana my bad I misunderstood your question

**Comment by semuelle** [comment]
@barmanabarmana You can find a list of mobile wallets and client libraries for different platforms [here](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md).
