### ISSUE TITLE
Compiler is not throwing all errors

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#406]
Repro:
- replace this line https://github.com/polkadot-js/api/blob/master/packages/api/src/promise/types.d.ts#L10
with `import { Codec } from '@polkadot/types/codec';`
- `tsc --noEmit`

Expected:
Compiler should throw, because the import does not exist.

Actual:
It passes.

**Comment by jacogr** [comment]
With @chevdor 's project, I toggled this line for some additional errors (in his project). It may need to explicitly set? https://github.com/polkadot-js/dev/blob/master/packages/dev/config/tsconfig.json#L25

It _could_ be related, not 100%, but worth looking into the options which is mostly left as-is.

**Comment by mn-io** [comment]
I'd like to add that I have to use the types with following tslint option:
"esModuleInterop": true

otherwise following error will be thrown:
.../node_modules/@polkadot/storage/types.d.ts
(7,8): Module '".../node_modules/@types/bn.js/index"' has no default export.

**Comment by jacogr** [comment]
Seems to be `*.d.ts` files only - acting stupid in `*.ts` files does get caught.

**Comment by jacogr** [comment]
Ok, some playing (yesterday)  - it is only in the `*.d.ts` files this happens. The `*.ts` files are fine. Chatted to @amaurymartiny so the suggestion is t do it right and rename these to `*.ts` (which is basically all repos)
