### ISSUE TITLE
[Question] about decode Bytes

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#4063]
Subscan is parsing https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.onfinality.io%2Fpublic-ws#/explorer/query/9638960

When parse the first ``paraInclusion.CandidateIncluded`` second  filed  ``head_data `` (type is Bytes)

Raw data is 

Bytes
``e902eacc19af51c15609ce68dedeb8005fab78ac15ee350e0810e15617f8e039f9f856512d0013feec8680a0d6648daed5af7f4cb84d5e52e770dde0eda06f104fb0f0cbae26ea8199a62e550fdd51a8065e3236fa3a0fdf99bbde1aa6e066e37d2d12cf5c09d83bb566c94fc6742e61646507d07a5b8c ``

length raw is  ``e902`` , decode value is  ``186``

But there only ``117`` length

As far as the data is concerned, there is no problem with polkadot.js parsing, but I don't know why it produces different results.

**Comment by jacogr** [comment]
The events appear is a `Vec<EventRecord>` - as the second field, it is unlikely that it is only 117 bytes. Then length is indeed 186 compact-encoded, so should be the full value.
