### ISSUE TITLE
6.4.x can not decode VersionedXcm which can be decoded by 6.3.1

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#4083]
Hi, @jacogr . Check [Statemine block 983104](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-statemine-rpc.paritytech.net#/explorer/query/983104), I can decode the `pubMsg` with api version `6.3.1`. 

![image](https://user-images.githubusercontent.com/2264908/137883402-f4a73c56-dec1-404c-af50-409ec261f12d.png)

But unfortunately I can not decode it with version `6.4.1` and `6.4.3-1`. Part of my code:

```javascript
  const pubSentAt = downwardMessage.pubSentAt.toJSON();
  const pubMsg = downwardMessage.pubMsg;
  const messageId = blake2AsHex(pubMsg.toHex());

  let versionedXcm;
  try {
    versionedXcm = registry.createType("VersionedXcm", pubMsg, true);
  } catch (e) {
    teleportLogger.info(
      `versionedXcm parse failed at ${extrinsicIndexer.blockHeight}`
    );
    return null;
  }

```

So maybe some problems with 6.4.x?

**Comment by jacogr** [comment]
Addendum to the above - the difference between 6.3.1 and 6.4.1 is that the V1 types have been aligned with Polkadot. So if it fails on 6.4.1 (and is ok on 6.3.1), it means it is due to that change.

**Comment by wliyongfeng** [comment]
I didn't read the pallet-xcm fully(will do). Can this case happen?
1. Kusama has old V1 type while Statemine has new V1 type.
2. Kusama send a old V1 type msg(10 KSM teleport for example) to Statemine.

If this can happen, will this teleport success? Or which of following results will happen?
- Kusama burns the to teleported 10 KSM, but Statemine won't issue new ones. -> bug
- Kusama won't burn the 10 KSM, and Statemine won't issue new ones. -> fine

**Comment by jacogr** [comment]
Still needs a look.
