### ISSUE TITLE
bug Frame size exceeds maximum accepted frame size

### ISSUE THREAD

**Issue by polariseye** [polkadot-js/api#4086]
there is a bug when i invoke  ApiPromise.rpc.chain.getBlock
chain:kusama
block num:9739528
error message:  API-WS: disconnected from wss://kusama-rpc.polkadot.io: 1009:: Frame size of 1069305 bytes exceeds maximum accepted frame size

**this bug just happend in docker  with node:lateast.there is ok in windows10**

fix: edit code https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/ws/index.ts#L178 .as follow
````
       // default: true
        fragmentOutgoingMessages: 16 * 1024 * 1024,
        // default: 16K (bump, the Node has issues with too many fragments, e.g. on setCode)
        fragmentationThreshold: 256 * 1024,
        // set frameSize
        maxReceivedFrameSize:16 * 1024 * 1024,
        // default: 8MB (however Polkadot api.query.staking.erasStakers.entries(356) is over that)
        maxReceivedMessageSize: 16 * 1024 * 1024
````

see also: https://github.com/ChainSafe/web3.js/issues/1217

**Comment by jacogr** [comment]
`fragmentOutgoingMessages` is only boolean, see https://github.com/theturtle32/WebSocket-Node/blob/a2cd3065167668a9685db0d5f9c4083e8a1839f0/docs/WebSocketClient.md#client-config-options

However, can certainly adjust the `fragmentationThreshold` upwards more, e.g. 1MB (or even more). Will do some tests with that block and see if the same issue happens.
