### ISSUE TITLE
is this lib mean to have a universal interface for all DOT natives tokens and substrate tokens?

### ISSUE THREAD

**Issue by Albert-Gao** [polkadot-js/api#4099]
For example, can I just use `api.query.system.getBalance` to get the balance for either native token like DOT or substrate token like ACA?

**Comment by Albert-Gao** [comment]
Thanks! @jacogr  which means, there are indeed generic APIs like `api.query.system.getBalance`, which I can use for both native tokens and substrate tokens, but I have to connect to different providers, right?

![image](https://user-images.githubusercontent.com/18282328/138617944-e73b9cdb-04a2-4a0a-b4e4-c6debb8d4f08.png)

For example, in this picture, code copied from here: `packages/apps-config/src/endpoints/testingRelayWestend.ts`

If I want to `getBlance` against WND, I connect to `wss://westend-rpc.polkadot.io`, if I want to get balance of basilisk, I need to connect to `wss://rpc-01.basilisk-testnet.hydradx.io`? 

Does this mean if I am building a wallet that supports Polkadot tokens, I have to establish many WebSockets connections for each token?

**Comment by jacogr** [comment]
Closing, answered.
