### ISSUE TITLE
Api initialisation blocks the JS thread on react-native

### ISSUE THREAD

**Issue by ahoseinian** [polkadot-js/api#4107]
Expensive computation on type registry blocks the JS thread for a multiple seconds

We have notice that while initialising the polkadot `ApiPromise` the app become unresponsive for multiple seconds on android it can take up to 60 seconds. (tested on completely empty new react native project with no other dependencies)

![Screenshot 2021-10-25 at 14 48 15](https://user-images.githubusercontent.com/1168983/138697920-7787d32f-e48d-4d35-b655-1b4f0e6038d9.png)

Going through the code that is responsible for initialising the api we have found that the [`decodeU8a()`](https://github.com/polkadot-js/api/blob/f20fadb51ce0e124949bd6b80dd1b31e0ff30bc2/packages/types/src/codec/utils/decodeU8a.ts#L27)  and generating the type for complex types like metadata is especially slow and could be the cause of the problem.

We were wondering what makes this function so expensive to run and is there any way we could reduce the load when initialising the api or lazily load the types that we want to use.

We should add that the api was not this slow previously and the problem might have something to do with the recent changes of the runtime. this problem is happening on both Polkadot & Kusama networks. however in our own [staging chain](wss://staging.registrar.litentry.io) the performance is slightly better and it takes roughly the half the amount of time for the Api Promise to get ready.

---
Test project: https://github.com/ahoseinian/test

**Comment by bkbooth** [comment]
I'm running into this problem too, in our case it's a browser extension. We initialize the API service in a background script, but when it gets to the blocking stage (which from this thread I understand to be when it's got the metadata from the chain and is parsing it), it also blocks the thread for the popup script, so the user can't click anything while this is happening, despite it happening in a background script.

I get that it's probably computationally expensive to parse the metadata, but I'm still surprised that it takes so long (~4s for us) during the thread blocking stage. Can you provide any more details on why it blocks for so long? Surely there's a way to improve this?

To be clear, I'm not complaining about the length of time to be able to _use_ the API service itself (7-10s for us depending on network), that seems slow but we can manage that. My issue is the time that the entire thread is blocked (~4s for us) and the user can't do anything during that time.

**Comment by dractw** [comment]
Facing same blocking issue, bump

**Comment by jacogr** [comment]
Closing, please try 7.7.1 with some improvements (lazy initialization of decoration, additional complex-type caching) that have addressed large parts of the initialization process. For additional improvements and pin-point specifics, PRs are welcome.

**Comment by Yuripetusko** [comment]
> Closing, please try 7.7.1 with some improvements (lazy initialization of decoration, additional complex-type caching) that have addressed large parts of the initialization process. For additional improvements and pin-point specifics, PRs are welcome.

So far it looks better

**Comment by bkbooth** [comment]
Blocking time for us looks like it's dropped from ~4s to ~1s for us which is totally manageable. Great result 🙌
