### ISSUE TITLE
[Help] Get network nominators + targets data

### ISSUE THREAD

**Issue by ivosk89** [polkadot-js/api#4124]
[API doc for api.query.staking.nominators](https://polkadot.js.org/docs/substrate/storage/#nominatorsaccountid32-optionpalletstakingnominations)

I have `null` responses for `api.query.staking.nominators` requests always. Is it a bug or I have some misunderstanding? 
It is not depends on network and/or validator's ID as parameter. Example  from `Developer -> JavaScript -> Console`

![image](https://user-images.githubusercontent.com/1576218/139314364-358a066e-c101-46a3-b768-9a9a4c7b9bc2.png)

Also, I would like to get the validator data from `/staking/targets` page (`nominators | commision | total stake | own stake | other stake | return`). I have not found any queries or methods that is able to get these values.

![image](https://user-images.githubusercontent.com/1576218/139304248-83242cfd-2fcd-493a-8d9f-6f6c3f205baf.png)

**Comment by ivosk89** [comment]
@jacogr 
So, I can't get `nominators | commision | total stake | own stake | other stake | return` validator's data via API?

**Comment by jacogr** [comment]
The API only exposes what the runtime state indicates - see https://polkadot.js.org/docs/api/start/basics#metadata

All the above data is in the staking state, eg. the `Exposures` has the totals, `ValidatorPrefs` has the preferences (incl. comission), `nominators` has the nominators (as explained above).

Anything derived, like returns, you need to calculate based on the inflation parameters.

**Comment by ivosk89** [comment]
@jacogr 
Ok, thank you! It's work fine for me.

There are 2 fields that I can't recieve via API now: `account name` & `returns`. 
Can you help me, please?

**Comment by jacogr** [comment]
Returns needs to be calculated via the on-chain data. 

Identity is in the identity pallet storage.

**Comment by jacogr** [comment]
Closing, answered.
