### ISSUE TITLE
Overwrite the types

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#4159]
Hi @jacogr , I'm having trouble to override the types.
It seems that passing the typesBundle or even the types to the ApiPromise.create is not enough, the api will pick the runtime generated types.
What is the suggested why to do that ?

**Comment by jacogr** [comment]
There are no overrides with metadata v14.

**Comment by crystalin** [comment]
@jacogr but I'm able to override them in the polkadotjs developer page :/

**Comment by jacogr** [comment]
The UI may display them, but won't use them that way. As soon as it encoded/decodes it will use the indexes in v14 and then the lookups on that. Unlike v13 where it actually did lookups on strings, in v14 it uses indexes. To clarify -

v13 - extrinsics (as an example) is defined as `<name>(<types>...)` in the metadata, e.g. `balances.transfer('AccountId', 'Balance')`

v14 - extrinsics are defined as `<name>(<type indexes>..)` in the metadata, e.g. `balances.transfer(0, 5)`

In the previous case the API would do a string lookup. In the current case the API looks up the index in the supplied runtime registry and constructs with that type. There are no names entering the picture, they are purely there for human consumption.

**Comment by crystalin** [comment]
Ok, I think it is still useful for us. Our issue is the naming convention (for some fields) that was broken in our typeBundle, and we need to provide those name back until the tools are able to support the new names. Changing the types with the new type naming convention seems to allow to use PolkadotJs and have the expected field names.

Thank you @jacogr
