### ISSUE TITLE
Is it possible to support custom types for codec?

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#416]
Currently it is required to have all types listed in a [single file](https://github.com/polkadot-js/api/blob/master/packages/types/src/index.ts) and I don't know if there is an easy way to add a new type. 

https://github.com/polkadot-js/api/blob/2f3af48875dec6aee3b8fa3c8dd674d6e2dd31bf/packages/types/src/codec/createType.ts#L152

This causes issues when we want to invoke a new module method that returns a new type.

polkadot.js should provides ability to:
1. Allow new types to be added at runtime (via a type registry or something similar)
2. Able to generate type files from Rust code so no need to manually keep the typescript definitions in sync with Rust definitions.

Alternatively, enhance the runtime metadata to include all the type definitions and have the js code construct the types using the metadata in runtime. Then there won't be any needs to worry about type registration. This can also be used to generate .d.ts files to provide documentations and IDE supports for typescript projects. This will also solve the potential type name conflicting issues (that the current types names are not namespaced).

**Comment by amaurymartiny** [comment]
1 should definitely be added into this package.

By 2, do you mean a parser that will parse the Rust code and look for types in it? I would say not ideal, but if it's robust enough, then why not as a helper tool.

Your alternative solution is of course the ideal solution, it is logged here: https://github.com/paritytech/substrate/issues/917, but probably won't be done soon unfortunately.

**Comment by jacogr** [comment]
The metadata does not have the specific type definitions (only names), as @amaurymartiny suggested. (Here is a parsed one-to-one mapping of what the API gets from the runtime - https://github.com/polkadot-js/api/blob/master/packages/types/src/Metadata.latest.json)

So briefly discussed this, a first step would probably be to have some way of injecting type definitions into the API, off-the-top of my head, a JSON that more-or-less defines the specific structures, eg.

```
{
  "TypeA": {
    "field1": "u32",
    "field2": "bool",
    "field3": "Vec<AccountId>"
  },
  "TypeB": {
    "field1": "u64",
    "field2": "Vec<TypeA>"
  }
}
```

Here anything Rust-y could work, e.g. `Vec`, `Compact<..>` in addition to the base Substrate types (already defined)

As soon as injected, these types become available. (In later iterations, probably look at stuff like enums and other stuff I'm not clearly thinking of now.)

**Comment by xlc** [comment]
Is it possible for the Rust serialization macro (or a new macro with similar mechanism) to generate a method that expose the type definition? Kind of like reflection for Rust. May be something similar already exists?
Then it should be possible for the metadata macro to invoke this reflect method to make type definitions available at runtime. A script can then get metadata from runtime and generate typescript files from it.

**Comment by xlc** [comment]
Thanks for the clarification. I am keen to work on the interim solution with a type registry unless there is already a plan for this.
My plan is to add a `TypeRegistry` class that is basically a map of types. It will be a singleton object and have all build-in types registered. Apps can register their types as well.
I will like to avoid singleton/global object if possible but that seems will require a large-ish refactor. i.e. passing the registry around in all the function calls.

Please let me know your thoughts.

**Comment by jacogr** [comment]
Perfect. The singleton is indeed the best approach. (Sadly we use some of them already, i.e. inside `Method`)

So once you have that going, I would adapt `types/codec/createType` to first check the registry for types and if found there construct from it, otherwise construct normally. (Unless the Registry has all types, then it just checks there. Don't have feelings any way, this is new)

@amaurymartiny Additional comments?

**Comment by jacogr** [comment]
Had a quick chat with @amaurymartiny , realised I missed showing how the Metadata is currently injected. Basically when the API connects, it makes the getMetadata call and then injects the stuff -

https://github.com/polkadot-js/api/blob/master/packages/api/src/Base.ts#L197

Before this point we probably need the user-types available. So It may be useful to have the types passed as an optional param to the API constructors. (That way the API can grab those and inject into types). Not perfect, but at least it means we pass everything to the API and it takes care of the messy nature - so at the very least it is in a single file where the injection happens.

Like I mentioned, I'm not really sure where/what is best here - looking forward to looking at something once it is available. (Take my comments as ideas, and feel free to take any approach that works better)
