### ISSUE TITLE
Why is there no transaction hash returned in getBlockf() block.extrinsics

### ISSUE THREAD

**Issue by MrLcj** [polkadot-js/api#4163]
Can I get the complete transaction information of a block through getBlock()? When I parsed the data of extrinsics, I found that there is no field about the transaction hash. Can the transaction hash be obtained from the returned data? What if you can’t get the hash of the transaction in the block by any other means?

**Comment by jacogr** [comment]
`extrinsic.hash` would always return the hash (this works on any object retuned by the API)

**Comment by MrLcj** [comment]
Thank you very much for your prompt reply! I already know how to get it, thank you
