### ISSUE TITLE
get transaction by hash

### ISSUE THREAD

**Issue by chaim-g** [polkadot-js/api#4167]
Hi! excuse me . How do I use polkadot-js to query transaction details or transaction certificates through transaction hashes?

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/FAQ#which-api-can-i-use-to-query-by-transaction-hash

**Comment by chaim-g** [comment]
So what do I need to do in the polkadot block to find out whether my transaction was sent successfully or failed?

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events
