### ISSUE TITLE
failed decoding paraInherent.enter

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#4171]
Hi. I'm operating application used polkadot-js v6.6.1. Our application queries transactions within the block whenever the block is created. Although the latest polkadot-js are applied, errors occur intermittently when parsing blocks with parainherent events. This problem occurs in both Polkadot Network and Kusama Network.

1. What are the causes of the following errors and how can they be solved?
```javascript
failed decoding paraInherent.enter:: decodeU8a: failed at 0x1903a00000000000... on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0xa000000000000000â€¦ on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1Sign
```

2. Is there a way to keep the websocket connection with the polkadot client (node) from being disconnected? Currently, `write EPIPE` errors are encountered once a day.

I'll be waiting for your reply. Thank you.

**Comment by jacogr** [comment]
Do you have a specific blockHash?

**Comment by boohyung** [comment]
1. There were various error cases. For example, #7560551, #7560551, #7560573 in DOT network
 #7560551: 0xeed33d7e4be5de0584959628c0309d4d2c0859cd2a5d40983e4b4c89c463701c
 #7560552: 0x03168f2ef8f1e399af193c00e1c2c99f58c16297465a838f2ba3f52a30930b54
 #7560573: 0xc78724974dece4994075a7788bb29dd03ffbdd4f5d61d29fd33192d2dd551009

2. Is there a way to confirm that it is alive?

**Comment by jacogr** [comment]
How are you querying? Are you using `api.at(<blockHash>)` that injects the correct registry for that point on-chain?

**Comment by boohyung** [comment]
1. we use 3 functions for querying transaction in block: `api.rpc.chain.getBlockHash(number), api.rpc.chain.getBlock(hash), api.query.system.events(hash)`
2. Ok. I got it. So If the connection is disconnected, what error message occurs?

**Comment by jacogr** [comment]
`event` doesn't take a `hash` parameter?

**Comment by boohyung** [comment]
Ok. will check. Thanks!
