### ISSUE TITLE
Bug: Vote locking period outdated calculation

### ISSUE THREAD

**Issue by wischli** [polkadot-js/api#4173]
# Issue

In https://github.com/paritytech/substrate/issues/9641 the democracy pallet's config trait received a new constant parameter `VoteLockingPeriod` which sets the number of blocks for which a vote with `1x` convictions locks the used tokens for. Before, the `EnactmentPeriod` parameter was used.

See [`fn try_remove_vote` in _Substrate:frame/democracy/src/lib.rs_](https://github.com/paritytech/substrate/blob/master/frame/democracy/src/lib.rs#L1429) for the unlocking block:
```rust
let unlock_at = end + T::VoteLockingPeriod::get() * lock_periods.into();
```

Unfortunately, the calculations in the Polkadot Apps still seem to use the `EnactmentPeriod`. This occurs both when you vote on a referendum as well as when inspecting the DemocracyLock in the Accounts section.

## Fix attempt

I tried to solve the issue on my own in https://github.com/KILTprotocol/polkadot-apps/commit/d655ee10040a5ade5bcaeb581a5404ce5575d4c0 but only managed to fix the lock period during voting. Unfortunately, I didn't manage to fix it in [_packages/react-components/src/DemocracyLocks.tsx_](https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/DemocracyLocks.tsx#L65).

## How to replicate

You can replicate this on our [Westend test parachain WILT](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend.kilt.io%3A9977#/accounts) which has different configurations for both parameters: 
* EnactmentPeriod = 1 day in blocks = 7200
* VoteLockingperiod = 7 days in blocks = 50400
* Address which voted on a successful referendum yesterday: `4oe5PCLwbEK4dq6rg9wbkRuC2xgzxf7jb953KMtSgUHpVZUW`

Without my fix, both voting in a referendum as well as the DemocracyLock do not use the VoteLockingPeriod but the EnactmentPeriod of 7200 blocks instead.

**Comment by jacogr** [comment]
Added in 6.7.1
