### ISSUE TITLE
Transaction isn't sent unless consuming result with rx.js

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/api#4174]
I have a following piece of code that is similar to https://polkadot.js.org/docs/api/start/api.tx and https://polkadot.js.org/docs/api/start/api.tx.wrap:
```typescript
this.api.rx.tx.feeds
    .put(feedId, block, metadataPayload)
    .signAndSend(signer.address, { nonce: nonce || -1, signer }, (result) => {
        console.log(result);
    });
```

This results in a whole lot of nothing happening, nothing arrives at the node, nothing is printed to the console (node.js) and `await` doesn't help when used either.

This works though:
```typescript
this.api.rx.tx.feeds
    .put(feedId, block, metadataPayload)
    .signAndSend(signer.address, { nonce: nonce || -1, signer }, Promise.resolve)
    .pipe(
        takeWhile(({ status }) => !status.isInBlock, true),
        catchError((error) => {
            this.logger.error(error);
            return EMPTY;
        })
    )
    .subscribe(this.logTxResult)
```

My use case is to send transaction and track transaction inclusion separately and manually to avoid all of the machinery related to above subscription since with that I can't push more than 500 txs per second even with a series of optimizations of the polkadot.js api internals.

Is it something about the way metadata v14 support is implemented?

I found this whole situation with rx.js super confusing, it would be so much nicer to have plain JS API with promises and async iterators.

**Comment by jacogr** [comment]
It is quite possible that the rxjs documentation is outdated, it is not something that is recommended unless you are familiar with rxjs. (There is nothing the rxjs does that the promise API doesn't)

**Comment by nazar-pc** [comment]
Well, promise API doesn't work for me in this case at all. This is with metadata v14 and beta version of `@polkadot/api` as of today.

**Comment by jacogr** [comment]
Both promise & rxjs executes this path - https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L191

Which means both check for inBlock || isFinalized - https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L235

So effectively what your code above translates to it the following -

```js
api.rpc.author.submitAndWatchExtrinsic(this).pipe(
        switchMap((status): Observable<ISubmittableResult> =>
          this.#observeStatus(hash, status)
        ),
        tap((status): void => {
          this.#updateSigner(updateId, status);
        })
      ).pipe(
        // User pipes added go after the already-added pipes
        takeWhile(({ status }) => !status.isInBlock, true),
        catchError((error) => {
            this.logger.error(error);
            return EMPTY;
        })
      );
```

If you wish to bypass the default API handling, you will need to provide your own. This has nothing to do with metadata v14, it didn't touch extrinsics.

**Comment by nazar-pc** [comment]
Hm, I think I was confused with `api.tx` and `api.rx.tx`. It works with `api.tx`, sorry for confusion.
