### ISSUE TITLE
Issue on a clean create-react-app and npm install @polkadot/api

### ISSUE THREAD

**Issue by Commitbe** [polkadot-js/api#4181]
Hi,

After doing a clean `create-react-app` and `npm install @polkadot/api`, I get below error on `npm start`.

> ./node_modules/@polkadot/util-crypto/key/DeriveJunction.js 12:2
> Module parse failed: Unexpected character '#' (12:2)
> File was processed with these loaders:
>   ./node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> | };
> | export class DeriveJunction {
>  -> #chainCode = new Uint8Array(32);
> |   #isHard = false;
> |

Am I missing a certain dependency for this repo to work out of the box?

**Comment by jacogr** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields - it is a valid JS construct. 

You will need to tell Babel to treat it correctly, it has a language plugin.

**Comment by Commitbe** [comment]
I'm trying to override the Babel config of create-react-app with the customize-cra plugin. I'm struggling but I should get there. Wouldn't it be good for the Polkadot dev community that this works out of the box for starting developers?

**Comment by jacogr** [comment]
Sure, PRs welcome to scratch your itch.

**Comment by Commitbe** [comment]
I understand. React is one of the most used ones though. I'll attempt to make a PR.

**Comment by jacogr** [comment]
See for instance https://github.com/facebook/create-react-app/issues/11339 where complaints are made around the exact same thing (browsers has support, CRA does not). The is really purely a CRA issue, nothing to do with the API, it tracks what browsers can and do support with babel/preset-env.

**Comment by Commitbe** [comment]
Fair enough! Consider this issue closed. ;)

**Comment by JasonDeeper** [comment]
Vue has this error as well.

**Comment by jacogr** [comment]
Closing. Against better judgement have adjusted the build process slightly in util 7.8.2 & api 6.7.1 - this should not appear in recent vereions.
