### ISSUE TITLE
How to get the transaction fee

### ISSUE THREAD

**Issue by chaim-g** [polkadot-js/api#4202]
Hello. Excuse me again. When I construct the transaction, I use transferKeepAlive. How do I calculate the transaction fee?

**Comment by jacogr** [comment]
const tx = api.tx.balances.transfer(…)
const fee = await tx.paymentInfo(…)

tx.signAndSend(…)

**Comment by chaim-g** [comment]
I have tried this, but I am prompted that the paymentInfo() method cannot be found. My transfer method is written like this:
const unsigned = methods.balances.transferKeepAlive(
            {
                value: amount,
                dest: toAddress,
            },
            {
                address: deriveAddress(fromKey.publicKey, PolkadotSS58Format.kusama),
                blockHash,
                blockNumber: registry
                    .createType('BlockNumber', block.header.number)
                    .toNumber(),
                eraPeriod: 64,
                genesisHash,
                metadataRpc,
                nonce: nonce,
                specVersion,
                tip: 0,
                transactionVersion,
            },
            {
                metadataRpc,
                registry,
            }
        );
