### ISSUE TITLE
Question: How do you get Staker rewards for a specific controller?

### ISSUE THREAD

**Issue by OnigiriJack** [polkadot-js/api#4205]
I am currently trying to user `derive/src/staking/StakerRewards.ts` and `EraRewards.ts`, but seem to be getting rewards for the whole network and not for the validator and account in question. Any suggestions would be helpful

**Comment by jacogr** [comment]
The query needs to retrieve all since to calculate it needs to nominators are well to split the proceeds. 

I guess there could be a specific ownRewards that can use the above an filter it to specific controllers/stashes.

**Comment by OnigiriJack** [comment]
Thank you for the reply. Basically what I want to calculate is the amount that would be received when you call `tx.staking.payoutStakers()`.  I would want to get the reward from the target validator controller pair for every era with unclaimed rewards and then aggregate those amounts.
