### ISSUE TITLE
Why toHex() is not hex of toU8a() ?

### ISSUE THREAD

**Issue by the729** [polkadot-js/api#4207]
I'm new to polkadot.js, but very confused that `type.toHex()` is not strictly the hex representation of `type.toU8a()`.

For example: 
```js
var t = api.createType('Option<u8>', "2")
console.log(t.toU8a())  // output: Uint8Array(2) [ 1, 2 ]
console.log(t.toHex())  // output: 0x02, why not be 0x0102 ?
```

**Comment by jacogr** [comment]
toJex is generally used in jsonrpc - there is no length prefixes added, since the string is of a certain length, and therefore it is extra info. 

Changing this would mean all RPCs break.

**Comment by the729** [comment]
Related to #4208. Closing this issue.
