### ISSUE TITLE
Wrong result when decoding 'Option<Vec<u8>>'

### ISSUE THREAD

**Issue by the729** [polkadot-js/api#4208]
Example:
```js
console.log(api.createType('Option<Vec<u8>>', null).toU8a())
// Output is [0x00], as expected.

console.log(api.createType('Option<Vec<u8>>', "0x01").toU8a())
// Output is [0x01 0x04 0x01], as expected.

console.log(api.createType('Option<Vec<u8>>', "0x").toU8a())
// Actual output is [0x00], expected output is [0x01 0x00].
// Expected is not None, but an empty vector. 
```

This issue is due to the following PR, which forces string "0x" to be decoded into None. 

> Not strictly needed as a fix, but this was the actual issue - `0x` should not convert into `Some` (Not needed with the change below to the `SignedPayload`, but still something that should be catered for)
> 
> _Originally posted by @jacogr in https://github.com/polkadot-js/api/pull/4079#discussion_r730992464_

**Comment by krhougs** [comment]
@jacogr 

I wonder how it should behavior according to the SCALE specs:
```
Definition B.5. The Option type is a varying data type of fNone; T2g which indicates if data
of T2 type is available (referred to as some state) or not (referred to as empty, none or null state). The presence of type None, indicated by idx(TNone)=0, implies that the data corresponding
to T2 type is not available and contains no additional data. Where as the presence of type T2
indicated by idx(T2) = 1 implies that the data is available. 
```

The current behavior seems to work as the specs should be, but not as in the Rust side(as least with the Substrate version which Khala uses for now).

May the change in https://github.com/polkadot-js/api/pull/4079#discussion_r730992464 be reverted to prevent from breaking consistency?

**Comment by jacogr** [comment]
0x is empty and therefore None. It is correct, as intended (it was incorrect before).

**Comment by krhougs** [comment]
![image](https://user-images.githubusercontent.com/1382065/141529333-0976fc97-9544-412f-94a4-c62dd09da5d7.png)
It this intended?

**Comment by the729** [comment]
`Some(vec![])` is a valid state of `Option<vec<T>>`, and `Some(vec![])` is not equal to `None`.
SCALE binary representation CAN correctly address the difference of these two state. 

And polkadot.js can do this too. Example:
```js
console.log(api.createType('Option<Vec<u8>>', null).toU8a())
// Output is [0x00], as expected.

console.log(api.createType('Option<Vec<u8>>', []).toU8a())
// Output is [0x01 0x00], as expected.
```

The issue is not with SCALE binary representation. It is with HEX representation used in JSON RPC. 

I can't find the spec of HEX representation. According to @jacogr 's comment in #4207 ("when it is there means it has a value"), then "0x" should not be converted to None. 

I suggest:
```
null -> None
"0x" -> Some(vec![])
"0x01" -> Some(vec![1])
```
