### ISSUE TITLE
Wrong ProxyType in past block on moonbase alpha

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#4215]
As documented here https://github.com/PureStake/moonbeam/issues/952, it seems the api is fetching the wrong ProxyType from the chain in this past block:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbeam-alpha.api.onfinality.io%2Fpublic-ws#/explorer/query/0xb15185527f90d3c9a6f15d4dae2a181fcf649e1e6d02f5dfd5fb7a1879c50d7c

On subscan (https://moonbase.subscan.io/block/0xb15185527f90d3c9a6f15d4dae2a181fcf649e1e6d02f5dfd5fb7a1879c50d7c) we can see the expected proxyType is CancelProxy but the error message in the first link shows `proxy_type: {"_enum":{"Any":0,"NonTransfer":1,"Governance":2,"Staking":3}}`
It looks like the api is fetching an older or incomplete version of ProxyType.

There is no ProxyType in our custom types so I'm thinking the problem could be coming form the api

**Comment by JoshOrndorff** [comment]
If the api doesn't know about Moonbeam's custom `ProxyType` it probably falls back to Polkadot's or some other default. This type should be in the moonbeam types bundle

**Comment by joelamouche** [comment]
Okay so this is normal behavior for old blocks

**Comment by jacogr** [comment]
It just injects the Substrate default from here - https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L276

Polkadot/Kusama/Westend/Rococo (the types I used to maintain pre v14), each has their own, very different from the default above.

**Comment by joelamouche** [comment]
Indeed! Will add our custom type for pre scale-info runtimes
