### ISSUE TITLE
How do I use signAndSend to get the same result as signAsync?

### ISSUE THREAD

**Issue by ThreeAndTwo** [polkadot-js/api#4218]
use signAsync will get
```js
const submittable = (await api.tx.utility.batch(txs).signAsync(sender, {}))
    console.log("submittable", submittable)
    console.log("tx hash", submittable.toHex())
    console.log("hash 11", submittable.hash.toHex())
```
How use signAndSend get same value with submittable.toHex()? I try print signAndSend the result, just can get tx hash.
Any help is appreciated.

**Comment by jacogr** [comment]
``js
const tx =  api.tx.utility.batch(txs);

tx.aignAndSend(..., () => {
  // tx after signing
  console.log(tx.hash.toHex());
});
```

**Comment by ThreeAndTwo** [comment]
thx~
