### ISSUE TITLE
All events showing up as `undefined.undefined` (t.derive.session undefined)

### ISSUE THREAD

**Issue by sander2** [polkadot-js/api#4219]
As the title says, all events in the network explorer show up as `undefined.undefined`. In the console, I can see that the correct types are being injected at startup. I do see this error in the console though: `Uncaught (in promise) TypeError: t.derive.session is undefined`. We are using metadata v14. It should be easy to reproduce: this is currently happening on the [kintsugi network explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/explorer)

**Comment by jacogr** [comment]
The derive issue is not related to the events, rather it is because the staking module is non-Substrate standard.

The events is due to the name matching on the runtime, the runtime here has a name format not seen before, so adjustments are to be made to find the event definitions in the metadata.

**Comment by sander2** [comment]
@jacogr thank you for making that PR so quickly, it indeed made the derive error go away. However, the main problem with the events showing up as `undefined.undefined` still persists. Should I open a new issue for it, since you closed this one? Or do you think that maybe it is covered by https://github.com/polkadot-js/api/issues/4213 ?

**Comment by jacogr** [comment]
It fixes both. The apps UI has a PR that bumps the version. (You can check against that branch)

**Comment by sander2** [comment]
> It fixes both. The apps UI has a PR that bumps the version. (You can check against that branch, [polkadot-js/apps#6566](https://github.com/polkadot-js/apps/pull/6566))
> 
> it has been tested against the apps UI while investigating.

Yea sorry, my bad, something went wrong when I tried updating the dependency - it indeed works now. Thanks again!
