### ISSUE TITLE
Cannot read deposit events of historical block in Westend

### ISSUE THREAD

**Issue by avolkov-dev** [polkadot-js/api#4223]
We are facing weird behaviour after recent node and polkadot-js library updates.
We can't read `deposit` event of historical blocks in Westend network.
Code to reproduce
```
      const rpcUrl = "westend-rpc-url";
      const provider = new HttpProvider(rpcUrl);
      const api = new ApiPromise({ provider });
      await api.isReadyOrError;
      const hash = await api.rpc.chain.getBlockHash(6308802);
      const txEvents = await api.query.system.events.at(hash);
      const depositEvents = txEvents
          .filter(r => api.events.balances.Deposit.is(r.event))
```
**depositEvents**  collection  **is empty**, but based on  explorer there are some `deposit` event in that block:
https://westend.subscan.io/extrinsic/6308802-2
Note: for recent blocks it is possible to read events this way, so the issue affects only historical blocks

**Comment by jacogr** [comment]
What is your blockhash that is problematic?

**Comment by avolkov-dev** [comment]
`0xd514092a29a4b0c86aa729e75e4f1915bdfab8039d1c7825ca0cdd72460d28fa`
https://westend.subscan.io/block/6308802

**Comment by jacogr** [comment]
```js
const h = await api.rpc.chain.getBlockHash(6308802);

if (h.toHex() !== '0xd514092a29a4b0c86aa729e75e4f1915bdfab8039d1c7825ca0cdd72460d28fa') {
  throw new Error('Invalid hash');
}

const e = await api.query.system.events.at(h);

console.log(JSON.stringify(e.toHuman(), null, 2))
```

Cannot reproduce with the above connecting to the known endpoints in the apps UI.

**Comment by avolkov-dev** [comment]
i've updated the code:

```
     const depositEvents = txEvents
          .filter(r => api.events.balances.Deposit.is(r.event))`
```
Is there are any depositEvents received?

**Comment by jacogr** [comment]
This won't work...

```js
const depositEvents = txEvents
          .filter(r => api.events.balances.Deposit.is(r.event))
```

The event indexes changes between runtimes. You cannot use current metadata to check for old.

So, you need to use api.at...

```js
const a = await api.at(<hash>);
const e = await a.query.system.events();

const depositEvents = txEvents
          .filter(r => a.events.balances.Deposit.is(r.event))
```

**Comment by avolkov-dev** [comment]
that makes sense. will try that way. thanks

**Comment by avolkov-dev** [comment]
yes, i can read historical events using `api.at(h)`.
Thanks @jacogr
