### ISSUE TITLE
transaction exec success, but use api.rpc.author.submitExtrinsic validate is Transaction is temporarily banned

### ISSUE THREAD

**Issue by ThreeAndTwo** [polkadot-js/api#4229]
I tried to send a transaction, and the https://polkadot.subscan.io/extrinsic/extrinsic_hash display success, but the api.rpc.author.submitExtrinsic validate shows info is Transaction is temporarily banned, the same time the account amply supported with funds. why? How should I fix this? 

Here are the details
```js
const submittable = (await api.tx.system.remark(remarkInfo).signAsync(account, {}))
const tx = await submittable.send()

console.log(api.rpc.author.submitExtrinsic(submittable.toHex()))   
//  RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1012: Transaction is temporarily banned
```

**Comment by jacogr** [comment]
That result is from the runtime, see the checks here - https://github.com/paritytech/substrate/blob/d2a43d47ab7339e70c3448b4553073584cfd61ab/client/transaction-pool/src/graph/rotator.rs#L36-L45

**Comment by ThreeAndTwo** [comment]
so, How should I fix this? add fees?

**Comment by alisivandiy** [comment]
> so, How should I fix this? add fees?
Change Your Provider Server , Or Change Your Signer Account , Or Change Tx Information , it should work 
its just a temporarily banned from provider server . 
The requests you sent to the server were probably high

**Comment by ThreeAndTwo** [comment]
thanks a lot. If happened the same event, I will try it.
