### ISSUE TITLE
Is it possible to query events at a specific block without .at()

### ISSUE THREAD

**Issue by bdmason** [polkadot-js/api#4235]
I'm trying to index data, and as there's over 7 million blocks right now performance is important. I've noticed that `api.query.system.events.at(blockHash)` is a lot slower than `api.query.system.events()`.

Is this because `.at()` is slowing things down (and if so is there an alternative way of doing this)? Or is querying historical blocks inherently slower?

**Comment by jacogr** [comment]
You need to get the metadata at that block to be able to decode it, so it will be slower.

**Comment by bdmason** [comment]
Thanks for the quick response @jacogr
