### ISSUE TITLE
Extrinsic hash from Event, How to ?

### ISSUE THREAD

**Issue by ironoa** [polkadot-js/api#4240]
I'd need to retrieve the `extrinsic hash` from the `event` which I'm subscribed to, is it something possible to do ?

For instance: 
- I'm subscribed to `balances -> Transfer` events, something similar to https://polkadot.js.org/docs/api/examples/promise/system-events, but I cannot correlate that event with the extrinsic that has generated it.
- if I stringify an Event I get something like this: `{"index":"0x0502","data":["16kXdSHkp1ZVDn7aVJTns7gQ45rPTRCang7fLsP2fVpifGV6","15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5",10000000000000]}`. the index section seems to identify just that it is a `balances -> Transfer`.
- Subscan is capable of correlating events and extrinsics, for instance here it is linking the Mulisig -> As_Multi extrinsic with all the events that have been generated by the : https://polkadot.subscan.io/extrinsic/0x8057569286bcaa68b72c7a771ba71340a45af7d59a169039f837fd0c8f0abf5f
- Even PolkadotJs is capable of doing such correlation (block and extrinsic, top right corner)
![image](https://user-images.githubusercontent.com/25957738/142629887-1c4f4f3b-66d2-4127-9186-d421642fd92f.png)

I know also that is possible to do it if you are the one who send the transaction, like here https://polkadot.js.org/docs/api/examples/promise/transfer-events, but in my case I'm not the one who send the transaction. I'm just listening to events.

Any suggestion ?
Thanks

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-map-extrinsics-to-their-events

**Comment by ironoa** [comment]
Thanks.

So basically I am supposed to "manually" scan all the blocks and correlate them with the related EventRecords: `const allRecords = await this.api.query.system.events.at(signedBlock.block.header.hash);`  

Just to double check: there is no way to directly retrieve this information just being subscribed to the event system, i.e. `this.api.query.system.events((events) => { ...`, you then have to "manually" retrieve also the block (that most probably is the latest if no delays have happened) and the EventRecords for that block (to verify).

**Comment by jacogr** [comment]
As detailed here - https://polkadot.js.org/docs/api/cookbook/blocks#how-do-i-view-extrinsic-information - it is better to go from block -> events since you can pass the has to retrieve events at a point. (subscribing to both and hoping they match will work in 99.999% of the cases, until it doesn't. But it is certainly faster that using the events at)
