### ISSUE TITLE
Test api/types fix

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#4241]
So I tried updating dependencies of moonbeam types-bundle to 6.8.2-17 (both api and types), and when I run tsc I still get:

```
node_modules/@polkadot/types/augment/lookup/types-kusama.d.ts:18:31 - error TS2304: Cannot find name 'XcmV2TraitsOutcome'.

18         readonly asAttempted: XcmV2TraitsOutcome;
                                 ~~~~~~~~~~~~~~~~~~

node_modules/@polkadot/types/augment/lookup/types-kusama.d.ts:46:75 - error TS2304: Cannot find name 'XcmV2TraitsError'.

46         readonly asNotifyTargetSendFail: ITuple<[XcmV1MultiLocation, u64, XcmV2TraitsError]>;
                                                                             ~~~~~~~~~~~~~~~~

node_modules/@polkadot/types/augment/lookup/types-kusama.d.ts:315:57 - error TS2304: Cannot find name 'XcmV2TraitsError'.

315         readonly asExecutionResult: Option<ITuple<[u32, XcmV2TraitsError]>>;
```

etc

**Comment by jacogr** [comment]
It is there and augmented, see https://github.com/polkadot-js/api/blob/master/packages/types/src/augment/lookup/types-polkadot.ts#L96

**Comment by joelamouche** [comment]
Stil throwing the same errors with the new api version

**Comment by joelamouche** [comment]
Unfortunately, stil throwing the same errors with the new api version

**Comment by jacogr** [comment]
All types are certainly included. They get used quite extensively elsewhere as actual new-gen type imports. Do you have a minimal reproducible sample?

**Comment by joelamouche** [comment]
- clone moonbeam repo
- `cd moonbeam-types-bundle`
- `npm i --save @polkadot/api@6.9.3-2`
- `npm i --save @polkadot/types@6.9.3-2`
- `npm run build` will throw these errors

**Comment by joelamouche** [comment]
This specific branch will keep the bug, in case we downgrade the types package: https://github.com/PureStake/moonbeam/pull/1018

**Comment by jacogr** [comment]
Thank you, will take a peek.

**Comment by joelamouche** [comment]
It works now thanks :)
