### ISSUE TITLE
proxy and proxyAnnounced never recognize hash of previously submitted transaction

### ISSUE THREAD

**Issue by sicco-moonbeam** [polkadot-js/api#4245]
I'm trying to use the proxyAnnounce and proxy/proxyAnnounced extrinsics to transfer some funds; but I keep running into the error `proxy.Unannounced:  Announcement, if made at all, was made too recently.` even though sufficient blocks have passed. I suspect there's some kind of bug in the type resolution.

Example code is as follows. First, I'm creating the announce, as follows:

```
async announceTransfer(delegate: KeyringPair, sourceAccount: string,  targetAcct: string, transferAmount: bigint){
        logger.debug(`Announcing transfer of ${transferAmount} from ${sourceAccount} to ${targetAcct} via ${delegate} `);

        /** The transaction to transfer the specified amount to the targetaccount. */
        const tx = api.tx.balances.transfer(targetAcct, transferAmount);
        /** The hash for the real call */
        const txHash = tx.toHex();

        /** The announce transaction */
        const announceTx = api.tx.proxy.announce(sourceAccount, txHash);

        await announceTx.signAndSend(delegate);

        return ({transferTx: tx, announceTx: announceTx});

    }
```

This call succeeds without issue, I see a successful announceExtrinsic in the polkadot.js app.

Next, I wait the required amount of blocks (in this example, my delegate is set with a delay of 1 block); and then I try to call proxy or proxyAnnounced (both produce the same result):

```
async dispatchAnnouncedTransfer(delegate: KeyringPair, sourceAccount:string, txHash: `0x${string}`){

        logger.debug(`Dispatching announced transfer from ${sourceAccount} by ${delegate}`);

        /** The announced transaction */
        const announcedTx = MoonbeamClient.api.tx.proxy.proxyAnnounced(delegate, sourceAccount,'Any', txHash);
        await announcedTx.signAndSend(delegate)

     }
```
     
 Depending on what I pass as ```txHash```, this produces different results.
 
 * If I pass in simply transferTx.toHex() or transferTx.hash.toHex() to the proxyAnnounced, I get:
 
 ```Error: createType(Call):: Call: failed decoding proxy.proxyAnnounced:: Struct: failed on args: {"delegate":"AccountId","real":"AccountId","force_proxy_type":"Option<ProxyType>","call":"Call"}:: Struct: failed on call: Call:: findMetaCall: Unable to find Call with index 0x4102/[65,2]```
 
 Which leads me to believe that it simply can't parse the associated hex.
 
 * If, instead, I pass in transferTx.method.toHex(), I don't get that error, but instead I always get:
 
 ```proxy.Unannounced:  Announcement, if made at all, was made too recently.```
 
 even though multiple blocks have passed.
 
 I suspect it's failing to find a match on the transferTx.method.toHex(), and is instead expecting transferTx.toHex() but since that's failing to parse, I can't provide that.
 
 Would appreciate some help with this...

**Comment by jacogr** [comment]
It is the call hash. So always `tx.method.toHex()`

**Comment by sicco-moonbeam** [comment]
Thanks for the response @jacogr . 

If I try to pass `tx.method.hash` into proxyAnnounced, I get:

`Error: createType(Call):: Call: failed decoding proxy.proxyAnnounced:: Struct: failed on args: {"delegate":"AccountId","real":"AccountId","force_proxy_type":"Option<ProxyType>","call":"Call"}:: Struct: failed on call: Call:: findMetaCall: Unable to find Call with index 0xab6b/[171,107]`

Same thing for `tx.method.hash.toHex()`

**Comment by jacogr** [comment]
- the hash for lookups is stored on-chain, i.e. `tx.method.hash`
- the input to it is a `Call`, i.e. `tx.method`

Same approach with e.g. multisigs, initial is only hash, final is the method

**Comment by sicco-moonbeam** [comment]
hey @jacogr Unfortunately, it's still failing for me.

I'm issuing this call to announce:
`api.tx.proxy.announce(sourceAccount, tx.method.hash);`

and then this call to proxyAnnounced:
`api.tx.proxy.proxyAnnounced(delegate, sourceAccount,'Any', tx.method.toHex());`

and that fails with:

`proxy.Unannounced:  Announcement, if made at all, was made too recently.`

**Comment by sicco-moonbeam** [comment]
@jacogr Actually, it IS working now - I had a different issue at the end as well. Thanks!
