### ISSUE TITLE
Finality is not reported if block is finalized immediately

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/api#4249]
Context: https://github.com/PureStake/moonbeam/pull/1012

When subscribing to transaction lifecycle it is common to get an event for `inBlock` and later, another event for `finalized` as demonstrated https://polkadot.js.org/docs/api/examples/promise/transfer-events among other places. This is how finalization typically works in GRANDPA chains.

However, it is also possible for a block to be finalized immediately upon import. This would be the case for eg Tendermint. Or, more simply, Substrate's manual seal which is commonly used in integration tests.

**When a block is finalized immediately upon import, Polkadot JS does not send the `finalized` event.**

**Comment by jacogr** [comment]
How do you mean "does not send the finalized event"?

**Comment by JoshOrndorff** [comment]
I mean, when I do a subscription like this, the last update I get tells me the transaction is `inBlock`.

```ts
  // Do the transfer and track the actual status
  api.tx.balances
    .transfer(recipient, AMOUNT)
    .signAndSend(alicePair, { nonce }, ({ events = [], status }) => {
      console.log('Transaction status:', status.type);

      if (status.isInBlock) {
        console.log('Included at block hash', status.asInBlock.toHex());
      } else if (status.isFinalized) {
        console.log('Finalized block hash', status.asFinalized.toHex());

        process.exit(0);
      }
    });
```

> Per update only 1 comes through from the subscription.

Sorry, what update do you mean? If the designed behavior is that only one of `inBlock` and `finalized` gets sent to the subscriber, then I would argue that it should be `finalized` that is sent because that is the further stage, and it implies `inBlock`. However, `inBlock` does not imply `finalized`.

**Comment by jacogr** [comment]
It is unlikely to change. It reacts to the first event where it can retrieve system events. 

At best you can ask for an enhancement to (optionally) configure the behavior to listen for finality. PRs welcome.

**Comment by jacogr** [comment]
Closing as answered - feel free to open a PR with a passed config option to change the behaviour, however the base functionality as-is won't change here as described above. Reasons -

- at least a 3 blocks delay
- finality may lag (and then we end up with a 50-block delay)

And yes, it is well understood that finality is final, however making this change default without optionality will break the ecosystem users' code.
