### ISSUE TITLE
Can't sent Polkadot from wallet to metamask

### ISSUE THREAD

**Issue by deivooo** [polkadot-js/api#4250]
Hi,

I got peoblem with sending money ( all from account ) to metamask. 
When i'm trying to sent my DOT's i see error : 
![dawd](https://user-images.githubusercontent.com/94858742/142903167-71bd58c5-d6fc-4ab2-a260-c51826418a55.PNG)

Do you now what could be problem?

Thanks!

**Comment by jacogr** [comment]
Metamask is an Ethereum wallet. Polkadot is not a token on the Ethereum network.

**Comment by deivooo** [comment]
Hello, thank you :) Already done - sent to binance account. Solved!
