### ISSUE TITLE
How to decode event.data to the 'sql-useful' format?

### ISSUE THREAD

**Issue by manylov** [polkadot-js/api#4253]
Hi, I want to store events data for the indexation and future sql queries.

Taken for example event #7761600-0 https://polkadot.subscan.io/block/7761600?tab=event
phragmenelection (NewTerm)

```js
const historicalApi = await api.at('0x4e55c8da55347b0a6e09400411900aba4becb6518258d9bfc6aca75e2d1e9293')

const events = await historicalApi.query.system.events()

const newTermEvent = events.find((e) => e.event.method === 'NewTerm')

const eventData = newTermEvent?.event.data
```

eventData.toHuman() output:
```js
[
    [
      '1hCMdtRsaRA4ZTEKpPKPvEjK9rZpGhyFnRHSDhqFMCEayRL',
      '234,582,102,953,828,765' // not useful for store in db
    ],
    [
      '12NLgzqfhuJkc9mZ5XUTTG85N8yhhzfptwqF1xVhtK3ZX7f6',
      '139,095,882,809,362,011'
    ]
...
]
```

eventData.toJSON() output: 
```js
[
  [
    [
      '1hCMdtRsaRA4ZTEKpPKPvEjK9rZpGhyFnRHSDhqFMCEayRL',
      '0x00000000000000000341672e053a219d'
    ],
...
]

```

How to decode eventData to the appropriate output like this:
```js
[
  [
    [
      '1hCMdtRsaRA4ZTEKpPKPvEjK9rZpGhyFnRHSDhqFMCEayRL',
      '234582102953828765'
    ],
    [
      '12NLgzqfhuJkc9mZ5XUTTG85N8yhhzfptwqF1xVhtK3ZX7f6',
      '139095882809362011'
    ],
```
?

**Comment by jacogr** [comment]
- toHuman is meant for human-consumption only
- toJson is meant to encode into a format useful for RPC

You would need to inspect and probably toString on the tuple fields, if that is useful.

**Comment by manylov** [comment]
And the only way to do it is to parse and decode nested data "manually" for all different types of events? Sounds difficult.

**Comment by jacogr** [comment]
Closing. The API only provides limited capabilities that allows it to interact with chains - any storage-related requirements are outside the scope.
