### ISSUE TITLE
Extrinsic and event types after Metadata v14

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/api#4254]
Extrinsics that take other extrinsics as parameters have type conflicts with the metdata-generated interfaces (`batch`, `sudo`). The snippet [here](https://polkadot.js.org/docs/api/cookbook/tx/#how-can-i-batch-transactions) wouldn't compile for instance.

Considering that snippet, `api.tx.balances.transfer(addrBob, 12345)` is a `SubmittableExtrinsic<"promise">`, whereas in our parachain `batch` expects an array of `InterbtcRuntimeParachainCall` now. `createType` doesn't solve this:
```
this.api.createType<InterbtcRuntimeParachainCall>("InterbtcRuntimeParachainCall", tx)
=>
REGISTRY: Unable to resolve type InterbtcRuntimeParachainCall, it will fail on construction
```
**Question 1**: What would be the correct way to convert `SubmittableExtrinsic<"promise">` to `InterbtcRuntimeParachainCall`?

----

Moreover, `api.query.system.events` now returns an array of `FrameSystemEventRecord`, whose `event` field is `InterbtcRuntimeParachainEvent` (an enum) rather than `AugmentedEvent<ApiTypes, T>`. Example:
```
export interface InterbtcRuntimeParachainEvent extends Enum {
    readonly isSystem: boolean;
    readonly asSystem: FrameSystemEvent;
    readonly isSudo: boolean;
    readonly asSudo: PalletSudoEvent;
    readonly isUtility: boolean;
    readonly asUtility: PalletUtilityEvent;
```

**Question 2**: What would be the correct way to convert `InterbtcRuntimeParachainEvent` to `AugmentedEvent<ApiTypes, T>`, so the `.is(...)` method can be used?

**Comment by jacogr** [comment]
Both Call and Event should be mapped to their API-native version. This seems like somewhere (call augmentation) they are not mapped.

**Comment by savudani8** [comment]
Thanks, I'll step through the code tomorrow to see where augmentation is going wrong for Call and Event

**Comment by jacogr** [comment]
EventRecord is actually fine - the issue is that the event type mapping needs to fall to, well, `Event`. See the Substrate example that does work as expected - https://github.com/polkadot-js/api/blob/master/packages/types/src/augment/lookup/substrate.ts#L59-L63

Honestly, nothing off-hand that springs to mind here. But something is wrong somewhere.

**Comment by jacogr** [comment]
@savudani8 Is this still an issue in your generated types? I would assume so?

**Comment by savudani8** [comment]
No longer an issue, turns out I was using a slightly outdated version of `api`!
