### ISSUE TITLE
Metadata format for messages/constructors in a `.contract` bundle changed

### ISSUE THREAD

**Issue by cmichi** [polkadot-js/api#4255]
The metadata supplied for a contract in the `.contract` bundle will change a bit.

Specifically the messages and constructors exposed by a contract were previously denoted with
```
"name": ["foo", "bar"]
```

Now they are instead denoted with
```
"label": "foo"
```

I've attached two files:
* [flipper.contract.old.zip](https://github.com/polkadot-js/apps/files/7590311/flipper.contract.old.zip) ‒ the old metadata version of our `flipper` example.
* [flipper.contract.new.zip](https://github.com/polkadot-js/api/files/7593452/flipper.contract.new.zip) ‒ the new one.

If you `diff flipper.contract.new flipper.contract.old` the changes are visible.

The PR on ink! side which does this is https://github.com/paritytech/ink/pull/923, we will hold-off merging it until the UI supports these changes. I'll also create follow-up issues for ask! and Solang after the new format is supported.

**Comment by cmichi** [comment]
Thanks for the quick reply! 

We've bumped the metadata version to `V2` for those changes, I updated the `flipper.contract.new.zip` file in the description of this PR.

**Comment by jacogr** [comment]
Brilliant. Will try to get support into the next API release (Monday), depending on other chaos.

**Comment by jacogr** [comment]
Do you maybe have an example with events? I am assuming it also has the label change, but would like to verify and add it to the tests as well.

**Comment by cmichi** [comment]
Good point, I uploaded the `erc20` here: [erc20.contract.zip](https://github.com/polkadot-js/api/files/7666640/erc20.contract.zip). It has some events.
