### ISSUE TITLE
How to traverse older events without querying range?

### ISSUE THREAD

**Issue by sirius651** [polkadot-js/api#4258]
Hi, it's related with this #3887

```
await apiData.query.system.events.range(['0x6de1501ba660b975a2fa2425425fe57e04c8ec8691b6b69f688d8dd92dc43320','0x5de5306c9afcf8d66151889349f903e63ae759227b6e5ee5fcbb2850b7eadb1b'])
```

without `range` function, how can I retrieve events in older blocks?

if the node is not exposing an unsafe rpc, is there no way to search for existing blocks?

**Comment by jacogr** [comment]
No. That is the only range-based RPC. (There are good reasons why it is not exposed, unless you run with the unsafe flag, since it is very heavy on the node)

**Comment by sirius651** [comment]
@jacogr okay so, could you advice which method should I call to retrieve events in an existing block?

**Comment by jacogr** [comment]
```js
const apiAt = await api.at(<blockHash>);
const events = await apiAt.query.system.events();

// alternative, @deprecated - the above allows everything at that point
const events = await api.query.system.events.at(<blockHash>);
```

Since you need the specific metadata at that point, the apiAt retrieves it once for that point and decodes using that.

**Comment by jacogr** [comment]
Closing as answered.
