### ISSUE TITLE
HttpProvider doesn't work

### ISSUE THREAD

**Issue by xcaptain** [polkadot-js/api#4259]
I'm using Http provider to interact with my chain, but I got some error.

```
2021-11-25 15:36:55        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2021-11-25 15:36:56        API/INIT: Error: FATAL: Unable to initialize the API: Cannot convert undefined or null to object
    at ApiPromise.value (/home/joey/Project/test1/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

below are my test code
```javascript
const { ApiPromise, HttpProvider } = require('@polkadot/api');

async function test1() {
    const httpProvider = new HttpProvider("http://127.0.0.1:9933");
    const api = await ApiPromise.create({
        provider: httpProvider,
    });
    const data = await api.rpc.chain.getBlock();
    console.log(data.hash.hash.toHex());
}

test1();
```

After some simple debugging, I found that error was throwed at

https://github.com/polkadot-js/api/blob/5dc0b38881d6cc709597c6131b5b3f7078f776fd/packages/api/src/base/Decorate.ts#L357-L358

At this time `this._rpc[section]` is undefined, so `delete this._rpc[section][method]` would throw error.

I'm not quite familiar with polkadot-js, but I think add some check before would solve this problem, such as:
```javascript
if ((this._rpc as Record<string, Record<string, unknown>>)[section]) {
    delete (this._rpc as Record<string, Record<string, unknown>>)[section][method];
}
if (this._rx.rpc as Record<string, Record<string, unknown>>)[section]) {
    delete (this._rx.rpc as Record<string, Record<string, unknown>>)[section][method];
}
```

**Comment by jacogr** [comment]
Thanks for the detail here.

Normally it shouldn't be since each section should have methods - however in this case, it fails on `beefy` which only has a single method, a subscription. So it is never decorated initially, nor available since it is Http. 

Will make a fix along the same lines as suggested. (We only need a single check, the 2 sections are equivalent)
