### ISSUE TITLE
Custom Proxy Type doesn't work with the api and TS

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#4264]
In Moonbeam, we added two new Proxy Types: https://github.com/PureStake/moonbeam/pull/923/files# (Balances and AuthorMapping)
But the typing prevents me form using those in the addProxy call. I tried adding those to my custom types but it seems the addProxy typing is static in the api: `/api/packages/api/src/augment/tx.ts` line 2114

@jacogr should I add the new Proxy Types here?

**Comment by jacogr** [comment]
It is not static - the augmentation is done from the Substrate metadata, i.e. `api/src/augment/tx.ts` is generated from the metadata itself.

**Comment by joelamouche** [comment]
So you are saying that it is generated from the default ProxyType in the substrate repo, right? Is there a way to override that without changing ProxyType in the substrate repo (which would impact all parachains)?

**Comment by joelamouche** [comment]
@jacogr Should I change the ProxyType for all parachains or should we add a way to override it?

**Comment by jacogr** [comment]
You cannot override it, e.g. in interfaces. It is from the metadata.

So when you generate type interfaces for your chain, and use those types (i.e. have something like `import '@my-scope/my-types-package/augment';`), it should reflect the new type. By default the API augmentation (which includes `import '@polkadot/api/augment'` reflects the base substrate types)

I am worried that the TS augmentation may bump into this though - https://github.com/polkadot-js/api/issues/2338

**Comment by joelamouche** [comment]
I'm sorry tbh I don't completely understand your answer. Are you saying I should change the ProxyType in Substrate?

**Comment by joelamouche** [comment]
@jacogr Thanks for the PR but unfortunately it doesn't solve my problem because I still need the augmented type for the other tests and importing it imports it for the whole test sequence

**Comment by jacogr** [comment]
You will need to add your augmented types for TS mapping - the API itself only have the Substrate versions from metadata. aka in Substrate -

- `ProxyType` - that is the pre metadata v14 version
- `NodeRuntimeProxyType` - that is the one in-use for Substrate chains

For instance in Kusama/Polkadot the specific types are - `KusamaRuntimeProxyType` & `PolkadotRuntimeProxyType` (each of these different to the original `ProxyType`)
