### ISSUE TITLE
Can it generate documentation corresponding to the substrate side?

### ISSUE THREAD

**Issue by Cupnfish** [polkadot-js/api#4265]
I am a developer using substrate, I developed a palltes and wrote documentation ( which is Rust's `///` documentation) in the call as well as the event, storage and other parts in it, I would like to know how I should be able to see this documentation in the interface generated by js when I use polkadot-js?

**Comment by jacogr** [comment]
Indeed. See https://polkadot.js.org/docs/api/examples/promise/typegen which generated TS interfaces for your chain (which at least VSCode can pickup)
