### ISSUE TITLE
Exposed derived storage on API

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#427]
Basically, have an api endpoint, which takes multiple storage values and runs it through a derivation function, returning a result. And example may be of votingBalance, we could do (pseudo-ish code) -

```
{
  section: 'balance',
  method: 'votingBalance',
  inputs: ['balances.freeBalanceOf', 'balances.reservedBalanceOf`],
  derive: (free, reserved) => free.add(reserved)
}
```

and then

```
api.derive.balances.votingBalance(ALICE).toString();
```

Basically the API will add these and attach them to the derive endpoints. We def. need something to this effect, either we write code or have it more templated. (And needs to support both API types)

EDIT: The above example is already hairy, how to we cater for params passed in?

**Comment by amaurymartiny** [comment]
Closed in #564 and #540
