### ISSUE TITLE
Constructing BTreeMap with enum keys by name rather than index

### ISSUE THREAD

**Issue by jonmattgray** [polkadot-js/api#4279]
Using `"@polkadot/api": "^5.9.1"`

I'm trying to run a transaction that includes a `BTreeMap` with keys that are enums. I'm finding I can only set the enum by index rather than name. If I construct the map like so it works:
```
new Map(Object.entries({ 0: 'ACCOUNT_ID' }))
```

However using the enum name causes an error:
```
new Map(Object.entries({ Admin: 'ACCOUNT_ID' }))

MAP: Failed to decode key or value: Unexpected token A in JSON at position 0
VEC: Unable to decode on index 0 Tuple: failed on 0:: Unexpected token A in JSON at position 0
```

Is there a different way I should be constructing the Map? Or something wrong with my types (see below)?

Substrate
```
pub enum Role {
    Admin = 0,
    NotAdmin = 1,
}

type RoleKey = Role;

run_process(
    origin: OriginFor<T>,
    inputs: Vec<T::TokenId>,
    outputs: Vec<(
        BTreeMap<T::RoleKey, T::AccountId>, # the bit we care about
        BTreeMap<T::TokenMetadataKey, T::TokenMetadataValue>,
    )>,
)
```

types JSON
```
{
    RoleKey: 'Role',
    Token: {
      roles: 'BTreeMap<RoleKey, AccountId>',
    },
    Role: {
      _enum: ['Admin', 'NotAdmin'],
    },
}
```

**Comment by jacogr** [comment]
It maps the entries directly to a map, i.e. there is no translation done from the type that the map contains and the values the string represents.

So unless there is specific logic added to cater for enums and then doing a mapping on the entries in those cases, the actual index values are to be specified.

**Comment by jonmattgray** [comment]
Thanks, I'll stick with using index then and our API layer will handle converting enum string -> index
