### ISSUE TITLE
New era start event?

### ISSUE THREAD

**Issue by manylov** [polkadot-js/api#4280]
Hi, how to detect new era start? Can't find event, do i need to compare with the previous block era?

**Comment by jacogr** [comment]
There is an event that marks the end of a session, i.e. new one starts - https://polkadot.js.org/docs/substrate/events#session

Together with the number of sessions per era (beware new eras can be forced), you can determine when a new era is due.

Additionally grandpa alerts when new authorities come into play - https://polkadot.js.org/docs/substrate/events#newauthoritiesvecspfinalitygrandpaapppublicu64

**Comment by jacogr** [comment]
Closing as answered.
