### ISSUE TITLE
Hash value for transaction returned true

### ISSUE THREAD

**Issue by OnigiriJack** [polkadot-js/api#4282]
Hash value for a successful [transaction ](https://westend.subscan.io/extrinsic/0xcff0edc2d39aa6846ecdc81e7c7fd331f2d04809d231eb9a8a7381071225fd3f)was returning true instead of a type 32. Is this normal behaviour? 

<img width="396" alt="スクリーンショット 2021-12-03 16 46 08" src="https://user-images.githubusercontent.com/35797565/144565815-d0d7bc8e-c4eb-4e7f-8dd3-3ab789cda366.png">

Code snippet
```typescript
const TxHash = await new Promise((resolve, reject) => {
				client.tx.utility
					.batch(rewardTxs)
					.signAndSend(account.data.address, { signer: injector.signer }, ({ status }) => {
						if (status.isInBlock) { resolve(status.isInBlock) }
					})
			})
			console.log(TxHash)
			return {
				hash: TxHash,
				status: "REWARDS CLAIM IN PROGRESS",
			}

```

**Comment by jacogr** [comment]
In tour example, you resolve the promise with `resolve(status.isInBlock` which is a boolean. So, yes, it would be true based on how your code is written.

**Comment by jacogr** [comment]
Closing. The code provided returns the value as logged.
