### ISSUE TITLE
Custom RPC method error: Invalid params: invalid type: string "0xffffffff", expected an array

### ISSUE THREAD

**Issue by clangenb** [polkadot-js/api#4283]
I have defined a custom rpc and pass it to the api. It used to work before. After changing the argument type form type `Hash` to the `CommunityIdentifier` given below, I get the following error.

```
RPC-CORE: getBusinesses(cid: CommunityIdentifier, at?: Hash): Vec<BusinessData>:: -32602: Invalid params: invalid type: string "0xffffffff", expected an array of length 4.

```

I don't understand why this error is thrown due to two reasons:
1. I pass a proper type to the rpc created with `registry.createType`.
2. The string is the correct representation of the second field `digest`, which should be created.
3. I evaluated that the `cid.toU8a()` yields the expected output, when comparing it to the rust equivalent.

```
  CommunityIdentifier: {
    geo_hash: 'GeoHash',
    digest: 'CidDigest'
  },
  GeoHash: '[u8; 5]',
  CidDigest: '[u8; 4]',
```

Link to the failing test: https://github.com/encointer/encointer-js/blob/03b6cd11ae64bddc7123520f259a4fba718da6b9/packages/node-api/src/e2e.ts#L39

**Comment by jacogr** [comment]
This on the node side - ensure you have the correct serde attributes on the type otherwise it expects a `[0, 1, 2, 3]` encoding as opposed to a `0x01020304` encoding.

**Comment by clangenb** [comment]
Oh, thanks for the swift response, I would have never guessed that. 

However, I'd actually want it to expect an array, but I guess this is overwritten because `[u8; 4]` does coincidentally map to some kind of 32bit hash, which defaults to a `0x01020304` encoding? I guess this because it seems to work for the other field, which is `[u8; 5]`.

**Comment by clangenb** [comment]
Thanks again for the input, I was able to solve it on the rust side. However, I was surprised that I could not find a predefined rust-attribute in substrate that makes the serialization compatible with polkadot-js.

This is my solution in case anybody needs it: https://github.com/encointer/pallets/pull/86

**Comment by jacogr** [comment]
Ummm, weird. So H256/Hash for instance is `[u8; 32]`, so it is the same thing, just a few more bytes. Haven't dug how that is de-serialized in Substrate, but whatever is done there should be "predefined" somewhere.
