### ISSUE TITLE
Call hash differs in UI vs created with API

### ISSUE THREAD

**Issue by Swader** [polkadot-js/api#4284]
When doing a batch of transfers, I encounter a discrepancy.

```
fs.writeFileSync(
    "call-data.txt",
    api.tx.utility.batchAll(calls).method.toHex()
  );

  console.log(api.tx.utility.batchAll(calls).hash.toString());
```

Putting the [call data I get above](https://gist.github.com/Swader/f58745cd81b0b0e131db4a09ff5fcd30) into Polkadot JS Apps UI's Decode, I get the call hash `0x862f23845b49561f9ad932318713321b218efb51cd1f0b78c746841e76d3a373`, whereas the final line `console.log` with `hash.toString()` gives me `0xe7bf79e30039664fcc1931b94ee9534175a3d5a8c848cf4491d6a2638d96b64c`.

Where is my mistake?

**Comment by jacogr** [comment]
`console.log(api.tx.utility.batchAll(calls).method.hash.toString());`

**Comment by jacogr** [comment]
Closing. Answered.
