### ISSUE TITLE
after installing @polkadot/api package, I got this error and can't open my expo app. "Conversion from 'BigInt' to 'number' is not allowed."

### ISSUE THREAD

**Issue by jinsheng323** [polkadot-js/api#4317]
![Screen Shot 2021-12-10 at 3 23 43 PM](https://user-images.githubusercontent.com/62555931/145637318-c41d39dc-c737-4754-9eae-5524cdb54706.png)

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/api/issues/4290

**Comment by khuddite1012** [comment]
@jacogr  that is not working

**Comment by jacogr** [comment]
If it "doesn't work" - then contribute to the existing issue, adding more issues doesn't help anybody, it just creates noise. At leats one RN app has solved their issues as linked (and verified), so, there is no reason why others are different. There is an existing solution linked.
