### ISSUE TITLE
Fee calculation details

### ISSUE THREAD

**Issue by maltekliemann** [polkadot-js/api#4324]
According to the [polkadot-wiki](https://wiki.polkadot.network/docs/learn-transaction-fees), the transaction fee consists of a per-byte fee and a weight fee (plus tips).

Unfortunately, I can't find anything in the documentation on where this type of information is stored for individual transactions, except that according to **Getting started** > **Transaction subscriptions** > [Payment Information](https://polkadot.js.org/docs/api/start/api.tx.subs) 

```js
paymentInfo = tx.paymentInfo(...);
partialFee = paymentInfo.partialFee
```

gives you the weight fee. But I would like to take the per-byte fee into account as well. This could be computed using `api.consts.transactionPayment.transactionByteFee`. But how do I get the byte representation of a transaction?

**Comment by jacogr** [comment]
`console.log(tx.toU8a().length)`

**Comment by maltekliemann** [comment]
@jacogr Thank you! Unfortunately, the results are not as expected. It seems to me that `partialFee` does not only include the weight fee, but also the length fee.

For example, check out this transaction: https://westend.subscan.io/extrinsic/0x30b321fb2187755a3c0fab4d5aa11db04e8682c9985cf15424b3de88b6f646d5

The `partialFee` is equal to `15600001486`, and the length fee (computed using the method stated above) is `14600000000`. But subscan.io specifies the fee as 0.015600001486 WND, i.e. exactly the `partialFee`.

What am I missing?

**Comment by jacogr** [comment]
For weight calculation logic, you would need to refer to the Rust code to see what Substrate defines for each field. It has been ages since I looked in these, so honestly can't say how Substrate does it at all.

**Comment by maltekliemann** [comment]
Ok, got it: https://wiki.polkadot.network/docs/build-node-interaction

> In the `balances.transfer` extrinsic, the `partialFee` item is the transaction fee. It is called "partial fee" because the total fee would include the tip field.
