### ISSUE TITLE
I have a question about backward compatibility of runtime upgrades.

### ISSUE THREAD

**Issue by mone-d** [polkadot-js/api#4327]
I have a question about the Polkadot runtime upgrade.

In my app, I am making an API request to get the latest RuntimeVersion and Metadata.
Like this.
```javascript
const { ApiPromise } = require('@polkadot/api');
const api = await ApiPromise.create();  // I believe I'm getting the current RuntimeVersion and metadata here.

const block = api.rpc.chain.getBlock('0xXXXXX');

console.log(block.number);
```

Is it possible that the response format will change as the runtime version is upgraded?
However, we assume that our SDK and node versions will not change.

For example, if the `block number` is renamed from `block.number` to `block.blockNumber`, then `block.number` will be undefined.

Is there anything I can do about this?

**Comment by jacogr** [comment]
There are 2 parts, runtime and node -

- runtime is on-chain and changes with each release, hence the use of api.at when for instance reading state
- the node is responsible for the RPCs and their definitions, it is not in the runtime

Generally the RPCs are relatively stable (apart from contracts). In this case the header format may change, it hasn't, but it could.

**Comment by mone-d** [comment]
@jacogr 
Thank you very much, that makes sense.
In addition, I would like to ask, when we create a transaction, we get the runtime version as well.
When I signed the transaction and broadcasted it, the following error was returned if the runtime version on the chain was different.
```
Transaction is temporarily banned
```
Is there any way to make the transaction broadcastable in this case, for example, by creating the transaction without specifying the runtime version?

**Comment by jacogr** [comment]
The spec version is encoded into the transaction payload which is signed. If it changes, all transactions are invalid. (Since methods may move around, have different parameters, etc.)

**Comment by mone-d** [comment]
Thanks!!
