### ISSUE TITLE
How can I calculate transaction hash at offline?

### ISSUE THREAD

**Issue by mone-d** [polkadot-js/api#4338]
I am trying to create an app to sign transactions offline and send.

But I am having trouble with the polkadot library because it gets Metadata and RuntimeVersion from the blockchain.

I was able to successfully sign offline by referring to the following issue.
https://github.com/polkadot-js/api/issues/1421

However, I was not able to run createType offline, so I rewrote the signature as follows.
````javascript
async function offlineSign(payload) {  // 'payload' is hexed ExtrinsicPayload object.
    const signature = keyPair.sign(hexToU8a(payload).slice(1), { withType: true });
    const sigHex = u8aToHex(signature);

    /** I want to calculate the transaction hash here. **/

    return sigHex;
}
````

After creating the signature, I know that I can get the hash for the `tx.addSignature` as follows, but I can't do it offline because I pass `Registory` and `Metadata` to `createType` in the process of `addSignature`. I couldn't do it.
```javascript
console.log(tx.hash.toHex())
```

How can I use `createType` at offline or can I calculate transaction hash at offline?

**Comment by mone-d** [comment]
@jacogr 
Thanks for the answer.

I know how transaction hash is calculated from transaction data. But I don't know how to create transaction data at offline without `metadata` and `registry`.

**Comment by mone-d** [comment]
But I don't know how to create transaction data by using polkadot-js/api

**Comment by jacogr** [comment]
The transaction is constructed _based_ on the registry - 

1. the types required for the transaction is part of the metadata, i.e. it details the different transaction parts and the types (as well as having the type definitions for those)
2. it details the signed extensions (part of the transaction data and payload that generates the signature) that needs to go into the transaction

So the Extrinsic itself is completely driven by the metadata, see 

- Signature being dynamic from extensions - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicSignature.ts#L32-L48
- Payload being dynamic from extensions - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicPayload.ts#L25-L38
