### ISSUE TITLE
Recreate Registry from file

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#4347]
In order to sign tx offline, I want to be able to rebuild the registry from a file. How can I do that? Thanks in advance

**Comment by jacogr** [comment]
Something like this _may_ work (I have not looked at what the API does to init, so this is mostly from memory) -

1. `cont registry = new TypeRegistry()`
2. `const metadata = new Metadata(registry, <hex data>)`
3. `registry.setMetadata(metadata)`

That should yield a mostly operable registry.

**Comment by joelamouche** [comment]
Thanks @jacogr I will try. What is the <hexData> here? How do I obtain it form api.registry?

**Comment by joelamouche** [comment]
(api.rpc.state.getMetadata()).toHex() ?

**Comment by joelamouche** [comment]
I don't think using metadata alone suffices but I used the initRegistry function you had in api: check it out in the createAndSendTx.ts https://github.com/PureStake/cli-ts-signer/pull/12/files
