### ISSUE TITLE
Implement HTTP polling to simulate WS-like subscriptions

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#435]
This is very ineffective, adds load to the node and delayed operation since we are not operating in a push fashion. However some users do prefer an HTTP API. So simulate subscriptions -

1. poll for new heads via `chain_getHead`
2. keep track of "subscriptions" (managed inside provider)
3. on new head, retrieve state changes via `state_getStorage` as per subscriptions, push results

Possibly just trap the subscription methods and hook into the `chain_getHead` loop, so it is transparent to the user. (Using subs in this way would come with an "inefficient" warning)

**Comment by jacogr** [comment]
For some subscriptions, it is exceedingly difficult if not impossible - for instance `author_subscribeAndWatch`

**Comment by amaurymartiny** [comment]
Alternative:
1. poll for new heads via `chain_getHead`
2. keep track of "subscriptions" (managed inside provider)
3. on new head, make a call `api.query.system.events()`, parse the events, and make `state_getStorage` calls only for the relevant parts of state that changed (assuming all state change emit events).

^ that's the approach I'm taking for LightApi. I'll think about how to merge these 2, or at least use the same underlying logic (aka the "on this do that" logic).

**Comment by jacogr** [comment]
Not all state changes emit events. There are logs though for the state root changes, however in reality I have not actually seen these come through as of yet.

**Comment by jacogr** [comment]
Also refer to https://github.com/polkadot-js/api/issues/440#issuecomment-444760455 (metadata, polling)

**Comment by jacogr** [comment]
Closing for now. Can re-open if we ever plan on doing this.
