### ISSUE TITLE
council instances mapping no longer works

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#4373]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura-rpc-3.aca-api.network%2Fws#/council/motions failed to load with error
`TypeError: Cannot read properties of undefined (reading 'proposalHashes')`

<img width="1050" alt="Screen Shot 2021-12-21 at 8 37 16 PM" src="https://user-images.githubusercontent.com/1201310/146890058-32c3e36a-20b4-4b39-891b-73b486ee1884.png">

I think it should be passing the normalized name (i.e. council) instead of the instance name.

It will be helpful to have some tests to ensure this scenario is supported.

**Comment by jacogr** [comment]
Contributions for derive tests would be welcomed.

**Comment by xlc** [comment]
I spent some time trying to fix it but the code is a bit complicated to figure out exactly what exactly all the `section`s are 😅

**Comment by jacogr** [comment]
Will release 7.0.2 and apply to the UI as well.
