### ISSUE TITLE
How to get transaction hash? 

### ISSUE THREAD

**Issue by NetGodFather** [polkadot-js/api#4380]
How to obtain the transaction hash of transactions created through “api.tx.utility.batchAll(calls)” after they are in block.

Code like this :

> const batchExtrinsic = api.tx.utility.batchAll(calls);
> await batchExtrinsic.signAndSend(sender, ({ events = [], status }) => { ... } );

**Comment by NetGodFather** [comment]
Refer to this page introduction: https://polkadot.js.org/docs/api/examples/promise/make-transfer/
```
  // Create a extrinsic, transferring 12345 units to Bob
  const transfer = api.tx.balances.transfer(BOB, 12345);

  // Sign and send the transaction using our account
  const hash = await transfer.signAndSend(alice);

  console.log('Transfer sent with hash', hash.toHex());
```

Code like this:
```
const batchExtrinsic = api.tx.utility.batchAll(calls);
const hash = await batchExtrinsic.signAndSend(sender, ({ events = [], status }) => { ... } );
console.log('Transfer sent with hash', hash.toHex())
```
Return error
```
hash.toHex is not a function
```

**Comment by jacogr** [comment]
In this example, there is no callback -

```js
const hash = await transfer.signAndSend(alice);
```

In this example, there is a callback -

```js
const ubsub = await batchExtrinsic.signAndSend(sender, ({ events = [], status }) => { ... } );
```

It is consistent in the API - on any callbacks, it returns an unsub function, without it returns the result of the function. 

For the behavior you want -

```js
const batchExtrinsic = api.tx.utility.batchAll(calls);
await batchExtrinsic.signAndSend(sender, ({ events = [], status }) => {
  // the signed transaction hashed
  console.log(batchExtrinsic.hash.toHex());
});

**Comment by NetGodFather** [comment]
It succeeded, thanks!

**Comment by jacogr** [comment]
The release made today (7.1.1) also exposes a txHash property in the callback. (Like you have result, status, events, …)
