### ISSUE TITLE
How do I `inspect the flags` from an RPC call using polkadot-js api?

### ISSUE THREAD

**Issue by forgetso** [polkadot-js/api#4389]
Hi, in the docs it states for `ContractReverted`:

>        * The contract ran to completion but decided to revert its storage changes.
>        * Please note that this error is only returned from extrinsics. When called directly
>        * or via RPC an `Ok` will be returned. In this case the caller needs to inspect the flags
>        * to determine whether a reversion has taken place.

Can these flags currently be viewed using `polkadot-js api` or is it waiting on [this](https://github.com/polkadot-js/apps/issues/6465)? When I call my contract function that should be reverted there are no `flags` in the `ISubmittableResult`.

**Comment by jacogr** [comment]
I have no idea about the contract results/flags as stated, have not delved into the newest contract interfaces for quite some time. It is quite possibly related to the above. (Quickly took a peek and it indeed seems very much api related as opposed to UI related where it was logged)

**Comment by jacogr** [comment]
I did a bit of digging, where the flags do come through is on the `abi.query.<mesage>(...)` calls, i.e. the result, if `isOk` has the flags.  so something like -

```js
const { result } = await abi.query.something(123);

if (result.isOk) {
  const { flags } = result.asOk;

  console.log(flags.toNumber());
}
```

They don't appear on `abi.tx.<message>` since the events returned, which is the only results from extrinsics, don't contain them.

**Comment by forgetso** [comment]
Thanks for the quick response. That's great I can get them from `query`.

I should have provided a bit more info. `ContractReverted` is an [error](https://github.com/paritytech/substrate/blob/0444ab7b4afbf4347d51e1e7352cda878e6a3df7/frame/contracts/src/lib.rs#L614) and does not appear in events. It states in the substrate docs that this error contains flags. Does the `ContractReverted` error propagate through to polkadot-js with flags?

**Comment by jacogr** [comment]
`dispatchError` always has the errors returned by the transaction. If you can see the details in e.g. the apps UI explorer, the same info is passed through.

**Comment by jacogr** [comment]
Please read the docs carefully, https://polkadot.js.org/docs/substrate/errors#contractreverted , it states -

"The contract ran to completion but decided to revert its storage changes." 

When it occurs ^^^

"Please note that this error is only returned from extrinsics." 

Error is returned from extrinsics.

"When called directly or via RPC an Ok will be returned."

RPC behaves different, e.g. alwaysw Ok, no error.

" In this case the caller needs to inspect the flags to determine whether a reversion has taken place."

The above applies to the last case, when called via RPC. (No flags in extrinsics)

**Comment by forgetso** [comment]
Thanks, I think I understand. polkadotjs calls substrate via RPC and is therefore only ever given an `Ok` and has no details of any errors.
