### ISSUE TITLE
Add a LightApi?

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#440]
Right now [I'm adding a LightApi](https://github.com/polkadot-js/light-ui/tree/master/packages/light-api) on top of the ApiRx object. But thinking about it, it could go below.

**Proposal: Add a LightApi layer below Api**

Ideally, LightApi is something that is totally invisible to the user, i.e. we keep the exact same final usage: `const api = new Api(new Provider(...))`.

However, add some "light logic", i.e. make the minimum viable number of jsonrpc calls to the node, assuming the node doesn't hold state. For example, if the user wants to subscribe on a account's balance, then make a subscription/polling on `newHead`, check the events on new head, and only make a subsequent jsonrpc call `getStorage` if the events show that the relevant part of the state has changed.

So, on load, Api will check:
- the provider
- the roles of the node, more specifically if it's a light node

and perform:

||Full node|Light Node|
|-|-|-|
|**WsProvider**|Use the current impl.|Use light logic|
|**HttpProvider**|Use light logic|Use light logic|

In this case, Providers stay "dumb", i.e. this invalidates #435 (dumb polling is enough for HttpProvider). The global idea is to not put the logic in #435 in rpc-provider, but in a layer on top of rpc-provider, but below api.
And it's totally transparent to all other layers, e.g. #427 doesn't care if the underlying Api is using full logic or light logic.

**Comment by jacogr** [comment]
Well, we don't actually need to poll for balances, the storage is a subscription already. So the polling really should not happen. Where there is value in additional stuff on-top of the API, is in making calls simple - for instance, the event check is a great example, i.e. give me all transfers for the following addresses. (Once again, no real polling required, the storage subs already do that node-side)

**Comment by jacogr** [comment]
... some additional info for above: I started playing with dumb-polling for HTTP, i.e. it will take the sub methods (mostly `state_storage` and `chain_newHead`) and poll around those. The screw-up here is that stuff like `author_submitAndWatch` cannot be supported at all - statusses are only available on subs.

**Comment by xlc** [comment]
While I agree using WS is much easier and more efficient, I am unsure about the robustness of it. Does it able to ensure the data integrity (no lost/corrupted messages) from poor network conditions (e.g. from mobile), reconnects, client crashing, node crashing etc? This can be crucial to implement a blockchain analytics service.
For  `author_submitAndWatchExtrinsic`, it seems like no rpc to get transaction status by hash, I think it can be simulated by polling for new finalized block, and check if the new block includes the transaction?

**Comment by jacogr** [comment]
The API support re-connects, re-creation of subscriptions (when re-connected) and queuing of transactions while not connected. Additionally, it allows allows subscribing to metadata changes, which is actually critical for any block analytics - block data cannot be correctly parsed without the correct metadata that matches the runtime, i.e. extrinsics, events are defined by the runtime, not hardcoded. (Alternatively, each new block, you need to poll for metadata)

So all these can be "simulated" via HTTP subscriptions, but it will always be slower, less robust in terms of logic and support and place a much larger load on the node.

**Comment by jacogr** [comment]
Closing here. (in conjunction with @amaurymartiny )
