### ISSUE TITLE
How to make keys optional when querying data on a chain?

### ISSUE THREAD

**Issue by Cupnfish** [polkadot-js/api#4411]
I have tried the chain data query of apps and found that some keys are optional, but I don't know how to implement a similar feature, I didn't find any related documentation, is there any related documentation? If not, how should I implement a similar feature?

<img width="1396" alt="图片" src="https://user-images.githubusercontent.com/40173605/148033886-af77a8d9-2714-4d89-bfae-7fea6d3f0d4d.png">

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/start/api.query.other/#map-keys--entries & https://polkadot.js.org/docs/api/cookbook/storage#how-do-i-use-entrieskeys-on-double-maps

**Comment by Cupnfish** [comment]
Thanks.
