### ISSUE TITLE
WrapperKeepOpaque not parse

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#4415]
https://github.com/polkadot-js/api/blob/8ba4ed53776a7a71478e229547c7af3d4dc57d63/packages/types/src/metadata/PortableRegistry/PortableRegistry.ts#L541

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/10815219

**Comment by jacogr** [comment]
Not sure what you are linking to here, the actual specific block you linked to is loading for me.

**Comment by freehere107** [comment]
![image](https://user-images.githubusercontent.com/7080674/148476703-89db3ee6-4810-4cce-b4a2-634cc0fca7ce.png)

WrapperKeepOpaque second params types is ``Call ``, not parsing here

**Comment by jacogr** [comment]
`WrapperKeepOpaque` is not guaranteed to be decodable, so it is kept in `Vec<u8>` form.  (Unlike `WrapperOpaque` which is always decodable)

Multi is a good example of where it may or may not actually be decodable - if the multisig process kicks off before a runtime upgrade, and the data is only supplied after a runtime upgrade (assuming indexes moved), it may not be decodable as a Call anymore (and subsequent execution would also fail).

So there is a case to be made for some new type with a "try to decode this into the base type" method aka `try_decode` as done on the runtime side for this type, but at this point it is left up to the API user.

**Comment by freehere107** [comment]
Thank you reply. I got it

**Comment by jacogr** [comment]
I'm re-opening to extend the wrapper with an `try_decode` step.
