### ISSUE TITLE
Error when decoding Range

### ISSUE THREAD

**Issue by stanly-johnson** [polkadot-js/api#4435]
Using [Range](https://doc.rust-lang.org/std/ops/struct.Range.html) seems to break the api, on connection attempt the error is 
```
FATAL: Unable to initialize the API: PortableRegistry: 83 (Range): Error extracting {"path":["Range"],"params":[{"name":"Idx","type":4}],"def":{"composite":{"fields":[{"name":"start","type":4,"typeName":"Idx","docs":[]},{"name":"end","type":4,"typeName":"Idx","docs":[]}]}},"docs":[]}: Cannot read property 'includes' of undefined
    at EventEmitter.value (/Users/stanly/Documents/enjin/efinity-dev/tools/redspot/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)

```

Using substrate v0.9.13

**Comment by stanly-johnson** [comment]
@jacogr Thanks for the quick fix. But the issue still persists. Anything I could be doing wrong?

**Comment by jacogr** [comment]
Which chain? Public endpoint would be useful.

**Comment by stanly-johnson** [comment]
Ah sorry I cannot share since the code is in private repo and CI won't let me merge since the api fails now :( 
But the idea is using the new type pattern over std::ops::Range like `pub struct Range<I: TypeInfo>(pub StdRange<I>);` , this is the source of the error.

**Comment by jacogr** [comment]
At this point nothing more that can be done then, need a reproduction to be able to look further if there are gaps. 

The fixes that went in is the same as applied in an open PR where the Opaque wrapper is reworked (it showed exactly the same issue, so in the fix it was just backported)

**Comment by jacogr** [comment]
Ok, I believe that the snippet above aka `{"path":["Range"],"params":[{"name":"Idx","type":4}],"def":{"composite":{"fields":[{"name":"start","type":4,"typeName":"Idx","docs":[]},{"name":"end","type":4,"typeName":"Idx","docs":[]}]}},"docs":[]}` may be enough to rever-sengineer with a testcase.

In general, unless it "can bee seen", it is difficult to guess in a vacuum.

Will create a test-case around the above.
