### ISSUE TITLE
`Invalid Transaction: Transaction has a bad signature` when the payload is too big

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#4436]
In https://github.com/PureStake/cli-ts-signer/pull/16/files , I am trying to implement an offlne signer. 
It works correctly, except when the input parameters is too long (list for a btach tx): https://github.com/PureStake/cli-ts-signer/pull/16/files#r781227667
I added a test to make sure the signing function worked with long messages: https://github.com/PureStake/cli-ts-signer/pull/16/files#r781228217
Since it does, I would guess it is something in the `send` step of the api, that fails to verify the signed payload when it is too long.
It looks like the limit above which the error is triggered is when the extrinsic payload in https://github.com/PureStake/cli-ts-signer/blob/5b284df1815115497abc899743157a75647c5939/src/methods/createAndSendTx.ts#L45 is bigger than 512
Any idea what could fix the problem? Thanks in advance

**Comment by jacogr** [comment]
When the payload > 256 bytes, the hash itself is signed, not the payload itself.

See https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/util.ts#L10

**Comment by joelamouche** [comment]
Thanks :)
