### ISSUE TITLE
Cannot set a large enough storage_deposit_limit

### ISSUE THREAD

**Issue by forgetso** [polkadot-js/api#4438]
I was having issues when running contract functions, hitting a `contracts.StorageDepositNotEnoughFunds` error from substrate.

It turns out, when `storage_deposit_limit` is set to `null` in [polkadotjs](https://github.com/polkadot-js/api/blob/8ba4ed53776a7a71478e229547c7af3d4dc57d63/packages/api-contract/src/base/Contract.ts#L109), the value `123576914103721` is somehow set as the limit. This is too small for many contract functions.

When I manually set the limit in the API call (`const storageDepositLimit = 9e15`), I am not able to set the value to a high enough number, receiving the error:

```
Error: createType(Call):: Call: failed decoding contracts.call:: Struct: failed on args: {"dest":"MultiAddress","value":"Compact<u128>","gas_limit":"Compact<u64>","storage_deposit_limit":"Option<Compact<u128>>","data":"Bytes"}:: Struct: failed on storage_deposit_limit: Option<Compact<u128>>:: Assertion failed
```

Further details can be found [here](https://github.com/paritytech/substrate-contracts-node/issues/23).

**Comment by jacogr** [comment]
Don't use the `9e15` form, it is not parsed by `bn.js`. Rather use `9000000000000000` (as a string, hex or `BigInt`)

I'm not sure where the `123576914103721` comes from.

**Comment by forgetso** [comment]
Joy to the world! Thank you so much for the tip. Everything is working again.

**Comment by jacogr** [comment]
Actually added a PR https://github.com/polkadot-js/api/pull/4439 this morning (which should have gone in a long time ago) that checks for both `number` and `string` formats - instead of the BN.js (mostly useless) "assertion failed" error, it will say what is wrong on the inputs.

**Comment by forgetso** [comment]
That will prove very useful for people. You're right about the BN error being useless!
