### ISSUE TITLE
Fetch inflation based rewards for Validators.

### ISSUE THREAD

**Issue by karthiknvlr** [polkadot-js/api#4443]
Objective:
I need to fetch the inflation-based rewards for validators from the blockchain for a specific ERA. 

I have found, I can use `api.derive.staking.stakerRewardsMultiEras` to fetch the information from the blockchain. 

May I know how to properly pass the stashId and EraIndex as the input parameters to the above API?

**Comment by jacogr** [comment]
`api.derive.staking.stakerRewardsMultiEras([stashId1, stashId2, ...], [era1, era2, ...])`
