### ISSUE TITLE
Tx.addSignature emiting error

### ISSUE THREAD

**Issue by ahsanahmed321** [polkadot-js/api#4446]
What I am trying to do is create a transaction using this 

const tx = await api.tx.balances
        .transfer(
          accountToSate.value, amountState.value * 10 ** decimals,
        );

 const txU8a = tx.toU8a();

Then I am transfering this u8a to beckground (where my keyring exist ) signing it like this

const signature = pair.sign(txU8a)
const sigHex = u8aToHex(signature);

sending this signature hex back to the application and then adding signature below
 tx.addSignature(address, signatureHex, tx);

I am getting this error

Unable to create Enum via index 194, in Ed25519, Sr25519, Ecdsa

**Comment by jacogr** [comment]
You are missing the signOptions, see https://github.com/polkadot-js/common/blob/master/packages/keyring/src/types.ts#L36

Specifically `withType: true`

**Comment by ahsanahmed321** [comment]
Thanks now it showing me this error when trying to send that transaction 

RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature

**Comment by jacogr** [comment]
The extrinsic payload is signed, not the transaction. You are serializing the transaction and signing that. The payload has all transaction information and more, e.g. spec_version, genesishash, blockhash for mortality, etc.

**Comment by ahsanahmed321** [comment]
@jacogr Can you please explain me what I am doing wrong

**Comment by ahsanahmed321** [comment]
Current State :

const tx = await api.tx.balances
.transfer(
accountToSate.value, amountState.value * 10 ** decimals,
);

const txU8a = tx.toU8a();

Then I am transfering this u8a to beckground (where my keyring exist ) signing it like this

const signature = pair.sign(txU8a, {withType:true} )
const sigHex = u8aToHex(signature);

sending this signature hex back to the application and then adding signature below
tx.addSignature(address, signatureHex, tx);

tx.Send( )

**Comment by ahsanahmed321** [comment]
Sorry for the late reply @jacogr I am trying to create a extrinsic payload here using tx 

        const tx = await api.tx.balances
        .transfer(
          accountToSate.value, amountState.value * 10 ** decimals,
        );


      const txPayload = api.createType('ExtrinsicPayload', {
        method: tx.toHex(),
        era: tx.era,
        nonce: tx.nonce,
        tip: tx.tip,
        specVersion: api.runtimeVersion.specVersion,
        genesisHash: api.genesisHash,
        blockHash: ' '
      }, { version: tx.version });

Can you please tell me where I can get blockHash from

**Comment by jacogr** [comment]
In your example above, 

- era would be unset
- nonce would be unset

They are part of the options to signAndSend, i.e. the information is retrieved and filled at that point along with the blockHash. (The blockHash is for the era the mortality applies to)

`signAndSend` only constructs the info here based on the results from a derive call. https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L221

**Comment by ahsanahmed321** [comment]
ok @jacogr I have made changes according to your suggestions and this is the current flow

    const tx = await api.tx.balances
    .transfer(
      accountToSate.value, amountState.value * 10 ** decimals,
    );

  const transactionData = {
        method: tx.toHex(),
        specVersion: api.runtimeVersion.specVersion,
        genesisHash: api.genesisHash,
        tip: tx.tip,
      };

      const txPayload = api.createType('ExtrinsicPayload', transactionData, { version: tx.version });

       const txU8a = txPayload.toU8a();

       Then I am transfering this u8a to background (where my keyring exist ) signing it like this

      const signature = pair.sign(txU8a, {withType:true} )
      const sigHex = u8aToHex(signature);

     sending this signature hex back to the application and then adding signature below
    tx.addSignature(address, sigHex, txPayload);

      tx.Send( )

and it is still showing me that bad signature error

**Comment by jacogr** [comment]
Your transaction data does not contain -

- blockHash
- era
- nonce

They are all part of the signed payload. Additionally the `txPayload` needs the `true` flag passed in toU8a to serialize with the call without the length prefix. See the logic you are trying to replicate - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/ExtrinsicPayload.ts#L157-L160

I cannot help more than this - you should have all the info and links now to where the API handles it. (It is all based on metadata, so the API doesn't fix any of these when it constructs)
