### ISSUE TITLE
Question: Available Balances

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#4448]
Should `free` balance from `api.query.system.account` api show correct transferable balance or there's more to it? If I do `free - feeFrozen` I sometimes get incorrect amount and sometimes even negative amount when I voted in democracy. 

The only way I found to get the correct available balance is to use `api.derive.balances.all` api (there's `availableBalance` field there)

This just tells me that either `api.query.system.account` is wrong as it's impossible to calculate correct available balance using it, or there's more values from other APIs that need to be subtracted or added to values from `api.query.system.account`

**Comment by jacogr** [comment]
The "available" (which is basically the amount that can be "transferred") is the free - locks (basically the max locked amount since locks overlap)

https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/balances/all.ts#L65
