### ISSUE TITLE
Compile failed after bump to 7.3.1

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/api#4451]
```
./node_modules/@polkadot/api/packageInfo.js 6:27
Module parse failed: Unexpected token (6:27)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export const packageInfo = {
|   name: '@polkadot/api',
>   path: new URL('.', import.meta.url).pathname,
|   type: 'esm',
|   version: '7.3.1'
```

Some loader is missing, but the error message does not indicate which one is missing.

**Comment by jacogr** [comment]
It is WP4 related, see https://polkadot.js.org/docs/usage/FAQ#on-webpack-4-i-have-a-parse-error-on-importmetaurl

**Comment by sxlwar** [comment]
Resolved, thanks

**Comment by smuxx** [comment]
There is also a similar issue in react-native apps using 7.3.1... metro complains and throws a syntax error about import.meta... is there a solution for metro and react-native?
