### ISSUE TITLE
Outdated api.at() return interface `ApiDecoration<ApiType>`

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#4473]
We found currently the  `api.at()` object interface still provide method like `.at()`, `.multi()`, which should not be supported. 
Ref : https://github.com/polkadot-js/api/issues/3763

For example : 
```
const apiAt = await api.at(blockHeight) 

apiAt.query.staking.payee.multi  //should not exist

```

We found It was due to the return interface is using the `ApiDecoration<ApiType>` object. 

https://github.com/polkadot-js/api/blob/88d72071029c134b4523d1f0c9a5908182ad4085/packages/api/src/base/Init.ts#L111

Do you think we can provide interface like `ApiDecorationAt`, just similar approach like the `QueryableStorage` and `QueryableStorageAt` .  https://github.com/polkadot-js/api/blob/88d72071029c134b4523d1f0c9a5908182ad4085/packages/api-base/src/types/storage.ts#L21

Thank you

**Comment by jacogr** [comment]
A new interface can probably be returned, internally using `QueryableStorageAt` as suggested. May be as simple as adding and returning. (Would just keep the things not changing as a base interface with both variants extending from it and then just adding the query/rx bits)

However methods here fall into 2 categories -

- those that would add value, e.g. `.multi` can be supported and probably should be added
- those that don't make sense, e.g. `.at` would lead down a rabbit hole (not API-wise, usage-wise)
