### ISSUE TITLE
I can't find unwrapOrDefault() function

### ISSUE THREAD

**Issue by TopCodeBeast** [polkadot-js/api#4474]
I used 6.12.1 and 4 days ago I updated 7.4.1
I used this code to fetch account detail info but it makes erro now.

    const optionIdentity = await api?.query.identity?.identityOf(address);
    const identity = optionIdentity?.unwrapOrDefault();

**Comment by jacogr** [comment]
See the 7.0.1 major release CHANGELOG - https://github.com/polkadot-js/api/releases/tag/v7.0.1 

FAQ entry here =- https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing
