### ISSUE TITLE
Codec doesnt have number[]

### ISSUE THREAD

**Issue by TopCodeBeast** [polkadot-js/api#4475]
Currently, I updated 7.4.1 before I used 6.12.1
And now this error hapeend 'No overload matches this call.'
because random is not number[] type    

const random = await api.query.babe.randomness()
    this.seed = Array.from(random);

**Comment by jacogr** [comment]
See the 7.0.1 major release CHANGELOG - https://github.com/polkadot-js/api/releases/tag/v7.0.1 

FAQ entry here =- https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing

**Comment by TopCodeBeast** [comment]
thanks
