### ISSUE TITLE
import { naclVerify, schnorrkelVerify } from '@polkadot/util-crypto' error

### ISSUE THREAD

**Issue by TopCodeBeast** [polkadot-js/api#4476]
import { naclVerify, schnorrkelVerify } from '@polkadot/util-crypto'
I updated  '@polkadot/util-crypto' from 7.4.1 to 8.3.2 and I can't find naclVerify, schnorrkelVerify

**Comment by jacogr** [comment]
Wrong repo.

**Comment by TopCodeBeast** [comment]
Where is Changelog?

**Comment by jacogr** [comment]
In the common repo where the code for util is, aka https://github.com/polkadot-js/common/releases/tag/v8.0.1
