### ISSUE TITLE
Breaking changes for TS

### ISSUE THREAD

**Issue by ftheirs** [polkadot-js/api#4480]
Hi! I'm running my code using 6.10.3 but I'm always trying to keep updated with my dependencies. I've read about the breaking changes for TS in version 7 but I couldn't figure out how to fix my code.

I've tried with a [basic example](https://polkadot.js.org/docs/api/examples/promise/make-transfer) and I've found that I'm getting different outputs right here.
```
const BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';
const transfer = api.tx.balances.transfer(BOB, 12345);
console.log(transfer)
```
Using version 6.10.3
```
Submittable {
  registry: TypeRegistry { createdAtHash: undefined },
  createdAtHash: undefined,
  initialU8aLength: undefined,
  _raw: Type(2) [Map] {
    'signature' => Type(5) [Map] {
      'signer' => [Type],
      'signature' => [Type],
      'era' => [Type],
      'nonce' => [Type],
      'tip' => [Type],
      registry: [TypeRegistry],
      createdAtHash: undefined,
      initialU8aLength: 101
    },
    'method' => Type(2) [Map] {
      'callIndex' => [GenericCallIndex [Uint8Array]],
      'args' => [Struct [Map]],
      registry: [TypeRegistry],
      createdAtHash: undefined,
      initialU8aLength: 0,
      _meta: [Type [Map]]
    },
    registry: TypeRegistry { createdAtHash: undefined },
    createdAtHash: undefined,
    initialU8aLength: 0
  }
}
```
Using version 7.4.1
`Submittable { createdAtHash: undefined, initialU8aLength: undefined }`

I'm not sure why, there is no **_raw** field with version 7 and that thing is breaking my code.
I've added the import that is mentioned [here](https://polkadot.js.org/docs/api/FAQ/#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing) but nothing happens, I get the same output.

What should I change in this code to get something similar to the 6.x version?

**Comment by jacogr** [comment]
`_raw` is internal, i.e. the `_` indicates it is not for external use. In the 7.x series the `_raw` field in `Base` is private field.

You can always `.unwrap()` to access the internals, aka get the same value - https://github.com/polkadot-js/api/blob/master/packages/types-codec/src/base/Base.ts#L105

**Comment by ftheirs** [comment]
Using inner or unwrap() solved my problem! Thanks :D
