### ISSUE TITLE
multisig opaque call decode

### ISSUE THREAD

**Issue by VegeBun-csj** [polkadot-js/api#4482]
hey, i want to decode the opaque call hash of the multisig to get the concrete call data, eg who call transfer function, dest is who. Can you tell me the method

**Comment by jacogr** [comment]
The hash of a call is a one-way operation, aka you cannot get a call from a hash. (All cryptographic hashes are non-reversible)

**Comment by VegeBun-csj** [comment]
thanks, that is to say, if i want to know the concrete call info(eg: who call , what function , dest is who), i can only get it when i use polkadot.js api dispatch the multisig tx which trigger the event. Only get it By the event ?

**Comment by VegeBun-csj** [comment]
> The hash of a call is a one-way operation, aka you cannot get a call from a hash. (All cryptographic hashes are non-reversible)

thanks, that is to say, if i want to know the concrete call info(eg: who call , what function , dest is who), i can only get it when i use polkadot.js api dispatch the multisig tx which trigger the event. Only get it By the event ?

**Comment by jacogr** [comment]
It depends which call. So with the initial only supplying the hash, you cannot extract. On the final with the WrapperKeepOpaque, the call is there.

**Comment by VegeBun-csj** [comment]
> It depends which call. So with the initial only supplying the hash, you cannot extract. On the final with the WrapperKeepOpaque, the call is there.

thanks, I understand. But how can i decode the WrapperKeepOpaque call type by using polkadot-js api? Can you help me? thank you very much. i study the polkadot-js app , but i did't find the method.

**Comment by VegeBun-csj** [comment]
i want to get the calls(Storage) by the call hash using polkadot-js api query.the result is a tuple include <WrapperKeepOpaque,accounts, balace>.

**Comment by VegeBun-csj** [comment]
how can i decode it

**Comment by jacogr** [comment]
`wrapper.unwrap()` - if the call is decodable, it may throw, i.e. when a runtime upgrade happened and the indexes moved, the call may be invalid and therefore the call will fail.

To check before trying to unwrap `wrapper.isDecoded` will tell you if all is ok and it will succeed.

**Comment by VegeBun-csj** [comment]
ok, i use `txwrapper-core`  to handle the question.Thanks.
