### ISSUE TITLE
Subscribe to runtime version, update metadata on change

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#449]
Process -

- API subscribes to runtimeVersion
- When the runtime version changes, retrieve metadata via `state_getMetadata`
- Inject

Basically we want the initialization that happens in https://github.com/polkadot-js/api/blob/master/packages/api/src/Base.ts#L456-L462 to happen on version updates

This is the one area where oo7 does it really well, i.e. `tie` to version, update on changes - https://github.com/paritytech/oo7/blob/master/packages/oo7-substrate/src/bonds.js#L207-L211

**Comment by ltfschoen** [comment]
i tried the following but it gives error that `subscribeRuntimeVersion` is not a function. I also tried adding to polkadot-js/api/packages/api-observable/src/Calls.ts
```
  subscribeRuntimeVersion = (): Observable<Header | undefined> => {
    return this._api.chain.subscribeRuntimeVersion().pipe(
      defaultIfEmpty()
    );
  }
```

```
// Required imports
const { ApiPromise } = require('@polkadot/api');

async function main () {
  const api = await ApiPromise.create();
  
  // Make a subscription to the network head
  api.rpc.chain.subscribeRuntimeVersion((version) => {
    console.log(`Runtime version is: #${version}`);
  });
}

main().catch(console.error).finally(() => process.exit());
```

**Comment by jacogr** [comment]
It is available here - https://github.com/polkadot-js/api/blob/master/packages/type-jsonrpc/src/chain.ts#L72 (Added at the end of last week - and it is being moved to `state` in Substrate)

**Comment by jacogr** [comment]
Needs #459
