### ISSUE TITLE
When and how are the node types augmented

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/api#4493]
I found the amazing bug in  https://github.com/kodadot/nft-gallery/issues/2058 

When the user for the first time connects to statemine/westmint node the `uniques` module is undefined 
e.g
```js
console.log(api.query.uniques) // undefined
```

`api.isReady` also has no `uniques` module

When and how are the node types augmented and if it's possible to listen to this change?

Other:
We use `"@polkadot/api": "^7.4.1"` and type augmentation is `import '@polkadot/api-augment'`

**Comment by jacogr** [comment]
I would suggest looking at the 7.x release notes. (Major semver bump)

**Comment by jacogr** [comment]
See https://github.com/jacogr/api-test-4493 (logging both `api.query.uniques` & `api.tx.uniques`

**Comment by vikiival** [comment]
I found the bug, it's related to how we handle endpoint connection

> Api is enhanced with the modules for the runtime on load, metadata retrieval.

but still it would be cool to hove
something
`api.on('enhance', updatedApi => {})`
