### ISSUE TITLE
`Unable to decode storage auctions.winning` on runtimes pre v9111 on kusama

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#4494]
## The Issue:

Currently when querying `apiAt.query.auctions.winnings(<offset>)` on any runtime below 9111 during an ending period phase (`AuctionStatus::EndingPeriod`) it will fail to decode. Everything on my end works for all phases with runtime 9111 and above.

Error log:

```
Error: Unable to decode storage auctions.winning:: createType(WinningData):: [Option<(AccountId,ParaId,BalanceOf)>;10]:: Decoded input doesn't match input, received 0x016d6f646c70792f6366756e641e080000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (140 bytes), created 0x016d6f646c70792f6366756e641e080000000000000000000000000000000000…00000000000000000000d10700000bc6435970ddd70100000000000000000000 (114 bytes)
``` 

## Reproduction

Note: I am replicating the offset calculation logic directly from the polkadot repo that is performed in [`handle_bid`](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/auctions.rs#L431). I leave it out below to not cloud the example (Happy to include it if you think it would help). All necessary info to calculate it too came from `AuctionInfo`. Also important to note for the examples below, they are both within the same auction, and a runtime upgrade happened within the ending period phase. One example is before at the beginning of the auction, and one example is after at the end of the auction.

RuntimeVersion v9111 (This works no problem)
```typescript
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://kusama-rpc.polkadot.io'),
    });

    await api.isReady

    /**
     * This is blockHeight -> 9634568
     * 
     * The last block in this `endPeriod` for this specific auction is 9634569
     */
    const blockHash = '0x7322f4c8a55250b76b09d341aba563bd2e18d04b6a940c5c2da4092696374b37';
    const apiAt = await api.at(blockHash);

    const endingOffset = 3599;
    const winning = await apiAt.query.auctions.winning(endingOffset);

    console.log(winning)
};
```

RuntimeVersion v9090 (This fails to decode)
```typescript
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://kusama-rpc.polkadot.io'),
    });

    await api.isReady

    /**
     * This is blockHeight -> 9562570
     * 
     * This is the the second block in this auctions `endPeriod`. The early end being 9562569.
     */
    const blockHash = '0x82d83826d8fdb6204bf617cc325ea46f0a188bafe448f781f5e92248ee276c4e';
    const apiAt = await api.at(blockHash);

    const endingOffset = 0;
    const winning = await apiAt.query.auctions.winning(endingOffset);

    console.log(winning)
};
```

## Packages

reproducible for polkadot-js/api: ">=7.2.1" (I didnt test below this version)

## Thoughts:

Wondering if this is an issue regarding the big change in metadata that occurred, and any direction on this is super helpful. This could very well be an issue on my end. But being that all the logic for all offset and cases works v9111 and above makes me think this might be some type of historical type bug (Not totally sure though).

**Comment by jacogr** [comment]
Quite possibly a historical type that is incorrect  for that version of the runtime.

**Comment by TarikGul** [comment]
Hey @jacogr, Thanks again for the explanation and patch. 

> Could possibly be SLOT_RANGE_COUNT that along the way went from 10 to 36. (140 bytes - 114 bytes = 26, it would explain the discrepancy, all the end bytes are 0, so the struct/Option takes up a single byte)

Clever way to debug that! I took a look at the PR above too and now remember that change to 8 lease period per slot, so the above all definitely lines up for me and makes sense now. 

> the next step is to track the Polkadot code at that point in time and compare the types in the runtime, adding (eg. possible WinningData9090) and adjusting types-known -

Ahhh okay, thats super helpful. In terms of historic type support that makes sense in order to test it locally, and for debugging thanks for that.
