### ISSUE TITLE
Where to find the Extrinsic Call index in different substrate chain

### ISSUE THREAD

**Issue by FitzLu** [polkadot-js/api#4496]
https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/Extrinsic.ts#L111
```
  /**
   * @description The actual `[sectionIndex, methodIndex]` as used in the Call
   */
  public get callIndex (): Uint8Array {
    return this.method.callIndex;
  }
```
Where can I find the sectionIndex and methodIndex.

I found that `balances.transfer` call index is 0400 on kusama like metioned here https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/Extrinsic.spec.ts#L34,  and what are the values on polkadot and other parachain.

**Comment by jacogr** [comment]
It is defined in the runtime metadata, i.e. it is not fixed. When the API connects and loads the metadata, the indexes are defined in there and it is used in building the extrinsics. The values in the testcases were extracted by looking at the metadata and counting the module & method offsets.

**Comment by sourabhniyogi** [comment]
For all substrate chains, how do we (easily) get the api/registry for older spec version/runtimes than the latest?

For analytics on old blocks, we would like to avoid doing any manual github archeology for (blocks/block hashes) and have an api call to get the right registry (with the right metadata) to interpret any call index.  Is there a way to do so?

**Comment by jacogr** [comment]
```js
const apiAt = await api.at('<blockHash>):

// registry decorated at this point
console.log(apiAt.registry);

// api will also decode any blocks or storage, etc. at that index with the registry retrieved via at, e.g.
// this uses apiAt internally to retrieve an instance and uses it for decoding
const block = await api.rpc.chain.getBlock(<blockHash>)

// registry decorated for the blockHash (exposed on the value)
console.log(block.registry);
```
