### ISSUE TITLE
Recreate Transaction from SignerPayloadJSON and signature

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/api#4498]
I am trying to build a tool that allows a user to do the steps createTx-signTx-SendTx in three separate (in time and location) steps.
I am having trouble with the 3rd step where I have SignerPayloadJSON, registry info and signature saved in a file and I want to recreate the signed tx to be able to send it.

Using signAndSend with injected signer wouldn't work because it would recreate a SignerPayloadJSON with new era and the signature wouldn't be valid anymore.

This is the PR: https://github.com/PureStake/cli-ts-signer/pull/12

**Comment by jacogr** [comment]
If you have the full tx constructed already elsewhere, use `api.tx(<hex goes here>).signAndSend(...)`
