### ISSUE TITLE
Next JS Build fails with api version v7.5.1

### ISSUE THREAD

**Issue by saadjhk** [polkadot-js/api#4500]
`
error - ./node_modules/@polkadot/api/rx/Api.js
Module parse failed: Unexpected character '#' (108:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export class ApiRx extends ApiBase {
>   #isReadyRx;
|   /**
|    * @description Create an instance of the ApiRx class
`

Next JS version: 11.0.1
Using Webpack 4

**Comment by jacogr** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by saadjhk** [comment]
I am aware about private fields, but when it comes to using the package with webpack 4, it doesn't work. I tried using web pack 5 and now i get a different error which is

`
error - ./node_modules/@polkadot/api/base/Decorate.js
Can't import the named export 'TypeRegistry' (imported as 'TypeRegistry') from default-exporting module (only default export is available)
`

**Comment by jacogr** [comment]
All I can do is to point you to a bare-bones WP5 sample project. See https://github.com/jacogr/api-test-4500

Apart from that, cannot debug local tooling issues.

**Comment by TopCodeBeast** [comment]
Hey, I have same error.
Did you solve it?

**Comment by saadjhk** [comment]
Well I wasn't able to solve it, I switched back to v6 for now.

**Comment by jacogr** [comment]
I am really not Webpack support - I barely can find my way around it. Additionally WP4 is really ancient, so I would suggest anybody using it to upgrade.

Having said that, here is a minimal config for WP4, YMMV - https://github.com/jacogr/api-test-4500-wp4 

If you have any additional issues, I would suggest Google and SO, this is not for bundler support.

**Comment by TopCodeBeast** [comment]
@saadjhk what do you mean "switched back to v6 " ?

**Comment by saadjhk** [comment]
@TopCodeBeast v6.5.1 of @polkadot/api

**Comment by saadjhk** [comment]
can confirm latest api works with next JS latest version, i was using old next that might have been using outdated tooling
[https://github.com/saadjhk/picasso-next.git](url)

**Comment by TopCodeBeast** [comment]
@saadjhk I think the problem is '@open-wc/webpack-import-meta-loader' cant parse @polkadot/keyring 8.3.3
It can parse keyring. 8.3.2. currently updated 8.3.3
