### ISSUE TITLE
How to subscribe to a map

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#4504]
I recall this is more a question for SackExchange, but it's not live quite yet.

I've a hard time subscribing to a map on a custom pallet we're building. Getting the entries works as expected with:
```js
api.query.filecoindot.verifiedBlocks.entries()
  .then((res: [StorageKey<AnyTuple>, Codec][]) => {
    console.log("my entries #", res.length)
  })
```

But framing it like a subscription in the entries doesn't yield the expected result

```js
api.query.filecoindot.verifiedBlocks.entries((res: [StorageKey<AnyTuple>, Codec][]) => {
  console.log("got some new", res.length)
  // this only runs once
})
```

I did try to subscribe to my `verifyBlocks` either (although I'm not sure how to decode what comes out of it since "entries is not a function" of the result), it only ran once either.

What am I missing?

**Comment by jacogr** [comment]
`.entries()` is not auto-updating on changes. There is no map-subscription RPC.

**Comment by Tbaut** [comment]
Got it, thanks.
