### ISSUE TITLE
_this7 is not defined

### ISSUE THREAD

**Issue by PhilipMantrov** [polkadot-js/api#4513]
![image](https://user-images.githubusercontent.com/8265714/151661095-b23c3068-ef1b-45f1-b501-f8b897b363d3.png)

After a small investigation i realize that this error has occur on version upper than 7.0.1, on version 7.0.1 all works like a charm. 

Repo with repo: https://github.com/PhilipMantrov/angular-polkadot-test

**Comment by jacogr** [comment]
The minimal sample is great, thank you.
