### ISSUE TITLE
Support question: getting extrinsic index within block

### ISSUE THREAD

**Issue by monitz87** [polkadot-js/api#4522]
Since tx hashes aren't enough to uniquely identify a transaction, but rather block hash + extrinsic index, I was wondering what is the easiest way of retrieving the index of an extrinsic from the result of a `signAndSend` call. From what I've been able to find, the `ISubmittableResult` interface has nothing relating to the index

Is this exposed somewhere? And if not, could it be?

**Comment by jacogr** [comment]
Don't believe it is exposed. since we extract the events anyway (which needs the index), it does mean we have it available in the process for the callback somewhere. So needs wiring in.

**Comment by monitz87** [comment]
In that same vein, I think exposing the nonce in the submittable result could be beneficial as well in case the user is not passing it explicitly (or using -1)
