### ISSUE TITLE
Using @polkadot/api on angular webapp

### ISSUE THREAD

**Issue by arunsybex** [polkadot-js/api#4525]
"@polkadot/api": "^7.6.1"

`
Error: node_modules/@polkadot/api-derive/staking/types.d.ts:3:98 - error TS2305: Module '"@polkadot/types/lookup"' has no exported member 'PalletStakingValidatorPrefs'.

3 import type { PalletStakingExposure, PalletStakingRewardDestination, PalletStakingStakingLedger, PalletStakingValidatorPrefs } from '@polkadot/types/lookup';
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@polkadot/api-derive/types.d.ts:5:15 - error TS2305: Module '"@polkadot/types/lookup"' has no exported member 'PalletBountiesBounty'.

5 import type { PalletBountiesBounty, PalletTreasuryProposal } from '@polkadot/types/lookup';
                ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@polkadot/api-derive/types.d.ts:5:37 - error TS2305: Module '"@polkadot/types/lookup"' has no exported member 'PalletTreasuryProposal'.

5 import type { PalletBountiesBounty, PalletTreasuryProposal } from '@polkadot/types/lookup';
`


Please suggest supporting lib for angular cli


Angular - ng-version="13.2.1"

**Comment by jacogr** [comment]
See the 7.0.1 release notes, pointing to this FAQ entry - https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing

**Comment by arunsybex** [comment]
@jacogr  Thanks it works!

![image](https://user-images.githubusercontent.com/20275068/152315440-8cbbe36e-3178-4867-927c-cd09f9fbbc38.png)
