### ISSUE TITLE
PORTABLEREGISTRY: Unable to determine runtime Call type /  Event type

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#4526]
Hi I have upgrade our project to 7.6.1 and encountered this issue when fetch early blocks. 

```
2022-02-03 23:05:18 PORTABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic
2022-02-03 23:05:18 PORTABLEREGISTRY: Unable to determine runtime Event type, cannot inspect frame_system::EventRecord
```

It happened when use api.at() object to query events, it can be reproduce in by code:

```
async function main(){
    const api = await ApiPromise.create({provider});
    const blockHash = await api.rpc.chain.getBlockHash(2);
    const apiAt = await api.at(blockHash);
    const events = await apiAt.query.system.events()
    console.log(events)
}
main().catch(e=>process.exit(1));
```

Please help. Thank you

**Comment by jacogr** [comment]
Which chain are you connecting to?

If it is a metadata v14 chain, it could be problematic. If it is a metadata v13/v12 chain, it is harmless. (There is a slight issue that it will get logged there while technically it shouldn't, but since all chains should migrate to v14 anyway)

**Comment by jacogr** [comment]
Ahhh... on early blocks. Yes, it is harmless. (Although as mentioned above should probably not appear, i.e. should only appear on v14+)

**Comment by jiqiang90** [comment]
@jacogr Oh thanks. Forget mention, it is connected to polkadot.
