### ISSUE TITLE
[Question] Integration Tests with a Local Node

### ISSUE THREAD

**Issue by danforbes** [polkadot-js/api#4533]
Is it possible to exhaustively test the Polkadot-JS API against a running instance of a node? I found [this test file](https://github.com/polkadot-js/api/blob/master/packages/api/src/test/api.spec.ts), but it seems to perform only a few checks, as opposed to exercising all the API capabilities - is such a thing possible? I am currently working with the [Gossamer](https://github.com/ChainSafe/gossamer) team to develop a test plan, and we would like a way to test our interoperability with the Polkadot-JS API.

**Comment by jacogr** [comment]
There used to be e2e tests about 18 months ago, I ripped them all out since I could not keep them updated targeting new runtimes. (Unmaintained tests are worse than none)

**Comment by danforbes** [comment]
Thank you, Jaco! I'm going to check with the Sidecar guys to see what their E2E tests are like. Please let me know if you know of other places we could check for E2E suites that may help us test our RPC implementations 🙏🏻
