### ISSUE TITLE
Sort `MultiAssets` on extrinsic submission

### ISSUE THREAD

**Issue by KiChjang** [polkadot-js/api#4537]
As it was found out in https://github.com/paritytech/cumulus/issues/892, extrinsics will fail if the `MultiAssets` parameter is not properly sorted. We should then ensure that the frontend UI sorts the `Vec` on submission.

**Comment by KiChjang** [comment]
I just remembered that there's also one important detail for the `teleport_asset` or `reserve_transfer_asset` extrinsics -- the 4th parameter is `fee_asset_item`, which is an index of the `assets` vec that indicates which asset in the vec is used to pay for the weights.

If we haphazardly reorder the `assets` vec, we'd invalidate this index, and so I think the better solution here may just be to create new UI elements specifically for these two extrinsics. I'm not sure if this is a cleaner way though, I could be wrong.

**Comment by jacogr** [comment]
Good point that I didn't think of. 

PS: Bonus point for using "haphazardly" in this context, it made my morning

**Comment by jacogr** [comment]
Closing, cannot really be done on the API - it is types agnostic. (Not sure if the UI wants this either, since it "just displays and doesn't interpret", but that is up to that layer)
