### ISSUE TITLE
Extrinsic contracts.call expects 5 arguments, got 4.

### ISSUE THREAD

**Issue by luozygithub** [polkadot-js/api#4542]
![1644287667(1)](https://user-images.githubusercontent.com/31771728/152907062-de8dd342-b27e-4375-ab53-fa114dd49cc9.jpg)

**Comment by jacogr** [comment]
You have no info attached to this -

- no version of the API
- no what you are trying to do
- no where you are trying to do it from
- no which node you are connecting to

Without proper comprehensive info, this is not quite useful nor actionable.

**Comment by luozygithub** [comment]
"language": "ink! 3.0.0-rc5",
    "compiler": "rustc 1.59.0-nightly",
    
    i want use  ContractPromise to call my int method
![image](https://user-images.githubusercontent.com/31771728/152953250-d8299570-7a8b-49e5-accc-ca3da6591ce8.png)

**Comment by jacogr** [comment]
Which version of the API?

**Comment by luozygithub** [comment]
"@polkadot/api": "^6.2.1"

**Comment by luozygithub** [comment]
"@polkadot/extension-dapp": "^0.42.2",

**Comment by jacogr** [comment]
You need to upgrade to the 7.x series, support for the new RPCs were added in https://github.com/polkadot-js/api/releases/tag/v7.1.1 (in December 2021)

**Comment by luozygithub** [comment]
ok thanks

**Comment by luozygithub** [comment]
What's the alternative to WebPack for polkaJS/API front-end development?
