### ISSUE TITLE
How to enbale api.derive.staking when staking module function erasRewardPoints is not available

### ISSUE THREAD

**Issue by yashirooooo** [polkadot-js/api#4555]

**Comment by yashirooooo** [comment]
I found that there is a check for staking module's function erasRewardPoints in the api check. Is there a parameter to disable this check?

**Comment by yashirooooo** [comment]
@jacogr

**Comment by jacogr** [comment]
No. It is needed inside the derives.

**Comment by yashirooooo** [comment]
> No. It is needed inside the derives. It is meant to support the default Substrate staking, so it is built completely around that.

our chain support the staking module, but our staking module has disabled the erasRewardPoints

**Comment by jacogr** [comment]
In that case the staking derives won't work as expected for calculated results, hence not being available.

**Comment by yashirooooo** [comment]
> In that case the staking derives won't work as expected for calculated results, hence not being available.

understood, thanks
