### ISSUE TITLE
Problem with signAndSend call failure  

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/api#4561]
![image](https://user-images.githubusercontent.com/45918704/153712953-6b3ca177-7e8c-4260-ad8a-c51a39a9483c.png)

`1002: Verification Error: Runtime error: Execution failed: Other("Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x693c - <unknown>!rust_begin_unwind\n    1: 0x2503 - <unknown>!core::panicking::panic_fmt::h81593b6faf34047a\n    2: 0x192834 - <unknown>!TaggedTransactionQueue_validate_transaction\n"): RuntimeApi, Execution failed: Other, \"Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\\nwasm backtrace:\\n    0: 0x693c - <unknown>!rust_begin_unwind\\n    1: 0x2503 - <unknown>!core::panicking::panic_fmt::h81593b6faf34047a\\…`

![image](https://user-images.githubusercontent.com/45918704/153712933-97ee2960-290b-40cd-b11b-bd14cc45abb4.png)

**Comment by jacogr** [comment]
The runtime is unable to execute your transaction. Ensure you construct it correct as per runtime expectations.

**Comment by 99Kies** [comment]
The chain I use is Rococo.(<https://rococo-rpc.polkadot.io>)

Account A has 100ROC, and account B has 30ROC. I want to realize the transfer function from account A to account B through the transfer interface.

**Comment by 99Kies** [comment]
I fixed it because of types problems.
