### ISSUE TITLE
Question about `yarn polkadot-types-from-chain` not generating custom types on the chain. Is this a normal condition?

### ISSUE THREAD

**Issue by Cupnfish** [polkadot-js/api#4569]
Question about `yarn polkadot-types-from-chain` not generating custom types on the chain.

Is this a normal condition?

<img width="423" alt="图片" src="https://user-images.githubusercontent.com/40173605/154233765-5e0d3203-2ed8-4dbf-9c20-bae93485a9dd.png">

<img width="580" alt="图片" src="https://user-images.githubusercontent.com/40173605/154233797-569528fe-1a3a-4367-b0c3-c5b7e91dec96.png">

**Comment by jacogr** [comment]
`types-from-def` generates both the user-defined and the lookup types. Order would be to run the defs first, the `from-chain` just re-uses the `lookup.ts` as generated.

**Comment by Cupnfish** [comment]
tks
