### ISSUE TITLE
`grandpa_proveFinality` RPC call typedef in Polkadot{.js} does not match Grandpa RPC API in Substrate

### ISSUE THREAD

**Issue by isSerge** [polkadot-js/api#4572]
I am using version `7.4.1` and trying to make `grandpa_proveFinality` RPC call. 

Typedef in `Polkadot{.js}` is following:
```
proveFinality: AugmentedRpc<(begin: BlockHash | string | Uint8Array, end: BlockHash | string | Uint8Array, authoritiesSetId?: u64 | AnyNumber | Uint8Array) => Observable<Option<EncodedFinalityProofs>>>;
```

However, when I provide `BlockHash` for `begin` and `end` parameters I got this error:
```
2022-02-17 10:33:06        RPC-CORE: proveFinality(begin: BlockHash, end: BlockHash, authoritiesSetId?: u64): Option<EncodedFinalityProofs>:: -32602: Invalid params: invalid type: string "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe", expected u32.
```

I have checked Grandpa RPC API and it expects only one parameter `block: Number`:
https://github.com/paritytech/substrate/blob/7409589ab78e7cb508db873dd6384634d667b8f5/client/finality-grandpa/rpc/src/lib.rs#L81

Thanks

**Comment by jacogr** [comment]
Change sees to be ancient in Substrate, introduced here - https://github.com/paritytech/substrate/commit/bd5c9a646896b11061a6ff92af3c673958e238eb

**Comment by isSerge** [comment]
Thanks, good to know. Is there any workaround to inject the relevant type?
