### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by DeveloperInProgress** [polkadot-js/api#4576]
I am trying to build a module with `@polkadot/api` dependency and I get the following errors in several places inside `@polkadot/api-augment/substrate/tx.d.ts:`

`Cannot find name 'SubmittableExtrinsicFunction'.`
`Cannot find name 'SubmittableExtrinsic'.`
`Cannot find name 'AugmentedSubmittable'.`

How may I resolve this?

**Comment by jacogr** [comment]
See -

- https://polkadot.js.org/docs/usage/FAQ#under-typescript-i-have-ts-compilation-errors
- https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing

**Comment by nuel77** [comment]
for custom chains this issue will be resolved by doing the type generation?
