### ISSUE TITLE
Ask for support to start repo locally

### ISSUE THREAD

**Issue by coolcorexix** [polkadot-js/api#4581]
Hello @jacogr , I been trying to contribute to the repo lately. But after struggling for days, I still have not set up a proper local workspace for debugging. My work is at here: https://github.com/coolcorexix/api/tree/investigate-4559 . It stuck with the TS configuration to run an extra workspace I created new.
Do you have any documentation on how to get setting for local bootstrapping. Thanks.

https://github.com/coolcorexix/api/tree/investigate-4559

**Comment by jacogr** [comment]
Sorry about the delay.

Generally for reproductions it is better wrapping it in a test, and testing from there. The alternative (which is generally use) is to just use the compile-copy to a new projects, i.e. assuming you have a structure like

```
<ROOT>/reproduction
<ROOT>/api
```

And in the reproduction you have the `index.js` and `package.json` with the API deps, you can copy the latest version of the API you are using into that folder via `cd api && yarn polkadot-dev-copy-to reproduction`

If you wish to add a new workspace, ensure you follow the same structure as the rest with the `tsconfig.*` files and then also add the links to the root `tsconfig.{base, build}.json` as well as `jest.config` (if going to be using Jest)

**Comment by phatNfqAsia** [comment]
OK, i got it up and running. To add to your answer, I have to paste in package.json version of the local built so that it does not get erased when I run 'yarn install' again. 
This can be closed now.
