### ISSUE TITLE
decoding `EncodedFinalityProofs`

### ISSUE THREAD

**Issue by isSerge** [polkadot-js/api#4583]
I am using `"@polkadot/api": "7.8.2-5"` and I am trying to decode response from `rpc.grandpa.proveFinality`, I receive `Option<EncodedFinalityProofs>` and when I try methods like `toJSON()` or `toHuman()` - both return result similar to this:
```
0x402ef1ab1cf6c7be59f5e3370c24b153fb1885fea2bd1c235c4716b0b500c9287e620500b213000000000000402ef1ab1cf6c7be59f5e3370c24b153fb1885fea2bd1c235c4716b0b500c9284ba6ae00710a402ef1ab1cf6c7be59f5e3370c24b153fb1885fea2bd1c235c4716b0b500c9284ba6ae005c28d1b33ddfcea8f631ad24e6b88fc9c4291ee2ce2f44bfe1a9a1861c7feac3e79252868f794a1cb3ac07c352bd3b4eaa683aaa6973aa3d7015d0b78eb7f304000e441df11d2886c8134a93a68dbf26e82d5eb862e0b652dac36452d1de7ef5402ef1ab1cf6c7be59f5e3370c24b153fb1885fea...
```
Is this expected? Is there a way to decode it properly? Thanks

**Comment by jacogr** [comment]
See here https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/rpc/src/finality.rs#L25 - the result via RPC is `Bytes`, aka encoded as returned. 

I have never looked at how it encodes it inside Substrate into the opaque result that is returned via RPC, so  your best bet is to look at where Substrate encodes it and decode it with the same underlying structure.

**Comment by isSerge** [comment]
got it, thanks!
