### ISSUE TITLE
about the signsend[nginx]

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/api#4584]
Hi

i am going to transfer signsend from vue front to the nginx -> (to local 9944 daemon socket)
but below code is not working well showing error.

can I know how to set it up from front vue to the nginx ?

```
error
index.mjs:378 WebSocket connection to 'ws://ip/transfer' failed:
```

```
<Vue front>
let wsProvider = new WsProvider('ws://ip/transfer');
let api = await ApiPromise.create({
       provider: wsProvider,
              types: {
              "Address": "AccountId",
              "LookupSource": "AccountId"
              }
        });

```

```
<Nginx>
location /transfer/ {
        proxy_pass http://localhost:9944;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Origin "";
    }

```

**Comment by jacogr** [comment]
Honestly no idea. Have never setup nginx.

**Comment by puffanddmx** [comment]
then how to send the coin to the api server using signsend without websocket connection?
most of example is based on websocket connection of WsProvider 9944 port to the substrate daemon like below~~
are there any rest signsend API without websocket base?

```
<Vue front>
let wsProvider = new WsProvider('ws://ip:9944');
let api = await ApiPromise.create({
       provider: wsProvider,
              types: {
              "Address": "AccountId",
              "LookupSource": "AccountId"
              }
        });
let result = await api.tx.balances
.transferKeepAlive(this.toaddress, amount)
.signAndSend(pair);
this.txhash = result.toString();

```

**Comment by jacogr** [comment]
The error you reported comes from the server itself, it is not code related.

Yes, there is an HTTP provider if your RPC server also exposes the 9933 port.

**Comment by jacogr** [comment]
- https://github.com/polkadot-js/api/blob/master/packages/api/src/bundle.ts#L7
- https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/http/index.ts

**Comment by puffanddmx** [comment]
i did what you suggest.
i got this below error.

```
vue.runtime.esm.js:1897 TypeError: B.HttpProvider is not a constructor
```

```
import {ApiPromise, WsProvider, HttpProvider} from '@polkadot/api';
let api = new HttpProvider('http://ip:9933');
let result = await api.tx.balances.transferKeepAlive(this.toaddress, amount)
                  .signAndSend(pair); 
```
