### ISSUE TITLE
Issue with signing the transaction

### ISSUE THREAD

**Issue by yvubr** [polkadot-js/api#4586]
@jacogr - I am trying to transfer westend tokens and below is my code

const keyring = new Keyring({ type: 'sr25519' });
    // const keyring = new Keyring({ type: 'ed25519' });

    // Provide and Api
    const wsProvider = new WsProvider('wss://westend-rpc.polkadot.io');
    const api = new ApiPromise({ provider: wsProvider });
    await api.isReady;
    .
    .
    .
    const transaction = api.tx.balances.transfer(account.address, randomAmount);

    // Get nonce
    const { nonce: non } = await api.query.system.account(account.address);
    console.log('Nonce : '+non);

    // Create a payload
    const payload = api.createType('ExtrinsicPayload',{
        method: transaction.toHex(),
        nonce: non.toHex(),
        specVersion: api.runtimeVersion.specVersion,
        genesisHash: api.genesisHash,
        blockHash: api.genesisHash
    }, { version: 4 });
    console.log(payload);
    
    const signature = account.sign(payload.toU8a(true));

    const signHex = u8aToHex(signature);
    console.log(signHex);
    
    transaction.addSignature(account.address, signHex, payload.toU8a());

    const hash = await transaction.send();
    console.log(hash);

Error in console is generated as below 

Nonce : 0
Type { createdAtHash: undefined, initialU8aLength: undefined }
0x3cc6b8e054be477ea25c747256bcd14b301db61aebd1371dab85cf61c91582799ddcc4d0a8089ed89e7d5e193c60ea1bc0683c2283b35d1a0bf806c25936a285
(node:27139) UnhandledPromiseRejectionWarning: Error: createType(ExtrinsicSignature):: Unable to create Enum via index 60, in Ed25519, Sr25519, Ecdsa
    at createTypeUnsafe (/Users/udaybhanuprasad/Documents/dojima/dojima-wallet-scripts/node_modules/@polkadot/types-create/create/type.cjs:73:18)
    at TypeRegistry.createTypeUnsafe (/Users/udaybhanuprasad/Documents/dojima/dojima-wallet-scripts/node_modules/@polkadot/types/create/registry.cjs:419:46)
    at Map.addSignature (/Users/udaybhanuprasad/Documents/dojima/dojima-wallet-scripts/node_modules/@polkadot/types/extrinsic/v4/ExtrinsicSignature.cjs:164:82)
    at Map.addSignature (/Users/udaybhanuprasad/Documents/dojima/dojima-wallet-scripts/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.cjs:101:20)
    at Submittable.addSignature (/Users/udaybhanuprasad/Documents/dojima/dojima-wallet-scripts/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:287:16)
    at Object.Polkadot (/Users/udaybhanuprasad/Documents/dojima/dojima-wallet-scripts/src/balance/polkadot.ts:62:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27139) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27139) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please let me know where I went wrong?

**Comment by jacogr** [comment]
Generally don't actually work with any raw signing at all, it it not really a supported avenue since the API takes care of that. With that said, you can look at the actual signing code here - https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/v4/ExtrinsicPayload.ts#L107

**Comment by yvubr** [comment]
Thanks for the help @jacogr . I was able to remove the error.
