### ISSUE TITLE
CreateType from hex or Uint8Array works incorrectly

### ISSUE THREAD

**Issue by osipov-mit** [polkadot-js/api#4587]
Hi there!

Code of [`decodeU8a` function](https://github.com/polkadot-js/api/blob/500e2022c39f247dd12054dfede45a3c855cf079/packages/types-codec/src/utils/decodeU8a.ts#L28) seems incorrect, rather [this line](https://github.com/polkadot-js/api/blob/500e2022c39f247dd12054dfede45a3c855cf079/packages/types-codec/src/utils/decodeU8a.ts#L40)

https://github.com/polkadot-js/api/blob/500e2022c39f247dd12054dfede45a3c855cf079/packages/types-codec/src/utils/decodeU8a.ts#L40

Is there a reason to use `value.initialU8aLength` to increase offset? Deleting this value resolves that issue.

I found that it was added [here](https://github.com/polkadot-js/api/pull/4127/files#diff-2b58011b4c60958643006ba8c6d09826ae3ad6d94a339dc1dffe4a895cdd16f7L30-R32)

I prepared a [small script](https://github.com/osipov-mit/polkadot-js-issue/blob/master/test.js), that shows this problem.
When I try to create some type from hex or Uint8Array `registry.createType` function fails. This doesn't always happen but only in the cases of structures with more than 2 fields.

You can check test run [here](https://github.com/osipov-mit/polkadot-js-issue/runs/5277394256?check_suite_focus=true#step:5:12)

**Comment by jacogr** [comment]
The issue is rather that BTreeSet is probably incorrect so it consumes too many bytes here, leaving 1 less for the `H256` - 

https://github.com/polkadot-js/api/blob/500e2022c39f247dd12054dfede45a3c855cf079/packages/types-codec/src/extended/BTreeSet.ts#L88

The `initialLength` is a speed and resource optimisation.

**Comment by jacogr** [comment]
Indeed, running this test -

```js
  it.only('correctly encodes/decodes the length', (): void => {
    const one = new (BTreeSet.with(U32))(registry, []);
    const hex = one.toHex();
    const two = new (BTreeSet.with(U32))(registry, hex);

    expect(one.encodedLength).toEqual(two.initialU8aLength);
  });
  ```
  
  yields -
  
  ```
    ● BTreeSet › correctly encodes/decodes the length

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 1

      139 |     const two = new (BTreeSet.with(U32))(registry, hex);
      140 |
    > 141 |     expect(one.encodedLength).toEqual(two.initialU8aLength);
          |                               ^
      142 |   });
      143 |
      144 |   it('correctly sorts numeric values', (): void => {

      at Object.<anonymous> (packages/types-codec/src/extended/BTreeSet.spec.ts:141:31)
```

**Comment by osipov-mit** [comment]
Thank you a lot
