### ISSUE TITLE
Batching signed transactions

### ISSUE THREAD

**Issue by drbh** [polkadot-js/api#4589]
How do you `batchAll` a list of signed transactions?

I'd like to send a batch of transactions signed by multiple parties. Is this functionality possible?

pseudo code: 
```ts
let firstSigned = await tx.sign(signerOne, { nonce });
let secondSigned = await tx.sign(signerTwo, { nonce });

let batch = [firstSigned, secondSigned];

await api.tx.utility.batchAll(batch).signAndSend(signer, { nonce }, callback);
```

**Comment by jacogr** [comment]
utility.batch/batchAll is validated as signed from a single sender in the runtime, the txs are not signed, the outer batch/batchAll is signed.

**Comment by drbh** [comment]
@jacogr thank you! however the functionality I'm looking for is sending a batch of presigned transactions. 

Is there a function that allows this? If not, can you point me to the location in substrate that would need to be updated for this feature?

Thanks!

**Comment by jacogr** [comment]
Look at the utility pallet.

**Comment by drbh** [comment]
thanks @jacogr
