### ISSUE TITLE
Enum decoding Error: Unable to decode storage decodeU8 : Cannot construct unknown type null

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/api#4597]
I am getting an error while decoding enums using polkadot.js/api version 7.9.1

This is the full decoding error i am getting
```
  DRR: Unable to decode storage decodeU8a: failed at 0x009001701220099003ddbbdfb0f41f0d… on tokenB:: DoNotConstruct: Cannot construct unknown type null
  ```
The tokenB is of type AssetId where, 
This is how the type is defined in the rust side.
```rs
pub enum AssetId {
    POLKADOT,
    Asset(u64),
}
```
This is how i defined it on the extended types on javascript 

```js
 AssetId: {
    _enum: {
      One: null,
      Two: "u64",
    },
  }
  ```
am i doing anything wrong here .  This was working in the older version 6.3.1 where i used the js enum as 
```js
 AssetId: {
    _enum: {
      POLKADOT: null,
      Asset: "u64",
    },
  }
  ```
But is failing with the new 7.9.1 version.

**Comment by nuel77** [comment]
issue moved to polkadot/api github page

**Comment by jacogr** [comment]
This definition should be -

```
AssetId: {
    _enum: {
      One: "Null",
      Two: "u64",
    },
  }
 ```
 
 `Null` is an actual Codec type `null` is not.

**Comment by nuel77** [comment]
alright, I tried with "Null", now the error is 
```
 DecodeU8a: Failed At 0x0423c78a000000000000000000900170… On TokenB: {"_enum":{"One":"Null","Two":"U64"}}:: Unable To Create Enum Via Index 4, In One, Two
 ```
 if "Null" should be used i guess a update to the docs will be helpfull
 <img width="505" alt="image" src="https://user-images.githubusercontent.com/50878033/155491776-7fcd5a9c-f8a4-4964-90ae-6feee4701328.png">

**Comment by jacogr** [comment]
That would seem correct, `0x0423c78a000000000000000000900170` has the first byte of 4, which means it looks for index 4 in the enum, there are only 2 entries.

It generally would mean that another type definition is wrong, i.e. for the records preceding this one.

PS: If the chain uses metadata v14, the metadata itself specifies the types completely, no need for manual definitions. (Manual is there currently for historic blocks)

**Comment by nuel77** [comment]
Okey let me try debugging the types before that.. 
So for metadat v14, we dont need to give the types field here? 
```js
await ApiPromise.create({
 provider
  types: {

    }
})
```
is it automatically injected from the provider ?

**Comment by nuel77** [comment]
I think its the decoding of the AccountID that is failing... 
```
 RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage interestedParticipantsAmounts:: createType(BTreeMap<Balance,BTreeSet<AccountId>>):: decodeU8a: failed at 0xcc816e946438b2b21b8a3073f983ce03…: BTreeSet<AccountId>:: decodeU8a: failed at 0x816e946438b2b21b8a3073f983ce03ee…: AccountId:: Invalid AccountId provided, expected 32 bytes, found 31
 ```
 These were working and decoding correctly on the old 6.3 version. Is there something i need to add manually to the 7. to make it compatable?

**Comment by jacogr** [comment]
It would most-probably be the structure even before the BTreeMap, when it gets there is runs out of bytes to decode from.

**Comment by nuel77** [comment]
This is the entire structure which its trying to decode ..  Balance is u64 except for that AssetId is the same as discussed above..
```js
{
    tokenA: "AssetId",
    creator: "AccountId",
    amount: "Balance",
    tokenB: "AssetId",
  }
  ```

**Comment by jacogr** [comment]
Just noticed the BTreeSet - there was a fix for decoding BTreeSet in master a couple of days ago, see https://github.com/polkadot-js/api/pull/4588, so you can try one of the latest betas. (Or wait for the next release, these go weekly so either Sunday or Monday)

**Comment by nuel77** [comment]
alright.. i will wait checkout the release . Thanks!
