### ISSUE TITLE
Can not decode `MultiAsset` properly when using subquery

### ISSUE THREAD

**Issue by tolak** [polkadot-js/api#4603]
Recently we are using Subquery index our xcm transactions, and we have an event with a parameter what which type is MultiAsset, in the handler we found that the what has the proper value, but when we trying to decode the fungible filed from it, this field becomes undefined.

The code is:
```
export async function handleXcmDepositedEvent(ctx: SubstrateEvent): Promise<void> {
    const {
        data: [what, who],
    } = ctx.event as unknown as IEvent<[MultiAsset, MultiLocation]>

    let hash = ctx.extrinsic?.extrinsic.hash.toHex()
    let recipient
    let isForward = false
    if (who.parents.eq(0)) {
        if (who.interior.isX1 && who.interior.asX1.isAccountId32) { // local account
            recipient = encodeAddress(who.interior.asX1.asAccountId32.id.toHex(), 42).toString()
        } else if (who.interior.isX3 && who.interior.asX3[2].isGeneralKey) {    // EVM account
            recipient = who.interior.asX3[2].asGeneralKey.toHex()
            isForward = true
        }
    } else {
        recipient = 'unknown'
    }

    logger.info(`===> XcmDeposited:\n`)
    logger.info(`asset: ${what.id.asConcrete.toString()}\n`)
    logger.info(`recipient: ${recipient}\n`)
    logger.info(`what: ${what}\n`)
    logger.info(`amount: ${what.fungibility.asFungible.toBigInt()}\n`)

    ... ...
}
```

The log message is:
```
subquery-node_1   | 2022-02-25T02:36:02.961Z <sandbox> INFO what: {"id":{"concrete":{"parents":1,"interior":{"x2":[{"parachain":2001},{"generalKey":"0x0207"}]}}},"fun":{"fungible":"0x000000000000152d02c7e1473cd36000"}} 
subquery-node_1   | subquery-node_1   | 2022-02-25T02:36:02.967Z <fetch> ERROR failed to index block at height 109 handleXcmDepositedEvent() TypeError: Cannot read properties of undefined (reading 'asFungible')
```
BTW, already upgrade packages to latest

**Comment by jacogr** [comment]
I don't know Subquery. If you have a minimal reproducible sample using the API itself, can take a look.

**Comment by jacogr** [comment]
Also be aware that in XCM, the field is named `fun`, see -

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/11562873

e.g

![image](https://user-images.githubusercontent.com/1424473/155746234-4ebefa38-f9a9-45e6-9a70-9fe09812982d.png)

**Comment by jacogr** [comment]
Those are v13 types. v14 types, as returned above are defined by the metadata itself. Definitions here - https://github.com/polkadot-js/api/blob/master/packages/types-augment/src/lookup/polkadot.ts#L428-L434

**Comment by tolak** [comment]
Looks like we may use the wrong type in client, but i am not sure. If we ingore the build error, we can access  filed `fun` in the run time, but can not access  field `fungible`. The log is:
```
subquery-node_1   | 2022-02-28T12:03:17.130Z <sandbox> INFO what: {"id":{"concrete":{"parents":1,"interior":{"x2":[{"parachain":2001},{"generalKey":"0x0207"}]}}},"fun":{"fungible":"0x000000000000152d02c7e1473cd36000"}}
subquery-node_1   |
subquery-node_1   | 2022-02-28T12:03:17.131Z <sandbox> INFO amount: undefined
```
The code is [here](https://github.com/tolak/khala-chainbridge-subql/blob/3bc57030f6e24acb5c36a780b148f5d548fbed5e/src/mappings/xtransfer.ts#L203).

Above code access `fungible`, if we just access `fun` it returns `{"fungible":"0x000000000000152d02c7e1473cd36000"}`

The event we are handling is defined with arguments `MultiAsset` and `MultiLocation` , see our runtime code [here](https://github.com/Phala-Network/khala-parachain/blob/ba68445cceb6fde989c3d856009f04d5caf83b45/pallets/xtransfer/src/xcm/xcm_transfer.rs#L88), and in the subquery side, we just catch it through [this way](https://github.com/tolak/khala-chainbridge-subql/blob/3bc57030f6e24acb5c36a780b148f5d548fbed5e/src/mappings/xtransfer.ts#L183)

**Comment by jacogr** [comment]
Access via `fun` is correct, it as an enum containing `Fungible` with the value.

**Comment by tolak** [comment]
Everything run as expected if i add @ts-ignore on `what.fun.asFungible`, unless the code will build failed with error "Property 'fun' does not exist on type 'MultiAsset'.", is this because the dismatch type?

**Comment by jacogr** [comment]
Like mentioned above in https://github.com/polkadot-js/api/issues/4603#issuecomment-1053210418, for metadata v14 you need to use the lookup types as linked. The types you are using is for the historic metadata v13, not the latest as supplied by the runtime metadata v14.

**Comment by tolak** [comment]
@jacogr Thanks a lot, definitely we should use the lookup version types. Close this issue.
