### ISSUE TITLE
Missing 'augmented' package in types since version 7

### ISSUE THREAD

**Issue by TobiWo** [polkadot-js/api#4604]
Since version 7 the `augmented` package which also declares the `lookup` module is missing for the types.

Reproducible example script
```
import { PalletStakingActiveEraInfo } from '@polkadot/types/lookup';

async function main(): Promise<void> {
  console.log('test')
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
``` 

This will cause an import error for version 7 as the relevant package (./node_modules/@polkadot/types/augment) is not present. Everything works as expected for version 6.

**Comment by jacogr** [comment]
See the CHANGELOG for the major version bump (which includes a FAQ entry as well) - https://github.com/polkadot-js/api/releases/tag/v7.0.1
