### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getRandomValues') at bundle.js 

### ISSUE THREAD

**Issue by paperfrog1228** [polkadot-js/api#4618]
Hi! I'm using this polkadot-js by bundling it to webpack.
I did bundling for common.js.

I tried to export and use your example code as a function below.

```
export function seedGenerate(){
     const keyring = new Keyring({ type: 'ed25519', ss58Format: 2 });
     const mnemonic = mnemonicGenerate();
     const pair = keyring.addFromUri(mnemonic, { name: 'first pair' }, 'ed25519');
     return pair.address;
}
```

That's why I got this error.

`TypeError: Cannot read properties of undefined (reading 'getRandomValues')`

So I checked the code and it was commented that you've already handled it in anticipation of bundling as below.

```
// Copyright 2017-2022 @polkadot/x-randomvalues authors & contributors
// SPDX-License-Identifier: Apache-2.0
function getRandomValues(arr) {
  // We use x-global here - this prevents packagers such as rollup
  // confusing this with the "normal" Node.js import and stubbing it
  // (and also aligns with eg. x-fetch, where x-global is used)
  return _xGlobal.xglobal.crypto.getRandomValues(arr);
}
```
Am I trying something wrong?
Of course, I confirmed that the function runs well before it is bundled.

**Comment by jacogr** [comment]
You probably need something along the line of https://github.com/polkadot-js/apps/blob/fdfc8236bc50e8479ae8d13c49a8ea4fdbf6dad9/packages/apps/webpack.base.cjs#L140

**Comment by paperfrog1228** [comment]
```
const path = require("path");

module.exports = {
    entry: path.resolve(__dirname, 'app.js'),
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        library: {
            name: 'EntryPoint',
            type: 'umd',
        },
        globalObject: '(typeof self !== \'undefined\' ? self : this)',
    },
    optimization: {
        minimize:false
    },
    resolve: {
        alias: {
            '@polkadot/wasm-crypto-wasm/packageInfo': require.resolve('@polkadot/wasm-crypto-wasm/packageInfo'),
            '@polkadot/wasm-crypto-wasm': require.resolve('@polkadot/wasm-crypto-wasm/empty'),
            '@polkadot/wasm-crypto-asmjs/packageInfo': require.resolve('@polkadot/wasm-crypto-asmjs/packageInfo'),
            '@polkadot/wasm-crypto-asmjs': require.resolve('@polkadot/wasm-crypto-asmjs/data')
        }
    }
}
```
this is my webpack.config.js.
It's still not working..

**Comment by jacogr** [comment]
Honestly not a webpack guru and never packaged as `umd` or `library`. (The npm packages actually does expose umd bundles generated via rollup). My guess if you need to inject some additional variable to make umd work as intended. For that the best I can suggest is google, checking for how others have solved for the `globalThis` variable.
