### ISSUE TITLE
Doesn't work with create-react-app prod build

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#462]
Currently the code relies on the class name

https://github.com/polkadot-js/api/blob/90a2e26540b9800325e207c91b0b8d2556900fb4/packages/types/src/codec/EnumType.ts#L67

However create-react-app prod build minifies the js code and mangle the class name (most of them end up been `t`), and breaks `EnumType`

**Comment by jacogr** [comment]
Umpf. This is an issue we need some solution for to make sure things "just work".

We actually had it in the https://github.com/polkadot-js/apps repo as well and addressed it by config. (But not using CRA there). We do have CRA in light-ui, so will run into the same there as well.

**Comment by jacogr** [comment]
We could add this to the build pipeline https://www.npmjs.com/package/babel-plugin-transform-class-display-name

Then we would basically check against `displayName` or `name` as a property. The only area where this will create problems is if users of this lib define their own types, i.e. those that don't go through the build step for the lib.

**Comment by xlc** [comment]
I think the proper solution is have the enum name as part of the input to `EnumType` constructor
So instead of taking array of constructors, change it to take a key-value object of constructors and use the property order as the index.
So instead of 
```
export class Phase extends EnumType<ApplyExtrinsic | Finalization> {
  constructor (value: any, index?: number) {
    super([
      ApplyExtrinsic,
      Finalization
    ], value, index);
  }
}
```
it becomes
```
export class Phase extends EnumType<ApplyExtrinsic | Finalization> {
  constructor (value: any, index?: number) {
    super({
      ApplyExtrinsic,
      Finalization
    }, value, index);
  }
}
```

**Comment by jacogr** [comment]
That would work with little impact. @amaurymartiny thoughts?

**Comment by amaurymartiny** [comment]
Yes, the above change for EnumType is a great idea.

I'm worried about other places where we use `someConstructor.name`, e.g.

https://github.com/polkadot-js/api/blob/90a2e26540b9800325e207c91b0b8d2556900fb4/packages/types/src/codec/typeRegistry.ts#L16-L32

CRA's uglify would break the registry too, right? We should probably force `{name: Constructor}` here (and everywhere else where .name is used)

**Comment by jacogr** [comment]
Yeap, if we use `.name` it will break unless passed in and checked in the same way as proposed for `EnumType`.

**Comment by jacogr** [comment]
I actually think the registry should be fine - if this issue does pop up, users can either specify the name or just pass the name+value object. 

I looked at the other `.name`'s in there, it is used in `Vector` and `Struct` to return the types. It _should_ hopefully be ok there since it is actually helpers, not really core. (And we don't really have a way around there at all, the `{ Object }` seems like real overkill for `Vector` - nothing will stop the API for working as with `EnumType`)

**Comment by xlc** [comment]
It works 🎉.
