### ISSUE TITLE
Fields of RPC error are not exposed

### ISSUE THREAD

**Issue by intendednull** [polkadot-js/api#4623]
On our node's rpc endpoint, we'd like to provide some context along with the error code:
```rust
RpcError {
    code: ErrorCode::InternalError,
    message: format!("Transaction failed: {}", e),
    data: ErrorContext { should_retry: false }.into_value(),
}
```

However it appears these fields are not accessible to client-side user code. Instead they are [merged ](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/coder/index.ts#L68) into the error message [immediately](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/coder/index.ts#L36). Is this the intended behavior? If I'm missing something here please let me know.

Otherwise I'd be happy to open a PR.

**Comment by jacogr** [comment]
It is intended behavior - this means that all throws indeed are for stock-standard JS `Error` object.

Exposing the actual full object can be done alongside by extending the `Error` object, however it is possible, but not something that JS actually likes, but there are hacks/workarounds around that behavior - https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript

**Comment by intendednull** [comment]
@jacogr would extending the error cause issues? I'm willing to add if it makes sense.

**Comment by jacogr** [comment]
Not as far as I recall - I had something like that somewhere that was lost in the sands in time. The only thing to check on something like that -

- stack traces still work (this is basically the more tricky part, but the above does cover that I believe)
- messages still work
- it is still an `Error`

**Comment by jacogr** [comment]
Here, I found the original implementation - https://github.com/polkadot-js/common/tree/fbc38aabc2b6c554d616d62ae7c84916eeac63e3/packages/util/src/ext (if re-added, just inside the rpc-core is perfect)

**Comment by MOZGIII** [comment]
That looks good, I'd only suggest chaning the name of the error to be `RpcError` or something like that - to better communicate the origin.

**Comment by intendednull** [comment]
> if re-added in some form, just inside the rpc-core is perfect since it would the the only place it is used
@jacogr wouldn't it be used in rpc-provider? Wouldn't that mean adding dep to rpc-core?
