### ISSUE TITLE
api.rpc.engine.createBlock is not a function

### ISSUE THREAD

**Issue by saiakilesh** [polkadot-js/api#4636]
I am trying to use manual-seal RPC call with TypeScript. I am using @polkadot/api version 6.12.1

But doing `await api.rpc.engine.createBlock(true, true);` gives me the error `api.rpc.engine.createBlock is not a function`.

Any help on how to get past this would be appreciated.

If it helps, here is a function I'm using:

```
/**
 * @description: fast forward {n} blocks from the current block number.
 */
export async function fastForward(
	api: ApiPromise,
	n: number,
	{ delayBetweenBlocks }: { delayBetweenBlocks?: number } = { delayBetweenBlocks: 5 }
): Promise<void> {
	for (let i = 0; i < n; i++) {
		const createEmpty = true;
		const finalize = true;
		await api.rpc.engine.createBlock(createEmpty, finalize);
		// sleep for delayBetweenBlocks milliseconds
		await new Promise((resolve) => setTimeout(resolve, delayBetweenBlocks));
	}	
}
```

**Comment by jacogr** [comment]
Check the output of the `rpc_methods` RPC - the API can only expose what is in there. If the Node doesn't expose it, it is not available.

aka `curl -H "Content-Type: application/json" -d '{"id":"1", "jsonrpc":"2.0", "method": "rpc_methods", "params":[]}' http://localhost:9933` or `api.rpc.rpc.methods()`

**Comment by saiakilesh** [comment]
You are correct, `engine_createBlock` is not exposed.

Do you know what needs to be done to expose it? I have no idea.

**Comment by jacogr** [comment]
I'm not a guru on the Substrate internals and how to ensure RPCs are exposed.
