### ISSUE TITLE
@polkadot/api 7.11.1 not working with jest testing framework

### ISSUE THREAD

**Issue by saiakilesh** [polkadot-js/api#4638]
I am getting the following error:
`Must use import to load ES Module: [...]/node_modules/@polkadot/x-bigint/shim.js`. Any insights on how to solve this would be appreciated. I tried configuring my `jest` config file and `tsconfig.json` in multiple ways, but nothing seems to work.

**Comment by jacogr** [comment]
There are multiple issues on Jest, see https://github.com/polkadot-js/api/issues?q=is%3Aissue+is%3Aclosed+jest

The bottom-line is that Jest ESM support seems to be lagging behind and it pulls in ESM despite the export maps. All the above issues have workarounds.
