### ISSUE TITLE
Uniques api is not decorated?

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#4640]
I am doing `import '@polkadot/api-augment';` but since version ~7.9.1, uniques API decoration doesn't seem to be working as expected

<img width="748" alt="image" src="https://user-images.githubusercontent.com/666169/157228380-32aeedeb-6533-4ea5-907d-4569eb93c2d9.png">

I think I was able to do type-casting before ~7.9.1 like so, but currently getting ts errors when trying to type cast the return codec types

<img width="760" alt="image" src="https://user-images.githubusercontent.com/666169/157228638-b5f09757-3203-459f-bbec-3908cab8d04e.png">

Is there anything obvious that I am doing wrong?

**Comment by Yuripetusko** [comment]
Other examples, also uniques api

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/666169/157230972-af6f50b6-d671-41f9-8470-2418738a8945.png">


<img width="818" alt="image" src="https://user-images.githubusercontent.com/666169/157231345-26ca9c4d-28d6-4616-9c1d-8fa02bd1d12d.png">

**Comment by jacogr** [comment]
`createType` doesn't decorate the pallet-specific types, so use the lookup generic -

```js
import '@polkadot/api-augment';

import type { PalletUniquesClassMetadata } from '@polkadot/types/lookup';

import { ApiPromise } from '@polkadot/api';

async function main () {
	const api = await ApiPromise.create();
	const metadataClass = api.registry.createType<PalletUniquesClassMetadata>('PalletUniquesClassMetadata');

	console.log(metadataClass.data.toString());

	const [[key]] = await api.query.uniques.account.entriesPaged({ args: [], pageSize: 10 });
	const [acc, a, b] = key.args;

	console.log(acc.toString(), a.mul(b).toString());
}

main().catch(console.error);
```

As for the last 3 lines, the types are correct in my editor for those.

**Comment by Yuripetusko** [comment]
Thank you re: lookup types, however, the uniques query return types are still wrong for me. Hmm not sure what I am doing wrong

<img width="697" alt="image" src="https://user-images.githubusercontent.com/666169/157248149-f9769dcc-5fe1-4554-805d-481afc1d4dca.png">


```
// correct in editor on my side
const [[key, opt]] = await api.query.uniques.account.entriesPaged({
  args: [],
  pageSize: 10,
});
const [acc, a, b] = key.args;
console.log(acc.toString(), a.mul(b).toString(), opt.isSome);
```

**Comment by Yuripetusko** [comment]
In another project the types are fine, so perhaps something to do with my monorepo setup. Will keep digging and report here. Thanks

**Comment by Yuripetusko** [comment]
Had to change the entry file where I do `import '@polkadot/api-augment';` in enxt.js app, from `_app.tsx` to `index.d.ts`
