### ISSUE TITLE
 Invalid params: unknown field `storageDepositLimit`, expected one of `origin`, `dest`, `value`, `gasLimit`, `inputData`.

### ISSUE THREAD

**Issue by luozygithub** [polkadot-js/api#4643]
"@polkadot/api": "^7.3.1",
    "@polkadot/api-contract": "^7.3.1",
![image](https://user-images.githubusercontent.com/31771728/157580485-065f4c5f-362c-4dbf-9c5b-ebe9a2083ddb.png)

**Comment by andresvsm** [comment]
You should set the value to 0 in order to make it work. Empty string should also do the work.

**Comment by driemworks** [comment]
Any update on this? I'm facing the same issue using polkadot/api-contract@7.13.1.  I'm trying to read this function from my contract:

`        #[ink(message)]
        pub fn get_version(&self) -> [u8; 32] {
            return [1; 32];
        }
`

Using this call:

`
contractPromise.query.getVersion(account.address, {value: 0, gasLimit: -1});
`

I'm not using the storageDepositLimit parameter in my call, so I'm not really sure why this is being called out, but I'm getting this same error as above:

**RPC-CORE: call(callRequest: ContractCallRequest, at?: BlockHash): ContractExecResult:: -32602: Invalid params: unknown field "storageDepositLimit", expected one of "origin", "dest", "value", "gasLimit", "inputData".**

**Comment by andresvsm** [comment]
> Using this call:
> 
> `contractPromise.query.getVersion(account.address, {value: 0, gasLimit: -1});`
> 

I didn't try queries using the polkadot api-contract, but I'm pretty sure you can omit storageDepositLimit. Try to create the same query but without the { ... }

contractPromise.query.getVersion(account.address, 0, -1);

I have some queries on my app and I'm querying those values using that syntax.

**Comment by driemworks** [comment]
I was able to get the call to go through using a different syntax, as detailed in the api-contract readme: https://github.com/polkadot-js/api/tree/master/packages/api-contract

`api.tx.contracts.call(address, 0, 30000000, abi.messages.getVersion).signAndSend(account, result => callback(result));`

I tried the call using the contractPromise with the params in the braces flattened to just standard args (i.e. (address, 0, -1)) but the same issue persists. 

To build the contract, I'm using `cargo-contract 0.17.0-unknown-x86_64-linux-gnu` and `polkadot/api@7.13.1, polkadot/api-contract@7.13.1`. Here's my contract code: https://github.com/driemworks/contracts/blob/dev/iris_asset_exchange/lib.rs

**Comment by andresvsm** [comment]
Your approach works fine but I’m curious about how you create the contractPromise.

I’m pretty sure you’ve read this https://polkadot.js.org/docs/api-contract/start/contract.read

I’ll get back to you tomorrow with my example working

**Comment by driemworks** [comment]
This is how I was creating the contractPromise.
```
    const file = e.target.files[0];
    let reader = new FileReader();
    reader.onloadend = async () => {
      const abi = new TextDecoder("utf-8").decode(new Uint8Array(reader.result));
      let contractPromise = new ContractPromise(api, abi, address);
      setContractPromise(contractPromise);
    };
```

It works as intended when calling an exec function in a contract, i.e.:
`contractPromise.tx
        .publishSale({ value, gasLimit }, assetId, mintQuantity, assetPrice)
        .signAndSend(account, result => callback(result));`

So the error only happens when using `contractPromise.query.funcName....`

**Comment by andresvsm** [comment]
@driemworks 
I assume you use the frontend template as well. 
 
I create the instance the same way, but I don't upload the metadata.json file manually. I have it in the same directory just for development purposes. I actually don't do anything with it, I just import it and use it in the contractPromise call:
`import contractABI from '../config/contracts/metadata.json'
...
const contract = new ContractPromise(api, contractABI, address)`

Later on, I use the contract the same way as you do (I've been working on the kitties project so this is a simple call to query the number of kitties on chain).

`const { result, output } = await contractInstance.query.getKittiesCnt(
          accountPair.address,
          0,
          -1
        )`

I can only think of the package.json file, I'm working with the ^7.3.1 version of the api-contract.
I also use the signAndSend approach but only for methods that modify my contract's storage.

**Comment by driemworks** [comment]
I just discovered that I'm also facing the same issue when trying to make calls to 'read' functions via the polkadotjs UI. This is happening with both my own contract and the default flipper contract. After reading through this: https://substrate.stackexchange.com/questions/530/invalid-params-unknown-field-storagedepositlimit-error-when-getting-contract I think my issue is due to using an older version of substrate (which I can't currently upgrade due to libp2p version incompatibilities with the latest substrate master and a library I'm using, rust-ipfs). It seems the solution for me is to downgrade the polkadot/api and polkadot/api-contract versions to ones compatible with my version of substrate.
