### ISSUE TITLE
Unable to retrieve the specified block details for some blocks in Kusama

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#4645]
Using current App:

Parity Polkadot v0.9.17
api v7.11.2-1
apps v0.108.2-5

i.e #4401242:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/4401242

```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding babe.reportEquivocation:: Struct: failed on args: {"equivocation_proof":"BabeEquivocationProof","key_owner_proof":"KeyOwnerProof"}:: decodeU8a: failed at 0x0b003c6d0d7501… on equivocation_proof: {"offender":"AuthorityId","slotNumber":"SlotNumber","firstHeader":"Header","secondHeader":"Header"}:: decodeU8a: failed at 0x0b003c6d0d7501… on offender: AccountId:: Invalid AccountId provided, expected 32 bytes, found 7
```

**Comment by jacogr** [comment]
This one is going to be tough to track. It is obviously a types mismatch, but going that far back is always problematic, i.e. difficult to see the exact wrong types in the actual Rust source. (Thank heavens for metadata v14... doesn't solve this one, but means that at least this is not an issue in the future)

**Comment by jacogr** [comment]
Starts breaking here - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/0xa705551c969c1e8eb7118ee8db654bc6b30d578f75fa662a3a330ab012710f0f (4401242)

**Comment by jacogr** [comment]
Sadly I was right - it was literally hours (!!!) of debugging and a final hail-mary of 3 lines solved it. See https://github.com/polkadot-js/api/pull/4646 (will be in the next beta as soon as merged)
