### ISSUE TITLE
Unable to retrieve the specified block details for some blocks in Kusama

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#4649]
Still some types error in early Kusama blocks, #111111 is the first arbitrary one I found but I don't know where the problem starts.

Parity Polkadot v0.9.17
api v7.11.2-5
apps v0.108.2-6

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/111111

```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [2, 0]/[2,0]
```

**Comment by jacogr** [comment]
First problematic one -

 https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/461692
 
 Last good one -
 
 https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/461693
 
 461692 is the runtime upgrade block for runtime 1032

**Comment by jacogr** [comment]
Was actually fixed in the API this morning in https://github.com/polkadot-js/api/pull/4647

(Have not deployed to apps yet, will do so now)

**Comment by jacogr** [comment]
Deployed.
