### ISSUE TITLE
syncronize batch extrinsic call 

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/api#4651]
i have two calls which needs to executed one after another, will using api.tx.utility.batchAll(call1, call2) ensure that call1 is executed before call2?

**Comment by jacogr** [comment]
Refer to the runtime logic for execution - https://github.com/paritytech/substrate/blob/f5f286db0da99761792b69bf4a997535dcc8f260/frame/utility/src/lib.rs#L316
