### ISSUE TITLE
historical transactions

### ISSUE THREAD

**Issue by cao148** [polkadot-js/api#4654]
Excuse me, is there an rpc interface for returning historical transactions by address?

**Comment by jacogr** [comment]
```js
// the account we wish to query
const accountId = '1....';

// the point where the queries are to be executed
const blockHash = '0x.....';

// get the decorated API for that point of the chain
const apiAt = await api.at(blockHash);

// make queries at that point, e.g. system account details
const info = await apiAt.query.system.account(accountId);
```

Basically the `api.at` will decorate the interface for specific metadata at a specific point in the chain history. Everything available at that point will be decorated on the `apiAt.query.*` interface.
