### ISSUE TITLE
Serializing Submittable Extrinsics?

### ISSUE THREAD

**Issue by gorillatron** [polkadot-js/api#4655]
Is there a way to serialize and deserialize(encode, decode) a submittable extrinsic to json or binary so that it can easily be passed between processes?

My use case is that I have an api that needs to sign some transactions, but for security concerns I want to pass it to another local process that isn't exposed to the network in the same way. So I want to serialize it, send it to the "signer", deserialize on the signer and sign it.

**Comment by jacogr** [comment]
All objects in the api has a `toHex()` on them that can serialize.

(Bear in mind that the transaction itself is not what gets signed, rather there is a payload with the transactional information as well as additional information that gets signed, e.g. additional info would be the runtime spec version, the genesis hash, etc.)

If you are looking at 2 process signing, look at the tools repo - https://github.com/polkadot-js/tools/tree/master/packages/signer-cli

**Comment by alannotnerd** [comment]
To serialize: `(await TX.signAsync()).toHex()`
To deserialize: `api.tx(TX_HEX)`

refer: https://github.com/polkadot-js/apps/blob/69f810c39c7a4859b01fed19899d28c26fe44fc0/packages/page-extrinsics/src/Decoder.tsx#L48
