### ISSUE TITLE
Cannot read private member #isReadyPromise from an object whose class did not declare it

### ISSUE THREAD

**Issue by bobo-k2** [polkadot-js/api#4656]
I upgraded my project to @polkadot/api 7.11.1 and after that started getting the above error. Any ideas what could be wrong?

<img width="863" alt="image" src="https://user-images.githubusercontent.com/8452361/158466654-1dc9f15e-bfc6-4c6c-a4ef-4155510e3067.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/8452361/158466783-faf92ba4-2d3d-4046-acc8-6b3540e9da11.png">

**Comment by jacogr** [comment]
No actual idea, have not seen this one. The private class member is defined in the class that uses it -

- definition https://github.com/polkadot-js/api/blob/32f149599321a581bb064621ec18ff88b4532e7c/packages/api/src/promise/Api.ts#L97
- usage https://github.com/polkadot-js/api/blob/32f149599321a581bb064621ec18ff88b4532e7c/packages/api/src/promise/Api.ts#L169

Which bundler are you using here?

**Comment by bobo-k2** [comment]
Thank you for the quick response. We are using Webpack. The project I am having trouble with can be found here https://github.com/AstarNetwork/astar-apps/tree/feature/apr-from-api

**Comment by jacogr** [comment]
Somewhere a Proxy is used (either explicitly or implicitly due to the framework), which means you run into this - 

https://stackoverflow.com/questions/67416881/es6-proxied-class-access-private-property-cannot-read-private-member-hidden-f

You can see the `Proxy` usage in the stacktrace.

**Comment by jacogr** [comment]
I can reproduce it using a Proxy with the following -

```js
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main () {
	const proxy = new Proxy(new ApiPromise({ provider: new WsProvider() }), {});
	const api = await proxy.isReady;

	api.rpc.chain.subscribeNewHeads((h) => console.log(h.number.unwrap().toString()));
}

main().catch(console.error);
```

**Comment by jacogr** [comment]
Addendum, here is something that can work around the non-proxyable `isReady` -

```js
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main () {
	const wrapped = new ApiPromise({ provider: new WsProvider() });
        const $api = { isReady: wrapped.isReady };
	const proxy = new Proxy(, {});
	
	// for any further ops, we use the api object returned from isReady
	const api = await proxy.isReady;

	console.log(api.registry);

	api.rpc.chain.subscribeNewHeads((h) => console.log(h.number.unwrap().toString()));
}

main().catch(console.error);
```

**Comment by bobo-k2** [comment]
Thank you very much for the clarification and samples.
