### ISSUE TITLE
Problem w/ decode historical events

### ISSUE THREAD

**Issue by olehmell** [polkadot-js/api#4657]
I try to get events at block on [Subsocial Arch Node](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Farch.subsocial.network#/chainstate):

I use node with v14 metadata. And I follow this code:
```
const events = await (await api.at(blockHash)).query.system.events()
```

And I catch the error:
```
2022-03-16 19:23:59        REGISTRY: Unknown signed extensions EnsureAllowedToClaimTokens found, treating them as no-effect
2022-03-16 19:23:59        REGISTRY: Unable to resolve type SpaceId, it will fail on construction
2022-03-16 19:23:59        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x0001000000120016f9415c34da11ca5a…: {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x120016f9415c34da11ca5a35f3f18627… on event: {"index":"EventId","data":"Null"}:: Struct: failed on data: GenericEventData:: decodeU8a: failed at 0xc9120000000000000000010000001600…:: DoNotConstruct: Cannot construct unknown type SpaceId
```

But when I set up our `typesBundle` it works but I catch the error when I try to get data from storage:
```
DRR: Unable to decode storage spaces.spaceById: entry 0:: createType(PalletSpacesSpace):: {"id":"u64","created":"PalletUtilsWhoAndWhen","updated":"Option<PalletUtilsWhoAndWhen>","owner":"AccountId32","parentId":"Option<u64>","handle":"Option<Bytes>","content":"PalletUtilsContent","hidden":"bool","postsCount":"u32","hiddenPostsCount":"u32","followersCount":"u32","score":"i32","permissions":"Option<PalletPermissionsSpacePermissions>"}:: Decoded input doesn't match input, received 0xc91200000000000042be75cb933073a967d8cb8c6c723028208a678c5a58f5e8…79787274796d77796865008200000001000000170000000a0600000100000000 (214 bytes), created 0xc91200000000000042be75cb933073a967d8cb8c6c723028208a678c5a58f5e8…79787274796d77796865008200000001000000170000000a0600000100000000 (214 bytes)
```

**Comment by jacogr** [comment]
You need to version the types per release. See Kusama as an example - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts

So basically from your description when you set it, it is correct for an old runtime version range, but not for newer. But it applies to all. Hence the versioning.

**Comment by olehmell** [comment]
I try to make [spec](https://github.com/olehmell/subsocial-sdk/blob/fix-types-bundle/packages/definitions/src/interfaces/know-types.ts) from your example.

But I catch the same error.

I use it as:

```
const api = new ApiPromise({ provider, typesBundle }) 
```

**Comment by olehmell** [comment]
> 1. Which specific params are you using for the v14 query?
Nothing

> 2. Does the same query work on the apps UI? (latest API)
No, on apps UI work previous API, but I tried to use there, but got the same error

> 3. Which version of the api are you using?
7.10.1

**Comment by olehmell** [comment]
I saw that when I create an instance without `typesBundle` v14 query works fine, when I paste `typesBundle` - I got the problem w/ decode

**Comment by jacogr** [comment]
Like I mentioned, you need to apply the correct versioning to `typesBuyndle` - for the runtime point where v14 kicks in, you should have no types. As per the Kusama example I linked above, here is where v14 kicks in, no types -

https://github.com/polkadot-js/api/blob/f83d23d0f66b6e434e660abacbf3207f312f3636/packages/types-known/src/spec/kusama.ts#L184-L188

**Comment by olehmell** [comment]
I generated the [typesBundle](https://gist.github.com/olehmell/7af8a94868d510d1c9f03ca19ab1d9e9), all types ended on 16 spec version. The last version after an update to v14 metadata.

And set `{ minmax: [17, undefined], types: {} }`

It works on local apps UI and in a separate node.js script. But dont work in my repo where I want to use it:)
I use version polkadot/api `7.12.1`

So, It is problem w/ my app, I will try to find this problem :)

**Comment by jacogr** [comment]
Is your API versions matching in the repo that is not working? Asked differently, is it on latest?

As I recall (correct me if I'm wrong) you do use the BTreeMap/BTreeSet constructs _somewhere_ and I know that recently there has been a fix or two for that. Hence the question on "latest".

**Comment by olehmell** [comment]
> As I recall (correct me if I'm wrong) you do use the BTreeMap/BTreeSet constructs _somewhere_ and I know that recently there has been a fix or two for that. Hence the question on "latest".

I use `latest`, and in another repo, this issue was solved. So I think I have an issue only in the current repo, so I will find locally problem

But also I find new error when I try to get blocks that will create on the very old substrate (100-200 blocks on Subsocial node):

```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x00010000000d000484b5670000000000…: {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x0d000484b56700000000000000000000… on event: {"index":"EventId","data":"Null"}:: findMetaEvent: Unable to find Event with index [13, 0]/[13,0]
23-2 12:44:34 ERROR Substrate: Unexpected error during processing of Substrate events: Error: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x00010000000d000484b5670000000000…: {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x0d000484b56700000000000000000000… on event: {"index":"EventId","data":"Null"}:: findMetaEvent: Unable to find Event with index [13, 0]/[13,0]
```

**Comment by jacogr** [comment]
The above error is due to mismatched types for that runtime range.

**Comment by jacogr** [comment]
I need a blockHash, item and chain to test against the apps UI. (Just via the explorer and/or state apps, depending on “what”)

Without a reproduction there the link doesn’t help me.
