### ISSUE TITLE
Unexpected type for field `data`  (`RpcErrorInterface` and `JsonRpcResponseBaseError`)

### ISSUE THREAD

**Issue by intendednull** [polkadot-js/api#4659]
Both `RpcErrorInterface` and `JsonRpcResponseBaseError` declare their `data` field as either `string` or `number`, however in testing it appears as an `object`.

We should either add that to the type declaration, or fix the unexpected internal conversion. My vote is on the former.

**Comment by jacogr** [comment]
It would make sense to align it with what is in Substrate - so I would suggest to look at the definitions there are align here.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/4665
