### ISSUE TITLE
Alternative for system.events.at(hash)

### ISSUE THREAD

**Issue by jerryjren** [polkadot-js/api#4660]
Hi there,

In the previous version of polkadot api (6.*), we used to use `api.query.system.events.at(blockhash)` to get the `Vec<EventRecord>`. In the newer version of polkadot api (7.*),  I noticed that `api.query.system.events.at(blockhash)` has been deprecated and `api.query.system.events` does not take any argument.

Could you suggest the alternative way to get the events with given blockhash?

Another question, I understand the query result is return Codec now. How do we convert `Codec` to `Vec<EventRecord>`?

Thank you

**Comment by jacogr** [comment]
Here we is a similar issue in the last week - https://github.com/polkadot-js/api/issues/4635

**Comment by jerryjren** [comment]
> Here we is a similar issue in the last week - #4635

Thank you for your reply @jacogr , really appreciated.
