### ISSUE TITLE
Polkadot Js API handling bitfields wrong

### ISSUE THREAD

**Issue by wpank** [polkadot-js/api#4673]
Given the hex value for a availability bitfield for example:
`0x0100010500`
polkadot.js converts to `0000000100000000000000010000010100000000`

https://docs.rs/bitvec/latest/bitvec/order/struct.Lsb0.html

The rust code uses LSB ordering, which should make that hex:

`1000000000000000100000001010000000000000`

**Comment by jacogr** [comment]
The API only handles BitVec partially. It can be LSB or MSB based on the input type, e.g. for a current use see this from https://raw.githubusercontent.com/polkadot-js/api/master/packages/types-support/src/metadata/v14/kusama-types.json -

```
{
    "id": 484,
    "type": {
      "path": [
        "polkadot_primitives",
        "v2",
        "AvailabilityBitfield"
      ],
      "params": [],
      "def": {
        "composite": {
          "fields": [
            {
              "name": null,
              "type": 485,
              "typeName": "BitVec<u8, bitvec::order::Lsb0>",
              "docs": []
            }
          ]
        }
      },
      "docs": []
    }
  },
  ```
  
So the BitVec implementation currently is actually decode-only, it cannot re-encode actually so all use is meant to be directly on the `toU8a()` result (which just returns the input data exactly as it was provided). In the same vein the `toHex()` will just return the exact bytes as returned, as does the `toHuman()` interfaces.
  
There certainly is a need to pass the LSB/MSB info through to the decoder and as a result tweak displays as well as allow for full `Codec` functionality. As of now, it does not do it, it is still in the V0-make-it-not-break phase.
