### ISSUE TITLE
Still pending events/callbacks after disconnecting the api

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#4680]
After upgrading to recent version, the following script doesn't exit anymore:
```
import { ApiPromise, WsProvider } from "@polkadot/api";

const main = async () => {
  const api = await ApiPromise.create({
    provider: new WsProvider("wss://rpc.polkadot.io")
  });
  await api.isReady;

  // This prevents the error:
  // RPC-CORE subscribeRuntimeVersion(): RuntimeVersion:: disconnected from wss://rpc.polkadot.io: 1000:: Normal connection closure
  await new Promise(resolve => setTimeout(resolve, 1000));

  console.log(`Disconnecting...`);
  await api.disconnect();
  console.log(`Disconnected !`);

};

main();
```

**Comment by jacogr** [comment]
If you change `main().then(() => console.log('returned'));` then you will see the function does return. You should probably add a `process.exit(0)` there in the main return (or `process.exit(-1)` on a catch)

**Comment by crystalin** [comment]
Thank you @jacogr for the quick response

**Comment by crystalin** [comment]
Yes, I've relied on this package a lot before. I think it is important to ensure all listeners/callbacks are cleared when exiting (avoid memory leak when you instantiate it often)
