### ISSUE TITLE
Initalize API with `StorageEntryType` not latest

### ISSUE THREAD

**Issue by mustermeiszer** [polkadot-js/api#4686]
Hi, 

sorry, for needing help again. I am trying to connect the API with a `WsProvider` to a fairly old-substrate-chain. 

I am getting this error: 
```shell
 API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageEntryTypeLatest):: Invalid character
```

Is it possible to fix this by telling the API that I want to use older `StorageEntryType`s that work with the respective chain? 

#### Setup
node v14.16.1
polkadot-api v6.12.1

Edit: 
Changed polkadot-api version to the one in the yarn.lock not the one in the package.json

**Comment by jacogr** [comment]
Could you try the latest stable release? `7.13.1` the `6.x` series is quite old. 

Having said that, there has been `Invalid character` issues logged in the past, I cannot recall what was the cause of it. (So a search of closed issues may yield something.)

**Comment by mustermeiszer** [comment]
That solved it. Thanks again!

**Comment by mikiquantum** [comment]
Thanks @jacogr For the record, technically this solved it: https://polkadot.js.org/docs/api/FAQ/#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing
