### ISSUE TITLE
Using `polkadot.js/api` to sign XCM transactions 

### ISSUE THREAD

**Issue by SidecarMaster** [polkadot-js/api#4688]
Is it possible to use `polkadot.js/api` to sign XCM transactions? For example, from Karura to Kintsugi, or vice versa, which are already available on https://apps.karura.network/bridge.

**Comment by jacogr** [comment]
The JS API can send any extrinsic that you wish to send. So construct the correct extrinsic via `api.tx.polkadotXcm.*` and call `signAndSend` on it.

If you wish to know which message in `polkadotXcm.*` to construct for this cross-chain transfer, I guess that is a great question for https://substrate.stackexchange.com/
