### ISSUE TITLE
extrinsic_index

### ISSUE THREAD

**Issue by cao148** [polkadot-js/api#4693]
I want to use the polkadot/api library to get the corresponding hash through extrinsic_index, what method should I call？

**Comment by jacogr** [comment]
I'm not suer I understand the question? The only index available is the index of the extrinsic in the block.

Assuming you have used `api.rpc.chain.getBlock()` you can just call `.hash` on any extrinsic in that block to get the hash of it.

**Comment by cao148** [comment]
![image](https://user-images.githubusercontent.com/62193059/160334056-82680702-a767-47a9-a525-9ef6b628e27e.png)
