### ISSUE TITLE
How to unserialize Transaction (and other questions!)?

### ISSUE THREAD

**Issue by michaelramuta** [polkadot-js/api#4706]
I can break these out into separate issues if that would make more sense :)

I've been poking through this code quite a bit and have a few questions. I'll try to provide as much context as I can (and include what solutions I attempted):

1. How do I unserialize a transaction?
Lets say I have the variables for this transaction:
 `const transaction = await api.tx.staking.bond(address, stakingAmount, rewardDestination);`
I'm aware I can serialize this with `const serializedTransaction = transaction.hash.toHex()`, but how can I turn that back into a transaction I can sign/send? I get that this transaction object is easily re-creatable, it would even suffice for me to be able to create a transaction from a string? I also don't know how to do that :)
I've tried `api.createType('Extrinsic', serializedTransaction, { version: api.extrinsicVersion })`, but I'm unable to sign/send

2. How do I check the status of nominations for a staking account?
I've used `await api.query.staking.nominators(address)` but that just returns something like:
```
{
	"result": {
		"targets": [
			"{nominatorId1}",
			"{nominatorId2}"
		],
		"submittedIn": 4957,
		"suppressed": false
	}
}
```
This is useful but I don't know the statuses of each of them!

3. How do I create a `MultiAddress` object?
I want to set a stash account and controller account for this stake bonding.
I've tried messing around with `api.createType('MultiAddress'...`, but I haven't gotten anything to work. I figure it'll have to be some sort of array of hashes, but according to error messages I'm only allowed to input keys `id, index, raw, address32, address20`

If there is a resource that has answers to these please point me in the correct direction :)

Thank you!

**Comment by jacogr** [comment]
The "how do I interact" questions are really well suited to  [substrate.stackexchange.com](https://substrate.stackexchange.com/)

1. Actually answered on Stackexchange this week, see https://substrate.stackexchange.com/questions/1330/two-way-js-serlialise-between-hex-and-extrinsic-object

2. This is also a great question for that forum

3. It is an enum, same as above, but `{ id: <address here> }` will construct the enum (generally you probably never need to do this, API will convert where needed)

**Comment by michaelramuta** [comment]
Thank you!! Appreciate it, I'll go bother the folks on stackexchange!
