### ISSUE TITLE
Specifying particular module when creating types with the same name

### ISSUE THREAD

**Issue by isSerge** [polkadot-js/api#4716]
I am running a local Substrate node and I have two enum types with the same name (`ChainType`) in different modules, so when I try to create a type I get this error:
```
Error: createType(ChainType):: Cannot map Enum JSON, unable to find 'PolkadotLike' in development, local, live, custom
```
`development`, `local`, `live`, `custom` - these are enum variants in the first module, but I need to create an enum type in the second module (`PolkadotLike`). 

Is there a way to specify a particular module when creating types? 
Thanks

**Comment by isSerge** [comment]
Sorry, forgot to mention that I am using metadata v14. 
It seems like it only supplies `ChainType` from one module. It works if I specify type when creating API (just like I did before metadata v14)

**Comment by jacogr** [comment]
You need to reference the specific v14 type - it has the module name built-in.

**Comment by isSerge** [comment]
thank you!
