### ISSUE TITLE
Calling `.toU8a()` on `grandpa.proveFinality` query result returns Uint8Array with an extra byte

### ISSUE THREAD

**Issue by isSerge** [polkadot-js/api#4724]
I am using `"@polkadot/api": "^7.14.3"` and querying GRANDPA finality proof:
```
const proof = await api.rpc.grandpa.proveFinality(5863249);
const bytes = proof.toU8a();
const hex = proof.toHex();
const bytes2 = new Uint8Array(Buffer.from(hex.slice(2), 'hex'));
```
I would expect `bytes` and `bytes2` to have the same value, however, there is an extra byte in the first one:
```
bytes1:  Uint8Array(26357) [
    1, 194, 155,   1,   0, 119,  56,  11, 160,  86, 149, 174,
  153, 202, 192,   5, 159, 117,  89, 246,  83, 133,  58, 229,
  148, 227, 139,  82, 135,  71, 120,  89, 122,   8, 164, 155,
   99,  46, 155,   1,   0, 134,  81,   0,   0,   0,   0,   0,
    0, 119,  56,  11, 160,  86, 149, 174, 153, 202, 192,   5,
  159, 117,  89, 246,  83, 133,  58, 229, 148, 227, 139,  82,
  135,  71, 120,  89, 122,   8, 164, 155,  99,  81, 119,  89,
    0,  29,   3, 119,  56,  11, 160,  86, 149, 174, 153, 202,
  192,   5, 159, 117,
  ... 26257 more items
]
bytes2:  Uint8Array(26356) [
  194, 155,   1,   0, 119,  56,  11, 160,  86, 149, 174, 153,
  202, 192,   5, 159, 117,  89, 246,  83, 133,  58, 229, 148,
  227, 139,  82, 135,  71, 120,  89, 122,   8, 164, 155,  99,
   46, 155,   1,   0, 134,  81,   0,   0,   0,   0,   0,   0,
  119,  56,  11, 160,  86, 149, 174, 153, 202, 192,   5, 159,
  117,  89, 246,  83, 133,  58, 229, 148, 227, 139,  82, 135,
   71, 120,  89, 122,   8, 164, 155,  99,  81, 119,  89,   0,
   29,   3, 119,  56,  11, 160,  86, 149, 174, 153, 202, 192,
    5, 159, 117,  89,
  ... 26256 more items
]
```

Is it expected? Thanks

**Comment by jacogr** [comment]
It is expected. In the Rust codebase, this is defined as `pub struct EncodedFinalityProof(pub sp_core::Bytes);` where `Bytes` is the same as `Vec<u8>`.

Any `Vec` types are encoded with the compact length, followed by the actual data.

If you want a it un-prefixed -

- use bytes.toHex() (the `toU8a()` variant will return the full SCALE-encoded value)
- use `compactStripLength` on the `bytes` after `toU8a()`

**Comment by isSerge** [comment]
Interesting, thanks for the prompt response!

**Comment by nazar-pc** [comment]
Hm... I'd expect to get fully SCALE-encoded value in either case because that is what RPC returned.

I see that it is deliberate, but must say `toHex` and `toU8a` not returning the same thing is really confusing behavior.
It is like if `Buffer.from(buffer.toString('hex'), 'hex') !== buffer`.

**Comment by jacogr** [comment]
- `toU8a()` is the SCALE-encoded value
- `toHex()` is the representation used over RPC (here eg. `Bytes` have no prefix)

In the first case you generally have types inside each other, so each types needs to conform to SCALE to be decodable.

In the second case when sending over hex values, the string itself has a length, so the JSONRPC layer doesn't need it.

**Comment by jacogr** [comment]
This is the same for the API -

```js
console.log(proof.eq(api.createType('GrandpaFinalityProof'), proof).toHex())); // true
console.log(proof.eq(api.createType('GrandpaFinalityProof'), proof).toU8a())); // true
```

On type creation, depending on the input format (basically where it came from), it decodes correctly and constructs equivalent types. (It nested inside another it is in SCALE format, in hex format is is raw from RPC)
