### ISSUE TITLE
How to use `polkadot-api` to send multiple transactions simultaneously?

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/api#4733]
when I want send more transactions.
the code will report this to me:
```
 RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (12562 vs 12562): The transaction has too low priority to replace another transaction already in the pool.
2022-04-09 23:44:45             DRR: 1014: Priority is too low: (12562 vs 12562): The transaction has too low priority to replace another transaction already in the pool.
2022-04-09 23:44:45        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (12562 vs 12562): The transaction has too low priority to replace another transaction already in the pool.
```
![image](https://user-images.githubusercontent.com/45918704/162581292-d45a3713-8305-4558-93b2-da716bd047da.png)
----
**My solution to this is to start multiple dockers and repeat the script.**
but I found that I could not connect over the `IP(like 192.168.xxx.xxx)` of the `LAN`.
Parallel chains can only be connected through `127.0.0.1`.(Even localhost is not supported).
this is my parachain start command.
```shell
./target/release/dorafactory-node \
--alice \
--collator \
--force-authoring \
--chain dora-roc-testnet.json \
--base-path /tmp/parachain/alice --log=info,xcm=trace,xcm-executor=trace \
--port 40334 \
--ws-port 8845 --ws-external --rpc-external --rpc-methods=unsafe --prometheus-port 9777 --prometheus-external \
-- \
--execution wasm \
--chain rococo-local-cfde.json \
--port 30344 \
--ws-port 9978
```
and this my `hosts`:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
```
this is my LAN ip:
![image](https://user-images.githubusercontent.com/45918704/162581605-e361fc42-884f-422f-8a19-a02b585ebde4.png)

this is my js-script error report:

![image](https://user-images.githubusercontent.com/45918704/162581615-38006524-f199-4045-9dca-bc3212f58307.png)
![image](https://user-images.githubusercontent.com/45918704/162581633-ed0e7594-f49d-4e1d-94ed-bf5f864dd34d.png)

this is my `WEB_SOCKET` on my `js-script`:
```javascript
const { ApiPromise, WsProvider, Keyring } = require('@polkadot/api');

const WEB_SOCKET = 'ws://192.168.1.4:8845';
const wsProvider = new WsProvider(WEB_SOCKET);
```

**Comment by jacogr** [comment]
This is a great question for https://substrate.stackexchange.com since it is not an enhancement request or bug report. It is the best way to get the community developer eyes on usage-related questions.

**Comment by jacogr** [comment]
Closing, logged here https://substrate.stackexchange.com/questions/1776/how-to-use-polkadot-api-to-send-multiple-transactions-simultaneously
