### ISSUE TITLE
Issue with NPM versions

### ISSUE THREAD

**Issue by gabrieljaegerde** [polkadot-js/api#4736]
there seems to be an issue with the npm versions. @polkadot/api uses a different version of @polkadot/util-crypto than is the @latest one on util-crypto npm.

**Comment by jacogr** [comment]
There are multiple versions, see the first entry -

```
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 9.0.1       /Users/user1/Documents/polkadot_projects/project1/node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 9.0.1       /Users/user1/Documents/polkadot_projects/project1/node_modules/@polkadot/api/node_modules/@polkadot/util/
```

This means that npm/yarn/pnpm installed `@polkadotutil` inside -

- `@polkadot/api-augment/node_modules/@polkadot/util/`
- `@polkadot/api/node_modules/@polkadot/util/`

A dedupe may be in order.

**Comment by gabrieljaegerde** [comment]
Thank you. Until now I never had to dedupe but that fixed it!
