### ISSUE TITLE
 Something Wrong with Democracy

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/api#4740]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/16152305/163145923-e6a9a72d-4b68-4d3e-b63e-28be0acefe34.png">

Why the standard vote's first param is a bool?

~~It looks like you are using `Vote` instead of `AccountVote`.~~

~~https://github.com/paritytech/substrate/blame/master/frame/democracy/src/vote.rs#L70-L76~~
~~https://github.com/paritytech/substrate/blame/master/frame/democracy/src/vote.rs#L29-L34~~

~~And the call needs `AccountVote`.~~

~~https://github.com/paritytech/substrate/blob/master/frame/democracy/src/lib.rs#L700~~

**Comment by jacogr** [comment]
That is the UI rendering component - it doesn't render aye + conviction, it only renders the "aye".

**Comment by AurevoirXavier** [comment]
> That is the UI rendering component - it doesn't render aye + conviction, it only renders the "aye". (It is a limited override only)

I can't vote on my chain. 
But it was worked a few days ago.
https://polkadot.js.org/apps/?rpc=wss://pangolin-rpc.darwinia.network#/democracy

```
react.01.387c2759.js:2 Uncaught Error: createType(Call):: Call: failed decoding democracy.vote:: Struct: failed on args: {"ref_index":"Compact<u32>","vote":"{\"_enum\":{\"Standard\":\"{\\\"vote\\\":\\\"u8\\\",\\\"balance\\\":\\\"u128\\\"}\",\"Split\":\"{\\\"aye\\\":\\\"u128\\\",\\\"nay\\\":\\\"u128\\\"}\"}}"}:: Struct: failed on vote: {"_enum":{"Standard":"{\"vote\":\"u8\",\"balance\":\"u128\"}","Split":"{\"aye\":\"u128\",\"nay\":\"u128\"}"}}:: Enum(Standard):: Struct: failed on vote: u8:: Assertion failed
```

I can vote from extrinsic.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/16152305/163170403-a7705fdc-e325-491d-b4dd-4e5b789fb706.png">

I check the democracy pallet, I didn't find some change.

**Comment by jacogr** [comment]
In the case of the Substrate-standard `AccountVote` metadata type path the `vote` value is aliased to a type that can do the `aye` + `conviction` encoding into a single `u8` instead of every user having to encode that manually. 

It implements the specialized encoding as found in Rust -

```rust
/// A number of lock periods, plus a vote, one way or the other.
#[derive(Copy, Clone, Eq, PartialEq, Default, RuntimeDebug, MaxEncodedLen)]
pub struct Vote {
	pub aye: bool,
	pub conviction: Conviction,
}

impl Encode for Vote {
	fn encode_to<T: Output + ?Sized>(&self, output: &mut T) {
		output.push_byte(u8::from(self.conviction) | if self.aye { 0b1000_0000 } else { 0 });
	}
}
```

**Comment by jacogr** [comment]
Applied wilcard matching on metadata type names in https://github.com/polkadot-js/api/pull/4741 - however this is a dangerous path, so would need to see the impact.
