### ISSUE TITLE
uniques entriesPaged  throws error 

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#4744]
I used to be able to do this:

```
const nftClasses = await polkadotUniquesApi.query.uniques.class.entriesPaged({
      pageSize,
      args: [],
});
```

To query paged entries from all classes, but now it throws an error

```
RPC-CORE: getKeysPaged(key: StorageKey, count: u32, startKey?: StorageKey, at?: BlockHash): Vec<StorageKey>:: -32603: Unknown error occurred: Client error: UnknownBlock: Header was not found in the database: 0x0000000000000000000000000000000000000000000000000000000000000000
DRR: -32603: Unknown error occurred: Client error: UnknownBlock: Header was not found in the database: 0x0000000000000000000000000000000000000000000000000000000000000000
```

empty `entries` call (non-paged) still works. Is this a change on polkadot.js or something changed on statemine itself?

**Comment by Yuripetusko** [comment]
Actually adding class id to args doesn't help either. So something happened with paged queries

**Comment by Yuripetusko** [comment]
I wonder if this is related to this PR https://github.com/polkadot-js/api/commit/39b1de326cd27d104c4c67a49cddcc67a25273d5

@xlc would you be able to chime in?

**Comment by jacogr** [comment]
Yes, the above doesn't look correct - it shouldn't use `0x000...000`, so there is a bug somewhere.
