### ISSUE TITLE
Give empty to Optional type argument

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/api#4754]
I am trying to query the blockchain , but one of the arguments is actually optional..
eg : ```blocks(u64, H256): Option <block>```

in the polkadot.js site i can see that we can pass "empty" to the second argument.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/50878033/163796329-914f0823-69ee-40bd-8da9-56613ce6eb03.png">

how do i give the second argument as empty programatically?

i tried  it doing ```api.query.mypallet.blocks(120, null)``` and ```api.query.mypallet.blocks(120)``` the first one gives back a null result and the scond one gives an error "mypallet.blocks(u64, H256) is a map, requiring 2 arguments, 1 found"

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/cookbook/storage#how-do-i-use-entrieskeys-on-double-maps

**Comment by nuel77** [comment]
Thanks !
