### ISSUE TITLE
How do I catch when the `WsProvider` failed on `health()`?

### ISSUE THREAD

**Issue by krhougs** [polkadot-js/api#4759]
Due to some issue to the substrate node, we got warning messages indicating keepalive failures:

```
2022-04-19 08:24:29        RPC-CORE: health(): Health:: No response received from RPC endpoint in 30s
```

How do I catch the corresponding exception with current api?

Related:
- https://github.com/paritytech/substrate/issues/11239
- https://github.com/Phala-Network/runtime-bridge/issues/83

**Comment by jacogr** [comment]
The keep alive warnings on health are not bubbled up. If it is useful to have an indicator, a specific event listener can be added without much effort.

**Comment by krhougs** [comment]
Just checked here:
https://github.com/polkadot-js/api/blob/40c78f95d29a781e0741348a8756eb51cf3854eb/packages/rpc-provider/src/ws/index.ts#L560
https://github.com/polkadot-js/api/blob/40c78f95d29a781e0741348a8756eb51cf3854eb/packages/api/src/base/Init.ts#L31

Seems there are not any events to work with this situation but only do logging. It would be nice if there be some event listeners to work with timeout or health failure.
