### ISSUE TITLE
Mocking Polkadot requests in Jest

### ISSUE THREAD

**Issue by michaelramuta** [polkadot-js/api#4760]
Howdy!

I'm building out some local unit tests and am trying to figure out how to mock Polkadot requests/responses. I'm doing my best to get mock-socket (https://github.com/thoov/mock-socket) working, but I'm wondering if there is any documentation on using this with Polkadot JS? I know that mock-socket is already integrated

If this is a better question for the Substrate Stackexchange, I'll post there instead!

Thanks! :)

**Comment by jacogr** [comment]
It is a great question for SE indeed :) I'm sure the community had put something together, somewhere for their usage. 

The API has a MockProvider that gets used in some tests, but it really is very, very hacky, non-comprehensive and requires a lot of TLC when trying to do anything substantial - https://github.com/polkadot-js/api/tree/master/packages/rpc-provider/src/mock (also non-reusable, so at best some ideas)

**Comment by michaelramuta** [comment]
Thank you! I'll take a peek and crosspost!
