### ISSUE TITLE
creating MultiSignature type

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/api#4762]
hello,
I've been using the keyring.sign() method which gives back a sr25519 signature, can i convert it to multisignature type as shown defined here 
https://docs.substrate.io/rustdocs/master/sp_runtime/enum.MultiSignature.html

i've been doing it by 
```js
let multiSig= api.createType("MultiSignature",  { Sr25519: keyring.sign(data.toU8a) } ) 
```

is this correct?

**Comment by jacogr** [comment]
Since it is a `MultiSignature`, you need to have a signature that is 65-bytes long where the first byte indicates the type. The `keyring.sign` options allows you to pass a flag to specify the generation of 65-byte signatures.

**Comment by nuel77** [comment]
the option given in keyring sign is 
```js
export interface SignOptions {
    withType?: boolean;
}
```

**Comment by jacogr** [comment]
Yes, `withType` add the pair type information to the signature.

**Comment by nuel77** [comment]
so i can change the first byte of the Uint8Array returned by
```js
signature: Uint8Array=  keyring.sign(payload, {withType:true}) 
```
to change to the different enums present in MulitSignature?
