### ISSUE TITLE
The the example in `README.md` at api-contract not working

### ISSUE THREAD

**Issue by xiyu1984** [polkadot-js/api#4772]
the example [here](https://github.com/polkadot-js/api/blob/master/packages/api-contract/README.md) is not working, maybe the interface is updated~

And so is the docs [here](https://polkadot.js.org/docs/api-contract/start/contract.read).

Maybe interfaces have been changed. Dose the docs need to be updated?

**Comment by jacogr** [comment]
Thank you for reporting, will remove it.
