### ISSUE TITLE
Sending 2 sudo transactions after each other results into error

### ISSUE THREAD

**Issue by dudo50** [polkadot-js/api#4780]
Is it possible to send 2 sudo transactions after each other on same api? I need to process them both in same time interval. If i set interval to 30 seconds both finish correctly because they get processed in different blocks.
Commands:

      //register asset Basilisk
      const call = api.tx.assetRegistry.register("UNIT","Token",0);
      const result = await api.tx.sudo.sudo(call).signAndSend(alice, (result) => { console.log(result.toHuman()) });
      
      //set asset location Basilisk
      const call3 = api.tx.assetRegistry.setLocation(3,{parents: 1, interior: "Here"});
      const result3 = await api.tx.sudo.sudo(call3).signAndSend(alice, (result) => { console.log(result.toHuman()) });

![Screenshot from 2022-04-27 19-51-34](https://user-images.githubusercontent.com/55763425/165588858-ed2b8441-0226-4b18-a2b9-696f2d6b81ee.png)

**Comment by jacogr** [comment]
Check error 3 in module 100 for the reason, this is not API related, the runtime code will have the reason for it.

**Comment by dudo50** [comment]
Yes you were right indeed. Calls were related sort of. Which ment calling the second one when first one was not yet processed in block was impossible. Thanks
