### ISSUE TITLE
BUG> Transfering XCM from Relay chain to parachain results in different account having tokens deposited

### ISSUE THREAD

**Issue by dudo50** [polkadot-js/api#4786]
So if I transfer tokens through official Polkadot UI everything works fine and correct account receives tokens. Transfering using api however results in different account being created and having tokens deposited to it besides of selecting correct address.

Api call> 
```
 const call = api.tx.xcmPallet.reserveTransferAssets({V1: { parents:0, interior:{ X1: {Parachain: 2090}}}}, 
 {V1:{parents:0,interior:{X1:{AccountId32: {network: "Any", id: "bXmPf7DcVmFuHEmzH3UX8t6AUkfNQW8pnTeXGhFhqbfngjAak"}}}}},
 {V1: [{id: {Concrete: {parents:0, interior: "Here"}}, fun:{ Fungible: this.amount}}]},0)
.signAndSend(keyring.createFromUri('//Alice'), (result) => { console.log(result) })
```
Result on destination parachain (Mind you, transaction was sent to alice address) : 
![Screenshot from 2022-04-30 15-27-17](https://user-images.githubusercontent.com/55763425/166107542-b8f38371-0d14-4204-9e1c-e0ce799ef35d.png)

What it should resuilt in however:
![Screenshot from 2022-04-30 15-27-34](https://user-images.githubusercontent.com/55763425/166107550-80567631-a7d7-486e-bc5a-f1437b516a96.png)

Using UI everything works and call is constructed same way as in API. So I do not know where the issue could be.
UI call that is working construction:
![Screenshot from 2022-04-30 15-29-36](https://user-images.githubusercontent.com/55763425/166107604-7ab8459e-75bb-489c-9ad6-9b0020b5c289.png)

![Screenshot from 2022-04-30 15-29-10](https://user-images.githubusercontent.com/55763425/166107830-a491f081-d247-4114-b81f-a435a0ce8bfe.png)

**Comment by jacogr** [comment]
In AccountId32 the id field is [u8: 32] and not an address as you pass in your code sample.  Since pass a string value there, the string itself is encoded as hex. 

Explicitly pass the publicKey hex as the id there. (The UI has a helper component for these, internally converting the address Dropdown selection into the underlying publicKey)

**Comment by dudo50** [comment]
Okay, I found this difference and wondered if that could be cause. How do I convert it please? Thank you

**Comment by dudo50** [comment]
SOLVED: it was decodeAddress from utils/crypto. Thanks for the hint and help Jaco. Appreciated.

**Comment by devdanco** [comment]
What I am using in AccountId32 is 
`api.createType('AccountId32', 'SOME_ADDRESS_HERE').toHex()` 
where **api** is **ApiPromise**
