### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by GopherJ** [polkadot-js/api#4797]
while upgrading @polkadot/api from v7.9 -> v8.3, we start to have the following issue with `@polkadot/typgen`:

```
node_modules/@polkadot/typegen/cjs/util/imports.js:98
  Object.entries(importDefinitions).forEach(_ref2 => {
                                    ^
TypeError: Cannot convert undefined or null to object
```

**Comment by jacogr** [comment]
It is quite possibly due to ordering - currently types-from-defs should be run first (to generate the `lookup.ts` file before `types-from-chain`.
