### ISSUE TITLE
findMetaError crashed in 7.8.2-2

### ISSUE THREAD

**Issue by GopherJ** [polkadot-js/api#4798]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/33961674/167282025-fca16d0e-aa4c-480e-9345-4ec28bd6b16b.png">

**Comment by GopherJ** [comment]
https://github.com/polkadot-js/api/blob/master/packages/types/src/create/registry.ts#L296-L298 looks fixed right? can someone confirm

**Comment by jacogr** [comment]
The API change went in alongside the Substrate change. I believe 7.15 was the version that added support. (The CHANGELOG can confirm)
