### ISSUE TITLE
Polkadot-js/api and polkadot-js-extension are generating different `address`es for the same `mnemonic`

### ISSUE THREAD

**Issue by ozgunozerk** [polkadot-js/api#4810]
When supplied the same mnemonic, the address generated on `polkadot-js/api` and `polkadot-js-extension(wallet)` are different.

Here are the screenshots
![image](https://user-images.githubusercontent.com/32795992/167442303-a3f57c2c-8910-47d2-b1c7-04cc161fb960.png)
![image](https://user-images.githubusercontent.com/32795992/167442333-fd23b1ee-cf51-4014-9703-0f2430bd020c.png)
![image](https://user-images.githubusercontent.com/32795992/167442361-a07bd31c-83c9-4769-b8ae-1fe5fcc2d110.png)

**Comment by jacogr** [comment]
The extension defaults to sr25519, you are using a ed15519 keyring.

**Comment by ozgunozerk** [comment]
I see. Sorry for the late reply. 
But why is API defaults to `ed15519` whilst the extension defaults to `sr25519`?
Isn't it making developers prone to error?

**Comment by jacogr** [comment]
The extension keyring is still ed25519, but all pairs are added as sr25519. (The Ed is just the default if no type is supplied). In the same fashion the apps UI for instance can add a pair of any type. 

Ed25519 was the first implementation. Sr25519 came later from the W3F. By changing the default type means that all code out on the wild behaves differently if the default is swapped - we don’t break user space.
