### ISSUE TITLE
how to create nft

### ISSUE THREAD

**Issue by polariseye** [polkadot-js/api#4817]
hi,could you give me some code to create nft in statemint.i can not create nft successfly.

**Comment by jacogr** [comment]
I would suggest pointing HOWTO questions to https://substrate.stackexchange.com/ so you could get community eyes on the question.

**Comment by polariseye** [comment]
i have create the question.could any one give the solution

https://substrate.stackexchange.com/questions/2545/how-to-create-nft-in-statemint
