### ISSUE TITLE
Query subscription to finalised blocks only

### ISSUE THREAD

**Issue by nahuseyoum** [polkadot-js/api#4818]
Is it possible to only subscribe to storage changes when the block the change occurred is finalised? 
I believe in the following code, as soon as the balance changes, the callback is triggered, but what I would like is to only act on the change when the block is finalised.

```
api.query.system.account(ALICE, ({ data: { free }}) => {
   // ... callback code
});
```

**Comment by jacogr** [comment]
The storage RPCs, as used by the API currently [only expose best-block functions](https://polkadot.js.org/docs/substrate/rpc#state), i.e. there are non available to track only finalized state changes natively on the RPC layer. 

It could probably be an enhancement request on the Substrate layer to add some of these RPCs.

It can obviously be glued-together with quite a bit of effort on the API layer, i.e. listen for finalized, re-query entries or wait for finalization before sending up changes on a specific block.
