### ISSUE TITLE
api.registry createType  return Codec

### ISSUE THREAD

**Issue by cinlk** [polkadot-js/api#4826]
My  @polkadot/api  version is 8.1.2-1,  I want to call  createType  to create balance type but it return Codec.

![截屏2022-05-14 10 30 57](https://user-images.githubusercontent.com/10222717/168407984-3b24a79a-1da9-4a4a-99a8-5fea70a70375.png)

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing

**Comment by cinlk** [comment]
> https://polkadot.js.org/docs/api/FAQ#since-upgrading-to-the-7x-series-typescript-augmentation-is-missing

got it, thanks~

**Comment by cinlk** [comment]
it looks good to me
