### ISSUE TITLE
`isReady` waits indefinitely in PROD

### ISSUE THREAD

**Issue by ozgunozerk** [polkadot-js/api#4833]
I have 2 issues, and I believe they are originating from the same issue. 

- **my 1st issue:**
I have a function to connect to some `publicApi: ApiPromise`.
This functions works in DEV, but waits indefinitely in PRODUCTION.
Below is the function:
```ts
public async connectPublicApi(): Promise<void> {
    if (!this.publicApi.isConnected) {
      await this.publicApi.connect()
    }
    try {
      await this.publicApi.isReady
    } catch(error) {
      util.errorLogger(error)
    }
  }
  ```
  I throughly debugged it, and via line-by-line print statements, i found out it waits indefinitely on `isReady` line.
  I put `try-catch` to debug, but `try-catch` does not fail -> no error is printed

- **my 2nd issue:**
Trying to generate a keyring using `sr25519`. I know I have to use `cryptoWaitReady()` for that. And I did. But still getting the error of: 
```
 The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
```
The code is below:
```ts
  public async createRewardAddress(): Promise<string> {
    try {
      const mnemonic = mnemonicGenerate()
      const keyring = new Keyring({ type: 'sr25519', ss58Format: 2254}) // 2254 is the prefix for subspace-testnet
      await cryptoWaitReady();
      const pair = keyring.createFromUri(mnemonic)
      this.mnemonic = mnemonic
      return pair.address
    } catch(error) {
      util.errorLogger(error)
      return "ERROR! Could not generate keyring"
    }
  }
```
Here are some more info on this issue:
it is working in DEV mode. In fact, even without `cryptoWaitReady()`, it is working in DEV. But it doesn't work (giving the error above) in PROD with or without it. 

### The reason I suspect both issues are originated from the same issue:
in the source file of `cryptoWaitReady()`, i saw this:
```ts
import { isReady } from '@polkadot/wasm-crypto';
export declare const cryptoIsReady: typeof isReady;
export declare function cryptoWaitReady(): Promise<boolean>;
```
I suspect `cryptoWaitReady` might be using the same underlying logic with `isReady` for `ApiPromise`, and hence, creating the above mentioned issues.

**Comment by ozgunozerk** [comment]
Yes, I used that:
```ts
export function createApi(url: string | string[]): ApiPromise {
  return new ApiPromise({
    provider: new WsProvider(url, false),
    types: apiTypes,
    throwOnConnect: true
  });
}
```

The behaviour is still the same, and it doesn't connect, nor generate error... Just waits...
And again, only in PROD. It works in DEV

**Comment by jacogr** [comment]
If by PROD you mean minified, that would point to your bundler and what it does. Somewhere it mangles the code in ways where it doesn't work.

If you mean PROD to be production URLs, the `throwOnConnect` would throw on connection issues.

**Comment by ozgunozerk** [comment]
I confirmed the issue is related to my bundler. Thanks for pointing that out @jacogr !
Appreciated your help 👍
