### ISSUE TITLE
functions in eth are not function.

### ISSUE THREAD

**Issue by heindrick17** [polkadot-js/api#4836]
functions(api.rpc.eth.*) are not working.

```
const provider = new WsProvider("wss://kusama-rpc.polkadot.io");
ApiPromise.create({ provider }).then((api) => {
  console.log(api.rpc.eth.accounts());
});
```

I am getting following error message. 
`TypeError: api.rpc.eth.accounts is not function
`
https://codesandbox.io/s/angry-rgb-5d9vwo?file=/index.js

**Comment by jacogr** [comment]
It is expected. The API is decorated based on what the runtime provides and what it extracts from the on-chain metadata - the runtime on Kusama doesn't include any [Frontier](https://github.com/paritytech/frontier) pallets. (Chains like Moonbeam provide those)

**Comment by heindrick17** [comment]
If then, how can I call eth functions?

**Comment by jacogr** [comment]
There are no ETH pallets on Kusama or Polkadot - they are not ETH chains, they are relay chains that doesn't try to support ETH-like compatibility features.

For ETH compatibility, connect to chains that apply ETH-like functionality, eg. Moonbeam/Moonriver/others. That is where those methods will be decorated.
