### ISSUE TITLE
Issues displaying/formatting data from `OpaqueNetworkState`

### ISSUE THREAD

**Issue by wpank** [polkadot-js/api#4838]
When polkadot.js decodes extrinsics in a block related to imOnline heartbeats, it often results in displaying something like:

```
      {
        isSigned: false
        method: {
          args: {
            heartbeat: {
              blockNumber: 12,736,127
              networkState: {
                peerId: 0x9800240801122072c6db141172ca99f3ac3265b0ce341ef52b937b9588f26337493bcb518c6648
                externalAddresses: [
                  x/ip4/142.132.149.240/tcp/30333
                  0x8c2f6970362f326130313a3466383a3236313a323563343a3a322f7463702f3330333333
                  h/ip4/10.110.16.4/tcp/30333
                ]
              }
              sessionIndex: 21,640
              authorityIndex: 592
              validatorsLen: 1,000
            }
            signature: 0x68b131b9279f94563912868d28adfef00183a193cd2544d1aa1c376901114850e792ef58f24001efee1f33291dbbd1f3b9e013fed2e4ea5325cd9eb347ad2387
          }
          method: heartbeat
          section: imOnline
        }
      }
```

The `networkState` (which I think is an [OpaqueNetworkState](https://github.com/paritytech/substrate/blob/01a3ad65d933cc58e79c04d114edb4d6c69b470a/primitives/core/src/offchain/mod.rs#L189) sometimes will be in hex, and also has some prefixes like `x/` or `h/`, which I'm not sure is related to a MultiAddr. 

Is this an issue with decoding these structs? 

One example is from Kusama block [#12,736,360](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/0x7d318e165aa929cfa7519c5dc2b688295a54ee48780a89bef61259163c52dc10), which looks to decode the network state as:

```
              networkState: {
                peerId: 0x98002408011220e3bcbe21c975ba34be904c62ecda0ee4aa3c0a48072bdea93597bca6daad8f80
                externalAddresses: [
                  x/ip4/142.132.236.141/tcp/30333
                  0x902f6970362f326130313a3466383a633031303a386335363a3a312f7463702f3330333333
                ]
              }
```

**Comment by jacogr** [comment]
The display is a bit wonky, it tries to detect ascii and then applies rules based on that. Lemme check those against the types on the RPCs.

**Comment by jacogr** [comment]
So, the decoder does do the right thing -

```
0x
0903 // length
04 // unsigned, v4
0b00 // imonline.heartbeat
6757c200 // blockNumber
9c // 39 length for peerid
98002408011220e3bcbe21c975ba34be904c62ecda0ee4aa3c0a48072bdea93597bca6daad8f80 // peedId, non ascii
08 // 2 length for Bytes[]
7c // 31 length for first
782f6970342f3134322e3133322e3233362e3134312f7463702f3330333333
94 // 37 length for second
902f6970362f326130313a3466383a633031303a386335363a3a312f7463702f3330333333
88540000 // sessionindex
70030000 // authorityIndex
e8030000 // validatorsLen
06a5f5d69530b166f4b88081910b2bd0ea1367554d98fb0e8ca3e9ceaee97079 // sig 1st 32
ad5b881861629888ee1958bc76ea50e02712527a951c5c546b4d5a445e002984 // sig 2nd 32
```

This issue is that this it cannot display as ascii - `902f6970362f326130313a3466383a633031303a386335363a3a312f7463702f3330333333` - the first character is 144, which would print to this - `�/ip6/2a01:4f8:c010:8c56::1/tcp/30333`

So in this case it expect chars > 32 & < 127 to be able to print it.
