### ISSUE TITLE
AccountIndex returning "incorrect" format

### ISSUE THREAD

**Issue by danielSbastos** [polkadot-js/api#4841]
Hey,

I've been having issues with the `AccountIndex` for a while where its value returns as a number even if `toString()` or `toHuman()` is called. FYI: We are connecting to the Kusama RPC.

**Example**

The image below is a screenshot of the current defender in the Kusama Society: 
![image](https://user-images.githubusercontent.com/21130697/169404167-5b20a2e0-f019-48bb-9438-76abdd703561.png)
As you can see, their index is set to `sSS`, **however**, the value I get is `150`.

Here is the code used to fetch the index (nothing much going on):
```js
api.derive.accounts.idToIndex(member.accountId, (accountIndex: AccountIndex) => {
  accountIndex && setIndex(accountIndex)
})
```
and the results for the given account

![image](https://user-images.githubusercontent.com/21130697/169404818-e04a30c3-f40e-49d2-8ed9-30b628cffe5d.png)

**Comment by jacogr** [comment]
Testing this in the JS console on the apps UI, I get -

```js
const a = await api.derive.accounts.idToIndex('EPhV6vifCet2sJPPCNGnUZdRhsQpfcsbxRvDkjsMPPCCvwR')

console.log('a', a.toString())

api.derive.accounts.idToIndex('EPhV6vifCet2sJPPCNGnUZdRhsQpfcsbxRvDkjsMPPCCvwR', (b) => console.log('b', b.toString()))
```

Both logging `sSS`. However, technically both are correct. On the chain, the index is a simple number, so for instance when I go `a.toNumber()` (or `b.toNumber())` it also returns 150. `sSS` is the ss58 representation of that number.

So you can always take the number into ss58 by `api.registry.createType('AccountIndex', 150).toString()`

In your case, no idea why it doesn't return the actual `AccountIndex` type, where are you in regard to API versions? (I do know there was an issue quite some time ago that was related to this, cannot remember the details, but I know I stumbled on it in the apps UI itself, however it was fixed a very long time ago, https://github.com/polkadot-js/api/pull/4059)

**Comment by danielSbastos** [comment]
Hey, @jacogr. What a weird issue, perhaps it is related to the arguments passed to the `ApiPromise`? Nonetheless, manually turning the number into a ss58 solved the problem. Thanks!
