### ISSUE TITLE
api.query.system.account(0) or account("")  unexpected return value 

### ISSUE THREAD

**Issue by cinlk** [polkadot-js/api#4842]
I  think that  calling  api.query.system.account(0) or api.query.system.account("")  should give me FrameSystemAccountInfo data  
```{"nonce":0,"consumers":0,"providers":0,"sufficients":0,"data":{"free":0,"reserved":0,"miscFrozen":0,"feeFrozen":0}}```
as expected  for any substrate node.

But I found those substrate node (wss://crab-rpc.darwinia.network, wss://pangolin-rpc.darwinia.network, wss://mandala.polkawallet.io, wss://mainnet.chainx.org)    has  no zero value at field of 'free'.

My polkadot version is   "@polkadot/api": "8.1.2-1".

**Comment by jacogr** [comment]
Each chain is different and has different types, as customized by the teams. There is no "standard", Substrate is meant to be customized. A good example is actually Crab, it has fields such as `freeKton` and `reservedKton`. (Obviously when connecting to the chains directly, assuming they are not using metadata v14, you also need to apply their types to adjust for their customizations)

**Comment by jacogr** [comment]
Seems this just popped-up on SO as well. See https://substrate.stackexchange.com/a/2946/627 for explicit checks against an explorer for the empty address.

**Comment by cinlk** [comment]
I see this reason
Thanks for your response.
