### ISSUE TITLE
WsProvider is only connectind to development node and not any other node

### ISSUE THREAD

**Issue by Abhishek-1857** [polkadot-js/api#4848]

**Comment by Abhishek-1857** [comment]
what i meant with this issue was that wsProvider in polkadot.js is only connecting to 9944 one endpoint and if i change it to some other endpoint for example 9946 it still says can't connect to 9944 ... its like that wsProvider is hardcoded to 9944 one endpoint. 
Please help @jacogr

**Comment by jacogr** [comment]
There is no hardcoding whatsoever. It connects to the url the user of the library specifes, e.g. `<protocol>://<host>:<port>` see the code [where it is assigned](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/ws/index.ts#L120-L135) and [where it connects](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/ws/index.ts#L192-L208)

**Comment by Abhishek-1857** [comment]
> There is no hardcoding whatsoever. It connects to the url the user of the library specifies, e.g. `<protocol>://<host>:<port>` see the code [where it is assigned](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/ws/index.ts#L120-L135) and [where it connects](https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/ws/index.ts#L192-L208)
> 
> You obviously need to pass in an endpoint to your Provider, if you don't it will assume localhost:9944 - it cannot guess where the port is.

Yes thank you i figured it out . I just has one more question .How can decode my custom event data which comes in bytes when contract event is emitted. There was one issue regarding this question but i can't get the hold of how to do it. If you can provide me some steps or something it will be a great help.  Thank you

**Comment by jacogr** [comment]
Please don't cross issues - the Abi provides event decoding, see https://github.com/polkadot-js/api/blob/f701c398c349159d5afd7344ea38c1d52e4aab56/packages/api-contract/src/Abi/index.ts#L111

For HOWTO, I would generally suggest [Stackoverflow](https://substrate.stackexchange.com/) to keep the issue-tracker for actual enhancements and issues (which is given priority here).
