### ISSUE TITLE
How to decode events from a specific past block without subscription

### ISSUE THREAD

**Issue by ManUtopiK** [polkadot-js/api#4863]
I found only this query that works, but is deprecated :
`await api.query.system.events.at('0x27393fff9fa1cddc2bcf00486594c8453807971838d8acd260971f3f2398e1bc')`

I know how to request manually event from raw storage, but I don't know how to decode this encoded event:
`await api.rpc.state.getStorage('0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7')`

I need how to decode manually a raw storage event, or a method to get the event at specific past block without subscription.
Thanks in advance for your help!

**Comment by jacogr** [comment]
```js
const apiAt = await api.at('0x27393fff9fa1cddc2bcf00486594c8453807971838d8acd260971f3f2398e1bc');
const events = await apiAt.query.system.events();
```

The `api.query.<module>.<method>.at(<blockHash>)` won't be removed soon (there are too many users of it), however it does have issues in that it uses the current metadata when forming the query. The `api.at(<blockHash>)` form gets an instance of the api with the runtime metadata at that specific point. (The deprecated form actually uses `api.at(<blockHash>)` form underneath)

**Comment by ManUtopiK** [comment]
Ok, I got it!
Thanks for your response.
