### ISSUE TITLE
Does it cause memory leaks when using getBlock() or getHeader() ?

### ISSUE THREAD

**Issue by madwiki** [polkadot-js/api#4871]
###Environment:
nodejs v16.x and v18
polkadotjs 6.x, 7.x and 8.x (6.x has more serious memory leaks than 7.x and 8.x)

I created a repo for example:
https://github.com/madwiki/polkadotjs-memory-example

```javascript
async function causeMemoryLeak(api: ApiPromise, count: number) {
  const hash = await api.rpc.chain.getBlockHash(count);
  console.log(`${count} : ${hash.toString()}`);
  await api.rpc.chain.getBlock(hash);
}


async function noMemoryLeak(api: ApiPromise, count: number) {
  const hash = await api.rpc.chain.getBlockHash(count);
  console.log(`${count} : ${hash.toString()}`);
}
```

When I called causeMemoryLeak() at intervals, promises in heap were keep growing.

![WechatIMG71](https://user-images.githubusercontent.com/13521165/170901476-ee484166-2c2d-4774-b5ba-293d59c575f2.jpeg)
![WechatIMG72](https://user-images.githubusercontent.com/13521165/170901479-84076262-d1b8-45a1-b3fa-66866ff49160.jpeg)
![WechatIMG73](https://user-images.githubusercontent.com/13521165/170901483-73c5463b-1e58-4746-98ca-1f0b0ae7d827.jpeg)

But when I called noMemoryLeak() by the same way, promises in heap will remain at a certain amount and didn't increase.

But their memory all will slowly and continuously increase, is it because of the cache? Can they be cleared?

**Comment by jacogr** [comment]
There is a LRU for queries using `blockHash`, e.g. as in your example `getBlock(<blockHash>)`, the implementation is here - 

https://github.com/polkadot-js/api/blob/6192e60668f0e72fc557592772267ae23bd3fce0/packages/rpc-provider/src/lru.ts#L4-L7

It is not unbounded (see the limits above), however the count limit is actually slightly high at this point in time based on even all-historic traversal usecases.

**Comment by madwiki** [comment]
It seems not configurable?
https://github.com/polkadot-js/api/blob/6192e60668f0e72fc557592772267ae23bd3fce0/packages/rpc-provider/src/ws/index.ts#L82-L83

**Comment by jacogr** [comment]
No, it is not configurable. It certainly would make sense to have _everything_ tweakable, however -

- at this point all the provider options is one big array of params
- what it really should be is `WsProvider(endpoints: string | string[], option?: Options)`
- the above is easy enough, however it comes with a backwards-compat caveat (i.e. needs detection for old-style as well, both forms should work with the older form deprecated)

With that in-place, it is easy enough to extend the `Options` object. However until we can have a PR that applies the above, adding more options is a slight road to maintenance woes.
