### ISSUE TITLE
Handling Option<bool> as OptionBool is incorrect

### ISSUE THREAD

**Issue by CertainLach** [polkadot-js/api#4874]
In this commit: https://github.com/polkadot-js/api/commit/5a90d02f1fc890a4a7357dfd670c586f4660938d code assumes that Option<bool> is always encoded as 1 byte, however this specialization is opt-in (https://github.com/paritytech/parity-scale-codec/blob/d70f8d474bdbcf3c6eaa580ec8983cdab1b4743e/src/codec.rs#L530-L532), as opposed to spec `As an exception, in the case that the type is a boolean, then it is always one byte`:
https://github.com/paritytech/parity-scale-codec/issues/89

As result, if chain expects to receive `Option<bool>`, it is no longer possible to pass this value from polkadot.js

**Comment by CertainLach** [comment]
Yes, in our chain we use `Option<bool>`, and latest release breaks extrinsics using it (`Failed to convert parameter `tx` from node to runtime of validate_transaction`)
https://github.com/UniqueNetwork/unique-chain/blob/feature/pallet-structure-rebased/primitives/data-structs/src/lib.rs#L385-L387

If code is explicitly migrated to OptionBool - then everything works fine

Incompatibility between polkadot.js and parity-scale-codec can be checked manually:
```javascript
// polkadot.js
console.log(api.registry.createType('Option<bool>', true).toU8a());
console.log(api.registry.createType('Option<bool>', false).toU8a());
console.log(api.registry.createType('Option<bool>', null).toU8a());
/*
Uint8Array(1) [ 1 ]
Uint8Array(1) [ 2 ]
Uint8Array(1) [ 0 ]
*/
```

```rust
// parity-scale-codec
None::<bool>.encode() == [0]
Some(true).encode() == [1, 1]
Some(false).encode() == [1, 0]

// And using opt-in OptionBool specialization
OptionBool(None::<bool>).encode() == [0]
OptionBool(Some(true)).encode() == [1]
OptionBool(Some(false)).encode() == [2]
```

**Comment by jacogr** [comment]
Perfect, thanks for the specific link. Will get a patch out.
