### ISSUE TITLE
Question: Custom types, getting the real toHuman types

### ISSUE THREAD

**Issue by Yuripetusko** [polkadot-js/api#4912]
quering api with custom types passed, the return type is correct until I do toHuman. Is there any way to get the humanised types/interfaces somehow? It is fine until I do toHuman() or toJSON() but after that, I just see `AnyJson` and all the props of the interface are lost. 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/666169/172655058-9f94fd93-2890-4c09-833a-b63e93929db4.png">

**Comment by jacogr** [comment]
`toHuman()` doesn't have any specific type interfaces. It is only typed since it needs to have "something", but since it is never for programatic use, rather only something that makes display "pretty", the typing is intentionally loose.

`toJSON` is similar - it is only meant to encode for transfer over JSONRPC, so formats with that in mind so it can be serialized immediately.

**Comment by Yuripetusko** [comment]
Ok I'll give a real-world example. Let's say our API query returns an object with all the lookup-related helpful methods and Codec related props and methods. It's useful but for example if I want to save it in global react state it's not very practical, so what I do most of the time is I do toHuman or toJson, and then do `parseInt` on those fields that are now strings as a result of `toHuman`. And I lose types this way, so I have to do type casting by defining my own interfaces now, and if API changes I have to maintain my interfaces to be synced with the ones coming from custom chain types.

I don't know if there's a better way to do this? to get rid of all the Codec related stuff and for example turn u32 into an integer and Bytes into a string etc as these types are not useful once I got what I need from the API and want to pass it around the client-side app

**Comment by jacogr** [comment]
So, yes, once `toHuman()` you have lost the types that have been applied. For those operations, the struct itself doesn't know what the [child-entries are or represent themselves](https://github.com/polkadot-js/api/blob/322ac0861de8a4fd039cacc7bdc08eb07b48ec7b/packages/types-codec/src/native/Struct.ts#L270-L278).

For `Bytes`, just call `toString()` on it, for any number-related, call `toNumber()/toString()` on it.
