### ISSUE TITLE
Get status of block with hash

### ISSUE THREAD

**Issue by A2DNEW** [polkadot-js/api#4914]
Hi,
How can I get block status (Finalized) with hash?
I get hash with this code:

`const txHash = await api.tx.balances.transfer(address, amount).signAndSend(pair);
`
Thanks

**Comment by jacogr** [comment]
Refer to SO for the general HOWTO questions - this is actually answered [there](https://substrate.stackexchange.com/questions/2760/get-transaction-by-hash). There is even a [FAQ entry](https://polkadot.js.org/docs/api/FAQ#which-api-can-i-use-to-query-by-transaction-hash) in the API docs that covers this.

**Comment by A2DNEW** [comment]
> Refer to SO for the general HOWTO questions - this is actually answered [there](https://substrate.stackexchange.com/questions/2760/get-transaction-by-hash). There is even a [FAQ entry](https://polkadot.js.org/docs/api/FAQ#which-api-can-i-use-to-query-by-transaction-hash) in the API docs that covers this. (As well as numerous old issues with the same question here)

Thank you for your reply
I am a newbie
Can you help me more?
I want to get status of hash like this url:

https://westend.subscan.io/extrinsic/0x5594d29df6618fc4030133dc10c8b04d1e127d78ff750ebe32eeb555e98dce79

I have `0x5594d29df6618fc4030133dc10c8b04d1e127d78ff750ebe32eeb555e98dce79` hash, and I want to get status (InBlock and Finalized)

I try this code:

```
const unsub = await api.tx.balances
    .transfer(address, price)
    .signAndSend(newPair, ({ status, txHash }: any) => {
      console.log(`Current status is ${status.type}`);

      txHash = txHash.toHex()

      if (status.isFinalized) {
        console.log(`Transaction included at blockHash ${status.asFinalized}`);
        console.log(`Transaction hash ${txHash.toHex()}`);
      }
    });
```

But not good for me.
Because I want to check hash in another function.

**Comment by jacogr** [comment]
As per the SO links and the FAQ entry, you cannot go from transaction hash to blockHash, there is no substrate RPC for this (non-unique) hash mapping. (Reasoning in the SO posts)

**Comment by A2DNEW** [comment]
> This is exactly what the links I provided address. As per the SO links and the FAQ entry, you cannot go from transaction hash to blockHash. (Reasoning in the SO post and FAQ links provided)

@jacogr 
Thank you again
So, What is the solution?
Can you help me more with codes?
Thanks
