### ISSUE TITLE
[Bug] Unable to decode storage system.events

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#4936]
### Enviornment

- `@polkadot/api: 8.8.1`
- `node.js: 16.15.1`

### Bug Report

When querying block `7944249` on kusama using `<apiAt>.query.system.events()` results in the following error:
```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec<EventRecord>:: Decoded input doesn't match input, received 0x1800000000000000480e0d0b0000000002000000010000003501e8030000edcf…000000000000000000000000020000000001030401089ed50b00000000000000 (666 bytes), created 0x1800000000000000480e0d0b0000000002000000010000003501e8030000edcf…000000000000000000020000000001030401089ed50b00000000000000000000 (669 bytes)
Error: Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec<EventRecord>:: Decoded input doesn't match input, received 0x1800000000000000480e0d0b0000000002000000010000003501e8030000edcf…000000000000000000000000020000000001030401089ed50b00000000000000 (666 bytes), created 0x1800000000000000480e0d0b0000000002000000010000003501e8030000edcf…000000000000000000020000000001030401089ed50b00000000000000000000 (669 bytes)
```

### Reproducible Code

```typescript
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://kusama-rpc.polkadot.io'),
    });

    // Block 7944249
    const apiAt = await api.at('0x8e86dcf9d455085ce99646166dd09e38306c9a3f1007cbeafc72a775dc74abbb');

    await apiAt.query.system.events();
};

main().catch(err => console.log(err)).finally(() => process.exit());
```

I also tested it against `8.7.1` and there was no issue.

**Comment by TarikGul** [comment]
Extra Info:

Given `8.7.2-0` following commit [f96b9c6](https://github.com/polkadot-js/api/commit/f96b9c6d19d4b28e4c264614ce2f825b120e9210) I was not able to reproduce the above error, and everything worked fine. 

But given `8.7.2-1` following commit [56a3d4e](https://github.com/polkadot-js/api/commit/56a3d4ece85de039989719f2114c0a9b674042ae) the error started to surface. Given the commit itself I am not totally sure how the decoding error arises though.

**Comment by jacogr** [comment]
For the ancient blocks, there needs to be an explicit set for these types now, e.g. `DispatchError: DispatchErrorU8` (in historic types)

**Comment by TarikGul** [comment]
Thanks for the quick resolve! Read over the PR, and it all makes sense. Very much appreciated!

**Comment by jacogr** [comment]
https://github.com/polkadot-js/api/releases/tag/v8.8.2

**Comment by TarikGul** [comment]
Ahh interesting, so even with the transition to V14 standardization there are exceptions such as Contracts (Due to its reliance on RPC's, that being said i guess all RPC's are actually the exception). Really good to know, thanks. 

And no worries at all, we have e2e tests for all historical runtimes on kusama, polkadot, and westend that we test each week for the new stable p-js releases. The hope being we would catch any/some of those nits that slip through (Which is very rare to say the least)  :).
