### ISSUE TITLE
How to include custom RPC in polkadotjs (+types)

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#4954]
When generating the api-augment with typegen, the additional RPC methods are not included. 
Additionally those rpc_method are not recognized when polkadotjs connect to the network and load the types.
```
API/INIT: RPC methods not decorated: eth_feeHistory, eth_maxPriorityFeePerGas, moon_isBlockFinalized, moon_isTxFinalized
```

Ex: using `npm install @moonbeam-network/api-augment@0.1605.3`

```
import "@moonbeam-network/api-augment";
import { ApiPromise, WsProvider } from "@polkadot/api";

const main = async () => {
  const api = await ApiPromise.create({
    provider: new WsProvider("wss://wss.api.moonbase.moonbeam.network"),
  });
  await api.isReady;

  const blockHash = `0x0bbeb2c7b5e7c3e960efd54029404fa2ec4288ff1e1ae6d2b149793a7b0a0226`;
  console.log(`${blockHash} finalized?: ${api.rpc.moon.isBlockFinalized(blockHash)}`);
};

main();
```
This will fail to compile (because of missing `moon`) and fail to execute because moon is not decorated in the api object.

**Comment by jacogr** [comment]
https://polkadot.js.org/docs/api/start/rpc.custom

**Comment by crystalin** [comment]
Thank you @jacogr , I'm testing it.
Do you know for the api-augment part ?

**Comment by jacogr** [comment]
Assuming you have the RPCs in your definitions when building the types, it should create augmented types for those as well. Basically it should create a `augment-api-rpc.ts` file. (This is based on the `rpc` key in the supplied edfinitions)

**Comment by crystalin** [comment]
I thought those were taken automatically from the rpc nodes

**Comment by jacogr** [comment]
There is no way it can be - the nodes only expose the names of the methods, no parameters whatsoever. (See the `api.rpx.rpc.methods` call)

**Comment by crystalin** [comment]
Interesting, that would definitely be valuable to include the types in there.

**Comment by crystalin** [comment]
I tried adding `rpc` to the `interfaces/moon/definitions.ts` (and including it in the index.ts) but it doesn't include it in the `augment-api-rpc.ts` ( see https://github.com/PureStake/moonbeam/pull/1613/files#diff-17f80788bf6f510b72f3d2b75c0d9fefe6ba3044235385f6732ce69be7f58316R1)
Do you see what I did wrong ?

**Comment by jacogr** [comment]
Ummm... will checkout that branch and run it, it certainly looks correct.

**Comment by crystalin** [comment]
@jacogr Were you able to find some information? Otherwise I'll try to dig into the typegen.

**Comment by jacogr** [comment]
Have it on the list.

**Comment by jacogr** [comment]
Add the `--package @moonbeam/api-augment/moonbeam/interfaces` parameter.

```
"generate:meta:moonbase": "ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --endpoint ./metadata-moonbase.json --package @moonbeam/api-augment/moonbeam/interfaces --output ./src/moonbase/interfaces",
    "generate:meta:moonriver": "ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --endpoint ./metadata-moonriver.json --package @moonbeam/api-augment/moonbeam/interfaces --output ./src/moonriver/interfaces",
    "generate:meta:moonbeam": "ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --endpoint ./metadata-moonbeam.json --package @moonbeam/api-augment/moonbeam/interfaces --output ./src/moonbeam/interfaces",
 ```
 
This added the `moon` endpoints for me on your branch.

**Comment by crystalin** [comment]
Thank you @jacogr it worked as expected :)
