### ISSUE TITLE
Remove useless cleaning in Type.ts

### ISSUE THREAD

**Issue by amaurymartiny** [polkadot-js/api#496]
This got merged: https://github.com/paritytech/substrate/pull/1298, we were doing the same stuff on our side.

**Comment by jacogr** [comment]
Yes, hold off on this until the fixes made it back to Charred Cherry, i.e. 0.9.0 branch - it is not great, but does provide some assurance as well.

**Comment by jacogr** [comment]
Now we can do this, changes are in CC.

**Comment by jacogr** [comment]
Won't be needed after https://github.com/polkadot-js/api/pull/678 - basically no string parsing. Closing, we can live with the extra duplication until then.
