### ISSUE TITLE
How to add a tip to an transaction with API, such as to api.tx.balances.transfer 

### ISSUE THREAD

**Issue by SixoneKui** [polkadot-js/api#4982]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [*] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [*] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments available)

  - Language:

    - [*] JavaScript
    - [ ] TypeScript
    - [ ] Other

**Comment by btwiuse** [comment]
You can use this for add a tip

```
...
const tip = new BN('100000000', 10);
await api.tx.balances
      .transfer(to, amount)
      .signAndSend(from, { tip })
```
