### ISSUE TITLE
How can I listen to new receive transfer?

### ISSUE THREAD

**Issue by A2DNEW** [polkadot-js/api#4988]
Hi
I want to listen to new transfers and get the hash and amount.
How can I?
Also, Can I get list transfers of account like this url?
https://westend.subscan.io/account/5D8JvKv1yL8ZPN9xxNbQiRxX14KvpiP8UJcDys1ouDnKpczx
Thank you

**Comment by jacogr** [comment]
Please refer HOWTO questions to SO. (As per the new issue links)

**Comment by jacogr** [comment]
Closing, answered on SO.
