### ISSUE TITLE
[Feature Request] Http-2 Support

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#4991]
**I'm submitting a Feature request**

**What is the current behavior and expected behavior?**
Currently polkadotjs uses node-fetch which doesn't support http-2 protocol, but substrate's http server does support http2.

**What is the motivation for changing the behavior?**
Http2 will be more efficient regards resources usage for both client and server side.

I've found a project that seems can do the job. https://github.com/grantila/fetch-h2

**Comment by jacogr** [comment]
If the new [Node fetch](https://fusebit.io/blog/node-fetch/?utm_source=duckduckgo.com&utm_medium=referral&utm_campaign=none) does support HTTP2, swapping to a version of Node that supports it will just work. (node-fetch is just used as a fallback when `fetch` is not in the global scope)

**Comment by jacogr** [comment]
Closing, answered - it is actually native to Node now. (with short-term work-around for cases where you don't want to update yet)
