### ISSUE TITLE
Is it possible to get rid of side effects when evaluating `api.tx` etc?

### ISSUE THREAD

**Issue by btwiuse** [polkadot-js/api#4994]
* **I'm submitting a**
  - Other

* **What is the current behavior and expected behavior?**

Tab completion is not working in some circumstances. 

Pressing tab(s) on the input `api.tx.` shows nothing:
```
$ deno repl --eval-file=https://deno.land/x/subshell@0.0.2/tini.ts
api is initializing. Please hold on...
Deno 1.23.1
exit using ctrl+d or close()
> api.tx.
```
Same is true for `api.query.`, `api.consts.`, `api.rpc.`, etc.

Expected tab completion to work without patching Deno

```
> api.tx.
system                      session                     claims                      electionProviderMultiPhase  ump                         name                        __defineSetter__
scheduler                   grandpa                     vesting                     voterList                   hrmp                        arguments                   hasOwnProperty
preimage                    imOnline                    utility                     configuration               parasDisputes               caller                      __lookupGetter__
babe                        democracy                   identity                    parasShared                 registrar                   constructor                 __lookupSetter__
timestamp                   council                     proxy                       paraInclusion               slots                       apply                       isPrototypeOf
indices                     technicalCommittee          multisig                    paraInherent                auctions                    bind                        propertyIsEnumerable
balances                    phragmenElection            bounties                    paras                       crowdloan                   call                        valueOf
authorship                  technicalMembership         childBounties               initializer                 xcmPallet                   toString                    toLocaleString
staking
```

* **What is the motivation for changing the behavior?**

To improve the dev experience of using https://deno.land/x/polkadot in Deno repl.

* **Please tell us about your environment:**

  - Version: deno.land/x/polkadot@0.0.1
  - Environment:
    - Other: Deno 1.23.1

  - Language:
    - TypeScript

Related: https://github.com/denoland/deno/issues/14967

Adding `--v8-flags=--trace-side-effect-free-debug-evaluate` shows that evaluating `api.tx` failed side effect check.
```
$ deno repl --v8-flags=--trace-side-effect-free-debug-evaluate --eval-file=https://deno.land/x/subshell@0.0.2/tini.ts
api is initializing. Please hold on...
Deno 1.23.1
exit using ctrl+d or close()
> api.tx.[debug-evaluate] Checking function  for side effect.
0x11230843cac1 <BytecodeArray[10]>[debug-evaluate] Checking function get tx for side effect.
0x11230843cb95 <BytecodeArray[13]>[debug-evaluate] Checking function assertResult for side effect.
0x11230843cc79 <BytecodeArray[15]>[debug-evaluate] bytecode LdaModuleVariable may cause side effect.
[debug-evaluate] Function assertResult failed side effect check.
[debug-evaluate] Function assertResult failed side effect check.
```

Deno repl skips tab completion for expressions evaluated with side effects: https://github.com/denoland/deno/blob/8d82ba729937baf83011354242cabc3d50c13dc2/cli/tools/repl/editor.rs#L132

I searched for similar problems in Deno's issue history, and it seems no one encountered the same tab completion problem before. 

My question: why evaluating api.tx introduces side effect and is it possible to get rid of it?

I understand that deno.land/x/polkadot is experimental, and Deno is not currently a supported target, but still would like to play with it more. Feel free to close this if it's off topic. 

Thanks.

**Comment by jacogr** [comment]
No idea, but actually saw that issue you logged, aka works in Node doesn't quite work in Deno.

If I had to take a guess... It is quite possibly due to the fact that `api.{query, events, errors, tx, runtime ...}.*` are all lazily decorated. The methods are decorated by adding getters on the object, see for instance [the decoration on tx](https://github.com/polkadot-js/api/blob/f5e89b75309d0abac809647efeddf478c4036ad9/packages/api/src/base/Decorate.ts#L588-L590) (the others operate the same).

However... looking at your log, it seems due to the [use of assertResult](https://github.com/polkadot-js/api/blob/f5e89b75309d0abac809647efeddf478c4036ad9/packages/api/src/base/Getters.ts#L227-L229) - not 100% sure these are all needed anymore (it _used_ to), I actually saw that earlier this week and for most of these I do believe the object would never be null or undefined. 

So if you are in the mood for a small PR - would suggest just dropping all of these in `Getters.ts` and re-add if TS does complain about one/two.

**Comment by btwiuse** [comment]
Thanks, I'll give it a shot.

BTW how are the files in https://github.com/polkadot-js/build-deno.land generated?

I'd like to first test it locally before submitting a PR.

**Comment by btwiuse** [comment]
I think I've found something interesting.

If we define `assertReturn` locally instead of importing it from another module, v8 would think that the getter has no side effect.

Experiment:

Create three files under current directory (bash)

```bash
cat <<EOF >is.ts
export function isUndefined(value?: unknown): value is undefined {
  return typeof value === "undefined";
}

export function isFunction(value: unknown): value is Function {
  return typeof value === "function";
}
EOF

cat <<EOF >module.ts
import { isFunction, isUndefined } from "./is.ts";

export function assertReturnModule<T>(
  value: T | undefined,
  message: string | (() => string),
): T {
  if (isUndefined(value)) {
    throw new Error(
      isFunction(message) ? message() : message,
    );
  }
  return value;
}
EOF

cat <<EOF >init.ts
import { isFunction, isUndefined } from "./is.ts";
import { assertReturnModule } from "./module.ts";

export function assertReturnLocal<T>(
  value: T | undefined,
  message: string | (() => string),
): T {
  if (isUndefined(value)) {
    throw new Error(
      isFunction(message) ? message() : message,
    );
  }
  return value;
}

class Getter {
  public name: string | undefined;
  constructor(name?: string) {
    this.name = name;
  }
  public get M(): string {
    return assertReturnModule(this.name, "name cannot be null");
  }
  public get L(): string {
    return assertReturnLocal(this.name, "name cannot be null");
  }
}

let G = new Getter("v8 getter side effect check");
EOF
```

Then start deno repl with the following flags
```
$ deno repl --v8-flags=--trace-side-effect-free-debug-evaluate --eval-file=init.ts
Deno 1.23.1
exit using ctrl+d or close()
```

`G.M` failed side effect check
```
> G.M.[debug-evaluate] Checking function  for side effect.
0x3b67003ae8e9 <BytecodeArray[10]>[debug-evaluate] Checking function get M for side effect.
0x3b67003ae9e5 <BytecodeArray[18]>[debug-evaluate] Checking function assertReturnModule for side effect.
0x3b67003aea89 <BytecodeArray[47]>[debug-evaluate] bytecode LdaModuleVariable may cause side effect.
[debug-evaluate] Function assertReturnModule failed side effect check.
[debug-evaluate] Function assertReturnModule failed side effect check.
```

`G.L` passed.
```
> G.L.[debug-evaluate] Checking function  for side effect.
0x3b67003af019 <BytecodeArray[10]>[debug-evaluate] Checking function get L for side effect.
0x3b67003af0f5 <BytecodeArray[18]>[debug-evaluate] Checking function assertReturnLocal for side effect.
0x3b67003af199 <BytecodeArray[43]>[debug-evaluate] Checking function isUndefined for side effect.
0x3b67003af24d <BytecodeArray[5]>[debug-evaluate] Checking function  for side effect.

length                charAt                fixed                 match                 replaceAll            substr                trimLeft              valueOf               propertyIsEnumerable
constructor           charCodeAt            includes              matchAll              search                substring             trimEnd               __defineGetter__      toLocaleString
anchor                codePointAt           indexOf               normalize             slice                 sup                   trimRight             __defineSetter__
at                    concat                italics               padEnd                small                 startsWith            toLocaleLowerCase     hasOwnProperty
big                   endsWith              lastIndexOf           padStart              split                 toString              toLocaleUpperCase     __lookupGetter__
blink                 fontcolor             link                  repeat                strike                trim                  toLowerCase           __lookupSetter__
bold                  fontsize              localeCompare         replace               sub                   trimStart             toUpperCase           isPrototypeOf
> G.L.
```

**Comment by jacogr** [comment]
Do you need a version published to Deno? (If you can wait a day or two, it will happen Saturday/Sunday with a new published API - if absolutely urgent, can do one manually)

**Comment by btwiuse** [comment]
> Do you need a version published to Deno? (If you can wait a day or two, it will happen Saturday/Sunday with a new published API - if absolutely urgent, can do one manually)

Absolutely not urgent, but I'd like to see it land asap if that's ok. 

![SoExcited~GIF](https://user-images.githubusercontent.com/54848194/176904242-e9278147-4260-469e-a533-b86f53360b0d.gif)

I'm too excited to wait :)

**Comment by jacogr** [comment]
https://github.com/polkadot-js/build-deno.land/releases/tag/0.0.2
