### ISSUE TITLE
How to support custom api-augment through relative path

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#5004]
I've been trying to include our `@moonbeam-network/api-augment` locally (to allow testing the changes without publishing), however I can't find a way to make it work :(

I tried replacing 
```
"@moonbeam-network/api-augment": "^0.1605.3",
```
by 
```
"@moonbeam-network/api-augment": "file:../typescript-api/build",
```

you can test it on moonbeam:
```
git clone -b crystalin-fail-augment https://github.com/purestake/moonbeam
cd moonbeam
git checkout 

cd test-augment
npm ci
npm run build

> test-augment@1.0.0 build
> tsc

index.ts:11:21 - error TS2339: Property 'current' does not exist on type 'Codec'.

11   console.log(round.current.toNumber());
                       ~~~~~~~

Found 1 error in index.ts:11
```

(If I replace the `@moonbeam-network/api-augment` from the npm registry, it works fine)

**Comment by jacogr** [comment]
Clueless. You may try these options -

```js
"@moonbeam-network/api-augment": "workspace:typescript-api/build",
```

The above is something I found in the API repo.

Alternatively, add it to your tsconfig paths -

```
"@moonbeam-network/api-augment": ["typescript-api/build"],
```

No other ideas apart from those 2.

**Comment by crystalin** [comment]
Thank you @jacogr 
Using
```
    "paths": {
      "@moonbeam-network/api-augment": ["../../typescript-api/build"]
    }
```
works, but only partially. All the imports are good like:
```
import type { ParachainStakingCandidateBondLessRequest } from "@polkadot/types/lookup";
```
but the ApiPromise is not decorated properly:
```
await context.polkadotApi.query.assetManager.assetIdType(assetId)
```
This would return a Codec.

So the module resolution is working well, but the augment is not happening :/

**Comment by jacogr** [comment]
I am assuming you did include `import '@moonbeam-network/api-augment';` top-level in the script you are testing? (This allows the augmentation to kick in)

**Comment by crystalin** [comment]
Yes, I also tried to reset the `"@moonbeam-network/api-augment": "^0.1605.3",` and copy the build folder after doing the `npm install`:
```
rm -rf node_modules/@moonbeam-network/api-augment
cp -r ../typescript-api/build  node_modules/@moonbeam-network/api-augment
```
it works totally fine :(
