### ISSUE TITLE
Deno + VSCode type augmentation missing

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#5019]
It would seem that TS type augmentation is not working for Deno projects.

![image](https://user-images.githubusercontent.com/1424473/177030373-8679759e-caa0-4635-9920-937e8502d0b1.png)

CC @btwiuse - the reason why I'm pinging you is that I just want a sanity check that it is not due to some local config for me.

No quite sure what to do about this as of yet, if indeed an issue.

**Comment by jacogr** [comment]
Running `deno check mod.ts` has error such as -

`TS2671 [ERROR]: Cannot augment module 'https://deno.land/x/polkadot@0.0.2/rpc-core/types/jsonrpc.ts' because it resolves to a non-module entity.`

So there is certainly "some" issues, "somewhere"

**Comment by jacogr** [comment]
There is something here. A simple local-only test -

```js
// foo.ts
export interface Foo {
	z: 1
}
```

```js
// aug.ts
declare module './foo.ts' {
	export interface Foo {
		a: {
			b: {
				c: 1
			}
		}
	}
}
```

```js
// test.ts
import './aug.ts';

import type { Foo } from './foo.ts'

export function testAugment (foo: Foo): void {
	console.log(foo.z + 1);
	console.log(foo.a.b.c + 1);
	// ^^^ complains here about foo.a not found
}
```

**Comment by btwiuse** [comment]
Never tried Deno + VSCode before, and not sure what the expected behavior should be like.

I'll take a look to see if this issue is reproducible for me.

**Comment by jacogr** [comment]
All good. There is certainly an issue (but it could be caused by a number of other issues that `deno check` reports on, so at least try to clear all the basics before trying to see what is up - however, cannot get any type augmentation working in Deno, polkadot-js or otherwise, so there is also that ...)

**Comment by btwiuse** [comment]
I tried https://github.com/polkadot-js/build-deno.land/ in GitHub Codespaces with Deno extension installed.

It doesn't work for me either.

The most obvious error I noticed is that when you open any of ./api-augment/{kusama,polkadot,substrate}/{consts,errors,events,query,tx}.ts in the editor, you will see something like

![image](https://user-images.githubusercontent.com/54848194/177208205-ca89d28f-e15f-4410-beed-e3a9c8671579.png)

That probably means augmentations for the module 'https://deno.land/x/polkadot@0.0.3/types/lookup.ts' did not kick in.

**Comment by btwiuse** [comment]
`deno check` currently produces [over 3000 errors](https://bafybeihqq3rulo5kxm3ly6k6nb27pwgbyj4ntnumzwyvkmp6r3un4b5a5u.ipfs.dweb.link).

```
$ deno check --unstable -q mod.ts |& npx -y strip-ansi-cli | tee deno-check.txt | grep '^TS' | sort -h | uniq -c | sort -h | tail
     37 TS2304 [ERROR]: Cannot find name 'AugmentedCall'.
     47 TS2304 [ERROR]: Cannot find name 'SubmittableExtrinsicFunction'.
    110 TS2339 [ERROR]: Property 'createType' does not exist on type 'Registry'.
    162 TS2304 [ERROR]: Cannot find name 'AugmentedConst'.
    290 TS2304 [ERROR]: Cannot find name 'AugmentedQuery'.
    340 TS2304 [ERROR]: Cannot find name 'QueryableStorageEntry'.
    352 TS2304 [ERROR]: Cannot find name 'AugmentedEvent'.
    352 TS2304 [ERROR]: Cannot find name 'AugmentedSubmittable'.
    352 TS2304 [ERROR]: Cannot find name 'SubmittableExtrinsic'.
    507 TS2304 [ERROR]: Cannot find name 'AugmentedError'.
```

 TS2304 is the most common one, usually seen in files with the header 
```
// Auto-generated via `yarn polkadot-types-from-chain`, do not edit
```
Here is the list of all errors sorted by number of occurrence
```
$ curl -sL https://github.com/microsoft/TypeScript/raw/v4.7.3/src/compiler/diagnosticMessages.json | jq -r 'to_entries[]|"s/TS\(.value.code)/TS\(.value.code): \(.key)/g"' > /tmp/mapping.sed
$  cat deno-check.txt | grep ^TS | cut -d ' ' -f 1 | sort | uniq -c | sort -h | sed -f /tmp/mapping.sed
      1 TS2488: Type '{0}' must have a '[Symbol.iterator]()' method that returns an iterator.
      1 TS4112: This member cannot have an 'override' modifier because its containing class '{0}' does not extend another class.
      2 TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
      2 TS2532: Object is possibly 'undefined'.
      2 TS2740: Type '{0}' is missing the following properties from type '{1}': {2}, and {3} more.
      2 TS7053: Element implicitly has an 'any' type because expression of type '{0}' can't be used to index type '{1}'.
      3 TS2365: Operator '{0}' cannot be applied to types '{1}' and '{2}'.
      3 TS2420: Class '{0}' incorrectly implements interface '{1}'.
      4 TS2531: Object is possibly 'null'.
      4 TS2580: Cannot find name '{0}'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
      7 TS2493: Tuple type '{0}' of length '{1}' has no element at index '{2}'.
     11 TS2308: Module {0} has already exported a member named '{1}'. Consider explicitly re-exporting to resolve the ambiguity.
     13 TS2571: Object is of type 'unknown'.
     13 TS2671: Cannot augment module '{0}' because it resolves to a non-module entity.
     15 TS7006: Parameter '{0}' implicitly has an '{1}' type.
     17 TS7031: Binding element '{0}' implicitly has an '{1}' type.
     40 TS2322: Type '{0}' is not assignable to type '{1}'.
     42 TS2345: Argument of type '{0}' is not assignable to parameter of type '{1}'.
    234 TS2305: Module '{0}' has no exported member '{1}'.
    273 TS2339: Property '{0}' does not exist on type '{1}'.
   2485 TS2304: Cannot find name '{0}'.
```

I think we can fix most of them by adjusting the codegen scripts.

Currently the output of `deno check` is too noisy to be helpful.

**Comment by jacogr** [comment]
Down to 706 - most (all?) of the stuff left are augmentation issues.

**Comment by jacogr** [comment]
This all works as expected now -

```js
import 'https://deno.land/x/polkadot@0.0.4/api-augment/mod.ts';

import { ApiPromise, WsProvider } from 'https://deno.land/x/polkadot@0.0.4/api/mod.ts';
import { BN_ONE, stringToU8a } from 'https://deno.land/x/polkadot@0.0.4/util/mod.ts';
import { blake2AsHex } from 'https://deno.land/x/polkadot@0.0.4/util-crypto/mod.ts';

async function main () {
	console.log('*** util');
	console.log(stringToU8a('hello world'), BN_ONE.toString());

	console.log('util-crypto');
	console.log(blake2AsHex('hello world'));

	const api = await ApiPromise.create({ provider: new WsProvider() });

	api.rpc.chain.subscribeNewHeads(({ hash }) => console.log(hash.toHex()));

	const acc = await api.query.system.account('');

	console.log(acc.consumers.toNumber());
}

main().catch(console.error);
```

With in-editor augmentation/help.

Still unsure why there is a discrepancy between Node TS augmentation and Deno TS augmentation, however the applied fixes are all happy in the Node environment, so possibly it was just more forgiving in the past and there were underlying issues in the way it was done.
