### ISSUE TITLE
API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageEntryTypeLatest):: Invalid character

### ISSUE THREAD

**Issue by coder-chenda** [polkadot-js/api#5023]
x
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/83049018/177124317-3ba63ae7-1249-446e-b9be-e4b34519dd68.png">

**Comment by jacogr** [comment]
Please log the versions of the queries as per the template - and if not current, first reproduce on the latest released version.

**Comment by coder-chenda** [comment]
> Please log the versions of the queries as per the issue template - and if not on current, first reproduce on the latest released version.
> 
> The above version seems very outdated, the `beefy_*` methods have been in the API since at least [7.7.1](https://github.com/polkadot-js/api/releases/tag/v7.7.1) the `mmr_*` methods have been in since [8.5.1](https://github.com/polkadot-js/api/releases/tag/v8.5.1).
> 
> We cannot support old versions, since (a) anything that is in there cannot be fixed (unless it happens on latest as well) & (b) we only test against latest and can only code against latest. (It is quite possible that old versions have issues since fixes and changes go in daily, so old !== new)

{
  "name": "polkadot",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "scripts": {
    "serve:polkadot": "ts-node src/index.ts https://rpc.polkadot.io        127.0.0.1 9990",
    "serve:kusama": "ts-node src/index.ts https://kusama-rpc.polkadot.io 127.0.0.1 9991"
  },
  "devDependencies": {
    "@polkadot/api": "^6.12.1",
    "@types/node": "^16.7.2",
    "ts-node": "^10.2.1",
    "typescript": "^4.4.2"
  }
}

I want to ask which version is needed?

**Comment by jacogr** [comment]
`6.12.1` was released on [13 Dec 2021](https://github.com/polkadot-js/api/releases/tag/v6.12.1) the current latest version is [8.11.2](https://github.com/polkadot-js/api/releases/tag/v8.11.2)

There has been a massive amount of fixed in the last 6 months, what was true in December 2021 is not not true in July 2022.

**Comment by jacogr** [comment]
Closing, not on latest API.
