### ISSUE TITLE
Kusama block 492360 events can not be decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5028]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/492360

Kusama block 492360 events can not be decoded.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: 8.11.2
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments available)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript
    - [ ] Other

**Comment by jacogr** [comment]
Seems like the old `ExtrinsicFailed` type

**Comment by wliyongfeng** [comment]
It will be perfect if we can create some test cases for these old types, but I know it will be a tough work. :)

**Comment by jacogr** [comment]
PRs very welcome to add additional tests. There are some, specifically around events and old versions, but in all of these cases it means that you need to know at which point the runtime changed.
