### ISSUE TITLE
Optional extrinsic parameters

### ISSUE THREAD

**Issue by MrShiposha** [polkadot-js/api#5045]
It would be great to have the possibility to make the last arguments of an extrinsic optional in generated types.
It could help to achieve backward compatibility when adding new params that are optional for the extrinsic.

For instance we have the following extrinsic:
```rust
#[weight = /* ... */]
pub fn do_some_stuff(
    origin,
    collection_id: CollectionId,
    token: TokenId
);
```

Then We can add some additional parameter that affects the logic of the extrinsic but yet it is optional.

```rust
#[weight = /* ... */]
pub fn do_some_stuff(
    origin,
    collection_id: CollectionId,
    token: TokenId,
    extra_info: Option<SomeInfoStruct>
);
```

Now the generated code will look something like this:
```typescript
doSomeStuff: AugmentedSubmittable<(collectionId: u32, token: u32, extra_info: Option<SomeInfoStruct> | null)>
```

It would be great to have the possibility to make the last parameter `extra_info` optional in TS: `extra_info?: SomeInfoStruct`.
So the existing JS/TS code could use the old version of the extrinsic even if there is additional optional parameter.

**Comment by jacogr** [comment]
All this info, at runtime, it as per the on-chain metadata. It is not based on TS definitions. 

The API encodes as the runtime requires - the decoration happens after the metadata is retrieved from the chain.
