### ISSUE TITLE
tx subs do not return status.isFinalized

### ISSUE THREAD

**Issue by timbrinded** [polkadot-js/api#5054]
## Description
Whilst attempting to automate some extrinsics, I use a function to sign and send a transaction and then subscribe to events. This is so I can wait until I can confirm it is in a finalized block as per (Transaction Subscriptions)[https://polkadot.js.org/docs/api/start/api.tx.subs/] in the docs.

However it is a commmon occurance for me that these can hang, whereby `status.isFinalized` never turns true, despite them being included in finalized blocks (confirmed via block explorer in polka.js). 

## Code
```
 export const submitTx = async (tx, signer) => {
  let details
  console.log('Txns built. Waiting...')
  let promise = new Promise(async (resolve, reject) => {
    const unsub = await tx.signAndSend(
      signer,
      { nonce: -1 },
      ({ events = [], status }) => {
        if (status.isInBlock)
          console.log(
            `Txns in unfinalized block: ${status.asInBlock} waiting...`
          )
        if (status.isDropped) {
          unsub()
          reject('Block has been dropped!')
        }
        if (status.isFinalized) {
          unsub()
          resolve({ events, hash: status.asFinalized })
        }
      }
    )
  })

  await promise
    .then((message) => {
      details = message
    })
    .catch((message) => {
      throw new Error('Sending transaction failed.')
    })

  return details
}
```

**Comment by jacogr** [comment]
The subscription only returns what the RPC returns, i.e. it doesn't "bail out early". See https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L248-L276

Tested this against the apps UI as well (which _does_ bail on `InBlock`) by not unsubscribing at all when `inBlock` is reached and with that change, in all cases, always get `Broadcast`, `Ready`, `InBlock` and `Finalized`.

**Comment by timbrinded** [comment]
@jacogr thanks for the snippets and explanation.

Are you saying that it's the RPC responsible for the status not updating then? This isn't a one off thing, i regularly encounter this issue on my scripts despite always benchmarking for the most performant wss endpoint.
