### ISSUE TITLE
Question: identifying pallets in a runtime

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/api#5055]
The challenge at hand is t identify if `pallet-balances` is in a runtime or not. My elementary way of solving this problem is testing something like `api.query.balances !== undefined`.

This works in 99% of the cases, but it is fundamentally flawed, as it depends on the name given to pallet-balances by `contruct_runtime!`.

Question is: is there a better, safer way to do this? I see efforts in substrate that expose the crate name in a Rust context. Seems like all we have to do is to expose the same thing over metadata. See: https://github.com/paritytech/substrate/pull/10053

**Comment by kianenigma** [comment]
example from `derive.balances.all` seems be quite close to what I want, but I am afraid it is itself outdated. If you try any of 

```rust
console.log(api.registry.getModuleInstances(api.runtimeVersion.specName.toString(), "Balances"))
console.log(api.registry.getModuleInstances(api.runtimeVersion.specName.toString(), "balances"))
console.log(api.registry.getModuleInstances(api.runtimeVersion.specName.toString(), "system"))
```

they are return `undefined`.

**Comment by jacogr** [comment]
It is as-used. And yes, that return value would be correct. It would return an array of the different instances if anything is found, alternatively `undefined` when no overrides are present. 

This means the caller needs to apply their own defaults, e.g. in the case you mentioned it applies `['balances']` when nothing is found - https://github.com/polkadot-js/api/blob/12750bc83d8d7f01957896a80a7ba948ba3690b7/packages/api-derive/src/balances/all.ts#L153

**Comment by kianenigma** [comment]
So `getModuleInstances` only returns something other than `undefined` if there has been overrides? 

If such, the general question is still open. 

I haven't inspected the metadata exactly, but each pallet should ideally return both an instance name, and something more meta like "module name", so that the api can understand the relation between the two, e.g. `api.query.balancesOther` and `api.query.balances` both should have "module name": "balances", coming NOT from what the name of the instance is, but rather from the fact that it is coming from `pallet-**balances**`.

Do you know if this data already exists in metadata? if so, let's keep this open as a TODO for you, else we first fix it in substrate.

**Comment by jacogr** [comment]
The name of the crate is where the above matches, the full path. 

Over and above that, nothing more that will be done on the API.

**Comment by kianenigma** [comment]
> The name of the crate is where the above matches, the full path.

Where can I get this path for each pallet instance, e.g. for `api.query.generalCouncil`?
