### ISSUE TITLE
Incorrect event handling in block 4754892

### ISSUE THREAD

**Issue by oblak1** [polkadot-js/api#5062]
## Description

I'm using js api version 8.11.3. While decoding block 4754892 I noticed the event from balances.ReserveRepatriated in tx _0x5303c6969a9ed8f1ffcb015496ec5d1eb9b6f63b8c87b1a2ae18517958a32d14_ is being incorrectly decoded to balances.Deposit one.

## Steps to replicate

Use _api.events.balances.Deposit.is(event)_ on the mentioned event.

My result:

`if (api.events.balances.Deposit.is(event)) console.log(event.method + ' ' + event.section);`

returns `ReserveRepatriated balances`, while using

`
if (api.events.balances.ReserveRepatriated.is(event)) console.log('TRUE');`

doesn't return anything.

**Comment by oblak1** [comment]
Sorry, kusama mainnet

**Comment by jacogr** [comment]
With the following code -

```js
const hash = await api.rpc.chain.getBlockHash(4754892);
const apiAt = await api.at(hash);
const records = await apiAt.query.system.events();

for (let i = 0; i < records.length; i++) {
  const { event } = records[i];
  
  console.log(i, `${event.section}.${event.method}`);
  
  if (apiAt.events.balances.Deposit.is(event)) {
    console.log('\tDeposit');
  }
  
  if (apiAt.events.balances.ReserveRepatriated.is(event)) {
    console.log('\tReserveRepatriated');
  }
}
```

It logs the following -

```
0 system.ExtrinsicSuccess
1 system.ExtrinsicSuccess
2 balances.ReserveRepatriated
	ReserveRepatriated
3 identity.JudgementGiven
4 proxy.ProxyExecuted
5 treasury.Deposit
6 balances.Deposit
	Deposit
7 system.ExtrinsicSuccess
```

There is no duplicating between the two. Are you using `apiAt` taking care of metadata changes between upgrades?
