### ISSUE TITLE
Statemine system events decoded problem

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5074]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

![x2HCLaLZtU](https://user-images.githubusercontent.com/2264908/179237745-232a213f-a34d-4136-85a9-21411328a807.jpg)

Same bug also on 829497, 841530

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Which is the block in the screenshot?

**Comment by wliyongfeng** [comment]
Sorry, 429268. https://polkadot.js.org/apps/#/explorer/query/429268
