### ISSUE TITLE
Question: Runtime Calls included in Metadata

### ISSUE THREAD

**Issue by NachoPal** [polkadot-js/api#5083]
Are Runtime Calls (https://polkadot.js.org/apps/#/runtime) part of the Metadata? I was checking the documentation and it looks they are not. Is it correct? In that case,  are all those Runtime Calls types hardcoded in polkadot-js?

I was wondering if it would be possible to add also the Runtime Calls types to the Metadata. In that way, in some cases developers could build a custom Runtime API instead of a custom RPCs, with the benefit of not having to generate the custom types.

**Comment by jacogr** [comment]
At this point they are hardcoded - there is an issue logged on Substrate to make this available in the metadata. 

For type generation, there is a new key in the definitions that pull in these - so you can add them to your definitions and typegen will spit out the correct values. This is also how the ones inside the API are generated, some examples -

https://github.com/polkadot-js/api/blob/434f969208c1697add98553d426f60b7422b9ca6/packages/types/src/interfaces/aura/runtime.ts#L6-L24

Which is in turn exposed here on the definition -

https://github.com/polkadot-js/api/blob/434f969208c1697add98553d426f60b7422b9ca6/packages/types/src/interfaces/aura/definitions.ts#L13

**Comment by NachoPal** [comment]
Thanks Jaco, I guess you are referring to this Issue: https://github.com/paritytech/substrate/issues/11648

**Comment by jacogr** [comment]
Sorry, fat fingers. Yes, the linked issue is the one.
