### ISSUE TITLE
How to add custom parameters to an transaction with API, such as to api.tx.balances.transfer 

### ISSUE THREAD

**Issue by sai1024** [polkadot-js/api#5103]
I want to implement payment function(dot、ksm)，but I don't know how to add custom parameters to an transaction with API, such as to api.tx.balances.transfer, thanks.

**Comment by sai1024** [comment]
such as: name and duration params
```
server.post<{ Body: { name: string, to: string, duration: string } }>("/worker/sendDot", async (request, reply) => {
    let { name, to, duration } = request.body
    const keyring = new Keyring({ type: 'sr25519' });
    const alice = keyring.addFromUri('//Alice');
    console.log('alice.address========', alice.address);

    const cost = 1;

    const txHash = await api.tx.balances
    .transfer(to, cost)
    .signAndSend(alice);

    return { txHash: txHash }
  });
```

**Comment by jacogr** [comment]
substrate doesn't have the concept of random attributes on an extrinsic. Best you can do id send a batch with a transfer and a remark.

**Comment by sai1024** [comment]
hello, 12345 is mean?

how to convert to dot or ksm price?

![21658736926_ pic](https://user-images.githubusercontent.com/56356960/180750580-78c63fa6-87d8-4113-8202-3e96c18ff9a9.jpg)

**Comment by sai1024** [comment]
https://polkadot.js.org/docs/api/examples/promise/make-transfer/

```
const txHash = await api.tx.balances
    .transfer(to, 12345)
    .signAndSend(alice);
```

I hope 12345 can convert my want, such as dot  or ksm price

java has methods: walletUtil.ksm2planck(amount)

**Comment by sai1024** [comment]
> 基板没有外部随机属性的概念。最好你可以发送一个带有转移和备注的批次。

I try:
```
const txHash = api.tx.utility.batchAll([
      api.tx.balances.transfer(to, price),
      api.tx.system.remark([name, duration])
    ]).signAndSend(alice)
```
use `batch` or `batchAll` is error:
```
Cannot read properties of undefined (reading 'batchAll')
```

**Comment by sai1024** [comment]
I try:
```
const hash = await Promise.all([
  api.tx.balances.transfer(polkaPnsAddr, amount * 1e10).signAndSend(alice),
  api.tx.system.remark('i am a remark')
])
```
is ok
