### ISSUE TITLE
RPC Remove extrinsic usage

### ISSUE THREAD

**Issue by Robiquet** [polkadot-js/api#5105]
Are there any examples on how to use [removeExtrinsic](https://polkadot.js.org/docs/substrate/rpc/#removeextrinsicbytesorhash-vecextrinsicorhash-vechash)?

I would expect something like this to work (no typescript errors):
`api.rpc.author.pendingExtrinsics((extrinsics) => {
      extrinsics.forEach((e) => {
        api.rpc.author.removeExtrinsic([e.hash]);
      });
    });`

But I get the following error:
`VEC: Unable to decode on index 0 Unable to create Enum via index 235, in Hash, Extrinsic`

**Comment by jacogr** [comment]
`{ Hash: e.hash }`

**Comment by Robiquet** [comment]
Thank a lot. This works:
`api.rpc.author.removeExtrinsic([{ Hash: e.hash }])`
