### ISSUE TITLE
Backward incompatibility with BasicAuth in the newest release

### ISSUE THREAD

**Issue by khelle** [polkadot-js/api#5112]
I believe I found a bug. I have just updated polkadot/api-js from version 8.10.1 to 8.14.1, and it no longer connects to the node. I am following error:

```
API/INIT: Error: FATAL: Unable to initialize the API: https://user:pass@155.155.155.155:8545/ is an url with embedded credentials.
```

Seems like the repository stopped being compatible with BasicAuth authentication for some reason. There is nothing about such change written in changelong as far as I can see. How can I provide BasicAuth credentials instead now?

NOTE: I changed the original endpoint credentials and IP in this issue for obvious reasons.

**Comment by jacogr** [comment]
Which version of Node are you using?

There is a difference between Node 18+ (they introduced `fetch` natively) vs older versions where [node-fetch](https://github.com/node-fetch/node-fetch) is used.

`node-fatch` was bumped to the latest version recently from the 2.x series to the 3.x series.

**Comment by jacogr** [comment]
Seems to be related to this issue in the `node-fetch` library - 

- https://github.com/node-fetch/node-fetch/issues/1304
- https://github.com/node-fetch/node-fetch/issues/1330

For header support as suggested above, you can pass headers to the HttpProvider object, see https://github.com/polkadot-js/api/blob/30f72f915eeb44f9e14996175a073b9e99057196/packages/rpc-provider/src/http/index.ts#L51

**Comment by khelle** [comment]
I am using Node v14. Seems the culprit is v8.12.1, so node-fetch had to be changed in that release. I will try the suggested method of fixing the issue with headers and provide feedback whether it helped. Thank you for a hint!
