### ISSUE TITLE
Update @substrate/smoldot-light dependecies

### ISSUE THREAD

**Issue by petersopko** [polkadot-js/api#5120]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

currently, our app isn't building on windows machines, due to bug in
- https://github.com/paritytech/smoldot/pull/2565
- https://github.com/kodadot/nft-gallery/pull/3603

Package was updated, however, still isn't used where I need it (we need `0.6.27`)
```
dependencies:
@kodadot1/sub-api 0.1.0-alpha.3
└─┬ @polkadot/api 8.14.1
  ├─┬ @polkadot/api-augment 8.14.1
  │ └─┬ @polkadot/api-base 8.14.1
  │   └─┬ @polkadot/rpc-core 8.14.1
  │     └─┬ @polkadot/rpc-provider 8.14.1
  │       └─┬ @substrate/connect 0.7.9
  │         └── @substrate/smoldot-light 0.6.25
  ├─┬ @polkadot/api-base 8.14.1
  │ └─┬ @polkadot/rpc-core 8.14.1
  │   └─┬ @polkadot/rpc-provider 8.14.1
  │     └─┬ @substrate/connect 0.7.9
  │       └── @substrate/smoldot-light 0.6.25
  ├─┬ @polkadot/api-derive 8.14.1
  │ ├─┬ @polkadot/api-augment 8.14.1
  │ │ └─┬ @polkadot/api-base 8.14.1
  │   └─┬ @substrate/connect 0.7.9
  │     └── @substrate/smoldot-light 0.6.25
  └─┬ @polkadot/rpc-provider 8.14.1
    └─┬ @substrate/connect 0.7.9
      └── @substrate/smoldot-light 0.6.25
@polkadot/extension-dapp 0.44.2
└─┬ @polkadot/extension-inject 0.44.2
  └─┬ @polkadot/rpc-provider 8.14.1
    └─┬ @substrate/connect 0.7.9
      └── @substrate/smoldot-light 0.6.25
@polkadot/extension-inject 0.44.2
└─┬ @polkadot/rpc-provider 8.14.1
  └─┬ @substrate/connect 0.7.9
    └── @substrate/smoldot-light 0.6.25

```

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
We only add `@substrate/connect` here - https://github.com/polkadot-js/api/blob/e4a19dcefda8944a569ff15e52b8f610ee25803a/packages/rpc-provider/package.json#L35

That is on latest. There is nothing that the API can do over and above that.

**Comment by petersopko** [comment]
thanks a lot for help :)
