### ISSUE TITLE
How to see if a transaction was successful by block hash

### ISSUE THREAD

**Issue by sai1024** [polkadot-js/api#5121]
hi, I want to see if a transaction was successful by block hash

```
const hash = await Promise.all([
  api.tx.balances.transfer(polkaPnsAddr, amount * 1e10).signAndSend(alice),
  api.tx.system.remark('i am a remark')
])
```
I added a remark: 'i am a remark', and  I know user's polkadot address and block hash， how can I find this remark through the block hash?

thanks.

**Comment by jacogr** [comment]
This, as per the suggestion for HOWTO queries, is best asked on SO. (Where answers for this question does exist)

Additionally the cookbook has examples of matching blocks/extrinsics to events.
