### ISSUE TITLE
Parachain provider is never ready

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#5140]
```
      const relayProvider = new ScProvider(endpoints.relaychain);
      const parachainSpec = endpoints.parachain;
      const provider = new ScProvider(parachainSpec, relayProvider);
      api = new ApiRx({ provider: provider })
      await provider.connect()
      console.log(111, provider.isConnected)
      provider.on('connected', () => {
        console.log(222, provider.isConnected)
      })
```

The para provider is never connected.

I think the fix is need to forward the connected event from relay provider to para provider

**Comment by jacogr** [comment]
The above code does look similar to the code provided here - https://github.com/polkadot-js/api/pull/4672

Have honestly not done the above (use it in relay-mode-only in the apps UI), and not overly familiar with the provider internals such that you can wake me up at 3am and ask, so cannot comment at this point of what may be the case or as to "why".

**Comment by xlc** [comment]
After some more investigation, it seems like my original understand was wrong. It is not related to relaychain provider conflicts with parachain provider but the parachain node actually have no peers, so that's likely smoldot issue.
