### ISSUE TITLE
Types not imported automatically after successful typegen

### ISSUE THREAD

**Issue by ntn-x2** [polkadot-js/api#5151]
After generating the augmentation stuff correctly (i.e., running `generate:meta && generate:defs`), with custom rpc, state_call, and type definitions, I noticed that, albeit the right types are then used in `augment-api-*.ts` files, they are not imported, and I manually have to add the ones that have not been imported to fix compilation issues. I followed the guide from start to end.
The compilation process finished successfully with no error messages. Am I forgetting something?

I attach a screenshot that hopefully makes it clear what I am talking about, bottom-right corner, pointed at by a red arrow.

<img width="1429" alt="Screenshot 2022-08-12 at 09 19 20" src="https://user-images.githubusercontent.com/6704504/184304718-f01b75d8-fc76-49f1-bf4b-287a1aea9995.png">

**Comment by jacogr** [comment]
The lookup types are from the on-chain metadata. This means, like in the from-chain, you also need to pass the `--endpoint` to the defs generation so it has access to the metadata.

**Comment by ntn-x2** [comment]
We do that. 

This is a snippet of our `package.json` file:

```json
"scripts": {
    "generate:defs": "ts-node --skip-project ../../node_modules/.bin/polkadot-types-from-defs --package @kiltprotocol/augment-api --input ./src/interfaces --endpoint ./metadata/spiritnet.json",
    "generate:meta": "ts-node --skip-project ../../node_modules/.bin/polkadot-types-from-chain --package @kiltprotocol/augment-api --endpoint ./metadata/spiritnet.json --output ./src/interfaces  --strict",
    "update-metadata": "node ./scripts/fetchMetadata.js -o './metadata/spiritnet.json' -e 'wss://spiritnet.kilt.io/'"
}
```

**Comment by jacogr** [comment]
Ensure that you apply all augmentations, e.g

```js
// augment on-chain lookup types
import './interfaces/types-lookup';

// augment types for createType(...)
import './interfaces/augment-types';
import './interfaces/registry';

// augment API interfaces
import './interfaces/augment-api';

// import API stuff
import { ApiPromise, WsProvider } from '@polkadot/api';

ApiPromise
	.create({ provider: new WsProvider('wss://spiritnet.kilt.io/') })
	.then((api) => api.query.aura.authorities())
	.then(console.log);
```

(Remember that the build outputs are augmentated files, so the lookup imports do require the lookup augmentation to resolve)

**Comment by ntn-x2** [comment]
Nice, that fixed the problem for all the `augment-api-*.ts` files, but now I am having the same issue with our custom type definitions inside an `extraDefs` folder. Is this also related? 

Our package `index.ts` file is the following now:

```ts
// Augment on-chain lookup types
import './interfaces/types-lookup.js'

// Augment types for createType(...)
import './interfaces/augment-types.js'
import './interfaces/registry.js'

// Augment API interfaces
import './interfaces/augment-api.js'

export * from './types.js'
```

<img width="1416" alt="Screenshot 2022-08-12 at 10 34 26" src="https://user-images.githubusercontent.com/6704504/184317031-8575e184-3215-4b4b-a957-d9a7763461b1.png">
