### ISSUE TITLE
[Support] Is there any way to suppress RPC errors from the provider (query_feeDetails)

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#5159]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Current Behavior: When querying `query_feeDetails` in a runtime that doesnt support it, you can catch the error but it will log regardless. 

## Code example:

```typescript
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://rpc.polkadot.io'),
    });

    const extrinsic = '0x510884122efdea02dda2a9b56b20809ae8108ab89c5a8692e6197d0cc8cf4903a7e81601005267278172d49fde8a23513165bcd894ba0d9b5a7ee3e2976b5202d9f2a942515021b2c175ea46139b066709dfe610ec96d019b9622f7a46ee8f2587378b8a550304001d00a569f6e4cf6bed95cafbf001e13254b28710220cd9b208c10f7154c17740099f001100305c5062779d44ea2ab0469e155b8cf3e004fce71b3b3d38263cd9fa9478f12f28f1fe9f7ba0feab9e47684d4006ed25ad6c441a1553cef62748545ea575392af5a69484f2b10ec2f1dea19394423d576f91c6b5ab2315b389f4e108bcf0aa28408e29df67564eddc299a2aa1cdacbec3c1ae061cf0835c87e5b46b920f7573a774adf51a47b72795366d52285e329229c836ea7bbfe139dbe8fa0700c4f86fc563c82ab06b794c99f14a161973be7aa6012568b1c491d45ec969ed7420bcfaa59ca5bc1915da74aba3aadd7ce7b809045d5eb5b73559259755fdcd85a40a5dc6e6af08f6bb841825b168ddf79837e70d88d75e1c5b290b74fa97cedfd668dd22c984e16482c99cfad1436111e321a86d87d0fac203bf64538f888e45d793b54133235f7d984058bb410c163fc1d7a90e5475c0917aad77deb241093a50b4f683f3ef37fce11457ebc5f00b154996471fcd30eae17efe69e5a39b12b76034dc7e4a6996ba5fce10b5419b5a9fd55998b5d7fde4922e61f93b021cb2cf6dfd5707e0f00001a93fa350e'
    const blockHash = '0x205da5dba43bbecae52b44912249480aa9f751630872b6b6ba1a9d2aeabf0177'; // BlockId 789628
    try {
        await api.rpc.payment.queryFeeDetails(extrinsic, blockHash)
    } catch {}
};
```

Error: `RPC-CORE: queryFeeDetails(extrinsic: Bytes, at?: BlockHash): FeeDetails:: 1: Unable to query fee details.: Execution failed: Other: Exported method TransactionPaymentApi_query_fee_details is not found`

* **What is the motivation for changing the behavior?**

Is there any way to suppress RPC error's that are logged from the provider? The error is still logged regardless of catching it. In general it's definitely not ideal to suppress any error but I think the use case here is pretty unique.

## The issue

`payment_query_feeDetails` is not available for use for all runtimes. As an example runtime v26 and below on polkadot. Currently I dont know any way to find out if it's an available rpc method or not. I tried to use the `RuntimeVersionApi` blake2 hashes to identify if the api has that method but it actually doesnt help here as it just stores the `TransactionPaymentApi` trait as a hash but no clue to the calls that exists, and the version given in that tuple is the same across runtimes. 

* **Please tell us about your environment:**

  - Version: 9.1.1
  - Environment:

    - [X] Node.js v17.1
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version) v4.7.4
    - [ ] Other

**Comment by jacogr** [comment]
Rathe use api.at and then use api.call.paymentApi.* (it will be decorated if available)

**Comment by TarikGul** [comment]
> Rathe use api.at and then use api.call.transactionPaymwntApi.* (it will be decorated if available)

That is a huge help, and definitely solves my issues. Much thanks again :) 🙏

**Comment by jacogr** [comment]
In the API itself where it does the signing, the RPCs will be replaced really soon with runtime calls - have not had a gap to see how that goes.

**Comment by TarikGul** [comment]
> In the API itself where it does the signing and paymentInfo, the RPCs will be replaced really soon with runtime calls - have not had a gap to see how that goes.

Ahh okay makes sense, good to know. Thanks for the heads up. I'll make sure to keep up with this as it will probably require some refactoring on our end as well.

**Comment by TarikGul** [comment]
@jacogr 

So I noticed a few areas where the `queryInfo` and `queryFeeDetails` are available for the runtime, but the `apiAt.call.transactionPaymentApi` comes back `undefined`. I'll put an example block below. Let me know if this is a valid bug and you want me to transfer this to an issue.

## Example

Network: Polkadot
BlockNumber: 4092619

```typescript
const extrinsic = '0x4102840012852bea5af210b7c409dadac3e2146857f7d2d63695cedcb8534ebff83a7ed3001a084779ccd11a3bfbaea5b81346c3943164e789fe367d4e39069bb4e321d248e90ad394307947b9e21c80fdf5d08d267bd211430d34c5abb7d828ddfe5aed0cb50100000503003b127a1acc2dd2c90ccbbd8d608bd58a527c0a700ab9bc323032414a85f81f1207009217b122';
const previousBlockHash = '0x3051684c90d92f234ed2ddeb434e4a93fc4a115600731a1805175498cd4f6359';

const apiAt = await api.at(previousBlockHash);

const paymentCallExists = await apiAt.call.transactionPaymentApi;

console.log('TransactionPaymentApi: ', paymentCallExists)

const queryInfo = await api.rpc.payment.queryInfo(extrinsic, previousBlockHash);
const { inclusionFee } = await api.rpc.payment.queryFeeDetails(extrinsic, previousBlockHash);

console.log('QueryInfo call: ', queryInfo.toJSON());
console.log('QueryFeeDetails call: ', inclusionFee.isSome);
```

**Comment by jacogr** [comment]
If it is on the runtime, it should be decorated. So if indeed the case, it is a bug. (Assuming that the versions of the API does match, but I believe payment is on version 1)

**Comment by TarikGul** [comment]
> transfer to an issue so it can get attention

Will do. Thanks again
