### ISSUE TITLE
[Support] `apiAt.call.transactionPaymentApi` RPC-CORE error logging

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#5169]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Apologies for the noise, but I wanted to ask a quick follow up question regarding the last two issue: https://github.com/polkadot-js/api/issues/5161, and https://github.com/polkadot-js/api/issues/5159.

So the hurdle for us and understanding `TransactionPaymentApi` is that the Runtime Api hashes and their corresponding versions dont change from when `queryFeeDetails` was added so there is no way to know if `queryFeeDetails` exists in the Api or not. 

So for `apiAt.call.transactionPaymentApi.queryFeeDetails`, in a runtime where it doesn't exist the calls are still decorated, and when we call it we still receive an RPC_CORE error (which is expected seeing the constraints you are dealing with). 

As a work around I want to set the `queryFeeDetails` call within a `try-catch`, and when it errors, catch that error, log a warning, and then do calculations with `queryInfo`. But currently there is no way to catch the error as it will be logged no matter what. Is there a way to work around this? If not it's totally fine and it's something we'll have to settle with for historic blocks. 

**Quick Example**

```typescript
const extrinsic = '0x3902846610b9239952035b0b722df256f97cb16b392e8b8e84eee2999ce06fae3b1f2b01388d21c5a077b728bcd304123fee47f09f06465b5d9ccee5b29752e6c19a5d5d1bf23c4ff0026f1e898b661e32bb0c76db976fe50d9549b3d8af27e5bad3a78ed50224000500ba421a69ce0d72b22ea6282ea380d5ef9c5f9392a45e8047b7ac38ee8552833a0700c817a804'
const blockHash = '0x46900e5340e9485e01c31c9d9cc0925c69c8eb2bc308de321a99feb3d6bf4993'; // BlockId 2392625

const apiAt = await api.at(blockHash);

try {
	await apiAt.call.transactionPaymentApi.queryFeeDetails(extrinsic, 0);
} catch (e) {} // Should silent error, but the error shows up regardless
```

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: v9.2.2
  - Environment:

    - [X] Node.js v17.1.0
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version) v4.7.4
    - [ ] Other

edit: Little grumble, there is a way to catch the errors, as you can catch it with a try-catch. But there is no way from stopping the api from logging the error itself which is the main concern here.

**Comment by jacogr** [comment]
We need to be really stringent on not „just adding stuff“ without version bumps. It creates a big mess like we have with RPCs. (In this case the version should have increased, imho)

Anyway, do you have a hash to look at?

**Comment by TarikGul** [comment]
> We need to be really stringent on not „just adding stuff“ without version bumps. It creates a big mess like we have with RPCs. (In this case the version should have increased, imho)

I definitely agree, I was a little confused when parsing through all the RuntimeApi hashes myself, and not seeing any differences in the versions for when the methods were added. 

Also as a note the above example is for Polkadot.

**Comment by jacogr** [comment]
Yes, the API matches on hashes and version - so it actually has historic definitions for old versions as well (not all, some have been difficult to extract, but will get it comprehensive sometime)

**Comment by jacogr** [comment]
For this, the only thing I can suggest is to add an additional logging flag to disable all by default RPC error logs. 

Something like this one - https://github.com/polkadot-js/api/blob/2bad0f479932ddac92a5583321a280e40e9cb8cf/packages/api/src/types/index.ts#L55

**Comment by TarikGul** [comment]
> For this, the only thing I can suggest is to add an additional logging flag to disable all by default RPC error logs.

For `noInitWarn` it currently doesn't work since it only silences the initialization warning logs. (But honestly just learning about this that's really neat :))

I was just looking into the RPC-CORE code as well: https://github.com/polkadot-js/api/blob/master/packages/rpc-core/src/bundle.ts#L43-L55

Im assuming using the `rpc` field in `ApiOptions` could technically work if we set `noErrorLog` to true if we define the `queryFeeDetails` rpc ourselves?

**Comment by TarikGul** [comment]
I would imagine it's not wise to define the RPC ourselves in general, but just from a general gaze it did look like a potential solution (even if we don't utilize it, definitely good to know about, but I will give it a try if it's something that is doable that wouldn't cause internal issues when defining the RPC's).

**Comment by jacogr** [comment]
Yes, was not suggesting to use `noInitWarn`, but rather something like it.

**Comment by TarikGul** [comment]
> Yes, was not suggesting to use noInitWarn, but rather something like it.

Makes sense looking back now, I read that wrong.

Anyways thanks again for all the guidance. I definitely have enough here to put together a solution. I will close the issue knowing the options I have now for logging.
