### ISSUE TITLE
Some para-chain block events can't be decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5172]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Please check the events sections on following 2 pages:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpublic-rpc.pinknode.io%2Fkhala#/explorer/query/410439
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Feu.bifrost-rpc.liebi.com%2Fws#/explorer/query/380456

I'm sure they work at previous versions like `8.11.3`, so maybe there are some bugs in latest versions.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The types for those chains are maintained by the teams themselves. The API does not manage the definitions (like with Kusama/Polkadot)

**Comment by wliyongfeng** [comment]
> The types for those chains are maintained by the teams themselves. The API does not manage the definitions for historic blocks (like with Kusama/Polkadot)

I know this, but I didn't change the para-chain types definitions, which means same type definitions may work with old version of api but not with latest versions. So is it possible there are some problems with latest api release? Or I should tell the teams and let them to confirm it first?

**Comment by jacogr** [comment]
In the case of Bifrost, they don't seem to have the old `DispatchError` mapping, aka as done in Kusama `DispatchErrorModule: 'DispatchErrorModuleU8',` (the block has an error returned)

In the case of Khala, same thing, there is a DispatchError on the proposal execution.

So in both cases, this is not an API issues, this is historic types that need adjustment.

**Comment by wliyongfeng** [comment]
I see. Thanks a lot.

**Comment by jasl** [comment]
> In the case of Bifrost, they don't seem to have the old `DispatchError` mapping, aka as done in Kusama `DispatchErrorModule: 'DispatchErrorModuleU8',` (the block has an error returned)
> 
> In the case of Khala, same thing, there is a DispatchError on the proposal execution.
> 
> So in both cases, this is not an API issue, this is historic types that need adjustment.
> 
> The reason why you don't see it on prior versions is that around 8.11 the new DispatchError was introduced, aligning with Substrate.

You mean I need to add `DispatchErrorModule: 'DispatchErrorModuleU8'` to our typedef?
(BTW, it seems ability of override typedef on Polkadot.js UI has been removed)

But, according to https://khala.subscan.io/event?block=410439 I don't see there's a DispatchError?

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/185383567-0c402eed-d9ea-49b7-91bd-0486519f86bf.png)

**Comment by jasl** [comment]
@jacogr Could you help to take a look https://github.com/Phala-Network/typedefs/pull/10/files#diff-20c768d8ab67dcc4bca7726f836903aa8432ea51225c13301ebc86c35bffdf68 I'm not sure I'm doing right.

thank you
