### ISSUE TITLE
Decoding error for raw public keys

### ISSUE THREAD

**Issue by ntn-x2** [polkadot-js/api#5196]
Currently, it is not possible to deal with public keys returned by an RPC endpoint.
According to the [source code of Ed25519 (as an example)](https://github.com/paritytech/substrate/blob/master/primitives/core/src/ed25519.rs#L186), public keys are always serialised as SS58 addresses.

This means that types that have references to public keys, such as our type below, will fail to decode since it expects an array of 32 bytes, but it indeed receives an array of 48 bytes, failing to decode with the error shown below.

I think this is something that could be possibly handled in the client side?

## Example of type definition with public key references

```rust
pub enum DidVerificationKey {
	Ed25519(ed25519::Public),
	Sr25519(sr25519::Public),
	Ecdsa(ecdsa::Public),
}
```

since `ed25519::Public` is just defined as below, the decoder expects an array of 32 bytes:

```rust
pub struct Public(pub [u8; 32]);
```

## What is returned by the RPC endpoint

This is what the RPC endpoint instead returns for a public key:

```json
{
  "PublicVerificationKey": {
    "Sr25519": "5EUTD6nGHNLNPQngmETv8YFUSuQi1GZcwXTsW3wpV5nZ6P2S"
  }
}
```

failing with the following error:

```
Struct: failed on key: {"_enum":{"PublicVerificationKey":"DidVerificationKey","PublicEncryptionKey":"DidEncryptionKey"}}:: Enum(PublicVerificationKey):: Enum(Ed25519):: Expected input with 32 bytes (256 bits), found 48 bytes
```

Is there a solution that could be implemented in the client library? Since types are taken from the runtime metadata, this is probably something that would require some sort of type definition override. Or is this something that should rather be fixed in Substrate? Or maybe we should implement a custom (de)serializer for our own use case? I guess this happens because serde serialization and deserialization is different from codec encoding and decoding, in this case.

Perhaps allowing for an additional `PublicKey` type definition, where the payload is simply base58decoded would work.

**Comment by jacogr** [comment]
How is the `DidVerificationKey` defined in the types? (Since it is RPC, it needs type definitions, aka it doesn't come from metedata, hence asking)

**Comment by ntn-x2** [comment]
It was using the runtime information about it, since the same time is also used in the metadata, and I guess that is where the issue arises.

Scale does not do anything special, but serde does. So I guess we would have to duplicate the type definition just to support the different encoding?

I just settled for

```js
 DidVerificationKey: {
    _enum: {
      // SS58-encoded
      Ed25519: "[u8; 48]",
      // SS58-encoded
      Sr25519: "[u8; 48]",
      // SS58-encoded
      Ecdsa: "[u8; 49]",
    },
  },
```

I think `AccountId32` applies some additional logic which then results in a different value than the raw key.

**Comment by jacogr** [comment]
AccountId32 has no logic - it is just a `[u8; 32]` that can decode from ss58 (and has an ss58 `toString`). If you do `.toU8a()` on either, it ends up with the raw public key.

**Comment by ntn-x2** [comment]
`AccountId32` does not work with public Ecdsa keys. It seems that it decodes fine, but it then truncates to the first 32 bytes, while an Ecdsa public key has 33 bytes.

Example:

```js
console.log(u8aToHex(decodeAddress('4o8ZUWNkE3mjgW73xGVFHFoTve33Uyw5jLhgDFKF7PTEVo2k')))
```

prints `0x0987654309876543098765430987654309876543098765430987654309876543` while the full key is `0x098765430987654309876543098765430987654309876543098765430987654309`, which has an additional `09` at the end.

**Comment by ntn-x2** [comment]
I guess at this point the best would be to define `"[u8; 48]"` or `"[u8; 49]"` and let applications handle the decoding.

**Comment by jacogr** [comment]
Yes, `AccountId32` won't work for Ecdsa, they are 33 bytes, so `AccountId32` will always just grab the first 32. 

There is no type that transparently handles 33-bytes publicKeys encoded as ss58.

**Comment by ntn-x2** [comment]
Just to close the loop, this is how I decided to settle for now, since I could not find any other way to make it work:

```js
DidVerificationKey: {
  _enum: {
    // SS58-encoded public key (consumer must call decodeAddress)
    Ed25519: "Text",
    // SS58-encoded public key (consumer must call decodeAddress)
    Sr25519: "Text",
    // SS58-encoded public key (consumer must call decodeAddress)
    Ecdsa: "Text",
  }
}
```

Should I close the issue? Or is it something that could be worked on, to add an additional type that would decode ss58-encoded public keys?

**Comment by jacogr** [comment]
AccountId32 does exactly what you want - it is a public key in ss58 format. (Assuming sr/ed)

Your only issue is that there is no 33 variant. 

That could be an enhancement for a AccountId33 at some point, but there needs to be a bit more cases for it to be coded. (Single-chain use costs just as much maintenance wise and anything else)

**Comment by ntn-x2** [comment]
Alright, then I will close the issue for now. Thanks for the prompt support.

**Comment by jacogr** [comment]
Will add `AccountId33` anyway - I took a look can make it generic with no maintenance overhead. (Will be in the next release over the weekend)

**Comment by ntn-x2** [comment]
But we need to be careful since this naming convention collides with the Substrate one. What is an `AccountId33`? Here we are talking about public keys. It is just a coincidence that the public key and the account are the same for Ed25519 and Sr25519 keypairs. This is not the case for Ecdsa keys, which are hashed to produce an account. So calling this `AccountId33` could be confusing. Just pointing this out.

**Comment by jacogr** [comment]
`AccountId20` is a `[u8; 20]` with an hex representation (ETH-like)
`AccountId32` is a `[u8; 32]` with an ss58 representation
`AccountId33` is a `[u8; 33]` with an ss58 representation

It just defines the length and (human) representation capabilities. What is contained within can be anything, depending on logic to create it. So in your case, for the sake of clarity, would sugest a `PublicKey32: 'AcocuntId32` alias and then using that.

The contained makes no guarantees as to what is contained within, something raw, something hashed - it is just concerned about the size and representation.

**Comment by ntn-x2** [comment]
Followup-question:

while the new type works great with a script that uses the latest 9.3.2 package, I still get the "Unexpected 48 bytes" when trying to call the RPC endpoint via the apps UI, as if that component does not use the latest type definitions.
I have built and linked locally the definitions with yalc, and it works just fine if I try to create a type via the embedded JS console.

Does perhaps the apps need changes to support the new types? Or am I still missing something? Should I open a new issue in the apps repo?

![Screenshot 2022-09-05 at 09 04 07](https://user-images.githubusercontent.com/6704504/188389165-19145ac7-57bf-4a78-b51a-dccb2b4deb47.png)
