### ISSUE TITLE
Sign transaction with AccountKey20 account from Moonbase Alpha

### ISSUE THREAD

**Issue by dudo50** [polkadot-js/api#5198]
-->

* **I'm submitting a issue with signing transaction with PolkadotJS wallet**

  - [ ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [x] Other

* **What is the current behavior and expected behavior?**

When I try to sign transaction with JSON imported account (with AddressKey20 address format) I can get to popup and sign transaction but immediately after signing I receive error `ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature`

![Screenshot from 2022-09-01 22-04-18](https://user-images.githubusercontent.com/55763425/188003634-41308f98-3d34-42a5-8ec9-cb5a61f11e90.png)

![Screenshot from 2022-09-01 22-05-24](https://user-images.githubusercontent.com/55763425/188003659-c9a494e9-7007-4144-af13-3b5c5951e320.png)

![Screenshot from 2022-09-01 22-05-42](https://user-images.githubusercontent.com/55763425/188003669-f4aaae5c-afa3-4e04-a186-7d4cb788b9e7.png)

How I sign API transaction call and inject wallet:

```
//I set selected address as injector
const injector = await web3FromAddress(address); 

//Signing transaction (Account has accountkey20 address format)
.signAndSend(address, { signer: injector.signer }, ({ status, txHash }) => {
              if(counter == 0){    
                this.$notify({ text: `Transaction hash is ${txHash.toHex()}`, duration: 10000,speed: 100})
                counter++
              }
              if (status.isFinalized) {
                this.$notify({ text: `Transaction finalized at blockHash ${status.asFinalized}`,type: 'success', duration: 10000,speed: 100})
              }
            })

```

I tried to use evmToAddress() function but then I get an error that the address could not be found in the wallet.

* **Please tell us about your environment:**

System Ubuntu 21
Chrome browser
Vue.js app

  - Version:
  - Environment:

    - [x] Node.js 16
    - [x] Browser Chrome
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
You seem to be using the extension to sign - there is an open issue on the extension repo with Moonbeam not working. (Along with an open PR that addresses the issue)

**Comment by dudo50** [comment]
Is there any way to sign API transactions with Metamask then? Thanks in advance

**Comment by jacogr** [comment]
The extension interface has a metamask-compatible layer, see https://github.com/polkadot-js/extension/tree/master/packages/extension-compat-metamask, that _could_ be used (contributed by the Moonbeam team), but as far as I know there are no dapps (and certainly not the apps UI) that enables this for Moonbeam-like chains. (I could be wrong on the usage of the compat layer, so can only speak for the polkadot-js side not enabling it by default)

**Comment by jacogr** [comment]
Closing.
