### ISSUE TITLE
ApiPromise import cost huge

### ISSUE THREAD

**Issue by sxlwar** [polkadot-js/api#5209]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [x] Other

* **What is the current behavior and expected behavior?**

<img width="582" alt="image" src="https://user-images.githubusercontent.com/20088392/189094157-3f276d13-b77a-4ce6-b20e-743630c74c67.png">

ApiPromise is almost 1M, it's too large

Expect: reduce the import cost

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Possibly nothing additional that can be done - there are a number of large layers (which only would be part of it when used), such as light and WASM (the first won't be included in modern bundlers when not used, the second can be bypassed when not using sr25519)

**Comment by jacogr** [comment]
Closing. The actual light has now been made optional (or rather requires some extra hoops where the user needs to "bring their own `substrate-connect`). This dropped the import by 50% alone.
