### ISSUE TITLE
Error: Unable to decode on index 6 createType

### ISSUE THREAD

**Issue by oblak1** [polkadot-js/api#5211]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

On block 90522 of altair chain I get this error:

```
VEC: Unable to decode on index 6 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding sudo.sudo:: Struct: failed on args: {"call":"Call"}:: decodeU8a: failed at 0xc7031c1a2c1a1fd224bd095c6f0ce057… on call (index 0/1): Call:: Call: failed decoding migration.migrateProxyProxies:: Struct: failed on args: {"proxies":"Vec<(AccountId,Balance,(Vec<ProxyDefinition>,Balance))>"}:: decodeU8a: failed at 0x1c1a2c1a1fd224bd095c6f0ce0579d58… on proxies (index 0/1): Vec<(AccountId,Balance,(Vec<ProxyDefinition>,Balance))>:: decodeU8a: failed at 0x5cd191163be61a3ab2645978e9e971bb… (index 1/7): (AccountId,Balance,(Vec<ProxyDefinition>,Balance)):: decodeU8a: failed at 0x083808d6223035f44fcf55f865ea210e… (index 2/3): (Vec<ProxyDefinition>,Balance):: decodeU8a: failed at 0x083808d6223035f44fcf55f865ea210e… (index 0/2): Vec<ProxyDefinition>:: decodeU8a: failed at 0x3808d6223035f44fcf55f865ea210eda… (index 0/2): {"delegate":"AccountId","proxyType":"ProxyType","delay":"BlockNumber"}:: decodeU8a: failed at 0x040000000069a697c24ac831524d6c1e… on proxyType (index 1/3): {"_enum":{"Any":0,"NonTransfer":1,"Governance":2,"Staking":3}}:: Unable to create Enum via index 4, in Any, NonTransfer, Governance, Staking
```

I was wondering whether this  could be a bug or if I should solve this another way (via downgrading an API) and why does this actually happen only on some blocks. I've read somewhere it could be a migration problem but I'm not sure.

* **Please tell us about your environment:**
tsconfig:

```
{
  "extends": "../tsconfig-base",
  "include": ["src/**/*.ts"],
  "compilerOptions": {
    "outDir": "./dist",
    "skipLibCheck": true,
    "paths": {
      "@polkadot/api/augment": ["./src/interfaces/augment-api.ts"],
      "@polkadot/types/augment": ["./src/interfaces/augment-types.ts"],
      "@polkadot/types/lookup": ["./src/interfaces/types-lookup.ts"]
    }
  }
}
```

  - Version:

I'm using @polkadot/api (and types) 9.2.3 with custom API augment for altair chain (node: wss://fullnode.altair.centrifuge.io).

  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
For historic blocks, you would need to inject types for the specific chain. These types are maintained by the teams themselves. 

In this case it looks like the Proxy type specifically.

**Comment by oblak1** [comment]
Okay, so augment-types aren't enough and I should also include the types object in WsPromise?

Why does this happen on some (random) blocks only?

**Comment by jacogr** [comment]
Augmentation is for typescript usage. 

It appears on that block since the Proxy type is used in that block.
