### ISSUE TITLE
Issues creating RuntimeDispatchInfo type when using queryInfo

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#5218]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When using `rpc.payment.queryInfo` against certain blocks on westend there is the following decoding error:

```
RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed
```

### Reproduction

```javascript
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://westend-rpc.polkadot.io'),
    });

    // Extrinsic is from block 12604391, blockhash is for block 12604390
    const extrinsic = '0x310284009ba31d1bca2c1123f67c012b86cceef3c8333fa2370a7e9f3ba7fe88b8600082009849e1cd980414a560e310bed2b2d82e9a4392eac0dc52245fd9fce31eef126c9a984511d1e0dec3f9b20b4846a12fe9d1ca47b4886c4316fe04d61bf656980e2b3e4d05000403002f833023f0254be1362a880c1e74bd1d2e1348b216201749b4f8d5191b1d17b400'
    const blockHash = '0xecc5770387f776b64a73f3614666a41fc325a81f3e029bc45fe684cc84103cf5';
    const result = await api.rpc.payment.queryInfo(extrinsic, blockHash);
    console.log('queryInfo: ', result.toJSON());

};

main().finally(() => process.exit());

```

This is happening on westend currently as far as I know, and here are some additional blocks:
12604449
12604804

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  `@polkadot/api@9.3.3`
  
  - Environment:

    - [x] Node.js v17.1
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [X] JavaScript (I reproduced in Typescript and Javascript)
    - [X] TypeScript (include tsc --version) 4.8.2
    - [ ] Other

**Comment by niklasad1** [comment]
This is probably because of the weight type in substrate was changed from `u64 -> struct Weight { ref_time: u64 }`

**Comment by lcovar** [comment]
Any update? We're unable to continue indexing blocks due to this.

**Comment by jacogr** [comment]
I am looking at solutions - these are deceptively tricky since RPCs are not fully-specified with metadata/types and needs tweaks on a version basis without breaking compat for all chains.  Hopefully a solution will present itself before a point release over the weekend.
