### ISSUE TITLE
api.derive.staking.account - redeemable using activeEra vs currentEra 

### ISSUE THREAD

**Issue by aserafin** [polkadot-js/api#5229]
In `api.derive.staking.account` the polkadot-js library is using `activeEra` to calculate redeemable amount https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/staking/account.ts#L48

```
function redeemableSum (api: DeriveApi, stakingLedger: PalletStakingStakingLedger | undefined, sessionInfo: DeriveSessionInfo): Balance {
  return api.registry.createType('Balance', (stakingLedger?.unlocking || [] as PalletStakingUnlockChunk[]).reduce((total, { era, value }): BN => {
    return sessionInfo.activeEra.gte(era.unwrap())
      ? total.iadd(value.unwrap())
      : total;
  }, new BN(0)));
}
```

but looking at rust implementation of the `withdraw_unbonded` method it makes it's comparisons against the `currentEra` here https://github.com/paritytech/substrate/blob/fdfdc73f9e64dc47934b72eb9af3e1989e4ba699/frame/staking/src/pallet/mod.rs#L966 and also uses `currentEra` when creating entries in ledger https://github.com/paritytech/substrate/blob/fdfdc73f9e64dc47934b72eb9af3e1989e4ba699/frame/staking/src/pallet/mod.rs#L922

Since activeEra and currentEra are actually different for the last epoch of an activeEra then assuming this entry in ledger:

```
{
"unlocking": 
  {
    "era": 2,
    "value": "2000000000000"
  }
}
```
and 

```
activeEra == 1
currentEra == 2 for the last epoch of activeEra
```

the redeemable method would return 0 bc. it uses `activeEra` but the `withdraw_unbonded` would be successful in withdrawing the `2000000000000` bc. it uses the currentEra?

**Comment by jacogr** [comment]
Thank you for linking through to the source of truth (Rust) as well. The good thing is that it doesn’t cost funds, although incorrectly it would delay by an era. 

Will have to take a look.

**Comment by aserafin** [comment]
@jacogr I'm looking at the PR and I'm not sure if it's right 🤔 in Rust:

```
.filter(|chunk| {
  if chunk.era > current_era {
    true
  } else {
    total = total.saturating_sub(chunk.value);
    false
  }
})
```

so if I understand it correctly if the `era` in unlocking is greater than `current_era` the entry stays, otherwise (so if `era <= current_era` we remove it).

That would mean when counting redeemable the comparison should be:

```
return sessionInfo.currentEra.gte(era.unwrap()) ? total.iadd(value.unwrap()) : total;
```
so `current_era >= era` 🤔 

Sadly I can't test it at the moment bc. the era on westend hasn't progressed for almost 2 days :(

**Comment by jacogr** [comment]
Umpf, you are right... blame lack of sleep, I swapped era & current_era
