### ISSUE TITLE
Handle Rust errors

### ISSUE THREAD

**Issue by tuul-wq** [polkadot-js/api#5240]
From time to time `smoldot-light` throws Rust errors that are not handled in `@polkadot/rpc-provider` so the application crashes. It doesn't happen when I initiate a `ScProvder/WsProvider` nor when I connect, thus I'm not able to use simple `try catch` in those situations.
Error example - https://github.com/paritytech/smoldot/issues/2740.
Me and @wirednkod have discussed this issue and came up with an idea to add some kind of handlers/callbacks to properly react on Rust errors.

**Comment by tomaka** [comment]
These situations are bugs in smoldot and are no different than if for example PolkadotJS tried to access a property on a `null` object.
The only sensible course of action, to me, is to fix the bugs, not try to handle bugs gracefully.

**Comment by pgolovkin** [comment]
@tomaka from the client application point of view there should be a way for error handling on the client application side. It shouldn't depend on how stable is the solution that is being used.
So it will be good anyway to have a way for catching and processing errors that happens in smoldot. The application shouldn't fail for sure.

**Comment by pgolovkin** [comment]
@tomaka What about adding the option to add the error handler callback that allows to developer to add some fallback logic like restarting the light client or warning the user about the problem?

**Comment by tomaka** [comment]
There is already an `error` event that you can subscribe on the provider, and an `error` is normally triggered in case of a crash of the client. When that happens, you can show a huge popup saying that something wrong happened.

However, I don't think it's a good idea to try to restart/continue automatically when such an error happens. Asking the user to reload the page is IMO the best course of action.

**Comment by tuul-wq** [comment]
@tomaka Could you share a JS/TS example of this subscription?
Signature of the methods is: 
`subscribe(type: string, method: string, params: unknown[], cb: ProviderInterfaceCallback): Promise<number | string>;`
What is `number` and `string` in the return value?
What values can I pass for `type`, `method` and `params`?
How can I subscribe to every error that might occur in Provider if that's possible?

**Comment by tuul-wq** [comment]
@tomaka any updates regarding code examples?

**Comment by pgolovkin** [comment]
Hey @tomaka! I'd like just to remind about the question above. Could you please provide some code examples with attaching error handler.

**Comment by tomaka** [comment]
You are asking a PolkadotJS-specific question. This is not my domain. I can only tell you that the provider has an events system, and that the substrate-connect provider generates an `error` event on crash. This events system isn't related to the parameters of the `subscribe` function.

I must also mention that it is not polite to ask questions to one person specifically, especially in an issue that isn't even related to the question.

**Comment by pgolovkin** [comment]
@tomaka thank you! Sorry for asking you the question out of your domain.
We'll proceed findings.
