### ISSUE TITLE
Add & typegen deprecation flag for RPCs

### ISSUE THREAD

**Issue by athei** [polkadot-js/api#5241]
We will soon [remove the contract RPCs](https://github.com/paritytech/substrate/pull/12358) from substrate as their are redundant. Please consider removing or deprecating them here and pointing users to `state_call` instead.

**Comment by jacogr** [comment]
The API contract interfaces itself doesn't use them, it has been converted to state_call, see https://github.com/polkadot-js/api/pull/5107. 

Like any other RPC, they could be available or not available, so the API will just decorate the interfaces are existing on `rpc_methods`, if they are not available, they won't be decorated.

**Comment by athei** [comment]
Makes sense. However, I was hoping we could easily add some deprecation attribute there or something because they are not expected to be there going forward. Otherwise users might think they need to add them when in fact they should just use `state_call`. If they use this stuff directly instead of the abstraction.

**Comment by jacogr** [comment]
Can certainly add a deprecation attribute, but this is actually a massive undertaking with typegen and reworking the interfaces. So we are literally month outs (probably Q1 2023) before that can even be looked at, just judging by what is in the queue atm.

**Comment by jacogr** [comment]
In addition to contracts, this would also affect actual RPCs marked as depreecated, eg. `state_getPairs` (this obviously only helps TS & IDE developers, the rest won't see this marking at all)
