### ISSUE TITLE
Decoding StorageMap gives wrong result when ecdsa::Public is key

### ISSUE THREAD

**Issue by 1xstj** [polkadot-js/api#5247]
Type : Bug Report

Summary :
We have a [StorageMap](https://github.com/webb-tools/dkg-substrate/blob/c74aef79e47ad2c8010364db9d61e87c8b98ea1e/pallets/dkg-metadata/src/lib.rs#L467) in runtime in the following format
```rust
#[pallet::storage]
	#[pallet::getter(fn authority_reputations)]
	pub type AuthorityReputations<T: Config> =
		StorageMap<_, Blake2_256, T::DKGId, T::Reputation, ValueQuery>;
```
Here, `T::DKGId` is a type substitution for [ecdsa::Public](https://docs.rs/sp-application-crypto/latest/sp_application_crypto/ecdsa/struct.Public.html) key

When viewing the StorageMap in polkadotjs the keys are different than expected, when viewing the entire map it displays as below
<img width="1703" alt="Screenshot 2022-09-29 at 4 33 38 PM" src="https://user-images.githubusercontent.com/106580853/193032323-54c12a30-ce03-4be2-9215-b4750543d581.png">

```
[
  [
    [
      0x3f6eaf1be5add88d84ca8b02d350074935dbf04f53f4287cb6abfd6b33413f8f
    ]
    1,000,000,000
  ]
  [
    [
      0x6672035dd6010e55e08eb707d171b5ec790bfea44f93ea8b1d22503033de45cd
    ]
    1,000,000,000
  ]
]
```

Although on searching the key displayed in above image it returns empty
<img width="1725" alt="Screenshot 2022-09-29 at 4 34 45 PM" src="https://user-images.githubusercontent.com/106580853/193032567-b710d7b1-0fa6-4c82-8209-bb6308a1902a.png">

Searching with the expected key returns the correct value
```
0x0389411795514af1627765eceffcbd002719f031604fadd7d188e2dc585b4e1afb
```
<img width="1734" alt="Screenshot 2022-09-29 at 4 35 40 PM" src="https://user-images.githubusercontent.com/106580853/193032749-17fb2d4b-535f-4022-ad67-3e3b1f55e26b.png">

How to reproduce:

Query `dkg->AuthorityReputations` at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstandalone.webb.tools#/chainstate

Or Follow local setup instructions [here](https://github.com/webb-tools/dkg-substrate#-standalone-local-testnet-)

**Comment by jacogr** [comment]
Do you have a link to the Rust source as well? (It makes it easier to check alongside the actual endpoint, which is great having here)

**Comment by jacogr** [comment]
It is correctly decoded. Your actual storage entry is a one-way hash (you are using `Blake2`) so the value displayed is the hash or the key. If you want decodable identity information, you need to use something like `Blake2_128Concat`

When you are querying individually, it takes the non-hashed value and then hashes it. The UI above has no way to decode the 1-way blake2 hash.

So - 

`blake2(0x036aec5853fba2662f31ba89e859ac100daa6c58dc8fdaf0555565663f2b99f8f2) -> 0x6672035dd6010e55e08eb707d171b5ec790bfea44f93ea8b1d22503033de45cd)`

**Comment by 1xstj** [comment]
Makes sense. Thankyou
