### ISSUE TITLE
WsProvider not working in node v18

### ISSUE THREAD

**Issue by carlosala** [polkadot-js/api#5249]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Using node 18, this code doesn't work properly (I think the error is in the connect part).
In latest lts (node 16) works as expected.
```typescript
  const provider = new WsProvider(url, false)

  // do not try to reconnect forever if connection fails
  // instead of that we listen events on provider
  await new Promise<void>((res, rej) => {
    provider.on('disconnected', () => null)
    provider.on('error', () => {
      rej('error on ws provider connection')
    })
    provider.on('connected', () => {
      res()
    })

    provider.connect()
  })
```

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: `v18.10.0`
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version) `v4.8.4`
    - [ ] Other

**Comment by jacogr** [comment]
What does it do? What does it log?

**Comment by carlosala** [comment]
I was looking into it in a clean project. As soon as I get something I tell you :)

**Comment by carlosala** [comment]
I don't get any output, I just get undefineds when trying to retrieve the metadata, and it just happens to me when running a local node of cumulus (using, for example, parity nodes doesn't happen). I am trying it with `statemint-dev`
With node 16 lts everything is ok.

I am running the node with `./target/release/polkadot-parachain --chain statemint-dev --ws-port 9944 --unsafe-ws-external`

**Comment by carlosala** [comment]
Maybe this is an issue of this cumulus nodes, what bothers me is that with node16 everything works well.

**Comment by jacogr** [comment]
What is really weird (based on the info above), is that it doesn’t happen with the Parity nodes.

**Comment by carlosala** [comment]
Investigating, I discovered that `localhost` is not pointing properly to `127.0.0.1` in Node >18. Using `127.0.0.1` instead of `localhost` solves my issues, so there was no bug in your code!
Thanks @jacogr 😊
