### ISSUE TITLE
Unable to decoded storage system.events

### ISSUE THREAD

**Issue by chenzongxiong** [polkadot-js/api#5256]
We setup governance2 testnet, and try to query related records. However, we receive following exceptions.

![image](https://user-images.githubusercontent.com/8354165/193613156-d7ee0caf-577e-4104-aad8-a9853ca4dfff.png)

We depend on substrate's version: 

https://github.com/paritytech/substrate?branch=master#37664fe5b3513eb996225f016eceaf74963b8133

You can reproduce the error via the following endpoint
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fgovernance2-testnet.litentry.io%23%2Faccounts#/referenda

**Comment by jacogr** [comment]
WeightV2 won't be supported until the next API release.

**Comment by jacogr** [comment]
Since the above is for the apps UI, you can track it here - https://github.com/polkadot-js/apps/issues/8188
