### ISSUE TITLE
PolkadotJs 9.4 blockWeights is missing refTime

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#5258]
Since Polkadot runtimes 9290, Weight is a structure with "refTime" attribute in there.
It works well with previous version of PolkadotJS but after upgrading to PolkadotJs 9.4, the type of Weight is again a BN:

```
 const relayBaseExtrinsic = relayApiAt.consts.system.blockWeights.perClass.normal
      .baseExtrinsic as any;
 console.log(relayBaseExtrinsic.toHuman()); // 86,309,000 in version Polkadot 9.4.2
```

It worked in PolkadotJs 8.8.2:
```
 const relayBaseExtrinsic = relayApiAt.consts.system.blockWeights.perClass.normal
      .baseExtrinsic as any;
 console.log(relayBaseExtrinsic.toHuman()); // { refTime: '86,309,000' } in version Polkadot 8.8.2

```

**Comment by jacogr** [comment]
It has been fixed in master. Before that neither the API nor the apps UI supports Weight V2.

**Comment by crystalin** [comment]
Thank you for the update @jacogr , we will try to support it accordingly.
