### ISSUE TITLE
InvalidScheduleVersion

### ISSUE THREAD

**Issue by luozygithub** [polkadot-js/api#5268]
* **I'm submitting a ...**

  - [ 1] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**
Create an instance with the ContractPromise of @polkadot/api-contract to call the contract method.
Error :" InvalidScheduleVersion"

* **Please tell us about your environment:**

  - Version:
  - "ink! 3.0.0-rc5"
  -     "@polkadot/api": "v9.5.1",
    "@polkadot/api-contract": "^v9.5.1",
    "@polkadot/extension-dapp": "^0.44.5",
  - Environment:

Browser

  - Language:

    - JavaScript

**Comment by jacogr** [comment]
The error is returned from the runtime, see https://github.com/paritytech/substrate/blob/488fc24d98cfe643402b86990ae0aff27ba927b3/frame/contracts/src/lib.rs#L751-L754

**Comment by luozygithub** [comment]
supplied to 'seal_call' or 'seal_delegate_call'. What's the specific reason?

**Comment by luozygithub** [comment]
Can you say /// A new schedule must have a greater version than the current one? What's the specific reason?
