### ISSUE TITLE
Comparing similar type should be coherent or forbidden

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#5284]
I know it is bad practice to compare different types, but I think there should be a way to forbid comparing those types (like u32 and BN) or try to provide a coherent comparison (not relying on toString()):

```
> api.registry.createType("u32", 596) >= new BN(5078)
true
> api.registry.createType("u32", 596) >= new BN(7850)
false
```

**Comment by jacogr** [comment]
There is an `.eq(...)` on all Codec types.

**Comment by crystalin** [comment]
Yes, and those work well, but it often happens that someone not too familiar with the project will try direct comparison leading to errors. Isn't there a way to override the operator or forbid them for some type/class

**Comment by jacogr** [comment]
In JS you cannot quite do operator overloading, it is entirely up to the engine.
