### ISSUE TITLE
REGISTRY: Error: Unsupported extrinsic payload version 0 after upgrading polkadot-api

### ISSUE THREAD

**Issue by aserafin** [polkadot-js/api#5293]
I'm in the process of upgrading polkadot-js/api package from `8.0.2` to `9.6.1`. I have a test that accepts a serialized transaction payload generated with version `8.0.2`, creates a SignerPayload and calls `toRaw()` on it. It was working with the previous version of the library but after upgrade I'm getting an error

```
const payload = "0x0004000000000000000000e143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423ee143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e000000000000000000000000000000000000000000000000000000000000000000000000000400002ac76cbe42d32387665f4c7e69dd2ed446ccbc10903de0a7741d8f773958e8060700e87648171c77657374656e64387061726974792d77657374656e6402000000222400000000000038df6acb689907609b0400000037e397fc7c91f5e40100000040fe3ad401f8959a06000000d2bc9897eed08f1503000000f78b278be53f454c02000000af2c0297a23e6d3d0200000049eaaf1b548a0cb00100000091d5df18b0d2cf5801000000ed99c5acb25eedf503000000cbca25e39f14238702000000687ad44ad37f03c201000000ab3c0572291feb8b01000000bc9d89904f5b923f0100000037c8bb1350a9a2a8010000000b0000000004";

const signerPayload = api.createType("SignerPayload", this.payload);
const data = signerPayload.toRaw().data;
```

In the old version the result of `signerPayload.toPayload()` yields:

```
{
      specVersion: '0x00002422',
      transactionVersion: '0x0000000b',
      address: '5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM',
      blockHash: '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e',
      blockNumber: '0x00000000',
      era: '0x00',
      genesisHash: '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e',
      method: '0x0400002ac76cbe42d32387665f4c7e69dd2ed446ccbc10903de0a7741d8f773958e8060700e8764817',
      nonce: '0x00000001',
      signedExtensions: [],
      tip: '0x00000000000000000000000000000000',
      version: 4
    }
```

but in the new one everything is the same except the `version` property which yields 0:

```
{
      specVersion: '0x00002422',
      transactionVersion: '0x0000000b',
      address: '5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM',
      blockHash: '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e',
      blockNumber: '0x00000000',
      era: '0x00',
      genesisHash: '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e',
      method: '0x0400002ac76cbe42d32387665f4c7e69dd2ed446ccbc10903de0a7741d8f773958e8060700e8764817',
      nonce: '0x00000001',
      signedExtensions: [ '' ],
      tip: '0x00000000000000000000000000000000',
      version: 0
    }
```

Any idea why this is happening and how to fix it? 🤔

**Comment by jacogr** [comment]
The `SignerPayload` is dynamically created using the signed extensions. In the last version you have `signedExtensions: [ '' ],` which most-probably means that non-defaults are passed through in the registry?

**Comment by aserafin** [comment]
hmm... originally the signedExtensions are `[]` (empty array), with the new library they turned into `['']` (array with empty element)... I don't think I'm passing anything that's non-default 🤔 

To create the payload in the first place I'm using:

```
const { nonce } = await api.query.system.account(accountAddress);

  return api.createType('SignerPayload', {
    method: transaction,
    nonce,
    genesisHash: api.genesisHash,
    blockHash: api.genesisHash,
    runtimeVersion: api.runtimeVersion,
    version: api.extrinsicVersion,
  });
```

The `api` is created like this:

```
api = await web3.ApiPromise.create({ provider: new web3.WsProvider(rpcUrl), metadata });
```

**Comment by jacogr** [comment]
The extensions are extracted from the metadata itself, since you explicitly pass that through, ensure it is actually a full metadata object.

**Comment by aserafin** [comment]
hmm... I'll try fetching the metadata fresh but running this snippet in the apps UI console returns the same error I'm getting locally:

```
const payload = "0x0004000000000000000000e143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423ee143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e000000000000000000000000000000000000000000000000000000000000000000000000000400002ac76cbe42d32387665f4c7e69dd2ed446ccbc10903de0a7741d8f773958e8060700e87648171c77657374656e64387061726974792d77657374656e6402000000222400000000000038df6acb689907609b0400000037e397fc7c91f5e40100000040fe3ad401f8959a06000000d2bc9897eed08f1503000000f78b278be53f454c02000000af2c0297a23e6d3d0200000049eaaf1b548a0cb00100000091d5df18b0d2cf5801000000ed99c5acb25eedf503000000cbca25e39f14238702000000687ad44ad37f03c201000000ab3c0572291feb8b01000000bc9d89904f5b923f0100000037c8bb1350a9a2a8010000000b0000000004";
const signerPayload = api.createType("SignerPayload", payload);
console.log(signerPayload.toRaw().data);
```

**Comment by aserafin** [comment]
Also just calling this in the UI console:

```
console.log(api.createType("SignerPayload").version);
```

yields `0` 🤔

**Comment by aserafin** [comment]
> The extensions are extracted from the metadata itself, since you explicitly pass that through, ensure it is actually a full metadata object.

I'm storing the metadata in cache for tests (aka it's mocked and passed directly), so it doesn't changed between running the tests with `8.0.2` and `9.6.1`

**Comment by aserafin** [comment]
Also was able to narrow it down to a single version change polkadot-js library: 

- up until 8.10.1 the tests passes
- starting 8.11.1 the test fails

I'm not that familiar with polkadot-js/api source code but maybe it'll help narrow it down? 🤔

**Comment by jacogr** [comment]
Yes, `console.log(api.createType("SignerPayload").version);` will yield 0 (nothing is passed in, so it is the default value for that type)

**Comment by aserafin** [comment]
> Which chain is this for?
It's for westend

**Comment by jacogr** [comment]
The change between 8.10 and 8.11 is aligning the `RuntimeVersion` structure to the latest.

This means that the format of the structure has changed (it includes an extra field in the struct), so previous versions of the hex value would not match anymore, aka would look different. The API here tries to decode an old (serialized) structure into a new one.

**Comment by jacogr** [comment]
Here is an updated hex value with the extra byte - `0x0004000000000000000000e143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423ee143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e000000000000000000000000000000000000000000000000000000000000000000000000000400002ac76cbe42d32387665f4c7e69dd2ed446ccbc10903de0a7741d8f773958e8060700e87648171c77657374656e64387061726974792d77657374656e6402000000222400000000000038df6acb689907609b0400000037e397fc7c91f5e40100000040fe3ad401f8959a06000000d2bc9897eed08f1503000000f78b278be53f454c02000000af2c0297a23e6d3d0200000049eaaf1b548a0cb00100000091d5df18b0d2cf5801000000ed99c5acb25eedf503000000cbca25e39f14238702000000687ad44ad37f03c201000000ab3c0572291feb8b01000000bc9d89904f5b923f0100000037c8bb1350a9a2a8010000000b000000000004`

**Comment by aserafin** [comment]
ahh... thank you! 👏 🙇 

Is there a recommended way to transform old value into the current-gen compatible one?

**Comment by aserafin** [comment]
gotcha... in my setup it's quite a real option that payload would be generated with one version of the library and then got consumed with other (independent systems generate and consume the payloads, hex representation is used for transport); 

from what you wrote there is no clear way to either:

- on the consumer side know it's an incompatible version
- transform the old one to the new one

is that correct? 🤔
