### ISSUE TITLE
Statemine block 1,006,328 events can not be decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5301]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Please check this link: 

![K3yKqkfa8c](https://user-images.githubusercontent.com/2264908/198334556-47395452-1c12-4ca1-82a7-8abb01bf6512.jpg)

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
This will be a tough one, the Statemine types are quite light - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/statemint.ts
