### ISSUE TITLE
`PalletDemocracyVoteAccountVote` does not work as expected

### ISSUE THREAD

**Issue by carlosala** [polkadot-js/api#5308]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I am trying to define a type to create a blob for `democracy.vote` in Polkadot.
This method takes two arguments, a `Compact<u32>` and a `PalletDemocracyVoteAccountVote`.
This is the code I am using to create the `PalletDemocracyVoteAccountVote`:
```typescript
metadata.api.createType('PalletDemocracyVoteAccountVote', {
  Standard: {
    vote: {
      aye: true,
      conviction: "None",
    },
    balance: metadata.api.createType('u128', randomAsU8a(16)),
  },
}),
```
I also tried:
```typescript
metadata.api.createType('PalletDemocracyVoteAccountVote', {
  Standard: {
    aye: true,
    conviction: "None",
    balance: metadata.api.createType('u128', randomAsU8a(16)),
  },
}),
```
```typescript
metadata.api.createType('PalletDemocracyVoteAccountVote', {
  Standard: {
    vote: 0x80,
    balance: metadata.api.createType('u128', randomAsU8a(16)),
  },
}),
```

Then, when I do `type.asStandard` I have two fields, `vote` and `balance`. But `type.asStandard.vote` is `0x00`. I get this `0x00` for everything not depending what I input in `aye` and `conviction` fields.

* **What is the motivation for changing the behavior?**

To be able to properly generate `vote` types.

* **Please tell us about your environment:**

  - Version: `9.6.2`
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version) `v4.8.4`
    - [ ] Other

**Comment by jacogr** [comment]
In the apps UI in the JS console -

```js
const vote = api.createType('PalletDemocracyVoteAccountVote', {
  Standard: {
    vote: {
      aye: true,
      conviction: 'None'
    },
    balance: 12345
  }
});

console.log(JSON.stringify(vote.asStandard.toHuman(), null, 2))
```

with the above code -

```
{
  "vote": {
    "conviction": "None",
    "vote": "Aye"
  },
  "balance": "12,345"
}
```

with `aye: false` and `conviction: 'Locked1x' -

```
{
  "vote": {
    "conviction": "Locked1x",
    "vote": "Nay"
  },
  "balance": "12,345"
}
```
```
```

**Comment by carlosala** [comment]
Thanks Jaco, I discovered my error.
I'll keep you posted for whatever. Thanks!!!
