### ISSUE TITLE
Version 9.6.2 Error, Uncaught NodeError Error [ERR_PACKAGE_PATH_NOT_EXPORTED]:

### ISSUE THREAD

**Issue by rajqumar** [polkadot-js/api#5309]
After upgrading polkadot version, I am getting this error
`Uncaught NodeError Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cjs/packageInfo' is not defined by "exports" in node_modules/@polkadot/networks/package.json`

Output for `npm show @polkadot/types-known` is shared below

@polkadot/types-known@9.6.2 | Apache-2.0 | deps: 6 | versions: 1715
Known type definitions
https://github.com/polkadot-js/api/tree/master/packages/types-known#readme

dist
.tarball: https://registry.npmjs.org/@polkadot/types-known/-/types-known-9.6.2.tgz
.shasum: b109763dea97cadde453d38dde1cdd4586f9ae11
.integrity: sha512-dekLSTr6CoukKAJezQ83Dn9ggOTRrRSMZr19Wi8NLJCTkbTzNCyFSMmQuwG1XxYWwTgjfqMLUVmInkLSxzDNSA==
.unpackedSize: 222.0 kB

dependencies:
@babel/runtime: ^7.20.0       @polkadot/types-codec: 9.6.2  @polkadot/types: 9.6.2        
@polkadot/networks: ^10.1.11  @polkadot/types-create: 9.6.2 @polkadot/util: ^10.1.11      

dist-tags:
beta: 8.14.2-12  latest: 9.6.2

**Comment by jacogr** [comment]
Weird. There has been no build adjustments in a very long time. Do you have a minimal sample that shows this error?

**Comment by jacogr** [comment]
The other question - which version of node are you using?
