### ISSUE TITLE
How to add custom derives?

### ISSUE THREAD

**Issue by ntn-x2** [polkadot-js/api#5315]
I was browsing in the codebase, but I could not get a full picture of what one is supposed to do if they want to provide custom derives to their api-augmented object. Documentation is very poor, and everything seems to be so "runtimey" and flexible that it's hard to look at and replicated.
Our use case is the following: given some sort of ID, we want to 1. perform a query to fetch some details, 2. use the information about the block number returned from the query to perform an` api.derive.getBlockByNumber` call, and then retrieve some info from the block and return it from the user.

This ideally would be solved with a `api.derive.credential.fetchById()`, which does all I mentioned above. Otherwise, one has to do `api.query.credentials.fetch()`, and then some more logic that, in the end, calls `api.derive.getBlockByNumber`.

Is there a way to get support in what we want to do?

**Comment by jacogr** [comment]
Yes, everything is driven by the runtime. Yes, code documentation is lacking, there are only x hours a day and only 7 days a week, a lot of repos and 1 dev.

See https://github.com/polkadot-js/api/blob/8883d355ffab8e30e7967e424a3cfa8f66fcf0c6/packages/api/src/types/index.ts#L42

An example here where a user of the apps UI injects their own derives https://github.com/polkadot-js/apps/blob/66f778e3fb1714b78366c634e0e6869379b61387/packages/apps-config/src/api/spec/interbtc.ts#L43-L72

(Most users in the apps UI do it via the types bundle, e.g.

```js
Api.create({
  provider: ....
  typesBundle: {
    spec: {
      chainNameHere: {
        derives: {...} // as above, just localized to a chain, instead of for all
        types: {...}  
      }
    }
  }
})
```

**Comment by ntn-x2** [comment]
Yeah I understand the lack of resources.. Anyway, I **did** get this far, but I was just not sure about few things:

1. Why do we have to use rxjs for declaring them? Why can't we use promises?
2. How do these custom derives play with TS augmentation? Are they also augmented?

**Comment by jacogr** [comment]
Internally the API uses rxjs, and this then gets exposed both rxjs and promise variants of the API. Since derives are "internal interfaces" it fits into the same process, creating them exposes them on all type of APIs.

There is no augmentation for derives.

**Comment by ntn-x2** [comment]
Thank you very much. Any plans to support derives in the augmented TS types as well?

**Comment by jacogr** [comment]
None at all. 

PRs are welcome for [additions/support](https://github.com/polkadot-js/api/tree/master/packages/typegen) if this would be useful. (Alternatively you can log it as an request to get it in the queue)

**Comment by ntn-x2** [comment]
Don't have bandwidth right now, but where can I log it as a request?

**Comment by jacogr** [comment]
https://github.com/polkadot-js/api/issues

I would not expect a speedy resolution (unless somebody submits a PR), but at least it gets it into the queue to be done at "some point in the future".

**Comment by ntn-x2** [comment]
So as a test, I have the following:

```ts
export function getCredential(
  instanceId: string,
  api: ApiInterfaceRx
): () => Observable<null> {
  return memo(instanceId, (): Observable<null> => {
    return of(null)
  })
}

export const derives: DeriveCustom = {
  publicCredentials: {
    getCredential,
  },
}
```

In the `index.ts` I then do:

```ts
export const typesBundle: OverrideBundleType = {
  chain: {
    'KILT Spiritnet': {
      runtime: {
        ...didCalls,
        ...parachainStakingCalls,
        ...publicCredentialsCalls,
      },
      derives: {
        ...publicCredentialsDerives,
      },
      types: defaultTypesBundle,
    },
...
```

But I still can't see the `publicCredentials` property for the `api.derive` object. What am I missing?
