### ISSUE TITLE
React Native: undefined is not a function (near '...window.addEventListener…')

### ISSUE THREAD

**Issue by tzechuen** [polkadot-js/api#5316]
![Simulator Screen Shot - iPhone 14 - 2022-11-04 at 12 28 37](https://user-images.githubusercontent.com/4160142/199887679-00b2c82d-29c0-4d64-aafa-9220ad466cac.png)

Hi, I tried updating my Polkadot JS libraries but after updating to the latest, I'm getting this error as above when running on React Native iOS.

My package.json has:

```
    "@polkadot/api": "^9.6.2",
    "@polkadot/extension-chains": "^0.44.6",
    "@polkadot/extension-inject": "^0.44.6",
    "@polkadot/keyring": "^10.1.11",
    "@polkadot/util": "^10.1.11",
    "@polkadot/util-crypto": "^10.1.11",
    "@polkadot/wasm-crypto": "^6.3.1",
```

Previously this configuration worked for me:

```
    "@polkadot/api": "~8.13.1",
    "@polkadot/extension-chains": "^0.44.3",
    "@polkadot/extension-inject": "^0.44.3",
    "@polkadot/keyring": "^10.1.2",
    "@polkadot/util": "^10.1.2",
    "@polkadot/util-crypto": "^10.1.2",
    "@polkadot/wasm-crypto": "^6.3.1",
```

The error seems to suggest that the library is trying to make function calls that are only available on the browser. I'm assuming this could be something that was added in `@polkadot/api` v9?

Assistance is much appreciated, thanks!

**Comment by jacogr** [comment]
Ummm, this _seems_ related to the `ScProvider` which is exported by default in the API now. Will have to look at the compiled code to see what assumptions are made here.

cc @wirednkod 

PS: I said _seems_ related, would need to look at what the compiled code shows, just going against what is shown above

**Comment by jacogr** [comment]
The full code there from `@substrate/connect` is the following -

```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createScClient = void 0;
const types_js_1 = require("./types.js");
const index_js_1 = require("./specs/index.js");
const listeners = new Map();
if (typeof window === "object") {
    window.addEventListener("message", ({ data }) => {
        var _a;
        if ((data === null || data === void 0 ? void 0 : data.origin) !== "substrate-connect-extension")
            return;
        (_a = listeners.get(data.chainId)) === null || _a === void 0 ? void 0 : _a(data);
    });
}
function getRandomChainId() {
    const arr = new BigUint64Array(2);
    // It can only be used from the browser, so this is fine.
    crypto.getRandomValues(arr);
    const result = (arr[1] << BigInt(64)) | arr[0];
    return result.toString(36);
}
```

Cannot see anything wrong in there.

**Comment by jacogr** [comment]
It would actually seem that it doesn't like the use of `require` in this context, judging by the line & `undefined is not a function`.

**Comment by wirednkod** [comment]
> It would actually seem that it doesn't like the use of `require` in this context, judging by the line & `undefined is not a function`, which in turn seems to point to the RN bundling itself.

Never tried ScProvider with Native React but based on Jaco's research it seems like an RN bundling case, rather an issue with ScProvider. Will try to have a better look and create a sample example of RN. Will get back to you in case something different.

**Comment by tzechuen** [comment]
Hey guys, just wanted to check in and see if there are any updates on this? Thanks!

**Comment by jacogr** [comment]
No updates. Like mentioned above the error seems to come from your bundler itself. There are no code changes that I can make to change anything on this as it manifests.

1. The api only has a third-party dependency on `@substrate/connect`
2. Where it throws an error, it is certainly valid Javascript

Happy to make changes if it sits in the polkadot-js repos and code I can actually affect. (And well, understand what the issue is, RN has always been quite difficult to get to the bottom of)
