### ISSUE TITLE
derive package not accessible via api.at(...)

### ISSUE THREAD

**Issue by gabrieljaegerde** [polkadot-js/api#5319]
* **I'm submitting a ...**

  - [x] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

I am not sure whether this is by design or indeed a bug.

* **What is the current behavior and expected behavior?**

I would like to query all democracy locks for a given account at a given block.

The api-derive package has a perfect function for this: 
`const userLocks = await api.derive.democracy.locks(vote.accountId)`

Currently it seems impossible to combine the above call with a blockApi:

```
const blockApi = await api.at(blockHash)
const userLocks = await blockApi.derive.democracy.locks(vote.accountId)
```

The above does not work as blockApi.derive is not defined. This is because the returned type of api.at() is **not** ApiPromise.

* **What is the motivation for changing the behavior?**

Currently there seems to be no way to make use of the derive package through a blockApi. I am curious whether this has a technical reason and is indeed by design or a use-case merely has not come up yet until now that would justify the integration.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
This won’t be added. The derives only work on current state - basically to do this would mean to redo everything to do queries at a specific block.
