### ISSUE TITLE
Do we need to do library updates?

### ISSUE THREAD

**Issue by mone-d** [polkadot-js/api#5322]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

The following release notes indicated that a runtime upgrade was in the works.
(https://github.com/paritytech/polkadot/releases/tag/v0.9.31)
The content of the upgrade is that the weight version will be changed.
In the past, the api became unusable due to the weight version change. 
(https://github.com/polkadot-js/api/issues/5292)
**I would like to know if this runtime upgrade will cause any problems with 9.6.1 that we are currently using.**
Supplementary note: We believe it is okay because the release notes for api do not state that an update is required.

* **What is the motivation for changing the behavior?**
Nothing.

* **Please tell us about your environment:**

  - Version: 9.6.1
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
9.6.1 is indeed fine with the latest Weights V2. (It contains the last minor tweak for full support for this version)

The Weights 1 -> 1.5 -> 2 unfortunately did require updates to the packages (some users were very outdated), the same applies to runtime developers on Rust are well, this was quite an intrusive change with wide ranging breakages (all for the right runtime reasons).

Looking at the release notes are indeed the best approach, I understand (from feedback) that sometimes it can be a bit cryptic, so certainly want to do better with those going forward.
