### ISSUE TITLE
encoding numbers when calling toJSON()

### ISSUE THREAD

**Issue by aserafin** [polkadot-js/api#5323]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When calling `toJSON` the numbers seem to be represented differently depending of whether they fit into JS Number range or not. For example this code:

```
const account = await api.query.system.account(accountAddress);
console.log(account.toJSON())
```

will return "integers" for account with small balance

```
{
	"account": {
		"nonce": 16,
		"consumers": 2,
		"providers": 1,
		"sufficients": 0,
		"data": {
			"free": 2757764139956,
			"reserved": 1003700000000,
			"miscFrozen": 1000000000000,
			"feeFrozen": 1000000000000
		}
	}
}
```
but hex for account with higher balance:

```
{
	"account": {
		"nonce": 37,
		"consumers": 2,
		"providers": 1,
		"sufficients": 0,
		"data": {
			"free": "0x00000000000000000950c9eceee7f1b7",
			"reserved": 0,
			"miscFrozen": "0x0000000000000000094445d76238256c",
			"feeFrozen": "0x0000000000000000094445d76238256c"
		}
	}
}
```

It makes it tricky to consume this data by some other service since it'll have to be aware of the above and parse the response accordingly 🤔  

Would it make more sense to represent numbers as strings when calling toJSON()? Have "1003700000000" instead of 1003700000000 and "671258363935846839" instead of "0x00000000000000000950c9eceee7f1b7"?

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
`toJSON` is for the RPC services. The encoding there is what makes sense for that environment, i.e. when making any RPC requests, the output from `toJSON` is passed through. So it is very specific to catering for the nuances of the Substrate JSONRPC interface.

If you wish to consume by something else, `toPrimitive` _may_ makes sense for you (strings, numbers).

**Comment by aserafin** [comment]
gotcha - thank you for clarifying 👍
