### ISSUE TITLE
Update docs to reflect unsubscribe() function return

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#533]
Based on this https://github.com/polkadot-js/api/pull/527/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR1 for api/promise -

- Update in-code samples
- Update actual docs/examples samples

**Comment by jacogr** [comment]
And it is now a `Promise<UnsubFunction>` after #572

**Comment by Stefie** [comment]
Yup, I did something similar in my branch. I just added it to the 'Listen to blocks' example.
https://github.com/polkadot-js/api/blob/sd-569-docs-add-and-fix-apirx-examples/docs/examples/promise/02_listen_to_blocks/index.js

**Comment by Stefie** [comment]
@jacogr and you don't really need the async/await in the ApiPromise example since you're awaiting for `const subscription` already. For ApiPromise `subscription` itself is the unsubscribe function `() => subscription.unsubscribe()`

**Comment by jacogr** [comment]
100%, there is an extra await in there.

**Comment by Stefie** [comment]
Fixed with PR #600
