### ISSUE TITLE
Missing `RuntimeDispatchInfoV1` for `rpc.payment.queryInfo` following upgrade to polkadot-v0.9.32

### ISSUE THREAD

**Issue by gdethier** [polkadot-js/api#5339]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

`rpc.payment.queryInfo(...)` and `SubmittableExtrinsic.paymentInfo(...)` are both returning a `RuntimeDispatchInfo` object. However, since [this change](https://github.com/paritytech/substrate/pull/12633), `rpc.payment.queryInfo` always returns a `RuntimeDispatchInfo` with a V1 weight while `SubmittableExtrinsic.paymentInfo` may return a `RuntimeDispatchInfo` with a V2 weight (with a recent runtime). Without any custom definition, this leads to decoding issues when calling `rpc.payment.queryInfo`.

Therefore, an additional return type (e.g. `RuntimeDispatchInfoV1`) could be defined and returned by `rpc.payment.queryInfo` while  `SubmittableExtrinsic.paymentInfo` would continue to return current `RuntimeDispatchInfo`.

[This commit](https://github.com/logion-network/logion-api/commit/5808c8828d947b4cbe75ae10bfe3e97210929b98) illustrates how we worked around the problem. In summary:
1. Add a new definition for `RuntimeDispatchInfoV1` (identical to `RuntimeDispatchInfo` but always using `WeightV1` for `weight` field)
2. Use the new type in RPC augments
3. Customize the RPC object passed to `ApiPromise.create` so that `rpc.payment.queryInfo` returns a `RuntimeDispatchInfoV1`

* **What is the motivation for changing the behavior?**

Be able to use both `rpc.payment.queryInfo` and `SubmittableExtrinsic.paymentInfo` in any case.

* **Please tell us about your environment:**

  - Version: @polkadot/api 9.8.1 | @polkadot/typegen 9.8.1
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [x] TypeScript 4.7.4
    - [ ] Other

**Comment by jacogr** [comment]
Why are you using the actual RPCs and not the runtime calls? (See the comments in the linked PR, the RPCs will be deprecated. There are a couple of reasons -

- duplication of functionality
- RPCs won't be added to metadata (so it will always be a manual sync with types), runtime call interfaces will be added
- you have versioning (albeit primitive) on runtime calls
- all middleware need to keep updated and it is quite a challenge when things change along the way

**Comment by gdethier** [comment]
We are not directly calling the RPCs in our code, it seems to come from polkadot-js/api itself. Here is an example of stack trace I get without the workaround described above:

```
backend1_1            | 2022-11-16 16:15:24 error: createType(RuntimeDispatchInfo):: Struct: failed on weight: {"refTime":"Lookup9","proofSize":"Lookup9"}:: Struct: Cannot decode value 166860000 (typeof number), expected an input object, map or array 
backend1_1            | 2022-11-16 16:15:24 error: Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: {"refTime":"Lookup9","proofSize":"Lookup9"}:: Struct: Cannot decode value 166860000 (typeof number), expected an input object, map or array
backend1_1            |     at createTypeUnsafe (/usr/share/logion-backend/node_modules/@polkadot/types-create/cjs/create/type.js:67:18)
backend1_1            |     at TypeRegistry.createTypeUnsafe (/usr/share/logion-backend/node_modules/@polkadot/types/cjs/create/registry.js:295:46)
backend1_1            |     at RpcCore._formatOutput (/usr/share/logion-backend/node_modules/@polkadot/rpc-core/cjs/bundle.js:381:21)
backend1_1            |     at RpcCore._formatResult (/usr/share/logion-backend/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)
backend1_1            |     at callWithRegistry (/usr/share/logion-backend/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)
```

**Comment by gdethier** [comment]
@jacogr I overlooked the part about RPC calls becoming deprecated, thanks! We'll switch asap. And thanks also for the PR, just had a look, it should indeed solve the issue.

**Comment by jacogr** [comment]
Additionally, it is quite difficult to support all the different RPCs (including those that are custom) on light clients. 

So Substrate devs certainly want to start steering people away from using them (obviously when there are runtime options). This applies to a lot of RPCs, for instance in contracts all RPCs are already deprecated (since there are runtime interfaces).

But anyway, your report was certainly an oversight in not reading the PR line-by-line, a patch will go out for it.
