### ISSUE TITLE
 RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.

### ISSUE THREAD

**Issue by rkhomyshyn** [polkadot-js/api#5340]
Hey there, I am having an issue with getting `partialFee` by next call:
`api.rpc.payment.queryInfo(extrinsic.toJSON(), transactionBlock.block.header.hash)` on westend rpc. 

The error is next: _RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.: Failed to decode return value of TransactionPaymentApi_query_info_.

I am using latest version of api lib `9.8.1`, also tried with older version. But the error is the same.

Is it know issue? could you suggest something to prevent the error?

Thank you.

**Comment by jacogr** [comment]
That would be returned from the actual RPC node. Basically it means that the RPC node and the runtime version is mismatched - the native node code needs to have the same version and the runtime to decode the response.

**Comment by rkhomyshyn** [comment]
@jacogr - thank you for the response. Can I specify version when creating request to rpc?

**Comment by jacogr** [comment]
RPCs are non-versioned - it just communicates with the runtime.

Your actual best approach (specifically in light of the fact that the RPC you are using will be deprecated in the future), is to rather use `api.call.transactionPaymentApi.queryInfo` - that is direct to the runtime.

The parameters are the same, however it doesn't accept a hash (unlike an RPC), in that case rather use `api.at(<blackHash>)` and then that to do the runtime call.

**Comment by rkhomyshyn** [comment]
@jacogr - thank you again. 
I tried you suggestion, but got next error in version `9.6.2`:
 _Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known), TransactionPaymentCallApi/2 (1 known)_

and for latest version (`9.8.1`) empty error message.

**Comment by jacogr** [comment]
9.6.2 doesn't yet know about `TransactionPaymentApi/2` - it went into Substrate last week Wednesday.

**Comment by rkhomyshyn** [comment]
it looks like it was needed to pass additional parameter to `queryInfo` method and after it starts work in `9.8.1`
```
const at = await api.at(transactionBlock.block.header.hash);
const info = await at.call.transactionPaymentApi.queryInfo(extrinsic.toJSON(), 0);
return res.send({
    fee: info.partialFee // but now can not take a partialFee from info, should it be casted to RuntimeDispatchInfo?
});
```
