### ISSUE TITLE
Is there an official substrate-based chain-list with chain-ids within polkadot-js?

### ISSUE THREAD

**Issue by wottpal** [polkadot-js/api#5345]
Hey!

From the EVM-ecosystem, I was used to having an official chain ID for every chain (e.g. `1` for Ethereum Mainnet, `137` for Polygon, etc.). See the following repositories/files on GitHub for reference:
* https://github.com/DefiLlama/chainlist/blob/main/constants/chainIds.js
* https://github.com/wagmi-dev/wagmi/blob/cabba6a6fd68a25bdfcaf47a19b4b34ffb4d83bb/packages/core/src/constants/chains.ts#L21

**Is there something equivalent for Substrate-based chains?** I'm asking here because I assume you have something like this in `polkadot-js` already somewhere. I'm currently building a boilerplate for dynamic multi-chain usage, and something like this would come in handy, otherwise, I would have to define inofficial IDs myself. The only things I could find via search:
* https://github.com/polkadot-js/build-bundle/blob/231c37d3c97bf9baaf493aa23ee8a037ca549e6c/bundle-polkadot-hw-ledger.js#L597 (is `cla` meant to be an identifier? but unfortunately, there are testnets missing)
* I also found this by subscan, but also without uint IDs: https://github.com/subscan-explorer/network-runtime-check/blob/17ffba30ff5941aad225f81fd1e44f470516c24e/conf/config.yaml

ty in advance

**Comment by jacogr** [comment]
This is not Ethereum, so there is no chain id.

There is the ss58 prefixes that can be used for address encoding, see https://github.com/paritytech/ss58-registry

**Comment by wottpal** [comment]
Thank you for the reference to `ss58-registry`, really appreciated! I probably have to use network string identifiers to be also able to separate testnets from each other, but that's not a big deal. I just wanted to make sure I don't miss out on anything :) 

ty
