### ISSUE TITLE
Allow to optionnally load substrate-connect

### ISSUE THREAD

**Issue by jeluard** [polkadot-js/api#5359]
- [ ] Bug report
- [x] Feature request
- [ ] Support request
- [ ] Other

* **What is the current behavior and expected behavior?**

PolkadotJS API bundles `substrate-connect` which itself embeds a number of `wasm` files. Using `parcel` bundler those are not removed and the overall size is 3M+. Depending on the the target environment/platform, this can be problematic.

* **What is the motivation for changing the behavior?**

Ideally it would be possible to load `substrate-connect` only when needed, allowing to have a smooth user experience.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jeluard** [comment]
Right it [does](https://parceljs.org/features/production/#tree-shaking), and I'm using the latest parcel release.

Any suggestion about how I could investigate that? My usage of PolkadotJS API is [fairly](https://github.com/jeluard/swipealot/blob/main/src/utils/democracy.ts) [small](https://github.com/jeluard/swipealot/blob/main/src/utils/polkadot-api.ts) so far.

**Comment by jacogr** [comment]
That is a really nice small usage.

 I'm no expert, but quickly dug through the docs (from where you pointed) and it may be [worthwhile](https://parceljs.org/features/scope-hoisting/#avoiding-bail-outs) running with `parcel build src/app.html --log-level verbose`
 
 If you possibly attach those can have a starting point to see how to adjust here. (There is obviously even a bigger worry for me - if it missing that, it possibly misses others as well, so certainly want to have things in a shape where bundlers can operate optimally)

**Comment by jeluard** [comment]
Thanks for putting me on the right track! I could identify a couple problematic dependencies that disable parcel tree-shaking.
There are still some left though, some related to some `@polkadot/common` libs. You can see some more details [here](https://gist.github.com/jeluard/c6698fb0db88807ad548644a6ff8a209).

Note that I have to use `--no-scope-hoist` [arg(https://parceljs.org/features/cli/#parameters-specific-to-build)] to parcel because of the following error (although it's not obvious to me what it is):

```js
@parcel/optimizer-terser: Private field must be used in an enclosing class

    55373 |    */ get defKeys() {
  > 55374 |         return this.#Types[1];
  >       |                    ^ Private field must be used in an enclosing class
    55375 |     }
    55376 |     /**

  💡 It's likely that Terser doesn't support this syntax yet.
```

The other messages related to tree-shaking disabling are still present though when `--no-scope-hoist` is not used.

**Comment by jacogr** [comment]
The above log is interesting - some deps are pulled in as ESM and some as CJS. This is very weird.

**Comment by jacogr** [comment]
Added a PR that would address my second comment above. 

For the Parcel-ignoring-exports-field, there is really not much I can do. The main/module/browser fields are added specifically for older bundlers - we cannot change "browser" to point to ESM files since that will make others break, so it is a bit of a catch-22. So it is a bit "ugly", however those problematic packages are exceptionally tiny, so there are actually nothing to really tree-shake in them.

**Comment by jeluard** [comment]
Thanks for looking into this!

Unfortunately I understand that those `Unknown usage of CommonJS `exports` object.` actually disable the whole tree-shaking, not just for those particular modules.

Hopefully `parcel` will address this issue at some point.

**Comment by jacogr** [comment]
Ahhh, ok, If it disabled tree-shaking completely... I hate saying this, but in that case you can use the parcel alias. (As per the parcel issue). So something like (in package.json) -

```json
"alias": {
  "@polkadot/x-fetch": "./node_modules/@polkadot/x-fetch/browser.js",
  "@polkadot/x-ws": "./node_modules/@polkadot/x-ws/browser.js",
  "@polkadot/x-textencoder": "./node_modules/@polkadot/x-textencoder/browser.js",
  "@polkadot/x-textdecoder": "./node_modules/@polkadot/x-textdecoder/browser.js"
}
```

**Comment by jeluard** [comment]
Nice! It actually solved the issue for the `@polkadot` packages, but the issue is still there for some other packages (e.g. `bn.js`).
I guess I'll have to wait for some parcel improvements, it's hard to believe that tree-shaking can only work when all modules are ESM.

**Comment by jeluard** [comment]
Some feedback: with latest API version, the previous warning related to `buffer` and `process` have disappeared.

There is still one thing that forces to load the `buffer` shim:

```js
@parcel/resolver-default: Auto installing polyfill for Node builtin module "buffer"...

  /Users/julien/Documents/Projects/jeluard/swipealot/node_modules/@polkadot/util/is/buffer.js:23:66
    22 |   // we do check a function first, since it is slightly faster than isBuffer itself
  > 23 |   return hasBuffer && isFunction(value && value.readDoubleLE) && Buffer.isBuffer(value);
  >    |                                                                  ^^^^^^ used here
    24 | }

  📝 Learn more: https://parceljs.org/features/node-emulation/#polyfilling-%26-excluding-builtin-node-modules
```
