### ISSUE TITLE
Node stopped working when injecting 100 transactions into one block

### ISSUE THREAD

**Issue by xfylsj** [polkadot-js/api#536]
Hi Polkadot and Substrate team, we're trying to test how many transactions can be handled in one block, and encountered the **'block production took too long**'  issue when injecting 100 transactions:

![image](https://user-images.githubusercontent.com/31326993/50742260-77abe500-126d-11e9-8a42-c3afabb0300f.png)

I'm running a single node network on my local machine (Macbook Pro 2017, Mac OS High Sierra)

We believe the block can handle more than 100 transaction. 

Could you please advise us how to fix the issue? Thanks a lot.

**Comment by jacogr** [comment]
Thanks for reporting. The best place to report Node-specific issues is at https://github.com/paritytech/substrate/issues - this one seems directly related to the Node and not the actual JS API layer.

**Comment by xfylsj** [comment]
Got it. Thanks.
