### ISSUE TITLE
Typegen generates types that don't exist within @polkadot/types or @polkadot/types-codec

### ISSUE THREAD

**Issue by forgetso** [polkadot-js/api#5362]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

I am using typegen to generate types for a contract. Some of the types in the contract are `Mapping` and `Timestamp` and these are correctly populated in the output types.ts file but they are not imported from polkadot bundles.

```
import type { Enum, Struct, Vec, u128, u16, u32, u64 } from '@polkadot/types-codec'
import type { AccountId, Balance, Hash } from '@polkadot/types/interfaces/runtime'

/** @name Commitment */
export interface Commitment extends Struct {
    readonly contract: AccountId
    readonly provider: AccountId
    readonly completed_at: Timestamp // not present in imports and causes a TS error
}

export interface Commitments extends Mapping {}  // not present in imports and causes a TS error

```

* **Please tell us about your environment:**

  - Version: @polkadot/api@8.14.1
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version `Version 4.9.3`)
    - [ ] Other

**Comment by jacogr** [comment]
For a contract? I know there is a long-running issue on contracts ABI generation, but not sure I ever got around to generating for contracts - only f on on-chain metadata. 

Which commands do you use to generate this?

**Comment by forgetso** [comment]
Hi Jaco, I generated the [definitions file](https://github.com/prosopo/contract/blob/5a45e6beb319d807f0eb132fa2d54202f0dc0838/src/interfaces/prosopo.ts) using my [contract ABI json](https://github.com/prosopo/contract/blob/5a45e6beb319d807f0eb132fa2d54202f0dc0838/src/abi/prosopo.json) and [a script I wrote](https://github.com/prosopo/contract/blob/5a45e6beb319d807f0eb132fa2d54202f0dc0838/src/util/definitionGen.ts). I then used the typegen commands to generate the types

```
    "generate:defs": "ts-node --skip-project ../../node_modules/.bin/polkadot-types-from-defs --package @prosopo/contract/interfaces --input ./src/interfaces --endpoint ./metadata.json",
    "generate:meta": "ts-node --skip-project ../../node_modules/.bin/polkadot-types-from-chain --package @prosopo/contract/interfaces --endpoint ./metadata.json --output ./src/interfaces"
  },
```

**Comment by forgetso** [comment]
I realise I can probably use `Vec<u8>` in the definitions file for `Timestamp` as this is [how its defined in ink](https://github.com/paritytech/ink/blob/e883ce5088553c93b49493e43185ce05485399d3/crates/engine/src/ext.rs#L399).

Should [`Mapping`](https://github.com/paritytech/ink/blob/78c05df6c474ed3eb6f3d0c7bcf8e777e8a0dcb8/crates/storage/src/lazy/mapping.rs#L84) be renamed to [`Map`](https://github.com/polkadot-js/api/blob/6cdbbf5372277ae8dc1da26e669678977890bdf2/packages/types-codec/src/extended/Map.ts) for polkadot-js typegen?
