### ISSUE TITLE
Inconsistent number formatting returned from transaction events and queries

### ISSUE THREAD

**Issue by forgetso** [polkadot-js/api#5365]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently, when I perform a query and a transaction that return the same information from a contract, they both return different number formats, making comparisons difficult. The query reads the contract storage and the transaction emits the data as part of an event.

#### Transaction Event

```
{
  args: [
    Type(32) [Uint8Array] [
      16,
      33,
      161,
      180,
      195,
      214,
      98,
      158,
      224,
      98,
      29,
      41,
      47,
      176,
      103,
      172,
      27,
      170,
      124,
      208,
      142,
      95,
      61,
      174,
      119,
      108,
      248,
      206,
      223,
      23,
      126,
      103,
      registry: TypeRegistry {},
      initialU8aLength: 32
    ],
    <BN: de0b6b3a764000a>
  ],
  event: {
    args: [ [Object], [Object] ],
    docs: [],
    fromU8a: [Function: fromU8a],
    identifier: 'DappFund',
    index: 10
  }
}
```

```
console.log(
    'TEST',
    events[0].args.map((arg) => [arg.toHuman(), arg.toString()])
)

TEST [
  [
    '5CRrcZmm7v8or2TJqfNybEFCs979R5r5jTw3AYnKqgB8kbXL',
    '5CRrcZmm7v8or2TJqfNybEFCs979R5r5jTw3AYnKqgB8kbXL'
  ],
  [ '1.0000 MUnit', '1000000000000000010' ]  // Note the number notation here
]
```
#### Query Read returning Struct from contract

When I perform a query that returns the same data from the contract, I receive a number containing commas.

```
dappStruct {
  status: 'Active',
  balance: '1,000,000,000,000,000,010',  // number contains commas
  owner: '5CdNQTdiQn4VokmcSx9XoFKVfjv8mRa7x7Uw147uQbV45aue',
  minDifficulty: '1',
  clientOrigin: '0x00000000000000687474703a2f2f6c6f63616c686f73743a3078653164663562'
}

/** @name Dapp */
export interface Dapp extends Struct {
    readonly status: GovernanceStatus
    readonly balance: u128
    readonly owner: AccountId
    readonly minDifficulty: u16
    readonly clientOrigin: Hash
}
```

Creating a u128 for comparison fails because of the commas

```
console.log(new u128(env.api.registry, dappStruct.balance))

     Error: String should not contain decimal points or scientific notation

```

* **What is the motivation for changing the behavior?**

I'm not sure where the problem lies, whether in substrate or polkadot-js but the returned number formats should be consistent and ideally without commas, for easier parsing or creation of BigInts.

* **Please tell us about your environment:**

  - Version: polkadot-js 8.14.1
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (tsc --version 4.9.3)
    - [ ] Other

**Comment by jacogr** [comment]
`toHuman()` is for display-only, not for machine consumption. (Hence the `human` part of the name).

**Comment by forgetso** [comment]
Yes, I tried to use `toBn` but it didn't work, complaining with `TypeError: dappStruct.balance.toBn is not a function
`. I'm not sure why this happens since balance is a `u128` and `toBn` seems to exist on `AbstractInt`.

**Comment by forgetso** [comment]
Ah, my bad, I had converted the query result `toHuman` already which is why I was getting the commas in the number. I can simply compare the data before the conversion and it will work.

**Comment by forgetso** [comment]
Thanks. I've changed my code simply to return the encoded type and I create the type myself using:

```
// create the type from the raw data
const dapp = createType(mockEnv.api.registry, 'ProsopoDapp', dappStruct.toU8a())
console.log(dapp.toHuman())

{
  Ok: {
    status: 'Active',
    balance: '1,000,000,000,000,000,010',
    owner: '5EuFxjpQbkkwhgDFujr1mgZRZbfoamo4D48jMaRKcqxMsDjp',
    minDifficulty: '1',
    clientOrigin: '0x00000000000000687474703a2f2f6c6f63616c686f73743a3078666530336336'
  }
}

```

Now when I compare my two Big Numbers I get very similar results:

```
// compare the result of the event balance to the struct balance
console.log(events![0].args[1], dapp.balance)
// event balance                 // contract query balance from struct above
<BN: de0b6b3a764000a> <BN: de0b6b3a764000a00>
```

Note the struct balance has `00` appended to the end, making it a different number when I do `toPrimitive`.

```
console.log(events![0].args[1].toPrimitive(), dapp.balance.toPrimitive())
1000000000000000010 256000000000000002560
```

But I've already shown that the balance is `'1,000,000,000,000,000,010',` as per the result of `toHuman` of my struct above. Why is the balance different when queried by key (`dapp.balance`)? Is it something to do with the `Ok` wrapper around the struct?

**Comment by forgetso** [comment]
Ok, so one is a `Balance` and the other is ` u128` and doing `eq` on them with `BN` class does not work.

```
console.log(events![0].args[1].toRawType(), dapp.balance.toRawType())
Balance u128

console.log(events![0].args[1].eq(dapp.balance))
false
```

**Comment by forgetso** [comment]
Essentially, the question is:

Given the following struct called `dapp`, which correctly shows the balance using `isHuman`:

```
console.log(dappStruct.toHuman())
{
  Ok: {
    status: 'Active',
    balance: '1,000,000,000,000,000,000',
    owner: '5FQM1SAuDGwejthytHUkCG4WQFbkqE24rNVf851XZHCCKHjg',
    minDifficulty: '1',
    clientOrigin: '0x00000000000000687474703a2f2f6c6f63616c686f73743a3078373465666663'
  }
}
```

How do I get `dapp.balance` to print out `1000000000000000000`?

```
        console.log(dappOriginal.balance.toPrimitive())
        console.log(dappOriginal.balance.toHuman())
        console.log(dappOriginal.balance.toBigInt())
        console.log(dappOriginal.balance.toString())

256000000000000000000
256,000,000,000,000,000,000
256000000000000000000n
256000000000000000000

```

**Comment by forgetso** [comment]
It seems this issue came from encoding the `Dapp` type twice. The API returned the `Dapp` type and then I did

`const dapp = createType(mockEnv.api.registry, 'ProsopoDapp', dappStruct.toU8a())`

which seems to have caused the multiplication of everything inside by 256
