### ISSUE TITLE
Add Support for ChargeAssetTxPayment

### ISSUE THREAD

**Issue by marshacb** [polkadot-js/api#5367]
* **I'm submitting a ...**

  - [ ] Bug report
  - [X] Feature request
  - [X] Support request
  - [] Other

* **What is the current behavior and expected behavior?**

Currently, when constructing a transaction in `txwrapper-core` we create a type called `UnsignedTransaction` which extends `SignerPayloadJSON` from the `types` package in `polkadotjs/api` and contains all fields needed for a transaction. 

```
export interface SignerPayloadJSON {
    /**
     * @description The ss-58 encoded address
     */
    address: string;
    /**
     * @description The checkpoint hash of the block, in hex
     */
    blockHash: string;
    /**
     * @description The checkpoint block number, in hex
     */
    blockNumber: string;
    /**
     * @description The era for this transaction, in hex
     */
    era: string;
    /**
     * @description The genesis hash of the chain, in hex
     */
    genesisHash: string;
    /**
     * @description The encoded method (with arguments) in hex
     */
    method: string;
    /**
     * @description The nonce for this transaction, in hex
     */
    nonce: string;
    /**
     * @description The current spec version for the runtime
     */
    specVersion: string;
    /**
     * @description The tip for this transaction, in hex
     */
    tip: string;
    /**
     * @description The current transaction version for the runtime
     */
    transactionVersion: string;
    /**
     * @description The applicable signed extensions for this runtime
     */
    signedExtensions: string[];
    /**
     * @description The version of the extrinsic we are dealing with
     */
    version: number;
}
```
```
/**
 * JSON format for an unsigned transaction.
 */
export interface UnsignedTransaction extends SignerPayloadJSON {
  /**
  * The SCALE-encoded metadata, as a hex string. Can be retrieved via the RPC
  * call `state_getMetadata`.
  */
  metadataRpc: `0x${string}`;
  }
```

I would like to implement support for constructing a transaction using the signedExtension `ChargeAssetTxPayment`

```
/// Require the transactor pay for themselves and maybe include a tip to gain additional priority
/// in the queue. Allows paying via both `Currency` as well as `fungibles::Balanced`.
///
/// Wraps the transaction logic in [`pallet_transaction_payment`] and extends it with assets.
/// An asset id of `None` falls back to the underlying transaction payment via the native currency.
#[derive(Encode, Decode, Clone, Eq, PartialEq, TypeInfo)]
#[scale_info(skip_type_params(T))]
pub struct ChargeAssetTxPayment<T: Config> {
	#[codec(compact)]
	tip: BalanceOf<T>,
	asset_id: Option<ChargeAssetIdOf<T>>,
}
```

`ChargeAssetTxPayment` consists of an `asset_id` and a `tip`. `SignerPayloadJSON` doesn’t have an `assetId` field and therefore when constructing our `UnsignedTransaction` type we are currently unable to provide an `assetId` field/value in order to use the `ChargeAssetTxPayment` signedExtension.

We use the `UnsignedTransaction` when we create a signing payload:

```
export function createSigningPayload(
	unsigned: UnsignedTransaction,
	options: Options
): string {
	const { registry } = options;

	return registry
		.createType('ExtrinsicPayload', unsigned, {
			version: unsigned.version,
		})
		.toHex();
}
```
Here we also find that `GenericExtrinsicPayload` (which `ExtrinsicPayload` extends) doesn't support `assetId` and we'd like to add it:

```
export interface ExtrinsicPayloadValue {
  blockHash: AnyU8a;
  era: AnyU8a | IExtrinsicEra;
  genesisHash: AnyU8a;
  method: AnyU8a | IMethod<AnyTuple>;
  nonce: AnyNumber;
  specVersion: AnyNumber;
  tip: AnyNumber;
  transactionVersion: AnyNumber;
  assetId?: AnyNumber;
}
```

```
export declare class GenericExtrinsicPayload extends AbstractBase<ExtrinsicPayloadVx> {
    constructor(registry: Registry, value?: Partial<ExtrinsicPayloadValue> | Uint8Array | string, { version }?: ExtrinsicPayloadOptions);
    /**
     * @description The block [[BlockHash]] the signature applies to (mortal/immortal)
     */
    get blockHash(): BlockHash;
    /**
     * @description The [[ExtrinsicEra]]
     */
    get era(): GenericExtrinsicEra;
    /**
     * @description The genesis block [[BlockHash]] the signature applies to
     */
    get genesisHash(): BlockHash;
    /**
     * @description The [[Bytes]] contained in the payload
     */
    get method(): Bytes;
    /**
     * @description The [[Index]]
     */
    get nonce(): ICompact<INumber>;
    /**
     * @description The specVersion as a [[u32]] for this payload
     */
    get specVersion(): INumber;
    /**
     * @description The [[Balance]]
     */
    get tip(): ICompact<INumber>;
    /**
     * @description The transaction version as a [[u32]] for this payload
     */
    get transactionVersion(): INumber;
    /**
     * @description Compares the value of the input to see if there is a match
     */
    eq(other?: unknown): boolean;
    /**
     * @description Sign the payload with the keypair
     */
    sign(signerPair: IKeyringPair): {
        signature: HexString;
    };
    /**
     * @description Converts the Object to to a human-friendly JSON, with additional fields, expansion and formatting of information
     */
    toHuman(isExtended?: boolean): AnyJson;
    /**
     * @description Converts the Object to JSON, typically used for RPC transfers
     */
    toJSON(): any;
    /**
     * @description Returns the string representation of the value
     */
    toString(): string;
    /**
     * @description Returns a serialized u8a form
     */
    toU8a(isBare?: BareOpts): Uint8Array;
}
```

* **What is the motivation for changing the behavior?**

I would like to extend `SignerPayloadJSON` as well as the `GenericExtrinsicPayload` to support the optional `assetId` field/getter for the purpose of constructing transactions that use sufficient assets to pay for fees.

In order to do so and properly test changes alongside `txwrapper-core`, I would like to know if there is a recommended way of using our local `polkadotjs` as a dependency during our development?(linking our local `polkadotjs` to `txwrapper-core`).

In addition, what is the best way to add tests for these changes in `polkadotjs`?

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (tsc --version 4.8.3)
    - [ ] Other

**Comment by jacogr** [comment]
So first things first - the payload interfaces are mostly from the days when we had non-metadata-defined, mostly-static signed extensions. So in that case it always tried have getters for all the signed extensions. In a modern world this doesn't work - a lot of these are dynamic and optional based on chain.

With that in mind, the inner classes for the payloads will always expose what is in the extensions. See -

```js
import { ApiPromise, WsProvider } from '@polkadot/api';

async function main () {
	const api = await ApiPromise.create({
		provider: new WsProvider('wss://statemine-rpc.polkadot.io')
	});
	const payload = api.registry.createType('ExtrinsicPayload', { assetId: 1234 });

	console.log(payload.toHuman());
	console.log(payload.inner.assetId.toHuman());
}

main().catch(console.error);
```

For both logs above the `assetId` is `1234` as passed. So there is no need for a wrapper since the inner Struct (like all structs), will dynamically expose the getters that are available on the signed extensions. (All the getters there _should_ be removed since the types will be inconsistent with what is on-chain, in the runtime - they should only rely on the dynamic addition. Currently it is a static/dynamic mix. Same applies to `SignerPayload`)

So for any optional fields where it should be added as new extensions come into play -

- on the signer interfaces in [SignerOptions](https://github.com/polkadot-js/api/blob/083e4594073a66921342b1931f0c7535c2d20b1a/packages/api-base/src/types/submittable.ts#L19) (available there so any signing operation can pass through)
- payload values in [SignatureOptions](https://github.com/polkadot-js/api/blob/083e4594073a66921342b1931f0c7535c2d20b1a/packages/types/src/types/extrinsic.ts#L166) (also available, same reasoning as above)

All the rest should drop all these getters since they are at best inconsistent with what is actually on-chain.

**Comment by IkerAlus** [comment]
Do we have a time estimate for this feature? Users of the API are making this a requirement to support certain services.

**Comment by marshacb** [comment]
> PS: Where there is a slight discrepancy (which can only be fixed by not using `Base`, but rather using `Enum` for the payload wrapper) is that it is not entirely obvious that `ExtrinsicPayload` is actually a versioned wrapper, the data really only sites on the inner, not the outer.

Thanks Jaco! I followed the code example of passing `assetId` into `createType` and can see that the correct `assetId` value is logged as well. I'll continue working on this and update after I complete testing using a sufficient asset.

**Comment by marshacb** [comment]
closed by: https://github.com/paritytech/txwrapper-core/pull/275
