### ISSUE TITLE
Type generation error for nested tuples: `Unable to extract location of ';'`

### ISSUE THREAD

**Issue by sander2** [polkadot-js/api#5383]
We have a storage type that has a key of type `((CurrencyId, CurrencyId), AccountId)`, i.e. it is a nested tuple. Type generation fails here: https://github.com/polkadot-js/api/blob/5cb6cf0a0034fccc992b182b8ebc7bc82a6b7eac/packages/types-create/src/util/getTypeDef.ts#L148

What seems to be happening is that [this code](https://github.com/polkadot-js/api/blob/7b5b8745a2af68f365987caccd922d01c813304f/packages/typegen/src/generate/query.ts#L44) creates the following `similarTypes`:
```
similarTypes[0][0]:
'ITuple<[ITuple<[InterbtcPrimitivesCurrencyId, InterbtcPrimitivesCurrencyId]>, AccountId32]>'
similarTypes[0][1]:
'[ITuple<[InterbtcPrimitivesCurrencyId, InterbtcPrimitivesCurrencyId]> | [InterbtcPrimitivesCurrencyId | { Token: any } | { ForeignAsset: any } | { LendToken: any } | { LpToken: any } | { StableLpToken: any } | string | Uint8Array, InterbtcPrimitivesCurrencyId | { Token: any } | { ForeignAsset: any } | { LendToken: any } | { LpToken: any } | { StableLpToken: any } | string | Uint8Array], AccountId32 | string | Uint8Array]'
```

Note the second item, which has the form `[value1, value2, value3]`. When [setImports](https://github.com/polkadot-js/api/blob/7b5b8745a2af68f365987caccd922d01c813304f/packages/typegen/src/generate/query.ts#L48-L56) is then called, `getTypeDef` gets called on that type, which calls `decodeFixedVec`, which expects something of the form `[type; len]` so the error above is thrown (note the `;` instead of a `,`).

**Comment by bvotteler** [comment]
> What seems to be happening is that [this code](https://github.com/polkadot-js/api/blob/7b5b8745a2af68f365987caccd922d01c813304f/packages/typegen/src/generate/query.ts#L44) creates the following `similarTypes`

To add some context, it seems like the [recursive handling](https://github.com/polkadot-js/api/blob/5c6294b71ca758749419dfe3456f1fca5502246f/packages/typegen/src/util/derived.ts#L118-L128) inside `api/derived.ts` `getSimilarTypes` method might play a significant factor.

**Comment by bvotteler** [comment]
> Ummm, this is a weird one. (And strange we have not run into it before). Do you have a chain where we can generate a metadata bundle from to test against (i.e. either via curl or RPC call)

It's not live yet, but here's the json file obtained from `state_getMetadata`
https://github.com/interlay/interbtc-api/blob/505b93f1ddf1acc4b43c353955b7c8b66b5a8320/src/json/parachain.json

**Comment by jacogr** [comment]
Brilliant, the json link is exactly what is needed.

**Comment by bvotteler** [comment]
> it depends where it throws the error

It throws while generating `augment-api-query.ts` via `ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --package <pacakge_name> --endpoint <provided_parachain.json> --output <output_folder>`

**Comment by jacogr** [comment]
Closing on the back of #5395 - please comment if there are still issues.
