### ISSUE TITLE
ContractCallOutcome gasConsumed and gasRequired type should be changed to WeightV2

### ISSUE THREAD

**Issue by niklabh** [polkadot-js/api#5385]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

ContractCallOutcome.gasConsumed and ContractCallOutcome.gasRequired type should be changed to WeightV2.

* **What is the motivation for changing the behavior?**

For weightV2 chains gasConsumed and gasRequired are returned as WeightV2 containing refTime and proofSize values. Currently they are not accessible with type Weight.

* **Please tell us about your environment:**

Shibuya Parachain.

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The api will detect and decorate the `Weight` type based on what is available on-chain. So for WeightV1, it will be V1 types, alternatively V2.
