### ISSUE TITLE
Expose block height on extrinsic results

### ISSUE THREAD

**Issue by ken-centrality** [polkadot-js/api#5393]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

> Currently, on extrinsic result, we can get `blockHash`, `txHash` and `txIndex` but not `blockHeight`

* **What is the motivation for changing the behavior?**

> In our apps, we log the extrinsic's block height for auditing and analytics purposes. With the current setup, we would have to do another RPC call `api.rpc.chain.getBlock` to retrieve the block height. If you are happy, we can submit a PR following the same principle as https://github.com/polkadot-js/api/pull/4556 to add `blockHeight` to the extrinsic results

* **Please tell us about your environment:**

  - Version: 9.9.1
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
PRs welcome. 

If you follow the linked PR you will notice that as part of the event derive the block is retrieved. So it would be possible to extract the number from the block -> header
