### ISSUE TITLE
How to get referendum data / image from proposal hash?

### ISSUE THREAD

**Issue by oblak1** [polkadot-js/api#5397]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm using polkadot api where I'm trying to query all referendums from kusama chain and their data. AFAIK the referendums are created based on passed proposals. What I do not understand is:

1. I cannot query any relevant data for historic referendums (only for active) - is there any way to get the tally votes/threshold etc. for every referendum either by using `derived functions` or `query.democracy.referendumInfoOf`? I tried using api.at before the voting ended but I don't get all the relevant data.
2. How to get the relevant preimage data from proposal_hash? I tried using `api.derive.democracy.preimage` using proposal_hash but it's just not working (getting null)
3. Looking at [subscan's 258 referenda](https://kusama.subscan.io/referenda/258?tab=proposal_preimage) they also have a topic. but I cannot find a field in the metadata which would indicate this was taken from rpc. I would imagine this was taken from another website (polkassembly)?

* **Please tell us about your environment:**

  - Version:  polkadot/api: 9.10.2
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
1. `api.at` before the voting ended would yield the result
2. preimages are removed when the referendum is enacted - the derive function would not return anything (since derives only operate on current state). In this case, also use `api.at` at the block before it ended.
3. There is no topic in the state.

**Comment by oblak1** [comment]
Thank you for the reply.

For 2., I tried doing it like this:

```
const img = api.query.preimage.preimageFor(
    '0x8ac3f722caf7677254e25ca4ad77d533ca893c7d2ad4009e258d749f2004ef94'
  );
```
where 0x8ac... is the proposal hash of this still ongoing [referenda](https://kusama.subscan.io/referenda/258) but I always get a null response. I also tried api.at for earlier blocks, nothing different. What am I doing wrong?
