### ISSUE TITLE
Your runtime does not expose the api.call.contractsApi.call runtime interfaces

### ISSUE THREAD

**Issue by deuszx** [polkadot-js/api#5400]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

After upgrading network to WeightsV2, my frontend code started to fail with the following errors
```
Uncaught (in promise) Error: Your runtime does not expose the api.call.contractsApi.call runtime interfaces
    at new Base (Base.js:13:1)
    at new Contract (Contract.js:33:1)
    at new ContractPromise (index.js:18:1)
    at getPostsAuthors (getPostsAuthors.ts:18:1)
    at async getAllPostsAuthors (BulletinBoard.tsx:51:1)
```
[link](https://github.com/Cardinal-Cryptography/bulletin-board-example/tree/ink4) to the repository.

* **Please tell us about your environment:**

1. Network running ink3, contracts deployed, custom frontend (built with polkadot.js) working.
2. Network migrated to ink4, contracts deployed, custom frontend (built with polkadot.js) not working.
3. ContractsUI connected to that same network capable of interacting with the contracts and the chain.

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (`"typescript": "^4.8.4"`)
    - [ ] Other

**Comment by jacogr** [comment]
It literally means what it says - the chain you are connecting to does not expose the runtime interfaces required. It either means -

(a) it is a non-contract chain (e.g. Polkadot/Kusama/etc - a chain explicitly needs to have the contracts pallet included in the on-chain runtime)
(b) it is an old version of the chain without the newer runtime interfaces (unlikely)

**Comment by deuszx** [comment]
Yes, I saw the `Base.ts`. My setup:
1. The contracts and fronted were correct with ink3
2. Network has been migrated to ink4
3. Deployment and interactions with the contracts work through the ContractsUI

Given that:
* on ink3 it used to work with polkadotjs and ContractsUI
* on ink3 it stopped working with polkadotjs and continues working with ContractsUI

**Comment by deuszx** [comment]
I think I've found the reason why it keeps working with ContractsUI https://github.com/paritytech/substrate/pull/12358

**Comment by deuszx** [comment]
My chain is exposing that interface though @jacogr , see https://github.com/Cardinal-Cryptography/aleph-node/blob/main/bin/runtime/src/lib.rs#L924

**Comment by jacogr** [comment]
Yes, the RPCs are completely unused since they are deprecated/removed in Substrate. So the API only uses the state call interfaces directly.

**Comment by deuszx** [comment]
Tell me, please, if I get the exact same error when running `substrate-contracts-node` from https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.22.1 and
```
"@polkadot/api": "^9.11.1",
"@polkadot/api-contract": "^9.11.1",
```
Wouldn't that mean it's not the problem with my chain but the library?

**Comment by deuszx** [comment]
@jacogr , turns out that the error was caused by invalid version of npm -- failed on `npm @ 9.1.1` but is "working" on `8.19.3`.
