### ISSUE TITLE
Cannot use from within a service-worker 

### ISSUE THREAD

**Issue by jeluard** [polkadot-js/api#5403]
- [ ] Bug report
- [x] Feature request
- [ ] Support request
- [ ] Other

* **What is the current behavior and expected behavior?**

PolkadotJS API cannot be used inside a Service Worker as dynamic imports [can't be used](https://web.dev/es-modules-in-sw/#static-imports-only) there. Dynamic imports are indirectly used by substrate-connect (see issue [there](https://github.com/paritytech/substrate-connect/issues/1371)).

While discussing the `substrate-connect` issue, @wirednkod suggested that PolkadotJS API should not depend directly on `substrate-connect`. This would solve this issue short term, allowing PolkadotJS API to be used in Service Worker. Ultimately it would be great to be able to use substrate-connect inside SW too.

Relates to #5359

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jeluard** [comment]
In this case looks like parcel detects the unsupported dynamic import before attempting to do any kind of tree shaking. It happens in development too.

> (PS: I missed your last comment on the linked issue, however addressed that specific parcel issue that you still had with Buffer - https://github.com/polkadot-js/common/pull/1701)

Cool, thanks!

**Comment by jacogr** [comment]
Thanks for the clarification - yes, I suppose that is a sane approach since the bundle otherwise would need to get itself into knots trying to figure out who/what/where.

**Comment by jeluard** [comment]
Wow great for the quick improvement! I will comment later on how it goes on my side.

**Comment by jacogr** [comment]
Will make a new release tomorrow with the latest of everything included.

**Comment by jeluard** [comment]
I can confirm that it now works perfectly. Thanks again @jacogr !
