### ISSUE TITLE
Ease WsProvider extensibility

### ISSUE THREAD

**Issue by jeluard** [polkadot-js/api#5408]
- [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

`WsProvider` has a built-in non-extensible retry logic. While useful on its own, some more advanced scenario could be enabled if `WsProvider` extensibility was enhanced.

* **What is the motivation for changing the behavior?**

I am working on implementing a more advanced reconnection mechanism for `WsProvider`. Ideally such an extended WsProvider could track current performance and initiate a connection to a new endpoint of its choosing.
It appears to me that the `WsProvider` class could be made a little more accessible to facilitate that task.

Would you be open for a PR going in that direction?

Specifically, some ideas I have in mind:

* expose the `endpoint` currently used
* allow subclasses/external entities to consume per endpoint stats (via emitter -perf impact?- or user provided interface))
* make the `endpoint` selection mechanism overrideable (and have default implementation be the current one)

I don't expect that this would bring any breaking changes.

**Comment by jeluard** [comment]
@jacogr Any thoughts about that?

**Comment by jeluard** [comment]
@jacogr any interest in this idea and the associated PR I would propose?

**Comment by jacogr** [comment]
It has been logged previously for health detection, see https://github.com/polkadot-js/api/issues/4237

So would ensure that we combine this into that and cover grounds.
