### ISSUE TITLE
Parachain onboarding fails with polkadot-v0.9.33

### ISSUE THREAD

**Issue by Chengcheng-S** [polkadot-js/api#5411]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
When I start relaychain and parachain using polkadot-v0.9.33 binary, I call the `parasSudoWrapper.sudoScheduleParaInitialize` interface using ts code, but it shows registration as parathread.  can only manually call `slots.frocelease`  This parachain can produce blocks normally. 
But There is no such problem with polkadot-v0.9.32, please is caused by the upgrade `parasSudoWrapper.sudoScheduleParaInitialize` interface? 
relate issue https://github.com/litentry/litentry-parachain/issues/1097
BTW, calling  `parasSudoWrapper.sudoScheduleParaInitialize`  via polkadot-js UI works.

* **Please tell us about your environment:**
OS: ubuntu 22.04
Rust-toolchain: 
~# rustc -V
rustc 1.66.0 (69f9c33d7 2022-12-12)
~# cargo -V
cargo 1.66.0 (d65d197ad 2022-11-15)
~# node --version
v16.19.0
~# yarn -v
1.22.19
polkadot-api version v.9.10.1

  - Version: 
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Not sure why this is marked as 

(a) a bug
(b) API related

At best this is a support request that deals with the runtime itself.
