### ISSUE TITLE
Drain pending requests on `.disconnect()`

### ISSUE THREAD

**Issue by polymath-eric** [polkadot-js/api#5420]
* **I'm submitting a ...**

  - [ ] Bug report
  - [X] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When calling `ApiBase.disconnect()` it should wait for pending requests to finish before closing.

I am using `ApiPromise`. When calling `disconnect` any pending request gets rejected with:

```
1000:: Normal connection closure
```

I was expecting after `disconnect()` is called, new requests will be rejected, but pending requests are given a grace period to complete, and then `disconnect()` resolves.

I can work around not having the requests drain on disconnect, but I have spent a while figuring out how to do so cleanly without a delay.

* **What is the motivation for changing the behavior?**

Before calling disconnect I want to ensure pending requests are complete. I am able to track them in my code, although its a bit tedious.

* **Please tell us about your environment:**

This is for a JS library that should work in the browser and Node.

```sh
tsc --version
Version 4.3.5
```

  - Version:
  - Environment:

    - [X] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Thanks for the detail. Happy to enhance, however not quite sure I "100% get what to do".

So basically when you `disconnect()` it closes the `WebSocket` connection.

- any pending requests won't/can't be sent
- any existing requests won't/can't get more data

Maybe if you provide a small sample of how/where and how you may/could work-around it would be a great place to start. (And obviously, if so inclined, PRs are always welcome to scratch the itch)

**Comment by polymath-eric** [comment]
@jacogr Thanks for the quick response.

My workaround is essentially is to keep a counter and increment when a request is sent, and decrement in a `.finally` on the request. I wait for that to be 0 before calling disconnect.

It would be nice to have the requests drain in the library, but I can see the case for the current behavior being OK.

**Comment by polymath-eric** [comment]
I am not too familiar with the code, but looking deeper at the source, and it seems like there was a previous PR that deliberately rejects the pending requests.

https://github.com/polkadot-js/api/pull/3197/files#diff-871752a27c655476527379eacbc4f66b71eb08a5bb1639acbcf8e380c57cda6cR355

I am going to close the current behavior seems intentional

Again, thanks for the response.
