### ISSUE TITLE
Encoding on Signing payload different from what recieved on node.

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/api#5431]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
The transaction payload that is being signed on the browser side is different from the payload actually sent. On the browser side it has one less bit. Here is what I did to create and sign on browser:

I am initializing the API with custom signed extensions..
```js
                let signedExtensions = {
                    AssetsTransactionPayment:{
                        extrinsic: {
                            asset_id: 'u128',
                            tip: 'Balance',
                            signature_scheme:'u8',
                        },
                        payload: {}
                    }
                }
                const provider= new WsProvider("ws://127.0.0.1:9944")

                // await injector.metadata.provide({userExtensions:signedExtensions})
                const api = await ApiPromise.create({provider,signedExtensions})
```    
I am calling a simple remark extrinsic like this.
```js
                const apiTx = api.tx.system.remark('esqAtwszqNAFdyCQRQmCLCgWNP4zWLXVY4h7siAaRTgD4JvRw')
                const signer = new mySigner({signer:signerHelper})
                apiTx.signAndSend(substrateAdder,
                    {
                        signer:signer,
                        asset_id:"1",
                        tip:"1",
                        signature_scheme:"1"
                    },
```

I created a custom signer for signing the API.  and when I print the extrinsic payload this is what is shown.

```js
                const signerHelper = async (signingPayload) => {
                    const extrinsicPayload = api.registry.createType('ExtrinsicPayload', signingPayload, { version: signingPayload.version});
                    let u8a = extrinsicPayload.toU8a({method:true});
                    let encoded = u8a.length > 256 ? api.registry.hash(u8a) : u8a;
                    console.log("encoded= ", encoded)
```
The console log shows values (length is 160)
```
encoded = Uint8Array(160) [0, 1, 196, 101, 115, 113, 65, 116, 119, 115, 122, 113, 78, 65, 70, 100, 121, 67, 81, 82, 81, 109, 67, 76, 67, 103, 87, 78, 80, 52, 122, 87, 76, 88, 86, 89, 52, 104, 55, 115, 105, 65, 97, 82, 84, 103, 68, 52, 74, 118, 82, 119, 4, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 24, 1, 0, 0, 2, 0, 0, 0, 6, 167, 247, 150, 101, 219, 67, 210, 31, 79, 173, 139, 58, 221, 84, 75, 92, 231, 190, 184, 151, 212, 83, 207, 94, 94, 112, 181, 92, 43, 40, 101, 203, 91, 166, 233, 224, 140, 123, 102, 248, 34, 45, 167, 96, 169, 7, 33, 109, 153, 20, 241, 29, 38, 193, 30, 246, 120, 251, 207, 40, 80, 191, 151]
```

This `signingPayload`is:
```js
{
    "asset_id": "0x00000000000000000000000000000001",
    "signature_scheme": "0x01",
    "specVersion": "0x00000118",
    "transactionVersion": "0x00000002",
    "address": "esmaKDoKGSS287oqtbDuBzQdmK1ohNCcJbJkjCgLrszKzFVcP",
    "blockHash": "0xe033381970e6fdf01c8765f2d0e59c66436cef974f0a06e882159a52af688c42",
    "blockNumber": "0x000000c6",
    "era": "0x6400",
    "genesisHash": "0x06a7f79665db43d21f4fad8b3add544b5ce7beb897d453cf5e5e70b55c2b2865",
    "method": "0x0001c4657371417477737a714e41466479435152516d434c4367574e50347a574c5856593468377369416152546744344a765277",
    "nonce": "0x00000000",
    "signedExtensions": [
        "CheckSpecVersion",
        "CheckTxVersion",
        "CheckGenesis",
        "CheckMortality",
        "CheckNonce",
        "CheckWeight",
        "AssetsTransactionPayment"
    ],
    "tip": "0x00000000000000000000000000000001",
    "version": 4
}
```
The extrinsicPayload.toJSON() give back:
```js
{
    "method": "0x0001c4657371417477737a714e41466479435152516d434c4367574e50347a574c5856593468377369416152546744344a765277",
    "era": {
        "MortalEra": {
            "period": "32",
            "phase": "16"
        }
    },
    "nonce": "0",
    "asset_id": "1",
    "tip": "1.0000 pUnit",
    "signature_scheme": "1",
    "specVersion": "280",
    "transactionVersion": "2",
    "genesisHash": "0x06a7f79665db43d21f4fad8b3add544b5ce7beb897d453cf5e5e70b55c2b2865",
    "blockHash": "0xcb5ba6e9e08c7b66f8222da760a907216d9914f11d26c11ef678fbcf2850bf97"
}
```
which does have all the fields of the custom signed Extensions created.

On the node side, the payload I get is almost the same, but it has one bit extra. And that last bit seems to show the signature_scheme field on the signedExtension as when I change the signature_scheme value, that last bit also changes accordingly

on node side (length is 161):
```
 [0, 1, 196, 101, 115, 113, 65, 116, 119, 115, 122, 113, 78, 65, 70, 100, 121, 67, 81, 82, 81, 109, 67, 76, 67, 103, 87, 78, 80, 52, 122, 87, 76, 88, 86, 89, 52, 104, 55, 115, 105, 65, 97, 82, 84, 103, 68, 52, 74, 118, 82, 119, 4, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 24, 1, 0, 0, 2, 0, 0, 0, 6, 167, 247, 150, 101, 219, 67, 210, 31, 79, 173, 139, 58, 221, 84, 75, 92, 231, 190, 184, 151, 212, 83, 207, 94, 94, 112, 181, 92, 43, 40, 101, 203, 91, 166, 233, 224, 140, 123, 102, 248, 34, 45, 167, 96, 169, 7, 33, 109, 153, 20, 241, 29, 38, 193, 30, 246, 120, 251, 207, 40, 80, 191, 151, 1]
``` 
I cant exactly figure out why the `extrinsicPayload.toU8a({method:true})` not adding this extra bit. Any help here will be appreciated..

**Comment by jacogr** [comment]
`method: true` encodes the payload directly for signing, i.e. the `method` is not length prefixed - this is signable but not decodable. (Without passing the flag, the payload has the length prefix for the method which means it is decodable, but not signable)

**Comment by nuel77** [comment]
@jacogr thanks for the response.  So i am using the `{method:true}` to get the u8 representation and sign it. But when log the received payload on the substrate-node side, it has an extra element as I mentioned on my issue. Why is this extra bit not there on the u8 representation given by `extrinsicPayload.toU8a({method:true})`

**Comment by jacogr** [comment]
If there is a bug in the encoding, it would mean that that API cannot send any transactions since the payload mismatch would mean that the signatures don't match and therefore no transactions would ever be succesfull.

**Comment by nuel77** [comment]
> 

The signatures are not matching right now. If I let the payload go through it is giving a `bad signature` error. It's only if I remove the extra bit which was added will the signature pass.

ie, right now on the node side I am manually removing this extra bit for signature verification :
```rs
       pub fn substrate_signing(payload: &[u8]) -> Vec<u8> {
	// FIXME: Temporary Fix is to remove the
        self.0.using_encoded(|payload| {
	                        payload: &[u8] = &payload[0..payload.len()-1];
			        if payload.len() > 256 {
				        f(&blake2_256(payload)[..])
			        } else {
				        f(payload)
			        }
		        })
```

**Comment by jacogr** [comment]
Where is your Rust definition for `AssetsTransactionPayment`?

You need to ensure the fields go into the correct places (my suspicion is that you have `signature_scheme ` in the wrong place and that it should be in `payload` based on your observations)

**Comment by nuel77** [comment]
The signature_scheme is defined in the ChargeAssetTransactionPayment struct linked here: https://github.com/Polkadex-Substrate/Polkadex/blob/125abd95917000fc2806626a7d3aa419854d74bf/pallets/assets-transaction-payment/src/lib.rs#L164
```rs
pub struct ChargeAssetTransactionPayment<T: Config> {
	pub asset_id: ChargeAssetIdOf<T>,
	pub tip: BalanceOf<T>,
	pub signature_scheme: u8,
}
```
The AssetTransactionPayment is an identifier for ChargeAssetTransactionPayment struct as shown here: (linked here: https://github.com/Polkadex-Substrate/Polkadex/blob/125abd95917000fc2806626a7d3aa419854d74bf/pallets/assets-transaction-payment/src/lib.rs#L231)
```rs
impl<T: Config> SignedExtension for ChargeAssetTransactionPayment<T>
where
	T::Call: Dispatchable<Info = DispatchInfo, PostInfo = PostDispatchInfo>,
	AssetBalanceOf<T>: Send + Sync + FixedPointOperand,
	BalanceOf<T>: Send + Sync + From<u64> + FixedPointOperand + IsType<ChargeAssetBalanceOf<T>>,
	ChargeAssetIdOf<T>: Send + Sync + Zero,
	CreditOf<T::AccountId, T::Fungibles>: IsType<ChargeAssetLiquidityOf<T>>,
{
	const IDENTIFIER: &'static str = "AssetsTransactionPayment";
	type AccountId = T::AccountId;
	type Call = T::Call;
	type AdditionalSigned = u8;
	type Pre = (
		// tip
		BalanceOf<T>,
		// who paid the fee - this is an option to allow for a Default impl.
		T::AccountId,
		// imbalance resulting from withdrawing the fee
		InitialPayment<T>,
	);

```

**Comment by jacogr** [comment]
`type AdditionalSigned = u8` - this means that `signature_scheme` needs to go into `payload` (not `extrinsic`)

**Comment by nuel77** [comment]
> signature_scheme

I tried adding `signature_scheme` into the payload, ie 
```js
                   AssetsTransactionPayment:{
                        extrinsic: {
                            asset_id: 'u128',
                            tip: 'Balance',
                        },
                        payload: {
                            signature_scheme:'u8',
                        }
                    }

```
But with no luck, now the node is throwing this error.
```
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Runtime error: Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `Call::Utility.0`:
	Could not decode `Call`, variant doesn't exist
```
do I need to configure it somewhere else on the node side, to specify its the `payload` type?

**Comment by jacogr** [comment]
So your node side has 1 extra byte, then maybe I'm incorrect and the issue is still the `AdditionalSigned` but for a different reason. (The JS API type _may_ be correct here)

1. Your `ChargeAssetTransactionPayment` does have the `u8`, so that is fine
2. You don't want additional `u8` in the payload only (so remove that and do `AdditionalSigned = ()`) - if you do want to double-up, as part of the struct/extrinsic _and_ the payload (additionally, already supplied) add an extra  `signature_scheme`

So looking at the intent, I'm guessing -

```rust
mpl<T: Config> SignedExtension for ChargeAssetTransactionPayment<T>
where
	T::Call: Dispatchable<Info = DispatchInfo, PostInfo = PostDispatchInfo>,
	AssetBalanceOf<T>: Send + Sync + FixedPointOperand,
	BalanceOf<T>: Send + Sync + From<u64> + FixedPointOperand + IsType<ChargeAssetBalanceOf<T>>,
	ChargeAssetIdOf<T>: Send + Sync + Zero,
	CreditOf<T::AccountId, T::Fungibles>: IsType<ChargeAssetLiquidityOf<T>>,
{
	const IDENTIFIER: &'static str = "AssetsTransactionPayment";
	type AccountId = T::AccountId;
	type Call = T::Call;
	type AdditionalSigned = ();
	type Pre = (
		// tip
		BalanceOf<T>,
		// who paid the fee - this is an option to allow for a Default impl.
		T::AccountId,
		// imbalance resulting from withdrawing the fee
		InitialPayment<T>,
	);
	...
```

and

```js
                let signedExtensions = {
                    AssetsTransactionPayment:{
                        extrinsic: {
                            asset_id: 'u128',
                            tip: 'Balance',
                            signature_scheme:'u8',
                        },
                        payload: {}
                    }
                }
```

(That is not doubling up on the value on either side, we assume it is all ok since it is in the struct)

**Comment by nuel77** [comment]
Thanks a lot, @jacogr. I don't just want to remove the extra bit, as I want the value of `signature_scheme` on the payload sent to the chain as well as the signing payload on the browser side. So from what I understood from your last message, I can make a workaround for this by adding some random field (let's say `signature_payload`) with type `u8`  (same as the `Extra::AdditionalSigned` type on chain) to the payload part and that would be part of the payload being signed on the browser.
```js
let signedExtensions = {
                    AssetsTransactionPayment:{
                        extrinsic: {
                            asset_id: 'u128',
                            tip: 'Balance',
                            signature_scheme:'u8',
                        },
                        payload: {
                            signature_payload:'u8',
                        }
                    }
                }
```
I can use this to sign on to the browser. That way, the `signature_scheme` field from extrinsic will be available on the node side along with the transaction payload. If I keep the `signature_scheme` and `signature_payload` values the same, then the node can reconstruct the exact payload I used to sign on the browser side (ie, can retrieve the `signature_scheme` value which if kept the same as `signature_payload` will result in the same payload for verification check on the node side). 

I tested this and this does seem to work. The only thing weird is having to keep the duplicate fields `signature_scheme` on extrinsic and `signature_payload` on the payload. Is it possible to access the value in payload field directly on the chain ?

**Comment by jacogr** [comment]
No. Payload values are only signed, but not part of the tx. So generally you fill those in as part of the verification. 

For instance, `genesisHash` is a good example: it doesn't need to be transmitted, but can be added for verification. Same with `transactionVersion`, etc. So the `AdditionalSigned` is for all the stuff that doesn't need transmission, but is known to all.

**Comment by nuel77** [comment]
I see. That is exactly what I am looking to do. The additional data for the chain to know, and in the signing payload so that the user can sign it. Thanks for taking the time to explain all this @jacogr.

**Comment by nuel77** [comment]
This change will break the Polkadot-apps UI though. Is there any way to keep the chain compatible there as well?

<img width="478" alt="image" src="https://user-images.githubusercontent.com/50878033/213860754-da277688-c048-47d7-9428-da9163c8ffa5.png">

**Comment by jacogr** [comment]
Each team has their own config for the apps UI, maintained by them. See https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api

This could be interesting, i.e. encointer does add their own signed extensions as part of the apps UI types bundle - https://github.com/polkadot-js/apps/blob/7b685cec664e0feeb3d0b1686641eb58d7ff3095/packages/apps-config/src/api/spec/encointer-para.ts#L247

**Comment by nuel77** [comment]
Thanks for the information. What encointer is doing does seem very similar to the functionality we want.
