### ISSUE TITLE
Is it possible to generate metadata markdown files for other chains?

### ISSUE THREAD

**Issue by alfarok** [polkadot-js/api#5452]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

  - Currently the @polkadot/typegen provides the ability to generate formatted markdown files for [Substrate metadata](https://github.com/polkadot-js/api/blob/master/packages/types-support/src/metadata/v14/substrate-json.json).  

* **Do you have any suggestions or recommendations?**

  - The TechEd at the Web3 Foundation was wondering if it's possible to generate the same files for Polkadot or Kusama (and possibly other chains)?

  - Quickly looking through the source code it looks like [this line](https://github.com/polkadot-js/api/blob/fee281fcb4982fecb38172a2de0d417613cab3f1/packages/typegen/src/metadataMd.ts#L417) could be modified, by replacing the `import rpcdata from '@polkadot/types-support/metadata/static-substrate` with another value, such as [static-polkadot](https://github.com/polkadot-js/api/blob/master/packages/types-support/src/metadata/static-polkadot.ts) or [static-kusama](https://github.com/polkadot-js/api/blob/master/packages/types-support/src/metadata/static-kusama.ts).  It appears the main function in `metadataMD` can be invoked via importing `@polkadot/typegen/metadataMd` but the `rpcdata` is hardcoded to [static-substrate](https://github.com/polkadot-js/api/blob/master/packages/types-support/src/metadata/static-substrate.ts).  Basically we are wondering if there is an out-of-the-box solution for this or if we will need to created a modified version of the module to do so.

* **What is the motivation for changing the behavior?**

  - Adding similar metadata content to the [Polkadot Wiki](https://wiki.polkadot.network/) and [Kusama Guide](https://guide.kusama.network/).

Any suggestions on this approach would be greatly appreciated, thanks!

FYI @drw3rk

**Comment by jacogr** [comment]
PRs welcome.

Other teams have contributed generation (for other parts) on a per-chain basis.

For backwards compat, you obviously want to keep the default. However there is nothing standing in the way of adding command-line arguments (like we have elsewhere), e.g. https://github.com/polkadot-js/api/blob/fee281fcb4982fecb38172a2de0d417613cab3f1/packages/typegen/src/fromChain.ts#L89-L93

And then using that. When not supplied, use the default, as-is.

The `metadataMd.ts` is actually only used externally (in a completely different repo), so the fact that it runs as a command is obviously intended. See https://github.com/polkadot-js/docs/blob/9cf83ac6e65c4e4dcdc89aff20bf512b4f9e3d46/package.json#L8

**Comment by alfarok** [comment]
Thanks @jacogr, this is exactly the info we were looking for.  I will circle back with the team and start planning our approach. :+1:
