### ISSUE TITLE
RPC eth_getTransactionCount first param should H160 type

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#5459]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

RPC ``eth_getTransactionCount`` first param should H160 type.

https://github.com/polkadot-js/api/blob/2c949e0fc58ce5b113f3d07045468ae153743bdb/packages/types/src/interfaces/eth/rpc.ts#L309 

https://docs.alchemy.com/reference/eth-gettransactioncount

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Reference to actual Frontier implementation - https://github.com/paritytech/frontier/blob/ab0f4a47e42ad17e4d8551fb9b3c3a6b4c5df2db/client/rpc-core/src/eth.rs#L140-L142
