### ISSUE TITLE
[Bug] Historic blocks on Kusama close to Genesis cant decode events

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#5461]
* **I'm submitting a ...** 

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

### **Current behavior:** 
When querying events on blocks close to genesis in this case, block 9253 (`specVersion 1020`) it cant decode the storage `system.events`. 

### Reproduction: 

```javascript
require('@polkadot/api-augment');
const { ApiPromise, WsProvider } = require('@polkadot/api');

/**
 * Simple polkadot-js template to test and reproduce things locally
 */
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://kusama-rpc.polkadot.io'),
    });

    // Kusama Block 9253
    const hash = '0xced7d69ee71848b6563095e203a125583194e87588d6d3f65e8d3a4ed4e5013f';
    const apiAt = await api.at(hash);

    try {
        await apiAt.query.system.events();
    } catch (e) {
        console.log(e)
    }
};

main().finally(() => process.exit());
```

### **Expected behavior:** 
It should decode correctly.

* **Please tell us about your environment:**

This bug is present in Release 9.13.1 and greater. It is not present in 9.12.1 or earlier. 

  - Version:
  - Environment:

    - [X] Node.js 18.12.1
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [X] JavaScript
    - [X] TypeScript (include tsc --version) 4.9.4 (Reproduction is in JS, but I found this bug in TS)
    - [ ] Other

**Comment by jacogr** [comment]
Ummm, interesting. No doubt related to the Weight aliasing. Will take a look.

**Comment by TarikGul** [comment]
Apologies, I forgot to also post the Error Message:

```
Uint8Array(242) [
  64,  66,  15,   0,   0,  1, 0, 0, 3, 0, 0,  0,
  13,   5, 160,  73, 112, 17, 0, 0, 0, 0, 0,  0,
   0,   0,   0,   0,   0,  0, 0, 0, 3, 0, 0,  0,
  17,   2,   0,   0,   0,  3, 0, 0, 0, 0, 0,  0,
   0,   0,   0,   1,   1,  0, 0, 4, 0, 0, 0, 13,
   5, 160,  73, 112,  17,  0, 0, 0, 0, 0, 0,  0,
   0,   0,   0,   0,   0,  0, 0, 4, 0, 0, 0, 17,
   2,   0,   0,   0,   4,  0, 0, 0, 0, 0, 0,  0,
   0,   0,   1,   1,
  ... 142 more items
] 16 1
Uint8Array(278) [
  72,   0,   0,   0,   0,  0, 0, 0, 16, 39,  0,  0,
   1,   1,   0,   0,   1,  0, 0, 0,  0,  0, 16, 39,
   0,   0,   0,   1,   0,  0, 2, 0,  0,  0,  0,  0,
  64,  66,  15,   0,   0,  1, 0, 0,  3,  0,  0,  0,
  13,   5, 160,  73, 112, 17, 0, 0,  0,  0,  0,  0,
   0,   0,   0,   0,   0,  0, 0, 0,  3,  0,  0,  0,
  17,   2,   0,   0,   0,  3, 0, 0,  0,  0,  0,  0,
   0,   0,   0,   1,   1,  0, 0, 4,  0,  0,  0, 13,
   5, 160,  73, 112,
  ... 178 more items
] 18 1
2023-01-31 15:52:16        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8aVec: failed at 0x00000010270000000100000200000000… (index 2/18): {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8aStruct: failed at 0x40420f0000010000030000000d05a049… on topics (index 3/3): Vec<Hash>:: decodeU8aVec: failed at 0x02000000070000000000000000000101… (index 8/16): H256:: Expected input with 32 bytes (256 bits), found 17 bytes
Error: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8aVec: failed at 0x00000010270000000100000200000000… (index 2/18): {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8aStruct: failed at 0x40420f0000010000030000000d05a049… on topics (index 3/3): Vec<Hash>:: decodeU8aVec: failed at 0x02000000070000000000000000000101… (index 8/16): H256:: Expected input with 32 bytes (256 bits), found 17 bytes
    at RpcCore._newType (/Users/tarikgul/Desktop/parity/tools-team/pjs-template/node_modules/@polkadot/rpc-core/cjs/bundle.js:458:13)
    at RpcCore._formatStorageData (/Users/tarikgul/Desktop/parity/tools-team/pjs-template/node_modules/@polkadot/rpc-core/cjs/bundle.js:394:17)
    at RpcCore._formatOutput (/Users/tarikgul/Desktop/parity/tools-team/pjs-template/node_modules/@polkadot/rpc-core/cjs/bundle.js:368:19)
    at RpcCore._formatResult (/Users/tarikgul/Desktop/parity/tools-team/pjs-template/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)
    at callWithRegistry (/Users/tarikgul/Desktop/parity/tools-team/pjs-template/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)
``

**Comment by jacogr** [comment]
Doesn't seem to be Weight or DispatchError  (which _normally_ causes historic failures) related, i.e. this yields the correct info -

```js
const hash = '0xced7d69ee71848b6563095e203a125583194e87588d6d3f65e8d3a4ed4e5013f';
const apiAt = await api.at(hash);
    
console.log(apiAt.registry.createType('Weight').toRawType())
```

So will have to dig to see wtf.

**Comment by jacogr** [comment]
Took a bit of wangling a a re-publish, 9.13.4 has been tested against the apps UI as working.

**Comment by TarikGul** [comment]
> Took a bit of wangling a a re-publish, 9.13.4 has been tested against the apps UI as working. (9.13.3 didn't publish successfully, either GH actions or npm to blame...)

Thanks for figuring that out, I can confirm that it now works. I was looking around yesterday, do you know of a way to accurately `yarn pack` a workspace for local troubleshooting against external projects. 

If not, i'll probably work on a solution in `/dev` and make a script because it would be super helpful to test, and more accurately troubleshoot, and debug some issues.

**Comment by jacogr** [comment]
Dev includes a “yarn polkadot-dev-copy-to [dest]” command. 

So assuming a root with apps and api. Inside api I can do a “copy-to apps” and it will compile and get it into node_modules

**Comment by TarikGul** [comment]
> Dev includes a “yarn polkadot-dev-copy-to [dest]” command.
> 
> So assuming a root with apps and api. Inside api I can do a “copy-to apps” and it will compile and get it into node_modules

Awesome, that is incredibly helpful. I'll start using that in order to give some more accurate feedback when debugging! Thanks again!
