### ISSUE TITLE
createType(Call) failed decoding council.propose

### ISSUE THREAD

**Issue by kroos47** [polkadot-js/api#5464]
Hey, So I was trying the council page to submit a motion from there. But found an issue there where I was not able to do the signandsend. I also tried a sample ts script to do the same but again that too failed with same error! :

`Error: createType(Call):: Call: failed decoding council.propose:: Struct: failed on args: {"threshold":"Compact<u32>","proposal":"{\"_enum\":{\"System\":\"FrameSystemCall\",\"Utility\":\"PalletUtilityCall\",\"Babe\":\"PalletBabeCall\",\"Timestamp\":\"PalletTimestampCall\",\"Authorship\":\"PalletAuthorshipCall\",\"Indices\":\"PalletIndicesCall\",\"Balances\":\"PalletBalancesCall\",\"__Unused7\":\"Null\",\"__Unused8\":\"Null\",\"ElectionProviderMultiPhase\":\"PalletElectionProviderMultiPhaseCall\",\"Staking\":\"PalletStakingPalletCall\",\"Session\":\"PalletSessionCall\",\"Democracy\":\"PalletDemocracyCall\",\"Council\":\"PalletCollectiveCall\",\"TechnicalCommittee\":\"PalletCollectiveCall\",\"Elections\":\"PalletElectionsPhragmenCall\",\"TechnicalMembership\":\"PalletMembershipCall\",\"Grandpa\":\"PalletGrandpaCall\",\"Treasury\":\"PalletTreasuryCall\",\"Sudo\":\"PalletSudoCall\",\"ImOnline\":\"PalletImOnlineCall\",\"__Unused21\":\"Null\",\"__Unused22\":\"Null\",\"__Unused23\":\"Null\",\"Scheduler\":\"PalletSchedulerCall\",\"Bounties\":\"PalletBountiesCall\",\"Tips\":\"PalletTipsCall\",\"__Unused27\":\"Null\",\"BagsList\":\"PalletBagsListCall\"}}","length_bound":"Compact<u32>"}:: Struct: failed on proposal: {"_enum":{"System":"FrameSystemCall","Utility":"PalletUtilityCall","Babe":"PalletBabeCall","Timestamp":"PalletTimestampCall","Authorship":"PalletAuthorshipCall","Indices":"PalletIndicesCall","Balances":"PalletBalancesCall","__Unused7":"Null","__Unused8":"Null","ElectionProviderMultiPhase":"PalletElectionProviderMultiPhaseCall","Staking":"PalletStakingPalletCall","Session":"PalletSessionCall","Democracy":"PalletDemocracyCall","Council":"PalletCollectiveCall","TechnicalCommittee":"PalletCollectiveCall","Elections":"PalletElectionsPhragmenCall","TechnicalMembership":"PalletMembershipCall","Grandpa":"PalletGrandpaCall","Treasury":"PalletTreasuryCall","Sudo":"PalletSudoCall","ImOnline":"PalletImOnlineCall","__Unused21":"Null","__Unused22":"Null","__Unused23":"Null","Scheduler":"PalletSchedulerCall","Bounties":"PalletBountiesCall","Tips":"PalletTipsCall","__Unused27":"Null","BagsList":"PalletBagsListCall"}}:: Cannot map Enum JSON, unable to find 'initialU8aLength' in system, utility, babe, timestamp, authorship, indices, balances, __unused7, __unused8, electionprovidermultiphase, staking, session, democracy, council, technicalcommittee, elections, technicalmembership, grandpa, treasury, sudo, imonline, __unused21, __unused22, __unused23, scheduler, bounties, tips, __unused27, bagslist
  at createTypeUnsafe (/Users/kroos/tests/js_api/node_modules/@polkadot/types-create/cjs/create/type.js:73:18)
  at TypeRegistry.createTypeUnsafe (/Users/kroos/tests/js_api/node_modules/@polkadot/types/cjs/create/registry.js:353:46)
  at extrinsicFn (/Users/kroos/tests/js_api/node_modules/@polkadot/types/cjs/metadata/decorate/extrinsics/createUnchecked.js:31:21)
  at Object.decorated [as propose] (/Users/kroos/tests/js_api/node_modules/@polkadot/api/cjs/base/Decorate.js:632:22)
  at /Users/kroos/tests/js_api/src/council.ts:28:40
  at Generator.next (<anonymous>)
  at fulfilled (/Users/kroos/tests/js_api/src/council.ts:5:58)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

I also tried a script to do an extrinsic submission which resulted in same error

```
import '@polkadot/api-augment'
import '@polkadot/types-augment/registry'
import { ApiPromise, WsProvider, Keyring } from '@polkadot/api';
import { KeyringPair } from '@polkadot/keyring/types';
import type { EventRecord, ExtrinsicStatus, H256 } from '@polkadot/types/interfaces';
import type { ISubmittableResult, SignatureOptions } from '@polkadot/types/types';
import config from './config';
import { createApi } from './api';

const keyring = new Keyring({ type: 'sr25519' });

interface SignatureOptionsNew extends SignatureOptions {
    app_id: number
}

async function main(){
    const api = await createApi();
    const sender = keyring.addFromUri(config.mnemonic);
    let nonce = (await api.rpc.system.accountNextIndex(sender.address)).toNumber();

    const increaseValidatorCount = api.tx.staking.increaseValidatorCount(10);
    const proposal = api.registry.createType('Call', {
        callIndex: increaseValidatorCount.callIndex,
        args: increaseValidatorCount.args,
      });
    const motion = {
        proposal: proposal,
        threshold: api.registry.createType('Compact<u32>', 5),
        length_bound: api.registry.createType('Compact<u32>', 36)            
    };
    const options: Partial<any> = { app_id: 0, nonce: nonce }

    const unsub = await api.tx.council.propose(motion.threshold, motion.proposal, motion.length_bound).signAndSend(sender, options, ({ events = [], status }) => {
        console.log('Transaction status:', status.type);
      
        if (status.isFinalized) {
          console.log('Completed at block hash', status.asFinalized.toHex());
          console.log('Events:', events);
      
          unsub();
        }
      });
    
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
```

One thing to note is that its a custom chain, where header implementation have changed. 

Also I tried to send this with the extrinsic page and I was able to do so. But when I went back to council page it gave another decoding error there

![image](https://user-images.githubusercontent.com/47864482/216273658-d1931217-380b-4624-82bb-af762c4f8ba9.png)

  - [ ] Bug report
  - [ ] Feature request
  - [ ✔️] Support request
  - [ ] Other

  - Version:
  - Environment:

    - [ ✔️ ] Node.js
    - [ ✔️] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ✔️ ] TypeScript (tsc version 4.5.5)
    - [ ] Other

**Comment by jacogr** [comment]
Without an actual chain to connect to, this is not quite possible to track.

**Comment by kroos47** [comment]
@jacogr I can provide the chain URL. But as this is a council call there needs to be a council account or must be a local dev network. So would you like to have the chain URL or the substrate repo

**Comment by jacogr** [comment]
A url is fine and certainly better - cloning and compiling a new chain is not fund when I already have to track 5 different chains. 

But this is certainly not related to just council, the Call type is detected wrong which leads to the issue. (It will also break elsewhere due to the same issue)

So can take a look at a deployed chain to determine why (and see if it needs a fix).

**Comment by kroos47** [comment]
@jacogr  yeh so this is the url to the [network](https://devnet06.dataavailability.link/)

**Comment by jacogr** [comment]
Yes, so this is the exact issue -

`polkadot.02.6ddb65fe.js:1 2023-02-07 10:56:47 PORTABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic`

It cannot find the `UncheckedExtrinsic` type so anything to do with `Call` would be touch and go.

**Comment by kroos47** [comment]
So what can be done to fix that! I mean to make it compatible with it. Everything else was working fine.

**Comment by jacogr** [comment]
I literally have no idea how the interrogate the metadata types in this case to get the required information. We are looking at a known/fixed type path from where to extract the `Call` info. As to why this specific chain does not expose the `UncheckedExtrinsic` (generally used for the signed extensions mappings), no idea.

The closest we get is `da_runtime::RuntimeCall`, but this has different paths on each runtime, so a non-fixed/guessing extraction.

**Comment by jacogr** [comment]
EDIT: In the case of this runtime, the type we are looking for is on `da_primitives::asdr::AppUncheckedExtrinsic` so we just cannot detect it as it stands. 

The TL:DR of it is that currently there is no way for the API to detect and support the runtime at this point. There could possibly be different ways in the future.

**Comment by kroos47** [comment]
So what it stands now is that it is unable to get the metadata properly, or to be more specific the `AppUncheckedExtrinsic`. 

> We are looking at a known/fixed type path from where to extract the Call info

So to get a clear picture the Call info is taken from a particular place, or did I get it wrong? 
Also exposing the `AppUncheckedExtrinsic` might help us with this?  

One thing to ask is that how do other substrate chains get these information? Just to take a point of reference!

**Comment by kroos47** [comment]
So it is failing to get the metadata properly. 
> We are looking at a known/fixed type path from where to extract the Call info.

So I assume this is how its defined in the api. 

I got confused because the other extrinsics were perfectly working fine, like balance transfer, democracy, custom pallet extrinsics etc. Also this council propose call worked from extrinsics page where it got submitted in chain, eventhough the council page returned a decoding error as shown above.

**Comment by kroos47** [comment]
One more thing to note is that the following warning 

```
polkadot.02.6ddb65fe.js:1 2023-02-07 10:56:47 PORTABLEREGISTRY: Unable to determine runtime Call type, cannot inspect sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic

```
was given for every js scripts like balance transfer, block subscription etc but it all worked fine. So actually I didn't thought this would give an error

**Comment by jacogr** [comment]
Yes, the warning would be displayed once per metadata retrieval.

**Comment by kroos47** [comment]
Makes sense! Then I guess unless `AppUncheckedExtrinsic ` is available, the error cannot be solved. Is that right?

**Comment by kroos47** [comment]
Closing this issue for now! @jacogr thanks for the info
