### ISSUE TITLE
mmr_generateProof params is not correct

### ISSUE THREAD

**Issue by DaviRain-Su** [polkadot-js/api#5478]
https://github.com/paritytech/substrate/blob/38c3e5ee10be760115a77a115ef0ac6ba381542b/client/merkle-mountain-range/rpc/src/lib.rs#L98 

this rpc method params need to update.

* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
It is very outdated - there are a number of new RPC methods added as well. PRs welcome.
