### ISSUE TITLE
[Question] Do we plan to optimize the ink-4.0 output handling?

### ISSUE THREAD

**Issue by kvinwang** [polkadot-js/api#5480]
Given a contract method:
```
#[ink(message)]
fn foo() -> T;
```
Ink-4.0 always turns the output type to `Result<T, LangError>`, that's a breaking change to the front end and a bad dev experience.
Is there a plan that polkadotjs would optimize the API kinda like auto unwrap the inner Result and merge the Err to the outer Result?

**Comment by jacogr** [comment]
The API does not mangle what is defined in either the on-chain metadata or the ABIs. So it will always return as-defined.

**Comment by kvinwang** [comment]
Get it. Thanks.
