### ISSUE TITLE
Where's xcm v3?

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/api#5489]
Should https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/xcm/v3.ts exist? That would be great if xcm v3 was supported.

**Comment by jacogr** [comment]
PRs welcome if you are in a rush. It is somewhere on my TODO list.

**Comment by jacogr** [comment]
From metedata, as per the connected chain, e.g. for Polkadot - https://github.com/polkadot-js/api/blob/6ea6b90e0395819c1d7ded0a2774710130eba892/packages/types-augment/src/lookup/types-polkadot.ts#L113-L122
