### ISSUE TITLE
API initialization/decoration warnings with Aleph Zero Testnet 

### ISSUE THREAD

**Issue by wottpal** [polkadot-js/api#5497]
Hey there,
when connecting to the Aleph Zero Testnet (`wss://ws.test.azero.dev`) I get the following warnings. Already reached out but they are not aware of missing decorations. Do you have any idea?

```
API/INIT: RPC methods not decorated: alephNode_emergencyFinalize
API/INIT: aleph-node/51: Not decorating unknown runtime apis: 0x2be3f75b696ad1f6/1
```

Also already found the place where this is logged: https://github.com/polkadot-js/api/blob/5183c28d5e35ff2ec086c9d8be16ccf74e15e787/packages/api/src/base/Decorate.ts#L372

**Comment by jacogr** [comment]
1. The method `alephNode_emergencyFinalize` (as returned by the `rpc_methods` RPC) does not have a known implementation.
2. The runtime API hash `0x2be3f75b696ad1f6` is unknown and doesn't have a decoration

For both of these, generally the team applies decorations via their own type packages.

**Comment by wottpal** [comment]
Thanks for the reply. Adding some of the team members to the discussion: @h4nsu @deuszx

**Comment by aang114** [comment]
> 1. The method `alephNode_emergencyFinalize` (as returned by the `rpc_methods` RPC) does not have a known implementation.
> 2. The runtime API hash `0x2be3f75b696ad1f6` is unknown therefore is not being decorated
> 
> For both of these, generally the team applies decorations via their own type packages.

The Polkadot.js Docs website only provides documentation for decorating custom RPC methods: https://polkadot.js.org/docs/api/start/rpc.custom.

Could you give an example on how to decorate a custom runtime API method? Thanks

**Comment by jacogr** [comment]
Here is an example as done by Frequency (rpc, types & runtime all-in-one) - https://github.com/LibertyDSNP/frequency/blob/main/js/api-augment/definitions/frequency.ts

**Comment by jacogr** [comment]
Closing. Answered as asked.
