### ISSUE TITLE
how to handle error: "Error: The transactionPaymentApi.queryInfo runtime call is not available in your environment"

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#5504]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

My program use singleton ApiPromise instance and run in background( on aws server).

Most of time it run well, but occassionally raise problem. 

Today it throw error:  "**The transactionPaymentApi.queryInfo runtime call is not available in your environment**"

and this error come out of `paymentInfo()` call, as show bellow.

**My code snippet:** 

```js
const { ApiPromise, WsProvider } = require('@polkadot/api');
	...
	
api = await ApiPromise.create({provider: provider, throwOnConnect: true});	

	...
	
const info = await api.tx.utility
        .batch(txs)
        .paymentInfo(estimatePair);  // Throw error here.
        
console.log("info.partialFee: ", info.partialFee);

```

**So, I have some puzzle:** 

1. why and how this error happen? 
2. how to solve my problem? Do i need to restart my program?

  - Version:  "9.10.1"
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The chain runtime needs to expose the call. This generally means adding the pallet to the runtime.

**Comment by code-brewer** [comment]
Thanks your info.
I have no idea of chain runtime.  In my case, I provide a set of url  to the WsProvider: 

```
      let nodeUrl = [
             "wss://westend-rpc.polkadot.io",
            "wss://westend.api.onfinality.io/public-ws",
            "wss://rpc.pinknode.io/westend/explorer"
    ]
        const provider = new WsProvider( nodeUrl, 30);
        const api = await ApiPromise.create({ provider: provider, throwOnConnect: true });

```
Maybe some change happened on the node that my program currently connected, so that it missed the `paymentInfo` call. 
This may soundable, but the `paymentInfo` api is a basic function that should not be interfered by any pallet, I believed.

Btw, can i get a list of all the pallet and the api they exposed?

**Comment by code-brewer** [comment]
Any expert or experienced guy can help me on how to solve this error ?
Upgrade `polkadot-js` library to latest verion? or use another set of node url ?

**Comment by code-brewer** [comment]
After upgrade polkadot-js package to latest version, this error appear.

**Comment by code-brewer** [comment]
Run into this error again. So annoying.
In my opinions, it was cause by the upgrade of wasm-runtime code and the library on my side not upgrade so frequently.
Is there a release notes list of polkadot testnet on the internet?  And how can I get the available API list that runtime code provide/support?

**Comment by JozzyF** [comment]
Any thing new about this issue. I have the same exact issue. It appears if i give kusama nodeUrl. Polkadot nodeUrl works fine.

**Comment by lukerQuant** [comment]
Hi @JozzyF we got around this issue by increasing the version to the latest for all of the @polkadot libraries

**Comment by JozzyF** [comment]
Hi @lukerQuant i upgraded the packages and saw some slight changes. It works fine now, i guess

**Comment by forgetso** [comment]
> Hi @JozzyF we got around this issue by increasing the version to the latest for all of the @PolkaDot libraries

@lukerQuant Which versions work for you? `"@polkadot/api": "10.7.1",` seems to not work for me.

**Comment by JozzyF** [comment]
Hey the version you wrote worked for me. But it has some differences in terms of staking parameters that bond takes. In previous version which i use, api.tx.staking.bond was taking 3 parameters: controller, amount and payee. Strangely they removed the controller but when i remove controller it says it requires 3 parameter. Someone please help me about this. @lukerQuant @jacogr
