### ISSUE TITLE
Is it possible to verify the SubmittableExtrinsic signature with the polkadot js api?

### ISSUE THREAD

**Issue by pgolovkin** [polkadot-js/api#5528]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Having the instance of the SubmittableExtrinsic I know the `signature`, `signer` and `extrinsic` data itself. Is it way to verify it? I tried to use the example https://polkadot.js.org/docs/util-crypto/examples/verify-signature but it doesn't work.

```
      //Wesend
      const blockHash = await api.rpc.chain.getBlockHash(14943788);
      const signedBlock = await api.rpc.chain.getBlock(blockHash);
      const extrinsic = signedBlock.block.extrinsics[2];
      const signer = api.createType('Address', extrinsic2.signer.toString()).toString();
      const signature = u8aToHex(extrinsic2.signature);
      console.log(signatureVerify(extrinsic.toHex(), signature, decodeAddress(signerAddress)));

```

I also tried to put `extrinsic2.hash` as the 1st parameter into `signatureVerify` function.

* **Please tell us about your environment:**

  - Version: 9.14.2
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Your issue is here -

```js
console.log(signatureVerify(extrinsic.toHex(), signature, decodeAddress(signerAddress)));
```

What is signed is not the extrinsic itself, but an extrinsic payload. (The call data only forms part of the payload, there are other information such as `genesisHash` that gets signed, but is not part of the extrinsic)

**Comment by dlebee** [comment]
I’ve been searching for the same thing to validate if the signature is signed a while before, and the era has passed the node can validate that the signature + extra details but no way to verify the signature with the polkadotjs, that would be awesome
