### ISSUE TITLE
Wrong capitalization in parameter when doing RPC call

### ISSUE THREAD

**Issue by onnovisser** [polkadot-js/api#5529]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm trying to do an RPC call, but it errors because there's a change in capitalization of one of the parameters when the call gets submitted.

The types: 
```
const types = {
  PoolId: "u64",
  TrancheId: "[u8; 16]",
  RewardDomain: {
    _enum: ["Block", "Liquidity"]
  },
  CurrencyId: {
    _enum: {
      Native: "Native",
      Tranche: "(PoolId, TrancheId)",
      KSM: "KSM",
      AUSD: "AUSD",
      ForeignAsset: "u32"
    }
  }
};

const rpc = {
  rewards: {
    computeReward: {
      description: "Compute reward",
      params: [
        {
          name: "currency_id",
          type: "(RewardDomain,CurrencyId)"
        },
        {
          name: "account_id",
          type: "AccountId"
        }
      ],
      type: "u128"
    }
  }
};
```

The call
```
api.rpc.rewards.computeReward(
  [
    "Liquidity",
    { Tranche: ["872535177", "0x58c4a52c1f0d239f1ff53f7f13875b3d"] }
  ],
  "4fZ56cX6at2SCLe8NbC6o2Q13KmCCkxDTSB5Hq6woekqZDf5"
);
```

The rpc call that gets made
```
{
  "id": 8,
  "jsonrpc": "2.0",
  "method": "rewards_computeReward",
  "params": [
    ["Liquidity", { "tranche": [872535177, "0x58c4a52c1f0d239f1ff53f7f13875b3d"] }],
    "kAMN6eYXWjYWzvsRYkVw8aJuW5ADjA3Hd2zgL6vbmM72U1Jcu"
  ]
}
```

The error
```
2023-03-09 12:03:12        RPC-CORE: computeReward(currency_id: (RewardDomain,CurrencyId), account_id: AccountId): u128:: -32602: unknown variant `tranche`, expected one of `Native`, `Tranche`, `KSM`, `AUSD`, `ForeignAsset` at line 1 column 23
```

`Tranche` unexpectedly changes to `tranche`.

A sandbox reproducing the error: https://codesandbox.io/s/polkadotjs-rpc-xjjdhl?file=/src/index.ts

* **What is the motivation for changing the behavior?**

I would expect the capitalization to remain unchanged.

* **Please tell us about your environment:**

  - Version: 10.0.1
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Where is the Rust definition for these enums?

Th reason for asking, as per the substrate standard, all enums are encoded (when they have values) in camelCase, see for instance https://github.com/paritytech/substrate/blob/310fe4095bff177ddcfa660ac0ab06171a25a9c2/frame/support/src/dispatch.rs#L138 (picking the first enum via JSON that my search picked up)

TL:DR It seems you are missing the `#[cfg_attr(feature = "std", serde(rename_all = "camelCase"))]` attribute in your type - sadly this is just a standard that needs to be followed, since encoding enums different would make the world break

**Comment by onnovisser** [comment]
It appears that the enums indeed don't have that attribute (here for example: https://github.com/centrifuge/centrifuge-chain/blob/0f32f7b4967c73cc38914c86c2f742f28f3da789/libs/types/src/tokens.rs#L27)
I found out that we were also defining runtime APIs besides the RPC methods, so I'll be using those instead.
Thanks and I'll close this.
