### ISSUE TITLE
Data from api.createType doesn't match with substrate runtime

### ISSUE THREAD

**Issue by amany9000** [polkadot-js/api#5554]
I've defined a schema type in the runtime, I'm signing it using `polkadot.js: keyPair.sign()` in typescript, I want to verify this signature on the runtime. I'm using `api.createType()` to create a `schemaInstance` and then call `schemaInstance.toU8a()` but these bytes don't completely match with what `schemaData.encode()` returned on the runtime, as a result my signature verification is failing.

A nested field in schema of the type `Option<Vec<u8>>` has an extra 0 byte on the runtime if the field is null on polkadot.js side. Similar byte-level inconsistencies are there with nested enums.

  - [ ] Bug report
  - Version:
  - Environment:
    - [ ] Node.js

  - Language:
    - [ ] TypeScript

Thank you in advance.

**Comment by jacogr** [comment]
The leading zero will be there. SCALE encodes None as 0, Some would be 1 with the bytes following.
