### ISSUE TITLE
RpcError: -32702: Response is too big: Exceeded max limit of 1048576

### ISSUE THREAD

**Issue by Ljzn** [polkadot-js/api#5579]
- [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Hi, I'm using `polkadot/api` to fetch the block data of Astar chain. When fetch the block height `3281149` , got this error:

```
2023-04-05 03:25:39 info: RpcError: -32702: Response is too big: Exceeded max limit of 1048576
    at checkError (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:34:11)
    at RpcCoder.decodeResponse (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:54:5)
    at WsProvider.value (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:297:90)
    at W3CWebSocket.value [as onmessage] (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:277:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/src/app/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (node:events:369:20)
    at WebSocketConnection.processFrame (/usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:323:40
```

It looks like there is a limit of 1mb to the response data. Is there a way to modify the max limit? Thanks!

  - Version: "@polkadot/api": "9.5.2",
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
`-32702: Response is too big: Exceeded max limit of 1048576` comes from the RPC node itself. So it is the configuration on the RPC nodes for the network that results in this error.

(In general Substrate have RPC limits - I believe in recent versions the 1MB size has been lifted, but not close enough to be 100% sure)

**Comment by johnnyji-dev** [comment]
I also have a same issue on nestjs.
Is it solved? How can I get some advice?

**Comment by jacogr** [comment]
As detailed above - this is not API related nor JS related. Frameworks doesn't matter, the same error will be received when using a simple `curl` call on the CLI.

The RPC Node, aka the Substrate code, has a built-in limit. It will not send responses higher than that limit. See the Substrate JSONRPC implementation for details - https://github.com/paritytech/jsonrpsee/blob/d6a96229d69f76cab2f6d31be111165571d430e1/core/src/server/helpers.rs#L216

On recent versions of Substrate you can use the `--rpc-max-response-size <RPC_MAX_RESPONSE_SIZE>` option on the RPC node to adjust.

**Comment by johnnyji-dev** [comment]
> 

I am using wss provider and code like this `api.rpc.chain.getBlock(blockHash);`
I think it need to add --rpc-max-response size option on WsProvider below code.
`const` provider = new WsProvider('wss://rpc.shibuya.astar.network', option);`

BTW, It is hard to find how to add option on that.
@jacogr Can you give some advice for that?

**Comment by johnnyji-dev** [comment]
> I am using wss provider and code like this `api.rpc.chain.getBlock(blockHash);` I think it need to add --rpc-max-response size option on WsProvider below code. `const` provider = new WsProvider('wss://rpc.shibuya.astar.network', option);`
> 
> BTW, It is hard to find how to add option on that. @jacogr Can you give some advice for that?

**Comment by jacogr** [comment]
Read above - it has nothing to do with JavaScript or the API.

It is a command-line option on the RPC node itself. It needs to be set by the RPC node operators.

**Comment by johnnyji-dev** [comment]
> Read above - it has nothing to do with JavaScript or the API.
> 
> It is a command-line option on the RPC node itself. It needs to be set by the RPC node operators. The RPC node queries the database, sees the response is too big (as per configuration on that side) and returns the stated error.
> 
> ```
> JS code -> JS API -> ~~~ internet ~~~ -> RPC node
>                                          ^^^^^^^^ error returned here
>                                          (based on the startup options
>                                          as supplied by the operators)
> ```

I am using public node endpoint like below.
`const provider = new WsProvider('wss://rpc.shibuya.astar.network');`
Your explaination is the problem is on RPC-node.

I just need to change another proper RPC node, is it right?
My program has no problem.~
