### ISSUE TITLE
How can I handle error from batchAll extrinsic 

### ISSUE THREAD

**Issue by Sotatek-TungLe2** [polkadot-js/api#5581]
- [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

// construct a list of transactions we want to batch
const txs = [
api.tx.balances.transfer(addrBob, 12345), (1)
api.tx.balances.transfer(addrEve, 12345), (2)
api.tx.staking.unbond(12345) (3)
];

// construct the batch and send the transactions
api.tx.utility
.batch(txs)
.signAndSend(sender, ({ status }) => {
if (status.isInBlock) {
console.log(included in ${status.asInBlock});
}
});

* **What is the current behavior and expected behavior?**

If the transaction (2) failed ( don't have enough balance fee to send anymore). So how can I block all the chain transactions or if don't, how can I handle the error comes out?

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
No action needed here, asked on StackOverflow.

**Comment by TarikGul** [comment]
@Sotatek-TungLe2 I believe you are looking for this: https://substrate.stackexchange.com/questions/7943/how-can-i-handle-error-from-batchall-extrinsic
