### ISSUE TITLE
V10.6.1 throw Error: SyntaxError: Unexpected token '||=' 

### ISSUE THREAD

**Issue by woyoutlz** [polkadot-js/api#5641]
* **I'm submitting a Bug**

  - [ √] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
when I do const { ApiPromise, WsProvider } = require('@polkadot/api')
Error throw
@polkadot/api/cjs/promise/Combinator.js:27
this.__internal__allHasFired ||= this.__internal__fired.filter((hasFired) => !hasFired).length === 0;
SyntaxError: Unexpected token '||='

* **Please tell us about your environment:**

  - Version: 10.6.1
  - Environment:

    - [√ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [√ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
It is valid JS syntax, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
