### ISSUE TITLE
How to createType with other chain types?

### ISSUE THREAD

**Issue by Verin1005** [polkadot-js/api#5654]
- [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
I have generated two types, one is [parachain](https://github.com/litentry/litentry-parachain/tree/de37126b8ac3fc040753f4299787b8454a146232/tee-worker/ts-tests/parachain-interfaces) and the other is [sidechain](https://github.com/litentry/litentry-parachain/tree/de37126b8ac3fc040753f4299787b8454a146232/tee-worker/ts-tests/sidechain-interfaces). I want to use the [type](https://github.com/litentry/litentry-parachain/blob/de37126b8ac3fc040753f4299787b8454a146232/tee-worker/ts-tests/sidechain-interfaces/types-lookup.ts#L359) of  "sidechain" with the API function `api.createType('LitentryPrimitivesIdentity')` to construct data. However, I receive an error message: `Error: createType(LitentryPrimitivesIdentity):: DoNotConstruct: Cannot construct unknown type LitentryPrimitivesIdentity`. This error is expected because the API is using the `parachain` type. Is there a way to use a different chain when using createType?Or is it necessary for the parachain to support "LitentryPrimitivesIdentity"?

btw:When instantiating the API, I don't want to customize types; otherwise, the generation of my types would be meaningless.

Thanks!

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The type name you are referring to comes from the on-chain metadata.

If you wish to construct chains not in the on-chain metadata, you can define/inject them via the api types/typesBundle options. (Which means they need to be fully defined there)

**Comment by Verin1005** [comment]
It's precisely because I don't want to customize that I came to ask this question.  However, I think I have found a solution.  We can load other metadata through the registry and then use registry.createType().  I have tested it, and it works.Thanks!
