### ISSUE TITLE
VersionedMultiLocation Encodes Incorrectly for V2

### ISSUE THREAD

**Issue by jboetticher** [polkadot-js/api#5655]
**I'm submitting a bug.**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Polkadot's recent version has defined the `VersionedMultiLocation` enum as two types, V2 and V3:  

```rust
versioned_type! {
	/// A single `MultiLocation` value, together with its version code.
	#[derive(Ord, PartialOrd)]
	pub enum VersionedMultiLocation {
		#[codec(index = 1)] // v2 is same as v1 and therefore re-using the v1 index
		V2(v2::MultiLocation),
		#[codec(index = 3)]
		V3(v3::MultiLocation),
	}
}
```

https://github.com/paritytech/polkadot/blob/41982b517b3405583cad877aa2af4e27925ac73b/xcm/src/lib.rs#L248-L254

Whenever you attempt to encode a VersionedMultiLocation V2, it keeps the index of 2. The index of 2 is not within the VersionedMultiLocation enum, however.

```typescript
const registry = new TypeRegistry();
const versionedMultiLocation = {
  V2: {
    parents: 1,
    interior: {
      X1: {
        AccountKey20: {
          id: "0x0000000000000000000000000000000000000000000000000000000000000000",
        },
      },
    },
  },
};
const destination = registry.createType(
  "VersionedMultiLocation",
  versionedMultiLocation
);
console.log(destination.toHex());
// 0x02010103000000000000000000000000000000000000000000
```

* **What is the motivation for changing the behavior?**

The codec ought to begin with "0x01" instead of "0x02", since that is how Polkadot expects V2 to be encoded (unless we consider this a bug within Polkadot itself).

* **Please tell us about your environment:**

  - Version: 
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jboetticher** [comment]
A related meantime fix that we used was simply changing V2 to V1, but regardless this issue still persists for anyone who intends to use V2 and doesn't know about this.

https://github.com/PureStake/moonbeam/pull/2288/commits/fc50a0667e523e93caeeadad456609ad6f67276b

**Comment by jacogr** [comment]
The correct approach is to use `XcmVersionedMultiLocation` which is the type added from the on-chain runtime. The `Versioned*` type is a manual type only for old runtime pre-v14.

So on Kusama for instance -

```js
// yields 0x010100
console.log(api.createType('XcmVersionedMultiLocation', { V2: { parents: 1 } }).toHex())
// yields 0x030100
console.log(api.createType('XcmVersionedMultiLocation', { V3: { parents: 1 } }).toHex())
```

Interesting on Kusama vs Polkadot (current vs previous) -

```js
// Kusama
{"_enum":{"__Unused0":"Null","V2":"XcmV2MultiLocation","__Unused2":"Null","V3":"XcmV3MultiLocation"}}

// Polkadot
{"_enum":{"V0":"XcmV0MultiLocation","V1":"XcmV1MultiLocation"}}
```
