### ISSUE TITLE
api.derive.democracy is undefined

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/api#5657]
* **I'm submitting a bug**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I found that `democracy` methods are suddenly missing from the API.

`api.derive.democracy`, `api.derive.council` and `api.derive.staking` are undefined.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: v10.7.2
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (v4.3.5)
    - [ ] Other

**Comment by jacogr** [comment]
Which chain?

**Comment by xwartz** [comment]
ok, thank you for the response.
