### ISSUE TITLE
Regression: Extrinsic.paymentInfo overwrites signature

### ISSUE THREAD

**Issue by parker-codes** [polkadot-js/api#5658]
I was using `.signAndSend()`, but needed to change my implementation to `.signAsync()`, then get payment details, then `.send()` once the user confirms. I can't change the order of these operations for various reasons.

When I split this up, I was getting the error: `submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature`. I narrowed the problem down to the cost/payment request, which really surprised me. I logged out the extrinsic details and found that it was mutating the already-valid signature!

I dove into the code and saw that there is indeed [a conditional statement](https://github.com/polkadot-js/api/blob/54c96ed975902a20bc37ac43b8d5181337f32799/packages/api/src/submittable/createClass.ts#L163-L165) based on if it is already signed, but the ternary always calls `signFake()` anyways..

I looked through past issues and found https://github.com/polkadot-js/api/issues/4755. It was triaged and a solution provided in https://github.com/polkadot-js/api/pull/4756 a year ago. It seems like there was a regression since then.

---

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently I have an extrinsic, I sign it, and then when I get the payment details, the signature is overwritten with a fake one. Here's a simple version of my flow:

```ts
const extrinsic = $_API.tx.staking.nominate(validators);
const signedExtrinsic = await extrinsic.signAsync($_SELECTED_ACCOUNT_ID, {
  signer: $_INJECTOR.signer,
});

// has valid signature
const info = (await extrinsic.paymentInfo($_SELECTED_ACCOUNT_ID)).toJSON(); // display to users
// has invalid signature

// after user confirmation
extrinsic
  .send((data) => {
    console.log('submit extrinsic response', data);
  });
```

* **What is the motivation for changing the behavior?**

So that this doesn't confuse others like it did for me.

* **Please tell us about your environment:**

  - Version: 9.13.6 and 10.7.2
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (v4.3.4)
    - [ ] Other

**Comment by jacogr** [comment]
The conditional statement is correct, i.e.

```js
const u8a = this.isSigned
  ? api.tx(this).signFake(address, signOptions).toU8a()
  : this.signFake(address, signOptions).toU8a();
```

Where it _does_ break down is optimizations in the actual creation of items that went in some time in the past. Since the `this` and `SubmittableExtrinsic` is the same thing, it basically just copies all fields (now, instead of re-creating), which then makes it end up with a shared signature object.

Not 100% sure (since it has been ages looking at any of this), but we could just do `api.tx(this.method).signFake(address, signOptions).toU8a()` in both cases to ensure that we always. forcing the creation of a new signature in all cases. (And never share the underlying objects)

**Comment by parker-codes** [comment]
I think I follow, though I don't know the internals very well. Just what I read through to try to find the source of the problem. For now in my own project I've just replaced 

```ts
const info = (await extrinsic.paymentInfo($_SELECTED_ACCOUNT_ID)).toJSON();
```

with

```ts
const info = (await $_API.rpc.payment.queryInfo(extrinsic.toHex())).toJSON();
```

and it works just fine.
