### ISSUE TITLE
How can we merge types-lookup generated from different metadata?

### ISSUE THREAD

**Issue by Verin1005** [polkadot-js/api#5664]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

I have two different metadata files, and I generated separate typegen outputs for each. I want to configure my `tsconfig.json` file like this: `"@polkadot/types/lookup": ["chain1-types-lookup path", "chain2-types-lookup path"]`. However, this configuration doesn't seem to work as expected. I can only access the types from `chain1-types-lookup`. Is it not supported to have multiple types-lookup configurations, or am I using it incorrectly?

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
You can read about TS path config here - 

- TypeScript docs - https://www.typescriptlang.org/tsconfig#paths
- Path alias writeup - https://betterprogramming.pub/how-to-configure-path-aliases-with-typescript-8586dc0aa214

The tsc compiler will pull the first matching path.

**Comment by grumpygreenguy** [comment]
@jacogr thanks for the answer.

One thing I was wondering is whether it'd be possible to somehow splice the metadata from both chains into a _single_ augmentation? Either by combining the metadata inputs or some unholy manipulation of the typegen outputs? :thinking: 

Alternatively, is there some recommended practice for projects that need to interface with multiple chains? (outside of liberally sprinkling our code with `as` and `any` which kind of defeats the purpose of the type system)

**Comment by jacogr** [comment]
You would need to augmented imports to apply the types, for instance

```js
// augmentation 1
import './something.js';
// augmentation 2
import './somethingElse.js'
```

Assuming they type structures don't conflict, i.e. extra fields added, extra methods added in a pallet (for instance you can never merge Kusama & Polkadot since they do have conflicts inside pallets with regards to method params), it would augment. TypeScript only allows clean merges in the compiler - this is what we rely on, there are no manual merges, the type definitions are all handled by TypeScript.

**Comment by Verin1005** [comment]
> You would need to augmented imports to apply the types, for instance
> 
> ```js
> // augmentation 1
> import './something.js';
> // augmentation 2
> import './somethingElse.js'
> ```
> 
> Assuming they type structures don't conflict, i.e. extra fields added, extra methods added in a pallet (for instance you can never merge Kusama & Polkadot since they do have conflicts inside pallets with regards to method params), it would augment. TypeScript only allows clean merges in the compiler - this is what we rely on, there are no manual merges, the type definitions are all handled by TypeScript, so the rules that apply there apply to augmentations.

This approach seems to be ineffective for importing the `types-lookup` separately. I have tried importing it separately, but it doesn't work. It seems that as mentioned in my description, the configuration in `tsconfig.json` is required for it to be effective.

**Comment by jacogr** [comment]
If you need the tsconbfig, then you are at the hands of how it works - tsconfig will inject the first path where it finds files.

For multiple tsconfig files, you can explore [TypeScript composite projects](https://www.typescriptlang.org/tsconfig#Projects_6255) and [TypeScript references](https://www.typescriptlang.org/tsconfig#references) where a set of files would be tied together (with their respective aliases and augmentations) and combined into a single compilation output.

There is nothing magical about type augmentations - it only uses what TypeScript provides with declaration merging, so is full in the hands of the TS compiler as to setup.

**Comment by grumpygreenguy** [comment]
> (...) the api itself manages multiple augmentations for (...) in a single [overall project](https://github.com/polkadot-js/api/blob/d9ea5ee921841319dde53cc15b37a3820e4ec697/tsconfig.build.json#L9-L11), (...)

noob question --- does that mean it can interoperate between the three chains, or that an application using the api can choose at integration which one to use?

**Comment by grumpygreenguy** [comment]
(bumping to signal my interest in an answer to [this question](https://github.com/polkadot-js/api/issues/5664#issuecomment-1573617186) before the thread gets locked :) )
