### ISSUE TITLE
@polkadot/storage 0.38.11 does not exist

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#567]
The latest published version for @polkadot/storage is 0.38.10 but for other packages are 0.38.11
I am having issue that yarn cannot find @polkadot/storage 0.38.11 and have to manually pick a version as fallback.

From version history you can also see 0.38.6 and few other versions are skipped as well. 

I noticed that packages/type-storage is published lastly, may have some race condition that CI process completes before the version is successfully published?

https://www.npmjs.com/package/@polkadot/storage

It seems like yarn may fail to publish and yet still report as success https://github.com/yarnpkg/yarn/issues/5931 https://github.com/yarnpkg/yarn/issues/6200

**Comment by jacogr** [comment]
It could be the latter since CI completes in all cases - we've been having this for the last couple of days intermittently, seems like every 2nd or so one is ok.

**Comment by jacogr** [comment]
0.38.12 seems to be all there again. I'll update the CI scripts to the latest stable 1.13.0 and see if that improves things (although we have not had any issues before with the version operational atm) - like I mentioned, it has been driving me batty the whole week.

**Comment by xlc** [comment]
You can try verbose output for yarn to confirm if it is indeed the same issue

**Comment by jacogr** [comment]
The last PR hopefully fixed things to be consistent - at least for 0.38.15 all have gone through (manually checked). https://travis-ci.com/polkadot-js/api/builds/97025881

Let's see, hopefully it is not just one of those that works and it continues to work.

**Comment by jacogr** [comment]
Ok, 0.13.0 does something, doesn't just swallow - partial publish here, and at least CI failed, so it is visible - https://travis-ci.com/polkadot-js/api/builds/97104871
