### ISSUE TITLE
Support gzip websocket

### ISSUE THREAD

**Issue by AlexZhenWang** [polkadot-js/api#5677]
Hi, I'm submitting a feature request.

* **What is the motivation for changing the behavior?**
The egress traffic cost is a big part, adding websocket gzip feature can help to reduce the cost of any app that uses polkadotjs.

**Comment by jacogr** [comment]
On the client side the compression is enabled by default on Node.js clients (will only take effect if the server supports it), see https://github.com/websockets/ws#websocket-compression

On the browser (or Deno) side, it will depend on the runtime used. There are no specific constructor options to override, see https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by AlexZhenWang** [comment]
Thanks, @jacogr. I will close this ticket then. I will check our server-side and test. If there is any other issue, might reopen and update.
