### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'toHuman')

### ISSUE THREAD

**Issue by Parikalp-Bhardwaj** [polkadot-js/api#5681]
Hey i am facing the issues using "@polkadot/api-contract": "^10.9.1", and "@polkadot/api": "^10.9.1",

    const wsProvider = new WsProvider("ws://localhost:9944"); ""
    const api = await ApiPromise.create({ provider: wsProvider })
    const key = new Keyring({ type: "sr25519" })
    const alice = key.addFromUri("//Alice");
    console.log("Alice Address ", alice.address)

    const contractAddress = "5D29fZDULKCQx4iYBdx1PqfBVsT6UxZXjjETGaeU2ParZqEX"
    const now = await api.query.timestamp.now();
    const { nonce, data: balance } = await api.query.system.account(contractAddress);
    const nextNonce = await api.rpc.system.accountNextIndex(contractAddress);

    console.log(`${now}: balance of ${balance.free} and a current nonce of ${nonce} and next nonce of ${nextNonce}`);
    const contract = new ContractPromise(api, abi, contractAddress)

    const value = await contract.query.get(alice.address, { value: 0 });
    console.log("Current value: ", value.output.toHuman());

    api.disconnect()

**Comment by jacogr** [comment]
Substrate is a set of Lego blocks - the query details would depend on the actual runtime configuration. In your case, the shape of the return is not as expected. Check the runtime config for how the actual data is setup.

**Comment by Parikalp-Bhardwaj** [comment]
@jacogr thanks for the replay I am not getting it. I have been runing substrate contract node

**Comment by Parikalp-Bhardwaj** [comment]
@jacogr thanks for the replay I am not getting it. I Started substrate contract node
