### ISSUE TITLE
How to decode tuple struct

### ISSUE THREAD

**Issue by xusanduo08** [polkadot-js/api#5683]
Hi there, I need some help please
I set offchain storage from runtime with below code：

data type is a tuple struct
```rust
pub struct IndexingData(Vec<u8>,  u64);
const ONCHAIN_TX_KEY: &[u8] = b"ocw-demo::storage::Tx";

//...
pub fn extrinsics(origin: OriginFor<T>, number: u64) -> DispatchResultWithPostInfo {
      let who = ensure_signed(origin)?;
      let key = Self::derive_key(frame_system::Module::<T>::block_number());
      let data = IndexingData(b"submit_number_unsigned".to_vec(), number);
      sp_io::offchain_index::set(&ONCHAIN_TX_KEY, &data.encode()); // 向offchain DB storage中写入数据
      log::info!("====write to offchain storage");
      Ok(().into())
}
```

and, in brower, I plan to get the storage by the following code:
```js

async function createApi() {
    const wsProvider = new WsProvider('ws://127.0.0.1:9944');
    const api = await ApiPromise.create({ provider: wsProvider });
    const storage = await api.rpc.offchain.localStorageGet("PERSISTENT", "ocw-demo::storage::Tx");
    const u8a = storage.toU8a();
    const stringValue = u8aToString(u8a);
    console.log("======storage", stringValue);

    return api;
}

```

but, I got error code in brower console:
![image](https://github.com/polkadot-js/api/assets/17930163/edf4c7ec-d2aa-4bcd-b547-6be65b771663)

so, how to decode a tuple struct in brower?

**Comment by ntn-x2** [comment]
You can use the `toHuman()` method to show human-consumable information about your `Codec` type.

**Comment by xusanduo08** [comment]
> You can use the `toHuman()` method to show human-consumable information about your `Codec` type.

no use:
```js
async function createApi() {
    const wsProvider = new WsProvider('ws://127.0.0.1:9944');
    const api = await ApiPromise.create({ provider: wsProvider });

    const storage = await api.rpc.offchain.localStorageGet("PERSISTENT", "INDEXING_KEY");
    // const u8Array = storage.toU8a();
    // const stringValue = u8aToString(u8Array);
    console.log(storage.toHuman()); // 0x587375626d69745f6e756d6265725f756e7369676e65647b00000000000000
}
```

The result is :
<img width="513" alt="image" src="https://github.com/polkadot-js/api/assets/17930163/43726f37-251e-4c3c-8262-617a72ec83e8">

**Comment by ntn-x2** [comment]
Then it means the storage element is s HEX string. Hard to help without knowing how the item is being saved to storage in the first place.

**Comment by xusanduo08** [comment]
> Then it means the storage element is s HEX string. Hard to help without knowing how the item is being saved to storage in the first place.
```rust
pub struct IndexingData(Vec<u8>,  u64);
const ONCHAIN_TX_KEY: &[u8] = b"ocw-demo::storage::Tx";
//....
let data = IndexingData(b"submit_number_unsigned".to_vec(), number);
sp_io::offchain_index::set(&ONCHAIN_TX_KEY, &data.encode());
```

I write to storage with code above

**Comment by ntn-x2** [comment]
Well, you are setting the `data.encode()` as the value, meaning you are writing a byte array to storage. So it's totally expected to get a HEX string when decoding the value.. You would have to decode the returned value on the client side.
