### ISSUE TITLE
Unable to Resolve Type within Custom Type Despite createType Accepting It

### ISSUE THREAD

**Issue by jboetticher** [polkadot-js/api#5688]
* **I'm submitting a...**

  - [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

In the following code, the `XcmVersionedMultilocation` can be created with `api.createType`. However, when the `XcmRouterUserAction` type is created with `api.createType`, a warning and error occur:

```
REGISTRY: Unable to resolve type XcmVersionedMultilocation, it will fail on construction
Uncaught (in promise) Error: createType(XcmRoutingUserAction):: Struct: failed on destination: Type:: DoNotConstruct: Cannot construct unknown type XcmVersionedMultilocation
``` 

Seems contradictory as the XcmVersionedMultilocation can be created so one would assume that it is a known type; unsure if this is intended behavior.

```typescript
  const wsProvider = new WsProvider('wss://wss.api.moonbase.moonbeam.network');
  const api = await ApiPromise.create({ provider: wsProvider, types: {
    XcmRoutingUserAction: { destination: "XcmVersionedMultilocation" },
    VersionedUserAction: { V1: "XcmRoutingUserAction" }
  }});

  // Versioned Multilocation can be created
  const versionedMultilocation = api.createType('XcmVersionedMultiLocation', multilocation);
  console.log('XcmVersionedMultiLocation', versionedMultilocation.toHex())

  // XcmRoutingUserAction cannot be created
  const routingUserAction = api.createType('XcmRoutingUserAction', { destination: versionedMultilocation });
  console.log('XcmRoutingUserAction', routingUserAction.toHex())
```

* **Please tell us about your environment:**

  - Version: 10.9.1
  - Environment: 

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [X] TypeScript (4.8.4)
    - [ ] Other

**Comment by jacogr** [comment]
Replace `XcmVersionedMultiLocation ` with `XcmVersionedMultiLocation` (`L` is capitalized as per the exposed type on the runtime)
