### ISSUE TITLE
endianness problem in assetId in signAndSend

### ISSUE THREAD

**Issue by sander2** [polkadot-js/api#5690]
the `signAndSend` function takes an optional assetId. We've been trying to use this for statemine/statemint to pay tx fees using USDT. In our test scripts, we've got it working, but when we deploy our code it doesn't. When inspecting the constructed extrinsics, it seems that there is some inconsistency in endianness used for the serialization. When using `signAndSend(address, { assetId: 1984 })` in our scripts, we see in the polkadotjs explorer that the assetId is `01 c0070000`, which corresponds to `Some(1984)` using little endian encoding. However, when we deploy our code, we see that instead it has `01 000007c0`. If we use `{ assetId: 3221684224 }`, which is `0xc0070000`, it works in the deployed code.

The type of the assetId is `type AnyNumber = BN | bigint | Uint8Array | number | string;`. We tried passing an explicit `Uint8Array` or `string` but that didn't work.

So it seems like somehow there is something wrong with the encoding of this assetId. Any help would be much appreciated

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/5716
