### ISSUE TITLE
Import error import { ApiPromise } from '@polkadot/api';

### ISSUE THREAD

**Issue by snowMan108** [polkadot-js/api#5701]
i'd like to use Polkadot.js api into my decentraland SDK7 project.
But during import Apipromise in my project, i can find 27 errors like this.
"[96mnode_modules/@polkadot/util/u8a/toBuffer.d.ts[0m:[93m1[0m:[93m23[0m - [91merror[0m[90m TS1452: [0m'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`."
Please help me to fix it. 
thanks

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/api/issues/5612

**Comment by snowMan108** [comment]
thanks
