### ISSUE TITLE
Incorrect decoding of signed integers `i8`/`i16` 

### ISSUE THREAD

**Issue by peetzweg** [polkadot-js/api#5702]
The decoding of some scale encoded signed integers values result in the wrong representation in js. 
Generally scale encoded `i8` and `i16` value seem to work fine, however the edge cases, the value of `1` and `i8::MAX` and `i16::MAX` are decoded to the wrong representation in javascript.

This issue bubbles up in one form or another, see related issue section. How can we resolve this once and for all?

[I've created a PR adding testcases for the broken decoding cases #5703.](https://github.com/polkadot-js/api/pull/5703)

* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

```ts
// Scale encoded signed integers of value `1`
const bytes_1i8 = new Uint8Array([1]);
const bytes_1i16 = new Uint8Array([1, 0]);
const bytes_1i32 = new Uint8Array([1, 0, 0, 0]);
const bytes_1i128 = new Uint8Array([
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ]);


api.createType("i8", bytes_1i8).toNumber(); // expected 1, actual -255 ❌
api.createType("i16", bytes_1i16).toNumber(); // expected 1, actual -65535 ❌
api.createType("i32", bytes_1i32).toNumber(); // expected 1, actual 1 ✅
api.createType("i128", bytes_1i128).toNumber(); // expected 1, actual 1 ✅


// Decoding MAX values for signed integers
const bytes_maxi8 = new Uint8Array([127]);
const bytes_maxi16 = new Uint8Array([255, 127]);
api.createType("i8", bytes_maxi8).toNumber(); // expected 127, actual -129 ❌
api.createType("i16", bytes_maxi16).toNumber(); // expected 32767, actual -32769 ❌


// SCALE encoded `0` value of `i8` and `i16`
const bytes_0i8 = new Uint8Array([0]);
const bytes_0i16 = new Uint8Array([0, 0]);
api.createType("i8", bytes_0i8).toNumber(); // expected 0, actual `Input too large. Found input with 9 bits, expected 8`  ❌
api.createType("i16", bytes_0i16).toNumber(); // expected 0, actual `Input too large. Found input with 17 bits, expected 16` ❌
```

[Codesandbox Link](https://codesandbox.io/p/sandbox/eloquent-snyder-x53s8l)

* **Please tell us about your environment:**

  - Version: @polkadot/api@10.9.1
    - [X] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [X] JavaScript
    - [X] TypeScript (include tsc --version)
    - [ ] Other

### Related Issues

+ https://github.com/polkadot-js/api/issues/5483

+ https://github.com/paritytech/contracts-ui/issues/508

+ https://github.com/paritytech/useink/issues/105

**Comment by jacogr** [comment]
Closing, issues addressed at the `util` layer (test cases merged)
