### ISSUE TITLE
Discussion: Switch from `bn.js` to new `BigInt` primitive?

### ISSUE THREAD

**Issue by peetzweg** [polkadot-js/api#5706]
As this repo does not offer a discussion section, I'm opening this request for a discussion here. Curious if it has been considered to switch to the new javascript `BigInt` primitive type instead of the probably more and more outdated version of `bn.js`.

Surely, it's missing immediate benefits but some in the future would be 

+ secure future seamless interoperability with adjacent libraries in the ecosystem,

+ moving dependency to javascript implementation instead of third party keeping bn.js supported on all future platforms

+ more?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

Mostly looking for a state of affairs regarding `BigInt` adoption in pjs.

**Comment by jacogr** [comment]
Eventually.

(The base utils already support `BigInt` as well)
