### ISSUE TITLE
Signing multiplies `assetId` by `2^24`

### ISSUE THREAD

**Issue by Chralt98** [polkadot-js/api#5713]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

We are experiencing weird behaviour when using the `pallet-asset-tx-payment` pallet. When supplying the `signAsync` function with the payload of `assetId` above zero it multiplies by `2^24`. So essentially after signing the transaction the `assetId` is changed to be multiplied by `2^24`. 

The same issue is currently on the asset-hub (aka statemint), so not just on our side.

The expected behaviour is obviously that the `assetId` stays the same after signing.

* **What is the motivation for changing the behavior?**

It seems like there is a type conversion in any way. It could be decoding, encoding, compacting etc...

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [X] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by IkerAlus** [comment]
I think this is related to (or same issue as): https://github.com/polkadot-js/api/issues/5710

**Comment by Chralt98** [comment]
Oh yeah thanks. It's indeed the same issue. Let me close this issue.
