### ISSUE TITLE
[BUG] Contract missing from signAndSend method

### ISSUE THREAD

**Issue by AnmolBansalDEV** [polkadot-js/api#5722]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
When I use `signAndSend` to execute the transaction and destructure `{contract, status}` like [here](https://polkadot.js.org/docs/api-contract/start/code) from the result which is of type `ISubmittableResult`
 I get the TS error: 
`Property 'contract' does not exist on type 'ISubmittableResult'.ts(2339)`

I even went ahead and looked into the type itself and found that `ISubmittableResult` doesn't contain `contract` in it, Have a look [here](https://github.com/polkadot-js/api/blob/ab3b162d7eb96cccef9e3ff057d4dbe96ffe01a3/packages/types/src/types/extrinsic.ts#L13)

I checked the `ChangeLog` but couldn't find when and at which version was it taken out of the type, cause it must've been in there at the time of documentation.

But when I ignored the error and went ahead to run the script, I was able to get the `address` out of the `contract`, so it means that it's still getting assigned but not available in Type. Is there something I'm doing wrong or missing here?

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (Version 5.1.6)
    - [ ] Other

**Comment by jacogr** [comment]
`contract` or `contractEvents` is only available on contracts, using the `api-contract` API.

It extends the normal Submittable result to add the additional field, as can be seen [here for blueprints (where contract is added)](https://github.com/polkadot-js/api/blob/ab3b162d7eb96cccef9e3ff057d4dbe96ffe01a3/packages/api-contract/src/base/Blueprint.ts#L48) and [here for contract calls (where contractEvents are added)](https://github.com/polkadot-js/api/blob/ab3b162d7eb96cccef9e3ff057d4dbe96ffe01a3/packages/api-contract/src/base/Contract.ts#L116-L129)

Depending on the usage and where (i.e. deployment has contract information while contract execution has the events for the method) would depend on what is available.

**Comment by AnmolBansalDEV** [comment]
then how should I resolve this typescript error `Property 'contract' does not exist on type 'ISubmittableResult'.ts(2339)` . I understand that `contract` property is injected at a later stage then how to check if it exists and resolve this TS error.

![image](https://github.com/polkadot-js/api/assets/86472377/4f1591a7-b7c5-4363-9f53-c1fe202cfe2c)

**Comment by AnmolBansalDEV** [comment]
@jacogr can you please help with this.
