### ISSUE TITLE
Expose runtime methods from metadata V15

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#5725]
Last remaining issue from https://github.com/polkadot-js/api/issues/5633

**Comment by xlc** [comment]
I only remember one feature from metadata v15 and it is not supported 😢

**Comment by ntn-x2** [comment]
Hello @TarikGul! How is this scored in priority compared to other tasks? When can we expect work to be completed on this?

**Comment by TarikGul** [comment]
Hey @ntn-x2, this is definitely a high priority task. There has just been a big backlog (bugs, reviews etc.), and learning curve with certain workflows especially with all the packages. Things will really start to gain speed soon, and I will have this on the list for next week. 

Thanks again for your patience.

**Comment by ntn-x2** [comment]
Great, thank you! I will check in with my co-workers if we can support this, since we have digged quite deep already into type augmentation, and having this in and released would greatly benefit us, so we could help out.

**Comment by TarikGul** [comment]
Okay cool, I've started this and am making some ground. PR should be wrapped up next weekish

**Comment by rflechtner** [comment]
> Okay cool, I've started this and am making some ground. PR should be wrapped up next weekish

Very cool! Will this be covering the typegen as well, so that runtime call interfaces are generated from the metadata without any additional input?

**Comment by TarikGul** [comment]
> > Okay cool, I've started this and am making some ground. PR should be wrapped up next weekish
> 
> Very cool! Will this be covering the typegen as well, so that runtime call interfaces are generated from the metadata without any additional input?

So my thought to this is a 2 part solution, first the new runtime api's will be added via `./types/*/*/runtime.ts` since the runtimes default metadata is still v14.

The following runtime apis to be added:

```
ValidateStatement
AssetsApi
ContractsApi
AssetConversionApi
NftsApi
MMRApi
    - leafCount
```

AFAIU the next step will be changing the `typegen` to be able to read the `apis` field inside of the metadata itself. This will be a bigger change though as the structure has changed from v14 to v15.
