### ISSUE TITLE
Westmint block #5482732 can not be decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5734]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsys.ibp.network%2Fwestmint#/explorer/query/5482732
![PXyyRhbBw5](https://github.com/polkadot-js/api/assets/2264908/e2d0a76a-41f5-4ff5-ae96-692d1051e81f)

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by Imod7** [comment]
I can confirm that I see the same error message when requesting 
- the same block (`5482732`) 
- and while also connected to `Westend Asset Hub` 

either by : 

- using [polkadot js apps](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestmint-rpc.dwellir.com#/rpc) (RPC call `chain` > [getBlock](https://polkadot.js.org/docs/substrate/rpc/#getblockhash-blockhash-signedblock))
- or Sidecar (endpoint `blocks/5482732`)

**Comment by bee344** [comment]
This should be closed by #5752

**Comment by jacogr** [comment]
Closing on the back of the comments. Feel free to re-open if there is another issue not solved by the PRs.
