### ISSUE TITLE
where is the new release of polkadot-js

### ISSUE THREAD

**Issue by nuaays** [polkadot-js/api#5735]
Just a question, I see it is a long time since the last release of this repo https://github.com/polkadot-js/api, is there anything we miss: move to other repo or there is no update for this repo?

  - [ ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [*] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ * ] Other (limited support for other environments)

  - Language:

    - [ * ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
This should probably be closed in favor of: https://github.com/polkadot-js/api/issues/5704
