### ISSUE TITLE
Error decoding Metadata v15 from hex bytecode

### ISSUE THREAD

**Issue by nicksinch** [polkadot-js/api#5736]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When trying to initialize **Metadata V15** from the **api** using its hex code located [here in the repo](https://github.com/polkadot-js/api/blob/ab3b162d7eb96cccef9e3ff057d4dbe96ffe01a3/packages/types-support/src/metadata/v15/substrate-hex.ts#L8C18-L8C18) , decoding fails with the following error: 

`Error: decodeU8aStruct: failed at 0x0f790e000c1c73705f636f7265186372… on metadata (index 2/2):: decodeU8aStruct: failed at 0x04990235027505590d2048436865636b… on extrinsic (index 3/5): {"type":"SiLookupTypeId","version":"u8","signedExtensions":"Vec<SignedExtensionMetadataV14>"}:: decodeU8aStruct: failed at 0x0235027505590d2048436865636b4e6f… on signedExtensions (index 3/3): Vec<SignedExtensionMetadataV14>:: Vec length 490769728 exceeds 65536`

The code used to initialize Metadata:

```javascript
const { Metadata, TypeRegistry } = require('@polkadot/types');

async function main () {
    const metadataStaticV15 = "<metadata_v15_substrate_hex_from_the_link>"

    const registry = new TypeRegistry();
    
    const metadata = new Metadata(registry, metadataStaticV15);
    console.log(metadata);
}
```

Also, If instead this hex code, we take the one from the **latest node-template.wasm**, it fails with another error.

**All versions below 15** have no problems and decoding works as expected.

  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
It is in master, there has not been a release made for a whil;e - it will come when I get over my hump. (There are other issues logged as to "when is there a release")
