### ISSUE TITLE
XCM crates squating breaks types

### ISSUE THREAD

**Issue by wirednkod** [polkadot-js/api#5741]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Due to some [XCM crates squating](https://crates.io/crates/xcm) there is a [renaming of crates](https://github.com/paritytech/polkadot-sdk/pull/1241/files). As a result the latest metadata are having a `Staking` prefix which (apparently) [broke teleporting in test faucet](https://github.com/paritytech/polkadot-testnet-faucet/pull/354)

Normally this "check" on client side should not take place and types (e.g. `XcmVersionedMultiLocation` should not appear like `StakingXcmVersionedMultiLocation`)

* **What is the motivation for changing the behavior?**

Current breaking of test faucet (rococo) and possible breakings in other apps

* **Please tell us about your environment:**

  - Version:  10.10.1
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by bkchr** [comment]
@jacogr appending  the `paths` in front of the types is really not a great idea. I think you probably tried to make them unique in this way. However, this is no guarantee that there doesn't exist a different type with the same name + prefix.

**Comment by bkchr** [comment]
I think users probably only require the type when they want to instantiate a `Call`. Instead of them trying to instantiate the `type` on their own, `polkadot-js` should give them the type by calling something like `type_for("my_call", index)`. Then they could for example get the correct type for `xcm` to instantiate it.

**Comment by jacogr** [comment]
There are no clashes - when a clash happens, it uses the Lookup id.

**Comment by bkchr** [comment]
I mean I get that the code works as expected. However, I think that people should not write their code in this way. They should not try to search for a type by name and instead get the type they are interested in by index from a call. This should be much more stable. I mean I'm also open to other suggestions. However for decoding we shouldn't have this problem as polkadot-js knows the types and can decode it properly. The only problem should be around encoding for transactions that we have seen now.

**Comment by jacogr** [comment]
You are _never_ supposed to work with the types directly.

So you should never do -

```js
const something = api.createType('SomeType', { foo: 'bar' });
...
await api.tx.somewhere.something(something);
...
```

In _all_ cases you should just let the API create the types, aka -

```js
await api.tx.somewhere.something({ foo: 'bar' });
```

So if you don't use the internal `createType` (based on names) yourself, you will be into a world of hurt. Never do that. Let the API create since it always knows what is exposed.

So we can go round and round, it is stays a wontfix.

**Comment by bkchr** [comment]
Ahh okay thank you!

**Comment by wirednkod** [comment]
Thank you @jacogr and @bkchr . Will close this here

**Comment by mutantcornholio** [comment]
@jacogr is that articulated somewhere? Here, at least.
https://polkadot.js.org/docs/api/start/types.create

Until the issue happened, we had no idea that this is a bad practice, and I can easily find tons of cases where people do it

**Comment by TarikGul** [comment]
Just to add: I do think there is merit behind using `api.createType`. In a static environment for testing it can be incredibly useful. Especially when you want to mock storage queries from the chain for testing purposes.

Here is an example below:

```typescript
// This was taken directly from polkadot-js
export function createApiWithAugmentations(metadataHex: `0x${string}`): ApiPromise {
	const registry = new TypeRegistry();
	const metadata = new Metadata(registry, metadataHex);

	registry.setMetadata(metadata);

	const api = new ApiPromise({
		provider: new WsProvider('ws://', false),
		registry,
	});

	api.injectMetadata(metadata, true, registry);

	return api;
}

const mockApi = createApiWithAugmentations(<some_metadata>);

const getSystemSafeXcmVersion = () =>
	Promise.resolve().then(() => {
		return mockApi.registry.createType('Option<u32>', 2);
	});
	
const adjustedMockApi = {
   registry: someRegistry // This should be of `new TypeRegistry()` then have metadata set.
   query: {
       polkadotXcm: {
           safeXcmVersion: getSafeXcmVersion
       }
   }
}
```

I also think it can be really useful when constructing the `Call` type or `ExtrinsicPayload` types for decoding. But generally speaking I do agree that in the case of building a `tx.something` it makes sense to just pass the params as is.

**Comment by IkerAlus** [comment]
> @jacogr is that articulated somewhere? Maybe it should be mentioned here, at least? https://polkadot.js.org/docs/api/start/types.create
> 
> Until the issue happened, we had no idea that this is a bad practice, and I can easily find tons of cases where people do it

@TarikGul just created a PR for said doc page: https://github.com/polkadot-js/docs/pull/455
