### ISSUE TITLE
Disable ESM/CJS double import warnings

### ISSUE THREAD

**Issue by wottpal** [polkadot-js/api#5744]
Hey @jacogr,

I'm fully aware of https://github.com/polkadot-js/api/issues/5636 and don't want to reiterate again on this PITA discussion 😅

We have the problem in our project too and they are not bypassable atm. But we are aware and have some refactorings planned that will resolve it, but they will take some time. In the meantime, all these warnings are just so painfully annoying during the development process and we would like to disable those as you suggested here:

> [Remove the warning](https://github.com/polkadot-js/common/blob/b73b96e412cd1333143efe2dc64f1269c12756e8/packages/util/src/versionDetect.ts#L120) about dual usage (it will still occur, but we are basically just "hiding" it)

I would suggest I do a PR to [`polkadot-js/common`](https://github.com/polkadot-js/common) introducing a check if an environment variable (e.g. `POLKADOT_JS_DISABLE_PACKAGE_WARN`) is set. And if yes, it doesn't print anything and skips the tests. This package is used within all other `@polkadot/*` packages, correct? So this change would be only necessary there.

**Comment by jacogr** [comment]
Sure, PRs welcome.

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/common/pull/1896
