### ISSUE TITLE
createType(Extrinsic):: createType(ExtrinsicUnknown):: Unsupported signed extrinsic version 31

### ISSUE THREAD

**Issue by flipchan** [polkadot-js/api#5749]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm trying to broadcast a tx:
```typescript

const pa_tx = create_tx(); // return tx obj: api.tx.balance.transfer
 console.log(`rawtx:`, pa_tx.toHex());
const s1 = u8aToHex(alice.sign(pa_tx.toHex())); // sign tx
const broadcast = await api.rpc.author.submitExtrinsic(signedExtrinsic);

```

Error while broadcasting:
```
13: author.submitExtrinsic: Hash
createType(Extrinsic):: createType(ExtrinsicUnknown):: Unsupported signed extrinsic version 31
```

How can i broadcast a api.tx?
Should i wrap the tx in a type or?(`const r2= api.registry.createType('Extrinsic', tx);`)

  - Version:
 npm -v:   
8.5.5
  - Environment:
`"@polkadot/api": "^10.9.1",`
    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Your signing is incorrect - you don't sign the extrinsic, you need to sign an extrinsic payload. (Which includes information non in the actual transaction, all based on the on-chain signed extensions, e.g. genesisHash, blockHash for mortal transactions, transaction version, etc.)

Use the `tx.sign` (which constructs a correct payload) and pass a relevant signer.

**Comment by flipchan** [comment]
@jacogr thanks, i was able to solve this, what is the best way of signing just a string containing a tx? with the tx object there is .signasync which works great, what is the best way to sign a transaction as a hex string?
