### ISSUE TITLE
Statemine blocks 5753828, 5753849 can not be decoded

### ISSUE THREAD

**Issue by wliyongfeng** [polkadot-js/api#5750]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemine-rpc.dwellir.com#/explorer/query/5753828
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemine-rpc.dwellir.com#/explorer/query/5753849
![PcRhQicaTq](https://github.com/polkadot-js/api/assets/2264908/60c43301-4063-450e-bd5b-94dc0570f5d1)

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by wliyongfeng** [comment]
@jacogr Could you take a look at this issue and #5734? They are crucial to explorers who depend on polkadot api.

**Comment by valentunn** [comment]
This seems to be related to `ChargeAssetTxPayment` signed extension being used in transactions. Our guess is that API doesn't infer types of signed extensions from runtime metadata correctly. For `ChargeAssetTxPayment`, its type is a struct with `tip` and `assetId`. Type for `assetId` got changed from `u32` to `MultiLocation` with most recent Kusama/Westmint upgrades
This introduces issues for our indexer as well

**Comment by valentunn** [comment]
@wliyongfeng we found a workaround which uses typesBundle overrides. This snippet is for rococo but it works in the same way in Kusama Asset Hub, adjusting runtime versions and specName

``` ts
import { OverrideBundleDefinition } from "@polkadot/types/types";

const definitions: OverrideBundleDefinition = {
  types: [
    {
      minmax: [0, 10004],
      types: {
        NovaAssetId: "Option<AssetId>"
      },
    },
    {
      minmax: [10005, null],
      types: {
        NovaAssetId: "Option<MultiLocation>"
      },
    },
  ],
  signedExtensions: {
    ChargeAssetTxPayment: {
      extrinsic: {
        tip: 'Compact<Balance>',
        // eslint-disable-next-line sort-keys
        assetId: 'NovaAssetId'
      },
      payload: {}
    }
  }
};

export default { typesBundle: { spec: { "statemine": definitions } } };
```

**Comment by wliyongfeng** [comment]
@valentunn I tried and it works. It's very nice, love you.

**Comment by wliyongfeng** [comment]
@jacogr Could you release a new version of `@polkadot/api`? So we can update our dependencies.
