### ISSUE TITLE
Support `SkipCheckIfFeeless` extension for substrate node

### ISSUE THREAD

**Issue by gupnik** [polkadot-js/api#5751]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

https://github.com/paritytech/polkadot-sdk/pull/1926 added `SkipCheckIfFeeless` extension. It needs to be added to Polkadot JS API.

* **What is the motivation for changing the behavior?**

To support feeless payments for certain cases. Please refer to [SkipCheckIfFeeless](https://github.com/paritytech/polkadot-sdk/pull/1926) for more details.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by bkchr** [comment]
@jacogr could you please add this? It doesn't require any data being added to the tx or signed data.

**Comment by gupnik** [comment]
Thanks @bkchr @jacogr!
