### ISSUE TITLE
When using a front-end framework for multi-end development, an error occurred when compiling the Android app using this plugin

### ISSUE THREAD

**Issue by cjh1129434866** [polkadot-js/api#5768]
I use a domestic framework for hybrid development of apps called uniapp. I can use your plug-in to run normally on the h5 terminal, but there is a blank screen on the Android terminal and error information is reported on the terminal.
I think the plugin uses the window object on the browser side, so the error is reported on the Android side. Can the official solve this problem?

_The error message is as follows:_
### **reportJSException >>>> exception function:createInstanceContext,  exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError:  Cannot read property 'location' of undefined
at getAbsoluteUrl (app-service.js:16233:19)**

**Comment by TarikGul** [comment]
Closing as this is not something polkadot-js supports, are aims to support in the future.
