### ISSUE TITLE
conflicting and duplicate types when generating types for multiple networks, in the same project

### ISSUE THREAD

**Issue by Muhammad-Altabba** [polkadot-js/api#5773]
Generating types for multiple networks in the same project results in errors because of some conflicting types and some other duplicate types. You can check the manual fixing done at: https://github.com/conx3/hackathon-2023-winter/commit/ddb35ec68ffb73445bd8c268eef16573787ca808

Or, is there a possible configuration to not have conflicts? I could not find something related to this in the docs.

Thanks,

* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Generating types from multiple edgeware files, from different networks, results in multiple build errors. To check, try generating the types for polkadot, kusama and substrate networks. The command `yarn generate:types` at: https://github.com/conx3/hackathon-2023-winter/commit/7ab1070eedc0b18f641123d87a0ba3f05749c7f4#diff-6f3e8b65d14ae9d27e7d9e50db9ca7225cf6a02e18911e883137a3598fcfe1baR29 do this. And then multiple build errors would came. 
[Note: you will see lots of errors also related to https://github.com/polkadot-js/api/issues/5765. Ignore them please and check the errors for the duplicate and conflicting declarations]

* **Please tell us about your environment:**
Here is the project: https://github.com/conx3/hackathon-2023-winter/tree/web3-plugin-polkadot/projects/32-web3-plugin-polkadot 
And you may check the specific commit: https://github.com/conx3/hackathon-2023-winter/commit/7ab1070eedc0b18f641123d87a0ba3f05749c7f4

  - Version:     "@polkadot/typegen": "^10.11.1"
  - Environment:

    - [x] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript: "typescript": "^5.3.3"
    - [ ] Other

**Comment by jacogr** [comment]
It is certainly intended - the typegen is not a free for all - if networks have different types, it would certainly conflict.

The api itself generates types for Substrate, Kusama & Polkadot. They are completely split (so it is possibly), but it is certainly not intended that you can include all three at any point in time. Types are static and cannot be magically injected into TS based on a per-network basis.

Bacuse of the static nature -

1. You can generate types for all networks you desire
2. You can only include one network per codebase to allow TS to type-check
