### ISSUE TITLE
Block with more than u16 events fails to be decoded

### ISSUE THREAD

**Issue by Leouarz** [polkadot-js/api#5782]
* **I'm submitting a ...**

  - [x] Bug report

* **What is the current behavior and expected behavior?**

When a block has more than 64 * 1024 events, it fails to be decoded by the api and makes other component panic (like the polkadot UI).
To reproduce, I connected to a local polkadot node 1.0.0 and sent 4 batch of 8500 remark with events all in the same block.
The node will process it correctly, but on the api side, if i try to decode the events, i will get an error : 
`Error: Unable to decode storage system.events:: createType(Vec<FrameSystemEventRecord>):: Vec length 72264 exceeds 65536`
This is coming from [this file](https://github.com/polkadot-js/api/blob/master/packages/types-codec/src/base/Vec.ts#L12).
Here's also my [initial question on Stack exchange](https://substrate.stackexchange.com/questions/10825/how-to-handle-blocks-with-more-than-u16-events).

* **What is the motivation for changing the behavior?**

With the rise of new types of chain, rollups and even inscriptions, block can definitely contain a lot of events and polkadot api is the main library to interract with such chains. This issue is not reproduced in subxt for example. If it's a choice, I would be interested to know the motivations.

* **Please tell us about your environment:**
  - Version: 
    - Polkadot API : ^10.10.1
    - Polkadot node : v1.0.0
  - Environment: Ubuntu 22.04

    - [x] Node.js

  - Language:

    - [x] TypeScript (include tsc --version : ^5.2.2)

**Comment by jamesbayly** [comment]
Hi @IkerAlus is there an update here? It's starting to impact us

**Comment by TarikGul** [comment]
I am happy to start taking a look at this, but that being said, I am hesitant to just change the `MAX_LENGTH` for Vec's without some heavy testing. 

Not sure what the residual affects could be, but I am sure Jaco put that there for good reason (I hope).

**Comment by TarikGul** [comment]
Pushing this issue to the top of the queue, I'll be expediting this today and tomorrow.

**Comment by TarikGul** [comment]
The source of the changes above: https://github.com/polkadot-js/api/pull/2670

**Comment by TarikGul** [comment]
This is also the first time it was introduced: https://github.com/polkadot-js/api/commit/7b04ea0bfeea7b3fc23abde32fe46fe8c0676bc3#diff-0d925a4fc950736275a23f6d43d19c518deab3978a724752c54ad22202f7454f

**Comment by valentunn** [comment]
Hey @TarikGul regarding the new value - would be ideal to increase it at least to 256k as we have seen chains with 144k events in a single block already in production 
I am thinking about maybe 512k as a safe ground that will allow this problem to not be brought up in the near future (hopefully). What do you think?

**Comment by TarikGul** [comment]
> Hey @TarikGul regarding the new value - would be ideal to increase it at least to 256k as we have seen chains with 144k events in a single block already in production I am thinking about maybe 512k as a safe ground that will allow this problem to not be brought up in the near future (hopefully). What do you think?

That would be ideal and I hope it's that straight forward: I am looking into the feasibility right now. Currently it uses [`compactFromU8aLim`](https://github.com/polkadot-js/common/blob/master/packages/util/src/compact/fromU8a.ts#L72-L109) which has limitations attached to it which is where I think the original `MAX_VALUE` comes from.

**Comment by TarikGul** [comment]
Made some local scripts to test, and work on this. Will post some of the workthrough I've done tomorrow. But for now its getting late!

**Comment by TarikGul** [comment]
This is the script I am currrently using: 

```javascript

require('@polkadot/api-augment');

const { ApiPromise, WsProvider } = require('@polkadot/api');
const { Keyring } = require('@polkadot/keyring');
const { cryptoWaitReady } = require('@polkadot/util-crypto');

const main = async () => {
	await cryptoWaitReady();

	const keyring = new Keyring();
	const alice = keyring.addFromUri('//Alice', { name: 'Alice' }, 'sr25519');

    const api = await ApiPromise.create({
        provider: new WsProvider('ws://127.0.0.1:9944')
    });

    const txs = [];
    for (let i = 0; i < 100000; i++) {
        txs.push(api.tx.system.remark('0x00'))
    };

    const unsub = await api.tx.utility.batchAll(txs)
        .signAndSend(alice, (result) => {
            console.log(`Current status is ${result.status}`);
        
            if (result.status.isInBlock) {
                console.log(`Transaction included at blockHash ${result.status.asInBlock}`);
            } else if (result.status.isFinalized) {
                console.log(`Transaction finalized at blockHash ${result.status.asFinalized}`);
                unsub();
            }
        });
};

main().finally(() => process.exit());
```

**Comment by TarikGul** [comment]
So i created a successful transaction, and submitted it with 34k events.

![Screenshot 2024-06-11 at 7 56 09 PM](https://github.com/polkadot-js/api/assets/47201679/7424b65a-e572-482b-acee-0341cdd94011)

Then using sidecar (just a RESTful wrapper around pjs to query and see if I would get any errors querying it, and I didnt).

<img width="335" alt="Screenshot 2024-06-11 at 7 57 14 PM" src="https://github.com/polkadot-js/api/assets/47201679/f90f6eae-448a-4b41-97f7-55a7da4704a4">

**Comment by valentunn** [comment]
Hey @TarikGul you can use this block: https://bittensor.com/scan/block/3014340 to test decoding of 144k events

**Comment by TarikGul** [comment]
@valentunn What chain is that for?

**Comment by KarimJedda** [comment]
@TarikGul it's for Bittensor, sending you some RPC endpoints to try out.

**Comment by Leouarz** [comment]
@TarikGul Hey, any news on this ?

**Comment by rzadp** [comment]
I've been looking into it.
I have reproduced it locally by increasing the amount of items in the [snippet above](https://github.com/polkadot-js/api/issues/5782#issuecomment-2161779791):

```
(...)
  for (let i = 0; i < 10_922; i++) { // utility.batchedCallsLimit
      txs.push(api.tx.system.remark('0x00'))
  };

  const batches = [
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
      api.tx.utility.batch(txs),
  ]
(...)
```

![Screenshot 2024-07-30 at 12 20 27](https://github.com/user-attachments/assets/810df4b5-ead0-4172-82d9-44f2ac5743fb)

---

I've been looking into how [`compactFromU8aLim`](https://github.com/polkadot-js/common/blob/c1b8098b9eb88aad84e4c0465b0c8bddcd12abf7/packages/util/src/compact/fromU8a.ts) works. Can't be 100% sure but I believe it's OK to increase our limit.
