### ISSUE TITLE
About the callback issue encountered by nodejs when using @ polkadot/API

### ISSUE THREAD

**Issue by HanSXY** [polkadot-js/api#5783]
#### Using nodejs to call @ polkadot/API version "^ 10.11.1"
There were some occasional issues during use, please refer to the following code snippet

```
import { ApiPromise, WsProvider, Keyring } from '@polkadot/api';
import { cryptoWaitReady } from '@polkadot/util-crypto';
const api = await ApiPromise.create();
await api.tx.utility
  .batch(Array)
  .signAndSend( accountFromKeyring, async ( { events = [], status , dispatchError  } ) => {
    if (status.isInBlock) {
      console.log('number1');
      events.forEach( async ({ event: { method, data: [error] } }) => {
        if (method == 'BatchInterrupted') {
          console.log('number2');
        } else if(method == 'BatchCompleted'){
          console.log('number3');
        }
      });
    }
  })
```
**In the above code execution, I can obtain the print log of number1, but sometimes I cannot obtain the print log of number2 or number3. Is there a problem with my writing style?**

**Comment by TarikGul** [comment]
This could be because you aren't covering all the events that could possibly happen.

https://github.com/polkadot-js/api/blob/64e30dd0a70cf98d4d243c1dd3d78681b5f3566a/packages/api-augment/src/kusama/events.ts#L1421-L1434
