### ISSUE TITLE
Connecting to Polkadot/Api 

### ISSUE THREAD

**Issue by peterkim2014** [polkadot-js/api#5788]
- [ ] Bug report
  - [ ] Feature request
  - [ X] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I'm requesting with the local node endpoint for the websocket; however, I'm not able to establish a connection with the endpoint. 

Current Behavior: 
I'm trying to retrieve the api through inputting the local endpoint into the websocket. However, it returns this message: API-WS: disconnected from ws://127.0.0.1:9944: 1006:: The operation couldn’t be completed. Connection refused. 

When I use the Polkadot/Substrate Portal, the local node automatically connects, so I believe I am instantiating the node correctly, just not able to connect it in my codebase. 

Expected Behavior: 
Establish a connection with the local node endpoint.

* **What is the motivation for changing the behavior?**

Currently, I'm trying to establish a connection, and retrieve data. However, I cannot go to the next step, due to this issue. 

![Screen Shot 2024-01-30 at 6 11 58 PM](https://github.com/polkadot-js/api/assets/109382681/b5f454f4-5d3a-40f5-b008-8411a4137a99)

![Screen Shot 2024-01-30 at 6 15 42 PM](https://github.com/polkadot-js/api/assets/109382681/6704b5f7-ec4f-4a23-ab15-f59929312ca7)

* **Please tell us about your environment:**

Environment:
Expo React Native v49.0.22
Node.js v21.6.1
@polkadot/api": "^10.11.2"

  - Version:
  - Environment:

    - [ X] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ X] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by peetzweg** [comment]
You state that your environment is react-native/expo? Maybe the node is not running on the same machine or as your mobile app? 

If so you would need to use the proper ip address of the system you want to connect to instead of 127.0.0.1 aka localhost. Probably something like ws://192.168.0.10:9944` or so.

**Comment by peterkim2014** [comment]
Worked like a charm! Thanks a bunch @peetzweg
