### ISSUE TITLE
Arithmetic operations on balance.free throwing an error 

### ISSUE THREAD

**Issue by akanksha-atrey** [polkadot-js/api#5808]
I am trying to get the account balance starting with an API query and perform some arithmetic on the value of balance.free.
```
const { nonce, data: balance } = await api.query.system.account(accountId);
console.log(Math.floor(balance.free/1000000000000));
```
However, I am getting this error:

`The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type. ts(2362)`

How can I fix this? Note, this error only shows up after importing `import '@polkadot/api-augment';` as per issue #4450.

Using @polkadot/api 10.11.3.

**Comment by TarikGul** [comment]
The `balance.free` [type](https://github.com/polkadot-js/api/blob/master/packages/types-augment/src/lookup/types-substrate.ts#L27) is defined as a `u128` which can be seen as an `object` primitive JS type. You can run `console.log(typeof balance.free)` to see that output. It's important to note that the JS [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) type forces us to treat potentially large numbers such as a u128 differently. 

An example with working code:

```javascript
require('@polkadot/api-augment');

const { ApiPromise, WsProvider } = require('@polkadot/api');
const BN = require('bn.js');

const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://rpc.polkadot.io')
    });

    await api.isReady;

    const { data: balances } = await api.query.system.account('16ZL8yLyXv3V3L3z9ofR1ovFLziyXaN1DPq4yffMAZ9czzBD');
    const divNum = new BN('1000000000000');
    const math = balances.free.toBn().div(divNum);
    console.log(math.toString());
};

main().finally(() => process.exit());
```

**Comment by akanksha-atrey** [comment]
Thank you for the prompt reply, Tarik! That did the trick.
