### ISSUE TITLE
`ApiPromise.create` doesn't resolve with the `ScProvier`

### ISSUE THREAD

**Issue by josepot** [polkadot-js/api#5816]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Current behaviour is that the following Promise doesn't resolve:

```ts
import { ApiPromise, ScProvider } from '@polkadot/api';
import * as Sc from "@substrate/connect"

const provider = new ScProvider(Sc, Sc.WellKnownChain.polkadot)
ApiPromise.create({provider}).then(console.log, console.error)
```
The expected behaviour is that the promise resolves 🙂 .

**Comment by kratico** [comment]
I think this is related to https://github.com/smol-dot/smoldot/issues/1694 which will be solved once https://github.com/polkadot-js/api/pull/5817 is merged

**Comment by josepot** [comment]
Closing this as it seems that the [latest release of substrate-connect solves this](https://stackblitz.com/edit/stackblitz-starters-gpwptz?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js&title=node.new%20Starter). Thanks @kratico !
