### ISSUE TITLE
[Tracking upstream] Remove `erasStakersClipped` from `api.derive.staking._erasExposure`  when applicable

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#5819]
Via https://github.com/polkadot-js/api/issues/5771 `api.derive.staking._erasExposure` needed to change its internal functionality to accommodate the new changes. Currently the derive has forward and backwards compatibility via https://github.com/polkadot-js/api/pull/5815. 

That being said, once all relay chain runtimes are updated to 1004000 it is safe to say we can remove the `erasStakersClipped`, and have support for only `erasStakersPaged`. This means we can also adjust the types to ensure there is a single source of truth for the `_eraExposure`. 

This is a tracking issue to ensure we stay on top of it and will be added to the projects board tracking column.

**Comment by ScepticMatt** [comment]
how would you get erasStakersClipped from api.at(hash) then? I haven't been able to use derive API with historical data

**Comment by TarikGul** [comment]
> That being said, once all relay chain runtimes are updated to 1004000 it is safe to say we can remove the erasStakersClipped, and have support for only erasStakersPaged

This is referring only to the functionality in the derive, not `api.query`

**Comment by TarikGul** [comment]
I changed the title to be more less confusing.

**Comment by TarikGul** [comment]
Keeping `erasStakersClipped` as a future backwards compatible even though the migration is done with Polkadot. I just want to ensure any other chains who use this functionality don't have their api broken.
