### ISSUE TITLE
Support `minimumPeriod` of `0`

### ISSUE THREAD

**Issue by bkchr** [polkadot-js/api#5826]
With the switch to async backing, parachains will set a `minimumPeriod` of `0`. (Not all, but some).

This currently breaks transaction signing here: https://github.com/polkadot-js/api/blob/8dbc373ac573e8c7aea580e8d17d634e40f01956/packages/api-derive/src/tx/signingInfo.ts#L88

We should check that if `minimumPeriod` is `0` and then just also use the fallback duration. On top of that we should use `SlotDuration` from Aura: https://github.com/paritytech/polkadot-sdk/pull/3732 as we use `ExpectedBlockTime` from Babe.

**Comment by bkchr** [comment]
@TarikGul could we get a quick fix for this?

**Comment by TarikGul** [comment]
Just woke up :), @pepoviola - Thanks for the PR. Going to check it all right now!

**Comment by TarikGul** [comment]
rel: https://github.com/polkadot-js/apps/issues/9970

**Comment by TarikGul** [comment]
Once #5827 goes in we will do a patch release.

**Comment by TarikGul** [comment]
Released in [10.12.3](https://github.com/polkadot-js/api/releases/tag/v10.12.3)
