### ISSUE TITLE
@polkadot/api@10.12.5 references non-existing versions

### ISSUE THREAD

**Issue by josepot** [polkadot-js/api#5841]
The CI of polkadot-api, which relies on a `npx @zombienet/cli` command, started failing a couple of hours ago for no apparent reason. After some digging, it turns out that the reason why it stopped working is because of the recent release of `@polkadot/api@10.12.5`:

![image](https://github.com/polkadot-js/api/assets/8620144/77db380c-b6ab-4c1d-a667-add1c47a83ae)

which references a bunch of dependencies:

<img width="422" alt="image" src="https://github.com/polkadot-js/api/assets/8620144/69aa4e44-00ed-4ce6-b7e9-9a42c94ec4c1">

that have not yet been published:

![image](https://github.com/polkadot-js/api/assets/8620144/f1224535-977a-452e-ba10-821bede33c6f)

Please, publish those versions ASAP, because `@polkadot/api@10.12.5` is a patch release. Therefore, all libraries that reference version "^10.12.x" of `@polkadto/api` are now broken. I mean, sure... the lock files will prevent some incidents, but this is still a serious issue. Eg what just happened to us while using `npx @zombienet/cli`.

## EDIT:

Actually, if it's not too late, the best solution IMO would be to perform a:

```bash
npm unpublish @polkadot/api@10.12.5 --force
```

Mainly for 2 reasons:
1) According to the release notes: this should have been a minor release, rather than a patch release.
2) The release is completely broken, so if possible it's better to just unpublish it for now.

## EDIT II:

[This job](https://github.com/polkadot-js/api/actions/runs/8529359176/job/23364972975) has been running for more than 3 hours and 30 mins, and it seems to keep on trying to re-publish a wrongly published release. I think that it should be manually stopped.

## EDIT III:

I ended up taking the liberty of canceling the workflow, given the fact that [it was obvious that there was no one monitoring it](https://github.com/polkadot-js/api/actions/runs/8529359176/job/23364972975#step:4:19713), and the npm servers had been responding with `403` and `429` errors for hours.

**Comment by TarikGul** [comment]
Weird thanks for notifying of this. I didn't get any notification, and CI process had successfully published the tags, and release therefore I assumed the automation had finished correctly. Not good.

**Comment by TarikGul** [comment]
latest release fixes this: https://github.com/polkadot-js/api/releases/tag/v10.12.6

Thanks a ton for the info and reporting this 🙏

**Comment by josepot** [comment]
Thanks! I can confirm that the release of 10.12.6 has solved the issue that we had with the CI, and now `npx @zombienet/cli` works again 🎉. I'm closing this issue.

However, there is IMO a learning lesson from this: which is that the `@polkadot/*` packages should be published in topological order. Otherwise, this kind of problems could happen again.
