### ISSUE TITLE
Add decoration of runtimeApis

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#5845]
rel: https://github.com/polkadot-js/api/issues/5725

The next step in getting runtimeApis from the metadata is to have them decorated at runtime via the metadata. This can be seen as similar to [`decorateExtrinsics`](https://github.com/polkadot-js/api/blob/master/packages/types/src/metadata/decorate/extrinsics/index.ts#L49). This should only be available for V15. 

Once this issue is complete we can then add it to the static typegen.

**Comment by TarikGul** [comment]
This would actually replace `decorateCalls` inside of the api base decoration.

**Comment by peetzweg** [comment]
@TarikGul Is there a way to manually add runtime API calls for now? 

I tried using the `runtime` option during `ApiPromise` creation like below. However, it's not even added to `ApiPromise.call` (`undefined is not an object`), so probably not the way how to do it in the first place. 🤔 

```ts
import { DefinitionsCall } from "@polkadot/types/types";
import { ApiPromise, WsProvider } from "@polkadot/api";

const wsProvider = new WsProvider(`wss://...`);

export const api = await ApiPromise.create({
  provider: wsProvider,
  runtime: {
    camelCasedPalletNameApi: [
      {
        version: 1,
        methods: {
          camelCasedRuntimeFn {
            description: "This is my function",
            params: [],
            type: "Balance",
          },
        },
      },
    ],
  } as DefinitionsCall,
});

const result = await pjsApi.call.camelCasedPalletNameApi.camelCasedRuntimeFn();
console.log({result})
```

**Comment by decentration** [comment]
this should go in V16

**Comment by josepot** [comment]
> this should go in V16

This is already available in V15... 🤷
