### ISSUE TITLE
Coretime Endpoint doesn't work

### ISSUE THREAD

**Issue by poppyseedDev** [polkadot-js/api#5848]
**I'm submitting a BUG**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

The endpoint `wss://rococo-coretime-rpc.polkadot.io` is currently producing an assertion error. Currently you are not able to do any sort of transaction, other times (for example yesterday) this wasn't an issue and things were working fine.

* **Please tell us about your environment:**

  - Version:
      "@polkadot/api": ">=10",
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version) ^5.3.2
    - [ ] Other

**Comment by TarikGul** [comment]
I don't have any ROC, so I am not able to test any transactions, yet... (I will try and get some soon), but for general purposes I am seeing no issues connecting to the chain etc via the websocket URL you posted.

Can you provide some of the assertion errors so I can investigate it further?

**Comment by poppyseedDev** [comment]
It this error, usually it happens when there is some issue with the compilation of the node:
```
😞 Transaction Failed: Error: Assertion failed
```

**Comment by poppyseedDev** [comment]
You can use the Rococo testnet faucet -> Choose Rococo network, chain Coretime
```
https://faucet.polkadot.io/
```

**Comment by TarikGul** [comment]
Yea I was able to send a transaction fine on Rococo Coretime, used the same WS url you gave to.

**Comment by TarikGul** [comment]
Is this still an issue for you?

**Comment by poppyseedDev** [comment]
So it seems that you have to constantly have the package of polkadot.js api updated to the latest version, otherwise the metadata doesn't match up and the transactions won't go through.

Yes, you can close the issue.
