### ISSUE TITLE
api.at warn Unable to map [u8; 32] to a lookup index

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#5871]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

We are recently update to v11, and we found decorated method `api.at` will throw warning, this flood so all other logs within our app, it also lead other logs monitoring app crashes.

To reproduce this: 

```
const { ApiPromise, WsProvider } = require(`@polkadot/api`)
const provider = new WsProvider('wss://rpc-polkadot.luckyfriday.io');


async function main(){
    const api = await ApiPromise.create({provider});
    // block height 38565
    const apiAt = await api.at('0xad17bc48645d34fb7e7109f047d027d7db21cfda17e4bade2007a247e47f7c79');
}

main().catch(e=>process.exit(1));

```
this should warn

```
Unable to map [u8; 32] to a lookup index
```

* **What is the motivation for changing the behavior?**

Improved logging

* **Please tell us about your environment:**

  - Version: 11.0.2
  - Environment: 

    - [x] Node.js v18.17.1
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
rel: https://github.com/polkadot-js/api/pull/5764

I will have this on the project board queue, but I don't see much that can be done to resolve this. At best we can switch the type of logging so that it can be turned off and or reduced.

**Comment by TarikGul** [comment]
Closing as any additional changes the to logging here wont change - I did general testing across sidecar and saw only limited logging per runtime across polkadot and kusama.
