### ISSUE TITLE
`api.derive.accounts.identity` broken ? | People Chain

### ISSUE THREAD

**Issue by ironoa** [polkadot-js/api#5883]
being connected with the new People chain (i.e. `wss://kusama-people-rpc.polkadot.io`):
- `api.derive.accounts.hasIdentity` seems to be working properly 
<img width="480" alt="image" src="https://github.com/polkadot-js/api/assets/25957738/7b82822c-77b8-455e-9c14-ee319f155d0e">

- `api.derive.accounts.identity` seems not and fails 
<img width="480" alt="image" src="https://github.com/polkadot-js/api/assets/25957738/78557c4b-5d97-4af2-83cc-e11adadcaec0">

- Tested with account `GaK38GT7LmgCpRSTRdDC2LeiMaV9TJmx8NmQcb9L3cJ3fyX`

**Comment by TarikGul** [comment]
Okay, i see the immediate problem with this. I just fixed something similar in: https://github.com/polkadot-js/apps/pull/10581

Basically the types have changes within the People chains - for `api.query.identity.identityOf` which is causing some big compatibility issues. I'll have this fixed tomorrow, and it will be part of next weeks release cycle.
