### ISSUE TITLE
Polkadot xcm type cannot be parsed (Bifrost chain)

### ISSUE THREAD

**Issue by hqwangningbo** [polkadot-js/api#5887]
```ts
    const wsProvider = new WsProvider("wss://hk.p.bifrost-rpc.liebi.com/ws");
    const parachain_api =  await ApiPromise.create({ provider: wsProvider });

    const result = await parachain_api.query.polkadotXcm.queries(0);
    console.log(result.toString()) // {"versionNotifier":{"origin":{"v2":{"parents":1,"interior":{"here":null}}},"isActive":true}}
    const result1 = await parachain_api.query.polkadotXcm.queries(1);
    // error: Error: Unable to decode storage polkadotXcm.queries
```

full logs:
Error: Unable to decode storage polkadotXcm.queries: entry 0:: createType(PalletXcmQueryStatus):: {"_enum":{"Pending":"{\"responder\":\"XcmVersionedMultiLocation\",\"maybeMatchQuerier\":\"Option<XcmVersionedMultiLocation>\",\"maybeNotify\":\"Option<(u8,u8)>\",\"timeout\":\"u32\"}","VersionNotifier":"{\"origin\":\"XcmVersionedMultiLocation\",\"isActive\":\"bool\"}","Ready":"{\"response\":\"XcmVersionedResponse\",\"at\":\"u32\"}"}}:: Decoded input doesn't match input, received 0x0001010000e0d80900 (9 bytes), created 0x000101000001d80900000000 (12 bytes)

**Comment by TarikGul** [comment]
Looks to be an issue with the provided types. Is `PalletXcmQueryStatus` a Bifrost speciifc type?

**Comment by hqwangningbo** [comment]
Since polkadotXcm is maintained by the polkadot sdk, I didn't pay attention to it, but just stumbled upon this problem

**Comment by TarikGul** [comment]
Thanks, I'll have a look into this and see if It can be resolved today!

**Comment by TarikGul** [comment]
Sorry for the delay initially I wasn't able to get this resolved, then a lot of high priority issues have come my way. Is this still an issue for you?

**Comment by hqwangningbo** [comment]
We've removed the error data using Sudo, so far no problem.
