### ISSUE TITLE
Error balances.transferKeepAlive createType(ExtrinsicSignature):: Expected input with 65 bytes (520 bits), found 66 bytes Issue with transferring GLMRs on the JS wallet

### ISSUE THREAD

**Issue by BalieiroX** [polkadot-js/api#5895]
I'm trying to transfer some GLMR tokens from Polkadot.js to another wallet and I am keep getting this error:

balances.transferKeepAlive createType(ExtrinsicSignature):: Expected input with 65 bytes (520 bits), found 66 bytes

What should I do ?

thanks

**Comment by TarikGul** [comment]
There is an issue template for a reason, please fill it out.

**Comment by BalieiroX** [comment]
> There is an issue template for a reason, please fill it out.

Its my fist time using this github. I'II close this issue and open other with the template.
