### ISSUE TITLE
Unable to do Moobeam token Tranfer from Polkadot Substrate Portal 

### ISSUE THREAD

**Issue by BalieiroX** [polkadot-js/api#5898]
* **I'm submitting a Issue **

  - [ ] Bug report
  - [ ] Feature request
  - [X ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

 I belive its a bug just as described above.

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [ X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
Rel: https://github.com/polkadot-js/api/issues/5895

The lack of info alone is enough for me to close this issue and consider it spam. In addition if this is a browser issue it should be reported in the right place such as Apps.
