### ISSUE TITLE
1010:Invalid Transaction:Transaction has a bad signature

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/api#5907]
I got this error when transfer KSM with the @polkadot/api v11.2.1 lib, and sign with  @polkadot/types v11.2.1

```
    let transfer = api.tx.balances.transferAllowDeath(BOB, 1);
    let signedHex = transfer.sign(pair, {era:0, runtimeVersion: { specVersion:runtime.specVersion, transactionVersion:runtime.transactionVersion}}).toHex()
//broadcast the signedHex
```
And pair can be any random one, I had never got this error before, could you please help me with this? Thanks a lot

**Comment by csquan** [comment]
same too,any solutions?

**Comment by TarikGul** [comment]
On Kusama the `CheckMetadataHash` signed extension was added which acted as a breaking change. Support for it has been added to the api in 11.1.1 - That being said, I have been able to successfully send transactions in Kusama, but I can double check using `.sign`

**Comment by TarikGul** [comment]
Try adding `mode: 0` to the signerOptions at the end.

**Comment by csquan** [comment]
how to adding mode: 0 to the signerOptions?

**Comment by csquan** [comment]
seems add field metadataHash and mode in payload，but I do not test it .

**Comment by TarikGul** [comment]
Yea you just need to add `mode: 0` to the `signerOptions` which is just a options object at the end of `sign`

**Comment by malingzhao** [comment]
const provider = new WsProvider('wss://kusama-rpc.polkadot.io');
    const api = await ApiPromise.create({ provider });
    console.log("the address is =========")
    console.log(sender.address)
    // Estimate the fees as RuntimeDispatchInfo using the signer
    const info = await api.tx.balances.transferAllowDeath("F7B8Hd9LrEyeLFdcXnf81NcNH75W4UobQ81viZBVTVFsRhK", 1).signAndSend(sender, {mode:0})

v11.3.1 how does the err resolve

**Comment by Wangmmx** [comment]
I have no idea why got this error after adding the mode:0 to sign function, at last  I solved it without using this sdk, create it offline and sign it in local environment, and also the signerPayload need add {mode:0, metadataHash:''}, and send it online

**Comment by malingzhao** [comment]
what's your version

**Comment by malingzhao** [comment]
ok
