### ISSUE TITLE
withClaimedRewardsEras, rate limit exceeded

### ISSUE THREAD

**Issue by ironoa** [polkadot-js/api#5923]
related to https://github.com/polkadot-js/api/issues/5859

```
api.derive.staking.query(validatorAddress,{withLedger:true, withClaimedRewardsEras: true})
```

seems to be so heavy that I get a `RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: -32999: RPC rate limit exceeded` error message when I'm connected to a public endpoint. Kusama node (v1.13.0).

- If I set `withClaimedRewardsEras: false` it works on a Kusama public endpoint (i.e. wss://kusama-rpc.polkadot.io/), but of course I'm missing info
- I can get past to this issue when I'm connected to my internal node, `withClaimedRewardsEras: true`, but still it takes roughly 13 seconds for 1 address
- Polkadot doesn't seem to have the same issue: I can make the query with `withClaimedRewardsEras: true` set on internal and public endpoints with no problems

Not sure that's expected, so I'm opening this issue...

**Comment by TarikGul** [comment]
> seems to be so heavy that I get a RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: -32999: RPC rate limit exceeded error message when I'm connected to a public endpoint. Kusama node (v1.13.0).

As you mentioned I would imagine this is directly related to the public node you are connected to. For all the heavy calls we are using entries to get everything at once so there is no limit hit. Have you tried with other Kusama public nodes?

**Comment by TarikGul** [comment]
I haven't been able to reproduce with any of the versions that contain the following:

https://github.com/polkadot-js/api/blob/64e30dd0a70cf98d4d243c1dd3d78681b5f3566a/packages/api-derive/src/staking/query.ts#L161-L162

Closing for now, feel free to reopen if the issue persists.
