### ISSUE TITLE
`api.query.identity` Works for Polkadot Chain but Returns Nothing for Kusama

### ISSUE THREAD

**Issue by Anastasiia-Khab** [polkadot-js/api#5925]
I've encountered an issue where `api.query.identity` functions as expected for the _**Polkadot chain**_ but returns **nothing** when used with the _**Kusama chain**_.

In the repository the _**identity**_ query setup in `api/packages/api-augment/src/kusama/query.ts` appears to be consistent with the corresponding file for Polkadot `api/packages/api-augment/src/polkadot/query.ts`

  - [ ] Bug report
  - [ ] Feature request
  - [X] Support request
  - [ ] Other

* **Current behavior**

**Polkadot Chain**: `api.query.identity` returns expected data.
**Kusama Chain**: `api.query.identity` does not return any data.

  - Version: @polkadot/api@12.0.2
  - Environment:

    - [ ] Node.js
    - [ ] Browser
    - [X] Other (Deno)

  - Language:

    - [X] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
This is because all the identities have been moved on Kusama from the relay chain to the Peoples chain, this transition has not been made for Polkadot yet. 

The one issue here is I could update the augmented types and the identity pallet should disappear for kusama.
