### ISSUE TITLE
Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [1, 7]/[1,7]

### ISSUE THREAD

**Issue by xuetong6** [polkadot-js/api#5930]
the code:
```
let blockHash = await polapi.rpc.chain.getBlockHash(_blockNum);
let block = await polapi.rpc.chain.getBlock(blockHash);
let allRecords = await polapi.query.system.events.at(block.block.header.hash);
```
number:21468174
Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [1, 7]/[1,7]

number:21468749
Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.killStorage:: Struct: failed on args: {\"keys\":\"Vec<Bytes>\"}:: decodeU8aStruct: failed at 0x03002326d02252ce7447206b042b59b4… on keys (index 1/1): Vec<Bytes>:: Vec length 3492160256 exceeds 65536

version:  "@polkadot/api": "^9.14.2", 
const wsProvider = new DotObj.WsProvider('wss://rpc.polkadot.io');

so how to solve this problem,  thank you.

**Comment by TarikGul** [comment]
> so how to solve this problem, thank you.

Have you tried updating the API version to latest?

**Comment by xuetong6** [comment]
"@polkadot/api": "^9.14.2", latest
The wallet node is also the latest

**Comment by TarikGul** [comment]
> "@polkadot/api": "^9.14.2", latest

This is not latesst we are on: 12.0.2

**Comment by xuetong6** [comment]
> > "@polkadot/api": "^9.14.2", 最新
> 
> 这不是我们最新的：12.0.2

Thank you, it has been resolved
It's because the API version is too low
