### ISSUE TITLE
Cannot read properties of undefined (reading 'toHuman')

### ISSUE THREAD

**Issue by ioannist** [polkadot-js/api#5933]
This still fails for me in 12.1.1

https://github.com/polkadot-js/api/issues/5875

**Comment by TarikGul** [comment]
The same reproducible you wrote can reproduce this right? I'll check it again.

**Comment by ioannist** [comment]
> The same reproducible you wrote can reproduce this right? I'll check it again.

yeap, i ran it locally with 12.1.1; hope i didn't mess up the versions :-P

**Comment by TarikGul** [comment]
No worries I'll have this checked out, hopefully a simple fix 🤞

**Comment by TarikGul** [comment]
Fixed, will release this shortly as a patch
