### ISSUE TITLE
Pack `assetId` as `HexString` in `SignerPayloadJSON`

### ISSUE THREAD

**Issue by carlosala** [polkadot-js/api#5965]
* **I'm submitting a ...**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

The interaction between a decentralized application (dApp) and a Polkadot.js (PJS) wallet extension is facilitated through a [`SignerPayloadJSON`](https://github.com/polkadot-js/api/blob/25ab1d123975a5e25c93de2f2380fe9b321d66eb/packages/types/src/types/extrinsic.ts#L32-L113) object. This object specifies the call data (`method`) and the necessary signed extensions required to reconstruct the extrinsic within the wallet. However, this process presents several challenges:

- The interface of this object is heavily tailored to the conventions used by PJS. For instance, numbers are transmitted as `HexString` and encoded in big-endian format, whereas the broader Substrate ecosystem typically uses little-endian encoding (Simple Concatenated Aggregate Little Endian, or SCALE).
- It lacks flexibility for incorporating new signed extensions.

Given these factors, developing a wallet that does not use the PJS Registry but remains compatible with PJS-based dApps is challenging and involves significant friction. A major issue arises when `assetId` is included in a transaction; it is [formatted as a JSON object](https://github.com/polkadot-js/api/blob/25ab1d123975a5e25c93de2f2380fe9b321d66eb/packages/types/src/extrinsic/SignerPayload.ts#L162) according to PJS's specific structure.

Ideally, `assetId` should be transmitted as a `HexString` using the SCALE encoding expected by the chain. This approach is compatible with current extensions, as PJS Types can handle the encoded format when constructing the types, and would simplify massively the development of new wallets outside of the PJS Registry world.

NB: _ideally all signed extensions should be sent with its SCALE encoding defined in the metadata_

**Comment by TarikGul** [comment]
> Ideally, assetId should be transmitted as a HexString using the SCALE encoding expected by the chain. This approach is compatible with current extensions, as PJS Types can handle the encoded format when constructing the types, and would simplify massively the development of new wallets outside of the PJS Registry world.

Works for me! This totally makes sense - I'll try to get something up soon so it can be released on Sunday into Monday!

**Comment by carlosala** [comment]
Wow, such a fast response. Thanks for your hard word Tarik! 😉
