### ISSUE TITLE
The operation couldn’t be completed

### ISSUE THREAD

**Issue by mehakdeep1898** [polkadot-js/api#5973]
- [X] Bug report
  - [X] Support request

* **What is the current behavior and expected behavior?**
I'm requesting with the wss://westend-rpc.polkadot.io node endpoint for the websocket; however, I'm not able to establish a connection with the endpoint.

Current Behavior:
I'm trying to retrieve the api through inputting the wss://westend-rpc.polkadot.io endpoint into the websocket. However, it returns this message:   API-WS: disconnected from wss://westend-rpc.polkadot.io: 1006:: The operation couldn’t be completed. (OSStatus error -9836.)

while running on android it is connected but giving issue in ios.

Expected Behavior:
Establish a connection with the wss://westend-rpc.polkadot.io node endpoint.

* ** What is the motivation for changing the behavior?**
Currently, I'm trying to establish a connection, and retrieve data. However, I cannot go to the next step, due to this issue.

![Screenshot 2024-09-06 at 3 28 13 PM](https://github.com/user-attachments/assets/7c7e31d4-3435-43bc-bc3d-2df8ca7e32e7)

![Screenshot 2024-09-06 at 3 29 14 PM](https://github.com/user-attachments/assets/1434ac18-db18-4713-a549-c8d42caca338)

* **Please tell us about your environment:**

    "@polkadot/api": "^12.4.2",
    "react": "18.3.1",
    "react-native": "0.75.2",
    
  - Version:
  - Environment:
    
    React-native

  - Language:

    - [X] TypeScript (include tsc --version)

**Comment by TarikGul** [comment]
under `const api = ...`

could you try `await api.isReady`.

**Comment by TarikGul** [comment]
React native has always posed issues with the PJS libraries, and is not tested on with it's maintainers and/or is a target framework. 

Closing for now since there is no response.
