### ISSUE TITLE
Validators missing from `api.derive.staking.electedInfo`

### ISSUE THREAD

**Issue by youPickItUp** [polkadot-js/api#6004]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Currently, validators without other nominators aren't returned from `api.derive.staking.electedInfo` as `nextElected`.
Expectedly, validators without other nominators should be returned from `api.derive.staking.electedInfo` as `nextElected`.

https://github.com/polkadot-js/api/blob/5c0fe9b34b3d2748deb51d260ad938e0d7d83620/packages/api-derive/src/staking/validators.ts#L19

`erasStakersPaged` contains only validators being nominated by others.

* **What is the motivation for changing the behavior?**

I think this is the correct behavior, I'd be glad to stand corrected.

* **Please tell us about your environment:**

  - Version: 13.2.1, but master seems to have the same issue
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by TarikGul** [comment]
> erasStakersPaged contains only validators being nominated by others.

It's been a while since I looked at the rust code for this, but this very well could be correct. I am just not sure what call this would be replaced by but I will have a look!

**Comment by youPickItUp** [comment]
I think it should be `erasStakersOverview`

**Comment by TarikGul** [comment]
> I think it should be `erasStakersOverview`

Yea I agree, I'll get a PR up shortly.
