### ISSUE TITLE
Unable to sign a transaction when using Ledger + Talisman Wallet

### ISSUE THREAD

**Issue by elilambnz** [polkadot-js/api#6006]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Current behavior:
When attempting to sign a transaction using a Ledger device with the Talisman wallet, the following error occurs: "This dapp needs to be updated in order to support Ledger signing."

<img width="408" alt="Screenshot 2024-10-24 at 6 39 45 AM" src="https://github.com/user-attachments/assets/b2baec7a-e45d-4424-8c9f-b28ac6447330">

I'm using the `signAndSend` method, passing an injected account from the extension.

Expected behavior:
The transaction should be successfully signed using the Ledger device through the Talisman wallet without any errors. The transaction signing works as expected when using the Bittensor Wallet browser extension.

* **Please tell us about your environment:**

  - Version:
      - @polkadot/api: 14.1.1
      - @polkadot/extension-dapp: 0.54.1
      - macOS 15.0.1
 
 - Environment:
    - [ ] Node.js
    - [x] Browser
        - Browser name and version: Google Chrome Version 130.0.6723.70 (Official Build) (arm64)
    - [ ] Other (limited support for other environments)

  - Language:
    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
      - TypeScript version: 5.6.3
    - [ ] Other

**Comment by TarikGul** [comment]
Do you have some code you can point to, or a reproducible example since this is hard to trouble shoot just based on the above (This seems very specific to what you are building).

**Comment by elilambnz** [comment]
I don't have a reproducible example, but I can share a minimum code sample of how the transaction is created:

```tsx
async function registerHotkey(api: ApiPromise, data: { coldkey: string, hotkey: string, netUid: number }) {
  const { coldkey, hotkey, netUid } = data;
  const injector = await web3FromAddress(coldkey);

  const extrinsic = api.tx.subtensorModule.burnedRegister(netUid, hotkey);

  return new Promise<void>((resolve, reject) => {
    extrinsic
      .signAndSend(
        coldkey,
        { signer: injector.signer },
        ({ status, dispatchError }) => {
          if (dispatchError) {
            if (dispatchError.isModule) {
              const decoded = api.registry.findMetaError(dispatchError.asModule);
              reject(new Error(`${decoded.section}.${decoded.name}`));
            } else {
              reject(new Error(dispatchError.toString()));
            }
          }

          if (status.isFinalized) {
            resolve();
          } else if (status.isInvalid || status.isDropped || status.isUsurped) {
            reject(new Error(`Transaction failed with status: ${status.type}`));
          }
        }
      )
      .catch(error => {
        console.error('Transaction failed:', error);
        reject(error);
      });
  });
}
```

The transaction is able to be signed by the Bittensor wallet extension, but seems to hit this error condition in the Talisman wallet: https://github.com/TalismanSociety/talisman/blob/8474c5db5335b8e004ae1248ca8f6394b93d6b28/apps/extension/src/ui/domains/Sign/SignLedgerSubstrateGeneric.tsx#L108

I'm unsure if I'm supposed to add `withSignedTransaction: true` to the `signAndSend` options.

Is this an issue on the Talisman side? If so, I can create an issue over there instead.

**Comment by TarikGul** [comment]
The following on `withSignedTransaction` can be found in [12.0.2](https://github.com/polkadot-js/api/releases/tag/v12.0.2). `withSignedTransaction` will enable the use of the `CheckMetadataHash` signedExtension. I am almost positive talisman supports and or uses that. I would file an issue with them as well to ensure but that may be your issue.

**Comment by elilambnz** [comment]
Thank you for your help with this issue. After passing the `withSignedTransaction` option to `signAndSend`, I no longer run into the error with the Talisman wallet.
