### ISSUE TITLE
DryRunApi implementation doesn't seem to work properly

### ISSUE THREAD

**Issue by HmFlashy** [polkadot-js/api#6041]
Issue type:

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

I saw that some time ago the dryRunApi has been implemented to be able to calculate fees for both extrinsic and XCMs. 
I am trying to use this API using polkadot js library but I can't make it work.

I am getting this error:

> No signer specified, either via api.setSigner or via sign options. You possibly need to pass through an explicit keypair for the origin so it can be used for signing.

```
const crossChainSendPayload: any = this.getCrossChainSendPayload(data.toAddress, amount, data.parachainId);
const extrinsicPayload = api.tx[xcmPallet][method](...Object.values(crossChainSendPayload));
const dryRunResult = await extrinsicPayload.dryRun(address);
```

Or 
This error:
![image](https://github.com/user-attachments/assets/dd21d2c7-2f4e-41ba-907c-26ddc1374b14)
with this code

```
const crossChainSendPayload: any = this.getCrossChainSendPayload(data.toAddress, amount, data.parachainId);
const extrinsicPayload = node.tx[xcmPallet][method](...Object.values(crossChainSendPayload));
const call = node.createType('RuntimeCall', extrinsicPayload.method.toHex());

const result = await node.call.dryRunApi.dryRunCall({
    system: { signed: decodeAddress(address) },
}, extrinsicPayload.method.toHex());
```

I have seen the implementation [here](https://github.com/polkadot-js/api/blob/42b9735c32671e4fac2a5b78283a7fcdec9ef912/packages/api/src/submittable/createClass.ts#L117-L136), either we need to set a blockhash or a signer. But isn't it possible to dry run without a signer and blockhash ? By just giving an address it should be enough right ? 

We need to calculate the fees for both XCM and basic extrinsic so we need this call to make it consistantly working.
Thanks

  - Version: 
  - Environment:

    - [x] Node.js v20.10.0
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript 5.4.5
    - [ ] Other

**Comment by TarikGul** [comment]
What version of the API are you using?

**Comment by TarikGul** [comment]
Hey so after some quick sanity checks everything works, i'll explain the mistake above - (I understand the confusion though).

The `SubmittableExtrinsic.dryRun` uses the system::dryRun rpc call, which is different from the `dryRunApi` call. The `SubmittableExtrinsic.dryRun` call requires the parameter to be a valid `KeyringPair`. This can be seen [here](https://github.com/polkadot-js/api/blob/master/packages/api/src/submittable/createClass.ts#L258-L260).

If you want to use the new `dryRunApi` calls you need to call them separately. That would look like:

```typescript
const extrinsic = api.tx[xcmPallet][method](...Object.values(crossChainSendPayload));
// Origin can be defined by https://github.com/polkadot-js/api/blob/master/packages/types-augment/src/lookup/types-kusama.ts#L24-L35
const dryRunResult = await api.call.dryRunApi.dryRunCall(<origin>, extrinsic.method);
console.log(dryRunResult)

// Conversely for xcm calls
const dryRunResult = await api.call.dryRunApi.dryRunXcm(<origin_location>, <xcm>);
```

**Comment by TarikGul** [comment]
Let me know if anything isn't clear.

**Comment by HmFlashy** [comment]
Thanks a lot for your answer, indeed much clearer and working like a charm !
Now I got another issue, it seems this endpoint doesn't work on assethub westend. Looks like the result can't be decoded by westend metadata
```
Caught unknown error: createType(Result\u003cCallDryRunEffects, XcmDryRunApiError\u003e):: decodeU8aStruct: failed at 0x031f02000000000000… on localXcm (index 3/4): Option\u003cVersionedXcm\u003e:: Unable to create Enum via index 31, in V0, V1, V2, V3, V4
```

**Comment by HmFlashy** [comment]
And we are using last version 15.0.1

**Comment by HmFlashy** [comment]
@TarikGul Do you have an idea why ?

**Comment by HmFlashy** [comment]
We can see here when selecting xcmPaymentApi; this [endpoint](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs#L1577C6-L1577C25) is missing 
And if you go into dryRunApi and enter a correct payload you will get same error as me above

**Comment by TarikGul** [comment]
> Thanks a lot for your answer, indeed much clearer and working like a charm ! Now I got another issue, it seems this endpoint doesn't work on assethub westend. Looks like the result can't be decoded by westend assethub metadata
> 
> ```
> Caught unknown error: createType(Result\u003cCallDryRunEffects, XcmDryRunApiError\u003e):: decodeU8aStruct: failed at 0x031f02000000000000… on localXcm (index 3/4): Option\u003cVersionedXcm\u003e:: Unable to create Enum via index 31, in V0, V1, V2, V3, V4
> ```

I am not really sure what the actual issue is here: Any chance can share the input params you are passing so I can do some testing.

> We can see [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsys.ibp.network%2Fasset-hub-westend#/runtime) when selecting xcmPaymentApi; this [endpoint](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs#L1577C6-L1577C25) is missing
And if you go into dryRunApi, select dryRunCall and enter a correct payload you will get same error as me above for a XCM message

I was seeing some odd behavior just now with the metadata versions which could be affecting the way the api initializes which could affect the runtime apis. Looking into this now.

ex: `metadataVersionsAt`

```
1: metadata.metadataVersions: Vec<u32>
[
  14
  15
  4,294,967,295
]
```

**Comment by HmFlashy** [comment]
Here is the call I am making in hex
0x1f090301000300010100e9251828c80479f5fde8b6d50863a739b9422b58925abf440768e6d1ec1d16cd0304000000000700e87648170000000000

**Comment by HmFlashy** [comment]
What is weird is, it is correctly decoded [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsys.ibp.network%2Fasset-hub-westend#/extrinsics/decode) so it means the message is ok, but the result is wrongly decoded

**Comment by HmFlashy** [comment]
But it works in kusama and polkadot

**Comment by TarikGul** [comment]
> Here is the call I am making in hex 0x1f090301000300010100e9251828c80479f5fde8b6d50863a739b9422b58925abf440768e6d1ec1d16cd0304000000000700e87648170000000000

Thank you!

> What is weird is, it is correctly decoded [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsys.ibp.network%2Fasset-hub-westend#/extrinsics/decode) so it means the message is ok, but if you use this call inside the dryRunApi dryRunCall, the result is wrongly decoded

There could have been a recent runtime upgrade as well which is causing this issue in westend. I remember hearing about some upgrades in westend to fix some things with v4, and potentially introduce v5. I could be wrong here but that could very well be it as well.

**Comment by HmFlashy** [comment]
when will it be fixed then ? We would need it to work in our testnet environment

**Comment by TarikGul** [comment]
Not sure. I still don't know the exact source of the issue. I asked internally, and will update here with answers. If its working correctly in polkadot and kusama through PJS but not in westend assethub I would say its safe to assume there is an issue with the runtime, but I can't say for certain.

**Comment by TarikGul** [comment]
In terms of `query_delivery_fees` not showing up I am looking into that. That might be a PJS issue.

**Comment by TarikGul** [comment]
Okay good news I found an issue locally with the metadataVersions - lets see if it fixes how the types are being resolved.

**Comment by TarikGul** [comment]
Okay so I have a fix for the `queryDeliveryFees` missing!

**Comment by TarikGul** [comment]
Okay so I got a fix that also fixes the call. The execution still fails that being said I let the correct individual know of the error and they are looking into it. 

That being said, the above PR fixes the actual call and types itself.

**Comment by TarikGul** [comment]
Fix is active in: https://github.com/polkadot-js/api/releases/tag/v15.0.2

**Comment by HmFlashy** [comment]
Thanks a lot for your time and effort, will check if it is working asap

**Comment by franciscoaguirre** [comment]
The reason the call doesn't work is you're specifying `{ parents: 0, interior: Here }` in the assets to teleport when you're on Asset Hub. It should be `{ parents: 1, interior: Here }`. WND is always identified by the relative location of the Westend Relay Chain. The same also happens with KSM and DOT on system parachains.

**Comment by HmFlashy** [comment]
Yes thanks! I realised that.
Btw  @franciscoaguirre @TarikGul, is there a way to generically call any endpoint which handles different versions for a parameter ?
For example:
queryWeightToAssetFee on Westend assethub as V5 for asset but Kusama assethub has only V4. 
Should I manage each network independently ? It looks like a lot of work to maintain
