### ISSUE TITLE
No easy / clean way to close ws connection and showdown Api object

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#661]
This prevents to node.js program exit cleanly because there is no disconnect / close method so `process.exit` have to be used.

`WSProviderInterface` should have a `disconnect` method to close ws connection

In additional to that, I think following changes can be helpful (not very confident so feel free to ignore those suggestions)

Move `connect` method to `ProviderInterface` and have `disconnect` on there as well

Add `open` and `close` to `ApiBase` method which does connect & setup and disconnect & teardown.

----

Current we are using `provider.websocket.close()` which logs 

```
API-WS: disconnected from ws://127.0.0.1:9944::1000: Normal connection closure
```

**Comment by jacogr** [comment]
Yes. Certainly an oversight.

I believe both needs to be in place - would just prioritise the shutdown before exposing the open explicitly. 

 (With the calling of metadata and setup on open it is a bit more involved to het 100%)
