### ISSUE TITLE
How to add custom derives?

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#667]
I can't find a way to add custom derives without forking this repo. It will be good if this is extensible.

The real issue I am having is that we have implemented a generic asset module using `StorageDoubleMap` which there are no metadata support (https://github.com/paritytech/substrate/issues/1715), so I want to implements the query manually. I can do it via rpc calls but can't find a good way to bind this with UI and everything seems very tacky to me.

**Comment by jacogr** [comment]
I think we can inject these on API creation via options? Either into derive or into “custome/ext/...”. Can follow the same pattern as the derive methods. (It is just functions)

**Comment by xlc** [comment]
Yes. A new `derive` option will be good. I am also thinking to to use it to override existing derives such as `balances.fees` to support custom fee calculation without changing too much on the apps

**Comment by jacogr** [comment]
If nobody grabs this before Tue, I'll try to get something basic in as a v1.

**Comment by jacogr** [comment]
Sorry, slightly delayed on this due to schnorrkel support - "Tue" didn't end up as "Tue".
