### ISSUE TITLE
Parametrized enums should display type + value via toString()

### ISSUE THREAD

**Issue by siman** [polkadot-js/api#680]
Currently, if the storage returns a value that is a parametrized enum, only a name of this enum is displayed. I have tested this on an enum `ElectionStage` from this example: https://github.com/polkadot-js/api/issues/679#issuecomment-462337798

**Comment by jacogr** [comment]
Basically it displays it via `toString()` which just returns the type, not via `toJSON()` which returns the full thing. Expanded in https://github.com/polkadot-js/api/pull/681/commits/b23c5ef8fee3f36c128c5cfdb4bf272b8d0fb431
