### ISSUE TITLE
Allow custom Extrinsic implementation

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#738]
Several changes required so that we can use TypeRegistry to replace the default Extrinsic.
1. priority changes: TypeRegistry should have higher priority than default implementation.
2. A Extrinsic interface.
2. SubmittableExtrinsic: change to have a _extrinsic member instead of extends directly.

**Comment by jacogr** [comment]
Discussed in https://github.com/polkadot-js/api/issues/614

**Comment by jacogr** [comment]
Closed in #739
