### ISSUE TITLE
HttpProvider doesn't work with ApiPromise

### ISSUE THREAD

**Issue by tjwelde** [polkadot-js/api#741]
The documentation of HttpProvider states, that it could be used with the `ApiPromise`.
Trying this, we get the error: `Api can only be used with a provider supporting subscriptions`, which is fired by `@polkadot/api/Base.js:101`

https://github.com/polkadot-js/api/blob/879fa28d0d0e32d6de5785352f66a938adb26c76/packages/rpc-provider/src/http/index.ts#L33

How is the HttpProvider supposed to work?

**Comment by jacogr** [comment]
It is a documentation issue. (Actually currently in the process of cleaning that up).

Since HTTP does not have subscriptions (which _could_ be emulated - there is an issue logged around that), it is actually not supported atm.

**Comment by tjwelde** [comment]
Ok, so the support of HttpProvider in ApiPromise was dropped?
Because HttpProvider already handles non-existing subscriptions: https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/http/index.ts#L117, which seems like a better approach, than forbidding it in ApiPromise completly

**Comment by jacogr** [comment]
The issue is that using it currently (dummy subs) means all the following breaks -

- storage subscriptions
- derived interfaces
- any query or RPC with a callback
- sign/send (api.tx - with callback)

**Comment by jacogr** [comment]
PS (to the above): Would like to resurrect it, but really struggling to see the actual benefits when WS also operates over HTTP. Apart from that, it is a matter of effort to get it operational with some sort of sane fallback for the bulk of the API interfaces. 

(Substrate is exceptionally subscription-heavy, as soon as you start doing anything that is not just "get me the chain name", especially when dealing with transactions and storage, getting sane up-to-date info is better suited to provider layer where the client and node works together to keep updated)

**Comment by beykery** [comment]
if i do not want subscribe any events , can i sign and send extrinsics with  HttpProvider ?
how ?

**Comment by PercivalZhang** [comment]
when HttpProvider supports subscribe or this feature has been dropped from HttpProvider ?

**Comment by jacogr** [comment]
Since HTTP is not bi-directional, providing subscriptions means long-polling - this is one of those features that would be done "one day where is there some time and nothing else in the queue".

It certainly is possible to provide an exceptionally limited API -

- no storage queries
- only constants
- only (some) RPCs using HTTP

At this point the above is not planned, but would certainly accept PRs in this regard.
