### ISSUE TITLE
How to create and submit a mortal transaction?

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#756]
Could you provide some examples of how to create and submit a mortal transaction? e.g. I want this transaction expire after block 10000 or after 100 blocks from current height

All I can found is [ExtrinsicEra](https://github.com/polkadot-js/api/blob/master/packages/types/src/type/ExtrinsicEra.ts) which requires me to construct the details from bytes. It should provide helper methods to construct `ExtrinsicEra` from block number.

I did found this https://github.com/paritytech/wiki/blob/master/Extrinsic.md#transaction-era
I can try to understand the algorithm and implement the encode method but it will be good if it is done by someone already knows how to do it.

**Comment by jacogr** [comment]
Both an enhancement and documentation -

- documentation: show how to submit the blockHash
- enhancement: provide the getters on ExtrinsicEra, encode fully (partly implemented)

**Comment by jacogr** [comment]
Keep https://github.com/polkadot-js/api/issues/778 in mind - specify the era as part of `signAndSend` (if not already 100% clear based on the above discussions)

**Comment by jacogr** [comment]
Mortals supported since https://github.com/polkadot-js/api/pull/927 - changing labels to reflect documentation and samples.

**Comment by kushptlapigarage** [comment]
This will be useful to apps me and my team building.

**Comment by jacogr** [comment]
We need to get the docs updated with samples. Eras have been supported since #927 (we wish to swap it to the default at some point, not the next stable, but most probably the one after)

**Comment by kushptlapigarage** [comment]
Thanks for the response.

We used [this](https://github.com/polkadot-js/api/pull/927/files#diff-0ae13b274820f1e4ec131df1958a37f9R159) e2e test as base. The difficult part was calculating the fees as we show users as part Enzyme (Polkadot DApp Wallet) how much it would cost a transaction.

**Comment by jacogr** [comment]
Closing, 0.82 now both support (already available in 0.81) and uses it by default.
