### ISSUE TITLE
Error: Can't Unnominate.

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/api#766]
Finish nominate first validator `5Dn8F1SUX6SoLt1BTfKEPL5VY9wMvG1A6tEJTSCHpLsinThm`
Tested some account can't unnominate.
Tested wallet and apps same.

**Comment by jacogr** [comment]
Staking has been completely reworked in the current substrate master - this is not rolled out to the testnets yet, but in the latest substrate master and will be rolled out at some point soon. Basically going forward `stake`/`nominate` and `unstake`/`unnominate` will be replaced with `bond`/`unbond`

https://polkadot.js.org/api/METHODS_EXTRINSICS.html#extrinsics (staking)

(Busy being implemented in apps as part of https://github.com/polkadot-js/apps/issues/715)

**Comment by jiangfuyao** [comment]
Good reference: <https://hackmd.io/5Vr3CvSPS0KS8JrJN_r58A>

**Comment by jacogr** [comment]
Closing, nothing can be done on the old APIs - this is really a symptom of the old staking APIs. (Replacements have been rolled-out to Alexander)
