### ISSUE TITLE
derives in ApiPromise always return cached result

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/api#777]
if using ApiPromise, it can be easily reproduced by executing `await api.derive.chain.bestNumber()` and `(await api.rpc.chain.getHeader()).blockNumber` repeatedly.

I think the current cache solution works only for rxjs because an observable is a stream, you still can get latest from it even you hold a cached one. but for promise it's one shot thing.

when the observable is toPromised, it will be terminated after first result, makes caching it meaningless.

**Comment by ianhe8x** [comment]
i think this might work but i'm not an expert of rxjs. 
https://github.com/polkadot-js/api/blob/a74367e924f4312644f45f56b1de743a4e830539/packages/api/src/promise/Api.ts#L208
can we change `first()` into `take(2)`, since we cached the last result via `publishReplay(1)`.

**Comment by ianhe8x** [comment]
Maybe expose an uncached in api-derive for apiPromise

**Comment by jacogr** [comment]
Good catch. This is a tough one - So background: on normal queries (no derive) the caching logic only applies to non-subscriptions. And for eg. Queries the calls are adjusted based on “is it a sub or not”, for example in storage. So it pulls through and gets fresh values. 

Derive does not have this, basically always assuming subscriptions. 

Will look at your possible solution. 

@amaurymartiny thoughts?

**Comment by jacogr** [comment]
Also wondering (out loud, not much thought as to exact implications) if we need ‘ddr’ in the derives at all. 

Basically the RPC side is already ddr-ed so for actually operations on those values there is already caching up the tree. (In some cases like the account I’d mappings, this probably does make sense, for most of the others it probably doesn’t add that much)

**Comment by ianhe8x** [comment]
it's possible that one of the input stream emits new value but output keep the same, means we still need ddr.
