### ISSUE TITLE
Support parameterisable modules

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#787]
Support parameterisable modules which implemented at https://github.com/paritytech/substrate/pull/1800

**Comment by jacogr** [comment]
Not sure what additionaly needs to be done - this PR did introduce 2 breaking bugs via the changes (events stopping working altogether due to wrong indexes in metadata being one of them and the CantPay issue on random follow up txs another), but that was fixed is subsequent substrate PRs.

**Comment by xlc** [comment]
Both substrate and polkadot chain does not use parameterisable module at moment and we don't plan to use it as well.
But when someone do use it, they can for example have multiple instances of the `balances` module to create a due token chain. Then polkadot.js needs ability to fetch the free balance for different instances of the `balances` module.

I don't see this is a priority until someone is developing a chain that actually uses this feature.

**Comment by jacogr** [comment]
100%, that is exactly my reading of the impl.  as well.

**Comment by jacogr** [comment]
Closing until a real need with specific use-cases. (I am still hopeful that metadata reflection will solve all the problems in this world)
