### ISSUE TITLE
Examples are using old ed25519 seeds, update to latest sr25519 derived

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#790]
... Alternatively, just use the testing keyring, i.e. https://polkadot.js.org/api/examples/promise/06_make_transfer/ would become

```js
const { ApiPromise } = require('@polkadot/api');
const testKeyring = require('@polkadot/keyring/testingPairs').default;

async function main () {
  const api = await ApiPromise.create();
  const keyring = testingKeyring();

  // all dev keys are on this test keyring as `.bob`, `.alice`, `.eve`, etc
  await api.balances
    .transfer(keyring.bob.address(), 12345)
    .signAndSend(keyring.alice);
}
```

cc @mattrutherford

**Comment by jacogr** [comment]
... or `keyring.addFromUri('//Alice', {}, 'sr25519')` for adding the seeds (`//Bob`, `//Eve`, etc)

**Comment by mswezey23** [comment]
Note for the example:

`const keyring = new Keyring();`
should come after 
`const api = await ApiPromise.create();`

Thanks to @jacogr for the fix!
