### ISSUE TITLE
Detects if multiple version of @polkadot/types are installed and print warning

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#795]
Currently the type registry is a shared global variable. polkadot.js will fail with unclear error message when multiple versions `@polkadot/types` are installed because each version of the lib have its own type registry.

Until the type registry is been refactored to not using shared global variable, it should detects if multiple versions are installed and print a big warning message.

**Comment by jacogr** [comment]
... Not quite sure as to "how" :)

**Comment by amaurymartiny** [comment]
> ... Not quite sure as to "how" :)

Me neither... but I've seen console.logs from mobx and storybook saying "it seems there are multiple versions of mobx/storybook running, please make sure there's only one". We could have a peek there.

**Comment by Stefie** [comment]
Maybe https://www.npmjs.com/package/duplicate-package-checker-webpack-plugin ?

**Comment by jacogr** [comment]
The above is nice, but it is webpack-specific-with-config, the issue appears everywhere.

**Comment by xlc** [comment]
I remember I read MobX code years ago and it was using global veriable to detect this. 
Something like
if (globals._polkadot_types)
  console.warn()
else
  globals._polkadot_types = true

**Comment by xlc** [comment]
This is how MobX does it

https://github.com/mobxjs/mobx/blob/c4131f1f008330ecd1fc3d9c5f1603b52760a82e/src/core/globalstate.ts#L124-L135
