### ISSUE TITLE
Keep alive ping

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#804]
(Please correctly me if I am mistaken)

Substrate drops the ws connection if it is idle for a minute. It will be good if there is a way to have polkadot.js sending some ping message in a configurable amount of interval (with a reasonable default) to ensure the connection is alive.

**Comment by jacogr** [comment]
Yes, it does. On the apps I'm sending a health check every 30s (I believe) to do exactly this.

Good idea to incorporate into the base.

**Comment by jiangfuyao** [comment]
Best to slove it from substrate layer. Sometime the api layer closed. The  node WS/RPC service will close too. Need restart by manual. It‘s trouble. So..Best have the substrate add parameter, set automatic close time, or set cancel automatic close.
