### ISSUE TITLE
Potential issue on double map implementation

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#819]
(I did not actually verify if this is a real issue)

https://github.com/polkadot-js/api/pull/798#discussion_r271116857

> DoubleMapType only exists in v3 so this should fail if trying to convert a metadata includes double to v2.
One way to solve this (without refactor everything to make it upgrade instead of downgrade), is duplicate DoubleMapType in v2 like how I retrofit is_linked in v1

**Comment by jacogr** [comment]
100% - the current v3 is really basic, it only "doesn't fail on parsing", the type is not actually usable as of yet.

**Comment by jacogr** [comment]
Handle as part of #776 when we get there.

**Comment by jacogr** [comment]
Closing. Since the testnets with v3 doesn't have real DoubleMaps and we will start using v4 natively as part of @amaurymartiny 's refactor. (V4 to have proper DM support in #776)
