### ISSUE TITLE
API throws InvalidSignature(0) (Bad signature) for usize function arguments. 

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/api#838]
If the function of your Substrate extrinsic contains `usize` arguments, the API seems to throw `InvalidSignature(0)` errors. Changing these to `u32` fixes the issue.

Nonetheless, these errors are caught at the API level before the extrinsics with `usize` function arguments ever touch the chain. Therefore, my intuition is the API cannot parse or serialize `usize` arguments.

**Comment by jacogr** [comment]
@amaurymartiny Would appreciate if you can take a look when you have a gap -https://github.com/polkadot-js/api/blob/master/packages/types/src/primitive/USize.ts 

(That looks innocent enough, the issue however is that it assumes u64 and usize is dependent on platform...)

**Comment by jacogr** [comment]
Seems to be u32 - https://github.com/rustwasm/wasm-bindgen/pull/1448/files#diff-ccdc0411efb64746018c8d6809af3411R86

**Comment by jacogr** [comment]
Closed in #839
