### ISSUE TITLE
Document base type functions (e.g. .eq) in a consistent manner

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#841]
```
const log = x => console.log(JSON.stringify(x, null, 2));

const { metadata } = await api.rpc.state.getMetadata();
const modules = metadata.asV3.modules;

const system = modules.find(m => m.name === 'system');
log(system);
```

This won't work because `new Text('system') === 'system'` is false.

`const system = modules.find(m => m.name.toString() === 'system');` can be used as workaround but I don't think it is good code.

**Comment by jacogr** [comment]
You should be able to use `m.name.eq('system')` (The `.eq` is exposed on all types, and generally detects different types to compare)

**Comment by jacogr** [comment]
I'm going to re-open this, and add it to docs - we need to be more clear about these things all-over, expand the docs and make sure things are 100% clear.
