### ISSUE TITLE
optimize double map first key hash

### ISSUE THREAD

**Issue by thiolliere** [polkadot-js/api#863]
https://github.com/paritytech/substrate/pull/2451

**Comment by thiolliere** [comment]
OK I'm finally not sure about the way to go we can also postponed this as it doesn't warm.

Also I don't know is this suppose to follow v1.0 or master ?

**Comment by jacogr** [comment]
API needs to support - 1.x as used by devs, testnets & master. (Which takes some juggling in some cases)
