### ISSUE TITLE
Add tests for api-derive methods

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/api#868]
None of the methods have any tests at the moment. they should gradually be added.

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
