### ISSUE TITLE
Error callback/event for API create exceptions

### ISSUE THREAD

**Issue by hugh-hoang** [polkadot-js/api#938]
Hi,

As per this, when the API failed to init, we only log to console.
[https://github.com/polkadot-js/api/blob/2ae90985345fc616408c5d3a14417a21a065f0f0/packages/api/src/Base.ts#L395](https://github.com/polkadot-js/api/blob/2ae90985345fc616408c5d3a14417a21a065f0f0/packages/api/src/Base.ts#L395)
But we would need a way to bubble this up so different UI implementation can handle it gracefully.
The WsProvider do have an .on('error') while this just dies silently.

Cheers,
Hugh

**Comment by hugh-hoang** [comment]
Sorry for reopening this and thanks for the PR but the issue probably somewhere else as well. So here is the scenario
```
api = await ApiPromise.create(provider)

// This line is never reached because the above await never come back if there was an API init exception
api.on('error', err => {
  //... Error handling
})
```

**Comment by jacogr** [comment]
You will need to `new Api()`, attach listeners and `await api.isReady` in that case - the other parsing errors are not an creation issue, rather a connection to the chain issue, so the API create should not fail/reject in that case.

**Comment by hugh-hoang** [comment]
Cool thanks and it seems working as expected.
For the background, in my work we need to upgrade the runtime that has more custom types.
And the API is failing if we don't supply the custom types in the creation, we need to catch that and feed the users.
