### ISSUE TITLE
Update dependencies in documentation examples

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/api#942]
When I go to https://polkadot.js.org/api/examples/promise/ and try and run one of the examples,
the dependencies in the package.json files are outdated (i.e. the @polkadot/api version) so for example if I run https://polkadot.js.org/api/examples/promise/10_upgrade_chain/ then I'll get an error like:
```
2019-05-22 10:37:13        RPC-CORE: getMetadata (block: Hash): Metadata:: Object.values(...)[index] is not a constructor
2019-05-22 10:37:13   API/DECORATOR: FATAL: Unable to initialize the API:  getMetadata (block: Hash): Metadata:: Object.values(...)[index] is not a constructor
```

Suggest we at least update the documentation so the user knows how to do it themselves.

And possibly also add Dependabot like we did for https://github.com/paritytech/js-libs

**Comment by jacogr** [comment]
this only gets updated as part of a release. (Which is today anyway - for the most part we don't track these on the minor bumps)

Greenkeeper doesn't track examples/* neither does depndabot.

**Comment by ltfschoen** [comment]
Noted that this commit makes our lives easier https://github.com/polkadot-js/api/pull/944
