### ISSUE TITLE
Metadata uses prefix, not name, for calls

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#947]
https://github.com/polkadot-js/api/blob/master/packages/type-extrinsics/src/fromMetadata/index.ts#L24

Basically this means if you have a module with no storage, i.e. metadata returns an empty prefix, you cannot call extrinsics.

cc @amaurymartiny

**Comment by amaurymartiny** [comment]
Agreed, should be `name`! You can change it, or I'll do it tomorrow

**Comment by jacogr** [comment]
@shawntabrizi Reported it - he was hacking about and couldn't see the extrinsics when he has no storage. So looked at the code. 

But anyway, can do it tomorrow, since I'm not updating apps tonight to pull this in.
