### ISSUE TITLE
Defer Websockte reconnect logic until after ApiPromise.create

### ISSUE THREAD

**Issue by felixSchl** [polkadot-js/api#949]
It's currently possible to end up stuck forever awaiting `ApiPromise.create` if the endpoint is not reachable as the websocket provider will continue to try to reconnect event though a connection was never established. I think we could perhaps hold off on the connection retry logic until after the api promise resolved.

**Comment by jacogr** [comment]
The providers are completely separate from the Api - this enables you to provide your own providers. If this is a real in a specific application, the suggested route is to not use the shortcuts, i.e.

- create provider - add any error handlers via `provider.on(...)`
- create API via `new Api({ provider })`
- explicitly call `isReady` based on logic

`Api.create` is the simple, non-frills approach where you don't need to worry about anything and only work with the created object once created, waiting until it does so.
