### ISSUE TITLE
Error in getRuntimeVersion method

### ISSUE THREAD

**Issue by fzzr-** [polkadot-js/api#972]
JS-Apps cannot initialize because fails in `getRuntimeVersion`.

versions:
- [js-apps](https://polkadot.js.org/apps/): api v0.80.1 / apps v0.34.0-beta.1
- [substrate](https://github.com/paritytech/substrate/commit/9687db56516ef573f650dadc030315b78d708cc4): 9687db56516ef573f650dadc030315b78d708cc4

Error: `RPC-CORE: getRuntimeVersion (hash: Hash): RuntimeVersion:: -32603: Unknown error occured Client(Ver)`

Steps to reproduce:
1. create any simple node based on Substrate rev. `9687db56516ef573f650dadc030315b78d708cc4`, run;
1. goto [apps](https://polkadot.js.org/apps/) and connect to your local node.

![Screen Shot 2019-06-05 at 18 27 03](https://user-images.githubusercontent.com/888526/58970080-62f25f80-87c1-11e9-8724-80fe6de802f7.png)

**Comment by jacogr** [comment]
Not labelling it yet, will need to look into what changed on master. (There are some other changes that needs to go in as well)

**Comment by jacogr** [comment]
As an aside, there were issues with master (fixed yesterday finally), where the `Client(Ver)` issue came up. This is returned from the node itself and indicates an error with the node binary itself, not the API.

So latest master needs #973 to be in for the new types, however depending on the commit, master may or may not work even with that.

On this morning's master, the issue does not appear -

`$ curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "state_getRuntimeVersion", "params":[]}' http://localhost:9933`

yields 

`{"jsonrpc":"2.0","result":{"apis":[["0xdf6acb689907609b",2],["0x37e397fc7c91f5e4",1],["0x40fe3ad401f8959a",3],["0xd2bc9897eed08f15",1],["0xf78b278be53f454c",1],["0xed99c5acb25eedf5",2],["0xdd718d5cc53262d4",1],["0x7801759919ee83e5",1]],"authoringVersion":10,"implName":"substrate-node","implVersion":92,"specName":"node","specVersion":92},"id":1}`
