### ISSUE TITLE
 Base.disconnect() does not work

### ISSUE THREAD

**Issue by AlexWZ0129** [polkadot-js/api#980]
Hi, I found the provider will keep re-connecting even if the [disconnect()](https://github.com/polkadot-js/api/blob/0b66f27a8c1ad28f15d6549d4a751f246398f91c/packages/api/src/Base.ts#L289) is called

**Comment by AlexWZ0129** [comment]
cannot reproduce

**Comment by AlexWZ0129** [comment]
I know what is happening here, this issue will happen only if `provider` in `ProviderInterface` is undefined.

**Comment by jacogr** [comment]
Closed in #983
